import {bettingSourceMutation691} from './bettingDomGuard691.js';

const VERSION='564.1.0';
const SNAP_STORE='kamil_betting_snapshots_545';
const AUTO_STORE='kamil_betting_autoscan_562';
const MIN_MOVE_PCT=2;

const num=v=>{const n=Number(String(v??'').replace(',','.').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null};
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
function cleanTitle(card){const strong=card.querySelector('.bet144-pickmain strong');if(!strong)return'';const clone=strong.cloneNode(true);clone.querySelectorAll('.bet560-corr,.bet564-urgency,.bet565-flag').forEach(x=>x.remove());return clone.textContent.trim().replace(/^🟢\s*/,'').replace(/\s*@\s*[0-9.,]+\s*$/,'')}
function cardInfo(card){const strong=card.querySelector('.bet144-pickmain strong');const detail=card.querySelector('.bet144-pickmain span')?.textContent?.trim()||'';const title=strong?.textContent||'';const odds=num(title.match(/@\s*([0-9]+(?:[,.][0-9]+)?)/)?.[1]);const decisions=Object.fromEntries([...card.querySelectorAll('.bet542-decision')].map(x=>[(x.querySelector('span')?.textContent||'').trim(),num(x.querySelector('b')?.textContent)]));const parts=detail.split('·').map(x=>x.trim());return{title:cleanTitle(card),event:parts[0]||detail,market:parts[1]||'',odds,minOdds:decisions['Min. kurz']}}
function matchingSnapshot(d){const snap=read(SNAP_STORE,{items:{}});const rows=Object.values(snap.items||{});const ev=d.event.toLowerCase(),title=d.title.toLowerCase();return rows.filter(r=>String(r.event||'').toLowerCase()===ev&&String(r.title||'').toLowerCase()===title).sort((a,b)=>Date.parse(b.lastSeenAt||0)-Date.parse(a.lastSeenAt||0))[0]||null}
function movement(d){const row=matchingSnapshot(d),obs=Array.isArray(row?.observations)?row.observations:[];if(!obs.length)return{count:0,first:d.odds,last:d.odds,deltaPct:0};const first=Number(obs[0]?.odds||d.odds),last=Number(obs[obs.length-1]?.odds||d.odds);return{count:obs.length,first,last,deltaPct:first?((last/first)-1)*100:0}}
function verdict(d,m){if(!d.odds)return{code:'WAIT',label:'ČEKÁM NA KURZ',level:'wait'};if(d.minOdds&&d.odds<d.minOdds)return{code:'SKIP',label:`SKIP · pod min ${d.minOdds.toFixed(2)}`,level:'bad'};const cushion=d.minOdds?((d.odds/d.minOdds)-1)*100:null;if(m.count>=2&&m.deltaPct<=-MIN_MOVE_PCT)return{code:'BET_NOW',label:`VSADIT TEĎ · kurz padá ${m.deltaPct.toFixed(1)} %`,level:'hot'};if(m.count>=2&&m.deltaPct>=MIN_MOVE_PCT)return{code:'WAIT',label:`POČKAT · kurz roste +${m.deltaPct.toFixed(1)} %`,level:'wait'};if(cushion!==null&&cushion<=2.5)return{code:'BET_NOW',label:`VSADIT TEĎ · jen ${cushion.toFixed(1)} % nad minimem`,level:'hot'};return{code:'VALUE',label:m.count>=2?'VALUE · kurz stabilní':'VALUE · sbírám pohyb',level:'ok'}}
function ensureStyles(){if(document.querySelector('style[data-bet564]'))return;const s=document.createElement('style');s.dataset.bet564='1';s.textContent=`.bet564-urgency{display:inline-flex;margin-left:7px;padding:4px 7px;border-radius:7px;font-size:8px;font-weight:900;vertical-align:middle}.bet564-urgency.ok{background:rgba(67,180,109,.10);color:#8fe0ad}.bet564-urgency.hot{background:rgba(241,144,57,.12);color:#f2b36d}.bet564-urgency.wait{background:rgba(96,165,250,.10);color:#9fc7ec}.bet564-urgency.bad{background:rgba(232,113,113,.12);color:#f2a0a0}.bet564-move{margin-top:4px;font-size:8px;color:#71899d}.bet564-auto{display:flex;justify-content:space-between;gap:8px;align-items:center;padding:7px 9px;border-radius:8px;background:rgba(135,164,194,.04);font-size:9px;color:#7f96a9}.bet564-auto b{color:#dce8f1}`;document.head.appendChild(s)}
function decorate(){const root=document.querySelector('#bettingView');if(!root)return;let blocked=0,hot=0,waiting=0;for(const card of root.querySelectorAll('.bet144-pick')){const d=cardInfo(card),m=movement(d),v=verdict(d,m);let tag=card.querySelector('.bet564-urgency');if(!tag){tag=document.createElement('span');tag.className='bet564-urgency';card.querySelector('.bet144-pickmain strong')?.appendChild(tag)}tag.className=`bet564-urgency ${v.level}`;tag.textContent=v.label;let move=card.querySelector('.bet564-move');if(!move){move=document.createElement('div');move.className='bet564-move';card.querySelector('.bet144-pickmain')?.appendChild(move)}move.textContent=m.count>=2?`Pohyb: ${m.first.toFixed(2)} → ${m.last.toFixed(2)} · ${m.deltaPct>=0?'+':''}${m.deltaPct.toFixed(1)} % · ${m.count} snapshotů`:'Pohyb: čekám na další snapshot';const btn=card.querySelector('.bet542-confirm');if(btn){if(v.code==='SKIP'){btn.disabled=true;btn.dataset.bet564Blocked='1';btn.title=`Kurz ${d.odds?.toFixed(2)} je pod minimem ${d.minOdds?.toFixed(2)}`;blocked++}else if(btn.dataset.bet564Blocked==='1'){btn.disabled=false;delete btn.dataset.bet564Blocked;btn.title=''}}if(v.code==='BET_NOW')hot++;if(v.code==='WAIT')waiting++}
 const auto=root.querySelector('[data-bet564-auto]');if(auto){const a=autoState();auto.innerHTML=`<span>Auto-scan: <b>${a.label}</b></span><span>HOT ${hot} · WAIT ${waiting} · BLOCK ${blocked}</span>`}window.__KAMIL_BETTING_TIMING564__={version:VERSION,blocked,hot,waiting,at:Date.now()}}
function budgetMode(){return window.__KAMIL_PULSE_BUDGET561__?.mode||'normal'}
function cooldown(mode){return mode==='critical'?24*3600000:mode==='economy'?12*3600000:mode==='exhausted'?Infinity:8*3600000}
function autoState(){const s=read(AUTO_STORE,{lastAt:0,lastResult:null});const mode=budgetMode(),left=Math.max(0,cooldown(mode)-(Date.now()-Number(s.lastAt||0)));return{...s,mode,left,label:mode==='exhausted'?'STOP · kvóta':left>0?`cache/cooldown ${Math.ceil(left/3600000)} h`:'připraven'}}
function ensureAutoBox(){const root=document.querySelector('#bettingView');if(!root)return;let box=root.querySelector('[data-bet564-auto]');if(!box){box=document.createElement('div');box.dataset.bet564Auto='1';box.className='bet564-auto';const anchor=root.querySelector('[data-bet561]')||root.querySelector('[data-bet560]');anchor?.insertAdjacentElement('afterend',box)}decorate()}
function maybeAutoScan(){const root=document.querySelector('#bettingView');if(!root||!document.querySelector('#view-betting.on'))return false;const btn=root.querySelector('[data-bet144-scan]');if(!btn||btn.disabled)return false;const scan=window.__KAMIL_VALUE_SCAN_144__;if(scan?.loading)return false;const a=autoState();if(a.mode==='exhausted'||a.left>0)return false;write(AUTO_STORE,{lastAt:Date.now(),lastResult:'triggered',mode:a.mode});btn.click();window.__KAMIL_BETTING_AUTOSCAN562__={version:'562.1.0',triggered:true,mode:a.mode,at:Date.now()};return true}
let timer=null;
export function installBettingTiming564(){ensureStyles();const root=document.querySelector('#bettingView');if(!root)return false;if(!root.__bet564Observer){let busy=false;const o=new MutationObserver(records=>{if(!bettingSourceMutation691(records)||busy)return;busy=true;setTimeout(()=>{busy=false;ensureAutoBox();maybeAutoScan()},120)});o.observe(root,{childList:true,subtree:true});root.__bet564Observer=o}ensureAutoBox();setTimeout(maybeAutoScan,1200);if(!timer)timer=setInterval(()=>{if(document.querySelector('#view-betting.on')){ensureAutoBox();maybeAutoScan()}},60000);return true}
installBettingTiming564();