const VERSION='695.0.0';
const originalFetch=window.fetch.bind(window);
let latest=null,lastHeartbeat=0,lastFeederVersion='694.0.0',installed=false;
const FEED_MAX_AGE=30*60*1000;
const PULSE_STORE='kamil_pulse_budget_561';

function freshFeed(){const stamp=Date.parse(latest?.relayedAt||latest?.fetchedAt||latest?.sourceCapturedAt||'');return latest?.ok===true&&Number.isFinite(stamp)&&Date.now()-stamp<FEED_MAX_AGE}
function resetPulseStop(){try{const s=JSON.parse(localStorage.getItem(PULSE_STORE)||'{}');s.providerExhausted=false;s.providerStatus=null;s.providerMessage=null;s.providerAt=null;s.used=0;s.log=[];s.updatedAt=new Date().toISOString();localStorage.setItem(PULSE_STORE,JSON.stringify(s))}catch{}if(window.__KAMIL_PULSE_BUDGET561__){window.__KAMIL_PULSE_BUDGET561__={...window.__KAMIL_PULSE_BUDGET561__,providerExhausted:false,providerStatus:null,providerMessage:null,used:0,remaining:500,mode:'normal'}}}
function responseJson(obj,status=200){return new Response(JSON.stringify(obj),{status,headers:{'content-type':'application/json','cache-control':'no-store','x-kamil-chance-feed':'browser695'}})}
function discovery(){const events=Array.isArray(latest?.events)?latest.events:[],leagues=[...new Set(events.map(e=>e?.league).filter(Boolean))].sort();return{ok:true,version:VERSION,provider:'chance-browser',bookmaker:'Chance.cz',mode:'page-discovery',days:5,totalPages:1,scannedPages:1,relevantPages:events.length?1:0,pages:events.length?[{page:1,supportedEvents:Number(latest?.capturedEvents||latest?.rawCount||events.length),leagues}]:[],fetchedAt:latest?.fetchedAt||new Date().toISOString()}}
function route(input){try{const raw=typeof input==='string'?input:input?.url,u=new URL(String(raw),location.href);if(u.origin!==location.origin)return null;if(u.pathname==='/api/chance-model-pages')return'pages';if(u.pathname==='/api/core70-health'&&u.searchParams.get('source')==='chance')return'scan';if(u.pathname==='/api/core70-health'&&!u.searchParams.get('source'))return'health';return null}catch{return null}}
async function fetch695(input,init){const kind=route(input);if(!kind||!freshFeed())return originalFetch(input,init);resetPulseStop();if(kind==='pages')return responseJson(discovery());if(kind==='scan')return responseJson({...latest,provider:'chance-browser',bookmaker:'Chance.cz',version:VERSION,page:1,totalPages:1,hasNextPage:false});const r=await originalFetch(input,init);try{const j=await r.clone().json();j.checks={...(j.checks||{}),pulsescore_api:true,pulsescore_configured:true,pulsescore_status:200};j.pulse={ok:true,status:200,authMode:'browser695',message:'Chance browser feeder active'};j.browserFeed695={ok:true,version:lastFeederVersion,fetchedAt:latest?.fetchedAt||null,capturedEvents:latest?.capturedEvents||latest?.rawCount||0};return responseJson(j,r.status)}catch{return r}}
function render(){const root=document.querySelector('#bettingView');if(!root)return;let box=root.querySelector('[data-bet694]');if(!box){box=document.createElement('section');box.dataset.bet694='1';box.style.cssText='display:grid;gap:5px;padding:10px 12px;border:1px solid rgba(135,164,194,.14);border-radius:10px;background:rgba(7,19,31,.55);font-size:11px;color:#91a7ba';const anchor=root.querySelector('.bet144-metrics');anchor?.insertAdjacentElement('afterend',box)}if(!box)return;const feederReady=Date.now()-lastHeartbeat<10000;const label=String(lastFeederVersion||'695.0.0').startsWith('695')?'695':'694';if(freshFeed()){const age=Math.max(0,Math.round((Date.now()-Date.parse(latest.relayedAt||latest.fetchedAt))/60000));box.innerHTML=`<div><b style="color:#8fe0ad">🟢 Chance Browser Feed ${label} aktivní</b> · ${Number(latest.capturedEvents||latest.rawCount||0)} zachycených zápasů · data ${age} min</div><div>Kurzy jdou z tvého prohlížeče → kanonický model → Betting centrum. PulseScore se nepoužívá.</div>`}else if(feederReady){box.innerHTML=`<div><b style="color:#f0c979">🟠 Chance Feeder ${label} běží</b> · otevři Chance a nech načíst nabídku kurzů.</div><div>Jakmile feeder zachytí první kurzy, scanner se automaticky přepne.</div>`}else{box.innerHTML='<div><b style="color:#f0c979">🟠 Chance Browser Feed není nainstalovaný</b></div><div>1× nainstaluj Tampermonkey a potom <a href="/chance-feeder695.user.js" target="_blank" style="color:#8fd4ff">Kamil OS Chance Feeder 695</a>. Potom stačí mít otevřenou Chance.</div>'}const state={version:VERSION,feederVersion:lastFeederVersion,healthy:true,feederReady,active:freshFeed(),capturedEvents:Number(latest?.capturedEvents||latest?.rawCount||0),fetchedAt:latest?.fetchedAt||null,at:Date.now()};window.__KAMIL_BROWSER_FEED694__=state;window.__KAMIL_BROWSER_FEED695__=state;window.__KAMIL_CHANCE_BROWSER_FEED__=state}
function onMessage(ev){if(ev.source!==window||ev.origin!==location.origin)return;const type=String(ev.data?.type||'');if(type==='KAMIL_CHANCE_FEEDER_READY_694'||type==='KAMIL_CHANCE_FEEDER_READY_695'){lastHeartbeat=Date.now();if(ev.data?.version)lastFeederVersion=String(ev.data.version);render();return}if((type==='KAMIL_CHANCE_FEED_694'||type==='KAMIL_CHANCE_FEED_695')&&ev.data.payload?.ok){latest=ev.data.payload;if(latest?.feederVersion)lastFeederVersion=String(latest.feederVersion);resetPulseStop();render();document.dispatchEvent(new CustomEvent('kamil:chance-feed695-updated',{detail:{capturedEvents:latest?.capturedEvents||latest?.rawCount||0,feederVersion:lastFeederVersion}}));document.dispatchEvent(new CustomEvent('kamil:chance-feed694-updated',{detail:{capturedEvents:latest?.capturedEvents||latest?.rawCount||0,feederVersion:lastFeederVersion}}))}}
export function installBettingBrowserFeed694(){if(installed)return true;installed=true;window.addEventListener('message',onMessage);window.fetch=fetch695;render();setInterval(()=>{if(document.querySelector('#view-betting.on'))render()},5000);return true}
installBettingBrowserFeed694();
