const API='/api/betting-ledger543';
const STORE='kamil_betting_ledger_543';
const CONFIRMED542='kamil_betting_confirmed_542';
const VERSION='543.1.0';

const num=value=>{const n=Number(String(value??'').replace(/\s/g,'').replace(',','.').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null};
const money=value=>`${Number(value||0).toLocaleString('cs-CZ',{maximumFractionDigits:0})} Kč`;
const pct=value=>`${Number(value||0).toLocaleString('cs-CZ',{minimumFractionDigits:1,maximumFractionDigits:1})} %`;
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
function read(){try{const v=JSON.parse(localStorage.getItem(STORE)||'{}');return{bets:Array.isArray(v?.bets)?v.bets:[],bankrollCzk:Number(v?.bankrollCzk||0),unitCzk:Number(v?.unitCzk||0),updatedAt:v?.updatedAt||null}}catch{return{bets:[],bankrollCzk:0,unitCzk:0}}}
function write(state){const next={...state,updatedAt:new Date().toISOString()};localStorage.setItem(STORE,JSON.stringify(next));window.dispatchEvent(new CustomEvent('kamil:betting-ledger543-updated',{detail:{bets:Array.isArray(next.bets)?next.bets.length:0,bankrollCzk:Number(next.bankrollCzk||0),unitCzk:Number(next.unitCzk||0),at:Date.now()}}));return next}
function betId(bet){return String(bet?.id||`${bet?.event||''}|${bet?.market||''}|${bet?.selection||bet?.label||''}|${bet?.odds||''}`).toLowerCase()}
function merge(a,b){const map=new Map();for(const item of [...(a||[]),...(b||[])]){if(!item)continue;const key=betId(item);map.set(key,{...(map.get(key)||{}),...item})}return [...map.values()]}
function analytics(state){
 const bets=state.bets||[],open=bets.filter(b=>b.status==='OPEN'),settled=bets.filter(b=>['WIN','LOSS','VOID'].includes(b.status));
 const stake=settled.reduce((s,b)=>s+Number(b.stakeCzk||0),0),profit=settled.reduce((s,b)=>s+Number(b.pnlCzk||0),0),wins=settled.filter(b=>b.status==='WIN').length,losses=settled.filter(b=>b.status==='LOSS').length;
 const group=key=>Object.values(bets.reduce((m,b)=>{const name=String(b?.[key]||'Nezařazeno');const r=m[name]||(m[name]={name,bets:0,settled:0,stake:0,pnl:0});r.bets++;if(b.status!=='OPEN'){r.settled++;r.stake+=Number(b.stakeCzk||0);r.pnl+=Number(b.pnlCzk||0)}return m},{})).map(r=>({...r,roi:r.stake?r.pnl/r.stake*100:0})).sort((x,y)=>y.pnl-x.pnl);
 return{openCount:open.length,openExposure:open.reduce((s,b)=>s+Number(b.stakeCzk||0),0),settled:settled.length,wins,losses,profit,roi:stake?profit/stake*100:0,winRate:wins+losses?wins/(wins+losses)*100:0,units:state.unitCzk?profit/state.unitCzk:null,byMarket:group('market'),byLeague:group('league')};
}
function migrate542(state){
 try{
  const src=JSON.parse(localStorage.getItem(CONFIRMED542)||'{}');
  for(const [key,item] of Object.entries(src||{})){
   if(state.bets.some(b=>b.sourceKey===key))continue;
   const title=String(item?.title||'');const detail=String(item?.detail||'');
   state.bets.push({id:`local542-${btoa(unescape(encodeURIComponent(key))).replace(/[^a-z0-9]/gi,'').slice(0,24)}`,sourceKey:key,label:title.replace(/^🟢\s*/,'').replace(/\s*@\s*[0-9.,]+\s*$/,''),event:detail.split('·')[0]?.trim()||detail,league:null,market:detail.split('·')[1]?.trim()||null,selection:title.replace(/^🟢\s*/,'').replace(/\s*@\s*[0-9.,]+\s*$/,''),odds:Number(item?.odds||0)||null,stakeCzk:Number(item?.stakeCzk||0)||0,status:'OPEN',bookmaker:'chance',placedAt:item?.at||new Date().toISOString(),recordedAt:item?.at||new Date().toISOString(),minOdds:item?.minOdds??null,units:item?.units??null,confidence:item?.confidence??null,source:'os542-migration'});
  }
 }catch{}
 return state;
}
async function apiGet(){try{const r=await fetch(`${API}?_=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function apiPost(payload){try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});return{status:r.status,payload:await r.json().catch(()=>null)}}catch{return{status:0,payload:null}}}
function cleanStrongText(card){const strong=card.querySelector('.bet144-pickmain strong');if(!strong)return'';const clone=strong.cloneNode(true);clone.querySelectorAll('.bet560-corr,.bet564-urgency,.bet565-flag').forEach(x=>x.remove());return clone.textContent||''}
function parseCard(card){
 const title=cleanStrongText(card);
 const detail=card.querySelector('.bet144-pickmain span')?.textContent||'';
 const stats=Object.fromEntries([...card.querySelectorAll('.bet144-stat')].map(x=>[x.querySelector('span')?.textContent?.trim(),num(x.querySelector('b')?.textContent)]));
 const actions=Object.fromEntries([...card.querySelectorAll('.bet542-decision')].map(x=>[x.querySelector('span')?.textContent?.trim(),num(x.querySelector('b')?.textContent)]));
 const oddsMatch=title.match(/@\s*([0-9]+(?:[,.][0-9]+)?)/);const parts=detail.split('·').map(x=>x.trim());
 return{id:`os543-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,label:title.replace(/^🟢\s*/,'').replace(/\s*@\s*[0-9.,]+\s*$/,''),selection:title.replace(/^🟢\s*/,'').replace(/\s*@\s*[0-9.,]+\s*$/,''),event:parts[0]||detail,market:parts[1]||null,league:null,odds:oddsMatch?Number(oddsMatch[1].replace(',','.')):null,stakeCzk:0,status:'OPEN',bookmaker:'chance',modelProbability:stats.Model?stats.Model/100:null,fairOdds:stats.Fair??null,edgePctPoints:stats.Edge??null,evPct:stats.EV??null,minOdds:actions['Min. kurz']??null,units:actions.Stake??null,confidence:actions.Confidence??null,placedAt:new Date().toISOString(),recordedAt:new Date().toISOString(),source:'os543-ui'};
}
function settleLocal(id,status,closingOdds=null){const state=read();const bet=state.bets.find(b=>b.id===id);if(!bet)return;bet.status=status;bet.settledAt=new Date().toISOString();if(closingOdds)bet.closingOdds=closingOdds;bet.pnlCzk=status==='WIN'?Number(bet.stakeCzk||0)*(Number(bet.odds||0)-1):status==='LOSS'?-Number(bet.stakeCzk||0):0;write(state);syncRender()}
function ensureStyles(){if(document.querySelector('style[data-bet543]'))return;const s=document.createElement('style');s.dataset.bet543='1';s.textContent=`
.bet543{display:grid;gap:10px;padding:13px;border:1px solid rgba(96,165,250,.15);border-radius:15px;background:rgba(7,19,31,.72)}.bet543-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.bet543-head h3{margin:0;font-size:15px}.bet543-head small{color:#71899d}.bet543-kpis{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:7px}.bet543-kpi{padding:9px;border-radius:9px;background:rgba(150,175,198,.055)}.bet543-kpi span{display:block;font-size:8px;color:#738ba0;text-transform:uppercase}.bet543-kpi b{display:block;margin-top:3px;font-size:12px;color:#e5eef5}.bet543-profit.pos{color:#77e39e}.bet543-profit.neg{color:#f59a9a}.bet543-grid{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(240px,.8fr);gap:8px}.bet543-panel{padding:10px;border:1px solid rgba(150,175,198,.09);border-radius:10px;background:rgba(2,10,18,.24)}.bet543-panel h4{margin:0 0 8px;font-size:10px;color:#879eb1;text-transform:uppercase;letter-spacing:.07em}.bet543-bank{display:grid;grid-template-columns:1fr 1fr auto;gap:6px}.bet543-bank input{min-width:0;padding:8px;border-radius:8px;border:1px solid rgba(150,175,198,.16);background:rgba(3,12,20,.65);color:#e5eef5}.bet543-btn{padding:7px 9px;border:1px solid rgba(96,165,250,.2);border-radius:8px;background:rgba(96,165,250,.1);color:#b8d4f2;cursor:pointer;font-size:9px;font-weight:800}.bet543-history{display:grid;gap:5px;max-height:230px;overflow:auto}.bet543-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center;padding:7px 8px;border-radius:8px;background:rgba(150,175,198,.035)}.bet543-row b{display:block;font-size:10px;color:#dce8f1}.bet543-row small{display:block;margin-top:2px;color:#70899d;font-size:8px}.bet543-settle{display:flex;gap:4px}.bet543-settle button{padding:4px 6px;border-radius:6px;border:1px solid rgba(150,175,198,.12);background:rgba(150,175,198,.05);color:#98acbd;cursor:pointer;font-size:8px}.bet543-table{display:grid;gap:4px}.bet543-line{display:grid;grid-template-columns:minmax(0,1fr) 54px 70px;gap:7px;font-size:9px;color:#8198ab}.bet543-line b{color:#d9e6ef;font-size:9px;text-align:right}.bet543-storage{padding:6px 8px;border-radius:8px;background:rgba(245,158,11,.07);color:#c6a96c;font-size:8px}.bet543-storage.ok{background:rgba(34,197,94,.07);color:#81c99b}@media(max-width:900px){.bet543-kpis{grid-template-columns:repeat(3,1fr)}.bet543-grid{grid-template-columns:1fr}}@media(max-width:520px){.bet543-kpis{grid-template-columns:repeat(2,1fr)}.bet543-bank{grid-template-columns:1fr 1fr}.bet543-bank button{grid-column:1/-1}}
`;document.head.appendChild(s)}
let storageMode='client_fallback',serverWritable=false;
async function hydrate(){let state=migrate542(read());const remote=await apiGet();if(remote?.ok){storageMode=remote.storage||storageMode;serverWritable=remote.writable===true;state.bets=merge(remote.bets,state.bets);if(!state.bankrollCzk)state.bankrollCzk=Number(remote.bankrollCzk||0);if(!state.unitCzk)state.unitCzk=Number(remote.unitCzk||0)}write(state);syncRender()}
function panelHtml(state){
 const a=analytics(state);const open=state.bets.filter(b=>b.status==='OPEN').slice().sort((x,y)=>Date.parse(y.placedAt||0)-Date.parse(x.placedAt||0));
 const market=a.byMarket.slice(0,5),league=a.byLeague.slice(0,5);
 const history=open.length?open.map(b=>`<div class="bet543-row"><div><b>${esc(b.label||b.event)} ${b.odds?`@ ${Number(b.odds).toFixed(2)}`:''}</b><small>${esc(b.event||'')} · ${esc(b.market||'sázka')} · ${money(b.stakeCzk||0)}</small></div><div class="bet543-settle"><button data-settle="WIN" data-id="${esc(b.id)}">WIN</button><button data-settle="LOSS" data-id="${esc(b.id)}">LOSS</button><button data-settle="VOID" data-id="${esc(b.id)}">VOID</button></div></div>`).join(''):'<div class="bet543-storage ok">Žádná otevřená sázka v OS543 historii.</div>';
 const groupRows=rows=>rows.length?rows.map(r=>`<div class="bet543-line"><span>${esc(r.name)}</span><b>${r.settled}</b><b class="${r.pnl>=0?'bet543-profit pos':'bet543-profit neg'}">${money(r.pnl)}</b></div>`).join(''):'<div class="bet543-storage">Zatím bez vyhodnocených dat.</div>';
 return `<section class="bet543" data-bet543><div class="bet543-head"><h3>📊 Ledger & výkon · OS543</h3><small>${state.bets.length} evidovaných sázek</small></div><div class="bet543-kpis"><div class="bet543-kpi"><span>Open</span><b>${a.openCount}</b></div><div class="bet543-kpi"><span>Expozice</span><b>${money(a.openExposure)}</b></div><div class="bet543-kpi"><span>Profit</span><b class="bet543-profit ${a.profit>=0?'pos':'neg'}">${money(a.profit)}</b></div><div class="bet543-kpi"><span>ROI / Yield</span><b>${pct(a.roi)}</b></div><div class="bet543-kpi"><span>Win rate</span><b>${pct(a.winRate)}</b></div><div class="bet543-kpi"><span>Units</span><b>${a.units==null?'—':a.units.toFixed(2)+'u'}</b></div></div><div class="bet543-storage ${serverWritable?'ok':''}">${serverWritable?'✓ Serverový ledger je zapisovatelný.':'Lokální persistentní režim: data přežijí refresh na tomto zařízení; serverové KV zatím není připojeno.'}</div><div class="bet543-grid"><div class="bet543-panel"><h4>Otevřené sázky / vyhodnocení</h4><div class="bet543-history">${history}</div></div><div class="bet543-panel"><h4>Bankroll</h4><div class="bet543-bank"><input data-bankroll type="number" min="0" step="100" placeholder="Bankroll Kč" value="${state.bankrollCzk||''}"><input data-unit type="number" min="0" step="10" placeholder="1u Kč" value="${state.unitCzk||''}"><button class="bet543-btn" data-save-bank>Uložit</button></div><h4 style="margin-top:12px">Top markety</h4><div class="bet543-table">${groupRows(market)}</div><h4 style="margin-top:12px">Top ligy</h4><div class="bet543-table">${groupRows(league)}</div></div></div></section>`;
}
function syncRender(){const root=document.querySelector('#bettingView');if(!root)return;let node=root.querySelector('[data-bet543]');const state=read();const html=panelHtml(state);if(node){node.outerHTML=html}else{const commander=root.querySelector('[data-bet542-command]')||root.querySelector('.bet144-metrics');if(commander)commander.insertAdjacentHTML('afterend',html)}bind(root);window.__KAMIL_BETTING_LEDGER543__={version:VERSION,storage:storageMode,serverWritable,bets:state.bets.length,analytics:analytics(state),at:Date.now()}}
function bind(root){root.querySelector('[data-save-bank]')?.addEventListener('click',async()=>{const state=read();state.bankrollCzk=Number(root.querySelector('[data-bankroll]')?.value||0);state.unitCzk=Number(root.querySelector('[data-unit]')?.value||0);write(state);if(serverWritable)await apiPost({action:'bankroll',bankrollCzk:state.bankrollCzk,unitCzk:state.unitCzk});syncRender()});for(const btn of root.querySelectorAll('[data-settle]'))btn.addEventListener('click',async()=>{const id=btn.dataset.id,status=btn.dataset.settle;settleLocal(id,status);if(serverWritable)await apiPost({action:'settle',id,status});});}
function captureBet(event){const button=event.target?.closest?.('.bet542-confirm');if(!button)return;const card=button.closest('.bet144-pick');if(!card)return;const bet=parseCard(card);const state=read();state.bets=merge(state.bets,[bet]);write(state);if(serverWritable)apiPost({action:'add',bet});setTimeout(syncRender,0)}
function observe(){const root=document.querySelector('#bettingView');if(!root)return;if(!root.__bet543Observer){const o=new MutationObserver(()=>{if(!root.querySelector('[data-bet543]'))syncRender()});o.observe(root,{childList:true,subtree:true});root.__bet543Observer=o}root.addEventListener('click',captureBet,true)}
export function installBettingLedger543(){ensureStyles();observe();hydrate()}
installBettingLedger543();