const VERSION='692.0.0';
const HEALTH='/api/market-history?source=bet_odds692&health=1';
const SCAN='/api/market-history?source=bet_odds692&days=5&limit=40&betsOnly=1&minOdds=1.45&maxOdds=3.20&minEv=0.05&minEdgePp=4';
const AUTO_KEY='kamil_betting_feed692_auto';
const AUTO_MS=8*3600000;
let healthCache={at:0,value:null};
let scanController=null;
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const decimal=value=>Number(value||0).toLocaleString('cs-CZ',{minimumFractionDigits:2,maximumFractionDigits:2});
const pct=value=>Number(value||0).toLocaleString('cs-CZ',{minimumFractionDigits:1,maximumFractionDigits:1});
function readAuto(){try{return JSON.parse(localStorage.getItem(AUTO_KEY)||'{"lastAt":0}')}catch{return{lastAt:0}}}
function writeAuto(value){try{localStorage.setItem(AUTO_KEY,JSON.stringify(value))}catch{}}
function state(patch={}){const old=window.__KAMIL_BETTING_FEED692__||{version:VERSION,configured:false,live:false,provider:'odds-api.io',bookmaker:'Chance.cz',exactChance:true};const next={...old,...patch,version:VERSION,at:Date.now()};window.__KAMIL_BETTING_FEED692__=next;document.dispatchEvent(new CustomEvent('kamil:betting-feed692-updated',{detail:next}));return next}
function marketLabel(type){const t=String(type||'').toUpperCase();return{MATCH_RESULT:'Výsledek zápasu',BOTH_TEAMS_TO_SCORE:'Oba dají gól',OVER_UNDER:'Góly v zápasu',HOME_OVER_UNDER:'Góly domácích',AWAY_OVER_UNDER:'Góly hostů',ASIAN_HANDICAP:'Handicap',CORNERS_OVER_UNDER:'Rohy v zápasu',BOOKINGS_OVER_UNDER:'Karty / bookings'}[t]||String(type||'Sázka')}
function ensureStyles(){if(document.querySelector('style[data-bet692]'))return;const s=document.createElement('style');s.dataset.bet692='1';s.textContent=`.bet692{display:grid;gap:12px;padding:18px;border:1px solid rgba(92,208,145,.22);border-radius:20px;background:linear-gradient(145deg,rgba(12,37,36,.9),rgba(9,22,33,.92));box-shadow:0 14px 34px rgba(0,0,0,.13)}.bet692-head{display:flex;justify-content:space-between;gap:14px;align-items:center}.bet692-head h2{margin:0;font-size:21px}.bet692-head p{margin:5px 0 0;color:#8fa4b8;font-size:12px}.bet692-status{display:flex;gap:7px;flex-wrap:wrap}.bet692-chip{padding:5px 8px;border-radius:999px;font-size:10px;font-weight:800;background:rgba(135,164,194,.08);color:#a9bdd0}.bet692-chip.ok{background:rgba(42,122,80,.18);color:#8fe0ad}.bet692-chip.warn{background:rgba(143,93,19,.18);color:#f0c979}.bet692-chip.bad{background:rgba(111,35,35,.2);color:#f2a0a0}.bet692-body{display:grid;gap:9px}.bet692-note{padding:13px 14px;border:1px solid rgba(135,164,194,.14);border-radius:13px;color:#91a7ba;font-size:12px;line-height:1.45;background:rgba(7,19,31,.36)}.bet692-meta{font-size:10px;color:#71899d}.bet692 .bet144-pick{margin:0}@media(max-width:700px){.bet692-head{align-items:flex-start;flex-direction:column}}`;document.head.appendChild(s)}
function root(){return document.querySelector('#bettingView')}
function legacyScanner(){return root()?.querySelector('.bet144-scanner:not([data-bet692])')||null}
function syncLegacy(){const old=legacyScanner(),s=window.__KAMIL_BETTING_FEED692__;if(!old)return;if(s?.live===true&&s?.operational===true)old.style.display='none';else old.style.display=''}
function frame(){const host=root();if(!host)return null;let box=host.querySelector('[data-bet692]');if(!box){box=document.createElement('section');box.className='bet692';box.dataset.bet692='1';const anchor=host.querySelector('.bet144-hero')||host.firstElementChild;anchor?.insertAdjacentElement('afterend',box)}return box}
function renderBase(message='Zjišťuju dostupnost přesného Chance feedu…'){const box=frame();if(!box)return;const s=window.__KAMIL_BETTING_FEED692__||{};const level=s.live?'ok':s.configured?'warn':'bad';const provider=s.live?'● Chance.cz LIVE':s.configured?'○ Chance API připraveno':'● Exact Chance API bez klíče';box.innerHTML=`<div class="bet692-head"><div><h2>🎯 Chance Feed 2.0</h2><p>Přesné Chance.cz kurzy → Kamil OS model → fair kurz → EV → VSADIT / NIC.</p></div><button class="btn" type="button" data-bet692-scan ${s.configured?'':'disabled'}>${s.loading?'Skenuji…':'Spustit exact sken'}</button></div><div class="bet692-status"><span class="bet692-chip ${level}">${provider}</span><span class="bet692-chip">1X2 · BTTS · góly · handicapy</span><span class="bet692-chip">týmové góly · rohy</span><span class="bet692-chip">EV ≥ 5 % · edge ≥ 4 pp</span></div><div class="bet692-body" data-bet692-body><div class="bet692-note">${esc(message)}</div></div><div class="bet692-meta" data-bet692-meta>${s.live?'Exact Chance feed byl ověřený a PulseScore je jen fallback.':s.configured?'Exact provider je nakonfigurovaný; PulseScore nechávám viditelný jako fallback až do prvního úspěšného exact skenu.':'PulseScore zůstává fallback. Exact Chance provider se automaticky aktivuje po nastavení ODDS_API_IO_KEY.'}</div>`;box.querySelector('[data-bet692-scan]')?.addEventListener('click',()=>runBettingFeed692(true));syncLegacy()}
async function jsonFetch(url,options={}){const response=await fetch(url,{headers:{Accept:'application/json'},...options});let payload=null;try{payload=await response.json()}catch{}return{response,payload}}
export async function loadBettingFeedHealth692(force=false){if(!force&&healthCache.value&&Date.now()-healthCache.at<60000)return healthCache.value;try{const {response,payload}=await jsonFetch(HEALTH,{cache:'no-store'});const value=response.ok&&payload?.ok?payload:{configured:false,provider:'odds-api.io',bookmaker:'Chance.cz',exactChance:true,error:payload?.error||`HTTP_${response.status}`};healthCache={at:Date.now(),value};state({configured:value.configured===true,provider:value.provider||'odds-api.io',bookmaker:value.bookmaker||'Chance.cz',exactChance:value.exactChance!==false,pulsescoreFallbackConfigured:value.pulsescoreFallbackConfigured===true,healthError:value.error||null,operational:value.configured===true?null:false});return value}catch(error){const value={configured:false,provider:'odds-api.io',bookmaker:'Chance.cz',exactChance:true,error:String(error?.message||error)};healthCache={at:Date.now(),value};state({configured:false,live:false,operational:false,healthError:value.error});return value}}
function rows(payload){const out=[];for(const event of Array.isArray(payload?.events)?payload.events:[]){for(const market of Array.isArray(event?.markets)?event.markets:[]){for(const selection of Array.isArray(market?.selections)?market.selections:[]){if(selection?.decision==='BET'&&!selection?.existingBet)out.push({event,market,selection})}}}return out.sort((a,b)=>Number(b.selection.evPct||0)-Number(a.selection.evPct||0))}
function rowHtml({event,market,selection}){return `<article class="bet144-pick" data-bet692-pick="1"><div class="bet144-pickmain"><strong>🟢 ${esc(selection.name||selection.outcome)} @ ${decimal(selection.odds)}</strong><span>${esc(event.home)} – ${esc(event.away)} · ${esc(marketLabel(market.type))} · ${esc(selection.modelSource||'Kamil model')}</span></div><div class="bet144-stat"><span>Model</span><b>${pct(Number(selection.modelProbability||0)*100)} %</b></div><div class="bet144-stat"><span>Fair</span><b>${decimal(selection.fairOdds)}</b></div><div class="bet144-stat"><span>Edge</span><b>+${pct(selection.edgePctPoints)} pp</b></div><div class="bet144-stat bet144-ev"><span>EV</span><b>+${pct(selection.evPct)} %</b></div></article>`}
function publishValueScan(payload,list){window.__KAMIL_VALUE_SCAN_144__={ok:true,loading:false,partial:false,modelReady:true,picks:list.length,pagesScanned:1,relevantPages:1,totalPages:1,modeledEvents:Number(payload?.value?.autoModel?.modeledEvents||0),dataRequests:Number(payload?.value?.autoModel?.dataRequests||0),apiRequests:Number(payload?.providerRequests||0),provider:'odds-api.io',bookmaker:'Chance.cz',exactChance:true,fetchedAt:payload?.fetchedAt||new Date().toISOString()}}
export async function runBettingFeed692(manual=false){const box=frame();if(!box)return false;if(scanController)scanController.abort();scanController=new AbortController();state({loading:true,scanError:null});renderBase('Načítám přesné Chance.cz kurzy a porovnávám je s nezávislým modelem…');try{const health=await loadBettingFeedHealth692();if(!health?.configured){state({loading:false,live:false,operational:false});renderBase('Exact Chance provider je připravený, ale v produkčním Vercelu zatím není ODDS_API_IO_KEY. Starý PulseScore může dál fungovat jako fallback po obnovení kvóty.');return false}const {response,payload}=await jsonFetch(SCAN,{cache:'no-store',signal:scanController.signal});if(!response.ok||!payload?.ok){const message=payload?.message||payload?.error||`HTTP ${response.status}`;state({loading:false,live:false,operational:false,scanError:String(message),lastStatus:response.status});renderBase(`Exact Chance feed selhal: ${message}. PulseScore fallback zůstává k dispozici, pokud má kvótu.`);return false}const list=rows(payload);state({configured:true,loading:false,live:true,operational:true,lastStatus:200,lastFetchedAt:payload.fetchedAt||new Date().toISOString(),providerRequests:Number(payload.providerRequests||0),eventCount:Number(payload.oddsEventCount||0),pickCount:list.length,modelProvider:payload?.value?.modelProvider||null});syncLegacy();const body=box.querySelector('[data-bet692-body]'),meta=box.querySelector('[data-bet692-meta]'),btn=box.querySelector('[data-bet692-scan]');if(btn){btn.disabled=false;btn.textContent='↻ Znovu skenovat'}if(body)body.innerHTML=list.length?list.map(rowHtml).join(''):'<div class="bet692-note"><b>NIC — 0u.</b> Exact Chance kurzy jsou načtené, ale žádný podporovaný trh neprošel Kamil OS modelem, EV a edge filtrem. Nic nenutím.</div>';if(meta)meta.textContent=`Chance.cz přes Odds-API.io · ${payload.oddsEventCount||0} eventů s kurzy · ${payload.value?.autoModel?.modeledEvents||0} modelovaných zápasů · ${list.length} value tipů · ${payload.providerRequests||0} provider requestů · ${payload.fetchedAt||''}`;publishValueScan(payload,list);writeAuto({lastAt:Date.now(),lastResult:'success',picks:list.length});document.dispatchEvent(new CustomEvent('kamil:betting-feed692-scan',{detail:{picks:list.length,manual}}));return true}catch(error){if(error?.name==='AbortError')return false;state({loading:false,live:false,operational:false,scanError:String(error?.message||error)});renderBase(`Exact Chance feed se nepodařilo načíst: ${String(error?.message||error)}`);return false}finally{scanController=null}}
async function maybeAuto(){const s=window.__KAMIL_BETTING_FEED692__,last=Number(readAuto().lastAt||0);if(!s?.configured||Date.now()-last<AUTO_MS||!document.querySelector('#view-betting.on'))return false;writeAuto({lastAt:Date.now(),lastResult:'triggered'});return runBettingFeed692(false)}
export async function appendBettingFeed692(){ensureStyles();state({mounted:true});renderBase();await loadBettingFeedHealth692();const s=window.__KAMIL_BETTING_FEED692__;renderBase(s?.configured?'Exact Chance provider je připravený. PulseScore nechávám jako fallback, dokud první exact sken neprojde.':'Exact Chance provider je v kódu připravený; zatím chybí serverový API klíč, proto se používá pouze PulseScore fallback.');setTimeout(maybeAuto,900);return true}
