import {store} from './state.js';
import {ownEvent1100} from './runtimeOwnership1100.js';
import {modal} from './utils.js';

const OWNER='product.bettingOverview';
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const money=v=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(Number(v||0));

function ledger(input=null){
 const canonical=(input||store.get())?.bettingLedger||{},bets=Array.isArray(canonical.bets)?canonical.bets:[];
 return {bets,bankrollCzk:Number(canonical.bankrollCzk||0),unitCzk:Number(canonical.unitCzk||0)};
}
export function bettingData1334(input=null){
 const state=input||store.get(),l=ledger(state),master=state?.bettingLedger?.masterMeta||null,open=l.bets.filter(x=>String(x.status||'OPEN').toUpperCase()==='OPEN').sort((a,b)=>Number(b.stakeCzk||0)-Number(a.stakeCzk||0)),settled=l.bets.filter(x=>['WIN','LOSS','VOID'].includes(String(x.status||'').toUpperCase()));
 const stake=settled.reduce((a,x)=>a+Number(x.stakeCzk||0),0),profit=settled.reduce((a,x)=>a+Number(x.pnlCzk||0),0),wins=settled.filter(x=>String(x.status).toUpperCase()==='WIN').length,losses=settled.filter(x=>String(x.status).toUpperCase()==='LOSS').length;
 const openTickets=open.reduce((a,x)=>a+Math.max(1,Number(x.ticketCount||1)),0),exposure=open.reduce((a,x)=>a+Number(x.stakeCzk||0),0),hasBankroll=l.bankrollCzk>0,risk=hasBankroll&&exposure>l.bankrollCzk*.2,unknownRisk=exposure>0&&!hasBankroll,riskPct=hasBankroll?exposure/l.bankrollCzk*100:null;
 return {...l,master,open,openTickets,settled,exposure,hasBankroll,risk,unknownRisk,riskPct,profit,roi:stake?profit/stake*100:0,winRate:wins+losses?wins/(wins+losses)*100:0};
}
const data=()=>bettingData1334();
function rows(items){if(!items.length)return '<div class="pr1300-empty">Žádná otevřená sázka.</div>';return items.map((x,i)=>'<button type="button" class="pr1300-row pr1300-clickrow" data-betting-open-row data-betting-open-index="'+i+'"><div class="pr1300-row-main"><b>'+esc(x.label||x.selection||x.event||'Sázka')+(x.odds?' @ '+Number(x.odds).toFixed(2):'')+'</b><small>'+esc(x.event||'')+' · '+esc(x.market||'')+'</small></div><div class="os1334-bet-stake"><b>'+money(x.stakeCzk||0)+'</b><small>'+(x.units?esc(x.units+'u'):'OPEN')+' <span class="os1500-row-arrow">→</span></small></div></button>').join('')}

export function renderBettingOverview(){
 const host=document.querySelector('#bettingView');if(!host)return false;if(host.dataset.productAdvanced==='1')return true;
 const d=data(),hasBankroll=d.hasBankroll,hasHistory=d.settled.length>0,risk=d.risk,unknownRisk=d.unknownRisk,largest=d.open[0]||null,riskPct=d.riskPct,master=d.master,blank=!d.bets.length&&!hasBankroll;
 const exposureGroups=new Map();for(const x of d.open){const key=String(x.selection||x.event||'Ostatní'),g=exposureGroups.get(key)||{label:key,stake:0,positions:0,tickets:0};g.stake+=Number(x.stakeCzk||0);g.positions++;g.tickets+=Math.max(1,Number(x.ticketCount||1));exposureGroups.set(key,g)}const heatmap=[...exposureGroups.values()].sort((a,b)=>b.stake-a.stake).slice(0,6);
 const settlementAudit=d.settled.map(x=>({x,missing:['stakeCzk','odds','status'].filter(k=>x?.[k]===null||x?.[k]===undefined||x?.[k]==='').concat(x.pnlCzk===null||x.pnlCzk===undefined?['pnlCzk']:[])})).filter(x=>x.missing.length);
 const perfMap=new Map();for(const x of d.settled){const k=x.category||x.league||'Ostatní',g=perfMap.get(k)||{label:k,stake:0,pnl:0,w:0,l:0};g.stake+=Number(x.stakeCzk||0);g.pnl+=Number(x.pnlCzk||0);if(String(x.status).toUpperCase()==='WIN')g.w++;if(String(x.status).toUpperCase()==='LOSS')g.l++;perfMap.set(k,g)}const performance=[...perfMap.values()].map(g=>({...g,roi:g.stake?g.pnl/g.stake*100:0,hit:g.w+g.l?g.w/(g.w+g.l)*100:0})).sort((a,b)=>b.stake-a.stake);
 const statusTone=risk||unknownRisk?'warn':'good';
 const riskCopy=blank?'Veřejný OS neobsahuje žádné osobní sázky. Soukromý ledger se načte z tvého zařízení nebo autentizovaného cloudu.':unknownRisk?'Máš otevřenou expozici, ale bankroll není nastavený. Poměr rizika proto nejde poctivě vyhodnotit.':risk?'Expozice je vyšší než 20 % uloženého bankrollu. Další vstup nejdřív zkontroluj.':d.exposure?'Otevřená expozice podle uloženého bankrollu není mimo běžný rámec.':'Teď nemáš žádnou otevřenou expozici.';
 const context='<section class="pr1300-panel os1334-context-panel os1334-betting-context"><div class="pr1300-panel-head"><div><h2>Rámec rizika</h2><span>bez modelových doporučení · scanner je v detailu</span></div></div><div class="os1334-mini-grid"><span><small>Bankroll</small><b>'+(hasBankroll?money(d.bankrollCzk):'nenastaven')+'</b></span><span><small>Expozice / bankroll</small><b>'+(riskPct===null?'—':riskPct.toFixed(1).replace('.',',')+' %')+'</b></span><span><small>Největší pozice</small><b>'+(largest?money(largest.stakeCzk||0):'—')+'</b></span><span><small>Otevřené pozice</small><b>'+d.open.length+'</b></span></div></section>';
 const openBlock=(d.open.length?'<section class="pr1300-panel os1334-open-bets"><div class="pr1300-panel-head"><h2>Otevřené pozice</h2><span>'+d.open.length+' pozic · '+d.openTickets+' tiketů · '+money(d.exposure)+'</span></div>'+rows(d.open)+'</section>':'<section class="pr1300-panel pr1330-betting-clear"><div class="pr1300-panel-head"><h2>'+(blank?'Začni soukromým ledgerem':'Bez otevřených sázek')+'</h2><span>'+(blank?'žádná veřejná data':'expozice 0 Kč')+'</span></div><div class="pr1300-empty">'+(blank?'Přidej nebo synchronizuj sázky v detailu. OS nebude tvoje pozice doplňovat z veřejného balíku.':'Teď není nic ve hře. Historii a scanner otevřeš jen pokud je potřebuješ.')+'</div></section>');
 const summaryBlock=blank?'':'<div class="os1500-summary-grid">'+(master?'<div class="os1500-summary"><span>Vsazeno</span><b>'+money(master.totalStakedCzk)+'</b></div><div class="os1500-summary"><span>Pot. výplata</span><b>'+money(master.potentialPayoutCzk)+'</b></div><div class="os1500-summary"><span>Zbývá dosázet</span><b>'+money(master.remainingToPlaceCzk)+'</b></div><div class="os1500-summary"><span>Otevřené pozice</span><b>'+d.open.length+'</b></div><div class="os1500-summary"><span>Otevřené tikety</span><b>'+d.openTickets+'</b></div>':'<div class="os1500-summary"><span>Profit</span><b>'+(hasHistory?money(d.profit):'—')+'</b></div><div class="os1500-summary"><span>ROI</span><b>'+(hasHistory?d.roi.toFixed(1).replace('.',',')+' %':'—')+'</b></div><div class="os1500-summary"><span>Win rate</span><b>'+(hasHistory?d.winRate.toFixed(1).replace('.',',')+' %':'—')+'</b></div><div class="os1500-summary"><span>Otevřené</span><b>'+d.open.length+'</b></div>')+'</div>';
 const truthBlock=blank?'<section class="pr1300-panel os741-betting-truth"><div class="pr1300-panel-head"><div><h2>Riziko a historie</h2><span>aktivuje se po načtení soukromého ledgeru</span></div></div><div class="pr1300-empty">Expozici, settlement audit a výsledky ukážu až z tvých skutečných dat. Bez nich nevyrábím falešné metriky.</div></section>':'<section class="pr1300-panel os741-betting-truth"><div class="pr1300-panel-head"><div><h2>Riziková koncentrace a settlement audit</h2><span>stejný tým / scénář · jen z uložených sázek</span></div></div><div class="os741-heatmap">'+(heatmap.length?heatmap.map((g,i)=>'<div style="--os741-weight:'+Math.max(10,100-i*12)+'%"><span>'+esc(g.label)+'</span><b>'+money(g.stake)+'</b><small>'+g.positions+' pozic · '+g.tickets+' tiketů</small></div>').join(''):'<div class="os1500-empty">Bez otevřené expozice.</div>')+'</div><div class="os1500-summary-grid"><div class="os1500-summary '+(settlementAudit.length?'warn':'good')+'"><span>Settlement chyby</span><b>'+settlementAudit.length+'</b></div><div class="os1500-summary"><span>Historické segmenty</span><b>'+performance.length+'</b></div><div class="os1500-summary"><span>Realizovaný P/L</span><b>'+(hasHistory?money(d.profit):'—')+'</b></div><div class="os1500-summary"><span>Realizované ROI</span><b>'+(hasHistory?d.roi.toFixed(1).replace('.',',')+' %':'—')+'</b></div></div>'+(performance.length?'<div class="os741-performance">'+performance.slice(0,5).map(g=>'<div><b>'+esc(g.label)+'</b><small>ROI '+g.roi.toFixed(1).replace('.',',')+' % · hit '+g.hit.toFixed(0)+' % · '+money(g.stake)+'</small></div>').join('')+'</div>':'')+'</section>';
 host.innerHTML='<div class="pr1300-shell" data-betting-overview data-decision-surface1334>' +
 '<div class="pr1300-head"><div><div class="pr1300-kicker">Sázení</div><h1>Sázení.</h1><p>'+(master?'Soukromý master · '+Number(master.ticketCount||d.openTickets)+' tiketů agregovaných do '+Number(master.positionCount||d.open.length)+' pozic.':blank?'Soukromý ledger bez veřejně vložených sázek. Data se načtou až z tvého zařízení nebo cloudu.':'Všechny otevřené sázky jsou vidět přímo. Scanner, modely a historie zůstávají až v detailu.')+'</p></div><span class="pr1300-status '+statusTone+'">'+(blank?'připraveno':d.open.length+' otevřených')+'</span></div>' +
 '<div class="os1334-decision-grid os1334-betting-grid"><section class="pr1320-now os1334-primary"><div><div class="pr1300-kicker">'+(blank?'Soukromá data':'Expozice')+'</div><h2>'+(blank?'Ledger je připravený':money(d.exposure))+'</h2><p>'+riskCopy+'</p></div><div class="pr1320-now-actions"><button class="pr1300-btn primary" type="button" data-betting-advanced>Otevřít detail sázek</button></div></section>'+(blank?'':context)+'</div>' + openBlock + summaryBlock +
 (master&&!blank?'<div class="os1500-section-note">Kategorie a další souhrny pocházejí výhradně ze soukromého masteru.</div>':'') + truthBlock +
 '<div class="pr1300-actions"><button class="pr1300-btn" type="button" data-betting-task>＋ Úkol k sázení</button></div></div>';
 host.__bettingOverview1500=d;
 if(!host.dataset.bettingOverviewBound){host.dataset.bettingOverviewBound='1';ownEvent1100(OWNER,host,'click',async e=>{if(e.target.closest('[data-betting-task]')){window.dispatchEvent(new CustomEvent('kamil:capture',{detail:'betting-task'}));return}if(e.target.closest('[data-betting-advanced]')){host.dataset.productAdvanced='1';const m=await import('./bettingAdvanced527.js');await m.renderBettingPage527?.();return}const row=e.target.closest('[data-betting-open-index]');if(row){const current=host.__bettingOverview1500||data(),x=current.open[Number(row.dataset.bettingOpenIndex)];if(!x)return;const odds=Number(x.odds);await modal('Otevřená sázka',`<div class="card"><div class="eyebrow">SÁZENÍ</div><h2>${esc(x.label||x.selection||x.event||'Sázka')}</h2><p class="muted">${esc(x.event||'')} ${x.market?'· '+esc(x.market):''}</p><div class="row"><span>Vklad</span><b>${money(x.stakeCzk||0)}</b></div><div class="row"><span>Kurz</span><b>${Number.isFinite(odds)&&odds>0?odds.toFixed(2):'—'}</b></div><div class="row"><span>Jednotky</span><b>${x.units?esc(x.units+'u'):'—'}</b></div><div class="row"><span>Stav</span><b>${esc(x.status||'OPEN')}</b></div></div>`,[{label:'Zavřít',value:null,primary:true}]);return}})}
 window.__KAMIL_BETTING_OVERVIEW__={healthy:true,open:d.open.length,openPositions:d.open.length,openTickets:d.openTickets,heatmap:heatmap.length,settlementIssues:settlementAudit.length,performanceSegments:performance.length,renderedOpen:d.open.length,exposure:d.exposure,profit:d.profit,hasBankroll,hasHistory,riskUnknown:unknownRisk,masterId:store.get()?.bettingLedger?.masterId||null,ticketCount:d.openTickets,positionCount:d.open.length,masterTicketCount:master?.ticketCount??null,masterPositionCount:master?.positionCount??null,decisionSurface:1335,directRows:true,blank,at:Date.now()};return true;
}