import {openFinanceCommand258} from './financeCommand258.js';

const VERSION=469;
const N=v=>Number.isFinite(Number(v))?Number(v):0;
const U=v=>String(v||'').toUpperCase();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`;
const round100=v=>Math.max(0,Math.floor(N(v)/100)*100);
const isTodayEvent=e=>{const d=e?.detail;return !d||d==='today'||d?.view==='today'};
const forbiddenRisks=new Set(['STALE_DATA','UNTRUSTED_LIVE_SIGNAL','RESALE_UNVERIFIED','TRANSFER_UNVERIFIED','STALE_PRICE','LOW_CONFIDENCE','LOW_OPPORTUNITY']);

function ensureCss(){if(document.querySelector('link[data-capital-plan469-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./capitalPlan469.css';l.dataset.capitalPlan469Css='1';document.head.appendChild(l)}
function liveInputs(){return{cashflow:window.__KAMIL_CASHFLOW468__?.model||null,sizing:window.__KAMIL_POSITION_SIZING373__?.model||null,tickets:window.__KAMIL_TICKET_TARGETS372__?.model||null,opportunities:window.__KAMIL_OPPORTUNITY370__?.model||null}}
function oppRows(model){return[...(model?.positive||[]),...(model?.rows||[])].filter(Boolean)}
function opportunityMap(model){const map=new Map();for(const x of oppRows(model)){const id=U(x?.id||x?.ticker||x?.name);if(!id)continue;const key=`${U(x?.domain)}|${id}`,old=map.get(key);if(!old||N(x?.score)>N(old?.score))map.set(key,x)}return map}
function evidence(map,domain,row){for(const id of [row?.id,row?.ticker,row?.name].map(U).filter(Boolean)){const hit=map.get(`${domain}|${id}`);if(hit)return hit}return null}
function evidenceSafe(o){if(!o||N(o.score)<60||N(o.confidence)<60)return false;return!(o.riskFlags||[]).some(x=>forbiddenRisks.has(String(x)))}
function cashflowSafe(cashflow){return!!cashflow&&cashflow.version===468&&cashflow.healthy===true&&cashflow.guardrails?.forecastMustStayAboveReserve!==false&&N(cashflow.deployable)>=0}
function xtbCandidates(sizing,map){return(sizing?.rows||[]).map(x=>{const o=evidence(map,'XTB',x),amount=round100(x?.recommendedAmount);if(!amount||x?.blockedReason||!evidenceSafe(o))return null;return{id:`XTB:${x.ticker||x.name}`,domain:'XTB',name:x.name||x.ticker||'XTB pozice',ticker:x.ticker||null,maxAmount:amount,score:N(o.score),confidence:N(o.confidence),quality:N(x.qualityScore)||N(o.score),action:'PŘIKOUPIT',limit:null,reason:`Opportunity ${Math.round(N(o.score))}/100 · confidence ${Math.round(N(o.confidence))}% · sizing ${money(amount)}. Cenový vstup zůstává v detailu XTB.`,autoExecute:false}}).filter(Boolean)}
function ticketCandidates(tickets,map){return(tickets?.opportunities||[]).map(x=>{const o=evidence(map,'TICKET',x),amount=Math.max(0,Math.round(N(x?.maxBuyPrice)));if(!x?.safeBuy||!amount||!evidenceSafe(o))return null;return{id:`TICKET:${x.id||x.name}`,domain:'TICKET',name:x.name||'Vstupenka',maxAmount:amount,score:N(o.score),confidence:N(o.confidence),quality:N(o.score),action:'KOUPIT MAX',limit:amount,reason:`Safe-buy potvrzen · Opportunity ${Math.round(N(o.score))}/100 · nekupovat nad ${money(amount)}.`,autoExecute:false}}).filter(Boolean)}
const horizons=[{code:'NOW',label:'Teď',pct:.35},{code:'D7',label:'Do 7 dnů',pct:.60},{code:'D14',label:'Do 14 dnů',pct:.80},{code:'D30',label:'Do 30 dnů',pct:1}];
function allocate(candidates,safeCapital){let allocated=0;const used=new Set(),steps=[];for(const h of horizons){const cumulative=Math.floor(safeCapital*h.pct),room=Math.max(0,cumulative-allocated);let chosen=null,amount=0;for(const c of candidates){if(used.has(c.id))continue;if(c.domain==='TICKET'&&c.maxAmount>room)continue;const proposed=c.domain==='TICKET'?c.maxAmount:round100(Math.min(c.maxAmount,room));if(proposed<=0)continue;chosen=c;amount=proposed;break}if(chosen){used.add(chosen.id);allocated+=amount;steps.push({...h,status:'ACTION',domain:chosen.domain,name:chosen.name,action:chosen.action,amount,limit:chosen.limit,score:chosen.score,confidence:chosen.confidence,reason:chosen.reason,candidateId:chosen.id,autoExecute:false})}else steps.push({...h,status:'HOLD',domain:'CASH',name:'Rezerva / čekání',action:'DRŽET',amount:0,limit:null,score:0,confidence:100,reason:room>0?'V tomto okně není další bezpečný vstup, který projde všemi guardrails.':'Kumulativní rozpočet tohoto okna je už využit.',candidateId:null,autoExecute:false})}return{steps,allocated}}
export function buildCapitalPlan469(inputs=liveInputs()){
  const cashflow=inputs?.cashflow||null,cashflowHealthy=cashflowSafe(cashflow),safeCapital=cashflowHealthy?Math.max(0,N(cashflow.deployable)):0,reserve=Math.max(0,N(cashflow?.reserve)),map=opportunityMap(inputs?.opportunities),candidates=cashflowHealthy?[...xtbCandidates(inputs?.sizing,map),...ticketCandidates(inputs?.tickets,map)].sort((a,b)=>b.quality-a.quality||b.score-a.score||b.confidence-a.confidence):[],allocation=allocate(candidates,safeCapital),planned=Math.min(safeCapital,allocation.allocated),unallocated=Math.max(0,safeCapital-planned),holdReason=!cashflow?'OS468 cash-flow model není dostupný.':!cashflowHealthy?'OS468 cash-flow model není zdravý; kapitál se nealokuje.':!safeCapital?'Po 90denním bufferu není bezpečně volný kapitál.':!candidates.length?'Žádná XTB/Ticket příležitost současně nesplňuje OS468 bezpečnostní podmínky.':null;
  return{version:VERSION,healthy:true,cashflowVersion:cashflow?.version||null,cashflowHealthy,safeCapital,reserve,planned,unallocated,candidates:candidates.length,steps:allocation.steps,recommendation:holdReason?{code:'HOLD',action:'DRŽET HOTOVOST',reason:holdReason}:{code:planned>0?'STAGED_ALLOCATE':'HOLD',action:planned>0?'ALOKOVAT POSTUPNĚ':'DRŽET HOTOVOST',reason:planned>0?`${money(planned)} je rozděleno do časových oken; ${money(unallocated)} zůstává nealokováno.`:'Bez bezpečného vstupu zůstává kapitál v hotovosti.'},generatedAt:new Date().toISOString(),guardrails:{cashflowGate:true,cashflowHealthy,reserveUntouched:true,totalWithinSafeCapital:planned<=safeCapital,unsafeTicketsExcluded:true,minOpportunityScore:60,minOpportunityConfidence:60,explicitConfirmation:true,autoExecute:false,partialTicketPurchase:false}}
}
function card(m){const rows=m.steps.map(x=>`<div class="os469-step ${x.status==='ACTION'?'action':'hold'}"><div><small>${esc(x.label).toUpperCase()}</small><b>${esc(x.action)}${x.name?` · ${esc(x.name)}`:''}</b><span>${esc(x.reason)}</span></div><div class="os469-step-amount"><b>${money(x.amount)}</b>${x.domain==='TICKET'&&x.limit?`<span>strop ${money(x.limit)}</span>`:''}</div></div>`).join('');return`<article class="os467-card os469" data-capital-plan469-root><header><div><small>OS469 · KAPITÁL 30 DNÍ</small><h3>30denní kapitálový plán</h3></div><button type="button" data-os469-finance>Peníze</button></header><div class="os469-summary"><div><small>Bezpečně volné</small><b>${money(m.safeCapital)}</b></div><div><small>Naplánováno</small><b>${money(m.planned)}</b></div><div><small>Zůstává volné</small><b>${money(m.unallocated)}</b></div><div><small>Rezerva nedotčena</small><b>${money(m.reserve)}</b></div></div><div class="os469-verdict ${m.planned>0?'allocate':'hold'}"><b>${esc(m.recommendation.action)}</b><span>${esc(m.recommendation.reason)}</span></div><div class="os469-steps">${rows}</div><footer>Každý krok vyžaduje potvrzení · žádné automatické obchody</footer></article>`}
function mount(){const grid=document.querySelector('[data-command-center467-root] .os467-grid');if(!grid)return false;const m=buildCapitalPlan469(),first=!window.__KAMIL_CAPITAL_PLAN469__;let host=grid.querySelector('[data-capital-plan469-root]');const holder=document.createElement('div');holder.innerHTML=card(m);const next=holder.firstElementChild;let changed=false;if(host){if(host.innerHTML!==next.innerHTML||host.className!==next.className){host.replaceWith(next);host=next;changed=true}}else{const cashflow=grid.querySelector('[data-cashflow468-root]');cashflow?cashflow.after(next):grid.appendChild(next);host=next;changed=true}window.__KAMIL_CAPITAL_PLAN469__={version:VERSION,healthy:true,mounted:!!host,model:m,refresh:renderSafe,at:Date.now()};document.documentElement.dataset.capitalPlan469='1';if(first||changed)window.dispatchEvent(new CustomEvent('kamil:capital-plan469-updated',{detail:{planned:m.planned,unallocated:m.unallocated,changed}}));return true}
function renderSafe(){try{return mount()}catch(error){console.error('[capitalPlan469]',error);window.__KAMIL_CAPITAL_PLAN469__={version:VERSION,healthy:false,error:String(error?.message||error),refresh:renderSafe,at:Date.now()};return false}}
let timer=0,bound=false;const schedule=(delay=70)=>{clearTimeout(timer);timer=setTimeout(renderSafe,delay)};
export function installCapitalPlan469(){ensureCss();document.documentElement.dataset.capitalPlan469='1';if(!bound){bound=true;document.addEventListener('click',e=>{if(e.target.closest?.('[data-os469-finance]')){e.preventDefault();openFinanceCommand258()}});for(const event of ['kamil:cashflow468-updated','kamil:opportunity370-updated','kamil:position-sizing373-updated','kamil:ticket-targets372-updated'])window.addEventListener(event,()=>schedule(30));window.addEventListener('kamil:view-change',e=>{if(isTodayEvent(e))schedule(40)});window.addEventListener('focus',()=>schedule(30))}renderSafe();setTimeout(()=>schedule(20),950);setTimeout(()=>schedule(20),1900)}
