import {store} from './state.js';
import {buildFinanceCommand258,openFinanceCommand258} from './financeCommand258.js';

const VERSION=468;
const N=v=>Number.isFinite(Number(v))?Number(v):0;
const U=v=>String(v||'').toUpperCase();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`;
const oppApi=()=>window.__KAMIL_OPPORTUNITY370__||null;
const sizingApi=()=>window.__KAMIL_POSITION_SIZING373__||null;
const ticketTargetsApi=()=>window.__KAMIL_TICKET_TARGETS372__||null;

function ensureCss(){if(document.querySelector('link[data-cashflow468]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./cashflow468.css';l.dataset.cashflow468='1';document.head.appendChild(l)}
function flowCollections(s){return [s.finance?.cashflow,s.finance?.cashflowItems,s.finance?.scheduled,s.cashFlow?.items,s.cashflow?.items,s.money?.cashflow,s.personalFinance?.cashflow,s.cashBook?.scheduled,s.scheduledPayments].filter(Array.isArray)}
function flowRows(s){const now=Date.now(),seen=new Set(),rows=[];for(const list of flowCollections(s))for(const x of list){const status=U(x?.status);if(['DONE','PAID','CANCELLED','CANCELED','ARCHIVED'].includes(status))continue;const date=x?.date||x?.dueDate||x?.scheduledAt||x?.expectedDate||x?.at;if(!date)continue;const at=Date.parse(date);if(!Number.isFinite(at))continue;const days=Math.ceil((at-now)/86400000);if(days<0||days>90)continue;let amount=N(x?.amountCzk??x?.valueCzk??x?.amount??x?.value);if(!amount)continue;const direction=U(`${x?.direction||''} ${x?.type||''} ${x?.kind||''} ${x?.category||''}`);let signed=0;if(amount<0)signed=amount;else if(/INCOME|INFLOW|RECEIV|PŘÍJ|PRIJ|PAYOUT/.test(direction))signed=amount;else if(/EXPENSE|OUTFLOW|PAYMENT|OBLIG|VÝDAJ|VYDAJ|BILL/.test(direction))signed=-amount;else continue;const key=`${date}|${signed}|${x?.title||x?.name||''}`;if(seen.has(key))continue;seen.add(key);rows.push({days,at:new Date(at).toISOString(),amount:signed,title:x?.title||x?.name||x?.label||'Cash-flow položka'})}return rows.sort((a,b)=>a.days-b.days)}
function horizon(finance,flows,days){const recurringOut=Math.max(0,N(finance.monthlyOut)*(days/30)),inside=flows.filter(x=>x.days<=days),explicitIn=inside.filter(x=>x.amount>0).reduce((a,x)=>a+x.amount,0),explicitOut=inside.filter(x=>x.amount<0).reduce((a,x)=>a+Math.abs(x.amount),0),expectedOut=Math.max(recurringOut,explicitOut),base=finance.forecast?.find(x=>x.days===days)?.balance,forecast=inside.length?N(finance.cash)+explicitIn-expectedOut:Number.isFinite(Number(base))?Number(base):N(finance.cash)-expectedOut;return{days,forecast,expectedIn:explicitIn,expectedOut,explicitCount:inside.length}}
function matching(list,id,name){const key=U(id||name);return (list||[]).find(x=>U(x?.id||x?.ticker||x?.name)===key)||null}
function chooseOpportunity(deployable){const rows=oppApi()?.model?.positive||[],sizing=sizingApi()?.model?.rows||[],tickets=ticketTargetsApi()?.model?.opportunities||[];for(const o of rows){if(N(o.score)<60||N(o.confidence)<60)continue;const risks=o.riskFlags||[];if(risks.some(x=>['STALE_DATA','UNTRUSTED_LIVE_SIGNAL','RESALE_UNVERIFIED','TRANSFER_UNVERIFIED'].includes(x)))continue;if(o.domain==='XTB'){const size=matching(sizing,o.id,o.name);const amount=Math.min(deployable,N(size?.recommendedAmount));if(amount>0)return{domain:'XTB',name:o.name||o.id,action:'PŘIKOUPIT XTB',amount,limit:null,score:N(o.score),confidence:N(o.confidence),reason:`Opportunity ${N(o.score)}/100 · sizing drží rizikový rozpočet.`,source:o,guardrails:size?.riskFlags||[]}}if(o.domain==='TICKET'){const target=matching(tickets,o.id,o.name);if(!target?.safeBuy||!N(target.maxBuyPrice))continue;const amount=N(target.maxBuyPrice);if(amount<=deployable)return{domain:'TICKET',name:o.name||o.id,action:'KOUPIT VSTUPENKU',amount,limit:amount,score:N(o.score),confidence:N(o.confidence),reason:`Safe-buy potvrzen · nekupovat nad ${money(amount)} za kus.`,source:o,guardrails:[]}}}return null}
export function buildCashflow468(s=store.get()){const finance=buildFinanceCommand258(s),flows=flowRows(s),h30=horizon(finance,flows,30),h90=horizon(finance,flows,90),reserve=Math.max(N(finance.reserveTarget),N(finance.monthlyOut)*3,N(finance.cash)*.15),baseDeployable=Math.max(0,Math.min(N(finance.deployable)||Math.max(0,N(finance.cash)-reserve),N(finance.cash)-reserve)),deployable=Math.max(0,Math.min(baseDeployable,h90.forecast-reserve)),buffer30=h30.forecast-reserve,buffer90=h90.forecast-reserve;let recommendation=null;if(N(finance.cash)<=0)recommendation={code:'NO_CASH_DATA',domain:'CASH',action:'DOPLNIT DATA',name:'Hotovost není evidovaná',amount:0,score:0,confidence:35,reason:'Bez stavu hotovosti OS bezpečně neurčí alokaci.',autoExecute:false};else if(buffer30<0||buffer90<0||deployable<=0)recommendation={code:'HOLD_CASH',domain:'CASH',action:'DRŽET HOTOVOST',name:'Rezerva má přednost',amount:0,score:100,confidence:90,reason:buffer30<0?'30denní výhled padá pod bezpečnou rezervu.':buffer90<0?'90denní výhled padá pod bezpečnou rezervu.':'Nad bezpečnou rezervou teď není volný kapitál.',autoExecute:false};else{const pick=chooseOpportunity(deployable);recommendation=pick?{code:`ALLOCATE_${pick.domain}`,...pick,autoExecute:false}:{code:'HOLD_CASH',domain:'CASH',action:'DRŽET HOTOVOST',name:'Čekat na lepší vstup',amount:0,score:0,confidence:75,reason:'Volný kapitál existuje, ale žádný XTB/Ticket signál právě nesplňuje bezpečnostní guardrails.',autoExecute:false}}return{version:VERSION,healthy:true,finance,flows,h30,h90,reserve,deployable,buffer30,buffer90,recommendation,generatedAt:new Date().toISOString(),guardrails:{autoExecute:false,minOpportunityScore:60,minOpportunityConfidence:60,threeMonthRecurringReserve:true,minCashReservePct:15,forecastMustStayAboveReserve:true}}}
function card(m){const r=m.recommendation,flowNote=m.flows.length?`${m.flows.length} explicitních budoucích cash-flow položek`:'forecast z pravidelných závazků';return `<article class="os467-card os468" data-cashflow468><header><div><small>OS468 · CASH-FLOW 30/90</small><h3>Kam dát další peníze?</h3></div><button type="button" data-os468-finance>Detail financí</button></header><div class="os468-horizons"><div><small>30 dní</small><b>${money(m.h30.forecast)}</b><span>příjmy ${money(m.h30.expectedIn)} · výdaje ${money(m.h30.expectedOut)}</span></div><div><small>90 dní</small><b>${money(m.h90.forecast)}</b><span>příjmy ${money(m.h90.expectedIn)} · výdaje ${money(m.h90.expectedOut)}</span></div><div><small>Bezpečná rezerva</small><b>${money(m.reserve)}</b><span>${esc(flowNote)}</span></div><div><small>Bezpečně k alokaci</small><b>${money(m.deployable)}</b><span>po 90denním bufferu</span></div></div><div class="os468-answer ${r.domain==='CASH'?'hold':'allocate'}"><div><small>DOPORUČENÍ · ${esc(r.domain)}</small><h4>${esc(r.action)}${r.name?` · ${esc(r.name)}`:''}</h4><p>${esc(r.reason)}</p></div><div class="os468-amount"><small>${r.amount>0?'NAVRŽENÁ ČÁSTKA':'AKCE'}</small><b>${r.amount>0?money(r.amount):'0 Kč'}</b>${r.limit?`<span>strop ${money(r.limit)}</span>`:''}</div></div><footer>Confidence ${Math.round(N(r.confidence))}% · žádné automatické obchody</footer></article>`}
function mount(){const grid=document.querySelector('[data-command-center467] .os467-grid');if(!grid)return false;const m=buildCashflow468();let host=grid.querySelector('[data-cashflow468]');const holder=document.createElement('div');holder.innerHTML=card(m);const next=holder.firstElementChild;if(host)host.replaceWith(next);else{const financeButton=grid.querySelector('[data-os467-finance]'),financeCard=financeButton?.closest('.os467-card');financeCard?financeCard.after(next):grid.appendChild(next)}window.__KAMIL_CASHFLOW468__={version:VERSION,healthy:true,mounted:true,model:m,refresh:renderSafe,at:Date.now()};document.documentElement.dataset.cashflow468='1';return true}
function renderSafe(){try{return mount()}catch(error){console.error('[cashflow468]',error);window.__KAMIL_CASHFLOW468__={version:VERSION,healthy:false,error:String(error?.message||error),refresh:renderSafe,at:Date.now()};return false}}
let timer=0,bound=false;const schedule=(delay=70)=>{clearTimeout(timer);timer=setTimeout(renderSafe,delay)};
export function installCashflow468(){ensureCss();if(!bound){bound=true;document.addEventListener('click',e=>{if(e.target.closest?.('[data-os468-finance]')){e.preventDefault();openFinanceCommand258()}});for(const event of ['kamil:command-center467-updated','kamil:opportunity370-updated','kamil:position-sizing373-updated','kamil:ticket-targets372-updated','kamil:execution-state364-updated'])window.addEventListener(event,()=>schedule(30));window.addEventListener('kamil:view-change',e=>{if(!e.detail||e.detail==='today')schedule(40)});store.subscribe?.(()=>schedule())}schedule(100);setTimeout(()=>schedule(20),850);setTimeout(()=>schedule(20),1800)}
