import {store} from './state.js';
import {h,qs} from './utils.js';
import {changePulse35} from './changePulse35.js';
import {ownEvent1100,ownObserver1100,schedule1100} from './runtimeOwnership1100.js';

const OWNER='today.changePulse35';
const LAST='kamil-os-last-open-35',SESSION='kamil-os-session-since-35',id='changePulse35Host';let sessionSince=null,queued=false,bound=false;
function initSince(){try{sessionSince=sessionStorage.getItem(SESSION);if(!sessionSince){sessionSince=localStorage.getItem(LAST)||new Date(Date.now()-86400000).toISOString();sessionStorage.setItem(SESSION,sessionSince)}localStorage.setItem(LAST,new Date().toISOString())}catch{sessionSince=new Date(Date.now()-86400000).toISOString()}}
const time=v=>{const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleTimeString('cs-CZ',{hour:'2-digit',minute:'2-digit'}):'—'};
const targetLabel=t=>t==='email'?'E-mail Control':t==='waiting'?'Waiting For':t==='director'?'Ředitel':t==='money'?'Peníze':t==='tickets'?'Vstupenky':t==='home'?'Domov':'Otevřít';
function openTarget(t){if(t==='email'){window.dispatchEvent(new CustomEvent('kamil:email-workflow-open'));return}if(t==='waiting'){window.dispatchEvent(new CustomEvent('kamil:waiting-open'));return}if(t==='director'){window.dispatchEvent(new CustomEvent('kamil:director-open'));return}window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:t||'today'}))}
function markRead(){const now=new Date().toISOString();sessionSince=now;try{sessionStorage.setItem(SESSION,now);localStorage.setItem(LAST,now)}catch{}render()}
function row(x){return `<div class="pulse35-row"><div><span class="pulse35-kind">${h(x.kind)}</span><b>${h(x.title)}</b><small>${h(x.detail||'')} · ${h(time(x.at))}</small></div><button class="btn" data-pulse35-target="${h(x.target||'today')}">${h(targetLabel(x.target))}</button></div>`}
function render(){const view=qs('#todayView');if(!view?.querySelector('.view-head'))return;qs(`#${id}`,view)?.remove();const p=changePulse35(store.get(),sessionSince),host=document.createElement('div');host.id=id;host.className='card pulse35-card';host.innerHTML=`<div class="card-head"><div><div class="eyebrow">CHANGE PULSE / 35.2</div><h2>${p.total?`Od posledního otevření: ${p.total} změn`:'Od posledního otevření nic zásadního'}</h2><p class="muted">Nové zprávy, odpovědi, změny dat a aktualizace, které stojí za pozornost.</p></div><div class="brain34-actions"><span class="status ${p.high?'warn':'good'}">${p.high} důležitých</span>${p.total?'<button class="btn" data-pulse35-read>Přečteno</button>':''}</div></div><div class="pulse35-stats"><span><b>${p.emails}</b> zprávy / odpovědi</span><span><b>${p.finance}</b> finance</span><span><b>${p.tickets}</b> vstupenky</span></div><div class="pulse35-list">${p.top.map(row).join('')||'<div class="empty success-empty">Žádná nová změna, která by vyžadovala tvoji pozornost.</div>'}</div><div class="decision-note">${h(p.note)}</div>`;const focus=qs('#focusAction35Host',view),today=qs('#todayBrain34Host',view),anchor=focus||view.querySelector('.view-head');if(focus)focus.insertAdjacentElement('afterend',host);else if(today)today.insertAdjacentElement('beforebegin',host);else anchor?.insertAdjacentElement('afterend',host)}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;render()})}
function start(){if(bound)return;bound=true;initSince();const view=qs('#todayView');if(view)ownObserver1100(OWNER,view,{childList:true,subtree:false},()=>{if(!qs(`#${id}`,view))schedule()});store.subscribe(()=>{if(qs('#view-today')?.classList.contains('on'))schedule()});ownEvent1100(OWNER,window,'kamil:navigate',schedule);ownEvent1100(OWNER,document,'click',e=>{const host=e.target.closest?.(`#${id}`);if(!host)return;const read=e.target.closest?.('[data-pulse35-read]');if(read){markRead();return}const b=e.target.closest?.('[data-pulse35-target]');if(b)openTarget(b.dataset.pulse35Target)});schedule1100(OWNER,'initial-render',render,520,{pauseWhenHidden:true})}
if(document.readyState==='loading')ownEvent1100(OWNER,document,'DOMContentLoaded',start,{once:true});else start();
