import {store} from './state.js';
import {qs,h,money} from './utils.js';
import {dailyProfitBrief32} from './dailyProfitBrief32.js';

let queued=false;
const tone=p=>p>=95?'bad':p>=85?'warn':'good';
function mount(view){let host=qs('#dailyProfitBrief32Host',view);if(host)return host;host=document.createElement('div');host.id='dailyProfitBrief32Host';view?.querySelector('.view-head')?.insertAdjacentElement('afterend',host);return host}
function suppressLegacy(view){const legacy=qs('#profitControlToday32Host',view);if(legacy){legacy.style.display='none';legacy.setAttribute('aria-hidden','true');legacy.dataset.replacedBy='daily-profit-brief-32-8'}}
function render(){const view=qs('#todayView');if(!view?.querySelector('.view-head'))return;const b=dailyProfitBrief32(store.get()),host=mount(view);suppressLegacy(view);host.innerHTML=`<div class="card"><div class="card-head"><div><div class="eyebrow">DAILY PROFIT BRIEF 32.8</div><h2>${h(b.headline)}</h2><p class="muted">Jedna fronta pro hotovost, XTB a resale vstupenky. Nejvyšší dopad je nahoře; bez automatického obchodování nebo přeceňování.</p></div><span class="status ${b.urgentCount?'warn':'good'}">${b.urgentCount} URGENT</span></div><div class="metric-strip"><div class="metric"><span>Další rozpočet</span><b>${money(b.router.plannedCzk)}</b><small>XTB ${money(b.router.xtbBudget)} · rezerva ${money(b.router.reserveBudget)}</small></div><div class="metric"><span>Cashflow / měsíc</span><b>${money(b.data.cashflow.averageSurplus)}</b><small>výdaje ${money(b.data.cashflow.averageExpenses)}</small></div><div class="metric"><span>Historické XTB exity</span><b>${b.trades.realizedTotal>=0?'+':''}${money(b.trades.realizedTotal)}</b><small>${b.trades.count} obchodů · hit ${b.trades.hitRate===null?'—':Math.round(b.trades.hitRate)+' %'}</small></div><div class="metric"><span>Ticket market</span><b>${b.data.tickets.freshMarketPct} % fresh</b><small>${b.data.tickets.events} eventů · ${b.data.tickets.needsMarket} obnovit</small></div></div>${b.actions.map(x=>`<button class="row" data-daily-target="${h(x.target)}" style="width:100%;text-align:left;background:none;border:0;color:inherit;cursor:pointer;align-items:flex-start"><div style="min-width:0;flex:1"><div><span class="status ${tone(x.priority)}">${Math.round(x.priority)}</span> <b>${h(x.domain)} · ${h(x.action)}</b></div><div style="margin-top:3px"><b>${h(x.title)}</b></div><div class="muted">${h(x.detail||'')}</div></div><span aria-hidden="true">›</span></button>`).join('')||'<div class="empty success-empty">Dnes není žádná finanční výjimka, která potřebuje akci.</div>'}<div class="decision-note ${b.data.xtb.fresh?'':'warn'}"><b>Data:</b> XTB ${h(b.data.xtb.label)} · cashflow ${b.data.cashflow.months?`${b.data.cashflow.months} uzavřených měsíců`:'baseline'} · ticket market ${b.data.tickets.freshMarketPct} % čerstvý. Brief pouze čte stav a nic sám nemění.</div></div>`;host.querySelectorAll('[data-daily-target]').forEach(el=>el.addEventListener('click',()=>qs(`#mainNav [data-view="${el.dataset.dailyTarget}"]`)?.click()))}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;render()})}
function start(){const view=qs('#todayView');if(view)new MutationObserver(schedule).observe(view,{childList:true,subtree:false});store.subscribe(schedule);window.addEventListener('kamil:market-quotes',schedule);window.addEventListener('kamil:source-ingest',schedule);setTimeout(render,320)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
