import {store} from './state.js';
import {h,money} from './utils.js';
import {xtbPositions} from './decision24.js';
import {xtbBoard,actionLabel} from './live24.js';
import {quoteSymbolForPosition32,quoteFresh32} from './marketQuote32.js';
import {loadTicketCloud660} from './ticketCloud660.js';
import {ticketIntelligence100,capitalDecision100} from './marketIntelligence100.js';
import {personalDailyAssistant650} from './personalAssistant650.js';

const N=v=>Number(v||0),A=v=>Array.isArray(v)?v:[],fmt=(v,d=2)=>Number(v).toLocaleString('cs-CZ',{maximumFractionDigits:d,minimumFractionDigits:d}),pct=v=>`${N(v)>=0?'+':''}${fmt(v,2)} %`;
const qty=p=>N(p.quantity||p.qty||p.volume||p.units||p.shares||0);
const avg=p=>N(p.open_price||p.openPrice||p.avgPrice||p.averagePrice||p.purchasePrice||p.price_open||0);
const importedPrice=p=>N(p.marketPrice||p.currentPrice||p.price||0);
const importedValue=p=>N(p.value||p.marketValue||0);
const tone=a=>/PRODAT|REDUKOVAT|ZLEVNIT|EXIT/.test(a)?'bad':/PŘIKOUPIT|VYSTAVIT|ZDRAŽIT/.test(a)?'good':/OVĚŘIT|PROVĚŘIT/.test(a)?'warn':'hold';
const quoteMap=rows=>new Map(A(rows).map(q=>[String(q.symbol||'').toUpperCase(),q]));
async function liveQuotes(positions){const symbols=[...new Set(positions.map(quoteSymbolForPosition32).filter(Boolean))];if(!symbols.length)return{ok:false,quotes:new Map(),fetchedAt:null};try{const r=await fetch(`/api/market-quotes?symbols=${encodeURIComponent(symbols.join(','))}`,{cache:'no-store'}),j=await r.json();return{ok:!!j.ok,quotes:quoteMap(j.quotes),fetchedAt:j.fetchedAt,errors:j.errors||[]}}catch{return{ok:false,quotes:new Map(),fetchedAt:null}}}
function quoteFor(p,live){const symbol=quoteSymbolForPosition32(p),q=symbol?live.quotes.get(symbol):null,fresh=q?quoteFresh32(q).fresh:false;return q&&fresh?{price:N(q.price),currency:q.currency||p.currency||p.accountCurrency||'',dailyPct:q.dailyPct,asOf:q.asOf,live:true}:{price:importedPrice(p),currency:p.currency||p.accountCurrency||'',dailyPct:null,asOf:null,live:false};}
function positionRows(s,live){const decisions=new Map(xtbBoard(s).map(x=>[String(x.p.ticker),x.d]));return xtbPositions(s).map(p=>{const q=quoteFor(p,live),qnty=qty(p),basis=avg(p),gainPct=basis&&q.price?(q.price-basis)/basis*100:N(p.net_profit_pct),gain=qnty&&basis&&q.price?(q.price-basis)*qnty:N(p.net_profit),value=qnty&&q.price?qnty*q.price:importedValue(p),d=decisions.get(String(p.ticker))||{};return{p,q,qnty,basis,gainPct,gain,value,action:actionLabel(d.action||'HOLD'),confidence:N(d.confidence||d.priority||40),reason:d.reason||''}}).sort((a,b)=>b.value-a.value)}
function donut(rows){const total=rows.reduce((a,x)=>a+Math.max(0,x.value),0);if(!total)return 'conic-gradient(#263448 0 100%)';const colors=['#2176ff','#20c77a','#9b5cff','#ff9d2e','#ef4e4e','#2bc7d9','#e8cf4a','#6b88ff'];let acc=0,parts=[];rows.slice(0,8).forEach((x,i)=>{const end=acc+x.value/total*100;parts.push(`${colors[i%colors.length]} ${acc.toFixed(2)}% ${end.toFixed(2)}%`);acc=end});if(acc<100)parts.push(`#263448 ${acc}% 100%`);return `conic-gradient(${parts.join(',')})`}
function xtbTable(rows){return rows.slice(0,12).map(x=>`<div class="d110-tr"><div class="d110-pos"><b>${h(x.p.ticker||'—')}</b><small>${h(x.p.name||'')}</small></div><div>${x.qnty?fmt(x.qnty,4):'—'}</div><div><b>${x.q.price?fmt(x.q.price,2):'—'} ${h(x.q.currency||'')}</b><small class="${x.q.live?'live':'stale'}">${x.q.live?'LIVE':'IMPORT'}</small></div><div>${x.basis?`${fmt(x.basis,2)} ${h(x.q.currency||'')}`:'—'}</div><div class="${x.gainPct>=0?'pos':'neg'}"><b>${pct(x.gainPct)}</b><small>${x.gain?`${x.gain>=0?'+':''}${fmt(x.gain,2)} ${h(x.q.currency||'')}`:'—'}</small></div><div>${x.value?`${fmt(x.value,2)} ${h(x.q.currency||'')}`:'—'}</div><div><span class="d110-action ${tone(x.action)}">${h(x.action)}</span></div><div><span class="d110-confidence">${Math.round(x.confidence)}/100</span></div></div>`).join('')}
function ticketRows(cloud,intel){const byId=new Map(A(intel?.rows).map(x=>[x.id,x]));return cloud.inventory.filter(r=>['LISTED','NOT_LISTED'].includes(r.market_status)).slice(0,7).map(r=>{const x=byId.get(r.id)||{},sector=N(r.verified_sector_price_czk),api=N(cloud.sources?.get(r.id)?.viagogo?.official_price_czk),market=sector||N(x.market)||api,src=sector?'SEKTOR':N(x.market)?'TRH':api?'API FLOOR':'—',ask=N(r.ask_each_czk),action=x.recommendation==='LOWER'?'ZLEVNIT':x.recommendation==='LIST'?'VYSTAVIT':x.recommendation==='RAISE'?'ZDRAŽIT':market?'DRŽET':'OVĚŘIT';return`<div class="d110-ticket"><div><b>${h(r.event_name)}</b><small>${h(r.section||'—')} · ${r.qty||1} ks</small></div><div>${ask?money(ask):'—'}</div><div><b>${market?money(market):'—'}</b><small>${src}</small></div><div><span class="d110-action ${tone(action)}">${action}</span></div></div>`}).join('')}
function summary(rows,live){const importedTotal=rows.reduce((a,x)=>a+N(x.p.value),0),positive=rows.filter(x=>x.gainPct>=0).length;return{positions:rows.length,importedTotal,positive,liveCount:rows.filter(x=>x.q.live).length,fetchedAt:live.fetchedAt}}
export async function renderDashboard110(){const host=document.querySelector('#todayView');if(!host)return;host.innerHTML='<div class="d110-loading">Načítám Command Center 110…</div>';const s=store.get(),positions=xtbPositions(s);const [live,cloud,ticketIntel]=await Promise.all([liveQuotes(positions),loadTicketCloud660().catch(()=>({ok:false,inventory:[]})),ticketIntelligence100().catch(()=>({ok:false,rows:[]}))]);const rows=positionRows(s,live),sum=summary(rows,live),daily=personalDailyAssistant650(s);let capital=null;try{capital=capitalDecision100(s,N(s.financePlan?.plannedInvestment)||25000,ticketIntel?.ok?ticketIntel:null)}catch{}
 const topCapital=A(capital?.choices).slice(0,3),updated=sum.fetchedAt?new Date(sum.fetchedAt).toLocaleTimeString('cs-CZ',{hour:'2-digit',minute:'2-digit'}):'—';
 host.innerHTML=`<div class="dashboard110"><header class="d110-head"><div><div class="eyebrow">KAMIL OS 110 · COMMAND CENTER</div><h1>Dashboard</h1><p>Portfolio, vstupenky a dnešní rozhodnutí na jednom místě.</p></div><div class="d110-head-actions"><span class="d110-time">Trh: ${h(updated)}</span><button class="btn primary" data-d110-refresh>↻ Aktualizovat data</button><span class="d110-status ${sum.liveCount?'live':'stale'}">● ${sum.liveCount?`${sum.liveCount}/${sum.positions} LIVE`:'IMPORT DATA'}</span></div></header>
 <div class="d110-grid-top"><section class="d110-card d110-portfolio"><div class="d110-title"><b>XTB PORTFOLIO — AKTUÁLNĚ</b><span class="d110-status ${sum.liveCount?'live':'stale'}">${sum.liveCount?'LIVE QUOTES':'BEZ LIVE QUOTES'}</span></div><div class="d110-th"><span>Pozice</span><span>Množství</span><span>Aktuální cena</span><span>Cena nákupu</span><span>Zisk %</span><span>Hodnota</span><span>Akce</span><span>Confidence</span></div>${xtbTable(rows)}<div class="d110-foot"><b>${sum.positions} pozic</b><span>${sum.liveCount} čerstvých cen · ${sum.positive} pozic v plusu</span></div></section>
 <aside class="d110-card d110-summary"><div class="d110-title"><b>XTB — SOUHRN</b></div><div class="d110-big"><small>Hodnota z posledního XTB importu</small><b>${money(sum.importedTotal)}</b></div><div class="d110-donut" style="background:${donut(rows)}"><i>${rows.length}<small>pozic</small></i></div><div class="d110-legend">${rows.slice(0,6).map((x,i)=>`<span><i class="c${i}"></i>${h(x.p.ticker)}</span>`).join('')}</div><div class="d110-note">Aktuální ceny se načítají z veřejného market quote feedu. Celková CZK hodnota zůstává označená jako import, dokud nemáme jednotný live FX přepočet.</div></aside></div>
 <div class="d110-grid-mid"><section class="d110-card"><div class="d110-title"><b>VSTUPENKY — AKTUÁLNĚ</b><button class="d110-link" data-d110-nav="tickets">Zobrazit vše →</button></div><div class="d110-ticket-head"><span>Událost</span><span>Moje cena</span><span>Trh</span><span>Akce</span></div>${cloud?.ok?ticketRows(cloud,ticketIntel):'<div class="d110-empty">Ticket cloud není dostupný.</div>'}</section>
 <section class="d110-card"><div class="d110-title"><b>CAPITAL ALLOCATION BRAIN</b></div><p class="d110-sub">Kam dát další peníze?</p>${topCapital.length?topCapital.map((x,i)=>`<div class="d110-cap"><b>#${i+1} ${h(x.key)}</b><span>${Math.round(N(x.score))}/100</span><small>${h(x.reason||'')}</small></div>`).join(''):'<div class="d110-empty">Čeká na dostatek dat.</div>'}<button class="btn primary d110-wide" data-d110-command>Mám 50 000 Kč, co s nimi?</button></section>
 <section class="d110-card"><div class="d110-title"><b>RYCHLÝ PŘEHLED DNES</b></div><div class="d110-kpi"><span>Co řešit</span><b>${daily.top?.length||0}</b></div><div class="d110-kpi"><span>Čekám na odpověď</span><b>${daily.waitingCount||0}</b></div><div class="d110-kpi"><span>Zítra</span><b>${daily.tomorrowCount||0}</b></div><div class="d110-kpi"><span>Do 7 dní</span><b>${daily.next7Count||0}</b></div></section></div>
 <div class="d110-bottom"><section class="d110-card"><div class="d110-title"><b>DATOVÁ KVALITA</b></div><div class="d110-kpi"><span>XTB live ceny</span><b>${sum.liveCount}/${sum.positions}</b></div><div class="d110-kpi"><span>Ticket market</span><b>${ticketIntel?.ok?'PŘIPOJEN':'OMEZENÝ'}</b></div><div class="d110-kpi"><span>Poslední market refresh</span><b>${h(updated)}</b></div></section><section class="d110-card"><div class="d110-title"><b>NEJBLIŽŠÍ AKCE</b></div>${A(daily.top).slice(0,4).map(x=>`<div class="d110-row"><span>${h(x.title||'Úkol')}</span><b>${h(x.cta||'Řešit')}</b></div>`).join('')||'<div class="d110-empty">Nic urgentního.</div>'}</section></div></div>`;
 host.querySelector('[data-d110-refresh]')?.addEventListener('click',()=>renderDashboard110());host.querySelector('[data-d110-nav="tickets"]')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:'tickets'})));host.querySelector('[data-d110-command]')?.addEventListener('click',()=>{const i=document.querySelector('#commandInput');if(i){i.value='Mám 50000 Kč, co s nimi?';document.querySelector('#commandGo')?.click()}});window.__KAMIL_DASHBOARD110__={at:Date.now(),liveQuotes:sum.liveCount,positions:sum.positions};}
