import {store} from './state.js';
import {h,qs} from './utils.js';
import {deadlineRadar35} from './deadlineRadar35.js';

let openEl=null,queued=false;
const tone=p=>Number(p)>=90?'bad':Number(p)>=75?'warn':'good';
const dateText=v=>v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString('cs-CZ'):'—';
const dayText=d=>d<0?`${Math.abs(d)} d po termínu`:d===0?'dnes':d===1?'zítra':`za ${d} d`;
const targetLabel=t=>t==='director'?'Ředitel':t==='waiting'?'Waiting For':t==='tickets'?'Vstupenky':t==='home'?'Domov':'Otevřít';
const setHtml=(el,html)=>{if(el&&el.innerHTML!==html)el.innerHTML=html};
function openTarget(t){if(t==='director'){window.dispatchEvent(new CustomEvent('kamil:director-open'));return}if(t==='waiting'){window.dispatchEvent(new CustomEvent('kamil:waiting-open'));return}window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:t||'today'}));if(openEl){openEl.remove();openEl=null}}
function rows(list,empty){return list.map(x=>`<div class="radar35-row"><div><b>${h(x.title)}</b><small>${h(x.domain)} · ${h(x.kind)}${x.detail?` · ${h(x.detail)}`:''}</small></div><div class="radar35-actions"><span class="status ${tone(x.priority)}">${h(dayText(x.days))}</span><b>${h(dateText(x.date))}</b><button class="btn" data-radar35-target="${h(x.target)}">${h(targetLabel(x.target))}</button></div></div>`).join('')||`<div class="empty success-empty">${h(empty)}</div>`}
function bodyHtml(r){return `<div class="card-head"><div><div class="eyebrow">DEADLINE RADAR / 41.6</div><h2>90 dní dopředu na jedné ose</h2><p class="muted">Práce, osobní administrativa, follow-upy, kalendář i vstupenky. Nejbližší věci jsou nahoře.</p></div><span class="status ${r.critical?'bad':'good'}">${r.critical} kritické</span></div><div class="metric-strip"><div class="metric"><span>Po termínu</span><b>${r.overdue.length}</b></div><div class="metric"><span>Dnes</span><b>${r.today.length}</b></div><div class="metric"><span>Do 7 dní</span><b>${r.week.length}</b></div><div class="metric"><span>Do 30 dní</span><b>${r.month.length}</b></div></div><div class="radar35-grid"><section><h3>Po termínu + dnes</h3>${rows([...r.overdue,...r.today],'Nic po termínu ani dnes.')}</section><section><h3>Dalších 7 dní</h3>${rows(r.week,'Příštích 7 dní je čistých.')}</section><section><h3>8–30 dní</h3>${rows(r.month,'Bez termínu v tomto okně.')}</section><section><h3>31–90 dní</h3>${rows(r.quarter,'Bez známého termínu do 90 dní.')}</section></div><div class="decision-note">${h(r.note)}</div>`}
function paint(){if(!openEl)return;const r=deadlineRadar35(store.get()),box=qs('[data-radar35-body]',openEl);setHtml(box,bodyHtml(r));box.querySelectorAll('[data-radar35-target]').forEach(btn=>btn.onclick=()=>openTarget(btn.dataset.radar35Target))}
export function openDeadlineRadar35(){openEl?.remove();const host=qs('#modalHost');if(!host)return;const el=document.createElement('div');el.className='modal';el.innerHTML=`<div class="modal-box radar35-modal"><div data-radar35-body></div><div class="row-actions" style="margin-top:15px"><button class="btn primary" data-radar35-close>Zavřít</button></div></div>`;host.appendChild(el);openEl=el;const close=()=>{el.remove();if(openEl===el)openEl=null};qs('[data-radar35-close]',el).onclick=close;el.onclick=e=>{if(e.target===el)close()};paint()}
function refreshTop(){const actions=document.querySelector('.top-actions');if(!actions)return;const r=deadlineRadar35(store.get());let btn=actions.querySelector('[data-radar35-open]');if(!btn){btn=document.createElement('button');btn.className='btn';btn.dataset.radar35Open='1';btn.onclick=openDeadlineRadar35;const wait=actions.querySelector('[data-followup35-open]');if(wait)wait.insertAdjacentElement('afterend',btn);else actions.insertBefore(btn,actions.firstChild)}setHtml(btn,`◎ <span>Radar</span>${r.critical?` <b class="bad">${r.critical}</b>`:''}`);btn.title=`${r.total} známých termínů do 90 dní`}
function injectTile(){const grid=qs('#moreView .more26-grid');if(!grid)return;let btn=grid.querySelector('[data-radar35-tile]');const r=deadlineRadar35(store.get());if(!btn){btn=document.createElement('button');btn.className='hub-tile';btn.dataset.radar35Tile='1';btn.onclick=openDeadlineRadar35;grid.appendChild(btn)}setHtml(btn,`<span class="hub-icon ${r.critical?'bad':r.week.length?'warn':'good'}">◎</span><span class="hub-copy"><b>Deadline Radar</b><small>${r.overdue.length} po termínu · ${r.week.length} do 7 dní · ${r.month.length} do 30 dní</small></span><span class="hub-arrow">→</span>`)}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;refreshTop();injectTile();if(openEl)paint()})}
function start(){refreshTop();injectTile();store.subscribe(schedule);const top=document.querySelector('.top-actions');if(top)new MutationObserver(schedule).observe(top,{childList:true});const more=qs('#moreView');if(more)new MutationObserver(schedule).observe(more,{childList:true,subtree:false});window.addEventListener('kamil:radar-open',openDeadlineRadar35);window.addEventListener('kamil:navigate',schedule);window.addEventListener('kamil:view-change',schedule)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
