import {store} from './state.js';
import {installRuntimeOwnership1100,ownEvent1100,activateDomain1100,scheduleMicrotask1100} from './runtimeOwnership1100.js';

const VERSION='1140.0.0',OWNER='core.decision1140',HISTORY='kamil_decision_history_1140';
const CLOSED=new Set(['DONE','CLOSED','ARCHIVED','RESOLVED','PAID','CANCELLED','CANCELED','SOLD']);
const A=v=>Array.isArray(v)?v:[],U=v=>String(v||'').toUpperCase(),N=v=>Number(v||0),open=x=>!CLOSED.has(U(x?.status||x?.workflow));
const due=x=>x?.due||x?.dueAt||x?.deadline||x?.followUpAt||x?.nextAt||x?.start||x?.date||null;
const days=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?Math.ceil((t-Date.now())/86400000):null};
const confidence=score=>Math.max(35,Math.min(99,Math.round(42+Number(score||0)*.43)));
const scoreDue=d=>d===null?35:d<0?130+Math.min(20,Math.abs(d)*2):d===0?122:d===1?110:d<=3?96:d<=7?78:d<=14?58:40;
function row(kind,x,route='today',bonus=0){const d=days(due(x)),score=scoreDue(d)+bonus,title=String(x?.title||x?.name||x?.subject||'Položka'),reason=d===null?'chybí pevný termín':d<0?`${Math.abs(d)} d po termínu`:d===0?'termín dnes':d===1?'termín zítra':`termín za ${d} d`;return{kind,title,route,score,confidence:confidence(score),reason,dueDays:d,id:String(x?.id||title)}}
function signature(x){return x?`${x.kind}|${x.id}|${Math.round(x.score)}`:'none'}
function history(){try{return A(JSON.parse(localStorage.getItem(HISTORY)||'[]'))}catch{return[]}}
function remember(top){if(typeof localStorage==='undefined'||!top)return;const h=history(),sig=signature(top);if(h.at(-1)?.signature===sig)return;h.push({signature:sig,title:top.title,kind:top.kind,score:top.score,confidence:top.confidence,at:new Date().toISOString()});while(h.length>100)h.shift();try{localStorage.setItem(HISTORY,JSON.stringify(h))}catch{}}
export function decisionSnapshot1140(s=store.get()){const rows=[];A(s.tasks).filter(open).forEach(x=>rows.push(row('task',x,'today',N(x.priority)*2)));A(s.delegations).filter(open).forEach(x=>rows.push(row('waiting',x,'today',8)));A(s.personalAdmin?.items).filter(open).forEach(x=>rows.push(row('admin',x,'home',2)));A(s.personalInbox?.items).filter(open).slice(0,20).forEach(x=>rows.push(row('inbox',x,'inbox',5)));A(s.calendar?.events).forEach(x=>{const d=days(x.start||x.date);if(d!==null&&d>=0&&d<=14)rows.push(row('calendar',{...x,due:x.start||x.date},'today',12))});A(s.ticketBook?.items).filter(x=>['HOLD','LISTED'].includes(U(x.workflow||'HOLD'))).forEach(x=>rows.push(row('ticket',{...x,due:x.sellBy||x.eventDate||x.date},'tickets',10)));const sorted=rows.sort((a,b)=>b.score-a.score),top=sorted[0]||null;const noAction=!top||top.score<55;const conflicts=sorted.slice(0,8).flatMap((a,i)=>sorted.slice(i+1,8).filter(b=>a.id===b.id&&a.route!==b.route).map(b=>({id:a.id,a:a.route,b:b.route,title:a.title})));const out={version:VERSION,top:noAction?null:top,noAction,recommendation:noAction?'Teď není nic dost silného na to, aby OS něco tlačil před ostatní.':top.title,why:noAction?'Nejvyšší skóre je pod akčním prahem.':`${top.reason}; ${top.kind}; confidence ${top.confidence}%`,top5:sorted.slice(0,5),conflicts,history:history().slice(-20),generatedAt:new Date().toISOString()};remember(out.top);return out}
function refresh(){scheduleMicrotask1100(OWNER,'refresh',()=>{globalThis.__KAMIL_DECISION1140__=decisionSnapshot1140();globalThis.dispatchEvent?.(new CustomEvent('kamil:decision1140',{detail:globalThis.__KAMIL_DECISION1140__}))})}
export function installDecisionCore1140(){if(globalThis.__KAMIL_DECISION1140_INSTALLED__)return decisionSnapshot1140();installRuntimeOwnership1100();activateDomain1100('core',[OWNER]);globalThis.__KAMIL_DECISION1140_INSTALLED__=true;store.subscribe(refresh);ownEvent1100(OWNER,globalThis,'kamil:view-change',refresh);refresh();globalThis.__KAMIL_DECISION1140_API__={snapshot:decisionSnapshot1140,history};return decisionSnapshot1140()}
