import {store} from './state.js';
import {h,qs,formModal,uid,toast} from './utils.js';
import {directorBriefing34,ensureDirectorBook34} from './director34.js';

let openEl=null,queued=false;
const dayText=d=>d===null?'bez termínu':d<0?`${Math.abs(d)} dní po termínu`:d===0?'dnes':d===1?'zítra':`za ${d} dní`;
const tone=p=>Number(p)>=90?'bad':Number(p)>=78?'warn':'good';
const dateText=v=>v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString('cs-CZ'):'—';
const setHtml=(el,html)=>{if(el&&el.innerHTML!==html)el.innerHTML=html};
function ensureBook(){const s=store.get();if(s.directorBook)return;store.mutate('Inicializován Director Mode',x=>ensureDirectorBook34(x),{undo:false,audit:false})}
function topRows(b){return b.top.slice(0,8).map(x=>`<div class="brain34-row director34-deadline ${x.priority>=90?'urgent':x.priority>=78?'soon':''}"><div><b>${h(x.title)}</b><small>${h(x.kind)} · ${h(x.detail)}${x.due?` · ${h(dateText(x.due))} · ${h(dayText(x.days))}`:''}</small></div><div class="brain34-actions"><span class="status ${tone(x.priority)}">${x.priority}</span></div></div>`).join('')||'<div class="empty success-empty">Žádný pracovní bod teď nehoří.</div>'}
function deadlineRows(b){return b.deadlines.map(x=>`<div class="brain34-row director34-deadline ${x.days<=2?'urgent':x.days<=7?'soon':''}"><div><b>${h(x.title)}</b><small>${h(x.note)} · ${h(dateText(x.due))} · ${h(dayText(x.days))}</small></div><div class="brain34-actions"><button class="btn" data-director-done34="${h(x.completionKey)}">Hotovo za měsíc</button></div></div>`).join('')}
function waitingRows(b){return b.waiting.map(x=>`<div class="brain34-row"><div><b>${h(x.title)}</b><small>${h(x.detail)}${x.due?` · ${h(dateText(x.due))} · ${h(dayText(x.days))}`:''}</small></div><div class="brain34-actions">${String(x.id||'').startsWith('waiting|')?`<button class="btn" data-director-waitdone34="${h(x.id)}">Vyřešeno</button>`:''}</div></div>`).join('')||'<div class="empty">Nic ručně označeného jako „čekám na“.</div>'}
function calendarRows(b){return b.calendar.map(x=>`<div class="row"><span>${h(x.title)}</span><b>${h(dateText(x.due))} · ${h(dayText(x.days))}</b></div>`).join('')||'<div class="empty">V příštích 7 dnech není rozpoznaná pracovní událost.</div>'}
function inboxRows(b){return b.inbox.slice(0,8).map(x=>`<div class="row"><div><b>${h(x.title)}</b><div class="muted">${h(x.detail)}</div></div><span class="status ${tone(x.priority)}">${x.priority}</span></div>`).join('')||'<div class="empty">Interní pracovní inbox je čistý nebo zatím neobsahuje rozpoznané pracovní položky.</div>'}
function bodyHtml(b){return `<div class="card-head"><div><div class="eyebrow">DIRECTOR MODE / 41.6</div><h2>Ředitel pobočky · Command Center</h2><p class="muted">Měsíční termíny, pracovní úkoly, delegace, čekání, kalendář a pracovní inbox. Nahoře jen to, co má největší dopad.</p></div><div class="view-head-stat"><b class="${b.critical?'bad':'good'}">${b.critical}</b><span>kritické body</span></div></div><div class="metric-strip"><div class="metric"><span>Do 7 dní</span><b>${b.week}</b></div><div class="metric"><span>Pracovní úkoly</span><b>${b.tasks.length}</b></div><div class="metric"><span>Čekám na</span><b>${b.waiting.length}</b></div><div class="metric"><span>Kalendář</span><b>${b.calendar.length}</b></div><div class="metric"><span>Inbox</span><b>${b.inbox.length}</b></div></div><h3>Co řešit teď</h3><div class="brain34-list">${topRows(b)}</div><h3>Měsíční ředitelské termíny</h3><div class="brain34-list">${deadlineRows(b)}</div><div class="brain34-subgrid"><div><h3>Čekám na někoho</h3>${waitingRows(b)}</div><div><h3>Pracovní kalendář</h3>${calendarRows(b)}</div></div><h3>Pracovní inbox</h3>${inboxRows(b)}<div class="decision-note">${h(b.note)}</div>`}
function paint(){if(!openEl)return;const b=directorBriefing34(store.get()),box=qs('[data-director-body34]',openEl);setHtml(box,bodyHtml(b));box.querySelectorAll('[data-director-done34]').forEach(btn=>btn.onclick=()=>{const key=btn.dataset.directorDone34;store.mutate('Splněn měsíční ředitelský termín',s=>{const book=ensureDirectorBook34(s);book.completions[key]=new Date().toISOString()});paint();toast('Termín označen jako hotový')});box.querySelectorAll('[data-director-waitdone34]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.directorWaitdone34;store.mutate('Uzavřeno čekání',s=>{const book=ensureDirectorBook34(s);book.waiting=book.waiting.filter(x=>x.id!==id)});paint()})}
export function openDirector34(){ensureBook();openEl?.remove();const host=qs('#modalHost');if(!host)return;const el=document.createElement('div');el.className='modal';el.innerHTML=`<div class="modal-box director34-modal"><div data-director-body34></div><div class="row-actions" style="margin-top:15px"><button class="btn" data-director-addtask34>＋ Pracovní úkol</button><button class="btn" data-director-addwait34>＋ Čekám na</button><button class="btn primary" data-director-close34>Zavřít</button></div></div>`;host.appendChild(el);openEl=el;const close=()=>{el.remove();if(openEl===el)openEl=null};qs('[data-director-close34]',el).onclick=close;el.onclick=e=>{if(e.target===el)close()};qs('[data-director-addwait34]',el).onclick=async()=>{close();const data=await formModal('Přidat „čekám na“',`<div class="form-grid"><label class="wide-field">Na co čekáš<input name="title" autofocus required placeholder="Např. potvrzení termínu dodavatele"></label><label>Na koho<input name="person" placeholder="Dodavatel / kolega"></label><label>Termín follow-up<input name="due" type="date"></label></div>`,{submitLabel:'Přidat'});if(data?.title){store.mutate('Přidáno čekání',s=>{const book=ensureDirectorBook34(s);book.waiting.unshift({id:uid('waiting'),title:data.title.trim(),person:data.person?.trim()||'',due:data.due||null,status:'OPEN',createdAt:new Date().toISOString()})});openDirector34()}};qs('[data-director-addtask34]',el).onclick=async()=>{close();const data=await formModal('Přidat pracovní úkol',`<div class="form-grid"><label class="wide-field">Úkol<input name="title" autofocus required></label><label>Termín<input name="due" type="date"></label><label>Priorita<input name="priority" type="number" min="1" max="100" value="75"></label></div>`,{submitLabel:'Přidat'});if(data?.title){store.mutate('Přidán pracovní úkol',s=>{s.tasks=s.tasks||[];s.tasks.unshift({id:uid('task'),title:data.title.trim(),due:data.due||null,priority:Number(data.priority||75),scope:'work',status:'OPEN',createdAt:new Date().toISOString()})});openDirector34()}};paint()}
function injectTile(){const grid=qs('#moreView .more26-grid');if(!grid)return;const b=directorBriefing34(store.get());let btn=grid.querySelector('[data-director-open34]');if(!btn){btn=document.createElement('button');btn.className='hub-tile';btn.dataset.directorOpen34='1';btn.addEventListener('click',openDirector34);grid.appendChild(btn)}setHtml(btn,`<span class="hub-icon ${b.critical?'bad':'good'}">◆</span><span class="hub-copy"><b>Director Mode</b><small>${b.critical?`${b.critical} kritické · `:''}${b.week} do 7 dní · ${b.waiting.length} čekání · ${b.inbox.length} inbox</small></span><span class="hub-arrow">→</span>`)}
function injectTopButton(){const actions=qs('.top-actions');if(!actions)return;let btn=qs('#directorTop34',actions);if(!btn){btn=document.createElement('button');btn.id='directorTop34';btn.dataset.directorTop34='1';btn.className='btn';btn.title='Otevřít Director Mode';btn.addEventListener('click',openDirector34);const theme=qs('#themeToggle33',actions);if(theme)theme.insertAdjacentElement('afterend',btn);else actions.prepend(btn)}const b=directorBriefing34(store.get());setHtml(btn,`◆ <span>Ředitel</span>${b.critical?` <b class="bad">${b.critical}</b>`:''}`)}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;injectTile();injectTopButton();if(openEl)paint()})}
function start(){injectTile();injectTopButton();const view=qs('#moreView');if(view)new MutationObserver(schedule).observe(view,{childList:true,subtree:false});const top=qs('.top-actions');if(top)new MutationObserver(schedule).observe(top,{childList:true,subtree:false});store.subscribe(schedule);window.addEventListener('kamil:director-open',openDirector34);window.addEventListener('kamil:navigate',schedule);window.addEventListener('kamil:view-change',schedule);setTimeout(schedule,300)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
