import {store} from './state.js';
import {documentScanCandidate,documentRecordDraft,findDocumentDuplicate,documentScanner30Note} from './documentScanner30.js';
import {h,uid,qs,qsa,modal,toast} from './utils.js';

const id='documentScanner30Host';
const OCR_SRC='https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.min.js';
const CATEGORIES={PAYMENT:'Platba / faktura',INSURANCE:'Pojištění',DOCUMENT:'Doklad / záruka',SUBSCRIPTION:'Smlouva / předplatné',OTHER:'Ostatní'};
let ocrLoad=null,busy=false;
const setStatus=t=>{const x=qs('#scanner30Status');if(x)x.textContent=t||''};
function opts(selected){return Object.entries(CATEGORIES).map(([k,v])=>`<option value="${k}" ${k===selected?'selected':''}>${h(v)}</option>`).join('')}
function loadOcr(){
 if(window.Tesseract?.recognize)return Promise.resolve(window.Tesseract);if(ocrLoad)return ocrLoad;
 ocrLoad=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=OCR_SRC;s.async=true;s.crossOrigin='anonymous';s.onload=()=>window.Tesseract?.recognize?resolve(window.Tesseract):reject(new Error('OCR engine se nenačetl.'));s.onerror=()=>reject(new Error('OCR engine se nepodařilo stáhnout.'));document.head.appendChild(s)}).catch(e=>{ocrLoad=null;throw e});return ocrLoad;
}
async function fileText(file){
 if(!file)throw new Error('Soubor chybí.');if(file.size>15*1024*1024)throw new Error('Soubor je větší než 15 MB. Pro OCR použij menší fotografii nebo screenshot.');
 if(file.type.startsWith('image/')){setStatus('Načítám lokální OCR…');const T=await loadOcr();const r=await T.recognize(file,'ces+eng',{logger:m=>{if(m.status==='recognizing text'&&Number.isFinite(m.progress))setStatus(`OCR ${Math.round(m.progress*100)} %`)}});return {text:r?.data?.text||'',method:'OCR'};}
 if(/^text\//.test(file.type)||/\.(txt|md|csv|json)$/i.test(file.name))return {text:await file.text(),method:'TEXT_FILE'};
 throw new Error('Tento formát zatím bezpečně nepodporuji. PDF otevři a vlož text nebo použij screenshot stránky.');
}
function navMode(category){return category==='INSURANCE'?'insurance':category==='DOCUMENT'?'documents':category==='PAYMENT'?'payments':'contracts'}
async function review(scan,rawText){
 const c=scan.candidate,duplicate=findDocumentDuplicate(store.get(),scan);if(duplicate){await modal('Dokument už vypadá evidovaný',`<div class="decision-note warn"><b>${h(duplicate.title||'Existující položka')}</b><div>Stejný lokální fingerprint už má aktivní položka. Novou kopii automaticky nevytvářím.</div></div><p class="muted">Fingerprint slouží jen jako ochrana proti opakovanému importu stejného OCR obsahu.</p>`,[{label:'Zavřít',value:true,primary:true}]);return}
 const warnings=(c.warnings||[]).map(x=>`<div class="decision-note warn">${h(x)}</div>`).join(''),rawPreview=String(rawText||'').slice(0,12000);
 const body=`<div class="metric-strip"><div class="metric"><span>Typ</span><b>${h(c.typeLabel)}</b></div><div class="metric"><span>Confidence</span><b>${c.confidence.score}/100</b></div><div class="metric"><span>Text</span><b>${c.textStats.characters.toLocaleString('cs-CZ')} znaků</b></div><div class="metric"><span>Citlivé markery</span><b>${c.sensitiveKinds.length}</b></div></div>${warnings}<div class="form-grid capture-form" style="margin-top:12px"><label class="wide-field">Název<input id="scanner30Title" value="${h(c.title)}"></label><label>Kategorie<select id="scanner30Category">${opts(c.category)}</select></label><label>Poskytovatel<input id="scanner30Provider" value="${h(c.provider)}"></label><label>Částka<input id="scanner30Amount" type="number" min="0" step="0.01" value="${c.amount===null?'':h(c.amount)}"></label><label>Měna<select id="scanner30Currency"><option ${c.currency==='CZK'?'selected':''}>CZK</option><option ${c.currency==='EUR'?'selected':''}>EUR</option><option ${c.currency==='USD'?'selected':''}>USD</option></select></label><label>Splatnost<input id="scanner30Due" type="date" value="${h(c.dueDate||'')}"></label><label>Expirace / platnost do<input id="scanner30Expiry" type="date" value="${h(c.expiryDate||'')}"></label><label>Výročí / obnova<input id="scanner30Renewal" type="date" value="${h(c.renewalDate||'')}"></label><label class="wide-field">Moje poznámka<textarea id="scanner30Notes" rows="2"></textarea></label></div><details style="margin-top:12px"><summary>Dočasně zobrazit OCR text ke kontrole</summary><pre style="white-space:pre-wrap;max-height:260px;overflow:auto" class="muted">${h(rawPreview)}</pre><p class="muted">Tento text zůstává jen v právě otevřeném náhledu a při uložení se zahodí.</p></details><div class="decision-note"><b>Co se uloží</b><div>Jen potvrzená metadata výše + fingerprint, název zdroje, typ zdroje a confidence. Raw obrázek ani raw OCR text ne.</div></div>`;
 const ok=await modal('Document Scanner · potvrdit návrh',body,[{label:'Zrušit',value:false},{label:'Uložit metadata',value:true,primary:true}]);if(!ok)return;
 const value=id=>qs(id)?.value?.trim()||'',amountRaw=value('#scanner30Amount'),draft=documentRecordDraft(scan,{title:value('#scanner30Title'),category:value('#scanner30Category'),provider:value('#scanner30Provider'),amount:amountRaw===''?null:Number(amountRaw),currency:value('#scanner30Currency')||c.currency,dueDate:value('#scanner30Due'),expiryDate:value('#scanner30Expiry'),renewalDate:value('#scanner30Renewal'),notes:value('#scanner30Notes')},new Date());if(!draft.ok)return toast(draft.message||'Návrh se nepodařilo připravit');
 const now=new Date().toISOString(),record={id:uid('personal-admin'),...draft.record,createdAt:now,updatedAt:now};store.mutate(`Document Scanner: ${record.title}`,s=>{s.personalAdmin=s.personalAdmin||{items:[]};s.personalAdmin.items=Array.isArray(s.personalAdmin.items)?s.personalAdmin.items:[];s.personalAdmin.items.unshift(record)});toast('Potvrzená metadata dokumentu uložena');window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:'home'}));queueMicrotask(()=>window.dispatchEvent(new CustomEvent('kamil:home-open',{detail:navMode(record.category)})));
}
async function processText(text,source){if(busy)return;busy=true;try{setStatus('Analyzuji bezpečná metadata…');const scan=documentScanCandidate(text,source);if(!scan.ok)return toast(scan.message||'Text se nepodařilo analyzovat');setStatus('');await review(scan,text)}catch(e){toast(e?.message||'Scanner selhal');setStatus('Scanner selhal')}finally{busy=false}}
async function chooseFile(file){if(!file||busy)return;busy=true;try{const x=await fileText(file);busy=false;await processText(x.text,{name:file.name,type:file.type,size:file.size,method:x.method})}catch(e){busy=false;setStatus('');toast(e?.message||'Soubor se nepodařilo zpracovat')}}
async function pasteText(){const ok=await modal('Vložit text dokumentu',`<label class="wide-field">Text<textarea id="scanner30Paste" rows="12" autofocus placeholder="Vlož text faktury, smlouvy, pojistky nebo dokladu…"></textarea></label><p class="muted">Raw text se po zavření náhledu neukládá.</p>`,[{label:'Zrušit',value:false},{label:'Analyzovat',value:true,primary:true}]);if(!ok)return;const text=qs('#scanner30Paste')?.value||'';if(!text.trim())return toast('Vlož text dokumentu');await processText(text,{name:'vložený text',type:'text/plain',size:text.length,method:'PASTE'})}
function render(){const view=qs('#moreView');if(!view)return;qs(`#${id}`,view)?.remove();const host=document.createElement('div');host.id=id;host.className='card';host.innerHTML=`<div class="card-head"><div><div class="eyebrow">DOCUMENT SCANNER / 30.1</div><h2>Vyfotit → rozpoznat → potvrdit</h2><p class="muted">Fotka se zpracuje OCR lokálně v prohlížeči. Do Kamil OS se uloží až tebou potvrzená metadata.</p></div><span class="status good">PRIVACY FIRST</span></div><input id="scanner30File" type="file" accept="image/*,.txt,.md,.csv,.json,text/plain,text/csv,application/json" capture="environment" hidden><div class="row-actions"><button class="btn primary" id="scanner30Camera">📷 Vyfotit / obrázek</button><button class="btn" id="scanner30PasteBtn">Vložit text</button></div><div id="scanner30Status" class="muted" style="margin-top:8px"></div><div class="decision-note" style="margin-top:10px">${h(documentScanner30Note)} OCR knihovna a jazyková data se při prvním obrazovém skenu načtou z jsDelivr; samotný dokument se z této funkce neposílá do Supabase. PDF zatím použij jako screenshot stránky nebo vložený text.</div>`;const head=view.querySelector('.view-head');if(head)head.insertAdjacentElement('afterend',host);else view.prepend(host);qs('#scanner30Camera',host)?.addEventListener('click',()=>qs('#scanner30File',host)?.click());qs('#scanner30File',host)?.addEventListener('change',e=>{const f=e.target.files?.[0];e.target.value='';if(f)chooseFile(f)});qs('#scanner30PasteBtn',host)?.addEventListener('click',pasteText)}
function start(){const view=qs('#moreView');if(!view)return;new MutationObserver(()=>{if(view.children.length&&!qs(`#${id}`,view))queueMicrotask(render)}).observe(view,{childList:true,subtree:false});window.addEventListener('kamil:navigate',e=>{if(e.detail==='more')queueMicrotask(render)});render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
