import {documentImportHints} from './personalPlus29.js';

const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number(v)||0));
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o||{},k);
const TYPE_LABELS={INVOICE:'Faktura / vyúčtování',INSURANCE:'Pojištění',CONTRACT:'Smlouva',RECEIPT:'Účtenka',WARRANTY:'Záruka',ID_DOCUMENT:'Osobní doklad',VEHICLE_DOCUMENT:'Doklad k vozidlu',OTHER:'Jiný dokument'};
const CATEGORY_BY_TYPE={INVOICE:'PAYMENT',INSURANCE:'INSURANCE',CONTRACT:'OTHER',RECEIPT:'PAYMENT',WARRANTY:'DOCUMENT',ID_DOCUMENT:'DOCUMENT',VEHICLE_DOCUMENT:'DOCUMENT',OTHER:'OTHER'};

function detectType(text){const q=norm(text);if(/obcansk[yy]|obcansky prukaz|cestovni pas|ridicsk[yy] prukaz/.test(q))return'ID_DOCUMENT';if(/technick[yy] prukaz|osvedceni o registraci|\bstk\b|vozidla|\bvin\b/.test(q))return'VEHICLE_DOCUMENT';if(/pojist|pojistna smlouva|pojisteni/.test(q))return'INSURANCE';if(/faktura|danovy doklad|vyuctovani|k uhrade/.test(q))return'INVOICE';if(/uctenka|paragon|pokladni doklad/.test(q))return'RECEIPT';if(/zarucni|zaruka|warranty/.test(q))return'WARRANTY';if(/smlouva|dodatek|tarif|predplat/.test(q))return'CONTRACT';return'OTHER'}
function validDate(d,m,y){const x=new Date(y,m-1,d);return x.getFullYear()===y&&x.getMonth()===m-1&&x.getDate()===d?`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`:null}
function dateEvidence(raw){const out=[],rx=/\b([0-3]?\d)[.\/-]\s*([01]?\d)[.\/-]\s*(20\d{2})\b/g;let m;while((m=rx.exec(raw))){const date=validDate(Number(m[1]),Number(m[2]),Number(m[3]));if(!date)continue;const before=norm(raw.slice(Math.max(0,m.index-60),m.index)),ctx=before.slice(-60);let kind='UNKNOWN';if(/splatnost|k uhrade|uhradit do|zaplatit do/.test(ctx))kind='DUE';else if(/platnost do|plati do|expir|konec platnosti|do konce/.test(ctx))kind='EXPIRY';else if(/vyroci|obnoveni|renewal|prodlouzeni/.test(ctx))kind='RENEWAL';else if(/vystaven|datum dokladu|uzavren|sjednan/.test(ctx))kind='ISSUE';out.push({date,kind})}const seen=new Set();return out.filter(x=>{const k=`${x.kind}|${x.date}`;if(seen.has(k))return false;seen.add(k);return true}).slice(0,10)}
function sensitiveKinds(raw){const defs=[['RODNE_CISLO',/rodn[eé]\s+[cč][ií]slo/i],['DOCUMENT_NUMBER',/[cč][ií]slo\s+(?:dokladu|pr[uů]kazu|pasu)/i],['CONTRACT_NUMBER',/[cč][ií]slo\s+smlouvy/i],['IBAN',/\bIBAN\b/i],['BANK_ACCOUNT',/[cč][ií]slo\s+[uú][cč]tu/i],['VARIABLE_SYMBOL',/variabiln[ií]\s+symbol/i],['CARD_NUMBER',/[cč][ií]slo\s+karty/i]];return defs.filter(([,rx])=>rx.test(raw)).map(([k])=>k)}
function fingerprint(raw){const text=norm(raw).replace(/\s+/g,' ');let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return `scan30-${(h>>>0).toString(16).padStart(8,'0')}-${text.length}`}
function firstDate(dates,kind){return dates.find(x=>x.kind===kind)?.date||null}
function confidence({type,hints,dates,textLength,sourceName}){let score=0;const reasons=[];if(type!=='OTHER'){score+=20;reasons.push('rozpoznaný typ')}if(hints.title){score+=10;reasons.push('název')}if(hints.provider){score+=15;reasons.push('poskytovatel')}if(finite(hints.amount)){score+=20;reasons.push('částka')}if(dates.some(x=>x.kind!=='UNKNOWN')){score+=20;reasons.push('datum s kontextem')}else if(dates.length){score+=8;reasons.push('datum bez kontextu')}if(textLength>=100){score+=10;reasons.push('dostatek textu')}if(sourceName){score+=5;reasons.push('zdrojový soubor')}score=Math.round(clamp(score));return {score,label:score>=70?'HIGH':score>=45?'MEDIUM':'LOW',reasons}}
export function documentScanCandidate(text='',source={}){
 const raw=String(text||'').slice(0,60000);if(!raw.trim())return {ok:false,code:'NO_TEXT',message:'OCR ani vložený text neobsahuje použitelný obsah.'};
 const imported=documentImportHints(raw),type=detectType(raw),dates=dateEvidence(raw),sensitive=sensitiveKinds(raw),hints=imported.hints||{},conf=confidence({type,hints,dates,textLength:raw.length,sourceName:source.name});
 const dueDate=firstDate(dates,'DUE'),expiryDate=firstDate(dates,'EXPIRY'),renewalDate=firstDate(dates,'RENEWAL'),issueDate=firstDate(dates,'ISSUE'),fallbackDates=dates.filter(x=>x.kind==='UNKNOWN').map(x=>x.date);
 const candidate={type,typeLabel:TYPE_LABELS[type],category:CATEGORY_BY_TYPE[type],title:String(hints.title||source.name||TYPE_LABELS[type]).slice(0,120),provider:String(hints.provider||'').slice(0,120),amount:finite(hints.amount)?Number(hints.amount):null,currency:String(hints.currency||'CZK').toUpperCase(),dueDate,expiryDate,renewalDate,issueDate,otherDates:fallbackDates.slice(0,4),confidence:conf,sensitiveKinds:sensitive,fingerprint:fingerprint(raw),source:{name:String(source.name||'').slice(0,180),type:String(source.type||'').slice(0,100),size:finite(source.size)?Math.max(0,Number(source.size)):null,method:String(source.method||'TEXT').toUpperCase()},textStats:{characters:raw.length,lines:raw.split(/\r?\n/).filter(x=>x.trim()).length},warnings:[]};
 if(sensitive.length)candidate.warnings.push(`Nalezeny citlivé identifikátory (${sensitive.length} typů). Jejich hodnoty se do návrhu nevytěžují ani neukládají.`);if(!dueDate&&!expiryDate&&!renewalDate&&fallbackDates.length)candidate.warnings.push('Datum bylo nalezeno bez dostatečného kontextu; před uložením ho ověř ručně.');if(type==='OTHER')candidate.warnings.push('Typ dokumentu není spolehlivě rozpoznaný; kategorii potvrď ručně.');
 return {ok:true,code:'OK',candidate,note:'Document Scanner 30.1 vrací pouze bezpečný návrh metadat. Raw OCR text ani citlivé identifikátory nejsou součástí výsledného kandidáta. Fingerprint slouží jen k lokální detekci stejného obsahu a není kryptografický důkaz.'};
}
export function findDocumentDuplicate(s={},scan){const fp=scan?.candidate?.fingerprint||scan?.fingerprint;if(!fp)return null;return (s.personalAdmin?.items||[]).find(x=>x?.scanner30?.fingerprint===fp&&String(x.status||'ACTIVE').toUpperCase()!=='ARCHIVED')||null}
function docKind(){return'OTHER'}
const dateOverride=(overrides,key,fallback)=>own(overrides,key)?(String(overrides[key]||'').trim()||null):fallback||null;
export function documentRecordDraft(scan,overrides={},now=new Date()){
 const c=scan?.candidate||scan;if(!c?.fingerprint)return {ok:false,code:'INVALID_SCAN',message:'Chybí bezpečný scanner kandidát.'};const category=String(overrides.category||c.category||'OTHER').toUpperCase(),title=String(overrides.title||c.title||c.typeLabel||'Dokument').trim().slice(0,160),provider=String(overrides.provider??c.provider??'').trim().slice(0,160),amount=own(overrides,'amount')?(finite(overrides.amount)?Math.max(0,Number(overrides.amount)):null):c.amount,currency=String(overrides.currency||c.currency||'CZK').toUpperCase(),dueDate=dateOverride(overrides,'dueDate',c.dueDate),expiryDate=dateOverride(overrides,'expiryDate',c.expiryDate),renewalDate=dateOverride(overrides,'renewalDate',c.renewalDate);
 const notes=[`Document Scanner 30.1 · ${c.typeLabel||c.type||'dokument'} · confidence ${c.confidence?.score??0}/100.`,c.sensitiveKinds?.length?'Citlivé identifikátory byly rozpoznány pouze jako přítomné; jejich hodnoty nejsou uložené.':'',overrides.notes||''].filter(Boolean).join(' ');
 const scannedAt=new Date(now).toISOString(),record={title,category,provider,amount:finite(amount)?amount:null,currency,cadence:'ONCE',nextDue:dueDate,renewalDate:renewalDate||expiryDate,status:'ACTIVE',notes,scanner30:{fingerprint:c.fingerprint,sourceName:c.source?.name||'',sourceType:c.source?.type||'',sourceSize:c.source?.size??null,sourceMethod:c.source?.method||'TEXT',documentType:c.type,confidence:Number(c.confidence?.score||0),sensitiveKinds:[...(c.sensitiveKinds||[])],scannedAt}};
 if(category==='DOCUMENT')record.document={kind:docKind(c.type),expiryDate:expiryDate||renewalDate||null,reminderDate:null,holder:''};if(category==='INSURANCE')record.insurance={kind:'OTHER',renewalDate:renewalDate||expiryDate||null,endDate:expiryDate||null,insured:''};
 return {ok:true,record,note:'Návrh neobsahuje raw OCR text ani hodnoty citlivých identifikátorů. Uložení musí potvrdit uživatel.'};
}
export const documentScanner30Note='OCR je pouze vstup do návrhu. Nic se neukládá bez potvrzení; raw dokument a raw OCR text nejsou součástí běžného Kamil OS state. Citlivé identifikátory se záměrně nevytěžují.';
