import {store} from './state.js';
import {h,qs,uid,toast} from './utils.js';
import {emailWorkflow35,markInboxResolved35,convertInboxToWaiting35,closeWaitingFromReply35} from './emailWorkflow35.js';

let openEl=null,queued=false;
const id='emailControl35Host';
const tone=p=>Number(p)>=90?'bad':Number(p)>=78?'warn':'good';
const whenText=v=>{const d=new Date(v);if(!Number.isFinite(d.getTime()))return'—';return d.toLocaleString('cs-CZ',{day:'numeric',month:'numeric',hour:'2-digit',minute:'2-digit'})};

function mutate(label,fn){store.mutate(label,fn);paint();renderToday();refreshTile();refreshTop()}
function resolveMail(emailId){mutate('E-mail označen jako vyřešený',s=>markInboxResolved35(s,emailId));toast('E-mail je vyřešený')}
function waitOnMail(emailId){mutate('E-mail převeden do Waiting For',s=>convertInboxToWaiting35(s,emailId,uid,new Date(),3));toast('Přidáno do Waiting For · první kontrola za 3 dny')}
function closeWaiting(idValue){mutate('Waiting For uzavřeno po odpovědi',s=>closeWaitingFromReply35(s,idValue));toast('Čekání uzavřeno')}
function openWaiting(){window.dispatchEvent(new CustomEvent('kamil:waiting-open'))}

function triageRow(x){return `<div class="email35-row"><div><div class="email35-title"><span class="status ${tone(x.priority)}">MAIL ${x.priority}</span><b>${h(x.title)}</b></div><small>${x.person?`${h(x.person)} · `:''}${h(x.reason)}${x.at?` · ${h(whenText(x.at))}`:''}</small></div><div class="email35-actions"><button class="btn" data-email35-done="${h(x.id)}">Hotovo</button><button class="btn primary" data-email35-wait="${h(x.id)}">Vyřízeno → čekám</button></div></div>`}
function replyRow(x){return `<div class="email35-row reply"><div><div class="email35-title"><span class="status good">ODPOVĚĎ</span><b>${h(x.title)}</b></div><small>${x.replyFrom?`${h(x.replyFrom)} · `:''}${h(x.reason)}</small></div><div class="email35-actions"><button class="btn primary" data-email35-closewait="${h(x.id)}">Uzavřít čekání</button></div></div>`}
function followRow(x){return `<div class="email35-row urgent"><div><div class="email35-title"><span class="status bad">URGOVAT</span><b>${h(x.title)}</b></div><small>${x.person?`Čekám na ${h(x.person)} · `:''}${h(x.reason)}</small></div><div class="email35-actions"><button class="btn" data-email35-openwaiting>Waiting For</button></div></div>`}

function bodyHtml(b){return `<div class="card-head"><div><div class="eyebrow">E-MAIL CONTROL / 35.2</div><h2>Inbox → akce → Waiting For</h2><p class="muted">Důležité e-maily nezůstanou viset. Po vyřízení je jedním klikem převedeš do čekání a příchozí odpověď pak OS navrhne uzavřít.</p></div><span class="status ${b.needsAction||b.readyToClose||b.followUpNow?'warn':'good'}">${b.needsAction+b.readyToClose+b.followUpNow} k zásahu</span></div><div class="metric-strip"><div class="metric"><span>E-maily řešit</span><b>${b.needsAction}</b></div><div class="metric"><span>Odpovědi přišly</span><b>${b.readyToClose}</b></div><div class="metric"><span>Urgovat dnes</span><b>${b.followUpNow}</b></div><div class="metric"><span>Celkem čekám</span><b>${b.waitingTotal}</b></div></div>${b.replies.length?`<h3>Odpovědi čekající na uzavření</h3><div class="email35-list">${b.replies.map(replyRow).join('')}</div>`:''}${b.followUps.length?`<h3>Čekání, která už mají být urgována</h3><div class="email35-list">${b.followUps.map(followRow).join('')}</div>`:''}<h3>Pracovní / důležitý inbox</h3><div class="email35-list">${b.triage.slice(0,12).map(triageRow).join('')||'<div class="empty success-empty">Žádný důležitý e-mail teď nečeká na rozhodnutí.</div>'}</div><div class="decision-note">${h(b.note)}</div>`}

function bind(root,b){root.querySelectorAll('[data-email35-done]').forEach(btn=>btn.onclick=()=>resolveMail(btn.dataset.email35Done));root.querySelectorAll('[data-email35-wait]').forEach(btn=>btn.onclick=()=>waitOnMail(btn.dataset.email35Wait));root.querySelectorAll('[data-email35-closewait]').forEach(btn=>btn.onclick=()=>closeWaiting(btn.dataset.email35Closewait));root.querySelectorAll('[data-email35-openwaiting]').forEach(btn=>btn.onclick=openWaiting)}
function paint(){if(!openEl)return;const box=qs('[data-email35-body]',openEl),b=emailWorkflow35(store.get());box.innerHTML=bodyHtml(b);bind(box,b)}

export function openEmailControl35(){openEl?.remove();const host=qs('#modalHost');if(!host)return;const el=document.createElement('div');el.className='modal';el.innerHTML=`<div class="modal-box email35-modal"><div data-email35-body></div><div class="row-actions" style="margin-top:15px"><button class="btn" data-email35-waiting>Otevřít Waiting For</button><button class="btn primary" data-email35-close>Zavřít</button></div></div>`;host.appendChild(el);openEl=el;const close=()=>{el.remove();if(openEl===el)openEl=null};qs('[data-email35-close]',el).onclick=close;qs('[data-email35-waiting]',el).onclick=()=>{close();openWaiting()};el.onclick=e=>{if(e.target===el)close()};paint()}

function summaryRow(x){const label=x.type==='REPLY'?'Odpověď':x.type==='FOLLOW_UP'?'Urgovat':'E-mail';return `<div class="email35-summary-row"><div><span class="status ${tone(x.priority)}">${label}</span><b>${h(x.title)}</b><small>${h(x.reason)}</small></div></div>`}
function renderToday(){const view=qs('#todayView');if(!view?.querySelector('.view-head'))return;qs(`#${id}`,view)?.remove();const b=emailWorkflow35(store.get()),action=b.needsAction+b.readyToClose+b.followUpNow;if(!action)return;const host=document.createElement('div');host.id=id;host.className='card email35-card';host.innerHTML=`<div class="card-head"><div><div class="eyebrow">E-MAIL CONTROL / 35.2</div><h2>${b.readyToClose?`${b.readyToClose} odpovědí už můžeš uzavřít`:b.followUpNow?`${b.followUpNow} čekání už máš urgovat`:`${b.needsAction} důležitých e-mailů čeká na rozhodnutí`}</h2><p class="muted">Inbox a Waiting For v jednom workflow.</p></div><button class="btn primary" data-email35-open>Otevřít mail control →</button></div><div class="email35-summary">${b.top.slice(0,3).map(summaryRow).join('')}</div>`;const pulse=qs('#changePulse35Host',view),focus=qs('#focusAction35Host',view);if(pulse)pulse.insertAdjacentElement('afterend',host);else if(focus)focus.insertAdjacentElement('afterend',host);else view.querySelector('.view-head')?.insertAdjacentElement('afterend',host);qs('[data-email35-open]',host).onclick=openEmailControl35}

function refreshTile(){const grid=qs('#moreView .more26-grid');if(!grid)return;const b=emailWorkflow35(store.get());let btn=grid.querySelector('[data-email35-tile]');if(!btn){btn=document.createElement('button');btn.className='hub-tile';btn.dataset.email35Tile='1';btn.onclick=openEmailControl35;grid.appendChild(btn)}const action=b.needsAction+b.readyToClose+b.followUpNow;btn.innerHTML=`<span class="hub-icon ${action?'warn':'good'}">✉</span><span class="hub-copy"><b>E-mail Control</b><small>${b.needsAction} řešit · ${b.readyToClose} odpovědí · ${b.followUpNow} urgovat</small></span><span class="hub-arrow">→</span>`}
function refreshTop(){const actions=qs('.top-actions');if(!actions)return;const b=emailWorkflow35(store.get()),action=b.needsAction+b.readyToClose+b.followUpNow;let btn=actions.querySelector('[data-email35-open]');if(!action){btn?.remove();return}if(!btn){btn=document.createElement('button');btn.className='btn';btn.dataset.email35Open='1';btn.onclick=openEmailControl35;const waiting=actions.querySelector('[data-followup35-open]');if(waiting)waiting.insertAdjacentElement('afterend',btn);else actions.insertBefore(btn,actions.firstChild)}btn.innerHTML=`✉ <span>Mail</span> <b class="${action?'warn':'good'}">${action}</b>`;btn.title='Otevřít E-mail Control'}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;renderToday();refreshTile();refreshTop();if(openEl)paint()})}
function start(){renderToday();refreshTile();refreshTop();store.subscribe(schedule);const view=qs('#todayView');if(view)new MutationObserver(()=>{if(!qs(`#${id}`,view))schedule()}).observe(view,{childList:true,subtree:false});const more=qs('#moreView');if(more)new MutationObserver(schedule).observe(more,{childList:true,subtree:true});const top=qs('.top-actions');if(top)new MutationObserver(schedule).observe(top,{childList:true});window.addEventListener('kamil:email-workflow-open',openEmailControl35);window.addEventListener('kamil:navigate',schedule)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
