import {store} from './state.js';
import {xtbBoard} from './live24.js';
import {loadTicketCloud660} from './ticketCloud660.js';
import {unifiedCapitalState160} from './unifiedCapital160.js';
import {dataTrustState163} from './dataTrust163.js';
import {h,money} from './utils.js';
const U=v=>String(v||'').toUpperCase(),A=v=>Array.isArray(v)?v:[];
function action(label,detail,tone='normal'){return{label,detail,tone}}
export async function executiveCommandState164(){const s=store.get(),items=[];let cloud=null;try{cloud=await loadTicketCloud660()}catch{}if(cloud?.ok){const und=A(cloud.inventory).filter(x=>U(x.market_status)==='SOLD_UNDELIVERED'),wait=A(cloud.inventory).filter(x=>U(x.market_status)==='SOLD_WAITING_PAYMENT');if(und.length)items.push(action(`${und.length}× ticket doručit`,'Prodané, ale převod ještě není potvrzený.','warn'));if(wait.length)items.push(action(`${wait.length}× čeká payout`,'Po doručení čeká skutečná platba.','normal'))}const risky=xtbBoard(s).filter(x=>['REVIEW','VERIFY_DATA'].includes(U(x.d?.action))||String(x.d?.reason||'').toLowerCase().includes('data'));if(risky.length)items.push(action(`${risky.length}× XTB prověřit data`,risky.slice(0,3).map(x=>x.p.ticker||x.p.symbol||x.p.name).join(', '),'warn'));const trust=await dataTrustState163();if(trust.errors)items.push(action(`${trust.errors}× datová chyba`,'Data Trust Center blokuje jisté rozhodnutí.','bad'));else if(trust.warnings||trust.unknown)items.push(action(`${trust.warnings+trust.unknown}× datová kontrola`,'Některé zdroje jsou neúplné nebo ještě neověřené.','warn'));const capital=await unifiedCapitalState160(s);return{items,capital,trust}}
export async function enhanceExecutiveCommand164(){const root=document.querySelector('.dashboard110');if(!root)return;root.querySelector('[data-exec164]')?.remove();const x=await executiveCommandState164(),sec=document.createElement('section');sec.dataset.exec164='1';sec.className='ec164';const known=x.capital.knownCapital,top=x.items.slice(0,6);sec.innerHTML=`<div class="ec164-top"><div><div class="eyebrow">OS 164 · EXECUTIVE COMMAND CENTER</div><h1>${top.length?'Co teď vyžaduje pozornost':'Žádná známá akce z ověřených modulů'}</h1><p>${top.length?'Priorita je sestavená jen ze stavů, které OS skutečně zná.':'To neznamená, že nejsou jiné povinnosti mimo načtená data.'}</p></div><div class="ec164-cap"><small>Známý kapitál</small><b>${money(known)}</b><span>${x.capital.cashKnown?'včetně explicitní hotovosti':'hotovost není explicitně zadaná'}</span></div></div><div class="ec164-actions">${top.map((a,i)=>`<article class="${a.tone}"><span>${i+1}</span><div><b>${h(a.label)}</b><small>${h(a.detail)}</small></div></article>`).join('')||'<article class="normal"><span>✓</span><div><b>Bez známé akutní akce</b><small>Podívej se níže na jednotlivé moduly a jejich coverage.</small></div></article>'}</div>`;root.prepend(sec);window.__KAMIL_EXEC164__={at:Date.now(),actions:top.length,capital:x.capital};return x}
export const executiveCommand164Info={factsOnly:true,maxActions:6,knownCapitalOnly:true};