import {buildFinanceCommand258} from './financeCommand258.js';
import {buildTicketCommand268} from './ticketCommand268.js';
import {buildManagerOS324} from './domainOS328.js';
const money=x=>`${Math.round(Number(x||0)).toLocaleString('cs-CZ')} Kč`,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function openView(v){document.querySelector(`.main-nav [data-view="${v}"],.bottom-nav [data-view="${v}"]`)?.click()}
function renderToday(){const host=document.querySelector('#todayView');if(!host)return;const f=buildFinanceCommand258(),t=buildTicketCommand268(),m=buildManagerOS324();let box=host.querySelector('[data-exec340]');if(!box){box=document.createElement('section');box.className='exec340';box.dataset.exec340='1';host.prepend(box)}box.innerHTML=`<div class="exec340-head"><div><small>KAMIL OS 4.0 · EXECUTIVE</small><h2>Jedna obrazovka pro to důležité.</h2></div><small>${new Intl.DateTimeFormat('cs-CZ',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</small></div><div class="exec340-grid"><button data-go="money"><span>Volný kapitál</span><b>${money(f.deployable)}</b><small>${f.concentration.length} koncentrovaných pozic</small></button><button data-go="tickets"><span>Vstupenky</span><b>${t.active.length} aktivních</b><small>${t.blocked.length} BUY blokováno</small></button><button data-go="more"><span>Práce</span><b>${m.rows.length} otevřených</b><small>${m.overdue.length} po termínu</small></button><button data-go="more"><span>Systém</span><b>${window.__KAMIL_HEALTH340__?.ok?'OK':'Kontrola'}</b><small>${(window.__KAMIL_BOOT_ERRORS__||[]).length} JS chyb</small></button></div>`;box.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.go)))}
function renderManager(){const host=document.querySelector('#moreView');if(!host)return;const m=buildManagerOS324();let box=host.querySelector('[data-manager340]');if(!box){box=document.createElement('section');box.className='manager340';box.dataset.manager340='1';host.prepend(box)}box.innerHTML=`<div class="manager340-card"><header><div><small>MANAGER OS</small><h3>Pracovní radar</h3></div><b>${m.overdue.length} po termínu</b></header><div class="manager340-list">${m.rows.slice(0,8).map(x=>`<div class="manager340-row"><span><b>${esc(x.title||x.name||'Položka')}</b><small>${esc(x.area||x.category||'práce')}</small></span><small>${x.due?new Date(x.due).toLocaleDateString('cs-CZ'):x.followUpAt?new Date(x.followUpAt).toLocaleDateString('cs-CZ'):'bez termínu'}</small></div>`).join('')||'<small>Žádné otevřené pracovní položky.</small>'}</div></div>`}
function ensureCss(){if(document.querySelector('link[data-os340]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./os340.css';l.dataset.os340='1';document.head.appendChild(l)}
export function installExecutive340(){ensureCss();let t=0;const schedule=()=>{clearTimeout(t);t=setTimeout(()=>{renderToday();renderManager()},100)};window.addEventListener('kamil:view-change',schedule);window.addEventListener('kamil:view',schedule);setTimeout(schedule,650);window.__KAMIL_EXECUTIVE340__={version:340,refresh:schedule}}
