const VERSION=366;
const KEY='kamil-os-execution-state-364';
const FOLLOW_KEY='kamil-os-followups-365';
const STATES={NOW:'Udělej teď',WAITING:'Čekám',RECHECK:'Zkontrolovat později',IGNORE:'Ignorovat'};
const DAY=86400000,parse=(x,f={})=>{try{return JSON.parse(x)||f}catch{return f}},save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
let overrides=parse(localStorage.getItem(KEY),{}),followups=parse(localStorage.getItem(FOLLOW_KEY),{}),model={version:VERSION,groups:{NOW:[],WAITING:[],RECHECK:[],IGNORE:[]},counts:{NOW:0,WAITING:0,RECHECK:0,IGNORE:0},dueFollowups:[],waitingPeople:[],queue:[],at:null};
const id=x=>`${x?.refType||x?.key||'item'}:${x?.refId||x?.title||''}`,emit=(detail={})=>window.dispatchEvent(new CustomEvent('kamil:execution-state364-updated',{detail}));
function automatic(x){const text=`${x?.title||''} ${x?.reason||''}`.toLowerCase(),score=Number(x?.score)||0;if(/čekám|čekame|odpověď|odpoved|waiting|awaiting|blok|blocked/.test(text))return'WAITING';if(score>=95||x?.refType==='manager-duty'||/po termínu|dnes|urgent/.test(text))return'NOW';if(['ticket','investment'].includes(x?.refType)||/review|zkontrol|cena|pozici/.test(text))return'RECHECK';if(score<65)return'IGNORE';return'NOW'}
const defaultDays=state=>state==='WAITING'?2:state==='RECHECK'?3:null;
function classify(x){const key=id(x),manual=overrides[key],state=STATES[manual]?manual:automatic(x),f=followups[key]||null,due=!!f?.dueAt&&Number(f.dueAt)<=Date.now(),last=Number(f?.lastContactAt||f?.setAt||0),waitingAgeDays=last?Math.max(0,Math.floor((Date.now()-last)/DAY)):null;return{...x,executionId:key,executionState:state,manual:!!STATES[manual],followup:f,followupDue:due,waitingFor:String(f?.waitingFor||''),lastContactAt:last||null,waitingAgeDays}}
function build(){const api=window.__KAMIL_FOCUS_QUEUE335__,queue=(api?.model?.queue||[]).map(classify),groups={NOW:[],WAITING:[],RECHECK:[],IGNORE:[]};queue.forEach(x=>groups[x.executionState].push(x));const dueFollowups=queue.filter(x=>x.followupDue&&['WAITING','RECHECK'].includes(x.executionState)).sort((a,b)=>Number(a.followup?.dueAt||0)-Number(b.followup?.dueAt||0));const peopleMap=new Map();groups.WAITING.forEach(x=>{const p=x.waitingFor.trim();if(!p)return;const prev=peopleMap.get(p)||{name:p,count:0,oldestDays:0,due:0};prev.count++;prev.oldestDays=Math.max(prev.oldestDays,Number(x.waitingAgeDays||0));if(x.followupDue)prev.due++;peopleMap.set(p,prev)});const waitingPeople=[...peopleMap.values()].sort((a,b)=>b.due-a.due||b.oldestDays-a.oldestDays||b.count-a.count),counts=Object.fromEntries(Object.entries(groups).map(([k,v])=>[k,v.length]));model={version:VERSION,groups,counts,queue,dueFollowups,waitingPeople,now:dueFollowups[0]||groups.NOW[0]||null,at:new Date().toISOString(),sourceVersion:api?.model?.version||null};publish();return model}
function setFollowup(executionId,days=2,note=''){const n=Math.max(1,Math.min(30,Number(days)||2)),prev=followups[executionId]||{};followups[executionId]={...prev,dueAt:Date.now()+n*DAY,days:n,note:String(note||prev.note||''),setAt:prev.setAt||Date.now()};save(FOLLOW_KEY,followups);build();emit({executionId,followup:true});return true}
function clearFollowup(executionId){delete followups[executionId];save(FOLLOW_KEY,followups);build();emit({executionId,followup:false});return true}
function setWaitingFor(executionId,person,days=2){const who=String(person||'').trim();if(!who)return false;overrides[executionId]='WAITING';save(KEY,overrides);const n=Math.max(1,Math.min(30,Number(days)||2)),prev=followups[executionId]||{};followups[executionId]={...prev,waitingFor:who,lastContactAt:Date.now(),contactCount:Number(prev.contactCount||0),dueAt:Date.now()+n*DAY,days:n,setAt:prev.setAt||Date.now()};save(FOLLOW_KEY,followups);build();emit({executionId,state:'WAITING',waitingFor:who});return true}
function markContact(executionId){const prev=followups[executionId];if(!prev)return false;const n=Math.max(1,Math.min(30,Number(prev.days)||2));followups[executionId]={...prev,lastContactAt:Date.now(),contactCount:Number(prev.contactCount||0)+1,dueAt:Date.now()+n*DAY};save(FOLLOW_KEY,followups);build();emit({executionId,contact:true});return true}
function clearWaitingFor(executionId){const prev=followups[executionId];if(!prev)return false;followups[executionId]={...prev,waitingFor:''};save(FOLLOW_KEY,followups);build();emit({executionId,waitingFor:''});return true}
function setState(executionId,state){if(!STATES[state])return false;overrides[executionId]=state;save(KEY,overrides);const days=defaultDays(state),prev=followups[executionId]||{};if(days&&!followups[executionId])followups[executionId]={dueAt:Date.now()+days*DAY,days,note:'',setAt:Date.now(),lastContactAt:state==='WAITING'?Date.now():null,auto:true};if(state==='WAITING'&&prev.waitingFor&&!prev.lastContactAt)followups[executionId]={...prev,lastContactAt:Date.now(),dueAt:Date.now()+(Number(prev.days)||2)*DAY};if(!days&&state!=='IGNORE')delete followups[executionId];save(FOLLOW_KEY,followups);build();emit({executionId,state});return true}
function clearState(executionId){delete overrides[executionId];save(KEY,overrides);build();emit({executionId,state:null});return true}
function publish(){window.__KAMIL_EXECUTION_STATE364__={version:VERSION,healthy:true,model,states:STATES,refresh:build,setState,clearState,setFollowup,clearFollowup,setWaitingFor,markContact,clearWaitingFor,at:Date.now()};window.__KAMIL_FOLLOWUP365__={version:VERSION,healthy:true,due:model.dueFollowups,setFollowup,clearFollowup,refresh:build,at:Date.now()};window.__KAMIL_WAITING366__={version:VERSION,healthy:true,people:model.waitingPeople,items:model.groups.WAITING,setWaitingFor,markContact,clearWaitingFor,refresh:build,at:Date.now()}}
let timer=0,bound=false;const schedule=()=>{clearTimeout(timer);timer=setTimeout(build,70)};
export function installExecutionState364(){document.documentElement.dataset.executionState364='366';document.documentElement.dataset.waiting366='1';if(!bound){bound=true;window.addEventListener('kamil:manager341-updated',schedule);window.addEventListener('kamil:view-change',schedule);window.addEventListener('focus',schedule)}schedule();setTimeout(schedule,700);setInterval(schedule,15*60*1000)}
