const DB_NAME='kamil-os-archives',DB_VERSION=1,STORE='records';
export function readFeature(key,fallback=null){try{const raw=localStorage.getItem(key);return raw===null?fallback:JSON.parse(raw)}catch{return fallback}}
export function writeFeature(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch(error){console.warn('[featureStorage] write failed',key,error);return false}}
export function removeFeature(key){try{localStorage.removeItem(key);return true}catch{return false}}
export function appendFeature(key,row,{max=500}={}){const rows=readFeature(key,[]),next=Array.isArray(rows)?rows:[];next.push(row);writeFeature(key,next.slice(-Math.max(1,max)));return row}
export function featureStorageHealth(){let bytes=0,keys=0;try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i),v=localStorage.getItem(k)||'';bytes+=(k?.length||0)+v.length;keys++}}catch{}return{keys,approxBytes:bytes*2,approxMb:Math.round(bytes*2/1024/1024*100)/100,status:bytes*2>4_000_000?'HIGH':bytes*2>2_500_000?'WATCH':'OK'}}
function openDb(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window)){reject(new Error('INDEXEDDB_UNAVAILABLE'));return}const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('IDB_OPEN_FAILED'))})}
export async function archiveRecord(id,value,meta={}){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite'),row={id:String(id),value,meta,archivedAt:new Date().toISOString()};tx.objectStore(STORE).put(row);tx.oncomplete=()=>{db.close();resolve(row)};tx.onerror=()=>{db.close();reject(tx.error||new Error('IDB_WRITE_FAILED'))}})}
export async function readArchive(id){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(String(id));r.onsuccess=()=>{db.close();resolve(r.result||null)};r.onerror=()=>{db.close();reject(r.error||new Error('IDB_READ_FAILED'))}})}
