import {store} from './state.js';

const VERSION='1180.0.0';
const A=v=>Array.isArray(v)?v:[],N=v=>Number(v||0),U=v=>String(v||'').toUpperCase();
function bankRows(s){const rows=A(s.bankBook?.accounts||s.banks||s.accounts).map((x,i)=>{const balance=N(x.balanceCzk??x.balance??x.amount),rate=N(x.ratePct??x.interestPct??x.apy),monthly=balance*rate/100/12;return{id:String(x.id||i),name:x.name||x.bank||x.title||'Účet',balance,ratePct:rate,monthlyInterest:monthly}});return rows.sort((a,b)=>b.balance-a.balance)}
function ticketRisk(s){const rows=A(s.ticketBook?.items).filter(x=>['HOLD','LISTED','NOT_LISTED'].includes(U(x.workflow||x.market_status||'HOLD'))),capital=rows.reduce((a,x)=>a+N(x.buy_total_czk??x.buy??x.cost),0),byEvent=new Map();for(const x of rows){const k=String(x.event_name||x.name||x.title||'event'),v=N(x.buy_total_czk??x.buy??x.cost);byEvent.set(k,(byEvent.get(k)||0)+v)}const top=[...byEvent].sort((a,b)=>b[1]-a[1])[0]||null;return{capital,positions:rows.length,topEvent:top?{name:top[0],capital:top[1],sharePct:capital?top[1]/capital*100:0}:null}}
function bettingRisk(s){let ledger=s.bettingLedger||s.betBook||null;if(!ledger&&typeof localStorage!=='undefined'){try{ledger=JSON.parse(localStorage.getItem('kamil_betting_ledger_543')||'{}')}catch{ledger={}}}const bankroll=N(ledger?.bankrollCzk),open=A(ledger?.bets).filter(x=>U(x.status||'OPEN')==='OPEN'),exposure=open.reduce((a,x)=>a+N(x.stakeCzk),0);return{bankroll,exposure,exposurePct:bankroll?exposure/bankroll*100:0,open:open.length}}
function investmentRisk(s){const planned=A(s.investments||s.investmentPlan?.items||s.capitalPlan?.items),committed=planned.reduce((a,x)=>a+N(x.committedCzk??x.amountCzk??x.amount),0);return{committed,count:planned.length}}
export function financeRisk1180(s=store.get()){const banks=bankRows(s),bankTotal=banks.reduce((a,x)=>a+x.balance,0),monthlyInterest=banks.reduce((a,x)=>a+x.monthlyInterest,0),tickets=ticketRisk(s),betting=bettingRisk(s),investments=investmentRisk(s),riskCapital=tickets.capital+betting.exposure+investments.committed,denom=Math.max(1,bankTotal+riskCapital),riskPct=riskCapital/denom*100;const alerts=[];if(tickets.topEvent?.sharePct>=30)alerts.push(`Ticket koncentrace ${tickets.topEvent.name} ${tickets.topEvent.sharePct.toFixed(1)} %`);if(betting.exposurePct>=8)alerts.push(`Betting expozice ${betting.exposurePct.toFixed(1)} % bankrollu`);if(riskPct>=40)alerts.push(`Celkový známý rizikový kapitál ${riskPct.toFixed(1)} %`);return{version:VERSION,banks:{rows:banks,total:bankTotal,monthlyInterest,annualInterest:monthlyInterest*12},tickets,betting,investments,riskCapital,riskPct,alerts,tone:alerts.length?'warn':'good',generatedAt:new Date().toISOString()}}
export function installFinanceRisk1180(){globalThis.__KAMIL_FINANCE_RISK1180_API__={snapshot:financeRisk1180};globalThis.__KAMIL_FINANCE_RISK1180__=financeRisk1180();return globalThis.__KAMIL_FINANCE_RISK1180__}
