import {store} from './state.js';
import {h,qs} from './utils.js';
import {todayBrain34} from './todayBrain34.js';

const id='focusAction35Host';let queued=false;
function openTarget(t){if(t==='waiting'){window.dispatchEvent(new CustomEvent('kamil:waiting-open'));return}if(t==='director'){window.dispatchEvent(new CustomEvent('kamil:director-open'));return}window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:t||'today'}))}
const buttonLabel=t=>t==='waiting'?'Vyřešit čekání':t==='director'?'Otevřít Director Mode':t==='tickets'?'Otevřít vstupenky':t==='money'?'Otevřít peníze':t==='home'?'Otevřít domov':'Otevřít';
function render(){const view=qs('#todayView');if(!view?.querySelector('.view-head'))return;qs(`#${id}`,view)?.remove();const b=todayBrain34(store.get()),x=b.top,host=document.createElement('div');host.id=id;host.className=`card focus35-card ${x?.tone||'good'}`;host.innerHTML=x?`<div class="focus35-grid"><div><div class="eyebrow">TEĎ UDĚLEJ TOTO / 35.1</div><div class="focus35-title">${h(x.title)}</div><p>${h(x.reason)}</p><div class="focus35-meta"><span class="status ${h(x.tone)}">priorita ${x.priority}</span><span class="status">${h(x.kind)}</span></div></div><div class="focus35-cta"><button class="btn primary" data-focus35-open>${h(buttonLabel(x.target))} →</button><small>Jedna věc. Pak se žebříček přepočítá.</small></div></div>`:`<div class="focus35-grid"><div><div class="eyebrow">TEĎ UDĚLEJ TOTO / 35.1</div><div class="focus35-title">Nic kritického.</div><p>OS z uložených dat nevidí žádný krok, který by teď měl přednost.</p></div><div class="focus35-cta"><span class="status good">KLID</span></div></div>`;view.querySelector('.view-head')?.insertAdjacentElement('afterend',host);qs('[data-focus35-open]',host)?.addEventListener('click',()=>openTarget(x.target))}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;render()})}
function start(){const view=qs('#todayView');if(view)new MutationObserver(()=>{if(!qs(`#${id}`,view))schedule()}).observe(view,{childList:true,subtree:false});store.subscribe(()=>{if(qs('#view-today')?.classList.contains('on'))schedule()});window.addEventListener('kamil:navigate',schedule);setTimeout(render,480)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
