const VERSION=470;
const N=v=>Number.isFinite(Number(v))?Number(v):0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`;
const HORIZONS=[7,14,30,60,90];
const isTodayEvent=e=>{const d=e?.detail;return !d||d==='today'||d?.view==='today'};

function ensureCss(){if(document.querySelector('link[data-free-cash-470-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./freeCashForecast470.css';l.dataset.freeCash470Css='1';document.head.appendChild(l)}
function liveCashflow(){return window.__KAMIL_CASHFLOW468__?.model||null}
function cashflowSafe(c){return!!c&&c.version===468&&c.healthy===true&&N(c.finance?.cash)>0&&c.guardrails?.forecastMustStayAboveReserve!==false}
function horizon(c,days){const cash=N(c.finance?.cash),monthlyOut=Math.max(0,N(c.finance?.monthlyOut)),reserve=Math.max(0,N(c.reserve)),inside=(c.flows||[]).filter(x=>N(x?.days)>=0&&N(x?.days)<=days),knownIn=inside.filter(x=>N(x?.amount)>0).reduce((a,x)=>a+N(x.amount),0),knownOut=inside.filter(x=>N(x?.amount)<0).reduce((a,x)=>a+Math.abs(N(x.amount)),0),recurringOut=monthlyOut*(days/30),expectedOut=Math.max(recurringOut,knownOut),forecast=cash+knownIn-expectedOut,freeCash=Math.max(0,forecast-reserve);return{days,forecast,freeCash,knownIn,expectedOut,reserve,explicitCount:inside.length}}
export function buildFreeCashForecast470(cashflow=liveCashflow()){
 const sourceHealthy=cashflowSafe(cashflow),reserve=Math.max(0,N(cashflow?.reserve));
 const rows=sourceHealthy?HORIZONS.map(days=>horizon(cashflow,days)):HORIZONS.map(days=>({days,forecast:0,freeCash:0,knownIn:0,expectedOut:0,reserve,explicitCount:0}));
 const lowest=rows.reduce((a,x)=>!a||x.forecast<a.forecast?x:a,null),nextDeployable=rows.find(x=>x.freeCash>0)||null,minFreeCash=rows.reduce((a,x)=>Math.min(a,x.freeCash),Infinity);
 const safeNow=sourceHealthy?Math.max(0,N(cashflow.deployable)):0,conservativeCap=sourceHealthy?Math.max(0,Math.min(safeNow,...rows.map(x=>x.freeCash))):0;
 const reason=!cashflow?'OS468 cash-flow model není dostupný.':!sourceHealthy?'OS468 nemá zdravý stav hotovosti; forecast je zablokovaný.':conservativeCap>0?`Ve všech pěti horizontech zůstává nejméně ${money(conservativeCap)} nad rezervou.`:nextDeployable?`Volný kapitál se objevuje nejdřív v horizontu ${nextDeployable.days} dní, ale dřívější období ještě není bezpečné.`:'V žádném sledovaném horizontu nezůstává bezpečně volná hotovost nad rezervou.';
 return{version:VERSION,healthy:true,sourceVersion:cashflow?.version||null,sourceHealthy,reserve,safeNow,rows,lowest,nextDeployable,conservativeCap,minFreeCash:Number.isFinite(minFreeCash)?minFreeCash:0,recommendation:{code:conservativeCap>0?'SAFE_CAPITAL':'HOLD',action:conservativeCap>0?'KAPITÁL JE VOLNÝ':'DRŽET HOTOVOST',amount:conservativeCap,reason},generatedAt:new Date().toISOString(),guardrails:{reserveProtected:true,unknownInflowsAssumedZero:true,explicitInflowsOnly:true,allHorizonsMustStayAboveReserve:true,autoExecute:false}}
}
function card(m){const rows=m.rows.map(x=>`<div class="os470-horizon"><small>${x.days} DNÍ</small><b>${money(x.freeCash)}</b><span>forecast ${money(x.forecast)} · rezerva ${money(x.reserve)}</span></div>`).join('');return `<article class="os467-card os470" data-free-cash470-root><header><div><small>OS470 · FREE CASH FORECAST</small><h3>Kolik bude bezpečně volné?</h3></div></header><div class="os470-horizons">${rows}</div><div class="os470-verdict ${m.conservativeCap>0?'safe':'hold'}"><div><small>KONZERVATIVNÍ LIMIT</small><h4>${esc(m.recommendation.action)}</h4><p>${esc(m.recommendation.reason)}</p></div><b>${money(m.conservativeCap)}</b></div><footer>7 / 14 / 30 / 60 / 90 dní · neznámé příjmy se nepočítají · žádná automatická akce</footer></article>`}
function mount(){const grid=document.querySelector('[data-command-center467-root] .os467-grid');if(!grid)return false;const m=buildFreeCashForecast470(),first=!window.__KAMIL_FREE_CASH470__;let host=grid.querySelector('[data-free-cash470-root]');const box=document.createElement('div');box.innerHTML=card(m);const next=box.firstElementChild;let changed=false;if(host){if(host.innerHTML!==next.innerHTML||host.className!==next.className){host.replaceWith(next);host=next;changed=true}}else{const anchor=grid.querySelector('[data-capital-plan469-root]')||grid.querySelector('[data-cashflow468-root]');anchor?anchor.after(next):grid.appendChild(next);host=next;changed=true}window.__KAMIL_FREE_CASH470__={version:VERSION,healthy:true,mounted:!!host,model:m,refresh:renderSafe,at:Date.now()};document.documentElement.dataset.freeCash470='1';if(first||changed)window.dispatchEvent(new CustomEvent('kamil:free-cash470-updated',{detail:{conservativeCap:m.conservativeCap,changed}}));return true}
function renderSafe(){try{return mount()}catch(error){console.error('[freeCashForecast470]',error);window.__KAMIL_FREE_CASH470__={version:VERSION,healthy:false,error:String(error?.message||error),refresh:renderSafe,at:Date.now()};return false}}
let timer=0,bound=false;const schedule=(delay=50)=>{clearTimeout(timer);timer=setTimeout(renderSafe,delay)};
export function installFreeCashForecast470(){ensureCss();document.documentElement.dataset.freeCash470='1';if(!bound){bound=true;for(const event of ['kamil:cashflow468-updated','kamil:capital-plan469-updated'])window.addEventListener(event,()=>schedule(25));window.addEventListener('kamil:view-change',e=>{if(isTodayEvent(e))schedule(35)});window.addEventListener('focus',()=>schedule(25))}renderSafe()}
