import {store} from './state.js';
const MAX_ERRORS=40;
function stateHealth(){const s=store.get?.()||{};const checks={tasks:Array.isArray(s.tasks),delegations:Array.isArray(s.delegations),inbox:Array.isArray(s.inbox),personalInbox:Array.isArray(s.personalInbox?.items),personalAdmin:Array.isArray(s.personalAdmin?.items)};return{ok:Object.values(checks).every(Boolean),checks}}
function moduleHealth(){return{core:!!window.__KAMIL_CORE312__,actions:!!window.__KAMIL_ACTION_MODEL312__,intelligence:!!window.__KAMIL_INTELLIGENCE318__,domain:!!window.__KAMIL_DOMAIN328__,finance:!!window.__KAMIL_FINANCE_COMMAND258__,tickets:!!window.__KAMIL_TICKET_COMMAND268__}}
function snapshot(){const errors=(window.__KAMIL_BOOT_ERRORS__||[]).slice(-MAX_ERRORS),state=stateHealth(),modules=moduleHealth(),missing=Object.entries(modules).filter(([,v])=>!v).map(([k])=>k);return{version:340,ok:state.ok&&missing.length===0&&errors.length===0,state,modules,missing,errors,at:new Date().toISOString()}}
function expose(){window.__KAMIL_HEALTH329__=snapshot();return window.__KAMIL_HEALTH329__}
function recover(){const h=snapshot();if(!h.modules.core)window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'today'}));if(!h.modules.finance)import('./financeCommand258.js').then(m=>m.installFinanceCommand258?.()).catch(()=>{});if(!h.modules.tickets)import('./ticketCommand268.js').then(m=>m.installTicketCommand268?.()).catch(()=>{});if(!h.modules.domain)import('./domainOS328.js').then(m=>m.installDomainOS328?.()).catch(()=>{});setTimeout(expose,500);return h}
function installErrorCapture(){if(window.__KAMIL_ERROR_CAPTURE329__)return;window.__KAMIL_ERROR_CAPTURE329__=true;const push=(scope,message)=>{window.__KAMIL_BOOT_ERRORS__=window.__KAMIL_BOOT_ERRORS__||[];window.__KAMIL_BOOT_ERRORS__.push({scope,message:String(message||'Unknown error'),at:Date.now()});window.__KAMIL_BOOT_ERRORS__=window.__KAMIL_BOOT_ERRORS__.slice(-MAX_ERRORS);expose()};window.addEventListener('error',e=>push('runtime',e.error?.message||e.message));window.addEventListener('unhandledrejection',e=>push('promise',e.reason?.message||e.reason))}
export function installHardening329(){installErrorCapture();let timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(expose,180)};store.subscribe?.(schedule);window.addEventListener('kamil:view-change',schedule);window.__KAMIL_RECOVER329__=recover;expose();setTimeout(expose,900);setTimeout(()=>{const h=snapshot();if(!h.ok&&h.errors.length===0)recover()},1500)}
