import {store} from './state.js';
import {householdBills,nextBillDue} from './householdBills25.js';
import {h,date,qs,qsa,toast} from './utils.js';

const tileId='householdBills25Tile';
const tone=s=>s==='URGENT'?'bad':s==='SOON'||s==='REVIEW'?'warn':'good';
const label=s=>({URGENT:'ŘEŠIT',SOON:'BRZY',REVIEW:'DOPLNIT',OK:'OK'}[s]||s);
const fmt=(v,c)=>v===null||v===undefined?'—':`${Number(v).toLocaleString('cs-CZ',{maximumFractionDigits:2})} ${h(c||'CZK')}`;

function ensureTile(){const view=qs('#moreView'),grid=view?.querySelector('.more24-grid');if(!grid||qs(`#${tileId}`,view))return;const a=householdBills(store.get());const b=document.createElement('button');b.id=tileId;b.className='hub-tile';b.innerHTML=`<span class="hub-icon ${a.overdue?'bad':a.due7?'warn':'good'}">Kč</span><span class="hub-copy"><b>Platby domácnosti</b><small>${a.total?`${a.total} závazků · ${a.due7} do 7 dní`:'Energie, hypotéka, služby a předplatná'}</small></span><span class="hub-arrow">→</span>`;b.onclick=renderBills;grid.prepend(b)}
function costsHtml(costs){const rows=Object.entries(costs);return rows.length?rows.map(([c,v])=>`<span class="status">${h(c)} ${Number(v.monthly).toLocaleString('cs-CZ',{maximumFractionDigits:2})}/měs · ${Number(v.annual).toLocaleString('cs-CZ',{maximumFractionDigits:2})}/rok</span>`).join(' '):'<span class="status">Náklady nejsou zadané</span>'}
function confirmPaid(id){const s=store.get(),x=s.personalAdmin?.items?.find(y=>y.id===id);if(!x)return;const next=nextBillDue(x.nextDue,x.cadence||'ONCE');store.mutate(`Potvrzena platba: ${x.title||'závazek'}`,z=>{const q=z.personalAdmin?.items?.find(y=>y.id===id);if(!q)return;q.lastPaidAt=new Date().toISOString();if(next)q.nextDue=next;else if((q.cadence||'ONCE')==='ONCE')q.status='ARCHIVED';q.updatedAt=new Date().toISOString()});toast(next?`Platba potvrzena · další termín ${date(next)}`:'Platba potvrzena');renderBills()}
function renderBills(){const view=qs('#moreView'),a=householdBills(store.get());if(!view)return;view.innerHTML=`<div class="subview-bar"><button class="btn" id="billsBack25">← Zpět</button><div><span>VÍCE</span><b>Platby domácnosti</b></div></div><div class="view-head compact"><div><div class="eyebrow">HOUSEHOLD BILLS / 25.15</div><h1>Všechny pravidelné platby pod kontrolou</h1><p>Hypotéka, energie, služby, poplatky, předplatná a další domácí závazky.</p></div><div class="view-head-stat"><b class="${a.overdue?'bad':a.due7?'warn':'good'}">${a.overdue}</b><span>po termínu</span></div></div><div class="metric-strip"><div class="metric"><span>Do 7 dní</span><b class="${a.due7?'warn':'good'}">${a.due7}</b></div><div class="metric"><span>Ručně do 7 dní</span><b class="${a.manualDue7?'warn':'good'}">${a.manualDue7}</b></div><div class="metric"><span>Autopay</span><b>${a.autopay}</b></div><div class="metric"><span>Předplatná</span><b>${a.subscriptions}</b></div></div><div class="card"><div class="card-head"><div><div class="eyebrow">NÁKLADY PO MĚNÁCH</div><h2>Kolik domácnost stojí</h2></div><div>${costsHtml(a.costs)}</div></div></div><div class="card"><div class="card-head"><div><div class="eyebrow">PLATEBNÍ RADAR</div><h2>Co zaplatit nebo zkontrolovat</h2></div><button class="btn" id="billsOpenAdmin25">Spravovat závazky</button></div><div class="intel-list">${a.items.map(x=>`<div class="intel-row"><div class="intel-main"><div><span class="status ${tone(x.status)}">${label(x.status)} · ${h(x.categoryLabel)}</span>${x.autoPay?' <span class="status good">AUTOPAY</span>':' <span class="status warn">RUČNĚ</span>'}</div><b>${h(x.title)}</b><span>${h(x.issues[0]||x.provider||'Bez aktuálního upozornění')}</span><small>${fmt(x.amount,x.currency)} · ${h(x.cadence||'ONCE')} · další termín ${x.nextDue?date(x.nextDue):'—'}${x.lastPaidAt?` · poslední potvrzení ${date(x.lastPaidAt)}`:''}</small></div><div class="row-actions">${x.nextDue?`<button class="btn primary" data-bill-paid="${h(x.id)}">Zaplaceno</button>`:''}</div></div>`).join('')||'<div class="empty">Žádné aktivní domácí platby. Přidej je v Osobní administraci.</div>'}</div><div class="decision-note">${h(a.note)} Náklady se nikdy nesčítají mezi různými měnami.</div></div>`;qs('#billsBack25').onclick=()=>window.dispatchEvent(new CustomEvent('kamil:more',{detail:'menu'}));qs('#billsOpenAdmin25').onclick=()=>window.dispatchEvent(new CustomEvent('kamil:personal-admin-open'));qsa('[data-bill-paid]',view).forEach(b=>b.onclick=()=>confirmPaid(b.dataset.billPaid))}
const start=()=>{const view=qs('#moreView');if(!view)return;window.addEventListener('kamil:household-bills-open',renderBills);new MutationObserver(()=>queueMicrotask(ensureTile)).observe(view,{childList:true,subtree:true});ensureTile()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
