import {APP_VERSION} from './releaseMeta.js';

const SNAPSHOT_KEY='kamil-os-fast-snapshot-66-0';
const root=document.documentElement;
const WORK_RE=/zak[aá]zk|faktur|dodavat|pks|cpi|zbrojov|pracovn|xtb|ticket|vstupenk/i;
const parse=(raw,fallback=null)=>{try{return JSON.parse(raw)}catch{return fallback}};
const personal=x=>!WORK_RE.test(`${x?.title||''} ${x?.name||''} ${x?.category||''}`);
function ensureOS111(){if(document.querySelector('link[data-os111]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./os111.css';l.dataset.os111='1';document.head.appendChild(l)}
function applyTheme(){ensureOS111();try{root.classList.remove('theme-light');root.classList.add('theme-dark');root.dataset.theme='dark';root.style.colorScheme='dark'}catch{}document.title='Kamil OS';document.querySelectorAll('.version').forEach(x=>x.classList.add('hidden'))}
function fallbackHtml(){const s=parse(localStorage.getItem('kamil-os-state')||'null',{})||{},tasks=(s.tasks||[]).filter(personal).filter(x=>!['DONE','CLOSED','ARCHIVED'].includes(String(x.status||'').toUpperCase())).length,admin=(s.personalAdmin?.items||[]).filter(x=>!['DONE','CLOSED','ARCHIVED'].includes(String(x.status||'').toUpperCase())).length;return `<div class="ux64-page ux65-today"><section class="ux64-hero ux65-hero"><div class="eyebrow">DNES</div><h1>Načítám osobní přehled…</h1><p>Nejdřív ukážu jen to, co má smysl řešit.</p></section><div class="metric-strip"><div class="metric"><span>Osobní úkoly</span><b>${tasks}</b></div><div class="metric"><span>Administrativa</span><b>${admin}</b></div></div></div>`}
function paintInstant(){const host=document.querySelector('#todayView');if(!host)return;let html='';try{const snap=parse(localStorage.getItem(SNAPSHOT_KEY)||'null');if(snap?.version===APP_VERSION&&snap?.html&&Date.now()-Number(snap.at||0)<2*86400000)html=snap.html}catch{}host.innerHTML=html||fallbackHtml();window.__KAMIL_SNAPSHOT_HIT__=!!html}
function saveSnapshot(){const host=document.querySelector('#todayView');if(!host)return;const html=[...host.children].slice(0,5).map(x=>x.outerHTML).join('');if(html.length>300&&html.length<160000)try{localStorage.setItem(SNAPSHOT_KEY,JSON.stringify({version:APP_VERSION,html,at:Date.now()}))}catch{}}
function registerSw(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
function noteBootError(scope,error){console.error(`[instantShell66:${scope}]`,error);window.__KAMIL_BOOT_ERRORS__=window.__KAMIL_BOOT_ERRORS__||[];window.__KAMIL_BOOT_ERRORS__.push({scope,message:String(error?.message||error),at:Date.now()})}
async function optionalImport(path,fn){try{const m=await import(path);if(typeof m?.[fn]==='function')m[fn]();return true}catch(error){noteBootError(path,error);return false}}
async function load(){let appOk=false;try{await import('./app.js');appOk=true}catch(error){noteBootError('app',error);const host=document.querySelector('#todayView');if(host&&!host.querySelector('[data-core-boot-failed]'))host.insertAdjacentHTML('beforeend','<div class="decision-note bad" data-core-boot-failed>Kamil OS se nepodařilo načíst. Lokální data zůstala beze změn. Zkus obnovit stránku.</div>');setTimeout(registerSw,300);return}await optionalImport('./personalShell640.js','bindPersonalShell640');await optionalImport('./personalHardening650.js','bindPersonalHardening650');await optionalImport('./appWorkspace211.js','installAppWorkspaces211');await optionalImport('./compactNavigation212.js','installCompactNavigation212');await optionalImport('./productionChrome228.js','installProductionChrome228');await optionalImport('./todayDashboard213.js','installTodayDashboard213');await optionalImport('./todayWake226.js','installTodayWake226');await optionalImport('./uxFoundation238.js','installUxFoundation238');await optionalImport('./dailyCommander248.js','installDailyCommander248');await optionalImport('./financeCommand258.js','installFinanceCommand258');await optionalImport('./ticketCommand268.js','installTicketCommand268');await optionalImport('./managerAutopilot278.js','installManagerAutopilot278');await optionalImport('./lifeOperator298.js','installLifeOperator298');await optionalImport('./operatorHome299.js','installOperatorHome299');await optionalImport('./kamilBrain300.js','installKamilBrain300');if(appOk){document.querySelector('[data-core-boot-failed]')?.remove();setTimeout(saveSnapshot,1100);setTimeout(registerSw,1200)}}
applyTheme();paintInstant();document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveSnapshot()});window.addEventListener('beforeunload',saveSnapshot);requestAnimationFrame(()=>requestAnimationFrame(load));