(function(){
  const VERSION='43.1.0';
  const SNAPSHOT_KEY='kamil-os-fast-snapshot-43-1';
  const BOOT_KEY='kamil-os-41-boot-summary';
  const THEME_KEY='kamil-os-theme33';
  const PARTITION_LAYOUT=3;
  const root=document.documentElement;
  const now=Date.now();
  const coreStyles=['./styles.css','./theme33.css'];
  const detailStyles=['./today25.css','./personal29.css'];
  const pageTitles={today:'DNES',money:'PENÍZE',tickets:'VSTUPENKY',home:'DOMOV',more:'VÍCE'};
  let lazyFeaturesStarted=false,leanAutopilotStarted=false,earlyView='today';
  function parse(raw,fallback=null){try{return JSON.parse(raw)}catch{return fallback}}
  function bootInfo(){try{return parse(localStorage.getItem(BOOT_KEY)||'null',{})||{}}catch{return{}}}
  function partitionReady(){const s=bootInfo().storage||{};return s.partitioned===true&&Number(s.layoutVersion||0)===PARTITION_LAYOUT}
  function applyTheme(){try{const theme=localStorage.getItem(THEME_KEY)||'light',light=theme!=='dark';root.classList.toggle('theme-light',light);root.classList.toggle('theme-dark',!light);root.dataset.theme=light?'light':'dark';root.style.colorScheme=light?'light':'dark'}catch{}document.querySelectorAll('.version').forEach(x=>x.textContent=VERSION)}
  function fallbackHtml(){const b=bootInfo(),tasks=Number(b.tasks||0),waiting=Number(b.waiting||0),tickets=Number(b.tickets||0),inbox=Number(b.inbox||0);return `<div class="view-head"><div><div class="eyebrow">KAMIL OS ${VERSION} / SAFE INSTANT START</div><h1>Kamil OS je připravený.</h1><p>Lokální přehled má přednost. Těžké analýzy čekají, dokud je aplikace opravdu interaktivní.</p></div></div><div class="metric-strip"><div class="metric"><span>Otevřené úkoly</span><b>${tasks}</b></div><div class="metric"><span>Waiting For</span><b>${waiting}</b></div><div class="metric"><span>Inbox</span><b>${inbox}</b></div><div class="metric"><span>Aktivní vstupenky</span><b>${tickets}</b></div></div><div class="decision-note">43.1 Lean Autopilot drží 60-feature detail zavřený, dokud ho opravdu neotevřeš.</div>`}
  function paintInstant(){const host=document.querySelector('#todayView');if(!host)return;let html='';try{const snap=parse(localStorage.getItem(SNAPSHOT_KEY)||'null');if(snap?.html&&typeof snap.html==='string'&&snap.html.length<120000&&now-Number(snap.at||0)<2*86400000)html=snap.html}catch{}host.innerHTML=html||fallbackHtml();host.dataset.instantShell='1';host.dataset.fastShell='1';window.__KAMIL_SNAPSHOT_HIT__=!!html;window.__KAMIL_PARTITION_READY_AT_BOOT__=partitionReady();window.__KAMIL_INSTANT_SHELL_AT__=performance.now();try{performance.mark('kamil-instant-shell')}catch{}}
  function placeholder(view){const host=document.querySelector(`#${view}View`);if(!host||host.innerHTML.trim())return;host.innerHTML=`<div class="view-head"><div><div class="eyebrow">${pageTitles[view]||'KAMIL OS'} / RYCHLÝ START</div><h1>Sekce je otevřená.</h1><p>Plný modul se právě připojuje. Ostatní části Kamil OS tím neblokují první obrazovku.</p></div></div><div class="decision-note">Nic se nemaže ani nevypíná; jde jen o progresivní načtení.</div>`}
  function earlyNavigate(view){if(!pageTitles[view])return;earlyView=view;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('on',x.id===`view-${view}`));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('on',x.dataset.view===view));const p=document.querySelector('#pageTitle');if(p)p.textContent=pageTitles[view];if(view!=='today')placeholder(view);window.__KAMIL_EARLY_VIEW__=view}
  function bindEarlyNavigation(){document.querySelectorAll('[data-view]').forEach(button=>{button.onclick=()=>earlyNavigate(button.dataset.view)})}
  function loadStyleList(list){for(const href of list){if(document.querySelector(`link[data-kamil-full-style="${href}"]`))continue;const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset.kamilFullStyle=href;document.head.appendChild(l)}}
  function compactSnapshot(host){const nodes=[...host.children].slice(0,4),html=nodes.map(x=>x.outerHTML).join('');return html.length>=200&&html.length<120000?html:''}
  function saveSnapshot(){const host=document.querySelector('#todayView');if(!host||host.dataset.instantShell==='1')return;const html=compactSnapshot(host);if(!html)return;try{localStorage.setItem(SNAPSHOT_KEY,JSON.stringify({version:VERSION,html,at:Date.now()}))}catch{}}
  function idle(fn,timeout=1800){if('requestIdleCallback'in window)return requestIdleCallback(fn,{timeout});return setTimeout(fn,450)}
  function registerSw(){if(!('serviceWorker'in navigator))return Promise.resolve(null);if(!window.__KAMIL_SW_PROMISE__)window.__KAMIL_SW_PROMISE__=navigator.serviceWorker.register('./sw.js').catch(error=>{console.warn('[instantShell431] service worker',error);return null});return window.__KAMIL_SW_PROMISE__}
  function startLazyFeatures(){if(lazyFeaturesStarted)return;lazyFeaturesStarted=true;import('./lazyBoot41.js').catch(()=>{})}
  function startLeanAutopilot(){if(leanAutopilotStarted)return;leanAutopilotStarted=true;loadStyleList(['./platform43.css']);Promise.allSettled([import('./platform431Stability.js'),import('./platform431LeanUi.js')]).catch(()=>{})}
  function waitForAppInteractive(appPromise){return new Promise((resolve,reject)=>{let done=false;const timeout=setTimeout(()=>finish('safe-timeout'),6000);const finish=v=>{if(done)return;done=true;clearTimeout(timeout);resolve(v)};appPromise.then(()=>finish('module'),error=>{if(done)console.warn('[instantShell431] background completion',error);else{done=true;clearTimeout(timeout);reject(error)}});const tick=()=>{if(done)return;const host=document.querySelector('#todayView');if(host?.dataset.todayLite43||host?.querySelector?.('[data-today43-full]')){finish('local-ui');return}requestAnimationFrame(tick)};requestAnimationFrame(tick)})}
  async function loadFullApp(){try{let partition=null,appPromise=null;if(partitionReady()){window.__KAMIL_PREBOOT_COMPACT__={ok:true,skipped:true,reason:'ALREADY_PARTITIONED'};window.__KAMIL_PREBOOT_COMPACT_AT__=performance.now();appPromise=import('./app.js')}else{partition=await import('./coldPartition42.js');try{const r=partition.compactLocalState42({force:true});window.__KAMIL_PREBOOT_COMPACT__=r;window.__KAMIL_PREBOOT_COMPACT_AT__=performance.now()}catch{}appPromise=import('./app.js')}window.__KAMIL_APP_IMPORT_PROMISE__=appPromise;window.__KAMIL_APP_READY_MODE__=await waitForAppInteractive(appPromise);window.__KAMIL_APP_READY_AT__=performance.now();try{performance.mark('kamil-app-ready')}catch{}document.querySelector('#todayView')?.removeAttribute('data-instant-shell');if(earlyView!=='today')window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:earlyView}));loadStyleList(detailStyles);import('./state.js').then(({store})=>{const b=document.querySelector('#undoBtn');if(b)b.disabled=!store.undoCount()}).catch(()=>{});setTimeout(()=>idle(async()=>{try{partition=partition||await import('./coldPartition42.js');await partition.startColdPartition42()}catch{}},1500),3000);setTimeout(()=>idle(()=>registerSw(),3000),6000);setTimeout(saveSnapshot,4500);setTimeout(()=>idle(()=>Promise.allSettled([import('./theme33.js'),import('./releaseStamp.js')]),2500),5000);setTimeout(startLeanAutopilot,9000);setTimeout(startLazyFeatures,15000)}catch(error){console.error('[instantShell431]',error);const host=document.querySelector('#todayView');if(host)host.insertAdjacentHTML('beforeend','<div class="decision-note bad">Detail aplikace se nepodařilo načíst. Lokální data zůstala beze změn.</div>')}}
  applyTheme();paintInstant();bindEarlyNavigation();setTimeout(()=>loadStyleList(coreStyles),120);window.addEventListener('kamil:today-full-ready',()=>{setTimeout(saveSnapshot,120);setTimeout(startLeanAutopilot,3500);setTimeout(startLazyFeatures,5000)},{once:true});window.addEventListener('kamil:view-change',e=>{if(e.detail==='today'){setTimeout(saveSnapshot,1200);setTimeout(startLeanAutopilot,1500)}else startLazyFeatures()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveSnapshot()});window.addEventListener('beforeunload',saveSnapshot);requestAnimationFrame(()=>requestAnimationFrame(loadFullApp));
})();
