import {APP_VERSION} from './releaseMeta.js';
import {runtimePhase,runtimePriorities} from './runtimeManifest.js';

const SNAPSHOT_KEY='kamil-os-fast-snapshot-66-0',root=document.documentElement,WORK_RE=/zak[aá]zk|faktur|dodavat|pks|cpi|zbrojov|pracovn|xtb|ticket|vstupenk/i;
const BOOT343={version:343,mode:'manifest',startedAt:performance.now(),modules:[],failures:[],complete:false,totalMs:0,slowest:[],healthy:true,at:Date.now()};
const DEFER345={version:345,mode:'manifest',started:false,complete:false,modules:[],failures:[],healthy:true,at:Date.now()};
window.__KAMIL_BOOT_BUDGET343__=BOOT343;window.__KAMIL_DEFERRED345__=DEFER345;
const parse=(raw,fallback=null)=>{try{return JSON.parse(raw)}catch{return fallback}},personal=x=>!WORK_RE.test(`${x?.title||''} ${x?.name||''} ${x?.category||''}`);

function ensureOS111(){if(document.querySelector('link[data-os111]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./os111.css';l.dataset.os111='1';document.head.appendChild(l)}
function applyTheme(){ensureOS111();try{root.classList.remove('theme-light');root.classList.add('theme-dark');root.dataset.theme='dark';root.style.colorScheme='dark'}catch{}document.title='Kamil OS';document.querySelectorAll('.version').forEach(x=>x.classList.add('hidden'))}
function fallbackHtml(){const s=parse(localStorage.getItem('kamil-os-state')||'null',{})||{},tasks=(s.tasks||[]).filter(personal).filter(x=>!['DONE','CLOSED','ARCHIVED'].includes(String(x.status||'').toUpperCase())).length,admin=(s.personalAdmin?.items||[]).filter(x=>!['DONE','CLOSED','ARCHIVED'].includes(String(x.status||'').toUpperCase())).length;return `<div class="ux64-page ux65-today"><section class="ux64-hero ux65-hero"><div class="eyebrow">DNES</div><h1>Načítám osobní přehled…</h1><p>Nejdřív ukážu jen to, co má smysl řešit.</p></section><div class="metric-strip"><div class="metric"><span>Osobní úkoly</span><b>${tasks}</b></div><div class="metric"><span>Administrativa</span><b>${admin}</b></div></div></div>`}
function paintInstant(){const host=document.querySelector('#todayView');if(!host)return;let html='';try{const snap=parse(localStorage.getItem(SNAPSHOT_KEY)||'null');if(snap?.version===APP_VERSION&&snap?.html&&Date.now()-Number(snap.at||0)<2*86400000)html=snap.html}catch{}host.innerHTML=html||fallbackHtml();window.__KAMIL_SNAPSHOT_HIT__=!!html}
function saveSnapshot(){const host=document.querySelector('#todayView');if(!host)return;const html=[...host.children].slice(0,5).map(x=>x.outerHTML).join('');if(html.length>300&&html.length<160000)try{localStorage.setItem(SNAPSHOT_KEY,JSON.stringify({version:APP_VERSION,html,at:Date.now()}))}catch{}}
function registerSw(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
function publishBoot(){BOOT343.totalMs=Math.round(performance.now()-BOOT343.startedAt);BOOT343.slowest=[...BOOT343.modules].sort((a,b)=>b.ms-a.ms).slice(0,8);BOOT343.healthy=BOOT343.failures.length===0;BOOT343.at=Date.now()}
function publishDeferred(){DEFER345.healthy=DEFER345.failures.length===0;DEFER345.at=Date.now()}
function reportError(target,entry,error){const row={scope:entry?.id||entry?.path||'runtime',message:String(error?.message||error)};target.failures.push(row);window.__KAMIL_BOOT_ERRORS__=window.__KAMIL_BOOT_ERRORS__||[];window.__KAMIL_BOOT_ERRORS__.push({...row,at:Date.now()});console.warn(`[runtime:${row.scope}]`,error);target===BOOT343?publishBoot():publishDeferred()}
async function installEntry(entry,target){const start=performance.now();let ok=false;try{const m=await import(entry.path);if(typeof m?.[entry.fn]!=='function')throw new Error(`Chybí ${entry.fn}`);await m[entry.fn]();ok=true;return true}catch(error){reportError(target,entry,error);return false}finally{target.modules.push({id:entry.id,path:entry.path,fn:entry.fn,phase:entry.phase,ms:Math.max(0,Math.round((performance.now()-start)*10)/10),ok});target===BOOT343?publishBoot():publishDeferred()}}
async function runPhase(phase,target){const rows=runtimePhase(phase);for(const p of runtimePriorities(phase)){const batch=rows.filter(x=>x.priority===p);await Promise.allSettled(batch.map(x=>installEntry(x,target)));await new Promise(resolve=>requestAnimationFrame(()=>resolve()))}}
function idle(fn,timeout=1600){if('requestIdleCallback'in window)requestIdleCallback(fn,{timeout});else setTimeout(fn,600)}
function scheduleBackground(){if(DEFER345.started)return;DEFER345.started=true;publishDeferred();idle(async()=>{await runPhase('deferred',DEFER345);idle(async()=>{await runPhase('idle',DEFER345);DEFER345.complete=true;publishDeferred();window.dispatchEvent(new CustomEvent('kamil:deferred345-complete',{detail:{healthy:DEFER345.healthy,modules:DEFER345.modules.length}}))},2400)},1200)}

async function load(){
 const appStart=performance.now();try{await import('./app.js');BOOT343.modules.push({id:'app',path:'./app.js',fn:'module',phase:'critical',ms:Math.round((performance.now()-appStart)*10)/10,ok:true})}catch(error){reportError(BOOT343,{id:'app',path:'./app.js'},error);const host=document.querySelector('#todayView');host?.insertAdjacentHTML('beforeend','<div class="decision-note bad" data-core-boot-failed>Kamil OS se nepodařilo načíst. Lokální data zůstala beze změny. Obnov stránku nebo otevři diagnostiku.</div>');BOOT343.complete=true;publishBoot();registerSw();return}
 await runPhase('critical',BOOT343);BOOT343.complete=true;publishBoot();window.dispatchEvent(new CustomEvent('kamil:boot-budget343',{detail:{totalMs:BOOT343.totalMs,healthy:BOOT343.healthy,criticalModules:BOOT343.modules.length}}));scheduleBackground();document.querySelector('[data-core-boot-failed]')?.remove();idle(saveSnapshot,1000);idle(registerSw,1200)
}

applyTheme();paintInstant();document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveSnapshot()});window.addEventListener('beforeunload',saveSnapshot);requestAnimationFrame(()=>requestAnimationFrame(load));
