import {store} from './state.js';
import {buildUniversalInbox302} from './universalInbox302.js';
import {buildFollowUpEngine303} from './followUpEngine303.js';
import {buildActivityFeed303} from './activityFeed303.js';
import {buildLifeTimeline303} from './lifeTimeline303.js';
import {recentBrainMemory301,confidence301} from './brainMemory301.js';
const DAY=86400000,done=x=>['DONE','CLOSED','ARCHIVED'].includes(String(x?.status||'').toUpperCase()),date=x=>Date.parse(x?.due||x?.followUpAt||x?.date||x?.start||0)||0,title=x=>x?.title||x?.name||x?.summary||x?.person||'Položka';
function allRows(s){return [['task',s.tasks||[]],['delegation',s.delegations||[]],['inbox',s.inbox||[]],['personalInbox',s.personalInbox?.items||[]],['admin',s.personalAdmin?.items||[]]].flatMap(([kind,rows])=>rows.filter(x=>!done(x)).map(x=>({kind,...x,title:title(x)})))}
export function buildUniversalInbox313(s=store.get(),now=Date.now()){const base=buildUniversalInbox302(s),follow=buildFollowUpEngine303(s),rows=allRows(s).map(x=>{const at=date(x),days=at?Math.ceil((at-now)/DAY):null,score=(days!=null&&days<0?95:days===0?85:days!=null&&days<=3?70:45)+(x.kind==='delegation'?5:0);return{...x,days,score,confidence:confidence301({...x,score,days})}}).sort((a,b)=>b.score-a.score);return{version:313,count:rows.length,urgent:rows.filter(x=>x.score>=80),rows,legacy:base,followups:follow.rows.length}}
export function buildFollowUp314(s=store.get(),now=Date.now()){const m=buildFollowUpEngine303(s);return{version:314,rows:m.rows.map(x=>{const days=Number(x.days??0),next=days<0?'Kontaktovat dnes a nastavit nový termín.':days===0?'Kontaktovat dnes.':days<=2?'Připravit follow-up.':'Počkat do plánovaného termínu.';return{...x,next,escalate:days<-3}}),overdue:m.overdue}}
export function buildDecisionMemory315(){const rows=recentBrainMemory301(50);return{version:315,rows,done:rows.filter(x=>x.event==='done').length,snoozed:rows.filter(x=>x.event==='tomorrow').length,last:rows[0]||null}}
export function confidence316(x,now=Date.now()){const base=confidence301(x),at=date(x),age=at?Math.abs(now-at)/DAY:null,hasReason=!!(x?.reason||x?.risk),hasSource=!!(x?.source||x?.area||x?.kind);let quality=base+(hasReason?3:-5)+(hasSource?2:-3);if(age!=null&&age>90)quality-=8;return Math.max(25,Math.min(98,Math.round(quality)))}
export function buildChanges317(s=store.get()){const a=buildActivityFeed303(s);return{version:317,newCount:a.newRows.length,rows:a.rows.slice(0,30),newRows:a.newRows}}
export function buildTimeline318(s=store.get(),now=Date.now()){const legacy=buildLifeTimeline303(s),rows=allRows(s).map(x=>{const at=date(x);return at?{...x,at,days:Math.ceil((at-now)/DAY)}:null}).filter(Boolean).filter(x=>x.days>=-30&&x.days<=90).sort((a,b)=>a.at-b.at);return{version:318,rows,overdue:rows.filter(x=>x.days<0),today:rows.filter(x=>x.days===0),week:rows.filter(x=>x.days>0&&x.days<=7),month:rows.filter(x=>x.days>7&&x.days<=30),quarter:rows.filter(x=>x.days>30&&x.days<=90),legacy}}
export function buildIntelligence318(s=store.get()){return{inbox:buildUniversalInbox313(s),followups:buildFollowUp314(s),memory:buildDecisionMemory315(),changes:buildChanges317(s),timeline:buildTimeline318(s)}}
function decorate(){const root=document.querySelector('[data-kamil-core312]');if(!root)return;const m=buildIntelligence318(store.get()),side=root.querySelector('.brain300-side');if(!side)return;let card=side.querySelector('[data-intelligence318]');if(!card){card=document.createElement('button');card.type='button';card.className='os303-card';card.dataset.intelligence318='1';card.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('kamil:detail-drawer',{detail:{title:'Intelligence 318',html:`<div class="os303-list"><div class="os303-row"><span><b>${m.inbox.urgent.length} urgentních</b><small>Universal Inbox</small></span></div><div class="os303-row"><span><b>${m.followups.rows.length} follow-upů</b><small>${m.followups.rows.filter(x=>x.escalate).length} k eskalaci</small></span></div><div class="os303-row"><span><b>${m.changes.newCount} změn</b><small>od poslední kontroly</small></span></div><div class="os303-row"><span><b>${m.timeline.rows.length} termínů</b><small>v horizontu 90 dní</small></span></div></div>`}})));side.appendChild(card)}card.innerHTML=`<small>INTELLIGENCE</small><b>${m.inbox.urgent.length+m.followups.rows.filter(x=>x.escalate).length}</b><span>věcí vyžaduje pozornost</span>`;window.__KAMIL_INTELLIGENCE318__={version:318,model:m,at:Date.now()}}
let timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(decorate,120)};
export function installIntelligence318(){store.subscribe?.(schedule);window.addEventListener('kamil:view-change',schedule);schedule();setTimeout(schedule,500)}
