import {store} from './state.js';
import {installKamilBrain301} from './kamilBrain301.js';
import {buildKamilBrain300} from './kamilBrain300.js';
import {confidence301,brainMemoryStats301} from './brainMemory301.js';
import {buildUniversalInbox302,openUniversalInbox302} from './universalInbox302.js';

const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ensureCss(){if(document.querySelector('link[data-brain302]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./kamilBrain302.css';l.dataset.brain302='1';document.head.appendChild(l)}
function candidates(m){return [m?.now,...(m?.next||[]),...(m?.waiting||[]),...(m?.risk||[])].filter(Boolean)}
function resolve(node,m){const id=node?.closest?.('[data-brain-item]')?.dataset?.brainItem||'';return candidates(m).find(x=>String(x.id||x.title||'')===id)||candidates(m).find(x=>norm(x.title)===norm(id))||null}
function why(c){const confidence=confidence301(c),parts=[];if(c?.reason)parts.push(c.reason);if(c?.risk)parts.push(c.risk);if(c?.days!=null)parts.push(c.days<0?`${Math.abs(c.days)} dní po termínu`:c.days===0?'termín je dnes':`termín je za ${c.days} dní`);if(c?.score>=80)parts.push('má velmi vysokou prioritu');else if(c?.score>=55)parts.push('má zvýšenou prioritu');if(c?.area)parts.push(`oblast: ${c.area}`);return{confidence,headline:confidence>=80?'Doporučení je silné':confidence>=65?'Doporučení je rozumně jisté':'Doporučení ber jako návrh',parts:parts.filter(Boolean),next:c?.days!=null&&c.days<0?'Buď dokončit, nebo nastavit nový konkrétní termín.':'Pokud to teď neuděláš, nastav další konkrétní krok.'}}
function openWhy(c){const w=why(c);window.dispatchEvent(new CustomEvent('kamil:detail-drawer',{detail:{title:`Proč právě tohle · ${w.confidence}%`,html:`<div class="why302"><div class="why302-score"><b>${w.confidence}%</b><span>${esc(w.headline)}</span></div><h3>${esc(c.title||'Položka')}</h3><ul>${w.parts.length?w.parts.map(x=>`<li>${esc(x)}</li>`).join(''):'<li>Brain ji vytáhl z aktuálního pořadí priorit.</li>'}</ul><div class="why302-next"><small>Doporučený další krok</small><b>${esc(w.next)}</b></div></div>`}}))}
function enhance(){const root=document.querySelector('[data-kamil-brain300]');if(!root)return;const m=buildKamilBrain300(),uin=buildUniversalInbox302(store.get()),memory=brainMemoryStats301();root.querySelector('.brain300-head small')?.replaceChildren(document.createTextNode('KAMIL BRAIN · v302'));for(const item of root.querySelectorAll('[data-brain-item]')){const c=resolve(item,m);if(!c)continue;const actions=item.querySelector('.brain300-actions');if(actions&&!actions.querySelector('[data-brain-why302]')){const b=document.createElement('button');b.type='button';b.dataset.brainWhy302='1';b.textContent='Proč';b.title='Proč Brain doporučuje právě tuto položku';b.addEventListener('click',e=>{e.stopPropagation();openWhy(c)});actions.insertBefore(b,actions.lastElementChild||null)}}const side=root.querySelector('.brain300-side');if(side){let box=side.querySelector('[data-universal-inbox302]');if(!box){box=document.createElement('button');box.type='button';box.dataset.universalInbox302='1';box.className='uin302-card';box.addEventListener('click',openUniversalInbox302);side.prepend(box)}box.innerHTML=`<span><small>UNIVERSAL INBOX</small><b>${uin.count} otevřených</b></span><span><strong>${uin.urgent.length}</strong><small>urgentní</small></span>`}window.__KAMIL_BRAIN302__={version:302,inbox:uin,memory,at:Date.now()}}
let timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(enhance,90)};
export function installKamilBrain302(){ensureCss();installKamilBrain301();store.subscribe?.(()=>schedule());window.addEventListener('kamil:view-change',schedule);const host=document.querySelector('#todayView')||document.body;new MutationObserver(schedule).observe(host,{childList:true,subtree:true});schedule();setTimeout(schedule,550)}
