import {store} from './state.js';
import {buildKamilBrain300} from './kamilBrain300.js';
import {confidence301,brainMemoryStats301,rememberBrain301} from './brainMemory301.js';
import {buildUniversalInbox302,openUniversalInbox302} from './universalInbox302.js';
import {buildLifeTimeline303,timelineLabel303} from './lifeTimeline303.js';
import {buildActivityFeed303,markActivitySeen303} from './activityFeed303.js';
import {buildFollowUpEngine303,completeFollowUp303,snoozeFollowUp303,touchFollowUp303} from './followUpEngine303.js';
import {openLifeOperator298} from './lifeOperator298.js';
const DAY=86400000,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function css(){for(const href of ['./kamilBrain300.css','./kamilBrain302.css','./kamilBrain303.css'])if(!document.querySelector(`link[href="${href}"]`)){const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.appendChild(l)}}
function collections(s){return [['tasks',s.tasks||[]],['delegations',s.delegations||[]],['inbox',s.inbox||[]],['personalInbox',s.personalInbox?.items||[]],['personalAdmin',s.personalAdmin?.items||[]]]}
function findSource(s,c){const id=c?.source?.id||c?.id?.split(':').slice(1).join(':'),title=norm(c?.title);for(const [collection,rows] of collections(s)){const index=rows.findIndex(x=>(id&&x.id===id)||(!id&&norm(x.title||x.name||x.summary)===title));if(index>=0)return{collection,index}}return null}
function mutate(c,action){const hit=findSource(store.get(),c);if(!hit)return false;store.mutate(`Kamil Core 312: ${action}`,state=>{const rows=hit.collection==='personalInbox'?state.personalInbox.items:hit.collection==='personalAdmin'?state.personalAdmin.items:state[hit.collection],item=rows?.[hit.index];if(!item)return;if(action==='done'){item.status='DONE';item.completedAt=new Date().toISOString()}else{const d=new Date(Date.now()+DAY);d.setHours(9,0,0,0);if(hit.collection==='delegations')item.followUpAt=d.toISOString();else item.due=d.toISOString();item.status=item.status||'OPEN'}item.updatedAt=new Date().toISOString()});rememberBrain301(c,action,{confidence:confidence301(c)});return true}
export function normalizeAction312(x,kind='task'){return{id:String(x?.id||x?.title||crypto.randomUUID()),title:x?.title||x?.name||'Položka',reason:x?.reason||x?.risk||'',urgency:Number(x?.score||0),confidence:confidence301(x||{}),source:kind,deadline:x?.due||x?.followUpAt||null,status:x?.status||'OPEN',raw:x}}
function item(x,kind){if(!x)return'';const a=normalizeAction312(x,kind),why=a.reason||(x.days!=null?(x.days<0?`${Math.abs(x.days)} d po termínu`:x.days===0?'Dnes':`Za ${x.days} d`):'');return `<article class="brain300-item brain300-${kind}" data-core312-item="${esc(a.id)}"><div><b>${esc(a.title)}</b><span class="brain300-confidence">${a.confidence}%</span><small>${esc(x.area||a.source)}${why?` · ${esc(why)}`:''}</small></div><div class="brain300-actions"><button data-core312-action="done">Hotovo</button><button data-core312-action="tomorrow">Zítra</button><button data-core312-action="why">Proč</button><button data-core312-action="detail">Detail</button></div></article>`}
function model(){const brain=buildKamilBrain300(store.get()),uin=buildUniversalInbox302(store.get()),timeline=buildLifeTimeline303(store.get()),activity=buildActivityFeed303(store.get()),follow=buildFollowUpEngine303(store.get()),memory=brainMemoryStats301();return{brain,uin,timeline,activity,follow,memory}}
function render(){const host=document.querySelector('#todayView');if(!host)return false;const m=model(),b=m.brain;host.querySelectorAll('[data-kamil-brain300],[data-operator-home299],[data-today-dashboard213]').forEach(x=>x.remove());const html=`<section class="brain300 os312" data-kamil-core312><header class="brain300-head"><div><small>KAMIL CORE · 312</small><h2>Co má smysl udělat teď</h2></div><button type="button" data-core312-open>Celý přehled</button></header><div class="brain300-layout"><div class="brain300-main"><section class="brain300-zone brain300-now"><label>TEĎ</label>${b.now?item(b.now,'now'):'<div class="brain300-clear">Nic kritického teď nehoří.</div>'}</section><section class="brain300-zone"><label>POTOM</label>${b.next.length?b.next.map(x=>item(x,'next')).join(''):'<div class="brain300-clear">Žádná další priorita.</div>'}</section><section class="brain300-zone"><label>ČEKÁM</label>${b.waiting.length?b.waiting.map(x=>item(x,'waiting')).join(''):'<div class="brain300-clear">Žádný prošlý follow-up.</div>'}</section><section class="brain300-zone"><label>RIZIKO</label>${b.risk.length?b.risk.map(x=>item(x,'risk')).join(''):'<div class="brain300-clear">Bez kritického rizika.</div>'}</section></div><aside class="brain300-side"><button class="uin302-card" data-core312-inbox><span><small>UNIVERSAL INBOX</small><b>${m.uin.count} otevřených</b></span><span><strong>${m.uin.urgent.length}</strong><small>urgentní</small></span></button><button class="os303-card" data-core312-timeline><small>LIFE TIMELINE</small><b>${m.timeline.today.length+m.timeline.week.length}</b><span>${m.timeline.overdue.length} po termínu</span></button><button class="os303-card" data-core312-activity><small>CO SE ZMĚNILO</small><b>${m.activity.newRows.length}</b><span>${m.activity.newRows.length?'nových změn':'vše přečteno'}</span></button><button class="os303-card" data-core312-follow><small>FOLLOW-UP RADAR</small><b>${m.follow.rows.length}</b><span>${m.follow.overdue.length} po termínu</span></button><div class="brain300-kpis"><span><b>${m.memory.count}</b><small>rozhodnutí</small></span><span><b>${b.deadlineCount}</b><small>termíny</small></span><span><b>${b.inboxCount}</b><small>inbox</small></span></div></aside></div></section>`;host.insertAdjacentHTML('afterbegin',html);window.__KAMIL_CORE312__={version:312,model:m,at:Date.now()};return true}
function resolve(el){const id=el.closest('[data-core312-item]')?.dataset.core312Item,m=window.__KAMIL_CORE312__?.model?.brain,all=[m?.now,...(m?.next||[]),...(m?.waiting||[]),...(m?.risk||[])].filter(Boolean);return all.find(x=>String(x.id||x.title)===id)||all.find(x=>norm(x.title)===norm(id))}
function drawer(title,html){window.dispatchEvent(new CustomEvent('kamil:detail-drawer',{detail:{title,html}}))}
function onClick(e){if(e.target.closest('[data-core312-open]'))return openLifeOperator298();if(e.target.closest('[data-core312-inbox]'))return openUniversalInbox302();if(e.target.closest('[data-core312-timeline]')){const t=buildLifeTimeline303(store.get());return drawer('Life Timeline',`<div class="os303-list">${t.rows.slice(0,24).map(x=>`<div class="os303-row ${x.days<0?'hot':''}"><span><b>${esc(x.title)}</b><small>${esc(x.area)} · ${esc(timelineLabel303(x))}</small></span></div>`).join('')}</div>`)}if(e.target.closest('[data-core312-activity]')){const a=buildActivityFeed303(store.get());markActivitySeen303();return drawer('Co se změnilo',`<div class="os303-list">${a.rows.slice(0,24).map(x=>`<div class="os303-row"><span><b>${esc(x.title)}</b><small>${new Date(x.at).toLocaleString('cs-CZ')}</small></span></div>`).join('')}</div>`)}if(e.target.closest('[data-core312-follow]')){const f=buildFollowUpEngine303(store.get());return drawer('Follow-up Radar',`<div class="os303-list">${f.rows.slice(0,20).map(x=>`<div class="os303-row"><span><b>${esc(x.title)}</b><small>${esc(x.reason||'Follow-up')}</small></span></div>`).join('')}</div>`)}const btn=e.target.closest('[data-core312-action]');if(!btn)return;const c=resolve(btn),a=btn.dataset.core312Action;if(!c)return;if(a==='done'||a==='tomorrow'){mutate(c,a);schedule()}else if(a==='why'){const n=normalizeAction312(c);drawer(`Proč právě tohle · ${n.confidence}%`,`<div class="why302"><h3>${esc(n.title)}</h3><p>${esc(n.reason||'Je vysoko v aktuálním pořadí priorit.')}</p></div>`)}else openLifeOperator298()}
let timer=0;function schedule(){clearTimeout(timer);timer=setTimeout(render,90)}
export function installKamilCore312(){css();document.documentElement.dataset.core312='1';document.addEventListener('click',onClick,true);store.subscribe?.(schedule);window.addEventListener('kamil:view-change',e=>{if(!e.detail||e.detail==='today')schedule()});schedule();setTimeout(schedule,350);window.__KAMIL_ACTION_MODEL312__={normalize:normalizeAction312}}
