import {store} from './state.js';
import {buildLifeOperator298,openLifeOperator298} from './lifeOperator298.js';

const DAY=86400000;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const label=x=>x?.title||x?.name||x?.summary||x?.person||'Položka';

function ensureCss(){if(document.querySelector('link[data-brain300]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./kamilBrain300.css';l.dataset.brain300='1';document.head.appendChild(l)}
function collections(s){return [
 ['tasks',s.tasks||[]],['delegations',s.delegations||[]],['inbox',s.inbox||[]],
 ['personalInbox',s.personalInbox?.items||[]],['personalAdmin',s.personalAdmin?.items||[]]
]}
function findSource(s,candidate){const id=candidate?.source?.id||candidate?.id?.split(':').slice(1).join(':');const title=norm(candidate?.title||label(candidate?.source));for(const [collection,rows] of collections(s)){const index=rows.findIndex(x=>(id&&x.id===id)||(!id&&norm(label(x))===title));if(index>=0)return{collection,index}}return null}
function mutateItem(candidate,action){const s=store.get(),hit=findSource(s,candidate);if(!hit)return false;store.mutate(`Kamil Brain: ${action}`,state=>{const rows=hit.collection==='personalInbox'?state.personalInbox.items:hit.collection==='personalAdmin'?state.personalAdmin.items:state[hit.collection];const item=rows[hit.index];if(!item)return;if(action==='hotovo'){item.status='DONE';item.completedAt=new Date().toISOString()}if(action==='zítra'){const d=new Date(Date.now()+DAY);d.setHours(9,0,0,0);if(hit.collection==='delegations')item.followUpAt=d.toISOString();else item.due=d.toISOString();item.status=item.status||'OPEN'}item.updatedAt=new Date().toISOString()});window.dispatchEvent(new CustomEvent('kamil:personal-action-updated'));return true}
function changes(s,now){return (s.audit||[]).filter(x=>Date.parse(x.at||0)>=now-24*60*60*1000).slice(0,5).map(x=>({title:x.label||'Změna',at:x.at}))}
function riskRows(m){const rows=[];for(const x of m.deadlines.critical||[])rows.push({...x,risk:'Termín'});for(const x of m.notifications||[])if((x.score||0)>=55)rows.push({...x,risk:x.reason||'Pozornost'});const seen=new Set();return rows.filter(x=>{const k=norm(x.title);if(seen.has(k))return false;seen.add(k);return true}).slice(0,3)}
function ranked(m){const top=(m.morning.top3||[]).map((x,i)=>({...x,rank:i+1}));return{now:top[0]||null,next:top.slice(1,3),waiting:(m.waiting.overdue||[]).slice(0,3),risk:riskRows(m)}}
export function buildKamilBrain300(s=store.get(),now=Date.now()){const life=buildLifeOperator298(s,now),r=ranked(life);return{version:300,generatedAt:new Date(now).toISOString(),now:r.now,next:r.next,waiting:r.waiting,risk:r.risk,changes:changes(s,now),inboxCount:life.inbox.length,deadlineCount:life.deadlines.critical.length,followupCount:life.waiting.overdue.length,life}}
function actionButtons(x){if(!x)return'';return `<div class="brain300-actions"><button data-brain-action="done">Hotovo</button><button data-brain-action="tomorrow">Zítra</button><button data-brain-action="detail">Detail</button></div>`}
function itemHtml(x,kind='next'){if(!x)return'';const reason=x.reason||x.risk||(x.days!=null?(x.days<0?`${Math.abs(x.days)} d po termínu`:x.days===0?'Dnes':`Za ${x.days} d`):'');return `<article class="brain300-item brain300-${kind}" data-brain-item="${esc(x.id||x.title||'')}"><div><b>${esc(x.title||'Položka')}</b><small>${esc(x.area||'Osobní')}${reason?` · ${esc(reason)}`:''}</small></div>${actionButtons(x)}</article>`}
function renderHtml(m){const change=m.changes.length?m.changes.map(x=>`<li><span>${esc(x.title)}</span><time>${new Date(x.at).toLocaleTimeString('cs-CZ',{hour:'2-digit',minute:'2-digit'})}</time></li>`).join(''):'<li><span>Za posledních 24 hodin bez zaznamenané změny.</span></li>';return `<section class="brain300" data-kamil-brain300><header class="brain300-head"><div><small>KAMIL BRAIN</small><h2>Co má smysl udělat teď</h2></div><button type="button" data-brain-open>Celý přehled</button></header><div class="brain300-layout"><div class="brain300-main"><section class="brain300-zone brain300-now"><label>TEĎ</label>${m.now?itemHtml(m.now,'now'):'<div class="brain300-clear">Nic kritického teď nehoří.</div>'}</section><section class="brain300-zone"><label>POTOM</label>${m.next.length?m.next.map(x=>itemHtml(x)).join(''):'<div class="brain300-clear">Žádná další priorita.</div>'}</section><section class="brain300-zone"><label>ČEKÁM</label>${m.waiting.length?m.waiting.map(x=>itemHtml(x,'waiting')).join(''):'<div class="brain300-clear">Žádný prošlý follow-up.</div>'}</section><section class="brain300-zone"><label>RIZIKO</label>${m.risk.length?m.risk.map(x=>itemHtml(x,'risk')).join(''):'<div class="brain300-clear">Bez kritického rizika.</div>'}</section></div><aside class="brain300-side"><div class="brain300-kpis"><span><b>${m.followupCount}</b><small>follow-up</small></span><span><b>${m.deadlineCount}</b><small>termíny</small></span><span><b>${m.inboxCount}</b><small>inbox</small></span></div><div class="brain300-changes"><div class="brain300-change-head"><b>Co se změnilo</b><small>24 h</small></div><ul>${change}</ul></div></aside></div></section>`}
function resolveCandidate(el,m){const id=el.closest('[data-brain-item]')?.dataset.brainItem||'';const all=[m.now,...m.next,...m.waiting,...m.risk].filter(Boolean);return all.find(x=>String(x.id||x.title||'')===id)||all.find(x=>norm(x.title)===norm(id))}
let timer=0;
export function renderKamilBrain300(){const host=document.querySelector('#todayView');if(!host)return false;const m=buildKamilBrain300();let node=host.querySelector('[data-kamil-brain300]');if(!node){node=document.createElement('div');const target=host.querySelector('.today213-head')||host.firstElementChild;if(target?.parentNode)target.parentNode.insertBefore(node,target.nextSibling);else host.prepend(node)}node.outerHTML=renderHtml(m);const fresh=host.querySelector('[data-kamil-brain300]');fresh?.querySelector('[data-brain-open]')?.addEventListener('click',openLifeOperator298);fresh?.addEventListener('click',e=>{const btn=e.target.closest('[data-brain-action]');if(!btn)return;const candidate=resolveCandidate(btn,m);if(!candidate)return;const a=btn.dataset.brainAction;if(a==='done')mutateItem(candidate,'hotovo');else if(a==='tomorrow')mutateItem(candidate,'zítra');else openLifeOperator298()});window.__KAMIL_BRAIN300__={...m,renderedAt:Date.now()};return true}
function schedule(){clearTimeout(timer);timer=setTimeout(renderKamilBrain300,40)}
export function installKamilBrain300(){ensureCss();schedule();setTimeout(schedule,250);setTimeout(schedule,900);store.subscribe?.(()=>schedule());window.addEventListener('kamil:view-change',e=>{if(e.detail==='today')schedule()});window.addEventListener('kamil:personal-action-updated',schedule);window.__KAMIL_BRAIN300_API__={build:buildKamilBrain300,render:renderKamilBrain300}}
