import {store} from './state.js';
import {installKamilBrain302} from './kamilBrain302.js';
import {buildLifeTimeline303,timelineLabel303} from './lifeTimeline303.js';
import {buildActivityFeed303,markActivitySeen303} from './activityFeed303.js';
import {buildFollowUpEngine303,completeFollowUp303,snoozeFollowUp303,touchFollowUp303} from './followUpEngine303.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ensureCss(){if(document.querySelector('link[data-brain303]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./kamilBrain303.css';l.dataset.brain303='1';document.head.appendChild(l)}
const drawer=(title,html)=>window.dispatchEvent(new CustomEvent('kamil:detail-drawer',{detail:{title,html}}));
function openTimeline(){const m=buildLifeTimeline303(store.get());drawer('Life Timeline',`<div class="os303-list">${m.rows.slice(0,24).map(x=>`<div class="os303-row ${x.days<0?'hot':''}"><span><b>${esc(x.title)}</b><small>${esc(x.area)} · ${esc(timelineLabel303(x))}</small></span></div>`).join('')||'<p>Žádné termíny v horizontu 60 dní.</p>'}</div>`)}
function openActivity(){const m=buildActivityFeed303(store.get());markActivitySeen303();drawer('Co se změnilo',`<div class="os303-list">${m.rows.slice(0,24).map(x=>`<div class="os303-row"><span><b>${esc(x.title)}</b><small>${x.kind==='decision'?'Rozhodnutí':'Změna'} · ${new Date(x.at).toLocaleString('cs-CZ')}</small></span></div>`).join('')||'<p>Za posledních 7 dní nejsou žádné zaznamenané změny.</p>'}</div>`);setTimeout(schedule,50)}
function openFollowups(){const m=buildFollowUpEngine303(store.get());drawer('Follow-up Radar',`<div class="os303-list">${m.rows.slice(0,20).map(x=>`<div class="os303-row ${x.days<0?'hot':''}"><span><b>${esc(x.title)}</b><small>${esc(x.reason||'Follow-up')}</small></span><div class="os303-actions"><button data-follow303="touch" data-id="${esc(x.source?.id||x.id||'')}">Kontaktováno</button><button data-follow303="snooze" data-id="${esc(x.source?.id||x.id||'')}">Zítra</button><button data-follow303="done" data-id="${esc(x.source?.id||x.id||'')}">Hotovo</button></div></div>`).join('')||'<p>Žádný follow-up v příštích 7 dnech.</p>'}</div>`)}
function card(parent,key,label,value,sub,open){let b=parent.querySelector(`[data-${key}]`);if(!b){b=document.createElement('button');b.type='button';b.dataset[key]='1';b.className='os303-card';b.addEventListener('click',open);parent.prepend(b)}b.innerHTML=`<small>${label}</small><b>${value}</b><span>${sub}</span>`}
function enhance(){const root=document.querySelector('[data-kamil-brain300]');if(!root)return;const t=buildLifeTimeline303(store.get()),a=buildActivityFeed303(store.get()),f=buildFollowUpEngine303(store.get());root.querySelector('.brain300-head small')?.replaceChildren(document.createTextNode('KAMIL BRAIN · v303'));const side=root.querySelector('.brain300-side');if(side){card(side,'lifeTimeline303','LIFE TIMELINE',t.today.length+t.week.length,`${t.overdue.length} po termínu`,openTimeline);card(side,'activity303','CO SE ZMĚNILO',a.newRows.length,a.newRows.length?'nových změn':'vše přečteno',openActivity);card(side,'followups303','FOLLOW-UP RADAR',f.rows.length,`${f.overdue.length} po termínu`,openFollowups)}window.__KAMIL_BRAIN303__={version:303,timeline:t,activity:a,followups:f,at:Date.now()}}
let timer=0;function schedule(){clearTimeout(timer);timer=setTimeout(enhance,90)}
export function installKamilBrain303(){ensureCss();installKamilBrain302();document.addEventListener('click',e=>{const b=e.target.closest?.('[data-follow303]');if(!b)return;const id=b.dataset.id,a=b.dataset.follow303;let ok=false;if(a==='done')ok=completeFollowUp303(id);if(a==='snooze')ok=snoozeFollowUp303(id,1);if(a==='touch')ok=touchFollowUp303(id);if(ok){openFollowups();schedule()}},true);store.subscribe?.(()=>schedule());window.addEventListener('kamil:view-change',schedule);const host=document.querySelector('#todayView')||document.body;new MutationObserver(schedule).observe(host,{childList:true,subtree:true});schedule();setTimeout(schedule,600)}
