const loaded=new Map(),styles=new Map();
const groups={
 today:{css:['../styles24.css','../decision24.css','../live24.css','../personal26.css','../autopilot28.css','../os34.css','../os35.css','../lifeOs42.css','../platform43.css'],primary:['./lifeOs42Ui.js','./directorUi34.js','./followUpUi35.js','./emailWorkflowUi35.js','./focusActionUi35.js','./os40ExecutiveUi.js'],secondary:['./platform431Stability.js','./platform431LeanUi.js','./desktopBridge43.js','./deadlineRadarUi35.js','./todayBrainUi34.js','./changePulseUi35.js']},
 money:{css:['../styles24.css','../decision24.css','../live24.css','../xtbDetail25.css','../personal26.css','../autopilot28.css','../os34.css'],primary:['./totalPortfolioUi34.js','./externalInvestmentsUi33.js','./os40MoneyUi.js'],secondary:['./cashflowUi25.js','./capitalAllocationUi25.js','./actionPlanUi25.js','./personalMoneyUi26.js','./netWorthUi29.js','./portfolioRebalancerUi29.js','./portfolioRiskMapUi29.js','./spendingIntelligenceUi29.js']},
 tickets:{css:['../styles24.css','../decision24.css','../live24.css','../ticketEvents25.css','../os34.css'],primary:['./ticketCurrentUi33.js','./ticketBrainUi34.js','./os40TicketsUi.js'],secondary:['./ticketProfitUi29.js']},
 home:{css:['../capture24.css','../personal26.css','../autopilot28.css'],primary:['./personalCopilotUi30.js'],secondary:['./documentScannerUi30.js','./documentFilingUi30.js','./renewalRadarUi26.js','./emergencyFileUi26.js']},
 more:{css:['../capture24.css','../personal26.css','../autopilot28.css','../os35.css'],primary:['./autopilotNavBridge28.js','./personalPlusNav29.js','./os40KnowledgeUi.js'],secondary:['./decisionExplainUi30.js','./decisionJournalUi31.js','./profileBootstrapUi31.js','./systemHealthUi31.js','./liveBrainUi32.js','./dataEngineUi31.js','./recoveryShieldUi32.js','./smartSyncUi31.js','./remoteInboxUi31.js']}
};
function loadModule(path){if(loaded.has(path))return loaded.get(path);const started=performance.now();const p=import(path).then(value=>{window.__KAMIL_MODULE_TIMINGS__=window.__KAMIL_MODULE_TIMINGS__||{};window.__KAMIL_MODULE_TIMINGS__[path]=Math.round(performance.now()-started);return value}).catch(err=>{console.error('[lazyBoot41]',path,err);loaded.delete(path);throw err});loaded.set(path,p);return p}
function loadStyle(path){if(styles.has(path))return styles.get(path);const p=new Promise(resolve=>{const l=document.createElement('link');l.rel='stylesheet';l.href=path;l.dataset.lazyStyle='1';l.onload=()=>resolve(true);l.onerror=()=>resolve(false);document.head.appendChild(l)});styles.set(path,p);return p}
const idle=(fn,timeout=1800)=>'requestIdleCallback'in window?requestIdleCallback(fn,{timeout}):setTimeout(fn,700);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function userBusy(){try{return document.visibilityState==='hidden'||navigator.scheduling?.isInputPending?.({includeContinuous:true})===true}catch{return document.visibilityState==='hidden'}}
async function responsiveLoad(paths,{gap=180}={}){const results=[];for(const path of paths){let waits=0;while(userBusy()&&waits<20){await sleep(250);waits++}try{results.push({status:'fulfilled',value:await loadModule(path)})}catch(reason){results.push({status:'rejected',reason})}if(gap)await sleep(gap)}return results}
function safeMode(){try{return !!JSON.parse(localStorage.getItem('kamil-os-platform43')||'{}')?.safeMode}catch{return false}}
function loadGroup(name,{staged=true}={}){let g=groups[name]||{css:[],primary:[],secondary:[]};if(safeMode())g={...g,primary:g.primary.slice(0,1),secondary:name==='today'?['./platform431Stability.js','./platform431LeanUi.js']:[]};const stylesReady=Promise.allSettled(g.css.map(loadStyle));const firstModule=g.primary.slice(0,1),restPrimary=g.primary.slice(1);const first=Promise.all([stylesReady,responsiveLoad(firstModule,{gap:0})]).then(async value=>{if(restPrimary.length)responsiveLoad(restPrimary,{gap:220});return value});if(g.secondary.length){const startSecondary=()=>responsiveLoad(g.secondary,{gap:320});if(staged)first.finally(()=>setTimeout(()=>idle(startSecondary,3000),2500));else first.finally(startSecondary)}return first}
function currentView(){return document.querySelector('.view.on')?.id?.replace('view-','')||'today'}
function boot(){let booted=false;const lateBoot=()=>{if(booted)return;booted=true;loadGroup(currentView(),{staged:true})};setTimeout(()=>idle(lateBoot,2500),1000);window.addEventListener('kamil:view-change',e=>{booted=true;loadGroup(e.detail||'today',{staged:true})});window.addEventListener('kamil:navigate',e=>{booted=true;loadGroup(e.detail||'today',{staged:true})});window.addEventListener('kamil:more',()=>{booted=true;loadGroup('more',{staged:false}).then(()=>import('./systemDiagnostics421.js')).then(m=>m.renderSystemDiagnostics421()).catch(err=>console.error('[lazyBoot41/system]',err))});setTimeout(()=>idle(()=>responsiveLoad(['./autopilotNavBridge28.js','./personalPlusNav29.js'],{gap:300}),3500),15000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
export {loadGroup,responsiveLoad};
