const loaded=new Map(),styles=new Map();
const MODULE_STATS_KEY='kamil-os-module-stats-43-3';
const QUARANTINE_KEY='kamil-os-module-quarantine-43-5';
const STABILITY_MEMORY_KEY='kamil-os-stability-memory-43-7';
const COLD_THRESHOLD_MS=1100,COLD_MIN_SAMPLES=3;
const QUARANTINE_FAILURES=2,QUARANTINE_WINDOW_MS=30*60*1000,QUARANTINE_TTL_MS=6*60*60*1000;
const SELF_HEAL_PROBE_DELAY_MS=20*60*1000,SELF_HEAL_PROBE_COOLDOWN_MS=30*60*1000,SELF_HEAL_MAX_PROBES=3;
const MEMORY_COLD_SCORE=6,MEMORY_BLOCK_SCORE=10,MEMORY_MIN_SAMPLES=3;
let lastUserIntentAt=0,selfHealPromise=null;
const groups={
 today:{css:['../styles24.css','../decision24.css','../live24.css','../personal26.css','../autopilot28.css','../os34.css','../os35.css','../lifeOs42.css','../platform43.css'],primary:['./lifeOs42Ui.js','./directorUi34.js','./followUpUi35.js','./emailWorkflowUi35.js','./focusActionUi35.js','./os40ExecutiveUi.js'],secondary:['./platform431Stability.js','./platform431LeanUi.js','./desktopBridge43.js','./deadlineRadarUi35.js','./todayBrainUi34.js','./changePulseUi35.js']},
 money:{css:['../styles24.css','../decision24.css','../live24.css','../xtbDetail25.css','../personal26.css','../autopilot28.css','../os34.css'],primary:['./totalPortfolioUi34.js','./externalInvestmentsUi33.js','./os40MoneyUi.js'],secondary:['./cashflowUi25.js','./capitalAllocationUi25.js','./actionPlanUi25.js','./personalMoneyUi26.js','./netWorthUi29.js','./portfolioRebalancerUi29.js','./portfolioRiskMapUi29.js','./spendingIntelligenceUi29.js']},
 tickets:{css:['../styles24.css','../decision24.css','../live24.css','../ticketEvents25.css','../os34.css'],primary:['./ticketCurrentUi33.js','./ticketBrainUi34.js','./os40TicketsUi.js'],secondary:['./ticketProfitUi29.js']},
 home:{css:['../capture24.css','../personal26.css','../autopilot28.css'],primary:['./personalCopilotUi30.js'],secondary:['./documentScannerUi30.js','./documentFilingUi30.js','./renewalRadarUi26.js','./emergencyFileUi26.js']},
 more:{css:['../capture24.css','../personal26.css','../autopilot28.css','../os35.css'],primary:['./autopilotNavBridge28.js','./personalPlusNav29.js','./os40KnowledgeUi.js'],secondary:['./decisionExplainUi30.js','./decisionJournalUi31.js','./profileBootstrapUi31.js','./systemHealthUi31.js','./liveBrainUi32.js','./dataEngineUi31.js','./recoveryShieldUi32.js','./smartSyncUi31.js','./remoteInboxUi31.js']}
};
function readStats(){try{return JSON.parse(localStorage.getItem(MODULE_STATS_KEY)||'{}')||{}}catch{return{}}}
function readMemory(){try{return JSON.parse(localStorage.getItem(STABILITY_MEMORY_KEY)||'{}')||{}}catch{return{}}}
function writeMemory(all){try{localStorage.setItem(STABILITY_MEMORY_KEY,JSON.stringify(all))}catch{}window.__KAMIL_STABILITY_MEMORY__=all;return all}
function backgroundPaths(){return new Set(Object.values(groups).flatMap(g=>[...g.primary.slice(1),...g.secondary]))}
function updateMemory(path,{timingMs=null,failure=false,healed=false}={}){if(!backgroundPaths().has(path))return;const all=readMemory(),prev=all[path]||{},ms=Number(timingMs),samples=Number(prev.samples||0)+(Number.isFinite(ms)?1:0);let score=Number(prev.score||0);if(Number.isFinite(ms)){if(ms>1600)score+=3;else if(ms>900)score+=2;else if(ms>450)score+=1;else if(ms<350)score-=1}if(failure)score+=4;if(healed)score-=3;score=Math.max(0,Math.min(20,Math.round(score)));all[path]={score,samples,failures:Number(prev.failures||0)+(failure?1:0),successes:Number(prev.successes||0)+(Number.isFinite(ms)?1:0),lastMs:Number.isFinite(ms)?Math.round(ms):Number(prev.lastMs||0),lastFailureAt:failure?Date.now():Number(prev.lastFailureAt||0),lastHealthyAt:Number.isFinite(ms)?Date.now():Number(prev.lastHealthyAt||0),updatedAt:Date.now()};writeMemory(all);refreshStabilityMemory();}
function stabilityPolicy(path){if(!backgroundPaths().has(path))return{mode:'normal',score:0,samples:0};const m=readMemory()[path]||{},score=Number(m.score||0),samples=Number(m.samples||0),failures=Number(m.failures||0);if((samples>=MEMORY_MIN_SAMPLES||failures>=2)&&score>=MEMORY_BLOCK_SCORE)return{mode:'blocked',score,samples,failures};if((samples>=MEMORY_MIN_SAMPLES||failures>=1)&&score>=MEMORY_COLD_SCORE)return{mode:'cold',score,samples,failures};return{mode:'normal',score,samples,failures}}
function refreshStabilityMemory(){const all=readMemory(),blocked=[],cold=[];for(const path of backgroundPaths()){const p=stabilityPolicy(path);if(p.mode==='blocked')blocked.push({path,...p});else if(p.mode==='cold')cold.push({path,...p})}blocked.sort((a,b)=>b.score-a.score);cold.sort((a,b)=>b.score-a.score);window.__KAMIL_STABILITY_MEMORY__=all;window.__KAMIL_MEMORY_BLOCKED_MODULES__=blocked;window.__KAMIL_MEMORY_COLD_MODULES__=cold;return{blocked,cold}}
function recordTiming(path,ms){try{const all=readStats(),prev=all[path]||{},avg=prev.avg?Math.round(prev.avg*.7+ms*.3):ms;all[path]={avg,last:ms,count:Number(prev.count||0)+1,at:Date.now()};localStorage.setItem(MODULE_STATS_KEY,JSON.stringify(all));window.__KAMIL_MODULE_STATS__=all;updateMemory(path,{timingMs:ms});refreshColdCandidate()}catch{}}
function adaptiveGap(path,base=180){const avg=Number(readStats()[path]?.avg||0),policy=stabilityPolicy(path);return base+(avg>1600?1200:avg>900?700:avg>450?300:0)+(policy.mode==='cold'?500:policy.mode==='blocked'?900:0)}
function coldCandidate(){const eligible=backgroundPaths(),stats=readStats();return Object.entries(stats).filter(([path,s])=>eligible.has(path)&&Number(s?.count||0)>=COLD_MIN_SAMPLES&&Number(s?.avg||0)>=COLD_THRESHOLD_MS).sort((a,b)=>Number(b[1]?.avg||0)-Number(a[1]?.avg||0))[0]?.[0]||null}
function refreshColdCandidate(){const path=coldCandidate();window.__KAMIL_COLD_MODULE__=path;window.__KAMIL_COLD_MODULE_REASON__=path?{avg:Number(readStats()[path]?.avg||0),count:Number(readStats()[path]?.count||0),threshold:COLD_THRESHOLD_MS}:null;return path}
function readQuarantineRaw(){try{return JSON.parse(localStorage.getItem(QUARANTINE_KEY)||'{}')||{}}catch{return{}}}
function writeQuarantine(all){try{localStorage.setItem(QUARANTINE_KEY,JSON.stringify(all))}catch{}window.__KAMIL_QUARANTINED_MODULES__=all;return all}
function quarantineSnapshot(){const now=Date.now(),all=readQuarantineRaw();let changed=false;for(const [path,q] of Object.entries(all)){if(Number(q?.until||0)<=now){delete all[path];changed=true}}if(changed)writeQuarantine(all);else window.__KAMIL_QUARANTINED_MODULES__=all;return all}
function isQuarantined(path){return Number(quarantineSnapshot()[path]?.until||0)>Date.now()}
function recordFailure(path){if(!backgroundPaths().has(path))return;updateMemory(path,{failure:true});const now=Date.now(),all=readQuarantineRaw(),prev=all[path]||{},failures=(Array.isArray(prev.failures)?prev.failures:[]).filter(t=>now-Number(t)<QUARANTINE_WINDOW_MS);failures.push(now);const next={...prev,failures,lastFailureAt:now};if(failures.length>=QUARANTINE_FAILURES){next.until=now+QUARANTINE_TTL_MS;next.autoProbes=Number(prev.autoProbes||0);if(Number(next.nextProbeAt||0)<=now)next.nextProbeAt=now+SELF_HEAL_PROBE_DELAY_MS}all[path]=next;writeQuarantine(all);if(next.until>now){window.__KAMIL_LAST_QUARANTINE__={path,at:now,until:next.until};window.dispatchEvent(new CustomEvent('kamil:module-quarantined',{detail:{path,until:next.until,failures:failures.length,nextProbeAt:next.nextProbeAt||null}}))}}
function clearQuarantine(path){const all=readQuarantineRaw();if(!all[path])return false;delete all[path];writeQuarantine(all);window.dispatchEvent(new CustomEvent('kamil:module-quarantine-cleared',{detail:{path}}));return true}
function loadModule(path){if(loaded.has(path))return loaded.get(path);const started=performance.now(),wasQuarantined=isQuarantined(path);const p=import(path).then(value=>{const ms=Math.round(performance.now()-started);window.__KAMIL_MODULE_TIMINGS__=window.__KAMIL_MODULE_TIMINGS__||{};window.__KAMIL_MODULE_TIMINGS__[path]=ms;recordTiming(path,ms);if(wasQuarantined)updateMemory(path,{healed:true});clearQuarantine(path);return value}).catch(err=>{console.error('[lazyBoot41]',path,err);loaded.delete(path);recordFailure(path);throw err});loaded.set(path,p);return p}
function safeToSelfHeal(){try{return document.visibilityState==='visible'&&Date.now()-lastUserIntentAt>8000&&navigator.scheduling?.isInputPending?.({includeContinuous:true})!==true}catch{return document.visibilityState==='visible'&&Date.now()-lastUserIntentAt>8000}}
async function probeQuarantinedModule436(path,{force=false}={}){const now=Date.now(),all=quarantineSnapshot(),q=all[path];if(!q||!backgroundPaths().has(path))return false;if(!force&&(Number(q.nextProbeAt||0)>now||Number(q.autoProbes||0)>=SELF_HEAL_MAX_PROBES||!safeToSelfHeal()))return false;q.autoProbes=Number(q.autoProbes||0)+1;q.lastProbeAt=now;q.nextProbeAt=now+SELF_HEAL_PROBE_COOLDOWN_MS;all[path]=q;writeQuarantine(all);window.__KAMIL_SELF_HEALING__={path,at:now,attempt:q.autoProbes};window.dispatchEvent(new CustomEvent('kamil:self-heal-probing',{detail:{path,attempt:q.autoProbes}}));try{await loadModule(path);window.__KAMIL_LAST_SELF_HEAL__={path,at:Date.now(),attempt:q.autoProbes};window.dispatchEvent(new CustomEvent('kamil:module-self-healed',{detail:{path,attempt:q.autoProbes}}));return true}catch{const fresh=readQuarantineRaw();if(fresh[path]){fresh[path].nextProbeAt=Date.now()+SELF_HEAL_PROBE_COOLDOWN_MS;writeQuarantine(fresh)}window.dispatchEvent(new CustomEvent('kamil:self-heal-failed',{detail:{path,attempt:q.autoProbes}}));return false}finally{window.__KAMIL_SELF_HEALING__=null}}
function runSelfHealingSweep436({force=false,path=null}={}){if(selfHealPromise)return selfHealPromise;const all=quarantineSnapshot(),now=Date.now();const candidate=path&&all[path]?path:Object.entries(all).filter(([,q])=>force||(Number(q.nextProbeAt||0)<=now&&Number(q.autoProbes||0)<SELF_HEAL_MAX_PROBES)).sort((a,b)=>Number(a[1]?.nextProbeAt||0)-Number(b[1]?.nextProbeAt||0))[0]?.[0]||null;if(!candidate||(!force&&!safeToSelfHeal()))return Promise.resolve(false);selfHealPromise=probeQuarantinedModule436(candidate,{force}).finally(()=>{selfHealPromise=null});return selfHealPromise}
function loadStyle(path){if(styles.has(path))return styles.get(path);const p=new Promise(resolve=>{const l=document.createElement('link');l.rel='stylesheet';l.href=path;l.dataset.lazyStyle='1';l.onload=()=>resolve(true);l.onerror=()=>resolve(false);document.head.appendChild(l)});styles.set(path,p);return p}
const idle=(fn,timeout=1800)=>'requestIdleCallback'in window?requestIdleCallback(fn,{timeout}):setTimeout(fn,700);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function userBusy(){try{return document.visibilityState==='hidden'||navigator.scheduling?.isInputPending?.({includeContinuous:true})===true}catch{return document.visibilityState==='hidden'}}
async function responsiveLoad(paths,{gap=180,allowCold=false,allowQuarantined=false,allowMemoryRisk=false}={}){const results=[],cold=refreshColdCandidate();refreshStabilityMemory();quarantineSnapshot();for(const path of paths){if(isQuarantined(path)&&!allowQuarantined){window.__KAMIL_QUARANTINE_DEFERRED__={path,at:Date.now()};results.push({status:'quarantined',path});continue}const policy=stabilityPolicy(path);if(policy.mode==='blocked'&&!allowMemoryRisk){window.__KAMIL_MEMORY_DEFERRED__={path,at:Date.now(),mode:'blocked',score:policy.score};results.push({status:'memory-blocked',path,score:policy.score});continue}if((path===cold||policy.mode==='cold')&&!allowCold&&!allowMemoryRisk){window.__KAMIL_COLD_DEFERRED__={path,at:Date.now(),memory:policy.mode==='cold'};results.push({status:'deferred',path});continue}let waits=0;while(userBusy()&&waits<40){await sleep(250);waits++}const learnedDelay=adaptiveGap(path,gap);if(learnedDelay>gap)await sleep(Math.min(learnedDelay-gap,1800));try{results.push({status:'fulfilled',value:await loadModule(path)})}catch(reason){results.push({status:'rejected',reason})}if(gap)await sleep(learnedDelay)}return results}
function safeMode(){try{return !!JSON.parse(localStorage.getItem('kamil-os-platform43')||'{}')?.safeMode}catch{return false}}
function loadGroup(name,{staged=true,explicit=false}={}){let g=groups[name]||{css:[],primary:[],secondary:[]};if(safeMode())g={...g,primary:g.primary.slice(0,1),secondary:name==='today'?['./platform431Stability.js','./platform431LeanUi.js']:[]};const stylesReady=Promise.allSettled(g.css.map(loadStyle));const firstModule=g.primary.slice(0,1),restPrimary=g.primary.slice(1);const first=Promise.all([stylesReady,responsiveLoad(firstModule,{gap:0,allowCold:true,allowMemoryRisk:true})]).then(async value=>{if(restPrimary.length)responsiveLoad(restPrimary,{gap:220,allowCold:explicit,allowMemoryRisk:explicit});return value});if(g.secondary.length){const startSecondary=()=>responsiveLoad(g.secondary,{gap:320,allowCold:explicit,allowMemoryRisk:explicit});if(staged)first.finally(()=>setTimeout(()=>idle(startSecondary,3000),2500));else first.finally(startSecondary)}return first}
function currentView(){return document.querySelector('.view.on')?.id?.replace('view-','')||'today'}
function boot(){let booted=false;window.__KAMIL_MODULE_STATS__=readStats();refreshColdCandidate();refreshStabilityMemory();quarantineSnapshot();const noteIntent=()=>{lastUserIntentAt=Date.now()};const explicitIntent=()=>Date.now()-lastUserIntentAt<3000;document.addEventListener('pointerdown',noteIntent,{capture:true,passive:true});document.addEventListener('keydown',noteIntent,{capture:true});const lateBoot=()=>{if(booted)return;booted=true;loadGroup(currentView(),{staged:true,explicit:false})};setTimeout(()=>idle(lateBoot,2500),1000);window.addEventListener('kamil:view-change',e=>{booted=true;loadGroup(e.detail||'today',{staged:true,explicit:explicitIntent()})});window.addEventListener('kamil:navigate',e=>{booted=true;loadGroup(e.detail||'today',{staged:true,explicit:explicitIntent()})});window.addEventListener('kamil:more',()=>{booted=true;loadGroup('more',{staged:false,explicit:explicitIntent()}).then(()=>import('./systemDiagnostics421.js')).then(m=>m.renderSystemDiagnostics421()).catch(err=>console.error('[lazyBoot41/system]',err))});window.addEventListener('kamil:load-cold-module',e=>{const path=e.detail?.path||e.detail;if(!path||isQuarantined(path))return;loadModule(path).then(()=>window.dispatchEvent(new CustomEvent('kamil:cold-module-loaded',{detail:{path}}))).catch(err=>console.error('[lazyBoot41/cold]',path,err))});window.addEventListener('kamil:retry-quarantined-module',e=>{const path=e.detail?.path||e.detail;if(!path||!isQuarantined(path))return;loadModule(path).then(()=>window.dispatchEvent(new CustomEvent('kamil:module-quarantine-recovered',{detail:{path}}))).catch(()=>window.dispatchEvent(new CustomEvent('kamil:module-quarantine-retry-failed',{detail:{path}})))});window.addEventListener('kamil:self-heal-now',e=>{const path=e.detail?.path||e.detail;runSelfHealingSweep436({force:true,path}).catch(()=>{})});window.addEventListener('kamil:loader-stats-reset',()=>refreshColdCandidate());window.addEventListener('kamil:stability-memory-reset',()=>refreshStabilityMemory());window.addEventListener('kamil:quarantine-reset',()=>quarantineSnapshot());setTimeout(()=>idle(()=>runSelfHealingSweep436(),4000),45000);setInterval(()=>idle(()=>runSelfHealingSweep436(),4000),10*60*1000);setTimeout(()=>idle(()=>responsiveLoad(['./autopilotNavBridge28.js','./personalPlusNav29.js'],{gap:300,allowCold:false,allowMemoryRisk:false}),3500),15000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
export {loadGroup,responsiveLoad,refreshColdCandidate,refreshStabilityMemory,stabilityPolicy,quarantineSnapshot,isQuarantined,runSelfHealingSweep436};
