import {store} from './state.js';
import {h,money,modal} from './utils.js';
const A=v=>Array.isArray(v)?v:[],N=v=>Number(v||0),U=v=>String(v||'').toUpperCase();
const CLOSED=new Set(['DONE','CLOSED','ARCHIVED','RESOLVED','PAID','CANCELLED','CANCELED']);
const WORK_RE=/zak[aá]zk|faktur|dodavat|cest[aá]k|doch[aá]zk|ředitel|reditel|pks|cpi|zbrojov|\bzl\b|projektov[aá] karta|pracovn/i;
const open=x=>!CLOSED.has(U(x?.status||x?.workflow)),personal=x=>!WORK_RE.test(`${x?.title||''} ${x?.name||''} ${x?.area||''} ${x?.category||''} ${x?.project||''}`);
const first=(...v)=>v.find(x=>x!==undefined&&x!==null&&x!=='')??null,day=v=>{const t=Date.parse(v||'');if(!Number.isFinite(t))return null;return Math.ceil((t-Date.now())/86400000)};
function norm(rows,kind){return A(rows).filter(open).filter(personal).map(x=>({kind,title:first(x.title,x.name,x.item,kind),amount:N(first(x.amount,x.price,x.cost,x.budget)),date:first(x.due,x.targetDate,x.date,x.start,x.when),days:day(first(x.due,x.targetDate,x.date,x.start,x.when))})).filter(x=>x.days===null||x.days>=0)}
export function lifePlanner446(s=store.get()){const rows=[...norm([...(s.plannedPurchases||[]),...(s.purchasePlan?.items||[])],'Nákup'),...norm([...(s.goals?.items||[]),...(s.personalGoals||[])],'Cíl'),...norm([...(s.calendar?.events||[]),...(s.calendarEvents||[])],'Termín'),...norm([...(s.maintenance?.items||[]),...(s.home?.service||[]),...(s.vehicles||[])],'Servis')];const inDays=n=>rows.filter(x=>x.days!==null&&x.days<=n).sort((a,b)=>a.days-b.days),cost=n=>inDays(n).reduce((a,x)=>a+x.amount,0);return{rows,d90:inDays(90),d180:inDays(180),d365:inDays(365),cost90:cost(90),cost180:cost(180),cost365:cost(365)}}
const block=(title,rows)=>`<div class="card"><div class="eyebrow">${h(title)}</div>${rows.slice(0,7).map(x=>`<div class="row"><div><b>${h(x.title)}</b><div class="muted">${h(x.kind)} · ${x.days===null?'bez termínu':`za ${x.days} d`}</div></div>${x.amount?`<b>${money(x.amount)}</b>`:''}</div>`).join('')||'<div class="empty">Nic evidovaného.</div>'}</div>`;
export async function openLifePlanner446(){const t=performance.now(),x=lifePlanner446();window.__KAMIL_LIFE_446_LAST__={ms:Math.round((performance.now()-t)*10)/10,at:Date.now()};const body=`<div class="metric-strip"><div class="metric"><span>3 měsíce</span><b>${money(x.cost90)}</b></div><div class="metric"><span>6 měsíců</span><b>${money(x.cost180)}</b></div><div class="metric"><span>12 měsíců</span><b>${money(x.cost365)}</b></div></div>${block('DALŠÍ 3 MĚSÍCE',x.d90)}${block('DALŠÍCH 6 MĚSÍCŮ',x.d180.filter(v=>!x.d90.includes(v)))}${block('DO 12 MĚSÍCŮ',x.d365.filter(v=>!x.d180.includes(v)))}<div class="decision-note">Life Planner 44.6 · jen uložené osobní plány, bez automatických akcí.</div>`;await modal('Life Planner / 44.6',body,[{label:'Zavřít',value:null,primary:true}])}