import {store} from './state.js';
import {buildDailyCommander248} from './dailyCommander248.js';
import {buildFinanceCommand258} from './financeCommand258.js';
import {buildTicketCommand268} from './ticketCommand268.js';
import {buildAutopilot278} from './managerAutopilot278.js';
import {personalVault640} from './personalVault640.js';
import {xtbBoard,actionLabel} from './live24.js';

const DAY=86400000;
const closed=x=>['DONE','HOTOVO','CLOSED','ARCHIVED','RESOLVED','PAID','SOLD','CANCELLED','CANCELED'].includes(String(x?.status||x?.workflow||'').toUpperCase());
const title=x=>x?.title||x?.name||x?.summary||x?.person||x?.reason||'Položka';
const dateOf=x=>x?.due||x?.dueAt||x?.deadline||x?.followUpAt||x?.nextAt||x?.date||x?.start||x?.when||x?.validUntil||x?.noticeBy||x?.reviewAt||null;
const daysTo=(v,now)=>{const t=Date.parse(v||'');return Number.isFinite(t)?Math.ceil((t-now)/DAY):null};
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const money=v=>`${Math.round(Number(v)||0).toLocaleString('cs-CZ')} Kč`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const workRe=/zak[aá]zk|faktur|dodavat|pks|cpi|zbrojov|prac|stavb|zl\b|ředitel|reditel/i;
const areaFor=x=>{const t=`${title(x)} ${x?.area||''} ${x?.category||''}`;if(workRe.test(t))return'Práce';if(/ticket|vstupenk|viagogo/i.test(t))return'Vstupenky';if(/hypot|bank|platb|peněz|finance|invest|xtb/i.test(t))return'Finance';if(/rodin|dítě|dcera|manžel/i.test(t))return'Rodina';if(/dom|dům|energie|servis|reviz/i.test(t))return'Domov';return'Osobní'};

function unifiedInbox(s,now){const rows=[],push=(x,kind,at=dateOf(x),extra={})=>{if(!x||closed(x))return;const d=daysTo(at,now),score=(d===null?18:d<0?100+Math.min(25,Math.abs(d)*4):d===0?90:d===1?72:d<=3?55:d<=7?35:12)+(kind==='waiting'?12:0);rows.push({id:`${kind}:${x.id||title(x)}`,kind,title:title(x),area:areaFor(x),days:d,score,source:x,...extra})};
 for(const x of s.personalInbox?.items||[])push(x,'inbox',dateOf(x),{triage:'TRIAGE'});
 for(const x of s.inbox||[])push(x,'inbox',dateOf(x),{triage:'TRIAGE'});
 for(const x of s.delegations||[])push(x,'waiting',dateOf(x),{triage:'WAITING'});
 for(const x of s.tasks||[])push(x,'task');
 for(const x of s.personalAdmin?.items||[])push(x,'admin');
 const seen=new Set();return rows.sort((a,b)=>b.score-a.score).filter(x=>{const k=norm(x.title);if(seen.has(k))return false;seen.add(k);return true}).slice(0,30)}
function deadlineGuardian(s,now){const rows=unifiedInbox(s,now).filter(x=>x.days!==null&&x.days<=7).map(x=>({...x,stage:x.days<0?'OVERDUE':x.days===0?'TODAY':x.days<=2?'PREPARE':x.days<=7?'UPCOMING':'LATER',leadDays:x.days}));return{rows,critical:rows.filter(x=>['OVERDUE','TODAY'].includes(x.stage)),prepare:rows.filter(x=>x.stage==='PREPARE')}}
function lifeTimeline(s,now){const rows=[];const add=(x,kind)=>{if(closed(x))return;const at=dateOf(x),d=daysTo(at,now);if(d===null||d<-30||d>90)return;rows.push({kind,title:title(x),area:areaFor(x),at,days:d})};for(const x of s.tasks||[])add(x,'task');for(const x of s.delegations||[])add(x,'waiting');for(const x of s.personalAdmin?.items||[])add(x,'admin');for(const x of s.calendar?.events||[])add(x,'calendar');for(const x of personalVault640(s).records||[])add(x,'document');return rows.sort((a,b)=>a.days-b.days||String(a.title).localeCompare(String(b.title),'cs'))}
function contacts(s,now){const map=new Map(),add=(name,x)=>{const n=String(name||'').trim();if(!n)return;const k=norm(n),row=map.get(k)||{name:n,open:0,overdue:0,items:[],lastAt:null};row.open++;const d=daysTo(dateOf(x),now);if(d!==null&&d<0)row.overdue++;row.items.push(title(x));const at=x.updatedAt||x.createdAt||x.at||null;if(at&&(!row.lastAt||Date.parse(at)>Date.parse(row.lastAt)))row.lastAt=at;map.set(k,row)};for(const x of s.delegations||[])if(!closed(x))add(x.person||x.contact||x.owner||x.assignee,x);for(const x of s.debtBook?.items||[])if(!closed(x))add(x.person||x.contact,x);return [...map.values()].sort((a,b)=>b.overdue-a.overdue||b.open-a.open).slice(0,20)}
function documentIntel(s,now){const v=personalVault640(s);return{coverage:v.coverage,records:v.records.map(x=>({id:x.id,title:x.title,provider:x.provider||null,type:x.recordType,amountMonthly:x.monthlyAmount||null,amountAnnual:x.annualAmount||null,days:daysTo(x.noticeBy||x.validUntil||x.reviewAt,now),status:x.status?.code||'OK',next:x.nextAction})),action:v.action.slice(0,8)}}
function investmentMemory(s){const board=xtbBoard(s);const journal=s.decisionJournal?.items||[];return board.map(({p,d})=>{const ticker=String(p.ticker||p.name||''),past=journal.find(x=>x.domain==='xtb'&&(String(x.entityId||'').toUpperCase()===ticker.toUpperCase()||norm(x.title).includes(norm(ticker))));return{ticker,title:p.name||ticker,action:actionLabel(d.action||'HOLD'),confidence:Number(d.confidence||d.priority||0),reason:d.reason||null,buyRule:d.buyRule||past?.buyRule||null,sellRule:d.sellRule||past?.sellRule||null,thesis:p.investmentThesis||p.thesis||past?.reason||null,thesisRecorded:!!(p.investmentThesis||p.thesis||past?.reason)}})}
function weeklyReview(s,now,autopilot,finance,tickets){const weekStart=now-7*DAY,done=(s.tasks||[]).filter(x=>closed(x)&&Date.parse(x.completedAt||x.updatedAt||x.doneAt||0)>=weekStart),audit=(s.audit||[]).filter(x=>Date.parse(x.at||x.createdAt||0)>=weekStart);return{done:done.length,changes:audit.length,open:autopilot.daily.items.length,waiting:autopilot.daily.waiting.length,finance:{netWorth:finance.netWorth,deployable:finance.deployable,concentration:finance.concentration.length},tickets:{active:tickets.active.length,realized:tickets.realized,blocked:tickets.blocked.length},next:autopilot.top3}}
function notificationBrain(autopilot,deadlines,tickets){const rows=[];for(const x of autopilot.top3||[])if(x.score>=55)rows.push({area:x.area,title:x.title,reason:x.reason,score:x.score});for(const x of deadlines.critical.slice(0,3))rows.push({area:x.area,title:x.title,reason:x.stage,score:x.score});if(tickets.blocked.length)rows.push({area:'Vstupenky',title:`${tickets.blocked.length} BUY blokováno`,reason:'Ověřit pravidla/data',score:45});const seen=new Set();return rows.sort((a,b)=>b.score-a.score).filter(x=>{const k=norm(x.title);if(seen.has(k))return false;seen.add(k);return true}).slice(0,6)}

export function buildLifeOperator298(s=store.get(),now=Date.now()){
 const daily=buildDailyCommander248(s,now),finance=buildFinanceCommand258(s),tickets=buildTicketCommand268(s),autopilot=buildAutopilot278(s,new Date(now)),inbox=unifiedInbox(s,now),deadlines=deadlineGuardian(s,now),timeline=lifeTimeline(s,now),documents=documentIntel(s,now),contactRows=contacts(s,now),investments=investmentMemory(s),weekly=weeklyReview(s,now,autopilot,finance,tickets),notifications=notificationBrain(autopilot,deadlines,tickets);
 const capital={cash:finance.cash,reserve:finance.reserveTarget,deployable:finance.deployable,investments:finance.investments,ticketInvested:tickets.invested,recommendation:finance.deployable<=0?'CHRÁNIT REZERVU':tickets.opportunities.length?'POROVNAT TICKET BUY S XTB':'NOVÝ KAPITÁL DRŽET PRO NEJLEPŠÍ PŘÍLEŽITOST'};
 return{version:298,morning:{top3:autopilot.top3,dailyScore:daily.dailyScore,waiting:daily.waiting.length,deadlines:deadlines.critical.length},priority:{top3:autopilot.top3,all:autopilot.notifications},inbox,triage:{needsTriage:inbox.filter(x=>x.kind==='inbox'),waiting:inbox.filter(x=>x.kind==='waiting')},waiting:{rows:inbox.filter(x=>x.kind==='waiting'),overdue:inbox.filter(x=>x.kind==='waiting'&&x.days!==null&&x.days<0)},deadlines,finance,capital,investments,tickets,timeline,documents,contacts:contactRows,notifications,weekly,searchIndex:[...inbox,...timeline,...documents.records.map(x=>({kind:'document',title:x.title,area:'Dokumenty',source:x}))],guardrails:{autoFinancialExecution:false,autoTicketExecution:false,explicitConfirmationForWrites:true},generatedAt:new Date(now).toISOString()}}

export function answerLifeOperator298(raw,s=store.get(),now=Date.now()){const q=norm(raw),m=buildLifeOperator298(s,now);if(!q)return null;const lines=x=>x.slice(0,8).map(v=>`${v.title}${v.reason?` — ${v.reason}`:v.days!==undefined&&v.days!==null?` — ${v.days<0?`${Math.abs(v.days)} d po termínu`:v.days===0?'dnes':`za ${v.days} d`}`:''}`);if(/co.*(dnes|ted).*(resit|udelat)|co hori|priorit/.test(q))return{title:m.morning.top3.length?'Teď mají největší smysl tyhle věci.':'Nic kritického teď nehoří.',lines:lines(m.morning.top3),note:`Denní skóre ${m.morning.dailyScore}/100 · ${m.morning.deadlines} kritických termínů.`};if(/co.*(stoji|visi)|cekam|follow.?up/.test(q))return{title:m.waiting.overdue.length?`${m.waiting.overdue.length} čekání je po follow-up termínu.`:'Žádné čekání není po follow-up termínu.',lines:lines(m.waiting.rows),note:'Waiting Radar řadí nejdřív prošlé follow-upy.'};if(/voln.*pen|lezic.*pen|kapital|investovat/.test(q))return{title:`Nad rezervu je podle uložených dat ${money(m.capital.deployable)}.`,lines:[`Hotovost ${money(m.capital.cash)}`,`Rezervní minimum ${money(m.capital.reserve)}`,`Investice ${money(m.capital.investments)}`,`Vstupenky ${money(m.capital.ticketInvested)}`,m.capital.recommendation],note:'Neprovádím automatické obchody ani převody.'};if(/vstupenk.*(zlev|prodat|drzet|reprice)|ktere.*vstupenk/.test(q))return{title:m.tickets.active.length?'Ticket portfolio — dnešní review':'Žádné aktivní vstupenky.',lines:m.tickets.active.slice(0,8).map(x=>`${x.name||x.event||'Vstupenka'} — ${x.sellTiming} · ${x.daysTo??'—'} dní`),note:`BUY blokováno: ${m.tickets.blocked.length}.`};if(/tyden|weekly|rekap/.test(q))return{title:`Týden: ${m.weekly.done} dokončeno, ${m.weekly.open} otevřeno.`,lines:[`Čekání ${m.weekly.waiting}`,`Změny ${m.weekly.changes}`,`Net worth ${money(m.weekly.finance.netWorth)}`,`Ticket realizovaný P/L ${money(m.weekly.tickets.realized)}`,...lines(m.weekly.next)],note:'CEO review z uložených dat.'};const hits=m.searchIndex.filter(x=>norm(`${x.title} ${x.area||''}`).includes(q)).slice(0,8);if(hits.length)return{title:`Našel jsem ${hits.length} souvisejících položek.`,lines:hits.map(x=>`${x.area||x.kind}: ${x.title}`),note:'Sjednocené hledání napříč OS.'};return null}

function body(m){const top=m.morning.top3.map((x,i)=>`<div class="life298-row"><strong>${i+1}</strong><span><b>${esc(x.title)}</b><small>${esc(x.area)} · ${esc(x.reason||'')}</small></span></div>`).join('')||'<div class="life298-clear">Nic kritického.</div>';return `<div class="life298"><div class="life298-hero"><small>KAMIL AI OPERATOR</small><h2>Co má teď největší smysl</h2></div>${top}<div class="life298-grid"><span><b>${m.inbox.length}</b><small>unified inbox</small></span><span><b>${m.waiting.overdue.length}</b><small>follow-up po termínu</small></span><span><b>${m.deadlines.critical.length}</b><small>kritické termíny</small></span><span><b>${money(m.capital.deployable)}</b><small>nad rezervu</small></span></div><div class="life298-note">AI Operator prioritizuje a vysvětluje. Peníze, obchody a ticket marketplace nemění bez výslovného potvrzení.</div></div>`}
function ensureCss(){if(document.querySelector('link[data-life298]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./lifeOperator298.css';l.dataset.life298='1';document.head.appendChild(l)}
export function openLifeOperator298(){const m=buildLifeOperator298();window.dispatchEvent(new CustomEvent('kamil:detail-drawer',{detail:{title:'Kamil AI Operator',html:body(m)}}));return m}
export function installLifeOperator298(){ensureCss();window.addEventListener('kamil:open-life-operator',openLifeOperator298);document.addEventListener('keydown',e=>{if(e.altKey&&!e.ctrlKey&&!e.metaKey&&e.key.toLowerCase()==='o'){e.preventDefault();openLifeOperator298()}},true);window.__KAMIL_LIFE_OPERATOR298__={version:298,build:buildLifeOperator298,answer:answerLifeOperator298,open:openLifeOperator298}}
