import {buildManagerOS341} from './managerOS341.js';
const VERSION=481;
const N=v=>Number.isFinite(Number(v))?Number(v):0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isTodayEvent=e=>{const d=e?.detail;return !d||d==='today'||d?.view==='today'};
function ensureCss(){if(document.querySelector('link[data-manager-deadlines481-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./managerDeadlines481.css';l.dataset.managerDeadlines481Css='1';document.head.appendChild(l)}
function dutyRow(x){return{id:`duty:${x.id}`,kind:'DUTY',sourceId:x.id,title:x.label||'Manažerská povinnost',diff:Number.isFinite(Number(x.diff))?Number(x.diff):null,state:x.state||'upcoming',due:x.due||null,detail:x.detail||'',canComplete:!x.isDone}}
function workRow(x){return{id:`work:${x.id||x._title}`,kind:'WORK',sourceId:x.id||null,title:x._title||x.title||x.name||'Pracovní úkol',diff:Number.isFinite(Number(x._diff))?Number(x._diff):null,state:x._state||'open',due:x._due||null,detail:'',canComplete:false}}
function risk(row){if(row.state==='overdue')return Math.min(100,92+Math.min(8,Math.abs(N(row.diff))));if(row.state==='today')return 90;if(row.state==='soon')return Math.max(65,82-N(row.diff)*4);if(row.diff!==null&&row.diff<=7)return 55;if(row.diff===null)return 35;return 20}
export function buildManagerDeadlines481(manager=buildManagerOS341()){
 const rows=[...(manager?.duties||[]).filter(x=>!x.isDone).map(dutyRow),...(manager?.work||[]).map(workRow)].map(x=>({...x,risk:risk(x)})).sort((a,b)=>b.risk-a.risk||(a.diff??9999)-(b.diff??9999));
 const overdue=rows.filter(x=>x.state==='overdue'),today=rows.filter(x=>x.state==='today'),next72=rows.filter(x=>x.diff!==null&&x.diff>=0&&x.diff<=3),missingDeadline=rows.filter(x=>x.kind==='WORK'&&x.diff===null),next=rows[0]||null;
 let recommendation={code:'CLEAR',action:'NIC NEHOŘÍ',title:'Termíny jsou pod kontrolou',reason:'Žádný známý termín není dnes ani po termínu.'};if(overdue.length)recommendation={code:'OVERDUE',action:'ŘEŠIT HNED',title:overdue[0].title,reason:`${overdue.length} položek je po termínu.`};else if(today.length)recommendation={code:'TODAY',action:'DOKONČIT DNES',title:today[0].title,reason:`${today.length} položek má termín dnes.`};else if(next72.length)recommendation={code:'NEXT_72H',action:'PŘIPRAVIT DO 72 H',title:next72[0].title,reason:`${next72.length} položek má termín do tří dnů.`};else if(missingDeadline.length)recommendation={code:'ASSIGN_DATES',action:'DOPLNIT TERMÍNY',title:missingDeadline[0].title,reason:`${missingDeadline.length} pracovních položek nemá termín.`};
 return{version:VERSION,healthy:true,rows,overdue,today,next72,missingDeadline,next,recommendation,generatedAt:new Date().toISOString(),guardrails:{consumesManager341:true,noSecondTaskStore:true,noAutoComplete:true,noInventedDeadlines:true,existingCompletionOwner:true}}
}
function fmtDiff(x){if(x.diff===null)return'bez termínu';if(x.diff<0)return`${Math.abs(x.diff)} d po termínu`;if(x.diff===0)return'dnes';return`za ${x.diff} d`}
function card(m){const r=m.recommendation,rows=m.rows.slice(0,4).map(x=>`<div class="os481-row ${x.state}"><div><small>${x.kind} · RISK ${x.risk}</small><b>${esc(x.title)}</b></div><span>${esc(fmtDiff(x))}</span></div>`).join('')||'<div class="os481-empty">Žádný aktivní manažerský termín.</div>';return `<article class="os467-card os481" data-manager-deadlines481-root><header><div><small>OS481 · MANAGER DEADLINE ENGINE</small><h3>Co nesmí propadnout?</h3></div><b>${m.overdue.length}</b></header><div class="os481-verdict ${String(r.code).toLowerCase()}"><div><small>${esc(r.action)}</small><h4>${esc(r.title)}</h4><p>${esc(r.reason)}</p></div><button type="button" data-os481-open>Otevřít Manager OS</button></div><div class="os481-list">${rows}</div><footer>OS341 zůstává jediný vlastník úkolů a completion stavu · OS481 pouze hlídá riziko termínů</footer></article>`}
function mount(){const grid=document.querySelector('[data-command-center467-root] .os467-grid');if(!grid)return false;const m=buildManagerDeadlines481(),first=!window.__KAMIL_MANAGER_DEADLINES481__;let host=grid.querySelector('[data-manager-deadlines481-root]');const wrap=document.createElement('div');wrap.innerHTML=card(m);const next=wrap.firstElementChild;let changed=false;if(host){if(host.innerHTML!==next.innerHTML||host.className!==next.className){host.replaceWith(next);host=next;changed=true}}else{const anchor=grid.querySelector('[data-investment-battle480-root]')||grid.querySelector('[data-property-decision472-root]')||grid.querySelector('[data-free-cash470-root]');anchor?anchor.after(next):grid.appendChild(next);host=next;changed=true}window.__KAMIL_MANAGER_DEADLINES481__={version:VERSION,healthy:true,mounted:!!host,model:m,refresh:renderSafe,build:buildManagerDeadlines481,at:Date.now()};document.documentElement.dataset.managerDeadlines481='1';if(first||changed)window.dispatchEvent(new CustomEvent('kamil:manager-deadlines481-updated',{detail:{overdue:m.overdue.length,next72:m.next72.length,missingDeadline:m.missingDeadline.length,changed}}));return true}
function renderSafe(){try{return mount()}catch(error){console.error('[managerDeadlines481]',error);window.__KAMIL_MANAGER_DEADLINES481__={version:VERSION,healthy:false,error:String(error?.message||error),refresh:renderSafe,at:Date.now()};return false}}
let timer=0,bound=false;const schedule=(delay=60)=>{clearTimeout(timer);timer=setTimeout(renderSafe,delay)};
export function installManagerDeadlines481(){ensureCss();document.documentElement.dataset.managerDeadlines481='1';if(!bound){bound=true;document.addEventListener('click',e=>{if(e.target.closest?.('[data-os481-open]')){e.preventDefault();window.__KAMIL_MANAGER_OS341__?.open?.()}});for(const event of ['kamil:command-center467-updated','kamil:manager341-updated'])window.addEventListener(event,()=>schedule(30));window.addEventListener('kamil:view-change',e=>{if(isTodayEvent(e))schedule(35)});window.addEventListener('focus',()=>schedule(30))}renderSafe();setTimeout(()=>schedule(20),850);setTimeout(()=>schedule(20),1800)}
