import {store} from './state.js';
import {qs,h,dateTime,toast,modal} from './utils.js';
import {xtbBoard,actionLabel,ticketDecision} from './live24.js';
import {refreshSecEvidence32,sourceIngestStatus32} from './sourceIngest32.js';
import {xtbTuningSummary32} from './xtbTuning32.js';
import {ticketTuningSummary32} from './ticketTuning32.js';

let seq=0,autoSecTried=false;
const n=v=>Number(v||0);
const money=v=>`${Math.round(n(v)).toLocaleString('cs-CZ')} Kč`;
const activeTicket=x=>!['SOLD','PAYOUT WAIT','PAYOUT RECEIVED'].includes(String(x.workflow||'HOLD').toUpperCase());
const safeUrl=v=>{try{const u=new URL(String(v||'').trim());return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
const insertAfterHead=(view,host)=>{const head=view?.querySelector('.view-head');if(head)head.insertAdjacentElement('afterend',host);else view?.prepend(host)};

function xtbCard(state){
 const board=xtbBoard(state),sum=xtbTuningSummary32(board),src=sourceIngestStatus32(state),top=board.filter(x=>['BUY','TRIM','SELL','REVIEW'].includes(String(x.d.action||'').toUpperCase())).slice(0,5);
 return `<div class="card"><div class="card-head"><div><div class="eyebrow">XTB / EDGE 32.4</div><h2>Execution & Filing Radar</h2><p class="muted">Konkrétní krok + oficiální SEC evidence. Žádný obchod se neprovádí automaticky.</p></div><div class="row-actions"><span class="status ${src.error?'bad':src.fresh?'good':'warn'}">SEC ${src.fresh?'FRESH':src.error?'CHYBA':'STALE'}</span><button class="btn" data-sec-refresh>Obnovit SEC</button></div></div><div class="metric-strip"><div class="metric"><span>Akční pozice</span><b>${sum.actionable}</b></div><div class="metric"><span>SEC pokrytí</span><b>${src.covered}/${src.requested}</b></div><div class="metric"><span>Review před obchodem</span><b>${sum.review}</b></div><div class="metric"><span>Blokováno starými daty</span><b>${sum.blocked}</b></div></div>${top.length?`<div>${top.map(({p,d})=>{const e=d.evidence?.latest,ex=d.execution||{};return `<div class="row" style="align-items:flex-start;gap:12px"><div style="min-width:0;flex:1"><b>${h(p.name||p.ticker)} · ${h(p.ticker)}</b><div class="muted">${h(actionLabel(d.action))} · ${h(ex.label||d.when||'')}</div>${ex.blocked?`<div class="bad" style="margin-top:4px">${h(ex.blockReason)}</div>`:''}${d.reviewBeforeTrade?`<div class="warn" style="margin-top:4px">${h(d.reviewReason)}</div>`:''}</div><div style="text-align:right;max-width:42%">${ex.trimQty?`<b>${Number(ex.trimQty).toLocaleString('cs-CZ',{maximumFractionDigits:4})} ks</b><div class="muted">≈ ${money(ex.trimAmount)}</div>`:ex.tranches?`<b>${ex.tranches.partsPct.join(' / ')} %</b><div class="muted">3 tranše</div>`:'<b>bez okamžitého obchodu</b>'}${e?`<div style="margin-top:5px"><a href="${h(e.sourceUrl)}" target="_blank" rel="noopener noreferrer">${h(e.form)} · SEC</a><div class="muted">${h(dateTime(e.asOf))}</div></div>`:''}</div></div>`}).join('')}</div>`:'<div class="empty success-empty">Žádná pozice teď nevyžaduje BUY / TRIM / SELL / REVIEW.</div>'}<div class="decision-note">SEC filing je faktická evidence, ne sentiment ani automatický investiční verdikt. Source confidence znamená autenticitu zdroje, ne pravděpodobnost růstu ceny.${src.fetchedAt?` Poslední fetch ${h(dateTime(src.fetchedAt))}.`:''}</div></div>`;
}

function ticketCard(state){
 const items=(state.ticketBook?.items||[]).filter(activeTicket),sum=ticketTuningSummary32(items,x=>ticketDecision(x,state)),rows=sum.rows.map(r=>({...r,d:ticketDecision(r.x,state)})).sort((a,b)=>n(b.d.priority)-n(a.d.priority)).slice(0,8);
 return `<div class="card"><div class="card-head"><div><div class="eyebrow">VSTUPENKY / EDGE 32.4</div><h2>Pricing & Sell-by Radar</h2><p class="muted">Časová fáze, kontrolní interval a market/floor/list tuning pro každý aktivní balík.</p></div><span class="status ${sum.missingListedPrice?'warn':'good'}">${sum.active} aktivních</span></div><div class="metric-strip"><div class="metric"><span>LISTED bez ceny</span><b>${sum.missingListedPrice}</b></div><div class="metric"><span>Data pod 60 %</span><b>${sum.lowQuality}</b></div><div class="metric"><span>Do 14 dnů</span><b>${sum.urgent}</b></div></div>${rows.map(({x,d,p,q})=>{const target=p.recommendedListPricePerTicket||p.internalTargetPricePerTicket,basis=p.recommendedListPricePerTicket?'market-backed target':'interní target';return `<div class="row" style="align-items:flex-start;gap:12px"><div style="min-width:0;flex:1"><b>${h(x.name)}</b><div class="muted">${h(p.phase.label)} · ${p.phase.days===null?'?':p.phase.days} dní · kontrola po ${p.nextCheckHours} h</div><div style="margin-top:4px"><span class="decision-action ${h(d.tone||'')}">${h(actionLabel(d.action))}</span> <span class="muted">${h(d.when||'')}</span></div>${d.transferWarning?`<div class="warn" style="margin-top:4px">${h(d.transferWarning)}</div>`:''}</div><div style="text-align:right;min-width:155px"><b>${target?money(target)+'/ks':'chybí cenový základ'}</b><div class="muted">${h(basis)}</div><div class="muted">data ${q.score} %</div><button class="btn" style="margin-top:6px" data-ticket-tune="${h(x.id)}">Tuning</button></div></div>`}).join('')||'<div class="empty">Žádné aktivní vstupenky.</div>'}<div class="decision-note">Pokud chybí market cena, zobrazený interní target vychází pouze z nákladu a času do akce — není vydáván za skutečnou tržní cenu. Pro spolehlivý repricing doplň market + zdroj + čas kontroly.</div></div>`;
}

async function editTicket(id){
 const state=store.get(),x=(state.ticketBook?.items||[]).find(v=>v.id===id);if(!x)return;
 const draft={listPrice:n(x.listPrice)||'',marketPrice:n(x.marketPrice)||'',floorPrice:n(x.floorPrice)||'',sellBy:x.sellBy||'',platform:x.platform||'',transferStatus:x.transferStatus||'UNKNOWN',marketSourceUrl:x.marketSourceUrl||''};
 const body=`<div class="form-grid"><label>Skutečná list cena / ks<input id="teList" type="number" min="0" step="1" value="${h(draft.listPrice)}"></label><label>Market cena / ks<input id="teMarket" type="number" min="0" step="1" value="${h(draft.marketPrice)}"></label><label>Floor cena / ks<input id="teFloor" type="number" min="0" step="1" value="${h(draft.floorPrice)}"></label><label>Sell-by<input id="teSellBy" type="date" value="${h(draft.sellBy)}"></label><label>Platforma<input id="tePlatform" value="${h(draft.platform)}" placeholder="Viagogo / Ticketmaster / ..."></label><label>Stav převodu<select id="teTransfer"><option value="UNKNOWN">Neznámý</option><option value="NOT_AVAILABLE">Zatím nelze převést</option><option value="READY">Připraven k převodu</option><option value="TRANSFERRED">Převedeno</option></select></label><label style="grid-column:1/-1">Zdroj market ceny<input id="teSource" type="url" value="${h(draft.marketSourceUrl)}" placeholder="https://..."></label></div><div class="decision-note">Market cenu ukládám jako ruční evidence. URL je volitelná, ale se zdrojem je později možné hlídat stáří a důvěryhodnost přesněji.</div>`;
 const promise=modal(`Tuning · ${x.name}`,body,[{label:'Zrušit',value:null},{label:'Uložit tuning',value:'save',primary:true}]),root=qs('#modalHost .modal:last-child');if(root){qs('#teTransfer',root).value=draft.transferStatus;const bind=(sel,key)=>qs(sel,root)?.addEventListener('input',e=>draft[key]=e.target.value);bind('#teList','listPrice');bind('#teMarket','marketPrice');bind('#teFloor','floorPrice');bind('#teSellBy','sellBy');bind('#tePlatform','platform');bind('#teTransfer','transferStatus');bind('#teSource','marketSourceUrl')}
 const result=await promise;if(result!=='save')return;const source=String(draft.marketSourceUrl||'').trim();if(source&&!safeUrl(source)){toast('Zdroj musí být platná http(s) URL.');return}
 store.mutate(`Tuning vstupenky: ${x.name}`,s=>{const t=(s.ticketBook?.items||[]).find(v=>v.id===id);if(!t)return;t.listPrice=Math.max(0,n(draft.listPrice));t.marketPrice=Math.max(0,n(draft.marketPrice));t.floorPrice=Math.max(0,n(draft.floorPrice));t.sellBy=draft.sellBy||null;t.platform=String(draft.platform||'').trim();t.transferStatus=draft.transferStatus||'UNKNOWN';t.marketSourceUrl=source||null;if(t.marketPrice>0)t.marketCheckedAt=new Date().toISOString()});toast('Tuning vstupenky uložen.');setTimeout(render,0);
}

async function refreshSec(){const b=qs('[data-sec-refresh]');if(b)b.disabled=true;const result=await refreshSecEvidence32(store.get(),{force:true});toast(result.ok?`SEC: ${result.evidence?.length||0} nových filing evidence`:`SEC se nepodařilo načíst: ${result.error||'chyba'}`);setTimeout(render,0)}
function render(){
 const nseq=++seq,moneyView=qs('#moneyView'),ticketsView=qs('#ticketsView'),state=store.get();
 if(moneyView?.querySelector('.view-head')){let host=qs('#marketEdgeXtb32Host',moneyView);if(!host){host=document.createElement('div');host.id='marketEdgeXtb32Host';insertAfterHead(moneyView,host)}host.innerHTML=xtbCard(state);host.querySelector('[data-sec-refresh]')?.addEventListener('click',refreshSec);const src=sourceIngestStatus32(state);if(!autoSecTried&&!src.fresh){autoSecTried=true;refreshSecEvidence32(state).then(()=>{if(nseq===seq)setTimeout(render,0)})}}
 if(ticketsView?.querySelector('.view-head')){let host=qs('#marketEdgeTicket32Host',ticketsView);if(!host){host=document.createElement('div');host.id='marketEdgeTicket32Host';insertAfterHead(ticketsView,host)}host.innerHTML=ticketCard(state);host.querySelectorAll('[data-ticket-tune]').forEach(b=>b.addEventListener('click',()=>editTicket(b.dataset.ticketTune)))}
}
function start(){window.addEventListener('kamil:navigate',()=>setTimeout(render,0));window.addEventListener('kamil:source-ingest',()=>setTimeout(render,0));store.subscribe(()=>setTimeout(render,0));setTimeout(render,250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
