import {store} from './state.js';
import {h,money} from './utils.js';
import {xtbBoard,actionLabel,xtbIntelligenceAge} from './live24.js';
import {loadTicketCloud660} from './ticketCloud660.js';
import {totalInvestmentPortfolio34,monthlyInvestmentPlan34} from './totalPortfolio34.js';
import {moneyRouter32} from './financialDecision32.js';
import {xtbBuyZones,xtbProfitLadder,xtbOpportunityScores,xtbConcentrationGuard,xtbEarningsRisk,xtbWatchlistRanking,xtbCashDeployment,ticketRepricingLadder,ticketNetProfit,ticketMinimumSafePrice,ticketInventoryRisk,ticketBuyOpportunities,ticketEventRanking,unifiedCapitalDecision} from './marketSuite554.js';

const A=v=>Array.isArray(v)?v:[],N=v=>Number(v||0),U=v=>String(v||'').toUpperCase(),clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Math.round(N(v)))),round=v=>Math.round(N(v));
const pct=v=>Number.isFinite(Number(v))?`${Math.round(Number(v))} %`:'—';
const daysTo=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?Math.ceil((t-Date.now())/86400000):null};
const trend=(rows,key)=>{const a=A(rows).filter(x=>N(x?.[key])>0).sort((x,y)=>Date.parse(x.checked_at||0)-Date.parse(y.checked_at||0));if(a.length<2)return null;const first=N(a[0][key]),last=N(a.at(-1)[key]);return first?((last-first)/first*100):null};
const diff=(rows,key)=>{const a=A(rows).filter(x=>Number.isFinite(Number(x?.[key]))).sort((x,y)=>Date.parse(x.checked_at||0)-Date.parse(y.checked_at||0));if(a.length<2)return null;return N(a.at(-1)[key])-N(a[0][key]);};

function ticketDemand(r,s,history=[]){const d=daysTo(r.event_date),velocity=trend(history,'market_price_czk'),supplyDelta=diff(history,'competitor_count'),conf=N(s?.multi_market_confidence);let score=45;if(velocity!==null)score+=Math.max(-20,Math.min(20,velocity));if(supplyDelta!==null)score+=Math.max(-15,Math.min(15,-supplyDelta*3));if(d!==null&&d<=14)score+=10;if(d!==null&&d<=7)score+=8;if(conf>=80)score+=8;if(s?.official_status==='available')score-=8;return{score:clamp(score),velocity,supplyDelta};}
function sellProbability(r,s,demand){const market=N(s?.market_price_czk),ask=N(r.ask_each_czk),d=daysTo(r.event_date),conf=N(s?.multi_market_confidence);let p=35+demand.score*.35;if(market&&ask){const ratio=ask/market;if(ratio<=.98)p+=20;else if(ratio<=1.05)p+=12;else if(ratio>1.15)p-=25;}if(d!==null&&d<=7)p+=10;if(conf<50)p-=12;return clamp(p,5,95);}
function lockScore(r,s,demand){const capital=N(r.buy_total_czk)||N(r.buy_each_czk)*Math.max(1,N(r.qty)),d=daysTo(r.event_date);let score=25;if(capital>=20000)score+=20;else if(capital>=10000)score+=10;if(!N(s?.market_price_czk))score+=25;if(d!==null&&d<=14)score+=20;if(demand.score<45)score+=15;return clamp(score);}
function ticketCurve(r,s,floor){const market=N(s?.market_price_czk),base=Math.max(floor,market||N(r.ask_each_czk)||floor);return [{d:30,f:1.08},{d:14,f:1.03},{d:7,f:.99},{d:3,f:.96},{d:1,f:.92}].map(x=>({days:x.d,price:round(Math.max(floor,base*x.f))}));}
export async function ticketIntelligence100(){const cloud=await loadTicketCloud660();if(!cloud?.ok)return{ok:false,reason:'cloud'};const local=store.get(),legacyNet=new Map(ticketNetProfit(local).map(x=>[x.id,x])),legacyFloor=new Map(ticketMinimumSafePrice(local).map(x=>[x.id,x])),rows=cloud.inventory.filter(x=>['LISTED','NOT_LISTED'].includes(x.market_status)).map(r=>{const s=cloud.latest?.get(r.id)||{},hist=cloud.history?.get(r.id)||[],fee=N(r.fee_rate||r.feeRate||.12)||.12,buy=N(r.buy_each_czk),market=N(s.market_price_czk),floor=buy?round(buy/(1-Math.min(.35,Math.max(0,fee)))):N(legacyFloor.get(r.id)?.safePrice),net=market?round((market*(1-fee)-buy)*Math.max(1,N(r.qty))):N(legacyNet.get(r.id)?.profit),demand=ticketDemand(r,s,hist),prob=sellProbability(r,s,demand),lock=lockScore(r,s,demand),curve=ticketCurve(r,s,floor);return{id:r.id,name:r.event_name,section:r.section||'',qty:Math.max(1,N(r.qty)),days:daysTo(r.event_date),buy,market,ask:N(r.ask_each_czk),fee,floor,net,roi:buy&&market?((market*(1-fee)-buy)/buy*100):null,demand:demand.score,velocity:demand.velocity,supplyDelta:demand.supplyDelta,sellProbability:prob,lockScore:lock,curve,confidence:N(s.multi_market_confidence),recommendation:s.recommendation_code||'HOLD',recommended:N(s.recommended_ask_czk),stubhub:N(s.stubhub_price_czk),viagogo:N(s.viagogo_price_czk)};});const opportunities=ticketBuyOpportunities(local),events=ticketEventRanking(local);return{ok:true,rows,opportunities,events,estimatedFee:true,summary:{capital:rows.reduce((a,x)=>a+x.buy*x.qty,0),expectedNet:rows.reduce((a,x)=>a+x.net,0),highDemand:rows.filter(x=>x.demand>=70).length,locked:rows.filter(x=>x.lockScore>=65).length}};}

function positionRows(s){return xtbBoard(s).map(({p,d})=>({p,d,ticker:p.ticker||p.symbol||p.name||'—',name:p.name||p.ticker||'—',gain:N(p.net_profit_pct),weight:N(p.weightPct),currency:U(p.accountCurrency||p.currency||''),value:N(p.value),price:N(p.marketPrice||p.currentPrice||p.price),avg:N(p.avgPrice||p.openPrice)}));}
function fxAdvice(p){if(!p.currency)return'NEZNÁMÁ MĚNA';if(p.currency==='USD')return'Pro USD pozici preferovat USD hotovost/účet; neprovádět zbytečný CZK→USD převod při každém nákupu.';if(p.currency==='EUR')return'Pro EUR pozici preferovat EUR hotovost/účet.';if(p.currency==='CZK')return'Bez FX konverze.';return`Hlídát konverzi ${p.currency}; chybí explicitní FX routing.`;}
function scenarios(s){const p=totalInvestmentPortfolio34(s),base=N(p.total);return[{name:'Akcie −20 %',impact:round(base*-.20)},{name:'USD −10 %',impact:round(A(p.rows).filter(x=>U(x.currency)==='USD').reduce((a,x)=>a+N(x.baseValue),0)*-.10)},{name:'Největší pozice −30 %',impact:round((A(p.rows).sort((a,b)=>N(b.baseValue)-N(a.baseValue))[0]?.baseValue||0)*-.30)}];}
export function xtbIntelligence100(s=store.get(),newCash=null){const board=positionRows(s),opps=xtbOpportunityScores(s),zones=new Map(xtbBuyZones(s).map(x=>[U(x.ticker),x])),ladders=new Map(xtbProfitLadder(s).map(x=>[U(x.ticker),x])),conc=new Map(xtbConcentrationGuard(s).map(x=>[U(x.ticker),x])),earn=new Map(xtbEarningsRisk(s).map(x=>[U(x.ticker),x])),positions=board.map(x=>{const o=opps.find(v=>U(v.ticker)===U(x.ticker)),z=zones.get(U(x.ticker)),l=ladders.get(U(x.ticker)),c=conc.get(U(x.ticker)),e=earn.get(U(x.ticker));let action=actionLabel(x.d.action),profitProtect='DRŽET';if(x.gain>=40)profitProtect='VYBRAT ČÁST ZISKU';else if(x.gain>=25)profitProtect='PŘIPRAVIT ČÁSTEČNÝ PRODEJ';return{...x,action,confidence:N(x.d.confidence)||N(x.d.priority),opportunity:N(o?.score),reason:x.d.reason||o?.reason||'',buyGood:z?.good,buyIdeal:z?.ideal,profitProtect,nextLadder:l?.next||null,concentration:c?.status||'NEZNÁMÉ',earnings:e?.risk||'NEZNÁMÉ',earningsDate:e?.date||null,fx:fxAdvice(x)};});const amount=newCash===null?N(s.financePlan?.plannedInvestment):N(newCash),deployment=monthlyInvestmentPlan34(s,amount),simpleDeployment=xtbCashDeployment(s,amount),router=moneyRouter32(s),age=xtbIntelligenceAge(s);return{positions,watchlist:xtbWatchlistRanking(s),deployment:deployment?.ok?deployment:simpleDeployment,router,scenarios:scenarios(s),age,earningsFeedMissing:positions.some(x=>!x.earningsDate),portfolio:totalInvestmentPortfolio34(s)};}

export function capitalDecision100(s=store.get(),amount=N(s.financePlan?.plannedInvestment)||25000,tickets=null){const legacy=unifiedCapitalDecision(s,amount),xtb=xtbIntelligence100(s,amount),bestXtb=Math.max(0,...xtb.positions.map(x=>x.opportunity)),bestTicket=tickets?.opportunities?.[0]?.score||0,router=xtb.router;const choices=[];if(router.xtbBudget>0)choices.push({key:'XTB',score:bestXtb||50,amount:Math.min(amount,router.xtbBudget),reason:xtb.positions.find(x=>x.opportunity===bestXtb)?.reason||router.reason,liquidity:'vysoká'});if(bestTicket)choices.push({key:'VSTUPENKY',score:N(bestTicket),amount,reason:tickets.opportunities[0]?.maxBuyLabel||'Ticket opportunity podle uložených dat',liquidity:'nízká až střední'});choices.push({key:'HOTOVOST',score:router.xtbBudget<=0?95:40,amount,reason:router.xtbBudget<=0?router.reason:'Rezerva / čekání na lepší příležitost',liquidity:'okamžitá'});choices.sort((a,b)=>b.score-a.score);return{amount,choices,legacy,top:choices[0],note:'Skóre porovnává uložené/odvozené signály. Nejde o automatický obchod ani garantovaný výnos.'};}

const metric=(a,b)=>`<div class="metric"><span>${h(a)}</span><b>${b}</b></div>`;
export async function appendTicketIntelligence100(host=document.querySelector('#ticketIntelView')){if(!host||host.querySelector('[data-ticket100]'))return;const x=await ticketIntelligence100();if(!x.ok)return;const top=[...x.rows].sort((a,b)=>b.lockScore-a.lockScore).slice(0,5),sec=document.createElement('section');sec.dataset.ticket100='1';sec.className='card';sec.style.margin='18px 0';sec.innerHTML=`<div class="eyebrow">TICKETS 100 · INTELLIGENCE</div><h2>Net profit, demand, supply a pravděpodobnost prodeje</h2><p class="muted">Poplatek je tam, kde není uložen přesně, počítán orientačně 12 %. OS ho označuje jako odhad.</p><div class="metric-strip">${metric('Kapitál',money(x.summary.capital))}${metric('Odhad net P/L',money(x.summary.expectedNet))}${metric('Demand ≥70',x.summary.highDemand)}${metric('Capital Lock ≥65',x.summary.locked)}</div>${top.map(v=>`<div class="row ux64-row"><div><b>${h(v.name)}</b><div class="muted">${h(v.section)} · demand ${v.demand}/100 · sell probability ${v.sellProbability}% · lock ${v.lockScore}/100</div><div class="muted">Price velocity ${v.velocity===null?'—':pct(v.velocity)} · supply Δ ${v.supplyDelta===null?'—':Math.round(v.supplyDelta)}</div></div><div><b>${v.market?money(v.market):'bez market ceny'}</b><div class="muted">break-even ${v.floor?money(v.floor):'—'} · net ${money(v.net)}</div></div></div>`).join('')}<div class="decision-note"><b>New Event Hunter / Deal Score:</b> ${x.opportunities.length?`${h(x.opportunities[0].name)} · score ${x.opportunities[0].score}/100 · ${h(x.opportunities[0].maxBuyLabel||'')}`:'čeká na kandidáty v ticket opportunities/watchlistu; bez živého discovery feedu nic nevymýšlí.'}</div>`;const anchor=host.querySelector('[data-ticket-priority87]');anchor?.after(sec);if(!anchor)host.prepend(sec);window.__KAMIL_TICKETS100__=x;}

export function appendXtbIntelligence100(host=document.querySelector('#moneyView')){if(!host||host.querySelector('[data-xtb100]'))return;const s=store.get(),x=xtbIntelligence100(s),sec=document.createElement('section');sec.dataset.xtb100='1';sec.className='card money-section';sec.dataset.moneyGroup='wealth';const top=x.positions.slice().sort((a,b)=>b.opportunity-a.opportunity).slice(0,6),scenario=x.scenarios.map(v=>`${h(v.name)}: ${money(v.impact)}`).join(' · ');sec.innerHTML=`<div class="eyebrow">XTB 100 · POSITION INTELLIGENCE</div><h2>Co přikoupit, držet, redukovat nebo prodat</h2><div class="metric-strip">${metric('Pozic',x.positions.length)}${metric('Data',h(x.age?.label||'bez živé intelligence'))}${metric('Cash routing',h(x.router.status))}${metric('Earnings feed',x.earningsFeedMissing?'NEÚPLNÝ':'OK')}</div>${top.map(v=>`<div class="row ux64-row"><div><b>${h(v.ticker)} · ${h(v.action)}</b><div class="muted">${h(v.reason)} · opportunity ${v.opportunity}/100 · confidence ${v.confidence}/100</div><div class="muted">Concentration: ${h(v.concentration)} · Earnings: ${h(v.earnings)} · Profit protection: ${h(v.profitProtect)}</div></div><div><b>${v.gain>=0?'+':''}${Math.round(v.gain)} %</b><div class="muted">dip: ${v.buyGood??'—'} / ideal ${v.buyIdeal??'—'}</div></div></div>`).join('')||'<div class="empty">XTB import zatím nemá pozice.</div>'}<div class="decision-note"><b>Scenario simulator:</b> ${scenario||'chybí kompletní portfolio/FX data'}</div><div class="decision-note"><b>FX optimizer:</b> ${top[0]?h(top[0].fx):'čeká na pozice'}</div>`;host.appendChild(sec);window.__KAMIL_XTB100__=x;}

export async function appendCapitalBrain100(host=document.querySelector('#moneyView')){if(!host||host.querySelector('[data-capital100]'))return;let tickets=null;try{tickets=await ticketIntelligence100()}catch{}const s=store.get(),amount=N(s.financePlan?.plannedInvestment)||25000,x=capitalDecision100(s,amount,tickets),sec=document.createElement('section');sec.dataset.capital100='1';sec.className='card money-section';sec.dataset.moneyGroup='wealth';sec.innerHTML=`<div class="eyebrow">CAPITAL ALLOCATION BRAIN 100</div><h2>Kam má jít další koruna?</h2><p class="muted">Porovnává XTB, ticket opportunity a hotovost podle dostupných signálů, rizika a likvidity.</p>${x.choices.map((v,i)=>`<div class="row ux64-row"><div><b>#${i+1} ${h(v.key)}</b><div class="muted">${h(v.reason)} · likvidita ${h(v.liquidity)}</div></div><div><b>${v.score}/100</b><div class="muted">${money(v.amount)}</div></div></div>`).join('')}<div class="decision-note">${h(x.note)}</div>`;host.appendChild(sec);window.__KAMIL_CAPITAL100__=x;}
