const VERSION=483;
const N=v=>Number.isFinite(Number(v))?Number(v):0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`;
const isTodayEvent=e=>{const d=e?.detail;return !d||d==='today'||d?.view==='today'};
function ensureCss(){if(document.querySelector('link[data-morning-director483-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./morningDirector483.css';l.dataset.morningDirector483Css='1';document.head.appendChild(l)}
function liveSources(){return{deadlines:window.__KAMIL_MANAGER_DEADLINES481__?.model||null,execution:window.__KAMIL_EXECUTION_STATE364__?.model||null,freeCash:window.__KAMIL_FREE_CASH470__?.model||null,investment:window.__KAMIL_INVESTMENT_BATTLE480__?.model||null,command:window.__KAMIL_COMMAND_CENTER467__?.model||null}}
function deadlineSection(m){if(!m)return{key:'DEADLINE',label:'Termíny',status:'UNKNOWN',value:'—',detail:'Deadline engine není dostupný.'};const overdue=m.overdue?.length||0,today=m.today?.length||0,next72=m.next72?.length||0,missing=m.missingDeadline?.length||0,status=overdue?'RED':today||next72?'AMBER':missing?'INFO':'OK',value=overdue?`${overdue} po termínu`:today?`${today} dnes`:next72?`${next72} do 72 h`:missing?`${missing} bez termínu`:'čisté';return{key:'DEADLINE',label:'Termíny',status,value,detail:m.recommendation?.reason||'Termíny jsou pod kontrolou.'}}
function followupSection(m){if(!m)return{key:'FOLLOW_UP',label:'Follow-up',status:'UNKNOWN',value:'—',detail:'Execution engine není dostupný.'};const due=m.dueFollowups?.length||0,waiting=N(m.counts?.WAITING),status=due?'RED':waiting?'AMBER':'OK',value=due?`${due} k urgenci`:waiting?`${waiting} čekám`:'čisté';return{key:'FOLLOW_UP',label:'Follow-up',status,value,detail:due?'Některý follow-up je připravený k akci.':waiting?'Čekající věci zatím nejsou po follow-up termínu.':'Na nikoho evidovaně nečekáš.'}}
function cashSection(m){if(!m||m.healthy!==true||m.sourceHealthy!==true)return{key:'CASH',label:'Free cash',status:'UNKNOWN',value:'—',detail:'Bez zdravého cash-flow zdroje neukazuju falešně volný kapitál.'};const cap=Math.max(0,N(m.conservativeCap));return{key:'CASH',label:'Free cash',status:cap>0?'OK':'HOLD',value:money(cap),detail:cap>0?'Bezpečný konzervativní limit nad rezervou.':'Teď není bezpečně volný kapitál nad rezervou.'}}
function capitalSection(m){if(!m)return{key:'CAPITAL',label:'Kapitál',status:'UNKNOWN',value:'—',detail:'Investment Battle není dostupný.'};const x=m.actionableWinner||m.recommendation||null;if(!x)return{key:'CAPITAL',label:'Kapitál',status:'UNKNOWN',value:'—',detail:'Chybí akční investiční verdikt.'};const cash=String(x.domain||'').toUpperCase()==='CASH';return{key:'CAPITAL',label:'Kapitál',status:cash?'HOLD':'OPPORTUNITY',value:cash?'držet cash':String(x.domain||'—'),detail:x.reason||x.action||'Bez detailu.'}}
function missingSources(s){return[['deadlines','OS481'],['execution','OS364'],['freeCash','OS470'],['investment','OS480'],['command','OS467']].filter(([key])=>!s?.[key]).map(([,label])=>label)}
function chooseFirst(s,missing){const d=s.deadlines,e=s.execution,i=s.investment,c=s.command;if(d?.overdue?.length)return{code:'DEADLINE',domain:'WORK',action:'ŘEŠIT HNED',title:d.overdue[0].title||d.recommendation?.title||'Manažerský termín',reason:d.recommendation?.reason||'Položka je po termínu.'};if(d?.today?.length)return{code:'DEADLINE',domain:'WORK',action:'DOKONČIT DNES',title:d.today[0].title||d.recommendation?.title||'Manažerský termín',reason:d.recommendation?.reason||'Položka má termín dnes.'};if(e?.dueFollowups?.length){const x=e.dueFollowups[0];return{code:'FOLLOW_UP',domain:'PEOPLE',action:'URGUJ / FOLLOW-UP',title:x.title||'Follow-up',reason:x.waitingFor?`Čekáš na ${x.waitingFor}.`:'Follow-up je po termínu.'}}if(d?.next72?.length)return{code:'PREPARE_DEADLINE',domain:'WORK',action:'PŘIPRAVIT DO 72 H',title:d.next72[0].title||d.recommendation?.title||'Blížící se termín',reason:d.recommendation?.reason||'Termín je do tří dnů.'};const inv=i?.actionableWinner||i?.recommendation;if(inv&&String(inv.domain||'').toUpperCase()!=='CASH'&&inv.actionable!==false)return{code:'CAPITAL',domain:'MONEY',action:inv.action||'PROVĚŘIT INVESTICI',title:inv.name||inv.domain||'Kapitálová příležitost',reason:inv.reason||'Existuje bezpečně akční kapitálová příležitost.'};if(c?.best)return{code:'FOCUS',domain:'FOCUS',action:'ZAČÍT PRVNÍ PRIORITOU',title:c.best.title||'Top priorita',reason:c.best.why||c.best.reason||'Nejlepší další krok z Command Centeru.'};if(missing.length)return{code:'DATA_CHECK',domain:'SYSTEM',action:'DOPLNIT / OBNOVIT DATA',title:'Briefing není kompletní',reason:`Chybí zdroje: ${missing.join(', ')}.`};return{code:'CLEAR',domain:'CALM',action:'NIC NEHOŘÍ',title:'Začni plánovanou prací',reason:'Deadline, follow-up i kapitálové enginy nemají silnější okamžitou akci.'}}
export function buildMorningDirector483(sources=liveSources()){
 const missing=missingSources(sources),sections=[deadlineSection(sources.deadlines),followupSection(sources.execution),cashSection(sources.freeCash),capitalSection(sources.investment)],firstBlock=chooseFirst(sources,missing);
 return{version:VERSION,healthy:true,firstBlock,sections,missingSources:missing,complete:missing.length===0,generatedAt:new Date().toISOString(),guardrails:{aggregateOnly:true,noNewTaskStore:true,noInventedDeadlines:true,noAutoExecute:true,noFalseClearWhenSourceMissing:true,sourceOwners:['OS481','OS364','OS470','OS480','OS467']}}
}
function card(m){const f=m.firstBlock,sections=m.sections.map(x=>`<div class="os483-cell ${String(x.status).toLowerCase()}"><small>${esc(x.label)}</small><b>${esc(x.value)}</b><span>${esc(x.detail)}</span></div>`).join('');return `<section class="os483-brief" data-morning-director483-root><header><div><small>OS483 · MORNING DIRECTOR BRIEFING</small><h2>První blok dne</h2></div><span>${new Date().toLocaleTimeString('cs-CZ',{hour:'2-digit',minute:'2-digit'})}</span></header><div class="os483-first ${String(f.code).toLowerCase()}"><div><small>${esc(f.action)} · ${esc(f.domain)}</small><h3>${esc(f.title)}</h3><p>${esc(f.reason)}</p></div>${m.missingSources.length?`<b>${m.missingSources.length} zdrojů chybí</b>`:'<b>briefing kompletní</b>'}</div><div class="os483-strip">${sections}</div><footer>Jedna agregovaná ranní vrstva · žádný nový task store · žádná automatická akce</footer></section>`}
function mount(){const root=document.querySelector('[data-command-center467-root]');if(!root)return false;const m=buildMorningDirector483(),first=!window.__KAMIL_MORNING_DIRECTOR483__;let host=root.querySelector('[data-morning-director483-root]');const wrap=document.createElement('div');wrap.innerHTML=card(m);const next=wrap.firstElementChild;let changed=false;if(host){if(host.innerHTML!==next.innerHTML||host.className!==next.className){host.replaceWith(next);host=next;changed=true}}else{const top=root.querySelector('[data-os467-core-top]');top?top.after(next):root.prepend(next);host=next;changed=true}window.__KAMIL_MORNING_DIRECTOR483__={version:VERSION,healthy:true,mounted:!!host,model:m,refresh:renderSafe,build:buildMorningDirector483,at:Date.now()};document.documentElement.dataset.morningDirector483='1';if(first||changed)window.dispatchEvent(new CustomEvent('kamil:morning-director483-updated',{detail:{code:m.firstBlock.code,complete:m.complete,changed}}));return true}
function renderSafe(){try{return mount()}catch(error){console.error('[morningDirector483]',error);window.__KAMIL_MORNING_DIRECTOR483__={version:VERSION,healthy:false,error:String(error?.message||error),refresh:renderSafe,at:Date.now()};return false}}
let timer=0,bound=false;const schedule=(delay=55)=>{clearTimeout(timer);timer=setTimeout(renderSafe,delay)};
export function installMorningDirector483(){ensureCss();document.documentElement.dataset.morningDirector483='1';if(!bound){bound=true;for(const event of ['kamil:command-center467-updated','kamil:manager-deadlines481-updated','kamil:execution-state364-updated','kamil:free-cash470-updated','kamil:investment-battle480-updated'])window.addEventListener(event,()=>schedule(25));window.addEventListener('kamil:view-change',e=>{if(isTodayEvent(e))schedule(30)});window.addEventListener('focus',()=>schedule(25))}renderSafe();setTimeout(()=>schedule(20),900);setTimeout(()=>schedule(20),1900)}
