import {store} from './state.js';
import {trueNetWorth,upsertNetWorthSnapshot} from './netWorth29.js';
import {h,qs,qsa,modal,toast,uid} from './utils.js';

const id='trueNetWorth29Host';
const KINDS={PROPERTY:'Nemovitost',VEHICLE:'Auto / vozidlo',BANK:'Další hotovost / účet',INVESTMENT:'Jiná investice',BUSINESS:'Podíl / podnikání',MORTGAGE:'Hypotéka',LOAN:'Úvěr',CREDIT:'Kreditka / kontokorent',OTHER:'Ostatní'};
const money=(v,c)=>`${Number(v||0).toLocaleString('cs-CZ',{maximumFractionDigits:0})} ${h(c)}`;
const tone=v=>Number(v)<0?'bad':Number(v)>0?'good':'';
const kindLabel=k=>KINDS[k]||String(k||'Ostatní');

async function editManual(item=null,forcedSide='ASSET'){
 const x=item||{},side=String(x.side||forcedSide).toUpperCase(),opts=Object.entries(KINDS).map(([k,v])=>`<option value="${k}" ${k===(x.kind||'OTHER')?'selected':''}>${h(v)}</option>`).join('');
 const body=`<div class="form-grid capture-form"><label class="wide-field">Název<input id="nwTitle" autofocus value="${h(x.title||'')}" placeholder="Např. Dům / Hypotéka / auto"></label><label>Strana<select id="nwSide"><option value="ASSET" ${side==='ASSET'?'selected':''}>Majetek</option><option value="LIABILITY" ${side==='LIABILITY'?'selected':''}>Závazek</option></select></label><label>Typ<select id="nwKind">${opts}</select></label><label>Aktuální hodnota / zůstatek<input id="nwValue" type="number" min="0" step="0.01" value="${x.value??''}"></label><label>Měna<select id="nwCurrency"><option value="CZK" ${(x.currency||'CZK')==='CZK'?'selected':''}>CZK</option><option value="EUR" ${x.currency==='EUR'?'selected':''}>EUR</option><option value="USD" ${x.currency==='USD'?'selected':''}>USD</option></select></label><label>Likvidita<select id="nwLiquid"><option value="false" ${x.liquid!==true?'selected':''}>Nelze hned použít</option><option value="true" ${x.liquid===true?'selected':''}>Likvidní</option></select></label><label class="wide-field">Poznámka<textarea id="nwNotes" rows="3">${h(x.notes||'')}</textarea></label></div><p class="muted">Zadej jen hodnotu, kterou opravdu znáš. Nemovitost ani auto Kamil OS sám neodhaduje. U závazku zadávej aktuální nesplacený zůstatek.</p>`;
 const ok=await modal(item?'Upravit položku čistého jmění':'Přidat do čistého jmění',body,[{label:'Zrušit',value:false},{label:'Uložit',value:true,primary:true}]);if(!ok)return;
 const title=qs('#nwTitle')?.value?.trim(),value=Number(qs('#nwValue')?.value);if(!title)return toast('Doplň název');if(!Number.isFinite(value)||value<=0)return toast('Doplň platnou kladnou hodnotu');const now=new Date().toISOString(),next={...x,id:x.id||uid('networth'),title,side:qs('#nwSide').value,kind:qs('#nwKind').value,value,currency:qs('#nwCurrency').value,liquid:qs('#nwLiquid').value==='true',notes:qs('#nwNotes').value.trim(),status:'ACTIVE',updatedAt:now,createdAt:x.createdAt||now};
 store.mutate(`${item?'Upravena':'Přidána'} položka čistého jmění: ${title}`,s=>{s.netWorthBook=s.netWorthBook||{items:[],history:[]};s.netWorthBook.items=Array.isArray(s.netWorthBook.items)?s.netWorthBook.items:[];const i=s.netWorthBook.items.findIndex(y=>y.id===next.id);if(i>=0)s.netWorthBook.items[i]=next;else s.netWorthBook.items.unshift(next)});toast('Čisté jmění aktualizováno');
}
function archiveManual(id){store.mutate('Archivována položka čistého jmění',s=>{const x=s.netWorthBook?.items?.find(y=>y.id===id);if(x){x.status='ARCHIVED';x.updatedAt=new Date().toISOString()}});toast('Položka archivována')}
function snapshot(){store.mutate('Uložen snapshot čistého jmění',s=>upsertNetWorthSnapshot(s,new Date()));toast('Dnešní stav čistého jmění uložen')}
function deltaRows(map,label){if(!map)return `<div class="empty">${h(label)} zatím nelze spočítat — potřebuješ starší snapshot.</div>`;return Object.values(map).map(x=>`<div class="row"><span>${h(x.currency)}</span><b class="${tone(x.delta)}">${x.delta>=0?'+':''}${money(x.delta,x.currency)}${x.pct===null?'':` · ${x.pct>=0?'+':''}${Number(x.pct).toFixed(1)} %`}</b></div>`).join('')}
function currencyBlock(v){return `<div class="card"><div class="card-head"><div><div class="eyebrow">${h(v.currency)}</div><h3>${money(v.net,v.currency)}</h3></div><span class="status ${tone(v.net)}">NET</span></div><div class="row"><span>Majetek</span><b>${money(v.assets,v.currency)}</b></div><div class="row"><span>Závazky</span><b>${money(v.liabilities,v.currency)}</b></div><div class="row"><span>Likvidní majetek</span><b>${money(v.liquidAssets,v.currency)}</b></div><div class="row"><span>Nelikvidní / čekající</span><b>${money(v.illiquidAssets,v.currency)}</b></div></div>`}
function sourceRows(r){const rows=Object.values(r.byCurrency).flatMap(v=>v.sources).sort((a,b)=>b.value-a.value).slice(0,12);return rows.map(x=>`<div class="row"><div><b>${h(x.label)}</b><div class="muted">${h(kindLabel(x.kind))} · ${x.manual?'ručně':'automaticky'} · ${h(x.basis)}</div></div><b class="${x.side==='LIABILITY'?'bad':''}">${x.side==='LIABILITY'?'−':''}${money(x.value,x.currency)}</b></div>`).join('')||'<div class="empty">Zatím nejsou hodnoty, ze kterých by šlo čisté jmění sestavit.</div>'}
function manualRows(s){const items=(s.netWorthBook?.items||[]).filter(x=>String(x.status||'ACTIVE').toUpperCase()!=='ARCHIVED');return items.map(x=>`<div class="row"><div><b>${h(x.title)}</b><div class="muted">${x.side==='LIABILITY'?'Závazek':'Majetek'} · ${h(kindLabel(x.kind))}${x.updatedAt?` · aktualizace ${h(new Date(x.updatedAt).toLocaleDateString('cs-CZ'))}`:''}</div></div><div class="row-actions"><b class="${x.side==='LIABILITY'?'bad':''}">${x.side==='LIABILITY'?'−':''}${money(x.value,x.currency)}</b><button class="btn" data-nw-edit="${h(x.id)}">Upravit</button><button class="btn" data-nw-archive="${h(x.id)}">Archivovat</button></div></div>`).join('')||'<div class="empty">Žádný ručně oceněný majetek ani závazek. Automatické zdroje se počítají samy.</div>'}
function historyRows(r){return r.history.slice(0,6).map(x=>`<div class="row"><span>${h(new Date(x.at).toLocaleDateString('cs-CZ'))}</span><b>${Object.entries(x.byCurrency||{}).map(([c,v])=>`${h(c)} ${Number(v.net??v).toLocaleString('cs-CZ',{maximumFractionDigits:0})}`).join(' · ')||'—'}</b></div>`).join('')||'<div class="empty">Historie je prázdná. Snapshot se uloží jen po tvém potvrzení.</div>'}
function render(){
 const view=qs('#moneyView');if(!view)return;qs(`#${id}`,view)?.remove();const s=store.get(),r=trueNetWorth(s,new Date()),host=document.createElement('div');host.id=id;
 const headline=r.base.complete&&r.base.net!==null?`${money(r.base.net,r.baseCurrency)}`:r.currencies.length===1?money(r.byCurrency[r.currencies[0]]?.net,r.currencies[0]):'Více měn';
 const baseNote=r.base.complete&&r.currencies.length>1?`Přepočet do ${h(r.baseCurrency)} používá jen skutečně dostupné FX kurzy.`:r.base.missingCurrencies.length?`Společný ${h(r.baseCurrency)} součet je skrytý: chybí FX pro ${h(r.base.missingCurrencies.join(', '))}.`:'Bez měnového přepočtu.';
 const gaps=r.gaps.map(x=>`<div class="audit-risk"><b class="warn">PROVĚŘIT</b><span>${h(x)}</span></div>`).join('')||'<div class="empty success-empty">Bez zásadní datové mezery v aktuálním ledgeru.</div>';
 host.innerHTML=`<div class="card"><div class="card-head"><div><div class="eyebrow">TRUE NET WORTH / 29.6</div><h2>Čisté jmění</h2><p class="muted">Majetek mínus skutečné závazky. Bez odhadů nemovitostí, auta nebo FX kurzů, které nejsou v datech.</p></div><div class="view-head-stat"><b class="${r.base.complete?tone(r.base.net):''}">${h(headline)}</b><span>${h(baseNote)}</span></div></div><div class="row-actions"><button class="btn primary" id="nwAddAsset">＋ Majetek</button><button class="btn" id="nwAddLiability">＋ Závazek</button><button class="btn" id="nwSnapshot">Uložit dnešní stav</button></div><div class="grid two" style="margin-top:12px">${Object.values(r.byCurrency).map(currencyBlock).join('')||'<div class="empty">Zatím bez oceněných položek.</div>'}</div><div class="decision-note">${h(r.note)}</div></div>
 <div class="grid two" style="margin-top:12px"><div class="card"><div class="card-head"><div><div class="eyebrow">ZDROJE</div><h3>Z čeho se číslo skládá</h3></div></div>${sourceRows(r)}</div><div class="card"><div class="card-head"><div><div class="eyebrow">KVALITA DAT</div><h3>Co může čisté jmění zkreslit</h3></div></div>${gaps}</div></div>
 <div class="grid two" style="margin-top:12px"><div class="card"><div class="card-head"><div><div class="eyebrow">RUČNÍ LEDGER</div><h3>Majetek a závazky mimo automatické zdroje</h3></div></div>${manualRows(s)}</div><div class="card"><div class="card-head"><div><div class="eyebrow">HISTORIE</div><h3>Vývoj čistého jmění</h3></div><span class="status">${r.coverage.historySnapshots} snapshotů</span></div><h3>Od posledního staršího snapshotu</h3>${deltaRows(r.comparisons.deltaFromPrior,'Změna')}<h3 style="margin-top:14px">Snapshoty</h3>${historyRows(r)}</div></div>`;
 const anchor=qs('#personalMoney26Host',view)||view.querySelector('.view-head');if(anchor)anchor.insertAdjacentElement('afterend',host);else view.prepend(host);
 qs('#nwAddAsset',host)?.addEventListener('click',()=>editManual(null,'ASSET'));qs('#nwAddLiability',host)?.addEventListener('click',()=>editManual(null,'LIABILITY'));qs('#nwSnapshot',host)?.addEventListener('click',snapshot);qsa('[data-nw-edit]',host).forEach(b=>b.onclick=()=>editManual((store.get().netWorthBook?.items||[]).find(x=>x.id===b.dataset.nwEdit)));qsa('[data-nw-archive]',host).forEach(b=>b.onclick=()=>archiveManual(b.dataset.nwArchive));
}
const start=()=>{const view=qs('#moneyView');if(!view)return;new MutationObserver(()=>{if(!qs(`#${id}`,view))queueMicrotask(render)}).observe(view,{childList:true,subtree:false});store.subscribe(()=>{if(qs('#view-money')?.classList.contains('on'))queueMicrotask(render)});render()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
