import {store} from './state.js';
import {modal,h,toast,uid} from './utils.js';
import {personalDailyAssistant650,personalSearch650,personalHomeTimeline650} from './personalAssistant650.js';
import {personalSettings647,openPersonalDataHealth647} from './personalSettings647.js';
import {unifiedCapitalState160} from './unifiedCapital160.js';
import {buildPropertyDecision472} from './propertyDecision472.js';

const VERSION='717.0.0';
const A=v=>Array.isArray(v)?v:[];
const N=v=>Number.isFinite(Number(v))?Number(v):0;
const open=x=>!['DONE','CLOSED','ARCHIVED','RESOLVED','PAID','CANCELLED','CANCELED'].includes(String(x?.status||x?.workflow||'').toUpperCase());
const dateOf=x=>x?.due||x?.dueAt||x?.deadline||x?.followUpAt||x?.nextAt||x?.date||x?.start||x?.when||null;
const day=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?Math.floor((t-Date.now())/86400000):null};
const fmt=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?new Date(t).toLocaleDateString('cs-CZ'):'—'};
const money=v=>`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`;
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const nav=v=>window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:v}));

function auditToday(s){const d=new Date();d.setHours(0,0,0,0);return A(s.audit).filter(x=>Date.parse(x.at||x.createdAt||'')>=d.getTime())}
function deadlines(s){const rows=[];for(const x of [...A(s.tasks),...A(s.personalAdmin?.items),...A(s.calendar?.events)]){if(!open(x))continue;const at=dateOf(x),d=day(at);if(d===null||d>60)continue;rows.push({title:x.title||x.name||x.summary||'Termín',at,days:d,area:x.area||x.category||x.sourceKind||'OS'})}return rows.sort((a,b)=>a.days-b.days).slice(0,20)}
function familyTimeline(s){return deadlines(s).filter(x=>/rodin|dite|dcera|manzel|lekar|doktor|plav|skol/i.test(norm(`${x.title} ${x.area}`))).slice(0,10)}
function homeTimeline(s){return personalHomeTimeline650(s).slice(0,10).map(x=>({title:x.title,at:x.date,days:x.days,area:'Domov'}))}
function waitingIntel(s){return A(s.delegations).filter(open).map(x=>({title:x.title||x.name||'Čekání',at:dateOf(x),days:day(dateOf(x)),id:x.id||x.title})).sort((a,b)=>(a.days??999)-(b.days??999)).slice(0,12)}
function inboxRows(s){return A(s.personalInbox?.items).filter(open).slice(0,8)}
function ticketModel(){const rows=A(window.__KAMIL_TICKET_COMMANDER465__?.rows);const active=rows.filter(x=>!['DONE','CLOSED'].includes(String(x.status||'').toUpperCase()));const sell=active.filter(x=>/PRODAT|ZLEVNIT|EXIT|PANIC/i.test(`${x.what||''} ${x.title||''}`));const buy=active.filter(x=>/KOUPIT|BUY/i.test(`${x.what||''} ${x.title||''}`));const profit=active.reduce((a,x)=>a+N(x.realizedProfitCzk||x.profitCzk||0),0);return{active,sell,buy,profit}}
function bettingModel(){let l={};try{l=JSON.parse(localStorage.getItem('kamil_betting_ledger_543')||'{}')}catch{}const bets=A(l.bets),closed=bets.filter(x=>['WON','LOST','SETTLED','VOID'].includes(String(x.status||'').toUpperCase())),openB=bets.filter(x=>String(x.status||'OPEN').toUpperCase()==='OPEN'),pnl=closed.reduce((a,x)=>a+N(x.profitCzk||x.pnlCzk||0),0),staked=closed.reduce((a,x)=>a+N(x.stakeCzk),0),roi=staked?pnl/staked*100:0,bankroll=N(l.bankrollCzk);const hub=window.__KAMIL_BETTING_HUB630__?.model;const value=A(hub?.groups?.BET);return{bankroll,open:openB.length,pnl,roi,value,gate:value.filter(x=>N(x.score)>=70)}}
function propertyRows(s){return A(s.propertyBook?.items||s.properties||[]).filter(open).map(x=>({name:x.name||x.title||'Nemovitost',price:N(x.priceCzk||x.price||x.purchasePrice),rent:N(x.rentCzk||x.rent||x.monthlyRent),fund:N(x.fundCzk||x.fund||x.svf),status:x.status||'WATCH'})).slice(0,10)}
function smartSnooze(){const d=new Date().getDay(),hour=new Date().getHours();if(d===5&&hour>12)return['Pondělí ráno','Za 3 dny','Příští týden'];if(hour>=18)return['Zítra ráno','Za 3 dny','Příští týden'];return['Zítra','Za 3 dny','Za týden']}
function universalSearch(q,s){if(!String(q||'').trim())return[];const personal=personalSearch650(q,s);const qq=norm(q),extra=[];for(const x of propertyRows(s))if(norm(x.name).includes(qq))extra.push({type:'reality',title:x.name,meta:`${money(x.price)} · nájem ${money(x.rent)}`,route:'money'});for(const x of ticketModel().active)if(norm(`${x.title||''} ${x.name||''}`).includes(qq))extra.push({type:'ticket',title:x.title||x.name||'Vstupenka',meta:x.what||'',route:'tickets'});return [...personal,...extra].slice(0,12)}
function dataTrust(s){const health=personalSettings647(s),last=localStorage.getItem('kamil_os_last_full_backup')||localStorage.getItem('kamil_last_full_backup')||null;return{missing:N(health.missing),cloud:!!health.cloud,lastBackup:last,score:Math.max(0,100-N(health.missing)*8-(last?0:15))}}

export async function buildOperator717(s=store.get()){
 const daily=personalDailyAssistant650(s),capital=await unifiedCapitalState160(s).catch(()=>({cash:null,cashKnown:false,ticketCapital:0,waitingGross:0})),property=buildPropertyDecision472(s),tickets=ticketModel(),betting=bettingModel(),wait=waitingIntel(s),dl=deadlines(s),family=familyTimeline(s),home=homeTimeline(s),health=dataTrust(s),done=auditToday(s),inbox=inboxRows(s),props=propertyRows(s);
 const next=daily.primary||null,allClear=!next&&!N(daily.waitingCount)&&!dl.some(x=>x.days!==null&&x.days<=0);
 const morning={headline:next?`Začni: ${next.title}`:allClear?'Dnes nic nehoří.':'Zkontroluj dnešní termíny.',urgent:dl.filter(x=>x.days!==null&&x.days<=0).length,waiting:wait.length,cash:capital.cashKnown?capital.cash:null};
 const evening={done:done.length,left:N(daily.top?.length),tomorrow:N(daily.tomorrowCount),headline:allClear?'Dnes máš hotovo.':`Dnes zbývá ${N(daily.top?.length)} priorit.`};
 const freeCash=capital.cashKnown?capital.cash:0,freeCashDecision=freeCash>=3000000?'Drž část likvidně a porovnej reality vs. úročený cash.':freeCash>=500000?'Rozděl rezervu a investiční část.':'Priorita je rezerva a cashflow.';
 return{version:VERSION,daily,next,allClear,morning,evening,smartSnooze:smartSnooze(),waiting:wait,inbox,capital,freeCashDecision,property,properties:props,tickets,betting,deadlines:dl,family,home,health,doneToday:done.length,generatedAt:new Date().toISOString()}
}

function row(title,value,meta=''){return`<div class="op717-row"><div><b>${h(title)}</b>${meta?`<small>${h(meta)}</small>`:''}</div><span>${h(value)}</span></div>`}
function section(title,body){return`<section class="op717-card"><div class="eyebrow">${h(title)}</div>${body}</section>`}
function actions(){return`<div class="op717-actions"><button class="btn" data-op717-nav="today">Dnes</button><button class="btn" data-op717-nav="money">Peníze</button><button class="btn" data-op717-nav="tickets">Vstupenky</button><button class="btn" data-op717-nav="betting">Sázení</button><button class="btn" data-op717-data>Data & backup</button></div>`}
function html(m){const best=m.property?.best;return`<div class="op717" data-operator717>
${section('OS698–700 · DNEŠEK',`<h2>${h(m.morning.headline)}</h2><p>${h(m.evening.headline)}</p>${row('Next best action',m.next?.title||'Dnes máš hotovo')}${row('Hotovo dnes',String(m.doneToday))}${row('Smart snooze',m.smartSnooze.join(' · '))}`)}
${section('OS703–704 · ČEKÁNÍ A INBOX',`${row('Čekám na',String(m.waiting.length),m.waiting[0]?.title||'Nic nečeká')}${row('Inbox k akci',String(m.inbox.length),m.inbox[0]?.title||'Inbox je čistý')}<button class="btn" data-op717-inbox>Inbox → úkol</button>`)}
${section('OS705–708 · PENÍZE A REALITY',`${row('Volný cash',m.capital.cashKnown?money(m.capital.cash):'nezadaný',m.freeCashDecision)}${row('Reality kandidáti',String(m.properties.length),best?`${best.name} · ${best.decision?.action||''}`:'bez kandidáta')}${row('Ticket capital',money(m.capital.ticketCapital||0))}`)}
${section('OS709–710 · VSTUPENKY',`${row('Aktivní akce',String(m.tickets.active.length))}${row('Prodat / zlevnit',String(m.tickets.sell.length))}${row('Koupit',String(m.tickets.buy.length))}${row('Realizovaný P&L',money(m.tickets.profit))}`)}
${section('OS711–712 · SÁZENÍ',`${row('Bankroll',money(m.betting.bankroll))}${row('Otevřené sázky',String(m.betting.open))}${row('ROI historie',`${m.betting.roi.toFixed(1)} %`)}${row('Decision gate',m.betting.gate.length?`${m.betting.gate.length} splňuje gate`:'Nic nesplňuje gate')}`)}
${section('OS713–715 · TERMÍNY / RODINA / DOMOV',`${row('Termíny do 60 dní',String(m.deadlines.length),m.deadlines[0]?`${m.deadlines[0].title} · ${fmt(m.deadlines[0].at)}`:'Bez termínu')}${row('Rodina',String(m.family.length),m.family[0]?.title||'Bez blízkého termínu')}${row('Domov',String(m.home.length),m.home[0]?.title||'Bez blízké údržby')}`)}
${section('OS716–717 · SEARCH / DATA TRUST',`<div class="op717-search"><input class="command-input" data-op717-search placeholder="Hledej napříč OS…"><button class="btn" data-op717-searchgo>Hledat</button></div><div data-op717-results></div>${row('Data trust',`${m.health.score}/100`,`${m.health.missing} chybějících · ${m.health.cloud?'cloud připojen':'lokální režim'}`)}${row('Poslední backup',m.health.lastBackup?fmt(m.health.lastBackup):'není známý')}`)}
${actions()}</div>`}
function bind(root,m){root.querySelectorAll('[data-op717-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.op717Nav)));root.querySelector('[data-op717-data]')?.addEventListener('click',()=>openPersonalDataHealth647());root.querySelector('[data-op717-inbox]')?.addEventListener('click',()=>captureInboxTask717(m));const input=root.querySelector('[data-op717-search]'),out=root.querySelector('[data-op717-results]');root.querySelector('[data-op717-searchgo]')?.addEventListener('click',()=>{const rows=universalSearch(input?.value,store.get());out.innerHTML=rows.length?rows.map(x=>`<button class="op717-hit" data-route="${h(x.route||'today')}"><b>${h(x.title)}</b><small>${h(x.meta||x.type||'')}</small></button>`).join(''):'<div class="empty">Nic nenalezeno.</div>';out.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.route)))})}
function ensureCss(){if(document.querySelector('link[data-operator717-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./operator717.css';l.dataset.operator717Css='1';document.head.appendChild(l)}
export function captureInboxTask717(model){const s=store.get(),x=A(s.personalInbox?.items).find(open);if(!x){toast('Inbox nemá nic k převodu.');return false}store.mutate(`Inbox → úkol: ${x.title||'Položka'}`,d=>{d.tasks=A(d.tasks);d.tasks.push({id:uid('inbox-task'),title:x.title||x.name||'Inbox úkol',status:'OPEN',area:'Administrativa',category:'Inbox',due:new Date().toISOString(),sourceInboxId:x.id||null,createdAt:new Date().toISOString()});x.status='DONE';x.updatedAt=new Date().toISOString()},{undo:true,cloud:true,audit:true});toast('Inbox položka převedena na úkol.');return true}
export async function openOperator717(){ensureCss();const m=await buildOperator717();const wrap=document.createElement('div');wrap.innerHTML=html(m);const root=wrap.firstElementChild;const host=document.createElement('div');host.appendChild(root);bind(root,m);window.__KAMIL_OPERATOR717__={version:VERSION,healthy:true,model:m,open:openOperator717,at:Date.now()};return modal('Kamil OS · Operator Center',host.innerHTML,[{label:'Zavřít',value:null,primary:true}]).then(v=>v)}
export async function appendOperatorSummary717(){const m=await buildOperator717();const root=document.querySelector('[data-today-priority696]');if(!root)return false;root.querySelector('[data-op717-summary]')?.remove();const el=document.createElement('div');el.className='op717-summary';el.dataset.op717Summary='1';el.innerHTML=`<b>${h(m.allClear?'Dnes máš hotovo':m.next?.title||'Další krok')}</b><span>${h(m.allClear?'Žádná povinná akce nehoří.':m.next?.why||m.next?.next||'OS přepočítal další nejlepší akci.')}</span><button class="btn" type="button">Operator Center</button>`;el.querySelector('button').addEventListener('click',openOperator717);root.prepend(el);window.__KAMIL_OPERATOR717__={version:VERSION,healthy:true,model:m,open:openOperator717,at:Date.now()};return true}
window.addEventListener('kamil:personal-action-updated',()=>setTimeout(appendOperatorSummary717,120));
