import {store} from './state.js';
import {buildLifeOperator298,openLifeOperator298} from './lifeOperator298.js';
import {ownEvent1100,ownObserver1100,ownCleanup1100,schedule1100} from './runtimeOwnership1100.js';

const OWNER='operator.home299';
const money=v=>`${Math.round(Number(v)||0).toLocaleString('cs-CZ')} Kč`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let bound=false;
function ensureCss(){if(document.querySelector('link[data-operator299]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./operatorHome299.css';l.dataset.operator299='1';document.head.appendChild(l)}
function root(){return document.querySelector('#todayView .ux65-today')||document.querySelector('#todayView .ux64-page')||document.querySelector('#todayView')}
function slot(){return document.querySelector('#todayView .today213-head')}
function headline(m){const top=m.morning.top3?.[0];if(top)return top.title;if(m.waiting.overdue.length)return`${m.waiting.overdue.length} follow-up čeká`;if(m.deadlines.critical.length)return`${m.deadlines.critical.length} termín vyžaduje pozornost`;return'Nic kritického teď nehoří'}
function render(){const h=root(),s=slot();if(!h||!s)return false;let strip=s.querySelector('[data-operator-home299]');if(!strip){strip=document.createElement('section');strip.className='operator299';strip.dataset.operatorHome299='1';const glance=s.querySelector('[data-glance221]');if(glance)s.insertBefore(strip,glance);else s.appendChild(strip);strip.onclick=e=>{if(e.target.closest?.('[data-operator-open299]'))openLifeOperator298()}}const m=buildLifeOperator298(store.get());strip.innerHTML=`<button type="button" class="operator299-main" data-operator-open299><span class="operator299-mark">AI</span><span class="operator299-copy"><small>KAMIL OPERATOR</small><b>${esc(headline(m))}</b></span><span class="operator299-arrow">›</span></button><div class="operator299-metrics"><span class="${m.waiting.overdue.length?'warn':''}"><b>${m.waiting.overdue.length}</b><small>follow-up</small></span><span class="${m.deadlines.critical.length?'warn':''}"><b>${m.deadlines.critical.length}</b><small>termíny</small></span><span><b>${m.inbox.length}</b><small>inbox</small></span><span><b>${money(m.capital.deployable)}</b><small>nad rezervu</small></span></div>`;h.querySelectorAll('[data-os80-command]').forEach(x=>{x.hidden=true;x.style.setProperty('display','none','important')});window.__KAMIL_OPERATOR_HOME299__={version:299,at:Date.now(),headline:headline(m),waiting:m.waiting.overdue.length,deadlines:m.deadlines.critical.length,inbox:m.inbox.length,deployable:m.capital.deployable,mountedIn:'today213-head'};return true}
function schedule(delay=35){schedule1100(OWNER,'render',render,delay,{pauseWhenHidden:true})}
export function installOperatorHome299(){ensureCss();schedule();schedule(180);schedule(700);schedule(1500);if(bound)return;bound=true;ownEvent1100(OWNER,window,'kamil:view-change',e=>{const view=typeof e.detail==='string'?e.detail:e.detail?.view;if(view==='today')schedule()});ownEvent1100(OWNER,window,'kamil:personal-action-updated',()=>schedule());const unsub=store.subscribe?.(()=>schedule());if(typeof unsub==='function')ownCleanup1100(OWNER,unsub);const h=document.querySelector('#todayView');if(h)ownObserver1100(OWNER,h,{childList:true,subtree:true},()=>schedule())}
