import {store} from './state.js';
import {buildLifeOperator298,openLifeOperator298} from './lifeOperator298.js';

const money=v=>`${Math.round(Number(v)||0).toLocaleString('cs-CZ')} Kč`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let observer=null,timer=0;
function ensureCss(){if(document.querySelector('link[data-operator299]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./operatorHome299.css';l.dataset.operator299='1';document.head.appendChild(l)}
function host(){return document.querySelector('#todayView .ux65-today')||document.querySelector('#todayView .ux64-page')||document.querySelector('#todayView')}
function headline(m){const top=m.morning.top3?.[0];if(top)return top.title;if(m.waiting.overdue.length)return`${m.waiting.overdue.length} follow-up čeká`;if(m.deadlines.critical.length)return`${m.deadlines.critical.length} termín vyžaduje pozornost`;return'Nic kritického teď nehoří'}
function render(){const h=host();if(!h)return false;let strip=h.querySelector('[data-operator-home299]');if(!strip){strip=document.createElement('section');strip.className='operator299';strip.dataset.operatorHome299='1';const anchor=h.querySelector('.ux65-context')||h.querySelector('[data-os80-command]')||h.querySelector('.ux65-quick')||h.firstElementChild;if(anchor)anchor.before(strip);else h.prepend(strip)}const m=buildLifeOperator298(store.get());strip.innerHTML=`<button type="button" class="operator299-main" data-operator-open299><span class="operator299-mark">AI</span><span class="operator299-copy"><small>KAMIL OPERATOR</small><b>${esc(headline(m))}</b></span><span class="operator299-arrow">›</span></button><div class="operator299-metrics"><span class="${m.waiting.overdue.length?'warn':''}"><b>${m.waiting.overdue.length}</b><small>follow-up</small></span><span class="${m.deadlines.critical.length?'warn':''}"><b>${m.deadlines.critical.length}</b><small>termíny</small></span><span><b>${m.inbox.length}</b><small>inbox</small></span><span><b>${money(m.capital.deployable)}</b><small>nad rezervu</small></span></div>`;strip.querySelector('[data-operator-open299]')?.addEventListener('click',openLifeOperator298);h.querySelectorAll('[data-os80-command]').forEach(x=>x.hidden=true);window.__KAMIL_OPERATOR_HOME299__={version:299,at:Date.now(),headline:headline(m),waiting:m.waiting.overdue.length,deadlines:m.deadlines.critical.length,inbox:m.inbox.length,deployable:m.capital.deployable};return true}
function schedule(){clearTimeout(timer);timer=setTimeout(render,35)}
export function installOperatorHome299(){ensureCss();schedule();setTimeout(schedule,180);setTimeout(schedule,700);window.addEventListener('kamil:view-change',e=>{if(e.detail==='today')schedule()});window.addEventListener('kamil:personal-action-updated',schedule);store.subscribe?.(()=>schedule());const h=document.querySelector('#todayView');if(h){observer?.disconnect?.();observer=new MutationObserver(schedule);observer.observe(h,{childList:true,subtree:false})}}
