import {store} from './state.js';
import {xtbPositions} from './decision24.js';
import {h} from './utils.js';
const N=v=>Number(v||0),U=v=>String(v||'').toUpperCase(),TARGET_KEY='kamil-os-target-allocation-113';
function val(p){return N(p.value||p.marketValue||0)}
function targets(rows){let saved={};try{saved=JSON.parse(localStorage.getItem(TARGET_KEY)||'{}')||{}}catch{};if(!Object.keys(saved).length)return Object.fromEntries(rows.map(r=>[r.ticker,r.actual]));const sum=Object.values(saved).reduce((a,v)=>a+N(v),0)||1;return Object.fromEntries(Object.entries(saved).map(([k,v])=>[k,N(v)/sum*100]))}
function riskPenalty(p,weight){let x=0;const cat=U(p.category),pl=N(p.net_profit_pct),name=U(`${p.sector||''} ${p.industry||''} ${p.name||''}`);if(cat!=='ETF')x+=8;if(weight>=12)x+=22;else if(weight>=9)x+=12;if(pl<=-15)x+=18;else if(pl<=-8)x+=9;if(pl>=35)x+=12;if(/BIOTECH|CRYPTO|SEMICONDUCTOR/.test(name))x+=8;return x}
function scoreRows(deposit){const ps=xtbPositions(store.get()).filter(p=>val(p)>0),total=ps.reduce((a,p)=>a+val(p),0)||1,base=ps.map(p=>({p,ticker:String(p.ticker||'—'),value:val(p),actual:val(p)/total*100})),tg=targets(base),after=total+deposit;return base.map(r=>{const target=N(tg[r.ticker]),gap=Math.max(0,after*target/100-r.value),under=Math.max(0,target-r.actual),pl=N(r.p.net_profit_pct),penalty=riskPenalty(r.p,r.actual);let score=42+Math.min(28,under*4)+Math.min(18,gap/Math.max(1,deposit)*22)-penalty;if(U(r.p.category)==='ETF')score+=6;if(pl<=-3&&pl>-15)score+=5;if(pl>=25)score-=10;score=Math.max(0,Math.min(100,score));const reasons=[];if(under>1)reasons.push(`pod cílem o ${under.toFixed(1)} p. b.`);if(gap>0)reasons.push(`rebalancing gap ${Math.round(gap).toLocaleString('cs-CZ')} Kč`);if(U(r.p.category)==='ETF')reasons.push('nižší penalizace za diverzifikaci');if(penalty>=15)reasons.push('vyšší risk penalizace');if(!reasons.length)reasons.push('blízko cílové váhy');return{...r,target,gap,under,score,penalty,reasons}}).sort((a,b)=>b.score-a.score)}
function allocate(rows,deposit){const eligible=rows.filter(r=>r.gap>0&&r.score>=45),weights=eligible.map(r=>Math.max(0,r.gap)*(r.score/100)),sum=weights.reduce((a,v)=>a+v,0)||1;return rows.map(r=>{const i=eligible.indexOf(r);return{...r,allocation:i<0?0:Math.min(r.gap,deposit*weights[i]/sum)}})}
function mount(){const root=document.querySelector('.dashboard110');if(!root||root.querySelector('.os116'))return;const deposit=N(store.get()?.financePlan?.plannedInvestment)||25000,rows=allocate(scoreRows(deposit),deposit),top=rows.filter(x=>x.allocation>0).slice(0,5);if(!rows.length)return;const sec=document.createElement('section');sec.className='os116 d110-card';sec.innerHTML=`<div class="os116-head"><div><div class="eyebrow">XTB · OPPORTUNITY RADAR</div><h2>Kam dát příštích ${Math.round(deposit).toLocaleString('cs-CZ')} Kč?</h2><p>Pořadí kombinuje cílovou váhu, rebalancing gap a risk penalizaci. Je to návrh k ručnímu rozhodnutí, ne pokyn k obchodu.</p></div><span class="os116-badge">${top.length?`${top.length} kandidátů`:'ČEKAT'}</span></div>${top.length?`<div class="os116-list">${top.map((r,i)=>`<article><div class="os116-rank">#${i+1}</div><div class="os116-main"><b>${h(r.ticker)}</b><small>${h(r.reasons.join(' · '))}</small><div class="os116-bar"><i style="width:${r.score}%"></i></div></div><div class="os116-score"><small>SKÓRE</small><b>${Math.round(r.score)}/100</b></div><div class="os116-money"><small>NÁVRH</small><b>${Math.round(r.allocation).toLocaleString('cs-CZ')} Kč</b></div></article>`).join('')}</div>`:`<div class="os116-empty"><b>Teď není zřetelný podvážený kandidát.</b><span>OS raději navrhuje nový vklad zatím nealokovat než ho rozdělit uměle.</span></div>`}<div class="os116-foot"><span>Nejvyšší penalizace se dává převaženým, výrazně ztrátovým nebo prudce ziskovým jednotlivým akciím.</span><button class="btn" data-os116-rebalance>Upravit cíle →</button></div>`;const anchor=root.querySelector('.os115')||root.querySelector('.os114')||root.querySelector('.os113');anchor?.after(sec);sec.querySelector('[data-os116-rebalance]')?.addEventListener('click',()=>root.querySelector('.os113')?.scrollIntoView({behavior:'smooth',block:'start'}));window.__KAMIL_OS116__={at:Date.now(),deposit,top:top.map(x=>({ticker:x.ticker,score:Math.round(x.score),allocation:Math.round(x.allocation)}))}}
export function enhanceOS116(){mount()}
