import {store} from './state.js';
import {xtbPositions} from './decision24.js';
import {quoteSymbolForPosition32} from './marketQuote32.js';
import {h} from './utils.js';
const A=v=>Array.isArray(v)?v:[],N=v=>Number(v||0),U=v=>String(v||'').toUpperCase();
const qty=p=>N(p.quantity||p.qty||p.volume||p.units||p.shares||0),val=p=>N(p.value||p.marketValue||0);
async function history(){const ps=xtbPositions(store.get()),symbols=[...new Set(ps.map(quoteSymbolForPosition32).filter(Boolean))];if(!symbols.length)return{ok:false,series:[]};try{const r=await fetch(`/api/market-history?symbols=${encodeURIComponent(symbols.join(','))}&range=3mo`,{cache:'no-store'});return await r.json()}catch{return{ok:false,series:[]}}}
function returns(points){const a=A(points).map(x=>N(x.p)).filter(x=>x>0),out=[];for(let i=1;i<a.length;i++)out.push(a[i]/a[i-1]-1);return out}
function mean(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function stdev(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/(a.length-1))}
function corr(a,b){const n=Math.min(a.length,b.length);if(n<5)return null;const x=a.slice(-n),y=b.slice(-n),mx=mean(x),my=mean(y),sx=Math.sqrt(x.reduce((s,v)=>s+(v-mx)*(v-mx),0)),sy=Math.sqrt(y.reduce((s,v)=>s+(v-my)*(v-my),0));if(!sx||!sy)return null;return x.reduce((s,v,i)=>s+(v-mx)*(y[i]-my),0)/(sx*sy)}
function build(data){const ps=xtbPositions(store.get()).filter(p=>val(p)>0),total=ps.reduce((a,p)=>a+val(p),0)||1,by=new Map(A(data?.series).map(s=>[U(s.symbol),s])),rows=[];for(const p of ps){const s=by.get(U(quoteSymbolForPosition32(p)));if(!s)continue;const r=returns(s.points),vol=stdev(r)*Math.sqrt(252)*100,weight=val(p)/total*100;rows.push({p,symbol:s.symbol,ret:r,vol,weight,riskContribution:weight*vol})}const riskSum=rows.reduce((a,r)=>a+r.riskContribution,0)||1;rows.forEach(r=>r.riskShare=r.riskContribution/riskSum*100);let pairs=[];for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){const c=corr(rows[i].ret,rows[j].ret);if(c!==null)pairs.push({a:rows[i].p.ticker,b:rows[j].p.ticker,c})}pairs.sort((x,y)=>y.c-x.c);const avgCorr=pairs.length?mean(pairs.map(x=>x.c)):0;const portfolioVolApprox=Math.sqrt(rows.reduce((sum,ri,i)=>sum+rows.reduce((s,rj,j)=>{const c=i===j?1:(corr(ri.ret,rj.ret)??0);return s+(ri.weight/100)*(rj.weight/100)*(ri.vol/100)*(rj.vol/100)*c},0),0))*100;const stressMarket=-10,stressUsd=-10;const marketLoss=rows.reduce((a,r)=>a+val(r.p)*(stressMarket/100),0),usdLoss=rows.filter(r=>U(r.p.currency||r.p.accountCurrency)==='USD').reduce((a,r)=>a+val(r.p)*(stressUsd/100),0);return{rows:rows.sort((a,b)=>b.riskShare-a.riskShare),pairs,avgCorr,portfolioVolApprox,marketLoss,usdLoss,total}}
function mount(model){const root=document.querySelector('.dashboard110');if(!root||root.querySelector('.os117')||!model.rows.length)return;const sec=document.createElement('section');sec.className='os117 d110-card';const topPair=model.pairs[0];sec.innerHTML=`<div class="os117-head"><div><div class="eyebrow">XTB · STATISTICAL RISK ENGINE</div><h2>Volatilita, korelace a stress test</h2><p>Výpočet z přibližně 3 měsíců denních market dat. Jde o historický model, ne předpověď budoucího rizika.</p></div><div class="os117-kpi"><small>Odhad anualizované volatility portfolia</small><b>${model.portfolioVolApprox.toFixed(1)} %</b><span>historický odhad</span></div></div><div class="os117-grid"><article><small>Průměrná korelace</small><b>${model.avgCorr.toFixed(2)}</b><span>${model.avgCorr>.65?'Vysoká společná závislost':model.avgCorr>.35?'Střední závislost':'Nižší závislost'}</span></article><article><small>Nejvyšší korelace</small><b>${topPair?`${h(topPair.a)} × ${h(topPair.b)}`:'—'}</b><span>${topPair?topPair.c.toFixed(2):'—'}</span></article><article><small>Stress: celý trh -10 %</small><b>${Math.round(model.marketLoss).toLocaleString('cs-CZ')} Kč</b><span>mechanický scénář</span></article><article><small>Stress: USD -10 %</small><b>${Math.round(model.usdLoss).toLocaleString('cs-CZ')} Kč</b><span>jen USD pozice</span></article></div><div class="os117-table"><div class="os117-th"><span>Pozice</span><span>Váha</span><span>Volatilita</span><span>Risk share</span></div>${model.rows.slice(0,10).map(r=>`<div class="os117-tr"><b>${h(r.p.ticker||'—')}</b><span>${r.weight.toFixed(1)} %</span><span>${r.vol.toFixed(1)} %</span><span><i style="width:${Math.min(100,r.riskShare)}%"></i><b>${r.riskShare.toFixed(1)} %</b></span></div>`).join('')}</div><div class="os117-note">Korelace jsou počítané z dostupných překrývajících se denních výnosů. Chybějící nebo krátká historie se vynechá. Stress scénáře jsou lineární a neřeší intradenní pohyb, opce ani nelineární měnové efekty.</div>`;const anchor=root.querySelector('.os116')||root.querySelector('.os115');anchor?.after(sec);window.__KAMIL_OS117__={at:Date.now(),positions:model.rows.length,portfolioVol:model.portfolioVolApprox,avgCorr:model.avgCorr}}
export async function enhanceOS117(){const data=await history();if(!data?.ok)return;mount(build(data))}
