import {store} from './state.js';
import {xtbPositions} from './decision24.js';
import {quoteSymbolForPosition32} from './marketQuote32.js';
import {loadTicketCloud660} from './ticketCloud660.js';
import {h,money} from './utils.js';
const A=v=>Array.isArray(v)?v:[],N=v=>Number(v||0),U=v=>String(v||'').toUpperCase();
const qty=p=>N(p.quantity||p.qty||p.volume||p.units||p.shares||0);
function svg(points,cls=''){if(!points?.length)return'';const ps=points.map(Number).filter(Number.isFinite);if(ps.length<2)return'';const min=Math.min(...ps),max=Math.max(...ps),span=max-min||1,w=100,hg=30,coords=ps.map((p,i)=>`${(i/(ps.length-1)*w).toFixed(1)},${(hg-(p-min)/span*hg).toFixed(1)}`).join(' ');return`<svg class="${cls}" viewBox="0 0 100 30" preserveAspectRatio="none"><polyline points="${coords}"/></svg>`}
async function history(range='1mo'){const pos=xtbPositions(store.get()),symbols=[...new Set(pos.map(quoteSymbolForPosition32).filter(Boolean))];if(!symbols.length)return{ok:false,series:[]};try{const r=await fetch(`/api/market-history?symbols=${encodeURIComponent(symbols.join(','))}&range=${range}`,{cache:'no-store'});return await r.json()}catch{return{ok:false,series:[]}}}
function positionMap(){return new Map(xtbPositions(store.get()).map(p=>[U(p.ticker),p]))}
function sparkRows(data){const by=new Map(A(data?.series).map(x=>[U(x.symbol),x.points||[]]));const pos=positionMap();for(const row of document.querySelectorAll('.d110-tr')){const ticker=U(row.querySelector('.d110-pos b')?.textContent),p=pos.get(ticker);if(!p)continue;const symbol=U(quoteSymbolForPosition32(p)),pts=A(by.get(symbol)).map(x=>N(x.p));if(pts.length<2)continue;const first=pts[0],last=pts.at(-1),cls=last>first?'pos':last<first?'neg':'';const priceCell=row.children?.[2];if(priceCell&&!priceCell.querySelector('.os111-spark'))priceCell.insertAdjacentHTML('beforeend',svg(pts.slice(-22),`os111-spark ${cls}`));}}
function portfolioSeries(data){const positions=xtbPositions(store.get()),map=new Map(A(data?.series).map(x=>[U(x.symbol),x.points||[]])),items=[];for(const p of positions){const pts=A(map.get(U(quoteSymbolForPosition32(p))));if(pts.length<2||!qty(p))continue;items.push({q:qty(p),pts})}if(!items.length)return[];const dates=[...new Set(items.flatMap(x=>x.pts.map(p=>p.t)))].sort((a,b)=>a-b),last=new Map(),out=[];for(const t of dates){let v=0,c=0;for(const x of items){const p=x.pts.find(z=>z.t===t);if(p)last.set(x,p.p);const px=last.get(x);if(px){v+=px*x.q;c++}}if(c)out.push({t,v})}if(out.length<2)return[];const base=out[0].v||1;return out.map(x=>(x.v/base-1)*100)}
function perfPanel(data,range){const portfolio=document.querySelector('.d110-portfolio');if(!portfolio)return;portfolio.querySelector('.os111-perf')?.remove();const values=portfolioSeries(data),end=values.at(-1)||0,panel=document.createElement('div');panel.className='os111-perf os111-soft';panel.innerHTML=`<div class="os111-perf-head"><div><b>VÝVOJ PORTFOLIA</b><small style="display:block;color:#8fa4bc">Normalizovaný vývoj pozic z market history feedu</small></div><b style="color:${end>=0?'#24d27e':'#ff5b66'}">${end>=0?'+':''}${end.toFixed(2)} %</b><div class="os111-tabs">${[['1mo','1M'],['3mo','3M'],['6mo','6M'],['1y','1R']].map(([r,l])=>`<button data-range="${r}" class="${r===range?'on':''}">${l}</button>`).join('')}</div></div>${values.length?svg(values,'os111-chart'):'<div class="d110-empty">Historie zatím není dostupná.</div>'}`;portfolio.appendChild(panel);panel.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>refreshMarketVisuals(b.dataset.range));}
function heatmap(){document.querySelector('.os111-heat-section')?.remove();const rows=[...document.querySelectorAll('.d110-tr')],portfolio=document.querySelector('.d110-portfolio');if(!portfolio||!rows.length)return;const sec=document.createElement('div');sec.className='os111-perf os111-heat-section os111-soft';sec.innerHTML='<div class="os111-perf-head"><div><b>PORTFOLIO HEATMAP</b><small style="display:block;color:#8fa4bc">Velikost pozice a aktuální P/L</small></div></div><div class="os111-heatmap"></div>';const grid=sec.querySelector('.os111-heatmap');rows.slice(0,16).forEach(r=>{const ticker=r.querySelector('.d110-pos b')?.textContent||'—',pl=r.children?.[4]?.textContent||'',value=r.children?.[5]?.textContent||'',neg=/-/.test(pl),pos=/\+/.test(pl);grid.insertAdjacentHTML('beforeend',`<div class="os111-heat ${neg?'neg':pos?'pos':''}"><b>${h(ticker)}</b><small>${h(value.trim())}</small><b>${h(pl.trim().split('\n')[0])}</b></div>`)});portfolio.appendChild(sec)}
async function ticketTradingCards(){const host=document.querySelector('.d110-grid-mid section:first-child');if(!host)return;let cloud;try{cloud=await loadTicketCloud660()}catch{return}if(!cloud?.ok)return;const old=host.querySelectorAll('.d110-ticket,.d110-ticket-head');old.forEach(x=>x.remove());for(const r of A(cloud.inventory).filter(x=>['LISTED','NOT_LISTED'].includes(x.market_status)).slice(0,6)){const d=r.event_date?Math.ceil((new Date(r.event_date).getTime()-Date.now())/86400000):null,buy=N(r.buy_each_czk),ask=N(r.ask_each_czk),market=N(r.verified_sector_price_czk),pl=ask&&buy?(ask-buy)*N(r.qty||1):0;host.insertAdjacentHTML('beforeend',`<div class="os111-ticket-card os111-soft"><div class="os111-ticket-top"><div><b>${h(r.event_name||'Vstupenka')}</b><small style="display:block;color:#8fa4bc">${h(r.section||'—')} · ${r.qty||1} ks</small></div>${d!==null?`<span class="os111-countdown">${d<0?'PROBĚHLO':d===0?'DNES':`${d} DNÍ`}</span>`:''}</div><div class="os111-ticket-grid"><div><small>Nákup</small><b>${buy?money(buy):'—'}</b></div><div><small>Moje cena</small><b>${ask?money(ask):'—'}</b></div><div><small>Sektor/trh</small><b>${market?money(market):'—'}</b></div><div><small>Potenciál</small><b style="color:${pl>=0?'#24d27e':'#ff5b66'}">${pl?money(pl):'—'}</b></div><div><small>Stav</small><b>${market?'SLEDOVAT':'OVĚŘIT'}</b></div></div></div>`);}}
function notifications(){if(document.querySelector('.os111-bell'))return;const top=document.querySelector('.top-actions');if(!top)return;const bell=document.createElement('button');bell.className='icon-btn os111-bell';bell.innerHTML='🔔<span class="os111-dot"></span>';bell.title='Notifikační centrum';top.prepend(bell);bell.onclick=async()=>{document.querySelector('.os111-pop')?.remove();let cloud=null;try{cloud=await loadTicketCloud660()}catch{}const near=A(cloud?.inventory).filter(r=>{const d=r.event_date?Math.ceil((new Date(r.event_date)-Date.now())/86400000):999;return d>=0&&d<=7&&['LISTED','NOT_LISTED'].includes(r.market_status)}).slice(0,4),review=[...document.querySelectorAll('.d110-action')].filter(x=>/OVĚŘIT|PRODAT|REDUKOVAT/.test(x.textContent)).slice(0,4),pop=document.createElement('div');pop.className='os111-pop os111-soft';pop.innerHTML=`<h3>Co si zaslouží pozornost</h3>${near.map(x=>`<article><b>🎟 ${h(x.event_name)}</b><small>Akce je do 7 dní — zkontroluj cenu a prodejní stav.</small></article>`).join('')}${review.map(x=>`<article><b>📈 ${h(x.closest('.d110-tr')?.querySelector('.d110-pos b')?.textContent||'XTB')}</b><small>${h(x.textContent)} — otevři detail rozhodnutí.</small></article>`).join('')||''}${!near.length&&!review.length?'<article><b>Klid</b><small>Teď tu není nic urgentního.</small></article>':''}`;document.body.appendChild(pop);setTimeout(()=>document.addEventListener('click',e=>{if(!pop.contains(e.target)&&e.target!==bell)pop.remove()},{once:true}),0)}}
async function refreshMarketVisuals(range='1mo'){const data=await history(range);sparkRows(data);perfPanel(data,range);heatmap();}
export async function enhanceOS111(){notifications();ticketTradingCards();await refreshMarketVisuals('1mo');document.body.classList.add('os111-ready');window.__KAMIL_OS111__={at:Date.now(),ready:true}}
