import {store} from './state.js';
import {xtbPositions} from './decision24.js';
import {h} from './utils.js';
const N=v=>Number(v||0),A=v=>Array.isArray(v)?v:[],U=v=>String(v||'').toUpperCase();
const KEY='kamil-os-portfolio-plan-114';
function value(p){return N(p.value||p.marketValue||0)}
function isEtf(p){return U(p.category)==='ETF'||/ETF|UCITS|ISHARES|VANGUARD|SPDR|XTRACKERS|AMUNDI/i.test(String(p.name||''))}
function assetClass(p){return isEtf(p)?'ETF':'Jednotlivé akcie'}
function currency(p){return U(p.accountCurrency||p.currency||'NEZNÁMÁ')}
function sector(p){const s=String(p.sector||p.industry||'').trim();if(s)return s;const c=String(p.category||'').trim();if(c&&U(c)!=='ETF')return c;return isEtf(p)?'ETF / fond':'Nezařazeno'}
function groups(ps,fn){const total=ps.reduce((a,p)=>a+value(p),0)||1,m=new Map();for(const p of ps){const k=fn(p);m.set(k,(m.get(k)||0)+value(p))}return [...m].map(([name,v])=>({name,value:v,pct:v/total*100})).sort((a,b)=>b.value-a.value)}
function loadPlan(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{return{}}}
function savePlan(x){localStorage.setItem(KEY,JSON.stringify(x))}
function defaults(asset){const etf=asset.find(x=>x.name==='ETF')?.pct||0,stocks=asset.find(x=>x.name==='Jednotlivé akcie')?.pct||0;return{assetTargets:{ETF:Number(etf.toFixed(1)),'Jednotlivé akcie':Number(stocks.toFixed(1)),Cash:0},currencyTargets:{},sectorCaps:{}}}
function rowHtml(x,target=null,cap=false){const diff=target===null?null:x.pct-target,tone=diff===null?'':cap?(x.pct>target?'bad':'good'):(Math.abs(diff)<=3?'good':diff>0?'warn':'under');return`<div class="os114-row"><b>${h(x.name)}</b><span>${x.pct.toFixed(1)} %</span><span>${target===null?'—':`${Number(target).toFixed(1)} %`}</span><span class="${tone}">${diff===null?'bez cíle':cap?(x.pct>target?`+${(x.pct-target).toFixed(1)} p. b. nad limitem`:'v limitu'):`${diff>=0?'+':''}${diff.toFixed(1)} p. b.`}</span></div>`}
function render(){const root=document.querySelector('.dashboard110');if(!root||root.querySelector('.os114'))return;const ps=xtbPositions(store.get()).filter(p=>value(p)>0);if(!ps.length)return;const asset=groups(ps,assetClass),curr=groups(ps,currency),sect=groups(ps,sector),saved=loadPlan(),plan={...defaults(asset),...saved,assetTargets:{...defaults(asset).assetTargets,...(saved.assetTargets||{})},currencyTargets:saved.currencyTargets||{},sectorCaps:saved.sectorCaps||{}};const sec=document.createElement('section');sec.className='os114 d110-card';sec.innerHTML=`<div class="os114-head"><div><div class="eyebrow">XTB · PORTFOLIO PLAN</div><h2>Strukturální alokace</h2><p>Kontrola typu aktiv, měn a sektorové koncentrace. Cíle jsou tvoje; OS je pouze porovnává s aktuálním importem.</p></div><button class="btn" data-edit>Upravit cíle</button></div><div class="os114-kpis"><div><small>ETF</small><b>${(asset.find(x=>x.name==='ETF')?.pct||0).toFixed(1)} %</b></div><div><small>Jednotlivé akcie</small><b>${(asset.find(x=>x.name==='Jednotlivé akcie')?.pct||0).toFixed(1)} %</b></div><div><small>Největší měna</small><b>${curr[0]?`${h(curr[0].name)} ${curr[0].pct.toFixed(0)} %`:'—'}</b></div><div><small>Největší sektor</small><b>${sect[0]?`${h(sect[0].name)} ${sect[0].pct.toFixed(0)} %`:'—'}</b></div></div><div class="os114-grid"><article><div class="os114-title"><b>TYP AKTIV</b><span>Aktuálně · Cíl · Odchylka</span></div>${asset.map(x=>rowHtml(x,plan.assetTargets[x.name]??null)).join('')}</article><article><div class="os114-title"><b>MĚNY</b><span>Aktuálně · Cíl · Odchylka</span></div>${curr.map(x=>rowHtml(x,plan.currencyTargets[x.name]??null)).join('')}</article><article><div class="os114-title"><b>SEKTORY / KATEGORIE</b><span>Aktuálně · Limit · Stav</span></div>${sect.slice(0,8).map(x=>rowHtml(x,plan.sectorCaps[x.name]??null,true)).join('')}</article></div><div class="os114-note">Cash se započítá až tehdy, když ho XTB import poskytne jako spolehlivou samostatnou hodnotu. Sektor používá importované metadata; neznámé pozice jsou označené „Nezařazeno“ místo domýšlení.</div>`;const anchor=root.querySelector('.os113')||root.querySelector('.d110-grid-mid');anchor?.after(sec);sec.querySelector('[data-edit]')?.addEventListener('click',()=>edit(plan,asset,curr,sect,sec));window.__KAMIL_OS114__={at:Date.now(),asset,currencies:curr,sectors:sect}}
function edit(plan,asset,curr,sect,sec){const modal=document.createElement('div');modal.className='d110-review-backdrop';modal.innerHTML=`<section class="d110-review-modal os114-modal"><header><div><div class="eyebrow">PORTFOLIO PLAN 114</div><h2>Upravit strukturální cíle</h2></div><button class="d110-review-close">×</button></header><h3>Typ aktiv</h3>${['ETF','Jednotlivé akcie','Cash'].map(k=>`<label>${h(k)}<input data-asset="${h(k)}" type="number" min="0" max="100" step="1" value="${N(plan.assetTargets[k])}"> %</label>`).join('')}<h3>Měnové cíle</h3>${curr.map(x=>`<label>${h(x.name)}<input data-currency="${h(x.name)}" type="number" min="0" max="100" step="1" value="${N(plan.currencyTargets[x.name])}"> %</label>`).join('')}<h3>Maximální sektorové váhy</h3>${sect.slice(0,8).map(x=>`<label>${h(x.name)}<input data-sector="${h(x.name)}" type="number" min="0" max="100" step="1" value="${N(plan.sectorCaps[x.name])}"> %</label>`).join('')}<footer><button class="btn" data-close>Zrušit</button><button class="btn primary" data-save>Uložit plán</button></footer></section>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.d110-review-close')?.addEventListener('click',close);modal.querySelector('[data-close]')?.addEventListener('click',close);modal.querySelector('[data-save]')?.addEventListener('click',()=>{const next={assetTargets:{},currencyTargets:{},sectorCaps:{}};modal.querySelectorAll('[data-asset]').forEach(i=>next.assetTargets[i.dataset.asset]=N(i.value));modal.querySelectorAll('[data-currency]').forEach(i=>{if(N(i.value)>0)next.currencyTargets[i.dataset.currency]=N(i.value)});modal.querySelectorAll('[data-sector]').forEach(i=>{if(N(i.value)>0)next.sectorCaps[i.dataset.sector]=N(i.value)});savePlan(next);close();sec.remove();render()})}
export function enhanceOS114(){render()}
