import {store} from './state.js';
import {xtbPositions} from './decision24.js';
import {h} from './utils.js';
const N=v=>Number(v||0),U=v=>String(v||'').toUpperCase();
const val=p=>N(p.value||p.marketValue||0);
function classify(p){const text=U(`${p.name||''} ${p.sector||''} ${p.industry||''} ${p.category||''}`);return{usd:U(p.currency||p.accountCurrency)==='USD',tech:/TECH|SOFTWARE|SEMICONDUCT|NASDAQ|INTERNET|AI|CLOUD/.test(text)}}
function positions(){return xtbPositions(store.get()).filter(p=>val(p)>0)}
function applyScenario(ps,type){const total=ps.reduce((a,p)=>a+val(p),0)||1;const largest=[...ps].sort((a,b)=>val(b)-val(a))[0];const rows=ps.map(p=>{const c=classify(p);let shock=0;if(type==='nasdaq')shock=c.tech?-20:-6;else if(type==='usd')shock=c.usd?-15:0;else if(type==='largest')shock=p===largest?-30:0;else if(type==='combo')shock=(c.tech?-18:-8)+(c.usd?-8:0);const impact=val(p)*shock/100;return{p,shock,impact,after:val(p)+impact}}).sort((a,b)=>Math.abs(b.impact)-Math.abs(a.impact));const impact=rows.reduce((a,r)=>a+r.impact,0),after=total+impact;return{rows,total,impact,after,pct:impact/total*100,largest}}
const SCENARIOS={nasdaq:{label:'Nasdaq / tech -20 %',desc:'Tech a growth pozice -20 %, ostatní akcie mechanicky -6 %.'},usd:{label:'USD -15 %',desc:'Měnový šok na pozice vedené v USD, bez změny ceny akcií.'},largest:{label:'Největší pozice -30 %',desc:'Izolovaný propad největší pozice v portfoliu.'},combo:{label:'Kombinovaný risk-off',desc:'Tech -18 %, ostatní -8 % a USD pozice navíc -8 %.'}};
function renderResult(sec,type){const m=applyScenario(positions(),type),cfg=SCENARIOS[type],box=sec.querySelector('[data-os118-result]');box.innerHTML=`<div class="os118-result-head"><div><small>SCÉNÁŘ</small><h3>${h(cfg.label)}</h3><p>${h(cfg.desc)}</p></div><div class="os118-impact"><small>Dopad portfolia</small><b>${Math.round(m.impact).toLocaleString('cs-CZ')} Kč</b><span>${m.pct.toFixed(1)} %</span></div></div><div class="os118-breakdown">${m.rows.slice(0,8).map(r=>`<div class="os118-row"><div><b>${h(r.p.ticker||'—')}</b><small>${r.shock?`${r.shock.toFixed(0)} % šok`:'bez šoku'}</small></div><strong class="${r.impact<0?'bad':'good'}">${Math.round(r.impact).toLocaleString('cs-CZ')} Kč</strong><span>po scénáři ${Math.round(r.after).toLocaleString('cs-CZ')} Kč</span></div>`).join('')}</div><div class="os118-total"><span>Hodnota před</span><b>${Math.round(m.total).toLocaleString('cs-CZ')} Kč</b><span>Hodnota po</span><b>${Math.round(m.after).toLocaleString('cs-CZ')} Kč</b></div>`;sec.querySelectorAll('[data-scenario]').forEach(b=>b.classList.toggle('active',b.dataset.scenario===type));window.__KAMIL_OS118__={at:Date.now(),scenario:type,impact:m.impact,pct:m.pct}}
function mount(){const root=document.querySelector('.dashboard110');if(!root||root.querySelector('.os118'))return;const ps=positions();if(!ps.length)return;const sec=document.createElement('section');sec.className='os118 d110-card';sec.innerHTML=`<div class="os118-head"><div><div class="eyebrow">XTB · SCENARIO LAB</div><h2>Co když přijde problém?</h2><p>Klikni na scénář a OS spočítá mechanický dopad na aktuální portfolio v Kč i po jednotlivých pozicích.</p></div></div><div class="os118-tabs">${Object.entries(SCENARIOS).map(([k,v])=>`<button data-scenario="${k}">${h(v.label)}</button>`).join('')}</div><div data-os118-result></div><div class="os118-note">Scenario Lab není předpověď ani VaR. Je to jednoduchý stresový test, který používá současnou hodnotu pozic a předem definované šoky. Neřeší intradenní korelace, opce ani daňový dopad.</div>`;const anchor=root.querySelector('.os117')||root.querySelector('.os116');anchor?.after(sec);sec.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>renderResult(sec,b.dataset.scenario)));renderResult(sec,'combo')}
export function enhanceOS118(){mount()}
