import {store} from './state.js';
import {xtbPositions} from './decision24.js';
import {h} from './utils.js';
const N=v=>Number(v||0),upper=v=>String(v||'').toUpperCase();
function value(p){return N(p.value||p.marketValue)}
function kind(p){return upper(p.category)==='ETF'?'ETF':'AKCIE'}
function riskFactor(p){let f=kind(p)==='ETF'?0.72:1.18;const pl=Math.abs(N(p.net_profit_pct));if(pl>=15)f+=.22;else if(pl>=8)f+=.10;const name=upper(`${p.sector||''} ${p.industry||''} ${p.name||''}`);if(/TECH|SEMICONDUCT|BIOTECH|CRYPTO|ENERGY/.test(name))f+=.12;return f}
function model(){const ps=xtbPositions(store.get()).filter(p=>value(p)>0),total=ps.reduce((a,p)=>a+value(p),0)||1;const rows=ps.map(p=>{const weight=value(p)/total*100,rf=riskFactor(p),score=weight*rf;return{p,weight,rf,score}});const sum=rows.reduce((a,r)=>a+r.score,0)||1;rows.forEach(r=>r.riskShare=r.score/sum*100);rows.sort((a,b)=>b.riskShare-a.riskShare);const top=rows[0];const top3=rows.slice(0,3).reduce((a,r)=>a+r.riskShare,0);const concentration=top3>=65?'VYSOKÁ':top3>=48?'STŘEDNÍ':'NÍZKÁ';return{rows,top,top3,concentration}}
function mount(){const root=document.querySelector('.dashboard110');if(!root||root.querySelector('.os115'))return;const m=model();if(!m.rows.length)return;const sec=document.createElement('section');sec.className='os115 d110-card';sec.innerHTML=`<div class="os115-head"><div><div class="eyebrow">XTB · RISK BUDGET</div><h2>Kdo nese riziko portfolia?</h2><p>Orientační model koncentrace podle váhy, typu aktiva a aktuálního P/L. Není to VaR ani predikce volatility.</p></div><div class="os115-badge ${m.concentration.toLowerCase()}"><small>KONCENTRACE TOP 3</small><b>${m.top3.toFixed(0)} %</b><span>${m.concentration}</span></div></div><div class="os115-summary"><div><small>Největší risk contributor</small><b>${h(m.top?.p?.ticker||'—')}</b><span>${m.top?.riskShare.toFixed(1)||0} % risk budgetu</span></div><div><small>Jeho váha portfolia</small><b>${m.top?.weight.toFixed(1)||0} %</b><span>${kind(m.top?.p||{})}</span></div><div><small>Risk multiplier</small><b>${m.top?.rf.toFixed(2)||'—'}×</b><span>heuristický koeficient</span></div></div><div class="os115-list">${m.rows.slice(0,8).map((r,i)=>`<div class="os115-row"><div class="os115-rank">${i+1}</div><div><b>${h(r.p.ticker||'—')}</b><small>${h(kind(r.p))} · váha ${r.weight.toFixed(1)} % · P/L ${N(r.p.net_profit_pct).toFixed(1)} %</small></div><div class="os115-meter"><i style="width:${Math.min(100,r.riskShare)}%"></i></div><strong>${r.riskShare.toFixed(1)} %</strong></div>`).join('')}</div><div class="os115-note">Risk budget ukazuje <b>relativní příspěvek</b> jednotlivých pozic v rámci aktuálně importovaného XTB portfolia. Pro skutečný statistický risk model budeme později potřebovat cenovou historii a korelace.</div>`;const anchor=root.querySelector('.os114')||root.querySelector('.os113');anchor?.after(sec);window.__KAMIL_OS115__={at:Date.now(),top3:m.top3,concentration:m.concentration,positions:m.rows.length}}
export function enhanceOS115(){mount()}
