import {store} from './state.js';
import {xtbPositions} from './decision24.js';
import {h} from './utils.js';
const N=v=>Number(v||0),U=v=>String(v||'').toUpperCase();
const val=p=>N(p.value||p.marketValue||0);
const KEY='kamil-os-target-allocation-113';
function targets(ps){let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{};const total=ps.reduce((a,p)=>a+val(p),0)||1;if(!Object.keys(saved).length)return Object.fromEntries(ps.map(p=>[String(p.ticker),val(p)/total*100]));const sum=Object.values(saved).reduce((a,v)=>a+N(v),0)||1;return Object.fromEntries(Object.entries(saved).map(([k,v])=>[k,N(v)/sum*100]))}
function classify(p){const text=U(`${p.name||''} ${p.sector||''} ${p.industry||''} ${p.category||''}`);return{usd:U(p.currency||p.accountCurrency)==='USD',tech:/TECH|SOFTWARE|SEMICONDUCT|NASDAQ|INTERNET|AI|CLOUD/.test(text),etf:U(p.category)==='ETF'}}
function shockPct(p){const c=classify(p);return (c.tech?-18:-8)+(c.usd?-8:0)}
function build(){const ps=xtbPositions(store.get()).filter(p=>val(p)>0),total=ps.reduce((a,p)=>a+val(p),0)||1,t=targets(ps),deposit=N(store.get()?.financePlan?.plannedInvestment)||25000;const rows=ps.map(p=>{const weight=val(p)/total*100,target=N(t[p.ticker]),gap=target-weight,shock=shockPct(p),loss=val(p)*shock/100;let action='DRŽET';if(gap<-2.5&&Math.abs(shock)>=16)action='NEPŘIKUPOVAT';else if(gap>2&&Math.abs(shock)<=12)action='PODPOŘIT VKLADEM';else if(gap<-4)action='REDUKOVAT PŘI REBALANCINGU';return{p,weight,target,gap,shock,loss,action}});const currentLoss=rows.reduce((a,r)=>a+r.loss,0),support=rows.filter(r=>r.action==='PODPOŘIT VKLADEM').sort((a,b)=>b.gap-a.gap),risk=rows.filter(r=>r.action!=='PODPOŘIT VKLADEM').sort((a,b)=>Math.abs(b.loss)-Math.abs(a.loss));let remaining=deposit;for(const r of support){r.add=Math.max(0,Math.min(remaining,deposit*(Math.max(0,r.gap)/Math.max(1,support.reduce((a,x)=>a+Math.max(0,x.gap),0)))));remaining-=r.add}const defendedLoss=currentLoss+support.reduce((a,r)=>a+(r.add||0)*r.shock/100,0);return{rows:[...support,...risk],currentLoss,defendedLoss,deposit,total}}
function mount(){const root=document.querySelector('.dashboard110');if(!root||root.querySelector('.os119'))return;const m=build();if(!m.rows.length)return;const sec=document.createElement('section');sec.className='os119 d110-card';sec.innerHTML=`<div class="os119-head"><div><div class="eyebrow">XTB · PORTFOLIO DEFENSE PLAN</div><h2>Jak snížit citlivost portfolia</h2><p>OS kombinuje cílové váhy, nový vklad a kombinovaný stress scénář z OS 118. Neprovádí žádné obchody.</p></div><div class="os119-kpi"><small>Stress loss nyní</small><b>${Math.round(m.currentLoss).toLocaleString('cs-CZ')} Kč</b><span>kombinovaný risk-off</span></div></div><div class="os119-grid"><article><small>Nový vklad</small><b>${Math.round(m.deposit).toLocaleString('cs-CZ')} Kč</b><span>pouze orientační rozdělení</span></article><article><small>Stress loss po navrženém vkladu</small><b>${Math.round(m.defendedLoss).toLocaleString('cs-CZ')} Kč</b><span>${m.defendedLoss>m.currentLoss?'riziko roste':'riziko klesá nebo zůstává podobné'}</span></article><article><small>Rozdíl</small><b>${Math.round(m.defendedLoss-m.currentLoss).toLocaleString('cs-CZ')} Kč</b><span>mechanický scénář</span></article></div><div class="os119-list">${m.rows.slice(0,10).map(r=>`<div class="os119-row"><div><b>${h(r.p.ticker||'—')}</b><small>váha ${r.weight.toFixed(1)} % · cíl ${r.target.toFixed(1)} % · stress ${r.shock.toFixed(0)} %</small></div><strong class="${r.action==='PODPOŘIT VKLADEM'?'good':r.action==='NEPŘIKUPOVAT'?'warn':''}">${h(r.action)}</strong><span>${r.add?`+${Math.round(r.add).toLocaleString('cs-CZ')} Kč z nového vkladu`:`stress dopad ${Math.round(r.loss).toLocaleString('cs-CZ')} Kč`}</span></div>`).join('')}</div><div class="os119-note">Defense Plan je ochranná vrstva nad cílovými váhami. `NEPŘIKUPOVAT` neznamená automaticky prodat; znamená jen neposílat do dané pozice nový kapitál, dokud je převažená a současně citlivá na zvolený stress scénář.</div>`;const anchor=root.querySelector('.os118')||root.querySelector('.os117');anchor?.after(sec);window.__KAMIL_OS119__={at:Date.now(),currentLoss:m.currentLoss,defendedLoss:m.defendedLoss,deposit:m.deposit}}
export function enhanceOS119(){mount()}
