import {store} from './state.js';
import {xtbPositions} from './decision24.js';
import {h} from './utils.js';
const N=v=>Number(v||0),A=v=>Array.isArray(v)?v:[];
const KEY='kamil-os-target-allocation-113';
function val(p){return N(p.value||p.marketValue||0)}
function rows(){const ps=xtbPositions(store.get()).filter(p=>val(p)>0),total=ps.reduce((a,p)=>a+val(p),0);return ps.map(p=>({ticker:String(p.ticker||'—'),value:val(p),actual:total?val(p)/total*100:0}))}
function loadTargets(rs){let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{};const has=Object.keys(saved).length>0;if(!has)return Object.fromEntries(rs.map(r=>[r.ticker,Number(r.actual.toFixed(2))]));return saved}
function saveTargets(t){localStorage.setItem(KEY,JSON.stringify(t))}
function normalize(t){const sum=Object.values(t).reduce((a,v)=>a+N(v),0)||1;return Object.fromEntries(Object.entries(t).map(([k,v])=>[k,N(v)/sum*100]))}
function rebalance(rs,t,deposit=25000){const total=rs.reduce((a,r)=>a+r.value,0),after=total+deposit;return rs.map(r=>{const target=N(t[r.ticker]),targetValue=after*target/100,gap=targetValue-r.value;return{...r,target,gap}}).sort((a,b)=>b.gap-a.gap)}
function fmt(v){return Math.round(v).toLocaleString('cs-CZ')}
function mount(){const root=document.querySelector('.dashboard110');if(!root||root.querySelector('.os113'))return;const rs=rows();if(!rs.length)return;let targets=normalize(loadTargets(rs)),deposit=N(store.get()?.financePlan?.plannedInvestment)||25000,plan=rebalance(rs,targets,deposit);const sec=document.createElement('section');sec.className='os113 d110-card';sec.innerHTML=`<div class="os113-head"><div><div class="eyebrow">XTB · TARGET VS. ACTUAL</div><h2>Rebalancing Center</h2><p>Cílové váhy si nastavíš sám; OS jen ukáže odchylku a rozdělení nového vkladu.</p></div><div class="os113-deposit"><span>Nový vklad</span><input data-deposit type="number" min="0" step="1000" value="${deposit}"><b>Kč</b></div></div><div class="os113-table"><div class="os113-th"><span>Pozice</span><span>Aktuálně</span><span>Cíl</span><span>Odchylka</span><span>Návrh z vkladu</span></div>${plan.map(x=>`<div class="os113-tr" data-ticker="${h(x.ticker)}"><b>${h(x.ticker)}</b><span>${x.actual.toFixed(1)} %</span><span><input data-target type="number" min="0" max="100" step="0.5" value="${x.target.toFixed(1)}"> %</span><span class="${x.actual>x.target?'over':'under'}">${(x.actual-x.target)>=0?'+':''}${(x.actual-x.target).toFixed(1)} p. b.</span><b class="${x.gap>0?'buy':''}">${x.gap>0?`${fmt(Math.min(x.gap,deposit))} Kč`:'0 Kč'}</b></div>`).join('')}</div><div class="os113-actions"><button class="btn" data-reset>Srovnat cíle s dneškem</button><button class="btn primary" data-save>Uložit cílové váhy</button></div><div class="os113-import"><div><b>XTB Import Center</b><small>Aktuálně používám poslední XTB data uložená v OS. Nový export načti přes sekci Peníze; tady po importu hned uvidíš nové váhy a odchylky.</small></div><button class="btn" data-money>Otevřít Peníze →</button></div>`;const anchor=root.querySelector('.d110-grid-mid')||root.querySelector('.d110-bottom');anchor?.before(sec);function readTargets(){const o={};sec.querySelectorAll('.os113-tr').forEach(r=>o[r.dataset.ticker]=N(r.querySelector('[data-target]')?.value));return normalize(o)}sec.querySelector('[data-save]')?.addEventListener('click',()=>{saveTargets(readTargets());sec.remove();mount()});sec.querySelector('[data-reset]')?.addEventListener('click',()=>{localStorage.removeItem(KEY);sec.remove();mount()});sec.querySelector('[data-deposit]')?.addEventListener('change',e=>{store.get().financePlan=store.get().financePlan||{};store.get().financePlan.plannedInvestment=N(e.target.value);sec.remove();mount()});sec.querySelector('[data-money]')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:'money'})));window.__KAMIL_OS113__={at:Date.now(),targets,deposit,positions:rs.length}}
export function enhanceOS113(){mount()}
