import {store} from './state.js';
import {xtbPositions} from './decision24.js';
import {loadTicketCloud660} from './ticketCloud660.js';
import {h} from './utils.js';
const A=v=>Array.isArray(v)?v:[],N=v=>Number(v||0),DAY=86400000;
function daysUntil(v){if(!v)return null;const d=new Date(v);if(!Number.isFinite(d.getTime()))return null;return Math.ceil((d-Date.now())/DAY)}
function taskSignals(){const s=store.get(),out=[];for(const x of A(s.tasks)){if(['DONE','CLOSED','ARCHIVED'].includes(String(x.status||'').toUpperCase()))continue;const d=daysUntil(x.due||x.date||x.deadline);if(d===null)continue;if(d<0)out.push({score:98,type:'LIFE ADMIN',title:x.title||x.name||'Úkol po termínu',detail:`Po termínu ${Math.abs(d)} dní`,target:'.os112'});else if(d<=2)out.push({score:88-d,type:'LIFE ADMIN',title:x.title||x.name||'Blízký termín',detail:d===0?'Dnes':`Za ${d} dny`,target:'.os112'})}return out}
function xtbSignals(){const out=[];for(const p of xtbPositions(store.get())){const pl=N(p.net_profit_pct),earn=daysUntil(p.earningsDate||p.nextEarnings||p.earnings_date);if(earn!==null&&earn>=0&&earn<=7)out.push({score:92-earn,type:'XTB · EARNINGS',title:p.ticker||p.name||'Pozice',detail:earn===0?'Výsledky dnes':`Výsledky za ${earn} dní`,target:'.os121'});if(pl<=-12)out.push({score:80+Math.min(15,Math.abs(pl)-12),type:'XTB · RISK',title:p.ticker||p.name||'Pozice',detail:`P/L ${pl.toFixed(1)} % · ověřit tezi`,target:'.os120:not(.os120-exec)'})}return out}
async function ticketSignals(){const out=[];try{const c=await loadTicketCloud660();if(!c?.ok)return out;for(const x of A(c.inventory)){if(!['LISTED','NOT_LISTED'].includes(x.market_status))continue;const d=daysUntil(x.event_date);if(d===null||d<0)continue;const market=N(x.market_price||x.sector_price),ask=N(x.listing_price||x.ask_price);let score=d<=3?94:d<=7?86:d<=14?76:0;if(market&&ask>market*1.15)score+=8;if(score)out.push({score,type:'TICKETS',title:x.event_name||'Událost',detail:`${d===0?'Dnes':`Za ${d} dní`}${market&&ask?` · cena ${Math.round((ask/market-1)*100)} % nad trhem`:''}`,target:'.d110-tickets'})}}catch{}return out}
function jump(root,target){const n=root.querySelector(target);if(!n)return;const body=n.closest('.os122-body');if(body?.hidden){body.hidden=false;const t=body.parentElement?.querySelector('.os122-toggle');if(t){t.setAttribute('aria-expanded','true');const b=t.querySelector('b');if(b)b.textContent='−'}}n.scrollIntoView({behavior:'smooth',block:'start'})}
function render(root,signals){root.querySelector('.os124')?.remove();const top=signals.sort((a,b)=>b.score-a.score).slice(0,3),sec=document.createElement('section');sec.className='os124';sec.innerHTML=`<div class="os124-head"><div><div class="eyebrow">SMART HOME</div><h2>Co si dnes zaslouží pozornost</h2><small>Automaticky podle termínů, earnings, risku a ticketů.</small></div><span>${top.length?`${top.length} priority`:'klidný režim'}</span></div><div class="os124-grid">${top.length?top.map((x,i)=>`<article><small>#${i+1} · ${h(x.type)}</small><b>${h(x.title)}</b><span>${h(x.detail)}</span><button data-target="${h(x.target)}">Otevřít</button></article>`).join(''):'<div class="os124-empty">Teď není žádný silný urgentní signál. OS nechává nahoře tvoje ručně připnuté Moje Dnes.</div>'}</div>`;const anchor=root.querySelector('.os123')||root.querySelector('.os122-toolbar')||root.querySelector('.os120-exec');anchor?.after(sec);sec.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>jump(root,b.dataset.target));window.__KAMIL_OS124__={at:Date.now(),signals:top}}
export async function enhanceOS124(){const root=document.querySelector('.dashboard110');if(!root||root.querySelector('.os124'))return;const signals=[...taskSignals(),...xtbSignals(),...(await ticketSignals())];render(root,signals)}
