import {store} from './state.js';
import {xtbPositions} from './decision24.js';
import {quoteSymbolForPosition32} from './marketQuote32.js';
import {h} from './utils.js';
const A=v=>Array.isArray(v)?v:[],N=v=>Number(v||0),U=v=>String(v||'').toUpperCase(),DAY=86400000;
const THESIS='kamil-os-theses-120',NW='kamil-os-networth-120',WHIST='kamil-os-wealth-history-121';
const val=p=>N(p.value||p.marketValue||0);
function load(k,d={}){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function positions(){return xtbPositions(store.get()).filter(p=>val(p)>0)}
async function history(ps){const symbols=[...new Set(ps.map(quoteSymbolForPosition32).filter(Boolean))];if(!symbols.length)return new Map();try{const r=await fetch(`/api/market-history?symbols=${encodeURIComponent(symbols.join(','))}&range=1y`,{cache:'no-store'}),j=await r.json();return new Map(A(j?.series).map(s=>[U(s.symbol),s]))}catch{return new Map()}}
function dd(points){const a=A(points).map(x=>N(x.p)).filter(x=>x>0);if(!a.length)return null;const peak=Math.max(...a),last=a[a.length-1];return{peak,last,drawdown:(last/peak-1)*100}}
function earnings(p){const raw=p.earningsDate||p.nextEarnings||p.earnings_at||p.next_earnings_at;if(!raw)return null;const t=new Date(raw).getTime();if(!Number.isFinite(t))return null;return{t,days:Math.ceil((t-Date.now())/DAY)}}
function wealthSnapshot(ps){const nw=load(NW,{cash:0,property:0,debt:0,other:0}),xtb=ps.reduce((a,p)=>a+val(p),0),net=xtb+N(nw.cash)+N(nw.property)+N(nw.other)-N(nw.debt),hist=load(WHIST,[]),month=new Date().toISOString().slice(0,7),existing=hist.find(x=>x.month===month);if(!existing){hist.push({month,net,xtb,cash:N(nw.cash),property:N(nw.property),debt:N(nw.debt),other:N(nw.other),at:Date.now()});save(WHIST,hist.slice(-24))}const prev=hist.filter(x=>x.month<month).sort((a,b)=>String(b.month).localeCompare(String(a.month)))[0];return{net,prev,delta:prev?net-N(prev.net):null}}
function mount(root,ps,series){const theses=load(THESIS,{}),wealth=wealthSnapshot(ps),rows=ps.map(p=>{const sym=U(quoteSymbolForPosition32(p)),d=dd(series.get(sym)?.points),th=theses[p.ticker],age=th?.at?Math.floor((Date.now()-th.at)/DAY):null,e=earnings(p);return{p,d,th,age,e}}).sort((a,b)=>(a.d?.drawdown??0)-(b.d?.drawdown??0));const sec=document.createElement('section');sec.className='os121 d110-card';sec.innerHTML=`<div class="os121-head"><div><div class="eyebrow">OS 121 · DATA AWARENESS</div><h2>Drawdown, earnings a stáří investiční teze</h2><p>Historický drawdown vychází z dostupné roční cenové historie. Earnings se zobrazí jen pokud máme skutečné datum v importovaných datech.</p></div><div class="os121-wealth"><small>Měsíční wealth delta</small><b>${wealth.delta===null?'čeká na další měsíc':`${wealth.delta>=0?'+':''}${Math.round(wealth.delta).toLocaleString('cs-CZ')} Kč`}</b><span>aktuální net worth ${Math.round(wealth.net).toLocaleString('cs-CZ')} Kč</span></div></div><div class="os121-table"><div class="os121-th"><span>Pozice</span><span>Drawdown od 1Y maxima</span><span>Earnings</span><span>Teze</span></div>${rows.slice(0,12).map(r=>`<div class="os121-tr"><div><b>${h(r.p.ticker||'—')}</b><small>${h(r.p.name||'')}</small></div><strong class="${r.d&&r.d.drawdown<-15?'bad':''}">${r.d?`${r.d.drawdown.toFixed(1)} %`:'čeká na historii'}</strong><span>${r.e?(r.e.days>=0?`za ${r.e.days} dní`:`před ${Math.abs(r.e.days)} dny`):'čeká na data'}</span><span>${r.age===null?'teze není zapsaná':r.age>=90?`REVIEW · ${r.age} dní`:`${r.age} dní`}</span></div>`).join('')}</div><div class="os121-note">Thesis review je označen jako REVIEW po 90 dnech. Earnings awareness nic neodhaduje: bez skutečného data z importu/API zůstává stav „čeká na data“.</div>`;const anchor=root.querySelector('.os120.d110-card:last-of-type')||root.querySelector('.os120-exec');anchor?.after(sec);window.__KAMIL_OS121__={at:Date.now(),positions:rows.length,wealthDelta:wealth.delta}}
export async function enhanceOS121(){const root=document.querySelector('.dashboard110');if(!root||root.querySelector('.os121'))return;const ps=positions();if(!ps.length)return;mount(root,ps,await history(ps))}
