import {loadTicketCloud660} from './ticketCloud660.js';
import {cloudClient,session} from './cloud.js';
import {h} from './utils.js';
const A=v=>Array.isArray(v)?v:[],N=v=>Number(v||0);
const stages=[
 {code:'SOLD_UNDELIVERED',label:'PRODÁNO / DORUČIT',next:'SOLD_WAITING_PAYMENT',nextLabel:'Označit jako doručeno'},
 {code:'SOLD_WAITING_PAYMENT',label:'DORUČENO / ČEKÁ NA PAYOUT',next:'PAYOUT_RECEIVED',nextLabel:'Označit jako vyplaceno'},
 {code:'PAYOUT_RECEIVED',label:'VYPLACENO',next:null,nextLabel:null}
];
function stage(s){return stages.find(x=>x.code===String(s||'').toUpperCase())||stages[0]}
async function advance(id,next){const c=await cloudClient(),sess=await session();if(!c||!sess)return{ok:false,reason:'NO_SESSION'};const {error}=await c.from('ticket_inventory').update({market_status:next,updated_at:new Date().toISOString()}).eq('user_id',sess.user.id).eq('id',id);return error?{ok:false,error}:{ok:true}}
function totals(rows){return{undel:rows.filter(x=>x.market_status==='SOLD_UNDELIVERED').reduce((a,x)=>a+N(x.qty),0),waiting:rows.filter(x=>x.market_status==='SOLD_WAITING_PAYMENT').reduce((a,x)=>a+N(x.sell_total_czk),0),paid:rows.filter(x=>x.market_status==='PAYOUT_RECEIVED').reduce((a,x)=>a+N(x.sell_total_czk),0)}}
export async function enhanceOS127(){const root=document.querySelector('.dashboard110');if(!root||root.querySelector('.os127'))return;let c;try{c=await loadTicketCloud660()}catch{return}if(!c?.ok)return;const rows=A(c.inventory).filter(x=>['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED'].includes(String(x.market_status||'').toUpperCase()));if(!rows.length)return;const t=totals(rows),sec=document.createElement('section');sec.className='os127 d110-card';sec.innerHTML=`<div class="os127-head"><div><div class="eyebrow">TICKETS · DELIVERY & PAYOUT</div><h2>Prodané vstupenky až do peněz na účtu</h2><p>Každý prodej má jasný další krok. Změna stavu se zapisuje přímo do ticket evidence.</p></div><div class="os127-flow"><span>PRODÁNO</span><i>→</i><span>DORUČENO</span><i>→</i><span>PAYOUT</span></div></div><div class="os127-kpis"><article><small>Doručit</small><b>${t.undel} ks</b></article><article><small>Čeká na payout</small><b>${Math.round(t.waiting).toLocaleString('cs-CZ')} Kč</b></article><article><small>Vyplaceno</small><b>${Math.round(t.paid).toLocaleString('cs-CZ')} Kč</b></article></div><div class="os127-list">${rows.slice().sort((a,b)=>String(b.updated_at||'').localeCompare(String(a.updated_at||''))).map(x=>{const s=stage(x.market_status);return`<div class="os127-row" data-ticket="${h(x.id)}"><div><b>${h(x.event_name||'Událost')}</b><small>${h(x.section||'')} · ${N(x.qty)} ks · ${Math.round(N(x.sell_each_czk)).toLocaleString('cs-CZ')} Kč/ks</small></div><strong>${h(s.label)}</strong>${s.next?`<button data-next="${s.next}">${h(s.nextLabel)}</button>`:'<span class="done">Hotovo</span>'}</div>`}).join('')}</div>`;const anchor=root.querySelector('.os126')||root.querySelector('.d110-tickets');anchor?.after(sec);sec.querySelectorAll('[data-next]').forEach(btn=>btn.onclick=async()=>{const row=btn.closest('[data-ticket]'),id=row?.dataset.ticket,next=btn.dataset.next;if(!id||!next)return;btn.disabled=true;btn.textContent='Ukládám…';const r=await advance(id,next);if(!r.ok){btn.disabled=false;btn.textContent='Chyba — zkusit znovu';return}sec.remove();document.querySelector('.os126')?.remove();await enhanceOS127();try{const m=await import('./os126.js');await m.enhanceOS126()}catch{}});window.__KAMIL_OS127__={at:Date.now(),tickets:rows.length,...t}}
