const KEY='kamil-os-pins-123';
const MAX=5;
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')||[]}catch{return[]}}
function save(v){localStorage.setItem(KEY,JSON.stringify(v))}
function labelFor(node){return node.querySelector('.eyebrow')?.textContent?.trim()||node.querySelector('h2')?.textContent?.trim()||node.dataset.group||'Panel'}
function idFor(node,i){if(node.dataset.pinId)return node.dataset.pinId;const cls=[...node.classList].find(c=>/^os\d+/.test(c)||c.startsWith('d110-'))||'panel';node.dataset.pinId=`${cls}-${i}`;return node.dataset.pinId}
function candidates(root){const out=[];let i=0;for(const n of root.querySelectorAll('.os122-body > section,.os122-body > .d110-card,.os120-exec,.os112-exec,.d110-card')){if(n.closest('.os123')||n.classList.contains('os122-toolbar')||n.classList.contains('os122-group'))continue;const id=idFor(n,i++);if(!out.some(x=>x.id===id))out.push({id,node:n,label:labelFor(n)})}return out}
function modal(root,items,pins,onApply){document.querySelector('.os123-modal')?.remove();const m=document.createElement('div');m.className='os123-modal';m.innerHTML=`<div class="os123-dialog"><div class="os123-head"><div><div class="eyebrow">MOJE DNES</div><h2>Připnout panely nahoru</h2><p>Vyber maximálně ${MAX} panelů. Výpočty ani data se nemění.</p></div><button data-close>×</button></div><div class="os123-options">${items.map(x=>`<label><input type="checkbox" value="${x.id}" ${pins.includes(x.id)?'checked':''}><span>${x.label}</span></label>`).join('')}</div><div class="os123-actions"><button data-cancel>Zrušit</button><button class="primary" data-save>Uložit</button></div></div>`;document.body.appendChild(m);const close=()=>m.remove();m.querySelector('[data-close]').onclick=close;m.querySelector('[data-cancel]').onclick=close;m.onclick=e=>{if(e.target===m)close()};m.querySelector('[data-save]').onclick=()=>{const chosen=[...m.querySelectorAll('input:checked')].map(x=>x.value).slice(0,MAX);save(chosen);close();onApply(chosen)}}
function renderPinned(root,items,pins){root.querySelector('.os123')?.remove();const sec=document.createElement('section');sec.className='os123';sec.innerHTML=`<div class="os123-title"><div><div class="eyebrow">MOJE DNES</div><h2>Připnuté panely</h2><small>${pins.length?`${pins.length}/${MAX} připnuto`:'Zatím nic nepřipnuto'}</small></div><button data-edit>Upravit</button></div><div class="os123-grid"></div>`;const grid=sec.querySelector('.os123-grid');for(const id of pins){const item=items.find(x=>x.id===id);if(!item)continue;const card=document.createElement('article');card.className='os123-pin';const title=item.label,summary=item.node.querySelector('h2')?.textContent?.trim()||item.node.querySelector('b')?.textContent?.trim()||title;card.innerHTML=`<div><small>${title}</small><b>${summary}</b></div><button data-jump="${id}">Otevřít</button>`;grid.appendChild(card)}if(!grid.children.length)grid.innerHTML='<div class="os123-empty">Vyber 3–5 panelů, které chceš vidět hned po otevření OS.</div>';const anchor=root.querySelector('.os122-toolbar')||root.querySelector('.os120-exec')||root.querySelector('.d110-head');anchor?.after(sec);sec.querySelector('[data-edit]').onclick=()=>modal(root,items,pins,p=>renderPinned(root,items,p));sec.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{const item=items.find(x=>x.id===b.dataset.jump);if(!item)return;const body=item.node.closest('.os122-body');if(body?.hidden){body.hidden=false;const t=body.parentElement?.querySelector('.os122-toggle');if(t){t.setAttribute('aria-expanded','true');const icon=t.querySelector('b');if(icon)icon.textContent='−'}}item.node.scrollIntoView({behavior:'smooth',block:'start'});item.node.classList.add('os123-flash');setTimeout(()=>item.node.classList.remove('os123-flash'),1400)})}
export function enhanceOS123(){const root=document.querySelector('.dashboard110');if(!root||root.querySelector('.os123'))return;const items=candidates(root),pins=load().filter(id=>items.some(x=>x.id===id)).slice(0,MAX);renderPinned(root,items,pins);window.__KAMIL_OS123__={at:Date.now(),pins}}
