import {store} from './state.js';
import {xtbPositions} from './decision24.js';
import {loadTicketCloud660} from './ticketCloud660.js';
import {h} from './utils.js';
const A=v=>Array.isArray(v)?v:[],N=v=>Number(v||0),DAY=86400000;
function tasks(){return A(store.get().tasks).filter(x=>!['DONE','CLOSED','ARCHIVED'].includes(String(x.status||'').toUpperCase())).map(x=>({...x,ts:new Date(x.due||x.date||x.deadline||0).getTime()})).filter(x=>x.ts).sort((a,b)=>a.ts-b.ts)}
function xtb(){return xtbPositions(store.get()).filter(p=>N(p.net_profit_pct)<=-10).sort((a,b)=>N(a.net_profit_pct)-N(b.net_profit_pct)).slice(0,2)}
async function tickets(){try{const c=await loadTicketCloud660();if(!c?.ok)return[];return A(c.inventory).filter(x=>['LISTED','NOT_LISTED'].includes(x.market_status)&&x.event_date).map(x=>({...x,days:Math.ceil((new Date(x.event_date)-Date.now())/DAY)})).filter(x=>x.days>=0&&x.days<=7).sort((a,b)=>a.days-b.days).slice(0,2)}catch{return[]}}
export async function enhanceOS125(){const root=document.querySelector('.dashboard110');if(!root||root.querySelector('.os125'))return;const ts=tasks(),xs=xtb(),tk=await tickets(),items=[];for(const x of ts.slice(0,2)){const d=Math.ceil((x.ts-Date.now())/DAY);items.push({score:d<0?100:d<=1?90:70,title:x.title||x.name||'Úkol',why:d<0?'po termínu':d===0?'dnes':`za ${d} dní`,target:'.os112'})}for(const p of xs)items.push({score:78+Math.min(20,Math.abs(N(p.net_profit_pct))),title:`XTB ${p.ticker}`,why:`P/L ${N(p.net_profit_pct).toFixed(1)} % — ověřit tezi`,target:'.os120'});for(const x of tk)items.push({score:85-x.days,title:x.event_name||'Vstupenka',why:x.days===0?'event dnes':`event za ${x.days} dní`,target:'.d110-tickets'});items.sort((a,b)=>b.score-a.score);const top=items.slice(0,3),sec=document.createElement('section');sec.className='os125';const sentence=top.length?`Dnes řeš hlavně ${top.map(x=>x.title).join(', ')}. ${items.length>top.length?'Ostatní může počkat.':'Nic dalšího teď nemá vyšší prioritu.'}`:'Dnes není žádný silný urgentní signál. Můžeš se soustředit na běžný plán.';sec.innerHTML=`<div><div class="eyebrow">OS 125 · DAILY BRIEFING</div><h2>${h(sentence)}</h2><p>Automaticky složeno z termínů, XTB rizik a blížících se ticket eventů.</p></div><div class="os125-items">${top.map((x,i)=>`<button data-target="${h(x.target)}"><span>${i+1}</span><b>${h(x.title)}</b><small>${h(x.why)}</small></button>`).join('')}</div>`;const anchor=root.querySelector('.os124')||root.querySelector('.os123')||root.querySelector('.os120-exec')||root.querySelector('.d110-head');anchor?.after(sec);sec.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{const el=root.querySelector(b.dataset.target);const body=el?.closest('.os122-body');if(body)body.hidden=false;el?.scrollIntoView({behavior:'smooth',block:'start'})});window.__KAMIL_OS125__={at:Date.now(),priorities:top.length}}
