import {store} from './state.js';
import {xtbPositions} from './decision24.js';
import {loadTicketCloud660} from './ticketCloud660.js';
import {h} from './utils.js';
const N=v=>Number(v||0),A=v=>Array.isArray(v)?v:[],U=v=>String(v||'').toUpperCase(),DAY=86400000;
const val=p=>N(p.value||p.marketValue||0), TKEY='kamil-os-target-allocation-113', THESIS='kamil-os-theses-120', HIST='kamil-os-decision-history-120', NW='kamil-os-networth-120';
function targets(ps){let x={};try{x=JSON.parse(localStorage.getItem(TKEY)||'{}')||{}}catch{};const total=ps.reduce((a,p)=>a+val(p),0)||1;if(!Object.keys(x).length)return Object.fromEntries(ps.map(p=>[p.ticker,val(p)/total*100]));return x}
function load(k,d={}){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function positions(){return xtbPositions(store.get()).filter(p=>val(p)>0)}
function action(p,total,t){const w=val(p)/total*100,g=N(t[p.ticker])-w,pl=N(p.net_profit_pct);if(g>2.5&&pl>-18)return'PŘIKOUPIT';if(g<-4)return'REDUKOVAT';if(pl<-12)return'OVĚŘIT';return'DRŽET'}
function execModel(){const ps=positions(),total=ps.reduce((a,p)=>a+val(p),0)||1,t=targets(ps),rows=ps.map(p=>({p,w:val(p)/total*100,g:N(t[p.ticker])-val(p)/total*100,a:action(p,total,t)}));const buy=rows.filter(r=>r.a==='PŘIKOUPIT').sort((a,b)=>b.g-a.g)[0],risk=rows.filter(r=>['OVĚŘIT','REDUKOVAT'].includes(r.a)).sort((a,b)=>N(a.p.net_profit_pct)-N(b.p.net_profit_pct))[0];return{ps,total,rows,buy,risk}}
function recovery(pl){return pl<0?(-pl/(100+pl)*100):0}
function mountExecutive(root,m){const sec=document.createElement('section');sec.className='os120 os120-exec';sec.innerHTML=`<div><div class="eyebrow">OS 120 · EXECUTIVE SUMMARY</div><h2>Dnešní rozhodovací centrum</h2></div><div class="os120-kpis"><article><small>Nový kapitál</small><b>${m.buy?h(m.buy.p.ticker):'ČEKAT'}</b><span>${m.buy?`pod cílem o ${m.buy.g.toFixed(1)} p.b.`:'bez silného kandidáta'}</span></article><article><small>Největší pozornost</small><b>${m.risk?h(m.risk.p.ticker):'KLID'}</b><span>${m.risk?h(m.risk.a):'bez červeného signálu'}</span></article><article><small>Portfolio</small><b>${Math.round(m.total).toLocaleString('cs-CZ')} Kč</b><span>${m.ps.length} aktivních pozic</span></article><article><small>Verdikty</small><b>${m.rows.filter(x=>x.a!=='DRŽET').length}</b><span>vyžadují akci / kontrolu</span></article></div>`;root.querySelector('.d110-head')?.after(sec)}
function mountInvestment(root,m){const theses=load(THESIS,{}),hist=load(HIST,{});const sec=document.createElement('section');sec.className='os120 d110-card';sec.innerHTML=`<div class="eyebrow">XTB · DECISION DISCIPLINE</div><h2>Teze, drawdown a disciplína prodeje</h2><div class="os120-table">${m.rows.slice(0,10).map(r=>{const pl=N(r.p.net_profit_pct),rec=recovery(pl),th=theses[r.p.ticker];const old=hist[r.p.ticker],changed=old&&old.action!==r.a;hist[r.p.ticker]={action:r.a,at:Date.now()};return`<div class="os120-row"><div><b>${h(r.p.ticker)}</b><small>${changed?`ZMĚNA ${h(old.action)} → ${h(r.a)}`:h(r.a)}</small></div><div><small>P/L</small><b>${pl.toFixed(1)} %</b></div><div><small>Recovery needed</small><b>${rec?`+${rec.toFixed(1)} %`:'—'}</b></div><div><small>Investiční teze</small><b>${th?h(th.text):'Není zapsaná'}</b></div><button data-thesis="${h(r.p.ticker)}">${th?'Upravit':'Zapsat tezi'}</button></div>`}).join('')}</div><div class="os120-sell"><b>Sell Discipline</b><span><i>PRODAT</i> při porušení teze · <i>REDUKOVAT</i> kvůli převažení/koncentraci · <i>VYBRAT ZISK</i> jen podle předem definovaného pravidla, ne emocí.</span></div></section>`;save(HIST,hist);root.querySelector('.os119')?.after(sec);sec.querySelectorAll('[data-thesis]').forEach(b=>b.onclick=()=>{const ticker=b.dataset.thesis,old=theses[ticker]?.text||'',text=prompt(`Proč vlastníš ${ticker}?`,old);if(text?.trim()){theses[ticker]={text:text.trim(),at:Date.now()};save(THESIS,theses);sec.remove();mountInvestment(root,m)}})}
async function mountTickets(root){let inv=[];try{const c=await loadTicketCloud660();if(c?.ok)inv=A(c.inventory)}catch{};const active=inv.filter(x=>['LISTED','NOT_LISTED'].includes(x.market_status));if(!active.length)return;const sec=document.createElement('section');sec.className='os120 d110-card';sec.innerHTML=`<div class="eyebrow">TICKETS · CAPITAL EFFICIENCY</div><h2>Likvidita, sell probability a cenový plán</h2><div class="os120-ticketgrid">${active.slice(0,8).map(x=>{const buy=N(x.purchase_price||x.buy_price),ask=N(x.listing_price||x.ask_price),market=N(x.market_price||x.sector_price),days=x.event_date?Math.max(0,Math.ceil((new Date(x.event_date)-Date.now())/DAY)):null,margin=buy?((ask-buy)/buy*100):0,eff=days!==null&&days>0?margin/days:margin;let prob=50;if(market&&ask<=market*1.03)prob+=20;if(days!==null&&days<14)prob+=10;if(market&&ask>market*1.15)prob-=25;prob=Math.max(10,Math.min(90,prob));const ladder=ask&&days!==null?[ask,Math.max(buy,ask*.94),Math.max(buy,ask*.88)]:[];return`<article><b>${h(x.event_name||'Událost')}</b><small>${h(x.section||'')} · ${days===null?'bez data':`${days} dní`}</small><div><span>Sell probability</span><strong>${prob} %</strong></div><div><span>Capital efficiency</span><strong>${eff.toFixed(2)} %/den</strong></div><div><span>Price ladder</span><strong>${ladder.length?ladder.map(v=>Math.round(v).toLocaleString('cs-CZ')).join(' → '):'čeká na cenu'}</strong></div></article>`}).join('')}</div></section>`;(root.querySelector('.os120.d110-card')||root.querySelector('.os119'))?.after(sec)}
function mountWealth(root,m){const nw=load(NW,{cash:0,property:0,debt:0,other:0,last:null}),net=m.total+N(nw.cash)+N(nw.property)+N(nw.other)-N(nw.debt);const sec=document.createElement('section');sec.className='os120 d110-card';sec.innerHTML=`<div class="os120-head"><div><div class="eyebrow">WEALTH · LIFE ADMIN</div><h2>Net Worth & Life Radar</h2></div><button data-nw>Upravit majetek / dluhy</button></div><div class="os120-kpis"><article><small>Čisté jmění</small><b>${Math.round(net).toLocaleString('cs-CZ')} Kč</b><span>XTB + zadaný majetek − dluhy</span></article><article><small>XTB</small><b>${Math.round(m.total).toLocaleString('cs-CZ')} Kč</b></article><article><small>Cash</small><b>${Math.round(N(nw.cash)).toLocaleString('cs-CZ')} Kč</b></article><article><small>Dluhy</small><b>${Math.round(N(nw.debt)).toLocaleString('cs-CZ')} Kč</b></article></div><div class="os120-life"><b>Life Admin Radar</b><span>OS zvýrazňuje prošlé úkoly v Risk Monitoru; další krok je sjednotit sem práci, dokumenty, finance a rodinné termíny z existujících modulů.</span></div></section>`;root.appendChild(sec);sec.querySelector('[data-nw]').onclick=()=>{const cash=prompt('Cash / spoření v Kč',nw.cash),property=prompt('Nemovitosti / další majetek v Kč',nw.property),debt=prompt('Dluhy v Kč',nw.debt),other=prompt('Ostatní majetek v Kč',nw.other);save(NW,{cash:N(cash),property:N(property),debt:N(debt),other:N(other),last:Date.now()});sec.remove();mountWealth(root,m)}}
export async function enhanceOS120(){const root=document.querySelector('.dashboard110');if(!root||root.querySelector('.os120-exec'))return;const m=execModel();if(!m.ps.length)return;mountExecutive(root,m);mountInvestment(root,m);await mountTickets(root);mountWealth(root,m);window.__KAMIL_OS120__={at:Date.now(),positions:m.ps.length,total:m.total}}
