import {cloudClient,session} from './cloud.js';
import {h} from './utils.js';
const N=v=>Number(v||0),A=v=>Array.isArray(v)?v:[];
function pct(v){return `${(N(v)*100).toFixed(1)} %`}
function money(v){return `${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`}
function cls(v){v=String(v||'').toUpperCase();return v==='BUY'?'buy':v==='AVOID'?'avoid':'watch'}
function reason(x){const parts=[];parts.push(`${x.trades} obchodů`);parts.push(`ROI ${pct(x.roi)}`);parts.push(`win-rate ${pct(x.win_rate)}`);if(N(x.median_roi))parts.push(`medián ${pct(x.median_roi)}`);return parts.join(' · ')}
async function loadStats(){const c=await cloudClient(),sess=await session();if(!c||!sess)return{ok:false,rows:[]};const {data,error}=await c.from('ticket_strategy_stats').select('*').eq('user_id',sess.user.id);return error?{ok:false,error,rows:[]}:{ok:true,rows:data||[]}}
export async function enhanceOS129(){const root=document.querySelector('.dashboard110');if(!root||root.querySelector('.os129'))return;const r=await loadStats();if(!r.ok||!r.rows.length)return;const overall=r.rows.find(x=>x.stat_type==='OVERALL'),cats=r.rows.filter(x=>x.stat_type==='CATEGORY').sort((a,b)=>N(b.roi)-N(a.roi)),families=r.rows.filter(x=>x.stat_type==='FAMILY');const buy=families.filter(x=>x.verdict==='BUY').sort((a,b)=>(N(b.roi)*Math.log2(N(b.trades)+1))-(N(a.roi)*Math.log2(N(a.trades)+1))).slice(0,8),avoid=families.filter(x=>x.verdict==='AVOID').sort((a,b)=>N(a.roi)-N(b.roi)).slice(0,6),watch=families.filter(x=>x.verdict==='WATCH').sort((a,b)=>N(b.trades)-N(a.trades)).slice(0,6);const sec=document.createElement('section');sec.className='os129 d110-card';sec.innerHTML=`<div class="os129-head"><div><div class="eyebrow">TICKETS · STRATEGY ENGINE</div><h2>Co historicky kupovat, sledovat a čemu se vyhnout</h2><p>Verdikt vzniká jen ze segmentů s alespoň 5 realizovanými obchody. Účetní korekce, pokuty a zjevné reklamace jsou z trénovacího vzorku vyřazené.</p></div><div class="os129-base"><small>Validovaný vzorek</small><b>${N(overall?.trades)} obchodů</b><span>${money(overall?.profit_czk)} zisk · ROI ${pct(overall?.roi)}</span></div></div><div class="os129-cats">${cats.map(x=>`<article class="${cls(x.verdict)}"><small>${h(x.stat_key)}</small><b>${h(x.verdict)}</b><span>${reason(x)}</span></article>`).join('')}</div><div class="os129-columns"><article><h3>BUY · silná historie</h3>${buy.map(x=>`<div class="os129-row"><div><b>${h(x.stat_key)}</b><small>${reason(x)}</small></div><strong>${money(x.profit_czk)}</strong></div>`).join('')||'<small>Bez dostatečného vzorku.</small>'}</article><article><h3>WATCH · zajímavé, ale ne bez výhrad</h3>${watch.map(x=>`<div class="os129-row"><div><b>${h(x.stat_key)}</b><small>${reason(x)}</small></div><strong>${money(x.profit_czk)}</strong></div>`).join('')||'<small>Bez dostatečného vzorku.</small>'}</article><article><h3>AVOID · historie varuje</h3>${avoid.map(x=>`<div class="os129-row bad"><div><b>${h(x.stat_key)}</b><small>${reason(x)}</small></div><strong>${money(x.profit_czk)}</strong></div>`).join('')||'<small>Žádný segment nesplnil podmínky AVOID.</small>'}</article></div><div class="os129-note"><b>Jak číst verdikt:</b> BUY neznamená automaticky nakoupit další event. Znamená, že tento typ obchodu má v tvé vlastní historii dostatečný vzorek, pozitivní ROI a win-rate. Aktuální tržní cenu a likviditu musí pořád potvrdit live Ticket Radar.</div>`;const anchor=root.querySelector('.os128')||root.querySelector('.os127')||root.querySelector('.d110-tickets');anchor?.after(sec);window.__KAMIL_OS129__={at:Date.now(),sample:N(overall?.trades),buy:buy.length,watch:watch.length,avoid:avoid.length}}
