import {store} from './state.js';
import {cloudClient,session} from './cloud.js';
import {loadTicketCloud660} from './ticketCloud660.js';
import {unifiedCapitalState160} from './unifiedCapital160.js';
import {dataTrustState163} from './dataTrust163.js';
import {xtbBoard} from './live24.js';
import {h,money} from './utils.js';
const N=v=>Number(v||0),A=v=>Array.isArray(v)?v:[],U=v=>String(v||'').toUpperCase(),DAY=86400000;
const ACTIVE=new Set(['LISTED','NOT_LISTED']),SOLD=new Set(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID']);
const explicit=(...v)=>{for(const x of v.flat())if(x!==null&&x!==undefined&&x!==''&&Number.isFinite(Number(x))&&Number(x)>=0)return Number(x);return null};
const ageH=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?Math.max(0,(Date.now()-t)/36e5):null};
const days=(a,b)=>{const x=Date.parse(a||''),y=Date.parse(b||'');return Number.isFinite(x)&&Number.isFinite(y)?Math.max(1,(y-x)/DAY):null};
function cashGuard(s){const cash=explicit(s.financePlan?.freeCashCzk,s.financePlan?.availableCashCzk,s.money?.freeCashCzk,s.cash?.availableCzk),reserve=explicit(s.financePlan?.cashReserveCzk,s.financePlan?.minimumReserveCzk,s.money?.minimumReserveCzk);return{cash,reserve,deployable:cash===null?null:Math.max(0,cash-(reserve??0)),blocked:cash!==null&&reserve!==null&&cash<=reserve,explicitOnly:true}}
function ticketState(r){const st=U(r.market_status),buy=N(r.buy_total_czk),sell=N(r.sell_total_czk),p=Number(r.payout_received_czk),payoutKnown=Number.isFinite(p)&&p>0,net=payoutKnown?p-buy:null,hold=payoutKnown?days(r.imported_at,r.payout_recorded_at):null;return{r,st,buy,sell,payoutKnown,payout:payoutKnown?p:null,net,hold,active:ACTIVE.has(st),sold:SOLD.has(st)}}
async function ledger(){try{const c=await cloudClient(),sess=await session();if(!c||!sess)return[];const {data,error}=await c.from('xtb_transaction_ledger').select('*').eq('user_id',sess.user.id).order('occurred_at',{ascending:true}).limit(5000);return error?[]:A(data)}catch{return[]}}
async function priceJournal(ticketId=null){try{const c=await cloudClient(),sess=await session();if(!c||!sess)return[];let q=c.from('ticket_price_journal').select('*').eq('user_id',sess.user.id).order('changed_at',{ascending:false}).limit(500);if(ticketId)q=q.eq('ticket_id',ticketId);const {data,error}=await q;return error?[]:A(data)}catch{return[]}}
function ledgerStats(rows){let deposits=0,withdrawals=0,dividends=0,fees=0,sellProceeds=0;for(const x of rows){const t=U(x.transaction_type),net=N(x.net_amount||x.gross_amount);if(t==='DEPOSIT')deposits+=net;if(t==='WITHDRAWAL')withdrawals+=Math.abs(net);if(t==='DIVIDEND')dividends+=net;if(t==='FEE')fees+=Math.abs(net);if(t==='SELL')sellProceeds+=net}return{rows:rows.length,deposits,withdrawals,dividends,fees,sellProceeds,netFlow:deposits-withdrawals,realizedPl:null,realizedPlKnown:false}}
function eventTimeline(r,market=[],prices=[]){const e=[];if(r.imported_at)e.push({at:r.imported_at,label:'Evidováno / nákup'});for(const x of prices)e.push({at:x.changed_at,label:`Cena ${N(x.old_ask_czk)?money(x.old_ask_czk)+' → ':''}${money(x.new_ask_czk)}`});for(const x of market.slice(-8))e.push({at:x.checked_at,label:`Market ${money(x.market_price_czk||x.median_price_czk)}`});if(r.updated_at&&SOLD.has(U(r.market_status)))e.push({at:r.updated_at,label:'Poslední změna prodeje'});if(r.payout_recorded_at)e.push({at:r.payout_recorded_at,label:`Payout ${money(r.payout_received_czk)}`});return e.filter(x=>Date.parse(x.at)).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at))}
function quality(r,s){let score=0,reasons=[];const a=ageH(s?.checked_at);if(N(s?.market_price_czk)){score+=25}else reasons.push('bez market ceny');if(a!==null&&a<=6)score+=25;else if(a!==null&&a<=24)score+=15;else reasons.push('stará/neznámá cena');if(N(s?.same_section_count)){score+=20}else reasons.push('bez sektorové shody');if(N(s?.multi_market_confidence)>=65)score+=20;else if(N(s?.multi_market_confidence)>=45)score+=10;else reasons.push('nízká confidence');if(!s?.multi_market_conflict)score+=10;else reasons.push('konflikt marketů');const grade=score>=85?'A':score>=70?'B':score>=50?'C':'D';return{score,grade,reasons}}
function opportunityRows(s,cloud,capital){const rows=[];for(const x of xtbBoard(s)){const a=U(x.d?.action),trust=!['REVIEW','VERIFY_DATA'].includes(a);rows.push({kind:'XTB',name:x.p.ticker||x.p.symbol||x.p.name||'XTB',action:a,score:trust?Math.max(0,Math.min(100,N(x.d?.priority))):0,liquidity:90,trust:trust?'ověřeno':'prověřit data'})}for(const r of A(cloud?.inventory).filter(x=>ACTIVE.has(U(x.market_status)))){const snap=cloud.latest?.get(r.id),q=quality(r,snap),margin=N(snap?.market_price_czk)&&N(r.buy_each_czk)?(N(snap.market_price_czk)/N(r.buy_each_czk)-1)*100:0;rows.push({kind:'TICKET',name:r.event_name||'Ticket',action:snap?.recommendation_code||'WATCH',score:q.grade==='D'?0:Math.max(0,Math.min(100,50+margin*.4+q.score*.3)),liquidity:45,trust:`data ${q.grade}`})}if(capital.cashKnown)rows.push({kind:'CASH',name:'Hotovost',action:'HOLD',score:35,liquidity:100,trust:'explicitní cash'});return rows.sort((a,b)=>b.score-a.score)}
function lockState(ticketStates,capital){const locked=ticketStates.filter(x=>x.active).reduce((a,x)=>a+x.buy,0),waiting=ticketStates.filter(x=>x.st==='SOLD_WAITING_PAYMENT').reduce((a,x)=>a+x.sell,0),ages=ticketStates.filter(x=>x.active).map(x=>days(x.r.imported_at,new Date().toISOString())).filter(Number.isFinite);return{locked,waiting,avgDays:ages.length?ages.reduce((a,b)=>a+b,0)/ages.length:null,share:capital.knownCapital?locked/capital.knownCapital*100:null}}
function ticketAccounting(states){const known=states.filter(x=>x.payoutKnown),invested=known.reduce((a,x)=>a+x.buy,0),net=known.reduce((a,x)=>a+x.net,0),fees=known.reduce((a,x)=>a+N(x.r.marketplace_fee_czk),0),hold=known.filter(x=>x.hold);return{trades:known.length,invested,net,fees,roi:invested?net/invested*100:null,avgProfit:known.length?net/known.length:null,avgHold:hold.length?hold.reduce((a,x)=>a+x.hold,0)/hold.length:null,turnover:hold.length?365/(hold.reduce((a,x)=>a+x.hold,0)/hold.length):null,profitPer10kDay:invested&&hold.length?net/invested*10000/(hold.reduce((a,x)=>a+x.hold,0)/hold.length):null}}
function actionRows(s,cloud,trust){const out=[];for(const r of A(cloud?.inventory)){const st=U(r.market_status);if(st==='SOLD_UNDELIVERED')out.push({key:`ticket:${r.id}:deliver`,label:`Doručit · ${r.event_name}`,area:'Vstupenky',impact:95});if(st==='SOLD_WAITING_PAYMENT')out.push({key:`ticket:${r.id}:payout`,label:`Zkontrolovat payout · ${r.event_name}`,area:'Vstupenky',impact:75})}for(const x of xtbBoard(s).filter(x=>['REVIEW','VERIFY_DATA'].includes(U(x.d?.action))))out.push({key:`xtb:${x.p.ticker}:verify`,label:`Prověřit XTB data · ${x.p.ticker}`,area:'Peníze',impact:85});for(const t of A(s.tasks).filter(x=>!['DONE','CLOSED'].includes(U(x.status))))out.push({key:`task:${t.id}`,label:t.title||t.name||'Úkol',area:t.area||'Úkol',impact:N(t.priority)||50});if(trust.errors)out.push({key:'system:data-errors',label:`Datová kvalita · ${trust.errors} chyba/y`,area:'OS',impact:100});return out.sort((a,b)=>b.impact-a.impact)}
async function actionState(keys){try{const c=await cloudClient(),sess=await session();if(!c||!sess||!keys.length)return new Map();const {data,error}=await c.from('os_action_state').select('*').eq('user_id',sess.user.id).in('action_key',keys);return error?new Map():new Map(A(data).map(x=>[x.action_key,x]))}catch{return new Map()}}
export async function updateAction181(key,status,extra={}){const c=await cloudClient(),sess=await session();if(!c||!sess)return false;const row={user_id:sess.user.id,action_key:key,action_type:key.split(':')[0],status,updated_at:new Date().toISOString(),...extra};const {error}=await c.from('os_action_state').upsert(row,{onConflict:'user_id,action_key'});return !error}
export async function os181State(){const s=store.get(),cloud=await loadTicketCloud660().catch(()=>null),capital=await unifiedCapitalState160(s),trust=await dataTrustState163(),ledgerRows=await ledger(),states=A(cloud?.inventory).map(ticketState),guard=cashGuard(s),actions0=actionRows(s,cloud,trust),statesMap=await actionState(actions0.map(x=>x.key)),now=Date.now(),actions=actions0.filter(x=>{const st=statesMap.get(x.key);if(!st)return true;if(st.status==='DONE'||st.status==='DELEGATED'||st.status==='WAITING')return false;if(st.status==='SNOOZED'&&Date.parse(st.snoozed_until||0)>now)return false;return true});return{s,cloud,capital,trust,ledger:ledgerStats(ledgerRows),ticket:ticketAccounting(states),locks:lockState(states,capital),guard,opportunities:opportunityRows(s,cloud,capital),actions,states}}
function k(label,val,sub=''){return `<article><small>${h(label)}</small><b>${val}</b>${sub?`<span>${h(sub)}</span>`:''}</article>`}
export async function enhanceMoney181(){const host=document.querySelector('#moneyView');if(!host)return;host.querySelector('[data-os181-money]')?.remove();const x=await os181State(),sec=document.createElement('section');sec.dataset.os181Money='1';sec.className='card money-section os181-panel';sec.dataset.moneyGroup='wealth';const t=x.ticket,l=x.ledger,lock=x.locks,g=x.guard;sec.innerHTML=`<div class="eyebrow">OS 165–175 · CAPITAL CONTROL</div><h2>Skutečný výkon, obrat a bezpečný kapitál</h2><div class="os181-kpis">${k('Ticket čistý P/L',t.trades?`${t.net>=0?'+':''}${money(t.net)}`:'—',`${t.trades} payoutově uzavřených`)}${k('Ticket čisté ROI',t.roi===null?'—':`${t.roi.toFixed(1)} %`,t.avgHold?`držení Ø ${t.avgHold.toFixed(0)} dní`:'bez doby držení')}${k('Obrat kapitálu',t.turnover?`${t.turnover.toFixed(1)}× / rok`:'—',t.profitPer10kDay?`${money(t.profitPer10kDay)} / 10k / den`:'čeká na payout historii')}${k('Zamčeno v ticketech',money(lock.locked),lock.share===null?'podíl nelze určit':`${lock.share.toFixed(1)} % známého kapitálu`)}${k('XTB ledger',String(l.rows),`dividendy ${money(l.dividends)} · fees ${money(l.fees)}`)}${k('Deployable cash',g.deployable===null?'—':money(g.deployable),g.blocked?'GUARD BLOKUJE NOVÉ ALOKACE':g.reserve===null?'rezerva není explicitní':'po rezervě')}</div><div class="os181-ranking"><small>OS 173 · OPPORTUNITY RANKING</small>${x.opportunities.slice(0,7).map((o,i)=>`<div><span>${i+1}</span><b>${h(o.name)}</b><small>${h(o.kind)} · ${h(o.action)} · ${h(o.trust)}</small><strong>${o.score.toFixed(0)}</strong></div>`).join('')}</div><p class="muted">Ranking je rozhodovací priorita, ne očekávaný výnos. XTB ledger eviduje skutečné transakce a cashflow; realizovaný XTB P/L se bez párování nákupů a prodejů nepředstírá. Cash Reserve Guard používá jen explicitně zadanou volnou hotovost a rezervu.</p>`;host.appendChild(sec);window.__KAMIL_OS181_MONEY__={at:Date.now(),ledger:l.rows,ticketTrades:t.trades,explicitCashGuard:true};return x}
export async function enhanceTickets181(){const host=document.querySelector('#ticketIntelView');if(!host)return;host.querySelector('[data-os181-ticket]')?.remove();let cloud;try{cloud=await loadTicketCloud660()}catch{return}if(!cloud?.ok)return;const prices=await priceJournal(),byPrice=new Map();for(const p of prices){if(!byPrice.has(p.ticket_id))byPrice.set(p.ticket_id,[]);byPrice.get(p.ticket_id).push(p)}const sec=document.createElement('section');sec.dataset.os181Ticket='1';sec.className='os181-ticket card';const rows=A(cloud.inventory).filter(r=>ACTIVE.has(U(r.market_status))).map(r=>({r,s:cloud.latest?.get(r.id),q:quality(r,cloud.latest?.get(r.id)),timeline:eventTimeline(r,A(cloud.history?.get(r.id)),A(byPrice.get(r.id)))}));sec.innerHTML=`<div class="eyebrow">OS 167–169 · TICKET CONTROL</div><h2>Timeline, repricing journal a kvalita trhu</h2><div class="os181-ticketgrid">${rows.slice(0,10).map(x=>`<article><div><b>${h(x.r.event_name||'Ticket')}</b><span>${h(x.r.section||'bez sektoru')}</span></div><strong class="grade-${x.q.grade.toLowerCase()}">DATA ${x.q.grade}</strong><small>${x.q.score}/100${x.q.reasons.length?` · ${h(x.q.reasons.slice(0,2).join(', '))}`:''}</small><details><summary>Timeline · ${x.timeline.length} bodů</summary>${x.timeline.slice(-10).map(e=>`<p><time>${new Date(e.at).toLocaleDateString('cs-CZ')}</time>${h(e.label)}</p>`).join('')||'<p>Bez historie.</p>'}</details></article>`).join('')||'<p class="muted">Žádné aktivní tickety.</p>'}</div><p class="muted">Price journal tvoří skutečnou historii až od auditovaných změn ceny; staré repricing kroky zpětně nevymýšlím.</p>`;const shell=host.querySelector('.tv132-shell');(shell||host).appendChild(sec);window.__KAMIL_OS181_TICKETS__={at:Date.now(),rows:rows.length};return rows}
export async function enhanceToday181(){const root=document.querySelector('.dashboard110');if(!root)return;root.querySelector('[data-os181-today]')?.remove();const x=await os181State(),sec=document.createElement('section');sec.dataset.os181Today='1';sec.className='os181-today';const top=x.actions.slice(0,7);sec.innerHTML=`<div class="os181-todayhead"><div><div class="eyebrow">OS 176–181 · PERSONAL OPERATING SYSTEM 2.0</div><h1>${top.length?`${top.length} priorit k řešení`:'Bez známé akutní akce'}</h1><p>Jedna fronta napříč OS. Data, která nejsou ověřená, nevytvářejí falešnou akci.</p></div><div><small>OS HEALTH</small><b class="${x.trust.errors?'bad':x.trust.warnings||x.trust.unknown?'warn':'good'}">${x.trust.errors?'CHYBA':x.trust.warnings||x.trust.unknown?'KONTROLA':'OK'}</b></div></div><div class="os181-actions">${top.map((a,i)=>`<article data-action-key="${h(a.key)}"><span>${i+1}</span><div><b>${h(a.label)}</b><small>${h(a.area)} · dopad ${a.impact}</small></div><div class="os181-acts"><button data-act="DONE">Hotovo</button><button data-act="SNOOZED">Odložit</button><button data-act="WAITING">Čekám</button></div></article>`).join('')||'<article><span>✓</span><div><b>Nic akutního z načtených dat</b><small>Neznamená to, že mimo OS nejsou jiné povinnosti.</small></div></article>'}</div><div class="os181-strip"><span>Kapitál <b>${money(x.capital.knownCapital)}</b></span><span>Ticket lock <b>${money(x.locks.locked)}</b></span><span>Čeká payout <b>${money(x.locks.waiting)}</b></span><span>Deployable cash <b>${x.guard.deployable===null?'—':money(x.guard.deployable)}</b></span></div>`;root.prepend(sec);sec.querySelectorAll('[data-act]').forEach(b=>b.addEventListener('click',async()=>{const row=b.closest('[data-action-key]'),status=b.dataset.act,extra=status==='SNOOZED'?{snoozed_until:new Date(Date.now()+86400000).toISOString()}:{};if(await updateAction181(row.dataset.actionKey,status,extra))row.remove()}));window.__KAMIL_OS181_TODAY__={at:Date.now(),actions:top.length,explicitCashGuard:true};return x}
export const os181Info={steps:[165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181],truthfulAccounting:true,noSyntheticHistory:true,explicitCashGuard:true,actionStates:['DONE','SNOOZED','WAITING','DELEGATED']};