import {store} from './state.js';
import {h,qs,uid,toast} from './utils.js';
import {markInboxResolved35,convertInboxToWaiting35,closeWaitingFromReply35} from './emailWorkflow35.js';
import {ensureWaiting35,nextFollowUpDate35} from './followUp35.js';
import {ensureOs40State,executiveInbox40,autoWaitingCandidates40,smartSnoozeOptions40,morningBriefing40,eveningShutdown40,workdayPlan40,delegationCenter40,projectHealth40,recordTicketPriceHistory40} from './os40Core.js';

const CARD='os40ExecutiveCard',TOP='os40Top',TILE='os40Tile';let openEl=null,tab='EXEC',queued=false;
const tone=p=>Number(p)>=90?'bad':Number(p)>=75?'warn':'good';
const money=v=>`${Math.round(Number(v)||0).toLocaleString('cs-CZ')} Kč`;
const date=v=>v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString('cs-CZ'):'—';
function ensureCss(){if(document.querySelector('link[data-os40-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./os40.css';l.dataset.os40Css='1';document.head.appendChild(l)}
const openTarget=t=>{if(t==='email'){window.dispatchEvent(new CustomEvent('kamil:email-workflow-open'));return}if(t==='waiting'){window.dispatchEvent(new CustomEvent('kamil:waiting-open'));return}if(t==='director'){window.dispatchEvent(new CustomEvent('kamil:director-open'));return}window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:t||'today'}))};
function bootstrap(){const s=store.get(),today=new Date().toISOString().slice(0,10);if(!s.os40||s.os40?.lastBootstrapDate!==today){store.mutate('Kamil OS 40 inicializace',x=>{const os=ensureOs40State(x);recordTicketPriceHistory40(x);os.lastBootstrapDate=today},{undo:false,audit:false})}}
function mutate(label,fn){store.mutate(label,s=>{ensureOs40State(s);fn(s)});schedule()}
function markEmailDone(id){mutate('E-mail vyřešen z Executive Inboxu',s=>markInboxResolved35(s,id));toast('E-mail vyřešen')}
function emailToWaiting(id){mutate('E-mail převeden do Waiting For z Executive Inboxu',s=>convertInboxToWaiting35(s,id,uid,new Date(),3));toast('OS teď hlídá odpověď')}
function closeWaiting(id){mutate('Waiting For uzavřeno z Executive Inboxu',s=>closeWaitingFromReply35(s,id));toast('Čekání uzavřeno')}
function taskDone(id){mutate('Pracovní úkol dokončen z Executive Inboxu',s=>{const x=(s.tasks||[]).find(y=>String(y.id)===String(id));if(x){x.status='DONE';x.completedAt=new Date().toISOString()}});toast('Úkol hotový')}
function hideExec(id){mutate('Executive položka odložena',s=>{s.os40.executiveDone[id]=new Date().toISOString()})}
function confirmTicket(id,price,action){mutate('Uložen ticket pricing návrh',s=>{s.os40.ticketDecisions[id]={ticketId:id,action,proposedPrice:Number(price)||null,at:new Date().toISOString(),status:'APPROVED_IN_OS'};const x=(s.ticketBook?.items||[]).find(y=>String(y.id)===String(id));if(x){x.osProposedPrice=Number(price)||null;x.osProposedAction=action;x.osProposalAt=new Date().toISOString()}});toast('Návrh uložen v OS; tržiště se nezměnilo')}
function addAutoWaiting(id){const c=autoWaitingCandidates40(store.get()).find(x=>String(x.id)===String(id));if(!c)return;mutate('Vytvořeno Waiting For z odeslaného mailu',s=>{ensureWaiting35(s).unshift({id:uid('waiting'),title:c.title,subject:c.title,person:c.person||'',sourceOutboundId:c.id,sourceThreadId:c.threadId,status:'OPEN',tone:'FORMAL',followUpEveryDays:3,nextFollowUpAt:nextFollowUpDate35(3,new Date()),createdAt:new Date().toISOString(),lastTouchAt:new Date().toISOString(),note:'Auto Waiting For z odeslaného e-mailu.'})});toast('Odpověď se bude hlídat')}
async function snoozeWaiting(id){const row=executiveInbox40(store.get()).waiting.rows.find(x=>String(x.id)===String(id));if(!row)return;const opts=smartSnoozeOptions40(row),host=qs('#modalHost'),el=document.createElement('div');el.className='modal';el.innerHTML=`<div class="modal-box"><div class="eyebrow">SMART SNOOZE / 35.4</div><h2>Kdy se k tomu vrátit?</h2><div class="os40-choice-list">${opts.map(x=>`<button class="btn" data-choice="${h(x.date)}"><b>${h(x.label)}</b><small>${h(date(x.date))}</small></button>`).join('')}</div><button class="btn" data-close>Zavřít</button></div>`;host.appendChild(el);const close=()=>el.remove();el.querySelector('[data-close]').onclick=close;el.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const d=b.dataset.choice;mutate('Smart Snooze Waiting For',s=>{const x=ensureWaiting35(s).find(y=>String(y.id)===String(id));if(x)x.nextFollowUpAt=d});close();toast(`Odloženo na ${date(d)}`)});el.onclick=e=>{if(e.target===el)close()}}
function execActions(x){if(x.sourceType==='EMAIL')return `<button class="btn" data-email-done="${h(x.sourceId)}">Hotovo</button><button class="btn primary" data-email-wait="${h(x.sourceId)}">Vyřízeno → čekám</button>`;if(x.sourceType==='WAITING'&&x.action==='CLOSE_WAITING')return `<button class="btn primary" data-close-wait="${h(x.sourceId)}">Uzavřít</button>`;if(x.sourceType==='WAITING')return `<button class="btn" data-snooze="${h(x.sourceId)}">Odložit…</button><button class="btn primary" data-target="waiting">Follow-up</button>`;if(x.sourceType==='TASK')return `<button class="btn primary" data-task-done="${h(x.sourceId)}">Hotovo</button>`;if(x.sourceType==='TICKET')return `${x.suggestedPrice?`<button class="btn primary" data-ticket="${h(x.sourceId)}" data-price="${h(x.suggestedPrice)}" data-action="${h(x.action)}">Návrh ${money(x.suggestedPrice)}/ks</button>`:''}<button class="btn" data-target="tickets">Detail</button>`;return `<button class="btn primary" data-target="${h(x.target||'today')}">Otevřít</button>`}
function execRow(x){return `<div class="os40-exec-row ${x.priority>=90?'urgent':''}"><div class="os40-exec-copy"><div class="os40-line"><span class="status ${tone(x.priority)}">${x.priority}</span><span class="os40-kind">${h(x.kind)}</span><span class="status">jistota ${x.confidence} %</span></div><b>${h(x.title)}</b><small>${h(x.reason)}</small><small class="os40-confidence">${h(x.confidenceWhy)}</small></div><div class="os40-actions">${execActions(x)}<button class="icon-btn quiet" data-hide="${h(x.id)}" title="Skrýt">×</button></div></div>`}
function bindExec(root){root.querySelectorAll('[data-email-done]').forEach(x=>x.onclick=()=>markEmailDone(x.dataset.emailDone));root.querySelectorAll('[data-email-wait]').forEach(x=>x.onclick=()=>emailToWaiting(x.dataset.emailWait));root.querySelectorAll('[data-close-wait]').forEach(x=>x.onclick=()=>closeWaiting(x.dataset.closeWait));root.querySelectorAll('[data-task-done]').forEach(x=>x.onclick=()=>taskDone(x.dataset.taskDone));root.querySelectorAll('[data-snooze]').forEach(x=>x.onclick=()=>snoozeWaiting(x.dataset.snooze));root.querySelectorAll('[data-ticket]').forEach(x=>x.onclick=()=>confirmTicket(x.dataset.ticket,x.dataset.price,x.dataset.action));root.querySelectorAll('[data-target]').forEach(x=>x.onclick=()=>openTarget(x.dataset.target));root.querySelectorAll('[data-hide]').forEach(x=>x.onclick=()=>hideExec(x.dataset.hide))}
function renderCard(){const view=qs('#todayView');if(!view?.querySelector('.view-head'))return;qs(`#${CARD}`,view)?.remove();const b=executiveInbox40(store.get()),m=morningBriefing40(store.get()),host=document.createElement('div');host.id=CARD;host.className='card os40-card';host.innerHTML=`<div class="card-head"><div><div class="eyebrow">EXECUTIVE INBOX / KAMIL OS 40.1</div><h2>${h(m.summary)}</h2><p class="muted">Práce, maily, čekání, vstupenky a peníze v jednom pořadí.</p></div><div class="os40-head-actions"><span class="status ${b.critical?'bad':'good'}">${b.critical} kritické</span><button class="btn primary" data-open-os40>Otevřít OS 40 →</button></div></div><div class="os40-brief-strip"><span><b>${m.counts.actions}</b> akcí</span><span><b>${m.counts.emails}</b> mailů</span><span><b>${m.counts.followUps}</b> urgovat</span><span><b>${m.counts.tickets}</b> ticket zásahů</span><span>${h(m.money)}</span></div><div class="os40-exec-list">${b.rows.slice(0,4).map(execRow).join('')||'<div class="empty success-empty">Nic důležitého teď nehoří.</div>'}</div>`;view.querySelector('.view-head').insertAdjacentElement('afterend',host);host.querySelector('[data-open-os40]').onclick=openOs40;bindExec(host)}
function execHtml(){const b=executiveInbox40(store.get()),auto=autoWaitingCandidates40(store.get());return `<div class="os40-panel"><div class="card-head"><div><div class="eyebrow">EXECUTIVE INBOX / 35.3 + ONE-CLICK / 35.4</div><h3>${b.rows.length} otevřených rozhodnutí</h3></div><span class="status ${b.critical?'bad':'good'}">${b.critical} kritické</span></div><div class="os40-exec-list">${b.rows.slice(0,20).map(execRow).join('')||'<div class="empty success-empty">Inbox je čistý.</div>'}</div></div><div class="os40-panel"><div class="eyebrow">AUTO WAITING FOR / 35.5</div><h3>Odeslané maily, kde čekáš na odpověď</h3><div class="os40-mini-list">${auto.slice(0,8).map(x=>`<div class="os40-auto-wait"><div><b>${h(x.title)}</b><small>${x.person?`${h(x.person)} · `:''}${h(x.reason)}</small></div><button class="btn primary" data-auto-wait="${h(x.id)}">Hlídát odpověď</button></div>`).join('')||'<div class="empty success-empty">Žádný nový kandidát.</div>'}</div></div>`}
function dayHtml(){const m=morningBriefing40(store.get()),p=workdayPlan40(store.get()),e=eveningShutdown40(store.get());return `<div class="os40-panel"><div class="eyebrow">MORNING BRIEFING / 36.0</div><h3>${h(m.summary)}</h3><div class="metric-strip"><div class="metric"><span>Akce</span><b>${m.counts.actions}</b></div><div class="metric"><span>Čekání</span><b>${m.counts.waiting}</b></div><div class="metric"><span>Odpovědi</span><b>${m.counts.replies}</b></div><div class="metric"><span>Tickets</span><b>${m.counts.tickets}</b></div></div><div class="decision-note">${h(m.money)}</div></div><div class="os40-panel"><div class="eyebrow">WORKDAY PLANNER / 36.2</div><h3>Doporučená kostra dne</h3><div class="os40-timeline">${p.blocks.map(x=>`<div><time>${h(x.start)}–${h(x.end)}</time><span class="status ${tone(x.priority)}">${h(x.kind)}</span><b>${h(x.label)}</b></div>`).join('')}</div><div class="decision-note">${h(p.note)}</div></div><div class="os40-panel"><div class="eyebrow">EVENING SHUTDOWN / 36.1</div><h3>${h(e.summary)}</h3><div class="os40-mini-list">${[...e.must,...e.tomorrow].slice(0,6).map(x=>`<div><b>${h(x.title)}</b><small>${h(x.reason)}</small></div>`).join('')||'<div class="empty success-empty">Den je čistý.</div>'}</div></div>`}
function workHtml(){const d=delegationCenter40(store.get()),p=projectHealth40(store.get());return `<div class="os40-panel"><div class="eyebrow">DELEGATION CENTER / 36.3</div><h3>${d.rows.length} otevřených delegací</h3><div class="os40-mini-list">${d.rows.map(x=>`<div><span class="status ${tone(x.priority)}">${h(x.risk)}</span><b>${h(x.title)}</b><small>${h(x.person)} · ${h(x.reason)}</small></div>`).join('')||'<div class="empty">Žádné delegace.</div>'}</div></div><div class="os40-panel"><div class="eyebrow">PROJECT HEALTH / 36.4</div><h3>Zdraví zakázek</h3><div class="os40-project-grid">${p.map(x=>`<div class="os40-project ${x.status.toLowerCase()}"><div><span class="os40-score">${x.score}</span><b>${h(x.title)}</b></div><small>${h(x.reason)} · ${x.overdue} po termínu · ${x.waiting} čekání · ${x.inbox} inbox</small></div>`).join('')||'<div class="empty">Chybí projektová data.</div>'}</div></div>`}
function modalHtml(){const body=tab==='DAY'?dayHtml():tab==='WORK'?workHtml():execHtml();return `<div class="modal-box os40-modal"><div class="card-head"><div><div class="eyebrow">KAMIL OS 40.1</div><h2>Executive Command Center</h2></div><button class="btn" data-close-os40>Zavřít</button></div><div class="os40-tabs"><button class="btn ${tab==='EXEC'?'primary':''}" data-tab="EXEC">Executive</button><button class="btn ${tab==='DAY'?'primary':''}" data-tab="DAY">Den</button><button class="btn ${tab==='WORK'?'primary':''}" data-tab="WORK">Práce</button></div>${body}</div>`}
function paint(){if(!openEl)return;openEl.innerHTML=modalHtml();openEl.querySelector('[data-close-os40]').onclick=()=>{openEl.remove();openEl=null};openEl.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{tab=x.dataset.tab;paint()});openEl.querySelectorAll('[data-auto-wait]').forEach(x=>x.onclick=()=>addAutoWaiting(x.dataset.autoWait));bindExec(openEl)}
export function openOs40(){bootstrap();openEl?.remove();const host=qs('#modalHost');if(!host)return;openEl=document.createElement('div');openEl.className='modal';host.appendChild(openEl);openEl.onclick=e=>{if(e.target===openEl){openEl.remove();openEl=null}};paint()}
function refreshTop(){const actions=qs('.top-actions');if(!actions)return;const b=executiveInbox40(store.get());let btn=qs(`#${TOP}`,actions);if(!btn){btn=document.createElement('button');btn.id=TOP;btn.className='btn';btn.onclick=openOs40;actions.insertBefore(btn,actions.firstChild)}btn.innerHTML=`◈ <span>OS 40</span>${b.critical?` <b class="bad">${b.critical}</b>`:''}`;btn.title=`Executive Inbox · ${b.rows.length} otevřených`}
function refreshTile(){const grid=qs('#moreView .more26-grid');if(!grid)return;const b=executiveInbox40(store.get());let btn=qs(`#${TILE}`,grid);if(!btn){btn=document.createElement('button');btn.id=TILE;btn.className='hub-tile';btn.onclick=openOs40;grid.appendChild(btn)}btn.innerHTML=`<span class="hub-icon ${b.critical?'bad':b.today?'warn':'good'}">◈</span><span class="hub-copy"><b>Kamil OS 40</b><small>${b.rows.length} otevřených · ${b.critical} kritické · Executive, den, práce</small></span><span class="hub-arrow">→</span>`}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;renderCard();refreshTop();refreshTile();if(openEl)paint()})}
function start(){ensureCss();bootstrap();renderCard();refreshTop();refreshTile();store.subscribe(schedule);const today=qs('#todayView');if(today)new MutationObserver(()=>{if(!qs(`#${CARD}`,today))schedule()}).observe(today,{childList:true,subtree:false});const more=qs('#moreView');if(more)new MutationObserver(schedule).observe(more,{childList:true,subtree:true});window.addEventListener('kamil:os40-open',openOs40);window.addEventListener('kamil:navigate',schedule)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
