import {store} from './state.js';
import {h,qs,formModal,toast} from './utils.js';
import {ensureOs40State,relationshipMemory40,universalSearch40,executiveInbox40,OS40_PERMISSION_LEVELS} from './os40Core.js';

let openEl=null,tab='SEARCH';
const labels={DISPLAY:'Jen zobrazit',PROPOSE:'Navrhnout',PREPARE:'Připravit',APPROVE:'Po mém potvrzení'};
const openTarget=t=>{if(t==='email'){window.dispatchEvent(new CustomEvent('kamil:email-workflow-open'));return}if(t==='waiting'){window.dispatchEvent(new CustomEvent('kamil:waiting-open'));return}if(t==='director'){window.dispatchEvent(new CustomEvent('kamil:director-open'));return}window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:t||'today'}))};
function mutate(label,fn){store.mutate(label,s=>{ensureOs40State(s);fn(s)});paint()}
function searchHtml(){return `<div class="os40-panel"><div class="eyebrow">UNIVERSAL SEARCH 2.0 / 39.0</div><h3>Najdi vše napříč Kamil OS</h3><div class="os40-search"><input data-search autofocus placeholder="PKS, Viagogo, jméno, projekt, investice…"><button class="btn" data-search-go>Hledat</button></div><div data-results class="os40-search-results"><div class="empty">Začni psát alespoň 2 znaky.</div></div></div>`}
function peopleHtml(){const rows=relationshipMemory40(store.get());return `<div class="os40-panel"><div class="eyebrow">RELATIONSHIP MEMORY / 39.1</div><h3>Pracovní kontext lidí</h3><div class="os40-people">${rows.slice(0,35).map(x=>`<div><div><b>${h(x.person)}</b><small>${x.open} otevřených · ${x.touches} interakcí · ${x.kinds.map(h).join(', ')}${x.lastTitle?` · naposled ${h(x.lastTitle)}`:''}</small>${x.note?`<small class="good">Poznámka: ${h(x.note)}</small>`:''}</div><button class="btn" data-note="${h(x.id)}" data-name="${h(x.person)}">Poznámka</button></div>`).join('')||'<div class="empty">Zatím není dost kontextu.</div>'}</div></div>`}
function settingsHtml(){const s=store.get(),p=ensureOs40State(s).permissions,b=executiveInbox40(s);return `<div class="os40-panel"><div class="eyebrow">OS CONFIDENCE / 40.0</div><h3>Jistota místo falešné přesnosti</h3><p class="muted">Executive Inbox u každého doporučení ukazuje procento jistoty podle čerstvosti dat, zdroje a úplnosti portfolia.</p><div class="os40-scorecards">${b.rows.slice(0,8).map(x=>`<div><span class="status">${x.confidence} %</span><b>${h(x.title)}</b><small>${h(x.confidenceWhy)}</small></div>`).join('')||'<div class="empty">Žádná doporučení.</div>'}</div></div><div class="os40-panel"><div class="eyebrow">AUTOPILOT PERMISSIONS / 40.1</div><h3>Kolik může OS připravit</h3><div class="os40-permissions">${Object.entries(p).map(([k,v])=>`<label>${h({email:'E-mail',waiting:'Waiting For',work:'Práce',money:'Peníze',tickets:'Vstupenky',personal:'Osobní'}[k]||k)}<select data-permission="${h(k)}">${OS40_PERMISSION_LEVELS.map(x=>`<option value="${x}" ${x===v?'selected':''}>${h(labels[x])}</option>`).join('')}</select></label>`).join('')}</div><button class="btn primary" data-save-permissions>Uložit oprávnění</button><div class="decision-note">Tato oprávnění řídí chování uvnitř OS. Neudělují webové appce samovolný přístup k obchodování, odesílání mailů ani změnám na tržištích.</div></div>`}
function modalHtml(){const body=tab==='PEOPLE'?peopleHtml():tab==='SETTINGS'?settingsHtml():searchHtml();return `<div class="modal-box os40-modal"><div class="card-head"><div><div class="eyebrow">KAMIL OS 39–40</div><h2>Search · Memory · Confidence</h2></div><button class="btn" data-close>Zavřít</button></div><div class="os40-tabs"><button class="btn ${tab==='SEARCH'?'primary':''}" data-tab="SEARCH">Hledat</button><button class="btn ${tab==='PEOPLE'?'primary':''}" data-tab="PEOPLE">Lidé</button><button class="btn ${tab==='SETTINGS'?'primary':''}" data-tab="SETTINGS">Nastavení</button></div>${body}</div>`}
function bind(){if(!openEl)return;openEl.querySelector('[data-close]').onclick=()=>{openEl.remove();openEl=null};openEl.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;paint()});const input=openEl.querySelector('[data-search]'),go=openEl.querySelector('[data-search-go]');const run=()=>{const rows=universalSearch40(store.get(),input?.value||''),host=openEl.querySelector('[data-results]');if(!host)return;host.innerHTML=rows.length?rows.map(x=>`<button class="os40-search-result" data-target="${h(x.target)}"><span class="status">${h(x.type)}</span><b>${h(x.title)}</b><small>${h(x.detail||'')}</small></button>`).join(''):'<div class="empty">Nic nenalezeno.</div>';host.querySelectorAll('[data-target]').forEach(x=>x.onclick=()=>openTarget(x.dataset.target))};if(input){input.oninput=()=>{if(input.value.trim().length>=2)run()};input.onkeydown=e=>{if(e.key==='Enter')run()}}if(go)go.onclick=run;openEl.querySelectorAll('[data-note]').forEach(btn=>btn.onclick=async()=>{const id=btn.dataset.note,name=btn.dataset.name,current=store.get().os40?.relationshipNotes?.[id]||'',data=await formModal(`Poznámka · ${name}`,`<label class="wide-field">Pracovní kontext<textarea name="note" rows="5" autofocus>${h(current)}</textarea></label>`,{submitLabel:'Uložit'});if(data){mutate('Uložena Relationship Memory poznámka',s=>{s.os40.relationshipNotes[id]=String(data.note||'').trim()});toast('Poznámka uložena')}});const save=openEl.querySelector('[data-save-permissions]');if(save)save.onclick=()=>{mutate('Uložena oprávnění Autopilotu',s=>{openEl.querySelectorAll('[data-permission]').forEach(sel=>s.os40.permissions[sel.dataset.permission]=sel.value)});toast('Oprávnění uložena')}}
function paint(){if(!openEl)return;openEl.innerHTML=modalHtml();bind()}
export function openOs40Knowledge(){openEl?.remove();const host=qs('#modalHost');if(!host)return;openEl=document.createElement('div');openEl.className='modal';host.appendChild(openEl);openEl.onclick=e=>{if(e.target===openEl){openEl.remove();openEl=null}};paint()}
function injectTile(){const grid=qs('#moreView .more26-grid');if(!grid||qs('#os40KnowledgeTile',grid))return;const btn=document.createElement('button');btn.id='os40KnowledgeTile';btn.className='hub-tile';btn.innerHTML='<span class="hub-icon good">⌕</span><span class="hub-copy"><b>Search & Memory</b><small>Universal Search · Relationship Memory · Confidence · Permissions</small></span><span class="hub-arrow">→</span>';btn.onclick=openOs40Knowledge;grid.appendChild(btn)}
function start(){injectTile();const more=qs('#moreView');if(more)new MutationObserver(injectTile).observe(more,{childList:true,subtree:true});window.addEventListener('kamil:knowledge-open',openOs40Knowledge);window.addEventListener('kamil:navigate',injectTile)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
