import {commandCenter40,copilot40,moneyBrain40,ticketPortfolioManager40,forecastEngine40,entityGraph40} from './os40.js';
const A=v=>Array.isArray(v)?v:[],N=v=>Number(v||0),U=v=>String(v||'').toUpperCase(),day=(v,now=new Date())=>{const t=Date.parse(v||0);return Number.isFinite(t)?Math.ceil((t-now)/86400000):null};
export const OS42_VERSION='42.0';
export const OS42_CONTRACT={autoSend:false,autoTrade:false,autoReprice:false,autoDelete:false,autoCalendarWrite:false,criticalActionsRequireConfirmation:true};
export function universalSearch42(s={},q=''){const x=String(q).trim().toLowerCase();if(!x)return[];const rows=[];const add=(kind,target,list,title,extra='')=>A(list).forEach(v=>{const t=String(title(v)||'');if(`${t} ${extra&&extra(v)||''}`.toLowerCase().includes(x))rows.push({kind,target,title:t,id:v.id||t,item:v})});add('ÚKOL','today',s.tasks,v=>v.title||v.text);add('PROJEKT','director',s.projects,v=>v.name||v.title);add('ČEKÁNÍ','waiting',s.delegations,v=>v.title||v.person,v=>v.person||'');add('VSTUPENKA','tickets',s.ticketBook?.items,v=>v.eventName||v.name||v.title);add('INBOX','today',s.inbox,v=>v.title||v.text);return rows.slice(0,20)}
export function commandPalette42(s={},q=''){const base=[['Přidat úkol','today','ADD_TASK'],['Otevřít XTB','money','OPEN_MONEY'],['Otevřít vstupenky','tickets','OPEN_TICKETS'],['Waiting For','waiting','OPEN_WAITING'],['Director Mode','director','OPEN_DIRECTOR']].map(([title,target,action])=>({title,target,action}));const z=String(q).toLowerCase();return (z?base.filter(x=>x.title.toLowerCase().includes(z)):base).slice(0,8)}
export function decisionInbox42(s={},now=new Date()){const c=commandCenter40(s,now);return {rows:A(c.top).filter(x=>N(x.priority)>=65).map(x=>({...x,decision:true})),count:A(c.top).filter(x=>N(x.priority)>=65).length}}
export function personalSla42(s={},now=new Date()){const rows=[...A(s.tasks).map(x=>({...x,kind:'ÚKOL',at:x.due})),...A(s.delegations).map(x=>({...x,kind:'ČEKÁNÍ',at:x.due||x.nextFollowUpAt||x.updatedAt}))].filter(x=>U(x.status)!=='DONE'&&U(x.status)!=='HOTOVO').map(x=>{const d=day(x.at,now);return {...x,days:d,breach:d!==null&&d<0,severity:d===null?20:d<0?Math.min(100,70+Math.abs(d)*5):d<=2?65:30}}).sort((a,b)=>b.severity-a.severity);return {rows:rows.slice(0,12),breaches:rows.filter(x=>x.breach).length}}
export function relationshipMemory42(s={}){const m={};A(s.delegations).forEach(x=>{const p=x.person||'Neurčeno';m[p]??={person:p,open:0,items:[],last:null};if(U(x.status||'WAITING')!=='DONE')m[p].open++;m[p].items.push(x);const t=Date.parse(x.updatedAt||x.lastContactAt||0);if(Number.isFinite(t)&&(!m[p].last||t>Date.parse(m[p].last)))m[p].last=x.updatedAt||x.lastContactAt});return Object.values(m).sort((a,b)=>b.open-a.open)}
export function lifeTimeline42(s={}){const r=[];const add=(kind,list,date,title)=>A(list).forEach(x=>{const d=date(x);if(d)r.push({kind,date:d,title:title(x),id:x.id||title(x)})});add('ÚKOL',s.tasks,x=>x.due,x=>x.title||x.text);add('EVENT',s.calendar?.events,x=>x.start||x.date,x=>x.title||x.name);add('VSTUPENKA',s.ticketBook?.items,x=>x.date,x=>x.eventName||x.name);add('ROZHODNUTÍ',s.decisionMemory36?.items,x=>x.at,x=>x.title);return r.sort((a,b)=>Date.parse(a.date)-Date.parse(b.date)).slice(0,50)}
export function smartDailyPlan42(s={},now=new Date()){const c=commandCenter40(s,now),cal=A(s.calendar?.events).filter(x=>day(x.start||x.date,now)===0);return {morning:A(c.top).slice(0,2),later:A(c.top).slice(2,5),calendar:cal,delegate:A(s.tasks).filter(x=>/deleg/i.test(x.kind||x.tags||'')).slice(0,4)}}
export function delegationOs42(s={},now=new Date()){const r=A(s.delegations).filter(x=>U(x.status||'WAITING')!=='DONE').map(x=>({...x,age:Math.max(0,-N(day(x.updatedAt||x.createdAt,now)))}));return {rows:r,count:r.length,people:new Set(r.map(x=>x.person).filter(Boolean)).size}}
export function meetingCopilot42(s={},meeting={},now=new Date()){const text=`${meeting.title||meeting.name||''} ${A(meeting.attendees).map(x=>x.name||x.email||x).join(' ')}`.toLowerCase();const waiting=A(s.delegations).filter(x=>text&&text.includes(String(x.person||'').toLowerCase()));const tasks=A(s.tasks).filter(x=>U(x.status)!=='HOTOVO').slice(0,8);return {title:meeting.title||meeting.name||'Porada',openTasks:tasks,waiting,questions:[...waiting.slice(0,3).map(x=>`Jaký je stav: ${x.title||x.person}?`),...tasks.slice(0,2).map(x=>`Potvrdit termín: ${x.title||x.text}?`)]}}
export function afterMeetingProcessor42(text=''){const lines=String(text).split(/\n|[.!?]\s+/).map(x=>x.trim()).filter(Boolean);const tasks=lines.filter(x=>/udělat|poslat|zajistit|ověřit|doplnit|termín|do \d/i.test(x)).map((x,i)=>({id:`proposal-${i}`,title:x,status:'PROPOSAL'}));return {tasks,decisions:lines.filter(x=>/dohod|rozhod|schvál|platí/i.test(x)),requiresConfirmation:true}}
export function financialWhatIf42(s={},input={}){const m=moneyBrain40(s),monthly=N(input.monthly||25000),months=Math.max(1,N(input.months||6)),oneOff=N(input.oneOff),cashAfter=m.cash-oneOff-monthly,invested=monthly*months+oneOff;return {cashAfterFirstMonth:cashAfter,invested,months,reserveOk:cashAfter>=m.reserveFloor,note:'Scénář je model, ne predikce výnosu.'}}
export function investmentThesis42(s={}){const positions=A(s.xtbReport?.positions||s.xtbHub?.positions);return positions.map(x=>({symbol:x.symbol||x.ticker,title:x.name||x.symbol,thesis:x.thesis||null,exitConditions:A(x.exitConditions),needsThesis:!x.thesis}))}
export function ticketMarketIntelligence42(s={},now=new Date()){const p=ticketPortfolioManager40(s,now);const rows=A(s.ticketBook?.items).filter(x=>!['SOLD','CANCELLED'].includes(U(x.workflow))).map(x=>{const d=day(x.date,now),buy=N(x.buy),ask=N(x.ask||x.listPrice||x.sell);const margin=buy?((ask-buy)/buy)*100:0;return {...x,days:d,marginPct:Math.round(margin),score:Math.max(0,Math.min(100,50+(d!==null&&d<14?15:0)+(margin>20?15:0)-(d!==null&&d<3&&margin<0?25:0)))}}).sort((a,b)=>b.score-a.score);return {...p,rows}}
export function opportunityRadar42(s={},now=new Date()){const out=[],m=moneyBrain40(s),t=ticketMarketIntelligence42(s,now);if(m.investable>0)out.push({kind:'KAPITÁL',title:`K dispozici plán ${m.investable.toLocaleString('cs-CZ')} Kč`,score:65,target:'money'});t.rows.filter(x=>x.marginPct>20).slice(0,3).forEach(x=>out.push({kind:'VSTUPENKY',title:`${x.eventName||x.name}: potenciální marže ${x.marginPct}%`,score:x.score,target:'tickets'}));return out.sort((a,b)=>b.score-a.score)}
export function wasteDetector42(s={}){const out=[];A(s.subscriptions||s.householdBills).forEach(x=>{if(x.active===false||U(x.status)==='CANCEL')return;if(N(x.monthly)>0&&x.lastUsedAt&&Date.now()-Date.parse(x.lastUsedAt)>60*86400000)out.push({kind:'PŘEDPLATNÉ',title:x.name||x.title,monthly:N(x.monthly),reason:'Bez použití 60+ dní'})});return {rows:out,monthlyPotential:out.reduce((a,x)=>a+x.monthly,0)}}
export function personalRiskMap42(s={},now=new Date()){const c=commandCenter40(s,now),sla=personalSla42(s,now);const dimensions={money:c.money.reserveGap?95:25,work:Math.min(100,N(c.director.score)),waiting:Math.min(100,N(c.waiting.count)*8),tickets:Math.min(100,N(c.tickets.risk)),admin:Math.min(100,sla.breaches*12)};return {dimensions,total:Math.round(Object.values(dimensions).reduce((a,b)=>a+b,0)/5)}}
export function goalEngine42(s={}){return A(s.goals).map(g=>{const target=N(g.target),current=N(g.current),pct=target?Math.max(0,Math.min(100,Math.round(current/target*100))):0;return {...g,pct,status:pct>=100?'HOTOVO':pct>=75?'NA DOBRÉ CESTĚ':pct>=40?'SLEDOVAT':'ZAOSTÁVÁ'}})}
export function weeklyCeoReview42(s={},now=new Date()){const c=commandCenter40(s,now),risk=personalRiskMap42(s,now),goals=goalEngine42(s);return {headline:`CEO Review · risk ${risk.total}/100`,wins:A(s.decisionMemory36?.items).filter(x=>x.status==='DONE').slice(-5),top:A(c.top).slice(0,5),warnings:A(c.warnings).slice(0,5),goals,money:c.money,tickets:c.tickets}}
export function agentLayer42(s={},request='',now=new Date()){const q=String(request),c=commandCenter40(s,now),plan=[];if(/zítr|den|dnes|vyřeš/i.test(q))smartDailyPlan42(s,now).morning.forEach(x=>plan.push({action:'FOCUS',title:x.title,target:x.target}));if(/mail|odpov|urg/i.test(q))A(c.waiting.rows).slice(0,3).forEach(x=>plan.push({action:'DRAFT_FOLLOWUP',title:x.title||x.person,target:'waiting'}));if(/invest|pen/i.test(q))plan.push({action:'REVIEW_MONEY',title:copilot40(s,'peníze',now).answer,target:'money'});return {request:q,plan,contract:OS42_CONTRACT,status:'PROPOSAL_ONLY',requiresConfirmation:true}}
export function os42(s={},now=new Date()){return {version:OS42_VERSION,contract:OS42_CONTRACT,search:q=>universalSearch42(s,q),palette:q=>commandPalette42(s,q),decisionInbox:decisionInbox42(s,now),sla:personalSla42(s,now),relationships:relationshipMemory42(s),timeline:lifeTimeline42(s),daily:smartDailyPlan42(s,now),delegation:delegationOs42(s,now),finance:financialWhatIf42(s),theses:investmentThesis42(s),tickets:ticketMarketIntelligence42(s,now),opportunities:opportunityRadar42(s,now),waste:wasteDetector42(s),risk:personalRiskMap42(s,now),goals:goalEngine42(s),weekly:weeklyCeoReview42(s,now),graph:entityGraph40(s),forecast:forecastEngine40(s,now)}}