import {store} from './state.js';
import {h} from './utils.js';
import {ownEvent1100} from './runtimeOwnership1100.js';
import {buildUpgradeContext2050} from './osUpgrades2050.js';

export const AUTOMATION_SUITE2100_VERSION='2100.0.0';
export const AUTOMATION_NAMES2100=[
 'Personal SLA Engine','Escalation Rules','No-Progress Detector','Recurring Problem Detector','Decision Revisit Engine',
 'Decision Journal','Outcome Tracker','Assumption Tracker','Confidence Drift','What Changed Since Last Time',
 'Single Source Inspector','Data Provenance Graph','Conflicting Data Detector','Duplicate Entity Resolver','Unknown Value Registry',
 'Data Freshness SLA','Broken Link / Missing Attachment Audit','Import Quality Score','Schema Drift Guard','Canonical Merge Assistant',
 'Scenario Lab','Best / Base / Worst Case','Break-Even Finder','Sensitivity Tornado','Stress Test Mode',
 'Opportunity Cost Engine','Capital Competition View','Constraint Engine','Goal Feasibility Check','Plan B Generator',
 'Calendar Load Map','Deadline Density','Task Duration Learning','Realistic Day Planner','Buffer Planner',
 'Context Switching Score','Batching Suggestions','Energy-Aware Planning','Deferred Task Cost','Sunday Reset / Monday Launch',
 'Smart Notification Policy','Alert Deduplication','Alert Suppression Rules','Change Thresholds','Exception-Only Dashboard',
 'Silent Healthy State','Morning Brief Generator','Evening Reconciliation','Weekly Learning Report','Autonomous Maintenance Mode'
];

const OWNER='product.automation2100';
const A=v=>Array.isArray(v)?v:[];
const N=v=>Number.isFinite(Number(v))?Number(v):0;
const U=v=>String(v||'').trim().toUpperCase();
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
const txt=x=>String(x?.title||x?.name||x?.subject||x?.eventName||x?.event||'').trim();
const CLOSED=new Set(['DONE','HOTOVO','CLOSED','ARCHIVED','RESOLVED','PAID','SOLD','CANCELLED','CANCELED','COMPLETED','FINISHED']);
const open=x=>!CLOSED.has(U(x?.status||x?.workflow||x?.state||'OPEN'));
const parse=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?t:null};
const days=v=>{const t=parse(v);return t===null?null:Math.round((t-Date.now())/86400000)};
const age=v=>{const d=days(v);return d===null?null:-d};
const money=v=>Math.round(N(v)).toLocaleString('cs-CZ')+' Kč';
const pct=v=>(N(v)*100).toFixed(1).replace('.',',')+' %';
const sum=(rows,fn)=>rows.reduce((n,x)=>n+N(fn(x)),0);
const med=rows=>{const a=rows.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return 0;const i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2};
const taskDue=x=>x?.due||x?.dueAt||x?.dueDate||x?.deadline||x?.followUpAt||null;
const updated=x=>x?.updatedAt||x?.modifiedAt||x?.lastChangedAt||x?.createdAt||x?.date||null;
const route=x=>x?.area==='Práce'?'work':x?.area==='Reality'?'property':x?.area==='Vstupenky'?'tickets':x?.area==='Peníze'?'money':'inbox';
const f=(id,domain,title,o={})=>({id,domain,title,value:o.value||'—',detail:o.detail||'',tone:o.tone||'',route:o.route||'today',score:N(o.score),data:o.data||null});
const key=x=>norm(txt(x)).replace(/\b(urgent|dnes|zítra|zitri|úkol|ukol)\b/g,'').trim();
const allOpen=c=>[...c.tasks,...c.waiting];
const decisionRows=c=>allOpen(c).filter(x=>/rozhod|vyber|schval|koup|prodat|zm[eě]n|potvrdit/i.test(txt(x)+' '+String(x.notes||x.detail||'')));
const taskMinutes=x=>Math.max(5,N(x.minutes||x.estimateMinutes||x.durationMinutes||30));
const currentWeekStart=()=>{const d=new Date(),day=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day);return d.getTime()};

export function buildAutomationContext2100(input=null){
 const base=buildUpgradeContext2050(input||store.get()),s=base.s,calendar=A(s.calendar?.events).filter(open),decisions=A(s.decisionJournal||s.decisions),notifications=A(s.notifications||s.alerts),imports=A(s.importLog||s.imports),goals=A(s.goals||s.personalGoals).filter(open);
 return{...base,calendar,decisions,notifications,imports,goals};
}

export function personalSLA2100(c){const breached=allOpen(c).filter(x=>{const a=age(updated(x));return a!==null&&a>14}).length;return f(51,'Automatizace',AUTOMATION_NAMES2100[0],{value:breached+' po SLA',tone:breached?'bad':'good',detail:'Otevřené položky bez změny déle než 14 dní.',route:'inbox',score:breached*15});}
export function escalationRules2100(c){const esc=allOpen(c).filter(x=>{const d=days(taskDue(x));return d!==null&&d<=2}).length;return f(52,'Automatizace',AUTOMATION_NAMES2100[1],{value:esc+' eskalací',tone:esc?'warn':'good',detail:'Termín do 2 dnů automaticky zvyšuje prioritu.',route:'inbox',score:esc*12});}
export function noProgress2100(c){const rows=allOpen(c).filter(x=>{const a=age(updated(x));return a!==null&&a>=7&&!x.progress&&!x.lastAction});return f(53,'Automatizace',AUTOMATION_NAMES2100[2],{value:rows.length+' bez pohybu',tone:rows.length?'warn':'good',detail:'Otevřeno ≥7 dní bez evidovaného progress/lastAction.',route:'inbox',score:rows.length});}
export function recurringProblem2100(c){const m={};for(const x of allOpen(c)){const k=key(x);if(k)(m[k]||(m[k]=[])).push(x)}const rows=Object.entries(m).filter(([,v])=>v.length>=3);return f(54,'Automatizace',AUTOMATION_NAMES2100[3],{value:rows.length+' vzorců',tone:rows.length?'warn':'good',detail:rows.slice(0,3).map(([k,v])=>k+' ×'+v.length).join(' · ')||'Bez opakovaného vzorce.',route:'inbox'});}
export function decisionRevisit2100(c){const rows=c.decisions.filter(x=>{const d=days(x.reviewAt||x.revisitAt);return d!==null&&d<=0&&!x.closed});return f(55,'Rozhodnutí',AUTOMATION_NAMES2100[4],{value:rows.length+' k revizi',tone:rows.length?'warn':'good',detail:'Dřívější rozhodnutí s dosaženým review termínem.',route:'today'});}
export function decisionJournal2100(c){return f(56,'Rozhodnutí',AUTOMATION_NAMES2100[5],{value:c.decisions.length+' záznamů',detail:'Historie důvodu, vstupů a výsledku rozhodnutí.',route:'today'});}
export function outcomeTracker2100(c){const due=c.decisions.filter(x=>x.expectedOutcome&&!x.actualOutcome&&days(x.outcomeAt||x.reviewAt)<=0);return f(57,'Rozhodnutí',AUTOMATION_NAMES2100[6],{value:due.length+' nevyhodnocených',tone:due.length?'warn':'good',detail:'Rozhodnutí s očekávaným výsledkem bez skutečného výsledku.',route:'today'});}
export function assumptionTracker2100(c){const rows=c.decisions.filter(x=>A(x.assumptions).length>0),count=sum(rows,x=>A(x.assumptions).length);return f(58,'Rozhodnutí',AUTOMATION_NAMES2100[7],{value:count+' předpokladů',detail:rows.length+' rozhodnutí má explicitně oddělené předpoklady.',route:'today'});}
export function confidenceDrift2100(c){const rows=c.decisions.filter(x=>x.confidence!=null&&x.initialConfidence!=null),drift=rows.length?med(rows.map(x=>N(x.confidence)-N(x.initialConfidence))):0;return f(59,'Rozhodnutí',AUTOMATION_NAMES2100[8],{value:(drift>=0?'+':'')+Math.round(drift)+' b.',tone:drift<-15?'warn':drift>15?'good':'',detail:'Medián změny confidence proti okamžiku rozhodnutí.',route:'today'});}
export function changedSinceLast2100(c){const recent=[...allOpen(c),...c.records,...c.properties,...c.ticketItems].filter(x=>{const a=age(updated(x));return a!==null&&a<=1});return f(60,'Rozhodnutí',AUTOMATION_NAMES2100[9],{value:recent.length+' změn / 24 h',detail:'Záznamy změněné během posledního dne.',route:'today'});}

export function sourceInspector2100(c){const known=['tasks','ticketBook','propertyBook','personalVault','calendar','financePlan','projects'],present=known.filter(k=>c.s[k]!=null);return f(61,'Data',AUTOMATION_NAMES2100[10],{value:present.length+'/'+known.length+' canonical zdrojů',tone:present.length<5?'warn':'good',detail:present.join(' · '),route:'more'});}
export function provenanceGraph2100(c){const edges=[['Today','tasks'],['Money','personalVault'],['Tickets','ticketBook'],['Reality','propertyBook'],['Documents','personalVault'],['Work','projects']];const active=edges.filter(([,k])=>c.s[k]!=null);return f(62,'Data',AUTOMATION_NAMES2100[11],{value:active.length+' vazeb',detail:active.map(x=>x[0]+'←'+x[1]).join(' · '),route:'more'});}
export function conflictingData2100(c){const bankVals=A(c.s.personalVault?.records).filter(x=>x.recordType==='bank-data').map(x=>N(x.balance||x.amount)).filter(Boolean),conflict=bankVals.length>1&&Math.max(...bankVals)!==Math.min(...bankVals);return f(63,'Data',AUTOMATION_NAMES2100[12],{value:conflict?'1 konflikt':'0 konfliktů',tone:conflict?'bad':'good',detail:conflict?'Více bank-data záznamů obsahuje rozdílné nenulové zůstatky.':'Bez zjevného konfliktu u hlavního cash zdroje.',route:'more'});}
export function duplicateEntity2100(c){const rows=[...c.properties,...c.records,...c.projects],m={};for(const x of rows){const k=key(x);if(k)(m[k]=(m[k]||0)+1)}const dup=Object.entries(m).filter(x=>x[1]>1);return f(64,'Data',AUTOMATION_NAMES2100[13],{value:dup.length+' kandidátů',tone:dup.length?'warn':'good',detail:dup.slice(0,3).map(x=>x[0]+' ×'+x[1]).join(' · ')||'Bez jasných duplicit entit.',route:'more'});}
export function unknownRegistry2100(c){let n=0;n+=c.tasks.filter(x=>!taskDue(x)).length;n+=c.properties.filter(x=>!N(x.purchasePrice||x.priceCzk||x.price)).length;n+=c.records.filter(x=>!x.title).length;return f(65,'Data',AUTOMATION_NAMES2100[14],{value:n+' neznámých',tone:n?'warn':'good',detail:'Chybějící termíny, ceny nebo identita záznamu.',route:'more'});}
export function freshnessSLA2100(c){const stale=[...c.records,...c.properties,...c.ticketItems].filter(x=>{const a=age(updated(x));return a!==null&&a>30});return f(66,'Data',AUTOMATION_NAMES2100[15],{value:stale.length+' po SLA',tone:stale.length?'warn':'good',detail:'Canonical data starší než 30 dní.',route:'more'});}
export function brokenAttachment2100(c){const broken=c.records.filter(x=>A(x.attachments).some(a=>!a||(!a.url&&!a.path&&!a.id))||x.sourceUrl==='');return f(67,'Data',AUTOMATION_NAMES2100[16],{value:broken.length+' problémů',tone:broken.length?'bad':'good',detail:'Záznamy s prázdným nebo neadresovatelným attachmentem/odkazem.',route:'more'});}
export function importQuality2100(c){const bad=c.imports.filter(x=>x.errors?.length||x.invalidRows||x.status==='ERROR'),quality=c.imports.length?Math.max(0,Math.round(100*(1-bad.length/c.imports.length))):100;return f(68,'Data',AUTOMATION_NAMES2100[17],{value:quality+' %',tone:quality<80?'warn':'good',detail:bad.length+' problematických importů z '+c.imports.length+'.',route:'more'});}
export function schemaDrift2100(c){const versions=new Set(c.imports.map(x=>x.schemaVersion).filter(Boolean));return f(69,'Data',AUTOMATION_NAMES2100[18],{value:versions.size+' verzí',tone:versions.size>1?'warn':'good',detail:'Počet současně evidovaných schemaVersion v importech.',route:'more'});}
export function canonicalMerge2100(c){const candidates=duplicateEntity2100(c).value;return f(70,'Data',AUTOMATION_NAMES2100[19],{value:candidates,detail:'Merge assistant používá duplicate entity radar jako vstup a vyžaduje ruční potvrzení canonical záznamu.',route:'more'});}

const bestProperty=c=>c.property?.best||null;
export function scenarioLab2100(c){const b=bestProperty(c),price=N(b?.purchasePrice),rent=N(b?.monthlyRent||b?.rentCzk||b?.rent);return f(71,'Scénáře',AUTOMATION_NAMES2100[20],{value:b?(money(price)+' / '+money(rent)+'/m'):'Bez vstupu',detail:'Univerzální základ scénáře bere aktuální top Property deal; další domény lze přidat stejným kontraktem.',route:b?'property':'today'});}
export function threeCases2100(c){const b=bestProperty(c),rent=N(b?.monthlyRent||b?.rentCzk||b?.rent);return f(72,'Scénáře',AUTOMATION_NAMES2100[21],{value:b?(money(rent*.9)+' / '+money(rent)+' / '+money(rent*1.1)):'Bez vstupu',detail:'Worst / Base / Best nájem ±10 %.',route:'property'});}
export function breakEven2100(c){const b=bestProperty(c),price=N(b?.purchasePrice)+N(b?.renovationBudget||b?.renovationCost),rent=N(b?.monthlyRent||b?.rentCzk||b?.rent),months=rent>0?price/rent:0;return f(73,'Scénáře',AUTOMATION_NAMES2100[22],{value:months?Math.round(months)+' měs.':'Bez vstupu',detail:'Jednoduchý hrubý break-even investice proti měsíčnímu nájmu.',route:'property'});}
export function sensitivityTornado2100(c){const b=bestProperty(c),price=N(b?.purchasePrice),rent=N(b?.monthlyRent||b?.rentCzk||b?.rent),base=price?rent*12/price:0,rentImpact=base?Math.abs((rent*1.1*12/price)-base):0,priceImpact=base?Math.abs((rent*12/(price*.9))-base):0,winner=rentImpact>=priceImpact?'nájem':'kupní cena';return f(74,'Scénáře',AUTOMATION_NAMES2100[23],{value:winner,detail:'Největší lokální citlivost při ±10 % mezi nájmem a kupní cenou.',route:'property'});}
export function stressTest2100(c){const b=bestProperty(c),price=N(b?.purchasePrice),rent=N(b?.monthlyRent||b?.rentCzk||b?.rent),stress=price?rent*.8*11/price:0;return f(75,'Scénáře',AUTOMATION_NAMES2100[24],{value:price?pct(stress):'Bez vstupu',tone:stress&&stress<.04?'warn':'',detail:'Stress: -20 % nájem a 1 měsíc vacancy ročně.',route:'property'});}
export function opportunityCost2100(c){const p=A(c.property?.p?.candidates||c.property?.shortlist||c.properties).filter(Boolean).slice(0,2);let gap=0;if(p.length>=2)gap=N(p[0].score)-N(p[1].score);return f(76,'Scénáře',AUTOMATION_NAMES2100[25],{value:p.length>=2?gap.toFixed(1)+' bodu':'Chybí alternativa',detail:'Rozdíl skóre top 2 evidovaných investičních variant.',route:'property'});}
export function capitalCompetition2100(c){const demands=[['Reality',N(bestProperty(c)?.purchasePrice)],['Tickety',N(c.ticket?.p?.totalCapital)],['Úkoly',sum(c.tasks,x=>N(x.budget||x.cost))]].filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]);return f(77,'Scénáře',AUTOMATION_NAMES2100[26],{value:demands.length+' žadatelé',detail:demands.map(x=>x[0]+' '+money(x[1])).join(' · ')||'Bez známé konkurence o kapitál.',route:'money'});}
export function constraintEngine2100(c){const cash=N(c.moneyState.bank),demand=N(bestProperty(c)?.purchasePrice),breach=demand>cash&&cash>0;return f(78,'Scénáře',AUTOMATION_NAMES2100[27],{value:breach?'1 porušení':'0 porušení',tone:breach?'warn':'good',detail:breach?'Top property převyšuje evidovanou okamžitou hotovost.':'Žádný základní cash constraint breach.',route:'money'});}
export function goalFeasibility2100(c){const impossible=c.goals.filter(x=>x.targetAmount&&x.deadline&&N(x.targetAmount)>N(c.moneyState.bank)&&days(x.deadline)<=30);return f(79,'Scénáře',AUTOMATION_NAMES2100[28],{value:impossible.length+' rizik',tone:impossible.length?'warn':'good',detail:'30denní cíle, které převyšují evidovanou hotovost.',route:'money'});}
export function planB2100(c){const risk=constraintEngine2100(c).tone==='warn'||stressTest2100(c).tone==='warn';return f(80,'Scénáře',AUTOMATION_NAMES2100[29],{value:risk?'Aktivovat fallback':'Fallback připraven',tone:risk?'warn':'good',detail:risk?'Snížit kapitálový závazek, odložit nákup nebo zvýšit likvidní rezervu.':'Hlavní scénář neporušuje základní constrainty.',route:risk?'money':'today'});}

export function calendarLoad2100(c){const weekEnd=currentWeekStart()+7*86400000,rows=c.calendar.filter(x=>{const t=parse(x.start||x.date||x.startsAt);return t>=currentWeekStart()&&t<weekEnd});return f(81,'Kapacita',AUTOMATION_NAMES2100[30],{value:rows.length+' událostí',tone:rows.length>12?'warn':'',detail:'Aktuální kalendářová zátěž tohoto týdne.',route:'today'});}
export function deadlineDensity2100(c){const m={};for(const x of allOpen(c)){const d=taskDue(x);if(d){const k=String(d).slice(0,10);m[k]=(m[k]||0)+1}}const top=Math.max(0,...Object.values(m));return f(82,'Kapacita',AUTOMATION_NAMES2100[31],{value:top+' v jednom dni',tone:top>=5?'warn':'good',detail:'Maximum otevřených termínů sdílejících stejný den.',route:'inbox'});}
export function durationLearning2100(c){const done=A(c.s.tasks).filter(x=>!open(x)&&N(x.actualMinutes)>0),estimate=done.length?Math.round(med(done.map(x=>N(x.actualMinutes)))):30;return f(83,'Kapacita',AUTOMATION_NAMES2100[32],{value:estimate+' min',detail:done.length?'Medián skutečné délky dokončených úkolů.':'Fallback odhad 30 minut – chybí actualMinutes historie.',route:'inbox'});}
export function realisticDay2100(c){const today=c.tasks.filter(x=>{const d=days(taskDue(x));return d===0}),mins=sum(today,taskMinutes),capacity=8*60;return f(84,'Kapacita',AUTOMATION_NAMES2100[33],{value:mins+' / '+capacity+' min',tone:mins>capacity?'bad':mins>capacity*.8?'warn':'good',detail:'Součet odhadů dnešních úkolů proti 8h kapacitě.',route:'today',score:Math.max(0,mins-capacity)});}
export function bufferPlanner2100(c){const tight=c.tasks.filter(x=>{const d=days(taskDue(x));return d!==null&&d<=1&&taskMinutes(x)>=120});return f(85,'Kapacita',AUTOMATION_NAMES2100[34],{value:tight.length+' bez rezervy',tone:tight.length?'warn':'good',detail:'Dlouhé úkoly s termínem dnes/zítra.',route:'today'});}
export function contextSwitch2100(c){const today=c.tasks.filter(x=>days(taskDue(x))===0),areas=new Set(today.map(x=>x.area||x.category||'Ostatní'));const score=Math.min(100,Math.max(0,(areas.size-2)*20));return f(86,'Kapacita',AUTOMATION_NAMES2100[35],{value:score+'/100',tone:score>=60?'warn':'good',detail:areas.size+' různých kontextů v dnešních úkolech.',route:'today'});}
export function batching2100(c){const m={};for(const x of c.tasks){const k=norm(x.area||x.category||'Ostatní');m[k]=(m[k]||0)+1}const batches=Object.entries(m).filter(x=>x[1]>=2);return f(87,'Kapacita',AUTOMATION_NAMES2100[36],{value:batches.length+' batchů',detail:batches.slice(0,4).map(x=>x[0]+' ×'+x[1]).join(' · ')||'Málo podobných úkolů k dávkování.',route:'inbox'});}
export function energyPlanning2100(c){const hard=c.tasks.filter(x=>taskMinutes(x)>=90||N(x.priority)>=80),light=c.tasks.filter(x=>taskMinutes(x)<=30);return f(88,'Kapacita',AUTOMATION_NAMES2100[37],{value:hard.length+' těžkých / '+light.length+' lehkých',detail:'Těžké bloky směřovat do high-energy části dne, drobnosti batchovat.',route:'today'});}
export function deferredCost2100(c){const overdue=c.tasks.filter(x=>days(taskDue(x))<0),cost=sum(overdue,x=>N(x.delayCost||x.penalty||x.dailyCost));return f(89,'Kapacita',AUTOMATION_NAMES2100[38],{value:cost?money(cost):overdue.length+' po termínu',tone:overdue.length?'warn':'good',detail:cost?'Známý náklad odkladu z overdue úkolů.':'Bez explicitního delayCost; zobrazen počet overdue.',route:'inbox'});}
export function weeklyReset2100(c){const now=new Date(),isSun=now.getDay()===0,isMon=now.getDay()===1,openCount=c.tasks.length;return f(90,'Kapacita',AUTOMATION_NAMES2100[39],{value:isSun?'Reset dnes':isMon?'Launch dnes':openCount+' otevřených',tone:(isSun||isMon)&&openCount?'warn':'',detail:'Týdenní reset čistí priority; Monday Launch vybírá top priority týdne.',route:'today'});}

const exceptionCount=c=>personalSLA2100(c).score+noProgress2100(c).score+conflictingData2100(c).score+brokenAttachment2100(c).score+constraintEngine2100(c).score+realisticDay2100(c).score;
export function smartNotifications2100(c){const critical=[personalSLA2100(c),conflictingData2100(c),realisticDay2100(c)].filter(x=>x.tone==='bad'||x.tone==='warn');return f(91,'Alerty',AUTOMATION_NAMES2100[40],{value:critical.length+' relevantních',detail:'Notifikovat jen změny s akcí nebo překročeným prahem.',route:'today'});}
export function alertDedup2100(c){const m={};for(const x of c.notifications){const k=norm(x.key||x.title||x.message);if(k)m[k]=(m[k]||0)+1}const dup=Object.values(m).filter(n=>n>1).reduce((a,n)=>a+n-1,0);return f(92,'Alerty',AUTOMATION_NAMES2100[41],{value:dup+' duplicit',tone:dup?'warn':'good',detail:'Opakované notifikace se stejným klíčem/titulem.',route:'today'});}
export function suppressionRules2100(c){const suppressed=c.notifications.filter(x=>x.suppressed||x.snoozedUntil&&days(x.snoozedUntil)>0);return f(93,'Alerty',AUTOMATION_NAMES2100[42],{value:suppressed.length+' potlačených',detail:'Alerty s aktivním suppress/snooze pravidlem.',route:'today'});}
export function changeThresholds2100(c){const material=c.notifications.filter(x=>N(x.delta)>=N(x.threshold||0)&&N(x.threshold||0)>0);return f(94,'Alerty',AUTOMATION_NAMES2100[43],{value:material.length+' materiálních',detail:'Alerty, kde delta překročila explicitní práh.',route:'today'});}
export function exceptionDashboard2100(c){const n=exceptionCount(c);return f(95,'Alerty',AUTOMATION_NAMES2100[44],{value:n+' výjimek',tone:n?'warn':'good',detail:'Zobrazuje pouze odchylky, ne zdravé moduly.',route:'today',score:n});}
export function silentHealthy2100(c){const n=exceptionCount(c);return f(96,'Alerty',AUTOMATION_NAMES2100[45],{value:n?'Aktivní upozornění':'Ticho',tone:n?'warn':'good',detail:n?'Systém mluví, protože existují výjimky.':'Zdravý stav nic zbytečně nehlásí.',route:'today'});}
export function morningBrief2100(c){const changed=changedSinceLast2100(c),today=c.tasks.filter(x=>days(taskDue(x))===0),overdue=c.tasks.filter(x=>days(taskDue(x))<0);return f(97,'Alerty',AUTOMATION_NAMES2100[46],{value:today.length+' dnes / '+overdue.length+' overdue',tone:overdue.length?'bad':today.length?'warn':'good',detail:changed.value+' · '+(today.slice(0,3).map(txt).join(' · ')||'Bez dnešních úkolů.'),route:'today'});}
export function eveningReconciliation2100(c){const doneToday=A(c.s.tasks).filter(x=>!open(x)&&age(x.completedAt||x.updatedAt)===0),carry=c.tasks.filter(x=>days(taskDue(x))<0);return f(98,'Alerty',AUTOMATION_NAMES2100[47],{value:doneToday.length+' hotovo / '+carry.length+' přesun',tone:carry.length?'warn':'good',detail:'Večerní uzávěrka hotových a přenášených věcí.',route:'inbox'});}
export function weeklyLearning2100(c){const done=A(c.s.tasks).filter(x=>!open(x)&&parse(x.completedAt)>=currentWeekStart()),late=done.filter(x=>x.due&&parse(x.completedAt)>parse(x.due)),accuracy=done.length?Math.round(100*(1-late.length/done.length)):100;return f(99,'Alerty',AUTOMATION_NAMES2100[48],{value:accuracy+' % včas',tone:accuracy<70?'warn':'good',detail:done.length+' dokončených úkolů tento týden, '+late.length+' po termínu.',route:'today'});}
export function autonomousMaintenance2100(c){const checks=[duplicateEntity2100(c),conflictingData2100(c),brokenAttachment2100(c),schemaDrift2100(c),freshnessSLA2100(c)],issues=checks.filter(x=>x.tone==='bad'||x.tone==='warn').length;return f(100,'Alerty',AUTOMATION_NAMES2100[49],{value:issues+' servisních oblastí',tone:issues?'warn':'good',detail:'Automatický audit datové kvality, schémat, duplicit, příloh a freshness.',route:'more',score:issues});}

export const AUTOMATION_BUILDERS2100=[
 personalSLA2100,escalationRules2100,noProgress2100,recurringProblem2100,decisionRevisit2100,decisionJournal2100,outcomeTracker2100,assumptionTracker2100,confidenceDrift2100,changedSinceLast2100,
 sourceInspector2100,provenanceGraph2100,conflictingData2100,duplicateEntity2100,unknownRegistry2100,freshnessSLA2100,brokenAttachment2100,importQuality2100,schemaDrift2100,canonicalMerge2100,
 scenarioLab2100,threeCases2100,breakEven2100,sensitivityTornado2100,stressTest2100,opportunityCost2100,capitalCompetition2100,constraintEngine2100,goalFeasibility2100,planB2100,
 calendarLoad2100,deadlineDensity2100,durationLearning2100,realisticDay2100,bufferPlanner2100,contextSwitch2100,batching2100,energyPlanning2100,deferredCost2100,weeklyReset2100,
 smartNotifications2100,alertDedup2100,suppressionRules2100,changeThresholds2100,exceptionDashboard2100,silentHealthy2100,morningBrief2100,eveningReconciliation2100,weeklyLearning2100,autonomousMaintenance2100
];

export function automationSuite2100(input=null){const c=buildAutomationContext2100(input);return{version:AUTOMATION_SUITE2100_VERSION,context:c,features:AUTOMATION_BUILDERS2100.map(fn=>fn(c))};}
const row=x=>'<button type="button" class="pr1300-row pr1300-clickrow" data-automation2100="'+x.id+'" data-automation-route="'+h(x.route)+'"><div class="pr1300-row-main"><b>'+x.id+'. '+h(x.title)+'</b><small>'+h(x.detail)+'</small></div><div class="pr1300-row-side '+h(x.tone)+'">'+h(x.value)+' <span class="os1500-row-arrow">→</span></div></button>';
export function renderAutomationCenter2100(){
 const host=document.querySelector('#moreView');if(!host)return false;const model=automationSuite2100(),features=model.features,bad=features.filter(x=>x.tone==='bad').length,warn=features.filter(x=>x.tone==='warn').length;
 host.innerHTML='<div class="pr1300-shell" data-automation2100-center><div class="pr1300-head"><div><div class="pr1300-kicker">OS Automation & Learning · dalších 50</div><h1>SLA, scénáře, kapacita, alerty a samoúdržba.</h1><p>Druhá intelligence vrstva čte stejná canonical data jako OS. Nic neduplikuje a automatické merge/akce bez potvrzení neprovádí.</p></div><span class="pr1300-status '+(bad?'bad':warn?'warn':'good')+'">'+bad+' červených · '+warn+' žlutých</span></div><section class="pr1320-now"><div><div class="pr1300-kicker">Autonomní údržba</div><h2>'+h(autonomousMaintenance2100(model.context).value)+'</h2><p>'+h(autonomousMaintenance2100(model.context).detail)+'</p></div><div class="pr1320-now-actions"><button class="pr1300-btn" type="button" data-automation2100-back>Zpět na Dokumenty</button></div></section>';
 for(const domain of ['Automatizace','Rozhodnutí','Data','Scénáře','Kapacita','Alerty']){const rows=features.filter(x=>x.domain===domain);host.innerHTML+='<section class="pr1300-panel"><div class="pr1300-panel-head"><h2>'+domain+'</h2><span>'+rows.length+' modulů</span></div><div class="os1500-direct-list">'+rows.map(row).join('')+'</div></section>'}
 host.innerHTML+='</div>';host.__automation2100=model;
 if(!host.dataset.automation2100Bound){host.dataset.automation2100Bound='1';ownEvent1100(OWNER,host,'click',async e=>{if(e.target.closest('[data-automation2100-back]')){const m=await import('./documentsPage141.js');m.renderDocumentsPage141?.();return}const el=e.target.closest('[data-automation2100]');if(el){const x=host.__automation2100?.features?.find(y=>String(y.id)===el.dataset.automation2100);if(x?.route&&x.route!=='more')window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:x.route}));}})}
 window.__KAMIL_AUTOMATION2100__={healthy:true,version:AUTOMATION_SUITE2100_VERSION,count:features.length,bad,warn,names:[...AUTOMATION_NAMES2100],at:Date.now()};return true;
}
