import {store} from './state.js';
import {h} from './utils.js';
import {ownEvent1100} from './runtimeOwnership1100.js';
import {buildAutomationContext2100} from './osAutomation2100.js';

export const EXECUTION_SUITE2200_VERSION='2200.0.0';
export const EXECUTION_NAMES2200=[
 'Action Executor','One-Click Resolve','Safe Auto-Complete Rules','Delegation Router','Delegation Tracker',
 'Owner Missing Detector','Blocked Task Resolver','Dependency Graph','Critical Path Engine','Auto-Replan After Delay',
 'Predictive Deadline Risk','Forecast Accuracy Tracker','Expected Completion Date','Workload Forecast 30 Days','Cash Need Forecast',
 'Liquidity Warning Forecast','Property Cashflow Forecast','Ticket Exposure Forecast','Project Billing Forecast','Forecast Confidence Bands',
 'Personal Knowledge Graph','Entity Timeline','Relationship Map','Conversation-to-Entity Linking','Document-to-Entity Linking',
 'Automatic Entity Resolution','Memory Relevance Engine','Historical Similarity Search','Past Decision Comparator','Long-Term Pattern Memory',
 'Email Action Extractor','Attachment Intake Pipeline','Calendar Action Extractor','Meeting Outcome Tracker','Reply Needed Detector',
 'Promise Tracker','Outbound Promise Tracker','Contact Context Card','Communication Gap Detector','Auto-Draft Follow-Up',
 'Permissioned Autopilot','Dry-Run Mode','Undo Ledger','Action Audit Trail','Autonomy Risk Levels',
 'Approval Inbox','Automation Kill Switch','Rule Conflict Detector','Simulation Before Automation','OS Governor'
];

const OWNER='product.execution2200';
const A=v=>Array.isArray(v)?v:[];
const N=v=>Number.isFinite(Number(v))?Number(v):0;
const U=v=>String(v||'').trim().toUpperCase();
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
const txt=x=>String(x?.title||x?.name||x?.subject||x?.eventName||x?.event||'').trim();
const CLOSED=new Set(['DONE','HOTOVO','CLOSED','ARCHIVED','RESOLVED','PAID','SOLD','CANCELLED','CANCELED','COMPLETED','FINISHED']);
const open=x=>!CLOSED.has(U(x?.status||x?.workflow||x?.state||'OPEN'));
const parse=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?t:null};
const days=v=>{const t=parse(v);return t===null?null:Math.round((t-Date.now())/86400000)};
const age=v=>{const d=days(v);return d===null?null:-d};
const money=v=>Math.round(N(v)).toLocaleString('cs-CZ')+' Kč';
const pct=v=>(N(v)*100).toFixed(1).replace('.',',')+' %';
const sum=(rows,fn)=>rows.reduce((n,x)=>n+N(fn(x)),0);
const med=rows=>{const a=rows.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return 0;const i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2};
const due=x=>x?.due||x?.dueAt||x?.deadline||x?.followUpAt||null;
const updated=x=>x?.updatedAt||x?.modifiedAt||x?.lastChangedAt||x?.createdAt||x?.date||null;
const route=x=>x?.area==='Práce'?'work':x?.area==='Reality'?'property':x?.area==='Vstupenky'?'tickets':x?.area==='Peníze'?'money':'inbox';
const key=x=>norm(txt(x));
const f=(id,domain,title,o={})=>({id,domain,title,value:o.value||'—',detail:o.detail||'',tone:o.tone||'',route:o.route||'today',score:N(o.score),data:o.data||null});
const allOpen=c=>[...c.tasks,...c.waiting,...c.projects.filter(open)];
const autonomy=s=>({enabled:false,dryRun:true,killSwitch:true,approvals:[],rules:[],simulations:[],riskPolicy:{LOW:'AUTO_IF_ALLOWED',MEDIUM:'APPROVAL',HIGH:'BLOCKED'},...(s.autonomy2200||{})});
const messages=c=>[...A(c.s.messages),...A(c.s.emailActions),...A(c.s.personalInbox?.items)];
const contacts=c=>A(c.s.contacts||c.s.people||c.s.familyHome?.members);
const docs=c=>A(c.records);
const dependencies=x=>A(x?.dependsOn||x?.dependencies||x?.blockedBy);

export function buildExecutionContext2200(input=null){
 const base=buildAutomationContext2100(input||store.get()),s=base.s;
 return{...base,autonomy:autonomy(s),messages:messages(base),contacts:contacts(base),docs:docs(base)};
}

export function actionExecutor2200(c){const executable=allOpen(c).filter(x=>!x.blocked&&!dependencies(x).length&&txt(x)).length;return f(101,'Execution',EXECUTION_NAMES2200[0],{value:executable+' proveditelných',detail:'Otevřené položky bez známého blockeru nebo dependency.',route:'inbox'});}
export function oneClickResolve2200(c){const rows=c.tasks.filter(x=>open(x)&&['LOW','TRIVIAL'].includes(U(x.risk||x.riskLevel))&&!x.blocked);return f(102,'Execution',EXECUTION_NAMES2200[1],{value:rows.length+' kandidátů',detail:'Pouze nízkorizikové úkoly; dokončení vždy vyžaduje explicitní klik.',route:'inbox'});}
export function safeAutoComplete2200(c){const rows=c.tasks.filter(x=>open(x)&&x.autoComplete===true&&U(x.risk||'LOW')==='LOW');return f(103,'Execution',EXECUTION_NAMES2200[2],{value:rows.length+' pravidel',tone:c.autonomy.killSwitch&&rows.length?'warn':'good',detail:c.autonomy.killSwitch?'Kill switch blokuje automatické dokončení.':'Povoleny jsou jen explicitní LOW-risk autoComplete položky.',route:'inbox'});}
export function delegationRouter2200(c){const candidates=c.tasks.filter(x=>open(x)&&!x.owner&&/zavolat|poslat|vyzved|kontrola|ověřit|overit|dodat/i.test(txt(x)+' '+String(x.notes||'')));return f(104,'Execution',EXECUTION_NAMES2200[3],{value:candidates.length+' k přiřazení',tone:candidates.length?'warn':'good',detail:'Úkoly vhodné k delegaci podle typu akce a chybějícího ownera.',route:'inbox'});}
export function delegationTracker2200(c){const active=A(c.s.delegations).filter(open);return f(105,'Execution',EXECUTION_NAMES2200[4],{value:active.length+' delegovaných',tone:active.some(x=>days(due(x))<0)?'bad':active.length?'warn':'good',detail:'Aktivní delegace včetně follow-up termínů.',route:'inbox'});}
export function ownerMissing2200(c){const rows=allOpen(c).filter(x=>!x.owner&&!x.assignee&&!x.responsible);return f(106,'Execution',EXECUTION_NAMES2200[5],{value:rows.length+' bez ownera',tone:rows.length?'warn':'good',detail:'Otevřené akce bez odpovědné osoby.',route:'inbox'});}
export function blockedResolver2200(c){const rows=allOpen(c).filter(x=>x.blocked||dependencies(x).length||/čeká|ceka|blok/i.test(String(x.status||x.notes||'')));return f(107,'Execution',EXECUTION_NAMES2200[6],{value:rows.length+' blokací',tone:rows.length?'warn':'good',detail:rows.slice(0,3).map(x=>txt(x)||'Blokovaná položka').join(' · ')||'Bez známých blokací.',route:'inbox'});}
export function dependencyGraph2200(c){const edges=allOpen(c).reduce((n,x)=>n+dependencies(x).length,0);return f(108,'Execution',EXECUTION_NAMES2200[7],{value:edges+' vazeb',detail:'Explicitní dependsOn/dependencies/blockedBy vazby mezi otevřenými položkami.',route:'work'});}
export function criticalPath2200(c){const rows=allOpen(c).filter(x=>dependencies(x).length&&due(x)).sort((a,b)=>(days(due(a))??999)-(days(due(b))??999));return f(109,'Execution',EXECUTION_NAMES2200[8],{value:rows.length?txt(rows[0]):'Bez kritické cesty',tone:rows.length&&days(due(rows[0]))<=3?'bad':'good',detail:rows.length?'Nejbližší termín s explicitní závislostí.':'Chybí dependency + deadline kombinace.',route:'work'});}
export function autoReplan2200(c){const delayed=allOpen(c).filter(x=>days(due(x))<0&&dependencies(x).length);return f(110,'Execution',EXECUTION_NAMES2200[9],{value:delayed.length+' k přepočtu',tone:delayed.length?'warn':'good',detail:'Overdue položky, jejichž posun může ovlivnit závislé kroky.',route:'work'});}

export function deadlineRisk2200(c){const rows=allOpen(c).filter(x=>{const d=days(due(x)),a=age(updated(x));return d!==null&&d>=0&&d<=7&&a!==null&&a>=Math.max(2,d)});return f(111,'Forecast',EXECUTION_NAMES2200[10],{value:rows.length+' rizik',tone:rows.length?'bad':'good',detail:'Blízký termín + dlouho bez posunu.',route:'today',score:rows.length*20});}
export function forecastAccuracy2200(c){const rows=A(c.s.forecasts).filter(x=>x.predicted!=null&&x.actual!=null),errs=rows.map(x=>Math.abs(N(x.actual)-N(x.predicted))/(Math.abs(N(x.actual))||1)),acc=rows.length?Math.max(0,Math.round(100*(1-med(errs)))):0;return f(112,'Forecast',EXECUTION_NAMES2200[11],{value:rows.length?acc+' %':'Bez historie',detail:'Medián relativní chyby uzavřených forecastů.',route:'today'});}
export function expectedCompletion2200(c){const mins=c.tasks.filter(open).reduce((n,x)=>n+Math.max(15,N(x.estimateMinutes||x.minutes||30)),0),daysNeed=Math.ceil(mins/(6*60));return f(113,'Forecast',EXECUTION_NAMES2200[12],{value:daysNeed?daysNeed+' prac. dnů':'0 dní',detail:'Hrubý odhad při 6 hodinách čisté kapacity denně.',route:'today'});}
export function workload30d2200(c){const rows=c.tasks.filter(x=>{const d=days(due(x));return open(x)&&d!==null&&d>=0&&d<=30}),mins=sum(rows,x=>Math.max(15,N(x.estimateMinutes||x.minutes||30)));return f(114,'Forecast',EXECUTION_NAMES2200[13],{value:Math.round(mins/60)+' h / 30 dní',tone:mins>120*60?'warn':'',detail:rows.length+' úkolů s termínem do 30 dní.',route:'today'});}
export function cashNeed2200(c){const out=A(c.s.financePlan?.cashflow||c.s.financePlan?.upcoming).filter(x=>{const d=days(x.date||x.due);return d!==null&&d>=0&&d<=30&&N(x.amount)<0}),need=Math.abs(sum(out,x=>N(x.amount)));return f(115,'Forecast',EXECUTION_NAMES2200[14],{value:money(need),detail:'Známé záporné cashflow položky v příštích 30 dnech.',route:'money'});}
export function liquidityWarning2200(c){const cash=N(c.moneyState.bank),need=Math.abs(sum(A(c.s.financePlan?.cashflow||c.s.financePlan?.upcoming).filter(x=>{const d=days(x.date||x.due);return d!==null&&d>=0&&d<=30}),x=>Math.min(0,N(x.amount)))),ratio=cash>0?need/cash:need?Infinity:0;return f(116,'Forecast',EXECUTION_NAMES2200[15],{value:ratio===Infinity?'kritické':pct(ratio),tone:ratio>0.8?'bad':ratio>0.5?'warn':'good',detail:'Známé 30denní odtoky proti evidované hotovosti.',route:'money'});}
export function propertyCashflow2200(c){const b=c.property?.best,rent=N(b?.monthlyRent||b?.rentCzk||b?.rent),cost=N(b?.monthlyCosts||b?.feesMonthly||b?.fundMonthly),annual=(rent-cost)*12;return f(117,'Forecast',EXECUTION_NAMES2200[16],{value:b?money(annual)+'/rok':'Bez kandidáta',detail:'12měsíční jednoduchý provozní cashflow před financováním a daní.',route:'property'});}
export function ticketExposureForecast2200(c){const rows=c.ticketItems.filter(open),soon=sum(rows.filter(x=>{const d=days(x.eventDate||x.date);return d!==null&&d>=0&&d<=30}),x=>N(x.buy||x.buyTotalCzk||x.cost));return f(118,'Forecast',EXECUTION_NAMES2200[17],{value:money(soon),tone:soon>0?'warn':'good',detail:'Nákupní kapitál v aktivních ticketech s eventem do 30 dní.',route:'tickets'});}
export function projectBillingForecast2200(c){const rows=c.projects.filter(x=>open(x)&&N(x.invoiceExpected||x.billingAmount||x.remainingToInvoice)>0),total=sum(rows,x=>N(x.invoiceExpected||x.billingAmount||x.remainingToInvoice));return f(119,'Forecast',EXECUTION_NAMES2200[18],{value:money(total),detail:rows.length+' projektů s evidovanou očekávanou fakturací.',route:'work'});}
export function confidenceBands2200(c){const hist=A(c.s.forecasts).filter(x=>x.errorPct!=null||x.predicted!=null&&x.actual!=null),err=hist.length?med(hist.map(x=>x.errorPct!=null?Math.abs(N(x.errorPct)):Math.abs(N(x.actual)-N(x.predicted))/(Math.abs(N(x.actual))||1))):.2;return f(120,'Forecast',EXECUTION_NAMES2200[19],{value:'± '+Math.round(err*100)+' %',detail:hist.length?'Interval podle historické mediánové chyby forecastů.':'Výchozí pásmo ±20 % bez historie.',route:'today'});}

export function knowledgeGraph2200(c){const entities=c.contacts.length+c.projects.length+c.properties.length+c.ticketItems.length+c.docs.length;return f(121,'Knowledge',EXECUTION_NAMES2200[20],{value:entities+' entit',detail:'Osoby, projekty, reality, tickety a dokumenty jako společný graph vstup.',route:'more'});}
export function entityTimeline2200(c){const dated=[...c.tasks,...c.projects,...c.docs,...c.ticketItems].filter(x=>parse(updated(x)));return f(122,'Knowledge',EXECUTION_NAMES2200[21],{value:dated.length+' událostí',detail:'Entity timeline lze sestavit ze všech záznamů s datem změny/vzniku.',route:'more'});}
export function relationshipMap2200(c){const links=sum([...c.projects,...c.tasks,...c.docs],x=>A(x.contactIds||x.people||x.relatedIds).length);return f(123,'Knowledge',EXECUTION_NAMES2200[22],{value:links+' vazeb',detail:'Explicitní propojení na osoby nebo související entity.',route:'more'});}
export function conversationLinking2200(c){const linked=c.messages.filter(x=>x.entityId||x.projectId||x.propertyId||x.ticketId).length;return f(124,'Knowledge',EXECUTION_NAMES2200[23],{value:linked+'/'+c.messages.length+' propojeno',tone:c.messages.length&&linked/c.messages.length<.5?'warn':'good',detail:'Komunikace s explicitním entity/project/property/ticket odkazem.',route:'inbox'});}
export function documentLinking2200(c){const linked=c.docs.filter(x=>x.entityId||x.projectId||x.propertyId||x.policyId||A(x.relatedIds).length).length;return f(125,'Knowledge',EXECUTION_NAMES2200[24],{value:linked+'/'+c.docs.length+' propojeno',tone:c.docs.length&&linked/c.docs.length<.5?'warn':'good',detail:'Dokumenty napojené na konkrétní entitu.',route:'more'});}
export function autoEntityResolution2200(c){const all=[...c.contacts,...c.projects,...c.properties,...c.docs],m={};for(const x of all){const k=key(x);if(k)(m[k]=(m[k]||0)+1)}const dup=Object.values(m).filter(n=>n>1).length;return f(126,'Knowledge',EXECUTION_NAMES2200[25],{value:dup+' kandidátů',tone:dup?'warn':'good',detail:'Stejné normalizované názvy napříč entity typy; merge bez potvrzení neproběhne.',route:'more'});}
export function memoryRelevance2200(c){const openTerms=new Set(c.tasks.filter(open).flatMap(x=>norm(txt(x)+' '+String(x.notes||'')).split(/\s+/).filter(w=>w.length>=5))),hits=c.docs.filter(x=>norm(txt(x)+' '+String(x.notes||'')).split(/\s+/).some(w=>openTerms.has(w))).length;return f(127,'Knowledge',EXECUTION_NAMES2200[26],{value:hits+' relevantních',detail:'Historické dokumenty sdílející významnější termín s otevřenými úkoly.',route:'more'});}
export function similaritySearch2200(c){const done=A(c.s.tasks).filter(x=>!open(x)),openRows=c.tasks.filter(open),hits=openRows.filter(x=>done.some(y=>{const a=new Set(norm(txt(x)).split(/\s+/)),b=norm(txt(y)).split(/\s+/);return b.filter(w=>a.has(w)&&w.length>4).length>=2})).length;return f(128,'Knowledge',EXECUTION_NAMES2200[27],{value:hits+' podobných',detail:'Otevřené úkoly s alespoň dvěma společnými významnými slovy s historickým úkolem.',route:'inbox'});}
export function pastDecisionComparator2200(c){const decisions=A(c.s.decisionJournal||c.s.decisions),openRows=c.tasks.filter(open),hits=openRows.filter(x=>decisions.some(d=>norm(txt(d)).includes(norm(txt(x)).slice(0,12))&&txt(x))).length;return f(129,'Knowledge',EXECUTION_NAMES2200[28],{value:hits+' shod',detail:'Nové otevřené věci s podobným názvem jako historické rozhodnutí.',route:'today'});}
export function longTermPattern2200(c){const history=[...A(c.s.audit),...A(c.s.learning?.feedback)],months=new Set(history.map(x=>String(x.at||x.date||'').slice(0,7)).filter(Boolean));return f(130,'Knowledge',EXECUTION_NAMES2200[29],{value:months.size+' měsíců',detail:history.length+' audit/learning záznamů pro dlouhodobé patterny.',route:'more'});}

export function emailActionExtractor2200(c){const rows=c.messages.filter(x=>/prosím|please|do |potřebuji|potrebuji|termín|deadline|zaplat|pošlete|poslete/i.test(String(x.body||x.text||x.notes||'')));return f(131,'Communication',EXECUTION_NAMES2200[30],{value:rows.length+' akcí',tone:rows.length?'warn':'good',detail:'Zprávy obsahující explicitní požadavek, termín nebo platbu.',route:'inbox'});}
export function attachmentIntake2200(c){const attachments=sum(c.messages,x=>A(x.attachments).length),unlinked=sum(c.messages,x=>A(x.attachments).filter(a=>!a.entityId&&!a.recordId).length);return f(132,'Communication',EXECUTION_NAMES2200[31],{value:unlinked+' nezařazených',tone:unlinked?'warn':'good',detail:attachments+' příloh celkem; nezařazené čekají na klasifikaci.',route:'more'});}
export function calendarActionExtractor2200(c){const rows=c.calendar.filter(x=>/follow|úkol|ukol|dodat|poslat|zavolat|připrav|priprav/i.test(String(x.notes||x.description||x.summary||'')));return f(133,'Communication',EXECUTION_NAMES2200[32],{value:rows.length+' follow-upů',detail:'Kalendářové události obsahující akční slovesa.',route:'today'});}
export function meetingOutcome2200(c){const meetings=c.calendar.filter(x=>/meeting|schůz|schuz|call|porada/i.test(txt(x)+' '+String(x.type||''))),missing=meetings.filter(x=>days(x.end||x.date)<0&&!x.outcome&&!x.notesAfter).length;return f(134,'Communication',EXECUTION_NAMES2200[33],{value:missing+' bez outcome',tone:missing?'warn':'good',detail:meetings.length+' schůzek/callů v datech.',route:'today'});}
export function replyNeeded2200(c){const rows=c.messages.filter(x=>open(x)&&(x.replyNeeded===true||/odpověd|reply/i.test(String(x.bucket||x.action||x.status||''))));return f(135,'Communication',EXECUTION_NAMES2200[34],{value:rows.length+' odpovědí',tone:rows.length?'warn':'good',detail:'Komunikace explicitně označená k odpovědi.',route:'inbox'});}
export function promiseTracker2200(c){const rows=c.messages.filter(x=>x.promisedBy&&x.promiseDue&&open(x));return f(136,'Communication',EXECUTION_NAMES2200[35],{value:rows.length+' příslibů',tone:rows.some(x=>days(x.promiseDue)<0)?'bad':rows.length?'warn':'good',detail:'Co ostatní slíbili a má termín.',route:'inbox'});}
export function outboundPromise2200(c){const rows=c.messages.filter(x=>x.promisedByMe&&x.promiseDue&&open(x));return f(137,'Communication',EXECUTION_NAMES2200[36],{value:rows.length+' mých příslibů',tone:rows.some(x=>days(x.promiseDue)<0)?'bad':rows.length?'warn':'good',detail:'Závazky, které jsi slíbil ty.',route:'inbox'});}
export function contactContext2200(c){const linked=new Set(c.messages.map(x=>x.contactId||x.personId).filter(Boolean));return f(138,'Communication',EXECUTION_NAMES2200[37],{value:linked.size+' kontaktů',detail:'Kontakty s dohledatelným komunikačním kontextem.',route:'inbox'});}
export function communicationGap2200(c){const rows=c.contacts.filter(x=>{const a=age(x.lastContactAt||x.updatedAt);return x.important&&a!==null&&a>30});return f(139,'Communication',EXECUTION_NAMES2200[38],{value:rows.length+' mezer',tone:rows.length?'warn':'good',detail:'Důležité kontakty bez kontaktu déle než 30 dní.',route:'inbox'});}
export function autoDraftFollowup2200(c){const n=replyNeeded2200(c).value.split(' ')[0],prom=promiseTracker2200(c).value.split(' ')[0];return f(140,'Communication',EXECUTION_NAMES2200[39],{value:(N(n)+N(prom))+' draftů',detail:'Kandidáti na návrh follow-upu; odeslání nikdy neproběhne bez potvrzení.',route:'inbox'});}

export function permissionedAutopilot2200(c){return f(141,'Governance',EXECUTION_NAMES2200[40],{value:c.autonomy.enabled?'Povoleno':'Vypnuto',tone:c.autonomy.enabled&&!c.autonomy.killSwitch?'warn':'good',detail:'Autonomie respektuje risk policy, approvals, dry-run a kill switch.',route:'more'});}
export function dryRunMode2200(c){return f(142,'Governance',EXECUTION_NAMES2200[41],{value:c.autonomy.dryRun?'Zapnuto':'Vypnuto',tone:c.autonomy.dryRun?'good':'warn',detail:'V dry-run se nic nemění; pouze se simuluje výsledek.',route:'more'});}
export function undoLedger2200(c){const n=typeof store.undoCount==='function'?store.undoCount():A(c.s.undo).length;return f(143,'Governance',EXECUTION_NAMES2200[42],{value:n+' vratných kroků',detail:'Undo stack spravovaný canonical state storem.',route:'more'});}
export function actionAudit2200(c){const rows=A(c.s.audit);return f(144,'Governance',EXECUTION_NAMES2200[43],{value:rows.length+' audit záznamů',detail:'Historie změn stavu a důvodu mutace.',route:'more'});}
export function autonomyRisk2200(c){const p=c.autonomy.riskPolicy||{},configured=['LOW','MEDIUM','HIGH'].filter(k=>p[k]).length;return f(145,'Governance',EXECUTION_NAMES2200[44],{value:configured+'/3 úrovně',tone:configured<3?'warn':'good',detail:'LOW / MEDIUM / HIGH policy pro automatické akce.',route:'more'});}
export function approvalInbox2200(c){const rows=A(c.autonomy.approvals).filter(x=>!['APPROVED','REJECTED','DONE'].includes(U(x.status)));return f(146,'Governance',EXECUTION_NAMES2200[45],{value:rows.length+' ke schválení',tone:rows.length?'warn':'good',detail:'Medium/high-risk akce čekající na člověka.',route:'more'});}
export function killSwitch2200(c){return f(147,'Governance',EXECUTION_NAMES2200[46],{value:c.autonomy.killSwitch?'AKTIVNÍ':'Vypnutý',tone:c.autonomy.killSwitch?'good':'bad',detail:c.autonomy.killSwitch?'Autonomní zásahy jsou blokované.':'Autonomie může běžet podle policy.',route:'more'});}
export function ruleConflict2200(c){const rules=A(c.autonomy.rules),m={};for(const x of rules){const k=norm(x.target||x.scope||x.key);if(k)(m[k]||(m[k]=new Set())).add(U(x.action))}const conflicts=Object.values(m).filter(s=>s.size>1).length;return f(148,'Governance',EXECUTION_NAMES2200[47],{value:conflicts+' konfliktů',tone:conflicts?'bad':'good',detail:'Stejný scope/target s více rozdílnými akcemi.',route:'more'});}
export function simulationBeforeAutomation2200(c){const sims=A(c.autonomy.simulations),rules=A(c.autonomy.rules),untested=Math.max(0,rules.length-new Set(sims.map(x=>x.ruleId).filter(Boolean)).size);return f(149,'Governance',EXECUTION_NAMES2200[48],{value:untested+' netestovaných',tone:untested?'warn':'good',detail:'Pravidla bez evidované historické simulace.',route:'more'});}
export function osGovernor2200(c){const blockers=[c.autonomy.killSwitch,c.autonomy.dryRun,!c.autonomy.enabled],pending=approvalInbox2200(c).score||A(c.autonomy.approvals).filter(x=>!['APPROVED','REJECTED','DONE'].includes(U(x.status))).length,conflicts=N(ruleConflict2200(c).value.split(' ')[0]);const safe=blockers.some(Boolean)||(!pending&&!conflicts);return f(150,'Governance',EXECUTION_NAMES2200[49],{value:safe?'SAFE':'REVIEW',tone:safe?'good':'bad',detail:'Governor blokuje agresivní autonomii přes kill switch, dry-run, approvals a rule-conflict kontrolu.',route:'more'});}

export const EXECUTION_BUILDERS2200=[
 actionExecutor2200,oneClickResolve2200,safeAutoComplete2200,delegationRouter2200,delegationTracker2200,ownerMissing2200,blockedResolver2200,dependencyGraph2200,criticalPath2200,autoReplan2200,
 deadlineRisk2200,forecastAccuracy2200,expectedCompletion2200,workload30d2200,cashNeed2200,liquidityWarning2200,propertyCashflow2200,ticketExposureForecast2200,projectBillingForecast2200,confidenceBands2200,
 knowledgeGraph2200,entityTimeline2200,relationshipMap2200,conversationLinking2200,documentLinking2200,autoEntityResolution2200,memoryRelevance2200,similaritySearch2200,pastDecisionComparator2200,longTermPattern2200,
 emailActionExtractor2200,attachmentIntake2200,calendarActionExtractor2200,meetingOutcome2200,replyNeeded2200,promiseTracker2200,outboundPromise2200,contactContext2200,communicationGap2200,autoDraftFollowup2200,
 permissionedAutopilot2200,dryRunMode2200,undoLedger2200,actionAudit2200,autonomyRisk2200,approvalInbox2200,killSwitch2200,ruleConflict2200,simulationBeforeAutomation2200,osGovernor2200
];

export function executionSuite2200(input=null){const c=buildExecutionContext2200(input);return{version:EXECUTION_SUITE2200_VERSION,context:c,features:EXECUTION_BUILDERS2200.map(fn=>fn(c))};}
const row=x=>'<button type="button" class="pr1300-row pr1300-clickrow" data-execution2200="'+x.id+'" data-execution-route="'+h(x.route)+'"><div class="pr1300-row-main"><b>'+x.id+'. '+h(x.title)+'</b><small>'+h(x.detail)+'</small></div><div class="pr1300-row-side '+h(x.tone)+'">'+h(x.value)+' <span class="os1500-row-arrow">→</span></div></button>';

function mutateAutonomy(label,fn){store.mutate(label,s=>{s.autonomy2200={enabled:false,dryRun:true,killSwitch:true,approvals:[],rules:[],simulations:[],riskPolicy:{LOW:'AUTO_IF_ALLOWED',MEDIUM:'APPROVAL',HIGH:'BLOCKED'},...(s.autonomy2200||{})};fn(s.autonomy2200)},{undo:true,cloud:true,audit:true})}

export function renderExecutionCenter2200(){
 const host=document.querySelector('#moreView');if(!host)return false;const model=executionSuite2200(),features=model.features,bad=features.filter(x=>x.tone==='bad').length,warn=features.filter(x=>x.tone==='warn').length,g=model.context.autonomy;
 host.innerHTML='<div class="pr1300-shell" data-execution2200-center><div class="pr1300-head"><div><div class="pr1300-kicker">OS Execution & Governance · třetích 50</div><h1>Provádění, forecasty, knowledge graph, komunikace a bezpečná autonomie.</h1><p>Rizikové akce se samy nespouštějí. Výchozí stav je dry-run + aktivní kill switch.</p></div><span class="pr1300-status '+(bad?'bad':warn?'warn':'good')+'">'+bad+' červených · '+warn+' žlutých</span></div><section class="pr1320-now"><div><div class="pr1300-kicker">OS Governor</div><h2>'+h(osGovernor2200(model.context).value)+'</h2><p>'+h(osGovernor2200(model.context).detail)+'</p></div><div class="pr1320-now-actions"><button class="pr1300-btn '+(g.killSwitch?'primary':'')+'" type="button" data-exec2200-kill>Kill switch: '+(g.killSwitch?'ON':'OFF')+'</button><button class="pr1300-btn" type="button" data-exec2200-dry>Dry-run: '+(g.dryRun?'ON':'OFF')+'</button><button class="pr1300-btn" type="button" data-exec2200-back>Zpět</button></div></section>';
 for(const domain of ['Execution','Forecast','Knowledge','Communication','Governance']){const rows=features.filter(x=>x.domain===domain);host.innerHTML+='<section class="pr1300-panel"><div class="pr1300-panel-head"><h2>'+domain+'</h2><span>'+rows.length+' modulů</span></div><div class="os1500-direct-list">'+rows.map(row).join('')+'</div></section>'}
 host.innerHTML+='</div>';host.__execution2200=model;
 if(!host.dataset.execution2200Bound){host.dataset.execution2200Bound='1';ownEvent1100(OWNER,host,'click',async e=>{if(e.target.closest('[data-exec2200-back]')){const m=await import('./documentsPage141.js');m.renderDocumentsPage141?.();return}if(e.target.closest('[data-exec2200-kill]')){mutateAutonomy('OS Governor: kill switch',a=>{a.killSwitch=!a.killSwitch});return renderExecutionCenter2200()}if(e.target.closest('[data-exec2200-dry]')){mutateAutonomy('OS Governor: dry-run',a=>{a.dryRun=!a.dryRun});return renderExecutionCenter2200()}const el=e.target.closest('[data-execution2200]');if(el){const x=host.__execution2200?.features?.find(y=>String(y.id)===el.dataset.execution2200);if(x?.route&&x.route!=='more')window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:x.route}));}})}
 window.__KAMIL_EXECUTION2200__={healthy:true,version:EXECUTION_SUITE2200_VERSION,count:features.length,bad,warn,killSwitch:g.killSwitch,dryRun:g.dryRun,names:[...EXECUTION_NAMES2200],at:Date.now()};return true;
}
