import {store} from './state.js';
import {h} from './utils.js';
import {ownEvent1100} from './runtimeOwnership1100.js';
import {moneyData1300} from './moneyOverview.js';
import {ticketData1300} from './ticketOverview.js';
import {buildPropertyHub620} from './propertyHub620.js';
import {workCommandCenter440} from './workCommandCenter440.js';
import {insuranceCenter} from './insurance25.js';
import {localInboxSummary660} from './inboxHub660.js';
import {personalVault640} from './personalVault640.js';

export const UPGRADE_SUITE2050_VERSION='2050.0.0';
export const UPGRADE_NAMES2050=[
 'Global Action Queue 2.0','Decision Inbox','Today Confidence','Today Source Trace','Priority Collision Detector',
 'Stale Data Radar','Missing Data Radar','Next Best Action Engine','Impact × Urgency Matrix','Quiet Mode',
 'Money Truth Center','Cash Parking Optimizer','Liquidity Ladder','Cashflow Calendar','Big Expense Detector',
 'Subscription Waste Detector','Net Worth History 2.0','Financial Risk Score','Mortgage Refinance Watch','Insurance Cost vs Coverage',
 'Property Deal Room','Property Scenario Engine','Offer Strategy','Rental Reality Check','Property Due Diligence Checklist',
 'Renovation Budget Builder','Property Exit Scenario','Yield Sensitivity Map','Property Watchlist Aging','Comparable Deals Memory',
 'Ticket Capital Dashboard','Ticket Sell-Through Forecast','Ticket Deadline Radar','Ticket Mistake Guard','Payout Reconciliation',
 'Marketplace Exposure','Duplicate Listing Detector','Seat Privacy Guard','Event Portfolio Heatmap','Resale Post-Mortem',
 'Work Project Command Center','Closeout Radar','Contract Risk Extractor','Invoice Gap Detector','Deadline Chain',
 'Waiting On Someone','Follow-Up Autopilot','Document Completeness Score','Weekly CEO View','OS Self-Audit 2.0'
];

const OWNER='product.upgrades2050';
const A=v=>Array.isArray(v)?v:[];
const N=v=>Number.isFinite(Number(v))?Number(v):0;
const U=v=>String(v||'').trim().toUpperCase();
const txt=x=>String(x?.title||x?.name||x?.subject||x?.event||x?.eventName||'').trim();
const CLOSED=new Set(['DONE','HOTOVO','CLOSED','ARCHIVED','RESOLVED','PAID','SOLD','CANCELLED','CANCELED','COMPLETED','FINISHED']);
const open=x=>!CLOSED.has(U(x?.status||x?.workflow||x?.state||'OPEN'));
const parseDate=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?t:null};
const days=v=>{const t=parseDate(v);return t===null?null:Math.round((t-Date.now())/86400000)};
const money=v=>Math.round(N(v)).toLocaleString('cs-CZ')+' Kč';
const pct=v=>(N(v)*100).toFixed(1).replace('.',',')+' %';
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
const feature=(id,domain,title,o={})=>({id,domain,title,status:o.status||'READY',tone:o.tone||'',value:o.value||'—',detail:o.detail||'',next:o.next||'',route:o.route||'today',score:N(o.score),data:o.data||null});
const median=arr=>{const x=arr.filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return 0;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
const by=(rows,key)=>rows.reduce((m,x)=>{const k=key(x)||'Neurčeno';m[k]=(m[k]||0)+1;return m},{});
const sum=(rows,fn)=>rows.reduce((n,x)=>n+N(fn(x)),0);

export function buildUpgradeContext2050(input=null){
 const s=input||store.get(),moneyState=moneyData1300(s),ticket=ticketData1300(s),property=buildPropertyHub620(s),work=workCommandCenter440(s),insurance=insuranceCenter(s),inbox=localInboxSummary660(s),vault=personalVault640(s);
 const tasks=A(s.tasks).filter(open),waiting=[...A(s.directorBook?.waiting),...A(s.delegations),...A(s.personalInbox?.items).filter(x=>String(x?.bucket||'').toLowerCase()==='waiting')].filter(open);
 const projects=[...A(s.projects),...A(s.workProjects),...A(s.directorBook?.projects)].filter(open);
 const transactions=A(s.personalSpending?.transactions),ticketItems=A(s.ticketBook?.items),properties=A(s.propertyBook?.candidates),records=A(vault?.records);
 return{s,moneyState,ticket,property,work,insurance,inbox,vault,tasks,waiting,projects,transactions,ticketItems,properties,records};
}
function taskDue(x){return x?.due||x?.dueAt||x?.deadline||x?.followUpAt||null}
function taskPriority(x){return N(x?.priority||x?.score||0)}
function titleKey(x){return norm(txt(x)).replace(/\b(dnes|zitri|zítra|urgent|ukol|úkol)\b/g,'').trim()}
function bestAction(c){const rows=[...c.tasks.map(x=>({title:txt(x)||'Úkol',route:x.area==='Práce'?'work':'inbox',score:taskPriority(x)+(days(taskDue(x))<0?80:days(taskDue(x))<=2?40:0)})),...A(c.ticket.attention).map(x=>({title:x.title,route:'tickets',score:x.tone==='bad'?130:90})),...A(c.work.topRisks).map(x=>({title:x.title,route:'work',score:N(x.score)+30}))].sort((a,b)=>b.score-a.score);return rows[0]||null}

export function globalActionQueue2050(c){const total=c.tasks.length+c.waiting.length+A(c.ticket.attention).length+A(c.work.topRisks).length;return feature(1,'Řízení',UPGRADE_NAMES2050[0],{value:total+' položek',tone:total?'warn':'good',detail:'Jedna fronta úkolů, čekání, ticketových zásahů a pracovních rizik.',next:bestAction(c)?.title||'Fronta je klidná.',route:'today',score:total});}
export function decisionInbox2050(c){const re=/rozhod|vyber|vybrat|koup|prodat|zmen|změn|schval|nabid|nabíd|potvrdit/i,rows=c.tasks.filter(x=>re.test(txt(x)+' '+String(x.notes||'')));return feature(2,'Řízení',UPGRADE_NAMES2050[1],{value:rows.length+' rozhodnutí',tone:rows.length?'warn':'good',detail:'Otevřené položky, které vyžadují volbu, ne jen provedení.',next:txt(rows[0])||'Žádné čekající rozhodnutí.',route:'inbox',score:rows.length});}
export function todayConfidence2050(c){const signals=[c.tasks.length>0,c.moneyState.bankKnown,c.ticket.items.length>0,c.properties.length>0,c.records.length>0,c.projects.length>0],confidence=Math.round(100*signals.filter(Boolean).length/signals.length);return feature(3,'Řízení',UPGRADE_NAMES2050[2],{value:confidence+' %',tone:confidence<50?'bad':confidence<80?'warn':'good',detail:'Důvěra v dnešní priority podle dostupnosti hlavních canonical zdrojů.',next:confidence<80?'Doplnit chybějící zdroje.':'Datové pokrytí je dobré.',route:'today',score:100-confidence});}
export function todaySourceTrace2050(c){const sources=[['Úkoly',c.tasks.length],['Peníze',c.moneyState.bankKnown?1:0],['Tickety',c.ticket.items.length],['Reality',c.properties.length],['Dokumenty',c.records.length],['Práce',c.projects.length]],active=sources.filter(x=>x[1]>0);return feature(4,'Řízení',UPGRADE_NAMES2050[3],{value:active.length+'/'+sources.length+' zdrojů',detail:active.map(x=>x[0]).join(' · ')||'Zatím bez zdrojů.',route:'today',score:sources.length-active.length});}
export function priorityCollision2050(c){const all=[...c.tasks,...c.waiting],m={};for(const x of all){const k=titleKey(x);if(k)m[k]=(m[k]||0)+1}const dup=Object.entries(m).filter(x=>x[1]>1);return feature(5,'Řízení',UPGRADE_NAMES2050[4],{value:dup.length+' kolizí',tone:dup.length?'warn':'good',detail:dup.slice(0,3).map(x=>x[0]+' ×'+x[1]).join(' · ')||'Žádné zjevné duplicity.',route:'inbox',score:dup.length});}
export function staleDataRadar2050(c){const dates=[...c.records.map(x=>x.asOf||x.updatedAt||x.reviewAt),...c.properties.map(x=>x.updatedAt||x.createdAt),...c.ticketItems.map(x=>x.marketUpdatedAt||x.updatedAt)].filter(Boolean),stale=dates.filter(x=>{const d=days(x);return d!==null&&d<-30}).length;return feature(6,'Řízení',UPGRADE_NAMES2050[5],{value:stale+' zastaralých',tone:stale?'warn':'good',detail:'Záznamy bez aktualizace déle než 30 dní.',next:stale?'Obnovit nejstarší data.':'Aktuálnost dat je v pořádku.',route:'more',score:stale});}
export function missingDataRadar2050(c){let miss=0;miss+=c.tasks.filter(x=>!taskDue(x)).length;miss+=c.properties.filter(x=>!N(x.purchasePrice||x.priceCzk||x.price)||!N(x.monthlyRent||x.rentCzk||x.rent)).length;miss+=c.records.filter(x=>x.recordType==='bank-data'&&x.balance==null).length;return feature(7,'Řízení',UPGRADE_NAMES2050[6],{value:miss+' mezer',tone:miss?'warn':'good',detail:'Chybějící termíny, ceny/nájmy a klíčové finanční hodnoty.',route:'more',score:miss});}
export function nextBestAction2050(c){const x=bestAction(c);return feature(8,'Řízení',UPGRADE_NAMES2050[7],{value:x?x.title:'Nic akutního',tone:x?.score>=120?'bad':x?'warn':'good',detail:x?'Nejvyšší kombinované skóre urgence a dopadu.':'Žádná otevřená akce.',next:x?.title||'',route:x?.route||'today',score:x?.score||0});}
export function impactUrgency2050(c){const urgent=c.tasks.filter(x=>{const d=days(taskDue(x));return taskPriority(x)>=80||(d!==null&&d<=2)}).length,important=c.tasks.filter(x=>taskPriority(x)>=50).length;return feature(9,'Řízení',UPGRADE_NAMES2050[8],{value:urgent+' teď / '+important+' důležité',tone:urgent?'warn':'good',detail:'Matice podle priority a blízkosti termínu.',route:'inbox',score:urgent*10+important});}
export function quietMode2050(c){const top=[bestAction(c),...c.tasks.sort((a,b)=>taskPriority(b)-taskPriority(a)).slice(0,3).map(x=>({title:txt(x),route:'inbox',score:taskPriority(x)}))].filter(Boolean).filter((x,i,a)=>a.findIndex(y=>y.title===x.title)===i).slice(0,3);return feature(10,'Řízení',UPGRADE_NAMES2050[9],{value:top.length+' priority',detail:top.map(x=>x.title).join(' · ')||'Klid.',route:'today',score:top.length});}

export function moneyTruth2050(c){return feature(11,'Peníze',UPGRADE_NAMES2050[10],{value:c.moneyState.bankKnown?money(c.moneyState.net):'Neúplná data',tone:c.moneyState.bankKnown?'good':'warn',detail:'Cash '+(c.moneyState.bankKnown?money(c.moneyState.bank):'—')+' · dluhy '+money(c.moneyState.debt)+' · investice '+money(c.moneyState.invest),route:'money'});}
export function cashParking2050(c){const offers=A(c.s.financePlan?.savingsOffers||c.s.savingsOffers).filter(x=>N(x.rate)>0),best=[...offers].sort((a,b)=>N(b.rate)-N(a.rate))[0],cash=c.moneyState.bank;return feature(12,'Peníze',UPGRADE_NAMES2050[11],{value:best?(N(best.rate).toFixed(2).replace('.',',')+' %'):'Chybí sazby',tone:best?'good':'warn',detail:best?((best.bank||best.name||'Nejlepší nabídka')+' · cca '+money(cash*N(best.rate)/12/100)+' / měsíc z evidované hotovosti'):'Přidej aktuální nabídky spoření do financePlan.savingsOffers.',route:'money',score:best?0:40});}
export function liquidityLadder2050(c){const immediate=c.moneyState.bank,invest=c.moneyState.invest,tickets=c.moneyState.tickets;return feature(13,'Peníze',UPGRADE_NAMES2050[12],{value:money(immediate)+' ihned',detail:'Do 30 dní orientačně: investice '+money(invest)+' · ticketový kapitál '+money(tickets)+'.',route:'money'});}
export function cashflowCalendar2050(c){const rows=A(c.s.financePlan?.cashflow||c.s.financePlan?.upcoming||c.s.cashflow).filter(x=>days(x.date||x.due)!=null&&days(x.date||x.due)>=0&&days(x.date||x.due)<=30),net=sum(rows,x=>x.amount);return feature(14,'Peníze',UPGRADE_NAMES2050[13],{value:rows.length+' pohybů',tone:net<0?'warn':'',detail:'Známý 30denní netto tok: '+money(net)+'.',route:'money',score:net<0?Math.abs(net):0});}
export function bigExpenseDetector2050(c){const outs=c.transactions.map(x=>Math.abs(N(x.amount))).filter(x=>x>0),med=median(outs),threshold=Math.max(5000,med*4),big=c.transactions.filter(x=>Math.abs(N(x.amount))>=threshold);return feature(15,'Peníze',UPGRADE_NAMES2050[14],{value:big.length+' velkých',tone:big.length?'warn':'good',detail:'Práh '+money(threshold)+' podle historie transakcí.',route:'money',score:big.length});}
export function subscriptionWaste2050(c){const groups={};for(const x of c.transactions){const k=norm(x.merchant||x.title||x.name);if(k)(groups[k]||(groups[k]=[])).push(x)}const recurring=Object.entries(groups).filter(([,v])=>v.length>=3).map(([k,v])=>({k,n:v.length,total:sum(v,x=>Math.abs(N(x.amount)))})).sort((a,b)=>b.total-a.total);return feature(16,'Peníze',UPGRADE_NAMES2050[15],{value:recurring.length+' opakovaných',detail:recurring.slice(0,3).map(x=>x.k+' '+money(x.total)).join(' · ')||'Bez jasných opakovaných plateb.',route:'money',score:recurring.length});}
export function netWorthHistory2050(c){const hst=A(c.s.netWorthBook?.history),a=hst.at(-1),b=hst.at(-2),av=N(a?.netKnown??a?.netWorth??a?.value),bv=N(b?.netKnown??b?.netWorth??b?.value),delta=av-bv;return feature(17,'Peníze',UPGRADE_NAMES2050[16],{value:hst.length?(delta>=0?'+':'')+money(delta):'Bez historie',tone:delta<0?'warn':delta>0?'good':'',detail:hst.length>=2?'Změna mezi posledními dvěma snapshoty.':'Potřebují se alespoň dva snapshoty.',route:'money'});}
export function financialRisk2050(c){const assets=Math.max(1,N(c.moneyState.assets)),debt=N(c.moneyState.debt),liq=N(c.moneyState.bank)/assets,score=Math.min(100,Math.round((debt/assets)*65+(liq<0.1?25:liq<0.2?12:0)+(c.moneyState.bankKnown?0:20)));return feature(18,'Peníze',UPGRADE_NAMES2050[17],{value:score+'/100',tone:score>=60?'bad':score>=30?'warn':'good',detail:'Strukturní riziko podle dluhu, likvidity a známých dat.',route:'money',score});}
export function mortgageRefinance2050(c){const m=c.moneyState.mortgage,d=days(m?.reviewAt||m?.fixationEnd||m?.validUntil),soon=d!==null&&d<=180;return feature(19,'Peníze',UPGRADE_NAMES2050[18],{value:m?(d===null?'Termín neznámý':d+' dní'):'Bez hypotéky',tone:soon?'warn':'',detail:soon?'Refinancování/fixaci je vhodné začít řešit.':'Bez blízkého známého refixačního termínu.',route:'money',score:soon?70:0});}
export function insuranceCoverage2050(c){const policies=A(c.insurance.policies),weak=policies.filter(x=>x.lifecycle==='ACTIVE'&&(!N(x.coverageLimit||x.limit||x.sumInsured)||!N(x.annualCost||x.yearlyCost||x.premiumAnnual)));return feature(20,'Peníze',UPGRADE_NAMES2050[19],{value:weak.length+' neúplných',tone:weak.length?'warn':'good',detail:'Aktivní pojistky bez známého limitu nebo roční ceny.',route:'more',score:weak.length});}

export function propertyDealRoom2050(c){const b=c.property.best;return feature(21,'Reality',UPGRADE_NAMES2050[20],{value:b?(b.name+' · '+b.score+'/100'):'Bez kandidáta',tone:b?.decision?.code==='PASS'?'bad':b?'good':'warn',detail:b?((b.location||'')+' · '+money(b.purchasePrice)+' · net yield '+pct(b.netYield)):'Property Book je prázdný.',route:'property',score:b?.score||0});}
export function propertyScenario2050(c){const b=c.property.best;if(!b)return feature(22,'Reality',UPGRADE_NAMES2050[21],{value:'Bez kandidáta',tone:'warn',route:'property'});const rent=N(b.monthlyRent||b.rentCzk||b.rent),price=N(b.purchasePrice),ren=N(b.renovationBudget||b.renovationCost),gross=price+ren?rent*12/(price+ren):0;return feature(22,'Reality',UPGRADE_NAMES2050[21],{value:pct(gross),detail:'Hrubý výnos po započtení známé rekonstrukce.',route:'property'});}
export function offerStrategy2050(c){const b=c.property.best;if(!b)return feature(23,'Reality',UPGRADE_NAMES2050[22],{value:'Bez kandidáta',tone:'warn',route:'property'});const gap=N(b.targetPrice)-N(b.purchasePrice);return feature(23,'Reality',UPGRADE_NAMES2050[22],{value:b.targetPrice?money(b.targetPrice):'Bez cíle',tone:gap<0?'warn':'good',detail:b.targetPrice?'Mezera proti nabídkové ceně '+money(Math.abs(gap))+'.':'Doplň cílovou cenu.',route:'property'});}
export function rentalReality2050(c){const rows=c.properties.filter(x=>N(x.monthlyRent||x.rentCzk||x.rent)>0),rents=rows.map(x=>N(x.monthlyRent||x.rentCzk||x.rent)),med=median(rents);return feature(24,'Reality',UPGRADE_NAMES2050[23],{value:rows.length?money(med)+'/m':'Chybí nájmy',detail:rows.length?'Medián evidovaných nájmů v Property Booku.':'Doplň realistické nájmy u kandidátů.',route:'property'});}
export function propertyDD2050(c){const b=c.property.best;if(!b)return feature(25,'Reality',UPGRADE_NAMES2050[24],{value:'Bez kandidáta',tone:'warn',route:'property'});const fields=['purchasePrice','location','area','monthlyRent','netYield'],missing=fields.filter(k=>b[k]==null&&!(k==='area'&&b.areaM2!=null)&&!(k==='monthlyRent'&&b.rentCzk!=null));return feature(25,'Reality',UPGRADE_NAMES2050[24],{value:(fields.length-missing.length)+'/'+fields.length,tone:missing.length?'warn':'good',detail:missing.length?'Chybí: '+missing.join(', '):'Základní investiční data kompletní.',route:'property',score:missing.length});}
export function renovationBudget2050(c){const b=c.property.best,cost=N(b?.renovationBudget||b?.renovationCost||b?.reconstructionCost);return feature(26,'Reality',UPGRADE_NAMES2050[25],{value:cost?money(cost):'Není vyplněno',tone:cost?'':'warn',detail:cost?'Známý rozpočet rekonstrukce kandidáta #1.':'Doplň low-cost rozpočet rekonstrukce.',route:'property'});}
export function propertyExit2050(c){const b=c.property.best,price=N(b?.purchasePrice),growth=N(b?.annualGrowth||0.02),future=price*Math.pow(1+growth,5);return feature(27,'Reality',UPGRADE_NAMES2050[26],{value:price?money(future):'Bez kandidáta',detail:price?'Orientační 5letá hodnota při '+pct(growth)+' ročně; bez garance.':'Chybí vstupní cena.',route:'property'});}
export function yieldSensitivity2050(c){const b=c.property.best,price=N(b?.purchasePrice),rent=N(b?.monthlyRent||b?.rentCzk||b?.rent),low=price?rent*.9*12/price:0,high=price?rent*1.1*12/price:0;return feature(28,'Reality',UPGRADE_NAMES2050[27],{value:price?(pct(low)+' – '+pct(high)):'Bez dat',detail:'Citlivost hrubého výnosu při ±10 % nájmu.',route:'property'});}
export function propertyAging2050(c){const ages=c.properties.map(x=>-N(days(x.listedAt||x.createdAt||x.firstSeenAt))).filter(x=>x>=0),old=ages.filter(x=>x>=30).length;return feature(29,'Reality',UPGRADE_NAMES2050[28],{value:old+' nad 30 dní',tone:old?'warn':'',detail:'Dlouho visící nabídky mohou mít větší prostor pro vyjednávání.',route:'property'});}
export function comparableDeals2050(c){return feature(30,'Reality',UPGRADE_NAMES2050[29],{value:c.properties.length+' srovnání',detail:'Paměť kandidátů v Property Booku pro budoucí porovnání.',route:'property'});}

export function ticketCapital2050(c){return feature(31,'Vstupenky',UPGRADE_NAMES2050[30],{value:money(c.ticket.p.totalCapital),tone:c.ticket.p.totalCapital?'warn':'good',detail:c.ticket.p.queue.activeQty+' aktivních kusů v '+c.ticket.p.totalEvents+' eventech.',route:'tickets'});}
export function sellThrough2050(c){const listed=c.ticketItems.filter(x=>['LISTED','OPEN','HOLD'].includes(U(x.workflow||x.market_status))).length,sold=c.ticketItems.filter(x=>U(x.workflow||x.market_status).includes('SOLD')).length,rate=listed+sold?sold/(listed+sold):0;return feature(32,'Vstupenky',UPGRADE_NAMES2050[31],{value:pct(rate),detail:'Historický poměr prodaných proti prodaným + aktuálně nabízeným řádkům.',route:'tickets'});}
export function ticketDeadline2050(c){const soon=c.ticketItems.filter(x=>{const d=days(x.eventDate||x.date);return d!==null&&d>=0&&d<=7&&open(x)});return feature(33,'Vstupenky',UPGRADE_NAMES2050[32],{value:soon.length+' do 7 dní',tone:soon.length?'bad':'good',detail:soon.slice(0,3).map(txt).join(' · ')||'Žádný aktivní event do 7 dní.',route:'tickets',score:soon.length*20});}
export function ticketMistakeGuard2050(c){const risky=c.ticketItems.filter(x=>open(x)&&(!x.eventDate&&!x.date||!x.section&&!x.category||x.qty==null));return feature(34,'Vstupenky',UPGRADE_NAMES2050[33],{value:risky.length+' rizik',tone:risky.length?'bad':'good',detail:'Aktivní řádky bez data, sekce/kategorie nebo počtu kusů.',route:'tickets',score:risky.length});}
export function payoutReconciliation2050(c){const sold=c.ticketItems.filter(x=>U(x.workflow||x.market_status).includes('SOLD')),missing=sold.filter(x=>x.payout==null&&x.payoutCzk==null&&x.sell==null&&x.sellTotalCzk==null);return feature(35,'Vstupenky',UPGRADE_NAMES2050[34],{value:missing.length+' nedopárovaných',tone:missing.length?'warn':'good',detail:sold.length+' prodaných řádků celkem.',route:'tickets'});}
export function marketplaceExposure2050(c){const g=by(c.ticketItems.filter(open),x=>x.marketplace||x.platform||'Neurčeno');return feature(36,'Vstupenky',UPGRADE_NAMES2050[35],{value:Object.keys(g).length+' tržišť',detail:Object.entries(g).slice(0,4).map(x=>x[0]+' '+x[1]).join(' · ')||'Bez aktivních listingů.',route:'tickets'});}
export function duplicateListing2050(c){const m={};for(const x of c.ticketItems.filter(open)){const k=norm([x.eventName||x.name,x.section,x.row,x.seat].join('|'));if(k)m[k]=(m[k]||0)+1}const dup=Object.values(m).filter(n=>n>1).length;return feature(37,'Vstupenky',UPGRADE_NAMES2050[36],{value:dup+' duplicit',tone:dup?'bad':'good',detail:'Kontrola shodného eventu + sekce + řady + sedadla.',route:'tickets'});}
export function seatPrivacy2050(c){const exposed=c.ticketItems.filter(x=>open(x)&&(x.seat||x.seatNumber)&&(x.marketplace||x.platform));return feature(38,'Vstupenky',UPGRADE_NAMES2050[37],{value:exposed.length+' přesných sedadel',tone:exposed.length?'warn':'good',detail:'Přesné sedadlo je evidované u aktivního marketplace řádku.',route:'tickets'});}
export function eventHeatmap2050(c){const g=by(c.ticketItems.filter(open),x=>x.eventName||x.name||'Neurčeno'),top=Object.entries(g).sort((a,b)=>b[1]-a[1])[0];return feature(39,'Vstupenky',UPGRADE_NAMES2050[38],{value:top?(top[0]+' · '+top[1]+' řádků'):'Bez expozice',detail:'Největší koncentrace aktivního ticketového portfolia.',route:'tickets'});}
export function resalePostmortem2050(c){const closed=c.ticketItems.filter(x=>!open(x)&&N(x.buy||x.buyTotalCzk)>0),profit=sum(closed,x=>N(x.sell||x.sellTotalCzk)-N(x.buy||x.buyTotalCzk));return feature(40,'Vstupenky',UPGRADE_NAMES2050[39],{value:closed.length?money(profit):'Bez uzavřených dat',tone:profit<0?'warn':profit>0?'good':'',detail:closed.length+' uzavřených řádků s nákupní cenou.',route:'tickets'});}

export function workCommandCenter2050(c){return feature(41,'Práce',UPGRADE_NAMES2050[40],{value:c.projects.length+' projektů',tone:A(c.work.topRisks).length?'warn':'good',detail:A(c.work.topRisks).length+' hlavních rizik.',route:'work'});}
export function closeoutRadar2050(c){const re=/hotov|předán|predan|complete|finish/i,missing=/foto|reviz|dsps|šanon|sanon|předáv|predav|faktur/i,rows=c.projects.filter(x=>re.test(String(x.status||''))&&missing.test(String(x.notes||x.nextAction||'')));return feature(42,'Práce',UPGRADE_NAMES2050[41],{value:rows.length+' closeoutů',tone:rows.length?'warn':'good',detail:'Dokončené/předané projekty s evidovaným chybějícím výstupem.',route:'work'});}
export function contractRisk2050(c){const rows=[...c.tasks,...c.records].filter(x=>/pokut|zádrž|zadrz|splatnost|vícepr|vicepr|dp[hH]|termín smlouv|termin smlouv/i.test(txt(x)+' '+String(x.notes||x.detail||x.nextAction||'')));return feature(43,'Práce',UPGRADE_NAMES2050[42],{value:rows.length+' rizik',tone:rows.length?'warn':'good',detail:'Smluvní texty/úkoly s termínem, pokutou, zádržným, DPH nebo vícepracemi.',route:'work'});}
export function invoiceGap2050(c){const rows=c.projects.filter(x=>/hotov|předán|predan|complete|finish/i.test(String(x.status||''))&&/dofaktur|faktur|invoice/i.test(String(x.nextAction||x.notes||'')));return feature(44,'Práce',UPGRADE_NAMES2050[43],{value:rows.length+' mezer',tone:rows.length?'bad':'good',detail:'Dokončené projekty s otevřenou fakturační akcí.',route:'work'});}
export function deadlineChain2050(c){const soon=c.projects.filter(x=>{const d=days(x.deadline||x.handoverAt||x.due);return d!==null&&d>=0&&d<=14});return feature(45,'Práce',UPGRADE_NAMES2050[44],{value:soon.length+' do 14 dní',tone:soon.length?'warn':'good',detail:soon.slice(0,3).map(txt).join(' · ')||'Bez blízkého známého předání.',route:'work'});}
export function waitingOnSomeone2050(c){return feature(46,'Práce',UPGRADE_NAMES2050[45],{value:c.waiting.length+' čekání',tone:c.waiting.length?'warn':'good',detail:c.waiting.slice(0,3).map(txt).join(' · ')||'Na nikoho evidovaně nečekáš.',route:'inbox'});}
export function followUpAutopilot2050(c){const due=c.waiting.filter(x=>{const d=days(x.followUpAt||x.due||x.deadline);return d!==null&&d<=0});return feature(47,'Práce',UPGRADE_NAMES2050[46],{value:due.length+' k urgenci',tone:due.length?'bad':'good',detail:due.slice(0,3).map(txt).join(' · ')||'Žádný follow-up po termínu.',route:'inbox',score:due.length*20});}
export function documentCompleteness2050(c){const docs=c.records,complete=docs.filter(x=>x.title&&(x.attachments?.length||x.sourceUrl||x.evidenceIds?.length)).length,p=docs.length?Math.round(100*complete/docs.length):100;return feature(48,'Práce',UPGRADE_NAMES2050[47],{value:p+' %',tone:p<60?'bad':p<85?'warn':'good',detail:complete+'/'+docs.length+' záznamů má titul a připojený/odkazovaný zdroj.',route:'more'});}
export function weeklyCEO2050(c){const rows=[nextBestAction2050(c),financialRisk2050(c),ticketDeadline2050(c),deadlineChain2050(c),followUpAutopilot2050(c)].sort((a,b)=>b.score-a.score);return feature(49,'Řízení',UPGRADE_NAMES2050[48],{value:'Top 5',tone:rows.some(x=>x.tone==='bad')?'bad':rows.some(x=>x.tone==='warn')?'warn':'good',detail:rows.map(x=>x.title+': '+x.value).join(' · '),route:'today',score:Math.max(...rows.map(x=>x.score),0),data:rows});}
export function selfAudit2050(c){const checks=[priorityCollision2050(c).score,staleDataRadar2050(c).score,missingDataRadar2050(c).score,ticketMistakeGuard2050(c).score,duplicateListing2050(c).score],issues=checks.reduce((a,b)=>a+b,0);return feature(50,'Řízení',UPGRADE_NAMES2050[49],{value:issues+' nálezů',tone:issues?'warn':'good',detail:'Souhrn datových duplicit, zastaralosti, chybějících údajů a ticketových rizik.',next:issues?'Projít červené a žluté moduly níže.':'Datový self-audit je čistý.',route:'more',score:issues});}

export const UPGRADE_BUILDERS2050=[
 globalActionQueue2050,decisionInbox2050,todayConfidence2050,todaySourceTrace2050,priorityCollision2050,staleDataRadar2050,missingDataRadar2050,nextBestAction2050,impactUrgency2050,quietMode2050,
 moneyTruth2050,cashParking2050,liquidityLadder2050,cashflowCalendar2050,bigExpenseDetector2050,subscriptionWaste2050,netWorthHistory2050,financialRisk2050,mortgageRefinance2050,insuranceCoverage2050,
 propertyDealRoom2050,propertyScenario2050,offerStrategy2050,rentalReality2050,propertyDD2050,renovationBudget2050,propertyExit2050,yieldSensitivity2050,propertyAging2050,comparableDeals2050,
 ticketCapital2050,sellThrough2050,ticketDeadline2050,ticketMistakeGuard2050,payoutReconciliation2050,marketplaceExposure2050,duplicateListing2050,seatPrivacy2050,eventHeatmap2050,resalePostmortem2050,
 workCommandCenter2050,closeoutRadar2050,contractRisk2050,invoiceGap2050,deadlineChain2050,waitingOnSomeone2050,followUpAutopilot2050,documentCompleteness2050,weeklyCEO2050,selfAudit2050
];
export function upgradeSuite2050(input=null){const c=buildUpgradeContext2050(input);return{version:UPGRADE_SUITE2050_VERSION,context:c,features:UPGRADE_BUILDERS2050.map(fn=>fn(c))};}
const featureHtml=x=>'<button type="button" class="pr1300-row pr1300-clickrow" data-upgrade2050="'+x.id+'" data-upgrade-route="'+h(x.route)+'"><div class="pr1300-row-main"><b>'+x.id+'. '+h(x.title)+'</b><small>'+h(x.detail)+(x.next?' · Další: '+h(x.next):'')+'</small></div><div class="pr1300-row-side '+h(x.tone)+'">'+h(x.value)+' <span class="os1500-row-arrow">→</span></div></button>';

export function renderUpgradeCenter2050(){
 const host=document.querySelector('#moreView');if(!host)return false;const model=upgradeSuite2050(),features=model.features,bad=features.filter(x=>x.tone==='bad').length,warn=features.filter(x=>x.tone==='warn').length;
 host.innerHTML='<div class="pr1300-shell" data-upgrades2050><div class="pr1300-head"><div><div class="pr1300-kicker">OS Intelligence · 50 upgradeů</div><h1>Řídicí vrstva nad celým Kamil OS.</h1><p>Všech 50 modulů čte canonical data. Nezakládá druhou databázi ani paralelní pravdu.</p></div><span class="pr1300-status '+(bad?'bad':warn?'warn':'good')+'">'+bad+' červených · '+warn+' žlutých</span></div><section class="pr1320-now"><div><div class="pr1300-kicker">CEO pohled</div><h2>'+h(weeklyCEO2050(model.context).detail||'Systém je klidný')+'</h2><p>Self-audit: '+h(selfAudit2050(model.context).value)+' · Today confidence: '+h(todayConfidence2050(model.context).value)+'</p></div><div class="pr1320-now-actions"><button type="button" class="pr1300-btn" data-upgrades2050-back>Zpět na Dokumenty</button></div></section>';
 const domains=['Řízení','Peníze','Reality','Vstupenky','Práce'];
 for(const domain of domains){const rows=features.filter(x=>x.domain===domain);host.innerHTML+='<section class="pr1300-panel"><div class="pr1300-panel-head"><h2>'+domain+'</h2><span>'+rows.length+' modulů</span></div><div class="os1500-direct-list">'+rows.map(featureHtml).join('')+'</div></section>'}
 host.innerHTML+='</div>';host.__upgrades2050=model;
 if(!host.dataset.upgrades2050Bound){host.dataset.upgrades2050Bound='1';ownEvent1100(OWNER,host,'click',async e=>{if(e.target.closest('[data-upgrades2050-back]')){const m=await import('./documentsPage141.js');m.renderDocumentsPage141?.();return}const row=e.target.closest('[data-upgrade2050]');if(row){const x=host.__upgrades2050?.features?.find(y=>String(y.id)===row.dataset.upgrade2050);if(x?.route&&x.route!=='more')window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:x.route}));}})}
 window.__KAMIL_UPGRADES2050__={healthy:true,version:UPGRADE_SUITE2050_VERSION,count:features.length,bad,warn,names:[...UPGRADE_NAMES2050],at:Date.now()};return true;
}
