import {store} from './state.js';
import {modal,h} from './utils.js';
import {personalSettings647,openPersonalSettings647,openPersonalDataHealth647} from './personalSettings647.js';
import {openPersonalWaiting650} from './personalWaiting650.js';
import {personalWeeklyReset650} from './personalAssistant650.js';

const open=x=>!['DONE','CLOSED','ARCHIVED','RESOLVED'].includes(String(x?.status||'').toUpperCase());
const openRows=(arr=[])=>arr.filter(open);
const date=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?new Date(t).toLocaleDateString('cs-CZ'):'—'};
const listBody=(title,rows)=>`<div class="card"><div class="eyebrow">${h(title)}</div>${rows.length?rows.slice(0,20).map(x=>`<div class="row"><div><b>${h(x.title||x.name||'Položka')}</b><div class="muted">${h(x.due||x.deadline||x.followUpAt?date(x.due||x.deadline||x.followUpAt):x.note||x.notes||'')}</div></div></div>`).join(''):'<div class="empty">Nic otevřeného.</div>'}</div>`;
async function openSimpleList(title,rows){return modal(title,listBody(title,rows),[{label:'Zavřít',value:null,primary:true}])}
function trackMore892(choice){if(!choice)return;import('./usage892.js').then(m=>m.recordUsage892(choice,{surface:'more'})).catch(()=>{})}
async function openWeeklyReset650(s){const w=personalWeeklyReset650(s),body=`<div class="card"><div class="eyebrow">PŘÍŠTÍCH 7 DNÍ</div>${w.next7.length?w.next7.slice(0,6).map(x=>`<div class="row"><span>${h(x.title||x.summary||'Událost')}</span><b>${x.d===0?'dnes':x.d===1?'zítra':`za ${x.d} d`}</b></div>`).join(''):'<div class="empty">Žádný známý termín.</div>'}</div><div class="card"><div class="eyebrow">ČEKÁM</div>${w.waiting.length?w.waiting.map(x=>`<div class="row"><span>${h(x.title||x.name||'Čekání')}</span></div>`).join(''):'<div class="empty">Na nic nečekáš.</div>'}</div><div class="card"><div class="eyebrow">OVĚŘIT DATA</div>${w.stale.length?w.stale.map(x=>`<div class="row"><span>${h(x.title)}</span><span>${h(x.nextAction||'')}</span></div>`).join(''):'<div class="empty success-empty">Nic důležitého k ověření.</div>'}</div>`;return modal('Týdenní reset',body,[{label:'Hotovo',value:null,primary:true}])}
async function openDataAndSettings(){const v=await modal('Data a nastavení',`<div class="card"><div class="eyebrow">ONE OS</div><h2>Data, export a osobní preference</h2><p class="muted">Diagnostiku starých decision vrstev najdeš už jen pod Pokročilé / legacy.</p></div>`,[{label:'Stav a export dat',value:'health',primary:true},{label:'Nastavit prioritu',value:'settings'},{label:'Zavřít',value:null}]);if(v==='health')return openPersonalDataHealth647();if(v==='settings')return openPersonalSettings647();return v}
export async function openPersonalMore640(){
 const s=store.get(),health=personalSettings647(s),goals=openRows(s.personalGoals?.items||[]),inbox=openRows(s.personalInbox?.items||[]),admin=openRows(s.personalAdmin?.items||[]),waiting=openRows(s.delegations||[]);
 let one=null,cp=null;try{one=await import('./oneOS977.js')}catch{}try{cp=await import('./controlPlane1037.js')}catch{}const os=one?.consolidationHealth977?.(),system=cp?.systemHealth988?.();
 const body=`<div class="card"><div class="eyebrow">ONE OS / VÍCE</div><h2>Jedna hlavní cesta</h2><p class="muted">Control Plane sjednocuje health, data, backup, integrace, automations a legacy správu. Běžné decision vrstvy zůstávají v One OS.</p><div class="row"><span>System health</span><b>${system?Math.round(system.score)+' / 100':'—'}</b></div><div class="row"><span>Consolidation health</span><b>${os?Math.round(os.score)+' / 100':'—'}</b></div><div class="row"><span>Čekám na odpověď</span><b>${waiting.length}</b></div><div class="row"><span>Osobní inbox</span><b>${inbox.length}</b></div><div class="row"><span>Administrativa</span><b>${admin.length}</b></div><div class="row"><span>Osobní cíle</span><b>${goals.length}</b></div><div class="row"><span>Data k aktualizaci</span><b>${health.missing}</b></div></div>`;
 const choice=await modal('Kamil OS / Více',body,[{label:'Kamil OS Control Plane',value:'control',primary:true},{label:`Čekám na odpověď (${waiting.length})`,value:'waiting'},{label:'Týdenní reset',value:'week'},{label:`Osobní inbox (${inbox.length})`,value:'inbox'},{label:`Administrativa (${admin.length})`,value:'admin'},{label:`Cíle (${goals.length})`,value:'goals'},{label:'Data a nastavení',value:'data'},{label:'Pokročilé / legacy',value:'legacy'},{label:'Zavřít',value:null}]);
 trackMore892(choice);one?.recordUsage975?.(`more:${choice||'close'}`,'more');
 if(choice==='control')return cp?.openControlPlane1037?.();if(choice==='legacy')return one?.openLegacy969?.();if(choice==='waiting')return openPersonalWaiting650();if(choice==='week')return openWeeklyReset650(s);if(choice==='inbox')return openSimpleList('Osobní inbox',inbox);if(choice==='admin')return openSimpleList('Administrativa',admin);if(choice==='goals')return openSimpleList('Osobní cíle',goals);if(choice==='data')return openDataAndSettings();return choice;
}
