import {personalQuery as baseQuery} from './autopilot28.js';
import {goalPlan,priceHistory,changeFeed,reminderEscalation,onboardingWizard} from './personalPlus29.js';
import {personalCopilot30} from './personalCopilot30.js';
import {buildPersonalToday} from './personalToday26.js';
import {decisionDelta30} from './decisionDelta30.js';
import {decisionJournalReview} from './decisionJournal31.js';

const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('cs-CZ').trim();
const money=(v,c='CZK')=>`${Math.round(Number(v)||0).toLocaleString('cs-CZ')} ${c}`;
const activeStatus=x=>!['DONE','CLOSED','ARCHIVED','HOTOVO','PAID'].includes(String(x?.status||'').toUpperCase());
const d0=x=>{const d=new Date(x);d.setHours(0,0,0,0);return d};
const dateOf=x=>x?.due||x?.dueAt||x?.date||x?.followUpAt||x?.follow_up_at||x?.scheduledAt||null;
const inDays=(v,from,to)=>{const t=Date.parse(v||'');return Number.isFinite(t)&&t>=from.getTime()&&t<to.getTime()};
function ticketCapital(s){return (s.ticketBook?.items||[]).filter(x=>['HOLD','LISTED'].includes(String(x.workflow||'HOLD').toUpperCase())).reduce((a,x)=>a+Number(x.buy||x.buyTotalCzk||x.buy_total_czk||0),0)}
function xtbSummary(s){const rows=[];for(const a of Object.values(s.xtbHub?.accounts||{})){const positions=a?.positions||[],value=positions.reduce((sum,p)=>sum+Number(p.marketValue??p.currentValue??p.value??p.market_value??0),0);if(positions.length)rows.push(`${a.name||a.currency||'XTB účet'}: ${money(value,a.currency||'CZK')} · ${positions.length} pozic`)}return rows}
function waitingRows(s){return (s.directorBook?.waiting||s.waitingFor||[]).filter(activeStatus)}

export function personalQuery(raw,s={},meta={},now=new Date()){
 const q=norm(raw);if(!q)return null;
 if((q.includes('kolik')||q.includes('kapital'))&&(q.includes('vstupenk')||q.includes('listk'))){const v=ticketCapital(s);return{title:`Ve vstupenkách máš známý nákupní kapitál ${money(v)}.`,lines:[`Počítám jen aktivní HOLD/LISTED položky z evidence vstupenek.`,`Pro aktuální tržní hodnotu otevři Vstupenky — ta závisí na čerstvosti zdroje.`],note:'Známá pořizovací hodnota, ne garantovaná prodejní cena.'}}
 if(q.includes('kolik')&&q.includes('xtb')){const lines=xtbSummary(s);return{title:lines.length?'XTB podle posledních uložených dat':'XTB data nejsou v OS aktuálně uložená.',lines:lines.length?lines:['Doplň nebo synchronizuj XTB snapshot; bez něj nebudu částku odhadovat.'],note:'Částky jsou jen tak čerstvé jako poslední uložený snapshot.'}}
 if((q.includes('zaplat')||q.includes('platby'))&&(q.includes('tyden')||q.includes('7 dni'))){const start=d0(now),end=new Date(start);end.setDate(end.getDate()+8);const candidates=[...(s.tasks||[]),...(s.personalAdmin?.items||[])].filter(activeStatus).filter(x=>inDays(dateOf(x),start,end)&&(/plat|faktur|pojist|spl[aá]t|poplatek/i.test(`${x.title||''} ${x.category||''}`)||String(x.category||'').toUpperCase()==='PAYMENT'));return{title:candidates.length?`Tento týden vidím ${candidates.length} platebních věcí.`:'Tento týden nemám v uložených datech známou platbu k řešení.',lines:candidates.map(x=>`${x.title||x.name||'Platba'} — ${new Date(dateOf(x)).toLocaleDateString('cs-CZ')}`),note:'Ukazuju jen položky s konkrétním termínem v OS.'}}
 if(q.includes('cek')&&(q.includes('dele nez tyden')||q.includes('vic nez tyden')||q.includes('7 dni'))){const cutoff=Date.now()-7*86400000,rows=waitingRows(s).filter(x=>{const t=Date.parse(x.since||x.createdAt||x.created_at||x.at||'');return Number.isFinite(t)&&t<cutoff});return{title:rows.length?`${rows.length} čekání je starších než týden.`:'Žádné známé čekání není starší než týden.',lines:rows.slice(0,10).map(x=>`${x.title||x.name||'Čekání'} — od ${new Date(x.since||x.createdAt||x.created_at||x.at).toLocaleDateString('cs-CZ')}`),note:'Staré čekání je kandidát na follow-up nebo uzavření.'}}
 if(q.includes('zitra')&&(q.includes('co mam')||q.includes('udelat')||q.includes('resit'))){const start=d0(now);start.setDate(start.getDate()+1);const end=new Date(start);end.setDate(end.getDate()+1);const rows=[...(s.tasks||[]),...waitingRows(s),...(s.calendar?.events||[])].filter(activeStatus).filter(x=>inDays(dateOf(x),start,end));return{title:rows.length?`Na zítra vidím ${rows.length} známých věcí.`:'Na zítra nemám v OS známý konkrétní termín.',lines:rows.slice(0,12).map(x=>`${x.title||x.name||x.summary||'Položka'} — ${new Date(dateOf(x)).toLocaleTimeString('cs-CZ',{hour:'2-digit',minute:'2-digit'})}`),note:'Kalendář, úkoly a Waiting For s konkrétním datem.'}}
 if(q.includes('co jsme doporucili')||q.includes('co jsi doporucil')||q.includes('historie rozhodnuti')||q.includes('decision journal')||q.includes('minula doporuceni')){const r=decisionJournalReview(s,buildPersonalToday(s,now),now);if(!r.total)return {title:'Decision Journal',lines:['Zatím není uložený žádný potvrzený rozhodovací snapshot.'],note:r.note};return {title:'Decision Journal',lines:r.items.slice(0,12).map(x=>`${new Date(x.at).toLocaleDateString('cs-CZ')} · ${x.title} — ${x.action||'—'} · priorita ${x.priority}/100${x.actionChanged?` · teď ${x.currentAction||'—'}`:''}`),note:r.note}}
 if(q.includes('co se zmenilo od minule')||q.includes('od posledni kontroly')||q.includes('decision delta')||q.includes('zmenilo rozhodnuti')){const d=decisionDelta30(buildPersonalToday(s,now),meta.decisionBaseline30,now);if(!d.initialized)return {title:'Co se změnilo od minule',lines:['Ještě nemám potvrzený předchozí rozhodovací snapshot. Otevři Dnes; výchozí stav se uloží lokálně a další změny už půjdou porovnat.'],note:d.note};return {title:'Co se změnilo od minule',lines:d.items.length?d.items.slice(0,12).map(x=>`${x.title} — ${x.detail}`):['Od poslední potvrzené kontroly se rozhodovací priority nezměnily.'],note:d.note}}
 const copilot=personalCopilot30(raw,s,meta,now);if(copilot)return copilot;
 if(q.includes('cil')||q.includes('fond')){const g=goalPlan(s,now);return {title:'Cíle a fondy',lines:g.items.slice(0,10).map(x=>`${x.title} — ${x.remaining===null?'chybí cílová částka':`zbývá ${money(x.remaining,x.currency)}`}${x.requiredMonthly!==null?` · potřebné tempo ${money(x.requiredMonthly,x.currency)}/měs`:''}`),note:g.note}}
 if(q.includes('zdrazil')||q.includes('zdrazilo')||q.includes('zlevnil')||q.includes('zlevnilo')||q.includes('historie cen')){const p=priceHistory(s);return {title:'Skutečné změny uložených cen',lines:p.top.map(x=>`${x.title} — ${x.previous===null?'bez srovnání':`${money(x.previous,x.currency)} → ${money(x.current,x.currency)} (${x.deltaPct>0?'+':''}${Number(x.deltaPct||0).toFixed(1)} %)`}`),note:p.note}}
 if(q.includes('co se zmenilo')||q.includes('zmeny za')||q.includes('change feed')){const f=changeFeed(s,now,30);return {title:'Co se změnilo za 30 dní',lines:f.items.slice(0,12).map(x=>`${x.title} — ${new Date(x.at).toLocaleDateString('cs-CZ')}`),note:f.note}}
 if(q.includes('pripom')||q.includes('eskalac')||q.includes('po terminu')){const r=reminderEscalation(s,now);return {title:'Eskalace osobních termínů',lines:r.top.map(x=>`${x.label}: ${x.title} — ${x.detail}`),note:r.note}}
 if(q.includes('onboarding')||q.includes('co doplnit dnes')||q.includes('co chybi nejvic')){const o=onboardingWizard(s,meta,now);return {title:'Co doplnit jako první',lines:o.steps.map(x=>`${x.rank}. ${x.title} — ${x.detail}`),note:o.note}}
 return baseQuery(raw,s,meta,now);
}
