import {store} from './state.js';
import {personalAdmin,PERSONAL_CATEGORIES,PERSONAL_CADENCES} from './personalAdmin25.js';
import {h,date,uid,qs,qsa,modal,toast} from './utils.js';

const tileId='personalAdmin25Tile';
const fmtDate=v=>v?date(v):'—';
const tone=s=>s==='URGENT'?'bad':s==='SOON'||s==='REVIEW'?'warn':'good';
const statusLabel=s=>({URGENT:'ŘEŠIT',SOON:'BRZY',REVIEW:'DOPLNIT',OK:'OK'}[s]||s);
const opts=(map,selected)=>Object.entries(map).map(([k,v])=>`<option value="${k}" ${k===selected?'selected':''}>${h(v)}</option>`).join('');
const toDate=v=>v?String(v).slice(0,10):'';
const costSummary=a=>Object.entries(a.costsByCurrency||{}).map(([c,v])=>`${c}: ${Number(v.monthly||0).toLocaleString('cs-CZ',{maximumFractionDigits:2})}/měs · ${Number(v.annual||0).toLocaleString('cs-CZ',{maximumFractionDigits:2})}/rok`).join(' · ')||'Žádné opakované náklady se zadanou částkou';

function ensureTile(){const view=qs('#moreView'),grid=view?.querySelector('.more24-grid');if(!grid||qs(`#${tileId}`,view))return;const a=personalAdmin(store.get());const b=document.createElement('button');b.id=tileId;b.className='hub-tile';b.innerHTML=`<span class="hub-icon ${a.urgent?'bad':a.due30?'warn':'good'}">⌂</span><span class="hub-copy"><b>Osobní administrace</b><small>${a.total?a.total+' závazků · '+a.due30+' do 30 dní':'Pojistky, platby, doklady, dům a rodina'}</small></span><span class="hub-arrow">→</span>`;b.onclick=renderPersonal;grid.prepend(b)}

async function editItem(id=null){
 const s=store.get(),x=id?(s.personalAdmin?.items||[]).find(y=>y.id===id):null,v=(k,d='')=>x?.[k]??d;
 const body=`<div class="form-grid capture-form"><label class="wide-field">Název<input id="paTitle" autofocus value="${h(v('title'))}" placeholder="Např. Pojištění domu / elektřina / občanka"></label><label>Typ<select id="paCategory">${opts(PERSONAL_CATEGORIES,v('category','PAYMENT'))}</select></label><label>Poskytovatel / komu<input id="paProvider" value="${h(v('provider'))}" placeholder="Pojišťovna, banka, dodavatel…"></label><label>Částka<input id="paAmount" type="number" min="0" step="0.01" value="${h(v('amount'))}"></label><label>Měna<select id="paCurrency"><option value="CZK" ${v('currency','CZK')==='CZK'?'selected':''}>CZK</option><option value="EUR" ${v('currency')==='EUR'?'selected':''}>EUR</option><option value="USD" ${v('currency')==='USD'?'selected':''}>USD</option></select></label><label>Periodicita<select id="paCadence">${opts(PERSONAL_CADENCES,v('cadence','MONTHLY'))}</select></label><label>Další platba / kontrola<input id="paDue" type="date" value="${toDate(v('nextDue'))}"></label><label>Výročí / expirace<input id="paRenewal" type="date" value="${toDate(v('renewalDate')||v('endDate'))}"></label><label>Výpověď nejpozději<input id="paNotice" type="date" value="${toDate(v('noticeDate'))}"></label><label>Platba<select id="paAuto"><option value="false" ${!v('autoPay',false)?'selected':''}>Ručně / neznámé</option><option value="true" ${v('autoPay',false)?'selected':''}>Automatická</option></select></label><label class="wide-field">Poznámka<textarea id="paNotes" rows="3" placeholder="Číslo smlouvy raději jen pokud ho tu opravdu chceš mít uložené.">${h(v('notes'))}</textarea></label></div><p class="muted">Prázdná částka nebo termín zůstane neznámý. Kamil OS nic nedopočítá a nic automaticky nezaplatí.</p>`;
 const ok=await modal(id?'Upravit osobní závazek':'Nový osobní závazek',body,[{label:'Zrušit',value:false},{label:'Uložit',value:true,primary:true}]);if(!ok)return;const title=qs('#paTitle')?.value?.trim();if(!title)return toast('Doplň název');const raw=qs('#paAmount')?.value?.trim(),amount=raw===''?null:Number(raw);if(amount!==null&&(!Number.isFinite(amount)||amount<0))return toast('Částka není platná');
 const next={id:id||uid('personal'),title,category:qs('#paCategory').value,provider:qs('#paProvider').value.trim(),amount,currency:qs('#paCurrency').value,cadence:qs('#paCadence').value,nextDue:qs('#paDue').value||null,renewalDate:qs('#paRenewal').value||null,noticeDate:qs('#paNotice').value||null,autoPay:qs('#paAuto').value==='true',notes:qs('#paNotes').value.trim(),status:'ACTIVE',updatedAt:new Date().toISOString(),createdAt:x?.createdAt||new Date().toISOString()};store.mutate(`${id?'Upraven':'Přidán'} osobní závazek: ${title}`,z=>{z.personalAdmin=z.personalAdmin||{items:[]};z.personalAdmin.items=Array.isArray(z.personalAdmin.items)?z.personalAdmin.items:[];if(id){const i=z.personalAdmin.items.findIndex(y=>y.id===id);if(i>=0)z.personalAdmin.items[i]=next}else z.personalAdmin.items.unshift(next)});toast('Osobní administrace uložena');renderPersonal();
}

function renderPersonal(){
 const view=qs('#moreView'),a=personalAdmin(store.get());if(!view)return;view.innerHTML=`<div class="subview-bar"><button class="btn" id="personalBack25">← Zpět</button><div><span>VÍCE</span><b>Osobní administrace</b></div></div><div class="view-head compact"><div><div class="eyebrow">PERSONAL ADMIN / 25.13</div><h1>Rodina, domácnost a všechny závazky</h1><p>Pojistky, pravidelné platby, služby, úvěry, doklady, auto, dům, poplatky a výročí smluv.</p></div><div class="view-head-stat"><b class="${a.urgent?'bad':a.due30?'warn':'good'}">${a.urgent}</b><span>urgentních</span></div></div><div class="metric-strip"><div class="metric"><span>Aktivní závazky</span><b>${a.total}</b></div><div class="metric"><span>Do 30 dní</span><b class="${a.due30?'warn':'good'}">${a.due30}</b></div><div class="metric"><span>Pojištění</span><b>${a.insurance}</b></div><div class="metric"><span>Chybí termín</span><b class="${a.withoutTerm?'warn':'good'}">${a.withoutTerm}</b></div></div><div class="decision-note"><b>Náklady podle měny:</b> ${h(costSummary(a))}. Měny se nikdy nesčítají dohromady.</div><div class="card"><div class="card-head"><div><div class="eyebrow">RADAR ZÁVAZKŮ</div><h2>Co nesmí propadnout</h2></div><button class="btn primary" id="personalAdd25">＋ Přidat</button></div><div class="intel-list">${a.items.map(x=>`<div class="intel-row"><div class="intel-main"><div><span class="status ${tone(x.status)}">${statusLabel(x.status)} · ${x.categoryLabel}</span>${x.autoPay?' <span class="status good">AUTOPAY</span>':''}</div><b>${h(x.title)}</b><span>${h(x.issues[0]||x.provider||'Bez aktuálního upozornění')}</span><small>${x.amount!==null?`${h(x.currency)} ${Number(x.amount).toLocaleString('cs-CZ')} · ${h(x.cadenceLabel)} · `:''}další termín ${h(fmtDate(x.nextDue))} · výročí/expirace ${h(fmtDate(x.renewalDate||x.endDate))}</small></div><div class="row-actions"><button class="btn" data-personal-edit="${h(x.id)}">Upravit</button><button class="btn quiet-action" data-personal-archive="${h(x.id)}">Archivovat</button></div></div>`).join('')||'<div class="empty">Zatím tu nic není. Přidej nejdřív pojistky a pravidelné platby.</div>'}</div><div class="decision-note">${h(a.note)} Souhrn nákladů zahrnuje jen opakované položky se skutečně zadanou částkou; jednorázové položky se do něj nezapočítávají.</div></div>`;
 qs('#personalBack25').onclick=()=>window.dispatchEvent(new CustomEvent('kamil:more',{detail:'menu'}));qs('#personalAdd25').onclick=()=>editItem();qsa('[data-personal-edit]',view).forEach(b=>b.onclick=()=>editItem(b.dataset.personalEdit));qsa('[data-personal-archive]',view).forEach(b=>b.onclick=()=>{const id=b.dataset.personalArchive;store.mutate('Archivován osobní závazek',s=>{const x=s.personalAdmin?.items?.find(y=>y.id===id);if(x){x.status='ARCHIVED';x.updatedAt=new Date().toISOString()}});renderPersonal()});
}
const start=()=>{const view=qs('#moreView');if(!view)return;new MutationObserver(()=>queueMicrotask(ensureTile)).observe(view,{childList:true,subtree:true});ensureTile()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
