import {store} from './state.js';
import {platformSnapshot43,setSafeMode43,clearQuarantine43,startPlatform43,recordDecision43,scenario43} from './platform43.js';
import {h} from './utils.js';

const safe=x=>h(String(x??''));
const money=x=>`${Math.round(Number(x||0)).toLocaleString('cs-CZ')} Kč`;
let expanded=false,delayDays=0,extraCash=0,timer=null;
const row=(title,sub='',right='')=>`<div class="life42-row"><div class="life42-main"><b>${safe(title)}</b>${sub?`<span>${safe(sub)}</span>`:''}</div>${right?`<span>${safe(right)}</span>`:''}</div>`;

function details(p){const sc=scenario43(store.get(),{extraCash,delayDays});return `<div id="platform431Details">
<div class="grid two life42-grid"><section class="card"><div class="card-head"><div><div class="eyebrow">RESILIENCE</div><h2>Stabilita</h2></div><span class="status ${p.health.tone}">${p.health.score}/100</span></div>${row('Safe Mode',p.health.safeMode?'Těžké moduly omezené':'Normální režim',p.health.safeMode?'ZAPNUTO':'VYPNUTO')}${row('Dlouhé blokace',`${p.health.longTasks.length} posledních`,p.health.mem.usedMB?`${p.health.mem.usedMB} MB`:'RAM N/A')}${p.health.lastCrash?row('Poslední pád',p.health.lastCrash.where,p.health.lastCrash.at):row('Crash recovery','Bez čerstvého pádu','OK')}<div class="actions"><button class="btn" id="p431SafeMode">${p.health.safeMode?'Vypnout Safe Mode':'Spustit Safe Mode'}</button><button class="btn" id="p431ClearQ">Vyčistit karanténu</button></div></section><section class="card"><div class="card-head"><div><div class="eyebrow">BRAIN 43.1</div><h2>Proč tyhle priority</h2></div><span class="status">${p.brain.accuracy===null?'učí se':p.brain.accuracy+' %'}</span></div>${p.brain.top.map(x=>row(x.title,`${x.why} Protiargument: ${x.counter}`,`${x.confidence}%`)).join('')||'<div class="empty">Žádná priorita.</div>'}</section></div>
<div class="grid two life42-grid"><section class="card"><div class="card-head"><div><div class="eyebrow">DIRECTOR</div><h2>Pobočka ${p.director.score}/100</h2></div></div>${p.director.risk.slice(0,4).map(x=>row(x.title,x.kind,x.score)).join('')||'<div class="empty">Bez pracovního požáru.</div>'}<div class="metric-strip"><div class="metric"><span>Faktury</span><b>${p.cash.open}</b></div><div class="metric"><span>Po splatnosti</span><b>${p.cash.overdue}</b></div><div class="metric"><span>Hodnota</span><b>${money(p.cash.value)}</b></div></div></section><section class="card"><div class="card-head"><div><div class="eyebrow">WAITING FOR</div><h2>Co urgovat</h2></div></div>${p.waiting.slice(0,4).map(x=>row(x.title||x.description||'Waiting For',x.followUp?x.draft:`čekání ${x.age} d`,x.followUp?'URGOVAT':'' )).join('')||'<div class="empty">Nic nečeká.</div>'}</section></div>
<div class="grid two life42-grid"><section class="card"><div class="card-head"><div><div class="eyebrow">MONEY</div><h2>Portfolio disciplína</h2></div></div>${p.portfolio.positions.slice(0,4).map(x=>row(x.name,`${x.sell}${x.thesis?` · thesis: ${x.thesis}`:' · thesis chybí'}`,`opp ${Math.round(x.opportunity)}`)).join('')||'<div class="empty">Portfolio data nejsou načtená.</div>'}</section><section class="card"><div class="card-head"><div><div class="eyebrow">TICKETS</div><h2>Sell window</h2></div></div>${p.tickets.rows.slice(0,4).map(x=>row(x.title,`${x.window} · prodej ${x.prob}%`,`≈ ${money(x.recommendedPrice)}`)).join('')||'<div class="empty">Žádné aktivní vstupenky.</div>'}</section></div>
<section class="card"><div class="card-head"><div><div class="eyebrow">SCENARIO</div><h2>Co když něco odložím?</h2></div></div><div class="platform43-scenario"><label>Odklad dní <input id="p431Delay" type="number" min="0" max="90" value="${delayDays}"></label><label>Extra cash <input id="p431Cash" type="number" step="1000" value="${extraCash}"></label></div><div class="decision-note" id="p431Scenario">${safe(sc.text)}</div></section>
<section class="card"><div class="card-head"><div><div class="eyebrow">60-FEATURE MAP</div><h2>Platforma 43</h2></div><span class="status good">${p.features.filter(x=>x.active).length}/60</span></div><div class="platform43-grid">${p.features.map(x=>`<div class="platform43-feature"><b>${x.id}. ${safe(x.name)}</b><span class="status ${x.active?'good':'warn'}">${x.active?'AKTIVNÍ':x.runtime==='desktop'?'DESKTOP':'PŘIPRAVENO'}</span></div>`).join('')}</div></section>
</div>`}

function render(){const host=document.querySelector('#todayView');if(!host||!host.children.length)return;let root=host.querySelector('#platform43');if(root)root.remove();const p=platformSnapshot43(store.get());root=document.createElement('div');root.id='platform43';root.className='life42-shell platform43-shell';root.innerHTML=`<section class="card life42-hero"><div class="card-head"><div><div class="eyebrow">KAMIL OS 43.1 / LEAN AUTOPILOT</div><h2>Dnes udělej tyhle 3 věci</h2></div><span class="status ${p.health.tone}">zdraví ${p.health.score}/100</span></div><p class="life42-summary">${safe(p.autopilot.summary)}</p><div class="life42-top">${p.autopilot.top.map((x,i)=>`<div class="life42-priority"><strong>${i+1}</strong><div><b>${safe(x.title)}</b><span>${safe(x.kind||'Priorita')} · confidence ${Math.round(x.confidence||70)}%</span></div><button class="btn mini" data-p431-ok="${safe(x.id||'')}" data-source="${safe(x.source||'')}" data-kind="${safe(x.kind||'')}">✓ dává smysl</button></div>`).join('')||'<div class="empty">Nic kritického.</div>'}</div><div class="actions"><button class="btn" id="p431Expand">${expanded?'Skrýt detail':'Otevřít detail platformy'}</button><span class="muted">Detail se nevykresluje, dokud ho opravdu nechceš.</span></div></section>${expanded?details(p):''}`;
const anchor=host.querySelector('#lifeOs42')||host.lastElementChild;anchor?.insertAdjacentElement('afterend',root);bind(root)}

function bind(root){root.querySelector('#p431Expand')?.addEventListener('click',()=>{expanded=!expanded;render()});root.querySelector('#p431SafeMode')?.addEventListener('click',()=>{setSafeMode43(!platformSnapshot43(store.get()).health.safeMode);render()});root.querySelector('#p431ClearQ')?.addEventListener('click',()=>{clearQuarantine43();render()});root.querySelectorAll('[data-p431-ok]').forEach(b=>b.addEventListener('click',()=>{recordDecision43({id:b.dataset.p431Ok,source:b.dataset.source,kind:b.dataset.kind},'accepted','good');render()}));const d=root.querySelector('#p431Delay'),c=root.querySelector('#p431Cash'),paint=()=>{delayDays=Math.max(0,Number(d?.value||0));extraCash=Number(c?.value||0);const t=root.querySelector('#p431Scenario');if(t)t.textContent=scenario43(store.get(),{extraCash,delayDays}).text};d?.addEventListener('input',paint);c?.addEventListener('input',paint)}
function schedule(){clearTimeout(timer);timer=setTimeout(()=>{if(document.visibilityState==='visible'&&document.querySelector('#view-today')?.classList.contains('on'))render()},900)}
startPlatform43();store.subscribe(schedule);window.addEventListener('kamil:view-change',e=>{if(e.detail==='today')schedule()});window.addEventListener('kamil:today-full-ready',schedule);window.addEventListener('kamil:platform43',schedule);schedule();
