import {store} from './state.js';
import {h} from './utils.js';
import {platformSnapshot43,setSafeMode43,clearQuarantine43,startPlatform43,recordDecision43,scenario43} from './platform43.js';

const safe=x=>h(String(x??''));
const money=x=>`${Math.round(Number(x||0)).toLocaleString('cs-CZ')} Kč`;
let scenarioDelay=0,scenarioCash=0;
function row(title,sub='',right=''){return `<div class="life42-row"><div class="life42-main"><b>${safe(title)}</b>${sub?`<span>${safe(sub)}</span>`:''}</div>${right?`<span>${safe(right)}</span>`:''}</div>`}
function featureGrid(features){return `<div class="platform43-grid">${features.map(x=>`<div class="platform43-feature"><b>${x.id}. ${safe(x.name)}</b><span class="status ${x.active?'good':'warn'}">${x.active?'AKTIVNÍ':x.runtime==='desktop'?'DESKTOP':'PŘIPRAVENO'}</span></div>`).join('')}</div>`}
function render(){const host=document.querySelector('#todayView');if(!host||!host.children.length)return;let root=host.querySelector('#platform43');if(root)root.remove();const p=platformSnapshot43(store.get()),sc=scenario43(store.get(),{extraCash:scenarioCash,delayDays:scenarioDelay});root=document.createElement('div');root.id='platform43';root.className='life42-shell platform43-shell';root.innerHTML=`
<section class="card life42-hero"><div class="card-head"><div><div class="eyebrow">KAMIL OS 43 / AUTOPILOT PLATFORM</div><h2>Dnes udělej tyhle 3 věci</h2></div><span class="status ${p.health.tone}">zdraví ${p.health.score}/100</span></div><p class="life42-summary">${safe(p.autopilot.summary)}</p><div class="life42-top">${p.autopilot.top.map((x,i)=>`<div class="life42-priority"><strong>${i+1}</strong><div><b>${safe(x.title)}</b><span>${safe(x.kind||'Priorita')} · confidence ${Math.round(x.confidence||Math.min(95,55+(x.score||50)*.35))}%</span></div><button class="btn mini" data-p43-done="${safe(x.id||'')}" data-source="${safe(x.source||'')}" data-kind="${safe(x.kind||'')}">✓ dává smysl</button></div>`).join('')||'<div class="empty">Nic kritického.</div>'}</div></section>
<div class="grid two life42-grid"><section class="card"><div class="card-head"><div><div class="eyebrow">RESILIENCE 43</div><h2>Freeze / crash / RAM ochrana</h2></div><span class="status ${p.health.tone}">${p.health.score}</span></div>${row('Safe Mode',p.health.safeMode?'Těžké rozšíření jsou omezené':'Normální režim',p.health.safeMode?'ZAPNUTO':'VYPNUTO')}${row('Dlouhé blokace',`${p.health.longTasks.length} zaznamenaných`,p.health.mem.usedMB?`${p.health.mem.usedMB} MB RAM`:'RAM N/A')}${p.health.lastCrash?row('Poslední pád',p.health.lastCrash.where,p.health.lastCrash.at):row('Crash recovery','Bez čerstvého pádu','OK')}<div class="actions"><button class="btn" id="p43SafeMode">${p.health.safeMode?'Vypnout Safe Mode':'Spustit Safe Mode'}</button><button class="btn" id="p43ClearQuarantine">Vyčistit karanténu</button></div></section><section class="card"><div class="card-head"><div><div class="eyebrow">BRAIN 43</div><h2>Důvody, jistota a protiargument</h2></div><span class="status ${p.brain.accuracy===null?'':'good'}">${p.brain.accuracy===null?'učí se':p.brain.accuracy+' % accuracy'}</span></div>${p.brain.top.map(x=>row(x.title,`${x.why} Protiargument: ${x.counter}`,`${x.confidence}%`)).join('')||'<div class="empty">Žádná priorita.</div>'}</section></div>
<div class="grid two life42-grid"><section class="card"><div class="card-head"><div><div class="eyebrow">DIRECTOR INTELLIGENCE</div><h2>Pobočka ${p.director.score}/100</h2></div><span class="status ${p.director.score>=80?'good':p.director.score>=60?'warn':'bad'}">${p.director.overdue} po termínu</span></div>${p.director.risk.slice(0,5).map(x=>row(x.title,x.kind,x.score)).join('')||'<div class="empty">Žádný pracovní požár.</div>'}<div class="metric-strip"><div class="metric"><span>Faktury otevřené</span><b>${p.cash.open}</b></div><div class="metric"><span>Po splatnosti</span><b>${p.cash.overdue}</b></div><div class="metric"><span>Hodnota</span><b>${money(p.cash.value)}</b></div></div></section><section class="card"><div class="card-head"><div><div class="eyebrow">WAITING FOR AUTOPILOT</div><h2>Follow-up bez zapomínání</h2></div><span class="status ${p.waiting.some(x=>x.followUp)?'warn':'good'}">${p.waiting.filter(x=>x.followUp).length} k urgenci</span></div>${p.waiting.slice(0,5).map(x=>row(x.title||x.description||'Waiting For',x.followUp?x.draft:`čekání ${x.age} d`,x.followUp?'URGOVAT':'' )).join('')||'<div class="empty">Nic nečeká.</div>'}</section></div>
<div class="grid two life42-grid"><section class="card"><div class="card-head"><div><div class="eyebrow">MONEY DISCIPLINE</div><h2>Portfolio + sell pravidla</h2></div><span class="status">${p.portfolio.positions.length} pozic</span></div>${p.portfolio.positions.slice(0,5).map(x=>row(x.name,`${x.sell}${x.thesis?` · thesis: ${x.thesis}`:' · thesis chybí'}`,`opp ${Math.round(x.opportunity)}`)).join('')||'<div class="empty">Portfolio data nejsou načtená.</div>'}<div class="decision-note">Měsíční allocator: cca ${money(p.portfolio.allocator)} na pozici. FX režim: ${safe(p.portfolio.fx)}.</div></section><section class="card"><div class="card-head"><div><div class="eyebrow">TICKET EDGE 43</div><h2>Sell window + dynamická cena</h2></div><span class="status ${p.tickets.rows.some(x=>x.days!==null&&x.days<=7)?'warn':'good'}">${p.tickets.rows.length} otevřených</span></div>${p.tickets.rows.slice(0,5).map(x=>row(x.title,`${x.window} · prodej ${x.prob}% · capital eff. ${x.capitalEfficiency}%/den`,`≈ ${money(x.recommendedPrice)}`)).join('')||'<div class="empty">Žádné aktivní vstupenky.</div>'}${p.tickets.presales.length?`<div class="decision-note">Nejbližší presale: ${safe(p.tickets.presales[0].title)} · ${p.tickets.presales[0].days} d</div>`:''}</section></div>
<div class="grid two life42-grid"><section class="card"><div class="card-head"><div><div class="eyebrow">PEOPLE + WORKLOAD</div><h2>Kdo je přetížený</h2></div><span class="status">${p.workload.length} lidí</span></div>${p.workload.slice(0,6).map(x=>row(x.name,`${x.open} otevřených · ${x.overdue} po termínu`,`${x.load}% load`)).join('')||'<div class="empty">Nemám dost přiřazených lidí.</div>'}</section><section class="card"><div class="card-head"><div><div class="eyebrow">MEETING RADAR</div><h2>${safe(p.meeting?.title||'Žádná blízká porada')}</h2></div></div>${p.meeting?.related?.map(x=>row(x.title,x.kind,x.days===null?'':`${x.days} d`)).join('')||'<div class="empty">Žádné související otevřené body.</div>'}</section></div>
<section class="card"><div class="card-head"><div><div class="eyebrow">SCENARIO COMPARISON</div><h2>Co když něco odložím nebo přidám cash?</h2></div></div><div class="platform43-scenario"><label>Odklad dní <input id="p43Delay" type="number" min="0" max="90" value="${scenarioDelay}"></label><label>Extra cash <input id="p43Cash" type="number" step="1000" value="${scenarioCash}"></label></div><div class="decision-note" id="p43ScenarioText">${safe(sc.text)}</div></section>
<section class="card"><div class="card-head"><div><div class="eyebrow">60-FEATURE DELIVERY MAP</div><h2>Budoucí roadmapa už běží jako platforma</h2></div><span class="status good">${p.features.filter(x=>x.active).length}/60 aktivních runtime schopností</span></div>${featureGrid(p.features)}</section>`;
const anchor=host.querySelector('#lifeOs42')||host.lastElementChild;anchor?.insertAdjacentElement('afterend',root);bind(root)}
function bind(root){root.querySelector('#p43SafeMode')?.addEventListener('click',()=>{setSafeMode43(!platformSnapshot43(store.get()).health.safeMode);render()});root.querySelector('#p43ClearQuarantine')?.addEventListener('click',()=>{clearQuarantine43();render()});root.querySelectorAll('[data-p43-done]').forEach(b=>b.addEventListener('click',()=>{recordDecision43({id:b.dataset.p43Done,source:b.dataset.source,kind:b.dataset.kind},'accepted','good');render()}));const d=root.querySelector('#p43Delay'),c=root.querySelector('#p43Cash'),paint=()=>{scenarioDelay=Math.max(0,Number(d?.value||0));scenarioCash=Number(c?.value||0);const sc=scenario43(store.get(),{extraCash:scenarioCash,delayDays:scenarioDelay});const t=root.querySelector('#p43ScenarioText');if(t)t.textContent=sc.text};d?.addEventListener('input',paint);c?.addEventListener('input',paint)}
let timer=null;function schedule(){clearTimeout(timer);timer=setTimeout(()=>{if(document.querySelector('#view-today')?.classList.contains('on'))render()},250)}
startPlatform43();store.subscribe(schedule);window.addEventListener('kamil:view-change',e=>{if(e.detail==='today')schedule()});window.addEventListener('kamil:today-full-ready',schedule);window.addEventListener('kamil:platform43',schedule);schedule();
