import {store} from './state.js';
import {portfolioRebalancePlan,rebalanceTargets,classifyRebalancePosition,REBALANCE_BUCKETS,REBALANCE_LABELS} from './portfolioRebalancer29.js';
import {h,qs,toast} from './utils.js';

const id='portfolioRebalancer29Host';
let lastInputs=null;
const money=(v,c)=>`${Number(v||0).toLocaleString('cs-CZ',{maximumFractionDigits:0})} ${h(c)}`;
const pct=v=>`${Number(v||0).toLocaleString('cs-CZ',{maximumFractionDigits:1})} %`;
function positions(s){const out=[];for(const [accountId,a] of Object.entries(s.xtbHub?.accounts||s.xtbHub?.report?.accounts||{}))for(const p of a?.positions||[])if(p&&p.sold!==true&&Number(p.value)>0)out.push({...p,ticker:p.ticker||p.symbol||'',accountId,accountCurrency:String(a.currency||p.currency||'CZK').toUpperCase(),bucket:classifyRebalancePosition(p,s)});return out}
function currencies(s){const set=new Set([String(s.financePlan?.currency||'CZK').toUpperCase()]);for(const a of Object.values(s.xtbHub?.accounts||s.xtbHub?.report?.accounts||{}))if(a?.currency)set.add(String(a.currency).toUpperCase());return [...set].sort()}
function preferredOptions(s,bucket){const rows=positions(s).filter(x=>x.bucket===bucket),selected=s.xtbStrategy?.rebalancePreferred?.[bucket]||'';return `<option value="">${bucket==='satellite'?'Vybrat ručně při nákupu':'Automaticky použít existující jádro'}</option>${rows.map(x=>`<option value="${h(x.ticker)}" ${x.ticker===selected?'selected':''}>${h(x.ticker)} · ${h(x.name||'')}</option>`).join('')}`}
function inputsFromDom(s){return {contribution:Number(qs('#rebalanceContribution')?.value),currency:qs('#rebalanceCurrency')?.value||s.financePlan?.currency||'CZK',targets:{broad:Number(qs('#rebalanceBroad')?.value),bond:Number(qs('#rebalanceBond')?.value),satellite:Number(qs('#rebalanceSatellite')?.value)}}}
function savePlan(s){const input=inputsFromDom(s),preferred=Object.fromEntries(REBALANCE_BUCKETS.map(k=>[k,qs(`#rebalancePreferred-${k}`)?.value||'']));const sum=Object.values(input.targets).reduce((a,b)=>a+Number(b||0),0);if(Math.abs(sum-100)>0.05)return toast(`Cíle musí dát 100 %. Teď: ${sum.toFixed(1)} %`);store.mutate('Uložen investiční rebalanční plán',state=>{state.xtbStrategy=state.xtbStrategy||{overrides:{}};state.xtbStrategy.rebalanceTargets=input.targets;state.xtbStrategy.rebalancePreferred=preferred});toast('Rebalanční cíle uloženy')}
function renderResult(host,s,input){
 const r=portfolioRebalancePlan(s,input),box=qs('#rebalanceResult',host);if(!box)return;if(!r.ok){box.innerHTML=`<div class="decision-note"><b class="bad">Plán nevytvořen</b><div>${h(r.message)}</div></div>`;return}
 const buckets=REBALANCE_BUCKETS.map(k=>{const x=r.byBucket[k];return `<div class="row"><div><b>${h(x.label)}</b><div class="muted">teď ${pct(x.currentPct)} · cíl ${pct(x.targetPct)} · po vkladu ${pct(x.afterPct)}</div></div><b class="${x.buyAmount>0?'good':''}">${x.buyAmount>0?`+ ${money(x.buyAmount,r.currency)}`:'0'}</b></div>`}).join('');
 const trades=r.trades.map(x=>x.requiresChoice?`<div class="autopilot29-row"><div><b>${h(x.label)} · vyber ticker</b><small>${h(x.reason)}</small></div><b>${money(x.baseAmount,x.baseCurrency)}</b></div>`:`<div class="autopilot29-row"><div><b>${h(x.ticker)} · ${h(x.name||x.label)}</b><small>${h(x.label)} · účet ${h(x.accountId||'—')}${x.nativeCurrency!==x.baseCurrency?` · vyžaduje přesun/směnu do ${h(x.nativeCurrency)}`:''}</small></div><div><b>≈ ${money(x.nativeAmount,x.nativeCurrency)}</b>${x.nativeCurrency!==x.baseCurrency?`<small class="muted">${money(x.baseAmount,x.baseCurrency)} v základní měně</small>`:''}</div></div>`).join('')||'<div class="empty">Nový vklad podle cíle nevyžaduje žádný nákup.</div>';
 const residual=r.residual.map(x=>`<span class="chip">${h(x.label)} ${x.deltaPct>0?'+':''}${pct(x.deltaPct)}</span>`).join('');
 const over=r.overweights.map(x=>`<div class="audit-risk"><b class="warn">PŘEVAHA</b><span>${h(x.label)} je i po započtení nového vkladu nad cílovou částkou přibližně o ${money(x.excess,r.currency)}.</span></div>`).join('');
 box.innerHTML=`<div class="metric-strip"><div class="metric"><span>Nový vklad</span><b>${money(r.contribution,r.currency)}</b></div><div class="metric"><span>Odchylka teď</span><b>${pct(r.currentDriftPct)}</b></div><div class="metric"><span>Odchylka po vkladu</span><b class="${r.afterDriftPct<r.currentDriftPct?'good':'warn'}">${pct(r.afterDriftPct)}</b></div><div class="metric"><span>Zlepšení</span><b>${pct(r.improvementPct)}</b></div></div><h3>Rozdělení nového vkladu</h3>${buckets}<h3>Konkrétní nákupní kroky</h3>${trades}${over?`<h3>Co nový vklad sám nevyřeší</h3>${over}`:''}${residual?`<div class="chip-row" style="margin-top:12px">${residual}</div>`:''}<div class="decision-note"><b>${r.perfect?'Cíl lze tímto vkladem dorovnat.':'Jde o nejlepší přiblížení bez prodeje.'}</b><div>${h(r.note)}</div></div>`;
}
function render(){
 const view=qs('#moneyView');if(!view)return;qs(`#${id}`,view)?.remove();const s=store.get(),targets=rebalanceTargets(s),ccys=currencies(s),planned=Number(s.financePlan?.plannedInvestment||0),host=document.createElement('div');host.id=id;
 const current=lastInputs||{contribution:planned>0?planned:'',currency:String(s.financePlan?.currency||ccys[0]||'CZK').toUpperCase(),targets};
 host.innerHTML=`<div class="card"><div class="card-head"><div><div class="eyebrow">PORTFOLIO REBALANCER / 29.7</div><h2>Co přesně koupit za nový vklad</h2><p class="muted">Optimalizace pouze novými penězi. Žádný automatický prodej a žádný vymyšlený ticker.</p></div><span class="status">NO-SALE</span></div><div class="form-grid"><label>Nový vklad<input id="rebalanceContribution" type="number" min="0" step="1" value="${h(current.contribution)}" placeholder="např. 25000"></label><label>Měna vkladu<select id="rebalanceCurrency">${ccys.map(c=>`<option value="${h(c)}" ${c===current.currency?'selected':''}>${h(c)}</option>`).join('')}</select></label><label>Široké ETF %<input id="rebalanceBroad" type="number" min="0" max="100" step="0.5" value="${h(current.targets.broad)}"></label><label>Dluhopisy %<input id="rebalanceBond" type="number" min="0" max="100" step="0.5" value="${h(current.targets.bond)}"></label><label>Satelity %<input id="rebalanceSatellite" type="number" min="0" max="100" step="0.5" value="${h(current.targets.satellite)}"></label></div><details style="margin-top:12px"><summary>Preferované tickery pro nákup</summary><div class="form-grid" style="margin-top:10px">${REBALANCE_BUCKETS.map(k=>`<label>${h(REBALANCE_LABELS[k])}<select id="rebalancePreferred-${k}">${preferredOptions(s,k)}</select></label>`).join('')}</div><p class="muted">Bez preference používá Kamil OS u širokého ETF/dluhopisů největší existující pozici. U více satelitních akcií ticker sám nevolí.</p></details><div class="row-actions" style="margin-top:12px"><button class="btn primary" id="rebalanceCalc">Spočítat bez prodeje</button><button class="btn" id="rebalanceSave">Uložit cíle</button></div><div id="rebalanceResult" style="margin-top:14px"></div></div>`;
 const anchor=qs('#trueNetWorth29Host',view)||qs('#personalMoney26Host',view)||view.querySelector('.view-head');if(anchor)anchor.insertAdjacentElement('afterend',host);else view.prepend(host);
 qs('#rebalanceCalc',host)?.addEventListener('click',()=>{lastInputs=inputsFromDom(s);renderResult(host,store.get(),lastInputs)});qs('#rebalanceSave',host)?.addEventListener('click',()=>savePlan(s));if(lastInputs)renderResult(host,s,current);
}
const start=()=>{const view=qs('#moneyView');if(!view)return;new MutationObserver(()=>{if(!qs(`#${id}`,view))queueMicrotask(render)}).observe(view,{childList:true,subtree:false});store.subscribe((s,reason)=>{if(reason==='Uložen investiční rebalanční plán'||reason==='cloud'||reason==='backup-import')queueMicrotask(render)});render()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
