import {store} from './state.js';
import {qs,h,money,date} from './utils.js';
import {xtbBoard,actionLabel} from './live24.js';
import {xtbContributionPlan32} from './xtbContribution32.js';
import {ticketEventPortfolio32} from './ticketPortfolio32.js';

let queued=false;
const n=v=>Number(v||0),tone=x=>x>=90?'bad':x>=75?'warn':'good';
const mount=(view,id,afterId)=>{let host=qs(`#${id}`,view);if(host)return host;host=document.createElement('div');host.id=id;const after=afterId?qs(`#${afterId}`,view):null,head=view?.querySelector('.view-head');if(after)after.insertAdjacentElement('afterend',host);else if(head)head.insertAdjacentElement('afterend',host);else view?.prepend(host);return host};
const accountAmount=x=>x.accountAmount===null?'—':`${Number(x.accountAmount).toLocaleString('cs-CZ',{maximumFractionDigits:2})} ${h(x.accountCurrency||'')}`;
const czkPlain=v=>`${Number(v||0).toLocaleString('cs-CZ',{maximumFractionDigits:0})} Kč`;
function allocationAudit(a){const fx=a?.currencyBreakdown||[];return `<div class="card"><div class="card-head"><div><div class="eyebrow">XTB / FX-SAFE AUDIT 32.5</div><h2>Portfolio audit bez míchání měn</h2><p class="muted">Každý účet se nejdřív přepočte do CZK čerstvým FX. Když kurz chybí, skóre i přesná alokace se záměrně skryjí.</p></div><span class="status ${a?.valuationComplete?'good':'warn'}">${a?.valuationComplete?'FX OVĚŘENO':'ČEKÁ NA FX'}</span></div><div class="metric-strip">${a?.valuationComplete?`<div class="metric"><span>Celkem po FX</span><b>${h(czkPlain(a.total))}</b><small>${a.valuedPositions||0} oceněných pozic</small></div>`:''}${fx.map(x=>`<div class="metric"><span>${h(x.currency)} účet</span><b>${x.complete?money(x.czkValue):'—'}</b><small>${x.currency==='CZK'?'1:1':x.rateToCzk?`1 ${h(x.currency)} = ${Number(x.rateToCzk).toLocaleString('cs-CZ',{maximumFractionDigits:4})} Kč`:'kurz chybí'}</small></div>`).join('')||'<div class="metric"><span>Účty</span><b>—</b><small>zatím bez pozic</small></div>'}</div>${a?.valuationComplete?`<div class="audit-score"><b class="${n(a.healthScore)<70?'warn':'good'}">${Math.round(n(a.healthScore))}</b><span>skóre alokace / 100<br>počítáno z FX-normalizovaných hodnot</span></div><div class="audit-mix"><div><span>Široké ETF</span><b>${n(a.mix?.broadPct).toFixed(1)} %</b><small>cíl ${h(a.targets?.broad||'')}</small></div><div><span>Dluhopisy</span><b>${n(a.mix?.bondPct).toFixed(1)} %</b><small>cíl ${h(a.targets?.bond||'')}</small></div><div><span>Satelity</span><b>${n(a.mix?.satellitePct).toFixed(1)} %</b><small>cíl ${h(a.targets?.satellite||'')}</small></div></div>`:`<div class="decision-note warn">Chybí čerstvý kurz ${h((a?.missingFx||[]).join(', ')||'cizí měny')} → CZK. Do načtení FX neukazuji health score, procenta portfolia ani přesný návrh dalšího vkladu.</div>`}<div class="audit-next"><b>Další vklad:</b> ${h(a?.nextContribution||'Čekám na data.')}</div></div>`}
function contributionCard(state){const p=xtbContributionPlan32(state),fx=p.audit?.currencyBreakdown||[];return `${allocationAudit(p.audit)}<div class="card" style="margin-top:12px"><div class="card-head"><div><div class="eyebrow">XTB / PROFIT CONTROL 32.5</div><h2>Dalších ${money(p.plannedCzk)} — přesný plán</h2><p class="muted">Alokace podle skutečné hodnoty účtů po FX přepočtu. Veřejná cena slouží jen k orientačnímu počtu kusů.</p></div><span class="status ${p.blocked?'warn':'good'}">${p.blocked?'BLOKOVÁNO':'PŘIPRAVENO'}</span></div>${fx.length?`<div class="metric-strip">${fx.map(x=>`<div class="metric"><span>${h(x.currency)} účet</span><b>${x.complete?money(x.czkValue):'čeká na FX'}</b><small>${x.rateToCzk&&x.currency!=='CZK'?`1 ${h(x.currency)} = ${Number(x.rateToCzk).toLocaleString('cs-CZ',{maximumFractionDigits:4})} Kč`:'v základní měně'}</small></div>`).join('')}</div>`:''}${p.blocked?`<div class="decision-note warn">${h(p.reason)}</div>`:`<div class="decision-note">${h(p.reason)}</div><div>${p.allocations.map(x=>`<div class="row" style="align-items:flex-start"><div><b>${h(x.name||x.bucket)} · ${h(x.ticker||'')}</b><div class="muted">${h(x.reason)}</div>${x.quote?`<div class="muted">Quote ${Number(x.quote.price).toLocaleString('cs-CZ',{maximumFractionDigits:4})} ${h(x.quote.currency)} · pouze odhad kusů</div>`:''}</div><div style="text-align:right"><b>${money(x.amountCzk)}</b><div class="muted">na účet ≈ ${accountAmount(x)}</div>${x.estimatedQty?`<div class="muted">≈ ${Number(x.estimatedQty).toLocaleString('cs-CZ',{maximumFractionDigits:4})} ks</div>`:''}</div></div>`).join('')}</div>`}<div class="decision-note">${h(p.note||'')} Kamil OS nic neposílá brokerovi.</div></div>`}
function ticketPortfolioCard(state){const p=ticketEventPortfolio32(state);return `<div class="card"><div class="card-head"><div><div class="eyebrow">VSTUPENKY / PROFIT CONTROL 32.5</div><h2>Event Portfolio & Action Queue</h2><p class="muted">Stejné akce už nevidím jako izolované řádky. Sčítám počet kusů, kapitál, listing coverage a market coverage za celý event.</p></div><span class="status ${p.queue.urgent?'warn':'good'}">${p.totalEvents} eventů</span></div><div class="metric-strip"><div class="metric"><span>Kapitál v eventech</span><b>${money(p.totalCapital)}</b></div><div class="metric"><span>Urgentní balíky</span><b>${p.queue.urgent}</b></div><div class="metric"><span>Chybí list cena</span><b>${p.missingListed}</b></div><div class="metric"><span>Stale market</span><b>${p.staleMarket}</b></div></div>${p.events.slice(0,6).map(e=>`<div class="row" style="align-items:flex-start;gap:12px"><div style="min-width:0;flex:1"><div><span class="status ${tone(e.priority)}">${e.priority}</span> <b>${h(e.name)}</b></div><div class="muted">${h(date(e.date))} · ${e.qty} ks · ${money(e.capitalAtRisk)} · ${e.capitalPct.toFixed(1)} % ticket kapitálu</div><div style="margin-top:4px"><b>${h(e.nextAction)}</b></div></div><div style="text-align:right;min-width:145px"><div class="muted">list ${e.listCoveragePct} %</div><div class="muted">fresh market ${e.marketCoveragePct} %</div><div class="muted">transfer ready ${e.transferReadyPct} %</div><span class="status ${e.exposure==='HIGH'?'bad':e.exposure==='MEDIUM'?'warn':'good'}">${h(e.exposure)}</span></div></div>`).join('')||'<div class="empty">Žádné aktivní eventy.</div>'}<div class="decision-note">Fronta neprodává ani nepřepisuje cenu sama. Říká, kterou konkrétní položku má smysl zkontrolovat jako první.</div></div>`}
function todayCard(state){const tickets=ticketEventPortfolio32(state),xtb=xtbBoard(state).filter(x=>['BUY','TRIM','SELL','REVIEW'].includes(String(x.d.action||'').toUpperCase())).slice(0,3),items=[];if(tickets.queue.top)items.push({kind:'Vstupenky',title:tickets.queue.top.name,priority:tickets.queue.top.score,action:tickets.queue.top.nextInput||tickets.queue.top.decision.when,target:'tickets'});for(const x of xtb)items.push({kind:'XTB',title:`${x.p.ticker} · ${actionLabel(x.d.action)}`,priority:n(x.d.priority),action:x.d.execution?.blocked?x.d.execution.blockReason:(x.d.reviewReason||x.d.when),target:'money'});items.sort((a,b)=>b.priority-a.priority);return `<div class="card"><div class="card-head"><div><div class="eyebrow">PROFIT CONTROL 32.5</div><h2>Peníze, které dnes potřebují pozornost</h2><p class="muted">Jedna krátká fronta jen z XTB a resale vstupenek.</p></div><span class="status ${items.some(x=>x.priority>=90)?'warn':'good'}">${items.filter(x=>x.priority>=75).length} priorit</span></div>${items.slice(0,4).map(x=>`<button class="row" data-profit-nav="${h(x.target)}" style="width:100%;text-align:left;background:none;border:0;color:inherit;cursor:pointer"><div><b>${h(x.kind)} · ${h(x.title)}</b><div class="muted">${h(x.action||'')}</div></div><span class="status ${tone(x.priority)}">${Math.round(x.priority)}</span></button>`).join('')||'<div class="empty success-empty">XTB ani vstupenky teď nemají akční výjimku.</div>'}</div>`}
function bindNav(host){host?.querySelectorAll('[data-profit-nav]').forEach(b=>b.addEventListener('click',()=>qs(`#mainNav [data-view="${b.dataset.profitNav}"]`)?.click()))}
function removeLegacyAudit(moneyView){moneyView?.querySelector('.audit-grid')?.remove()}
function render(){const s=store.get(),moneyView=qs('#moneyView'),ticketsView=qs('#ticketsView'),todayView=qs('#todayView');if(moneyView?.querySelector('.view-head')){removeLegacyAudit(moneyView);const hst=mount(moneyView,'profitControlMoney32Host','marketEdgeXtb32Host');hst.innerHTML=contributionCard(s)}if(ticketsView?.querySelector('.view-head')){const hst=mount(ticketsView,'profitControlTickets32Host','marketEdgeTicket32Host');hst.innerHTML=ticketPortfolioCard(s)}if(todayView?.querySelector('.view-head')){const hst=mount(todayView,'profitControlToday32Host');hst.innerHTML=todayCard(s);bindNav(hst)}}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;render()})}
function observe(view){if(view)new MutationObserver(()=>schedule()).observe(view,{childList:true,subtree:false})}
function start(){observe(qs('#moneyView'));observe(qs('#ticketsView'));observe(qs('#todayView'));window.addEventListener('kamil:market-quotes',schedule);window.addEventListener('kamil:source-ingest',schedule);window.addEventListener('kamil:navigate',schedule);store.subscribe(schedule);setTimeout(render,300)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
