import {store} from './state.js';
const VERSION=472;
const N=v=>Number.isFinite(Number(v))?Number(v):0;
const clamp=(v,min,max)=>Math.min(max,Math.max(min,N(v)));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`;
const pct=v=>`${(N(v)*100).toFixed(2).replace('.',',')} %`;
const isTodayEvent=e=>{const d=e?.detail;return !d||d==='today'||d?.view==='today'};
const DEFAULTS={vacancyRate:.05,maintenanceRate:.05,targetNetYield:.04,minBuyScore:75,minNegotiateScore:55,downsideRentDrop:.10,downsideVacancy:.10,downsideMaintenance:.07};
function cfg(x={}){return{...DEFAULTS,...x}}
function ensureCss(){if(document.querySelector('link[data-property-decision472-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./propertyDecision472.css';l.dataset.propertyDecision472Css='1';document.head.appendChild(l)}
function sourceCandidates(s=store.get()){const rows=s?.propertyBook?.candidates;return Array.isArray(rows)?rows:[]}
export function evaluateProperty472(x={},options={}){
 const c=cfg(options),purchasePrice=Math.max(0,N(x.purchasePrice||x.priceCzk||x.price)),renovation=Math.max(0,N(x.renovationCzk||x.renovation)),acquisition=Math.max(0,N(x.acquisitionCostsCzk||x.acquisitionCosts)),totalCost=purchasePrice+renovation+acquisition,monthlyRent=Math.max(0,N(x.monthlyRent||x.rentCzk||x.rent)),fund=Math.max(0,N(x.monthlyFund||x.fundCzk||x.fund)),ownerCosts=Math.max(0,N(x.monthlyOwnerCosts||x.ownerCostsCzk||x.ownerCosts)),vacancy=clamp(x.vacancyRate??c.vacancyRate,0,.5),maintenance=clamp(x.maintenanceRate??c.maintenanceRate,0,.5),annualGross=monthlyRent*12,annualNet=Math.max(0,annualGross*(1-vacancy-maintenance)-(fund+ownerCosts)*12),grossYield=totalCost?annualGross/totalCost:0,netYield=totalCost?annualNet/totalCost:0;
 const downRent=monthlyRent*(1-c.downsideRentDrop),downNet=Math.max(0,downRent*12*(1-Math.max(vacancy,c.downsideVacancy)-Math.max(maintenance,c.downsideMaintenance))-(fund+ownerCosts*1.1)*12),downsideYield=totalCost?downNet/totalCost:0,targetPrice=annualNet>0?annualNet/c.targetNetYield:0,discountToTarget=purchasePrice>0?(targetPrice-purchasePrice)/purchasePrice:0;
 const location=clamp(x.locationScore??50,0,100),condition=clamp(x.conditionScore??50,0,100),liquidity=clamp(x.liquidityScore??50,0,100),yieldScore=clamp((netYield/c.targetNetYield)*60,0,60),downsideScore=clamp((downsideYield/c.targetNetYield)*20,0,20),qualityScore=(location*.08)+(condition*.05)+(liquidity*.07),score=Math.round(clamp(yieldScore+downsideScore+qualityScore,0,100));
 const missing=[];if(!purchasePrice)missing.push('purchasePrice');if(!monthlyRent)missing.push('monthlyRent');const dataReady=missing.length===0;
 let code='PASS',action='NEBRAT',reason='Výnos nebo kvalita neprochází bezpečnostní hranicí.';if(!dataReady){code='INCOMPLETE';action='DOPLNIT DATA';reason='Chybí kupní cena nebo očekávaný nájem.'}else if(score>=c.minBuyScore&&netYield>=c.targetNetYield&&downsideYield>=c.targetNetYield*.7){code='BUY';action='KOUPIT / POKRAČOVAT';reason=`Net yield ${pct(netYield)} a downside ${pct(downsideYield)} procházejí limitem.`}else if(score>=c.minNegotiateScore&&targetPrice>0&&targetPrice<purchasePrice){code='NEGOTIATE';action='VYJEDNÁVAT';reason=`Modelová cílová cena je přibližně ${money(targetPrice)}.`}else if(score>=c.minNegotiateScore&&netYield>=c.targetNetYield*.8){code='NEGOTIATE';action='VYJEDNÁVAT';reason=`Výnos ${pct(netYield)} je blízko cíli; rozhoduje sleva nebo lepší nájem.`}
 return{id:x.id||null,name:x.name||x.title||'Nemovitost',location:x.location||null,purchasePrice,totalCost,monthlyRent,annualGross,annualNet,grossYield,netYield,downsideYield,targetPrice,discountToTarget,score,locationScore:location,conditionScore:condition,liquidityScore:liquidity,dataReady,missing,decision:{code,action,reason},guardrails:{usesNetYield:true,downsideRequired:true,missingDataBlocksBuy:true,autoExecute:false}}
}
export function buildPropertyDecision472(s=store.get(),options={}){const rows=sourceCandidates(s).map(x=>evaluateProperty472(x,options)).sort((a,b)=>b.score-a.score||b.netYield-a.netYield),best=rows[0]||null;return{version:VERSION,healthy:true,candidates:rows,best,counts:{buy:rows.filter(x=>x.decision.code==='BUY').length,negotiate:rows.filter(x=>x.decision.code==='NEGOTIATE').length,pass:rows.filter(x=>x.decision.code==='PASS').length,incomplete:rows.filter(x=>x.decision.code==='INCOMPLETE').length},recommendation:best?best.decision:{code:'EMPTY',action:'PŘIDAT KANDIDÁTA',reason:'V Property Booku zatím není žádná investiční nemovitost.'},generatedAt:new Date().toISOString(),guardrails:{genericEngine:true,noHardcodedPrivateData:true,autoExecute:false}}
}
function row(x){return `<div class="os472-row ${x.decision.code.toLowerCase()}"><div><small>${esc(x.decision.action)} · SCORE ${x.score}/100</small><b>${esc(x.name)}</b><span>${esc(x.location||'Lokalita neuvedena')} · net ${pct(x.netYield)} · downside ${pct(x.downsideYield)}</span></div><div><b>${money(x.purchasePrice)}</b><span>${x.targetPrice?`cíl ${money(x.targetPrice)}`:'cíl —'}</span></div></div>`}
function card(m){const rows=m.candidates.slice(0,4).map(row).join('')||'<div class="os472-empty">Zatím není žádný kandidát. Engine čeká na data v existujícím Property Booku.</div>';return `<article class="os467-card os472" data-property-decision472-root><header><div><small>OS472 · PROPERTY DECISION</small><h3>Investiční byty: BUY / NEGOTIATE / PASS</h3></div><b>${m.candidates.length}</b></header><div class="os472-verdict ${String(m.recommendation.code).toLowerCase()}"><b>${esc(m.recommendation.action)}</b><span>${esc(m.recommendation.reason)}</span></div><div class="os472-list">${rows}</div><footer>Net yield + downside + likvidita + stav · žádné automatické rozhodnutí</footer></article>`}
function mount(){const grid=document.querySelector('[data-command-center467-root] .os467-grid');if(!grid)return false;const m=buildPropertyDecision472(),first=!window.__KAMIL_PROPERTY_DECISION472__;let host=grid.querySelector('[data-property-decision472-root]');const wrap=document.createElement('div');wrap.innerHTML=card(m);const next=wrap.firstElementChild;let changed=false;if(host){if(host.innerHTML!==next.innerHTML||host.className!==next.className){host.replaceWith(next);host=next;changed=true}}else{const anchor=grid.querySelector('[data-free-cash470-root]')||grid.querySelector('[data-capital-plan469-root]')||grid.querySelector('[data-cashflow468-root]');anchor?anchor.after(next):grid.appendChild(next);host=next;changed=true}window.__KAMIL_PROPERTY_DECISION472__={version:VERSION,healthy:true,mounted:!!host,model:m,refresh:renderSafe,evaluate:evaluateProperty472,at:Date.now()};document.documentElement.dataset.propertyDecision472='1';if(first||changed)window.dispatchEvent(new CustomEvent('kamil:property-decision472-updated',{detail:{candidates:m.candidates.length,best:m.best?.decision?.code||'EMPTY',changed}}));return true}
function renderSafe(){try{return mount()}catch(error){console.error('[propertyDecision472]',error);window.__KAMIL_PROPERTY_DECISION472__={version:VERSION,healthy:false,error:String(error?.message||error),refresh:renderSafe,at:Date.now()};return false}}
let timer=0,bound=false;const schedule=(delay=60)=>{clearTimeout(timer);timer=setTimeout(renderSafe,delay)};
export function installPropertyDecision472(){ensureCss();document.documentElement.dataset.propertyDecision472='1';if(!bound){bound=true;store.subscribe?.(()=>schedule(80));for(const event of ['kamil:command-center467-updated','kamil:cashflow468-updated','kamil:capital-plan469-updated','kamil:free-cash470-updated'])window.addEventListener(event,()=>schedule(25));window.addEventListener('kamil:view-change',e=>{if(isTodayEvent(e))schedule(35)});window.addEventListener('focus',()=>schedule(30))}renderSafe();setTimeout(()=>schedule(20),850);setTimeout(()=>schedule(20),1800)}
