import {store} from './state.js';
import {h} from './utils.js';

const VERSION=610;
const A=v=>Array.isArray(v)?v:[];
const N=v=>Number.isFinite(Number(v))?Number(v):0;
const money=v=>`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`;
function css(){if(document.querySelector('link[data-upgrade610-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./upgrade610.css';l.dataset.upgrade610Css='1';document.head.appendChild(l)}
function settings(s=store.get()){const x=s.propertyBook?.mortgageScenario||{};return{ratePct:x.ratePct??'',equityPct:Number.isFinite(Number(x.equityPct))?Number(x.equityPct):20,years:Number.isFinite(Number(x.years))?Number(x.years):30}}
function payment(principal,ratePct,years){principal=Math.max(0,N(principal));const n=Math.max(1,Math.round(N(years)*12)),r=Math.max(0,N(ratePct))/100/12;if(!principal)return 0;if(!r)return principal/n;return principal*(r*Math.pow(1+r,n))/(Math.pow(1+r,n)-1)}
function sourceCandidates(s=store.get()){return A(s.propertyBook?.candidates).map(x=>({id:x.id,name:x.name||x.title||'Nemovitost',location:x.location||'',price:N(x.purchasePrice||x.priceCzk||x.price),rent:N(x.monthlyRent||x.rentCzk||x.rent),fund:N(x.monthlyFund||x.fundCzk||x.fund),owner:N(x.monthlyOwnerCosts||x.ownerCostsCzk||x.ownerCosts)})).filter(x=>x.price>0).slice(0,6)}
function scenarioRows(x,cfg){if(!(N(cfg.ratePct)>0))return[];const loan=x.price*(1-N(cfg.equityPct)/100),rates=[{label:'Lepší sazba',rate:Math.max(.1,N(cfg.ratePct)-.75)},{label:'Základ',rate:N(cfg.ratePct)},{label:'Stress',rate:N(cfg.ratePct)+1.5}];return rates.map(r=>{const monthly=payment(loan,r.rate,cfg.years),cash=x.rent-x.fund-x.owner-monthly;return{...r,monthly,cash}})}
function propertyHtml(x,cfg){const equity=x.price*N(cfg.equityPct)/100,loan=x.price-equity,rows=scenarioRows(x,cfg);return `<div class="os610-property"><div class="os610-property-top"><div><b>${h(x.name)}</b><small>${h(x.location||'Lokalita neuvedena')} · cena ${money(x.price)} · nájem ${x.rent?money(x.rent):'—'}</small></div><strong>Úvěr ${money(loan)}</strong></div>${rows.length?`<div class="os610-scenarios">${rows.map(r=>`<div class="os610-scenario"><small>${h(r.label)} · ${r.rate.toFixed(2).replace('.',',')} %</small><b>${money(r.monthly)}/měs.</b><em class="${r.cash>=0?'os610-good':'os610-bad'}">cash-flow ${r.cash>=0?'+':''}${money(r.cash)}/měs.</em></div>`).join('')}</div>`:`<div class="muted" style="margin-top:10px">Doplň základní úrokovou sazbu. Pak ukážu lepší, základní a stress scénář.</div>`}<div class="os610-delta" style="margin-top:8px">Vlastní zdroje ${money(equity)} · fond + náklady vlastníka ${money(x.fund+x.owner)}/měs. · bez daní, vacancy a mimořádných oprav.</div></div>`}
function card(){const s=store.get(),cfg=settings(s),items=sourceCandidates(s);return `<section class="os610-card" data-property-finance610><div class="os610-head"><div><small>OS610 · PROPERTY FINANCING LAB</small><h2>Hypoteční scénáře investičních bytů</h2><p>Zadej vlastní předpoklady. OS nic nepředstírá jako bankovní nabídku.</p></div><span class="os610-badge">${items.length} kandidátů</span></div><form class="os610-finance-form" data-property-finance-form610><label>Základní sazba %<input name="ratePct" inputmode="decimal" placeholder="např. 4,7" value="${h(cfg.ratePct)}"></label><label>Vlastní zdroje %<input name="equityPct" inputmode="decimal" value="${h(cfg.equityPct)}"></label><label>Splatnost let<input name="years" inputmode="numeric" value="${h(cfg.years)}"></label><label>&nbsp;<button class="os610-btn primary" type="submit">Přepočítat</button></label></form><div class="os610-property-list">${items.length?items.map(x=>propertyHtml(x,cfg)).join(''):'<div class="muted">V Property Booku zatím nejsou kandidáti s kupní cenou.</div>'}</div></section>`}
function save(form){const data=new FormData(form),rate=Number(String(data.get('ratePct')||'').replace(',','.')),equity=Number(String(data.get('equityPct')||'').replace(',','.')),years=Number(String(data.get('years')||'').replace(',','.'));store.mutate('Upraven hypoteční scénář investičních bytů',s=>{s.propertyBook=s.propertyBook||{candidates:[]};s.propertyBook.mortgageScenario={ratePct:Number.isFinite(rate)&&rate>0?rate:'',equityPct:Number.isFinite(equity)?Math.max(0,Math.min(100,equity)):20,years:Number.isFinite(years)?Math.max(1,Math.min(50,years)):30}})}
function mount(){const host=document.querySelector('#moneyView');if(!host)return false;const old=host.querySelector('[data-property-finance610]'),wrap=document.createElement('div');wrap.innerHTML=card();const next=wrap.firstElementChild;if(old)old.replaceWith(next);else{const anchor=host.querySelector('[data-wealth-history610]')||host.querySelector('[data-money-group="wealth"]');anchor?.after(next);if(!anchor)host.appendChild(next)}next.querySelector('[data-property-finance-form610]')?.addEventListener('submit',e=>{e.preventDefault();save(e.currentTarget);setTimeout(mount,30)});return true}
export function appendPropertyFinance610(){css();const ok=mount();window.__KAMIL_PROPERTY_FINANCE610__={version:VERSION,healthy:ok,settings:settings(),candidates:sourceCandidates(),refresh:mount,at:Date.now()};return ok}
window.addEventListener('kamil:focus610',e=>{if(e.detail?.focus!=='property')return;setTimeout(()=>document.querySelector('[data-property-finance610]')?.scrollIntoView({behavior:'smooth',block:'start'}),180)});
