import {buildPropertyHub620,openPropertyDetail620} from './propertyHub620.js';
import {store} from './state.js';
import {ownEvent1100} from './runtimeOwnership1100.js';

const OWNER='product.property1300';
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const money=v=>`${Math.round(Number(v||0)).toLocaleString('cs-CZ')} Kč`;
const pct=v=>`${(Number(v||0)*100).toFixed(2).replace('.',',')} %`;
const decisionTone=code=>code==='BUY'?'good':code==='NEGOTIATE'||code==='INCOMPLETE'?'warn':code==='PASS'?'bad':'';

function candidateRows(rows){
 if(!rows.length)return '<div class="pr1300-empty">V Property Booku zatím není žádný kandidát.</div>';
 return rows.map((x,i)=>`<button type="button" class="pr1300-row pr1300-clickrow" data-property-shortlist-row data-property-candidate="${x.index}"><div class="pr1300-row-main"><b>${i+1}. ${esc(x.name)}</b><small>${esc(x.location||'Lokalita neuvedena')} · ${money(x.purchasePrice)} · ${x.area?`${String(x.area).replace('.',',')} m² · `:''}net yield ${pct(x.netYield)}</small></div><div class="pr1300-row-side ${decisionTone(x.decision.code)}">${esc(x.decision.action)} · ${x.score}/100 <span class="os1500-row-arrow">→</span></div></button>`).join('');
}
function metric(label,value,tone=''){return '<span class="os1334-property-metric '+tone+'"><small>'+label+'</small><b>'+value+'</b></span>'}

function render(){
 const host=document.querySelector('#propertyView');if(!host)return false;
 const state=store.get(),m=buildPropertyHub620(state),best=m.best,own=best?.equity||0,cf=best?.cashAfterMortgage,gap=best?.targetGap,raw=Array.isArray(state.propertyBook?.candidates)?state.propertyBook.candidates:[];
 const lifecycle={new:0,review:0,negotiating:0,closed:0,bought:0},deadLinks=[];raw.forEach((x,i)=>{const st=String(x.status||x.lifecycle||'REVIEW').toUpperCase();if(['CLOSED','SOLD','REMOVED','REJECTED','ARCHIVED'].includes(st))lifecycle.closed++;else if(['BOUGHT','PURCHASED'].includes(st))lifecycle.bought++;else if(['NEGOTIATING','OFFER','OFFERED'].includes(st))lifecycle.negotiating++;else if(st==='NEW')lifecycle.new++;else lifecycle.review++;if((['CLOSED','SOLD','REMOVED','ARCHIVED'].includes(st)||x.active===false)&&x.url)deadLinks.push({index:i,name:x.name||x.title||'Kandidát',status:st})});const compareLock=Array.isArray(state.ui?.propertyCompareIds)?state.ui.propertyCompareIds.slice(0,4):[];
 const populated=best?'<div class="os1334-decision-grid os1334-property-grid"><section class="pr1320-now os1334-primary"><div><div class="pr1300-kicker">#1 podle Deal Score</div><h2>'+esc(best.name)+'</h2><p>'+esc(best.location||'Lokalita neuvedena')+' · '+esc(best.decision.reason)+'</p></div><div class="pr1320-now-actions"><button class="pr1300-btn primary" type="button" data-property-candidate="'+best.index+'">Otevřít kandidáta →</button><button class="pr1300-btn" type="button" data-property1300-task>＋ Úkol</button></div></section><section class="pr1300-panel os1334-context-panel os1334-property-context"><div class="pr1300-panel-head"><div><h2>'+esc(best.decision.action)+'</h2><span>čísla kandidáta #1</span></div><button class="pr1300-btn" type="button" data-property1300-money>Finanční detail</button></div><div class="os1334-property-metrics">'+metric('Deal Score',best.score+'/100',decisionTone(best.decision.code))+metric('Kupní cena',money(best.purchasePrice))+metric('Cílová cena',best.targetPrice?money(best.targetPrice):'—')+metric('Mezera k cíli',gap===null?'—':(gap>=0?'+':'')+money(gap),gap!==null?(gap>=0?'good':'warn'):'')+metric('Net yield',pct(best.netYield))+metric('Downside yield',pct(best.downsideYield))+metric('Vlastní zdroje',money(own))+metric('CF po hypotéce',cf!==null?(cf>=0?'+':'')+money(cf):'—',cf===null?'':cf>=0?'good':'bad')+'</div></section></div><section class="pr1300-panel os1334-property-shortlist"><div class="pr1300-panel-head"><h2>Shortlist</h2><span>všech '+m.rows.length+' kandidátů</span></div>'+candidateRows(m.rows)+'</section>':'<section class="pr1320-now pr1328-property-empty"><div><div class="pr1300-kicker">Shortlist</div><h2>Zatím žádný kandidát</h2><p>Přidej investiční byt do Property Booku. Jakmile jsou data uložená, OS ukáže pořadí a Deal Score.</p></div><div class="pr1320-now-actions"><button class="pr1300-btn primary" type="button" data-property1300-task>＋ Úkol k realitě</button><button class="pr1300-btn" type="button" data-property1300-money>Peníze</button></div></section>';
 host.innerHTML='<div class="pr1300-shell" data-property-page1300 data-decision-surface1334>' +
  '<div class="pr1300-head"><div><div class="pr1300-kicker">Reality</div><h1>Reality.</h1><p>Nejdřív nejlepší kandidát a důvod. Pod tím čísla a celý shortlist.</p></div><span class="pr1300-status '+(best?decisionTone(best.decision.code):'')+'">'+m.rows.length+' kandidátů</span></div>' +
  populated +
  '<section class="pr1300-panel os741-property-lifecycle"><div class="pr1300-panel-head"><div><h2>Lifecycle shortlistu</h2><span>nový → prověřuji → jednám → uzavřeno</span></div></div><div class="os741-lifecycle"><span><small>Nové</small><b>'+lifecycle.new+'</b></span><span><small>Prověřuji</small><b>'+lifecycle.review+'</b></span><span><small>Jednám</small><b>'+lifecycle.negotiating+'</b></span><span><small>Uzavřené / pryč</small><b>'+lifecycle.closed+'</b></span><span><small>Koupené</small><b>'+lifecycle.bought+'</b></span></div><div class="os1500-summary-grid"><div class="os1500-summary '+(deadLinks.length?'warn':'good')+'"><span>Neaktivní odkazy k úklidu</span><b>'+deadLinks.length+'</b></div><div class="os1500-summary"><span>Compare lock</span><b>'+compareLock.length+'/4</b></div><div class="os1500-summary"><span>True net yield #1</span><b>'+(best?pct(best.netYield):'—')+'</b></div><div class="os1500-summary"><span>Downside yield #1</span><b>'+(best?pct(best.downsideYield):'—')+'</b></div></div>'+(deadLinks.length?'<div class="os741-deadline-list">'+deadLinks.slice(0,5).map(x=>'<div><b>'+esc(x.name)+'</b><small>'+esc(x.status)+' · skrýt z aktivního shortlistu</small></div>').join('')+'</div>':'')+'<div class="pr1300-actions"><button class="pr1300-btn" type="button" data-property741-lock>Uzamknout TOP 2 pro srovnání</button>'+(compareLock.length?'<button class="pr1300-btn" type="button" data-property741-unlock>Zrušit compare lock</button>':'')+'</div></section>' +
 '</div>';
 if(!host.dataset.property1300Bound){host.dataset.property1300Bound='1';ownEvent1100(OWNER,window,'kamil:focus610',e=>{const f=String(e.detail?.focus||'');if(!f.startsWith('property:'))return;const i=Number(f.slice(9));if(Number.isFinite(i))openPropertyDetail620(i)});ownEvent1100(OWNER,host,'click',e=>{if(e.target.closest('[data-property1300-money]')){window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:'money'}));return}if(e.target.closest('[data-property1300-task]')){window.dispatchEvent(new CustomEvent('kamil:capture',{detail:'property-task'}));return}if(e.target.closest('[data-property741-lock]')){const cur=buildPropertyHub620(store.get()),ids=cur.rows.slice(0,2).map(x=>x.raw?.id??String(x.index));store.mutate('Uzamčeno srovnání realit',s=>{s.ui=s.ui||{};s.ui.propertyCompareIds=ids},{undo:true,cloud:true,audit:true});render();return}if(e.target.closest('[data-property741-unlock]')){store.mutate('Zrušeno srovnání realit',s=>{s.ui=s.ui||{};s.ui.propertyCompareIds=[]},{undo:true,cloud:true,audit:true});render();return}const row=e.target.closest('[data-property-candidate]');if(row)openPropertyDetail620(Number(row.dataset.propertyCandidate))})}
 window.__KAMIL_PROPERTY_PAGE1300__={healthy:true,candidates:m.rows.length,renderedCandidates:m.rows.length,lifecycle,deadLinks:deadLinks.length,compareLock:compareLock.length,best:best?{name:best.name,score:best.score,decision:best.decision.code}:null,decisionSurface:1334,directCandidates:true,at:Date.now()};
 return true;
}
export function renderPropertyPage1300(){return render()}
