import {ownEvent1100,ownObserver1100} from './runtimeOwnership1100.js';
const OWNER='core.qa143';
const viewType={today:'task',inbox:'task',money:'money-task',tickets:'ticket-task',family:'family-task',home:'home-task',more:'document-source'};
const titles={today:'DNES',inbox:'INBOX',money:'PENÍZE',tickets:'VSTUPENKY',family:'RODINA',home:'DOMOV',more:'DOKUMENTY'};
const labels={today:'Osobní úkol',inbox:'Úkol',money:'Finanční úkol',tickets:'Úkol k ticketům',family:'Rodinný úkol',home:'Domácí úkol',more:'Dokument / zdroj'};
function currentView(){const on=document.querySelector('#mainNav [data-view].on')||document.querySelector('#bottomNav [data-view].on');return on?.dataset.view||'today'}
function sync(){const view=currentView(),page=document.querySelector('#pageTitle'),add=document.querySelector('#quickAddBtn');if(page)page.textContent=titles[view]||'KAMIL OS';document.querySelectorAll('[data-view]').forEach(x=>{const active=x.dataset.view===view;x.classList.toggle('on',active);if(active)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current')});if(add){const b=add.querySelector('b'),label=labels[view]||'Přidat';if(b)b.textContent=label;add.title=`Rychle přidat ${label.toLowerCase()} · Ctrl N`}}
function fireCapture(e){const view=currentView(),type=viewType[view]||'task';e?.preventDefault?.();e?.stopImmediatePropagation?.();window.dispatchEvent(new CustomEvent('kamil:capture',{detail:type}))}
function install(){if(window.__KAMIL_QA143_INSTALLED__)return;window.__KAMIL_QA143_INSTALLED__=true;ownEvent1100(OWNER,document,'click',e=>{const btn=e.target.closest?.('#quickAddBtn');if(btn)fireCapture(e)},{capture:true});ownEvent1100(OWNER,document,'keydown',e=>{if((e.ctrlKey||e.metaKey)&&String(e.key||'').toLowerCase()==='n')fireCapture(e)},{capture:true});ownEvent1100(OWNER,window,'kamil:view-change',()=>queueMicrotask(sync));ownEvent1100(OWNER,window,'kamil:release-stamp',()=>queueMicrotask(sync));const nav=document.querySelector('#mainNav')||document.body;ownObserver1100(OWNER,nav,{subtree:true,attributes:true,attributeFilter:['class']},sync);sync();window.__KAMIL_QA143__={at:Date.now(),quickAddRouting:true,ctrlNRouting:true,chromeGuard:true,scopedObserver:true}}
if(document.readyState==='loading')ownEvent1100(OWNER,document,'DOMContentLoaded',install,{once:true});else install();
