import {qs,h,dateTime,modal,toast} from './utils.js';
import {store} from './state.js';
import {listRecoverySnapshots32,maybeCreateRecoverySnapshot32,restoreRecoverySnapshot32,validateRecoverySnapshot32,recoveryShieldStatus32} from './recoveryShield32.js';
import {ownEvent1100,schedule1100} from './runtimeOwnership1100.js';

const OWNER='recovery.shield32';
let seq=0,scheduled=false,bound=false,lastRows=[];
const summary=x=>{const v=validateRecoverySnapshot32(x);if(!v.ok)return 'neplatná';const c=v.counts;return `${c.tickets} vstupenek · ${c.tradeHistory} trade záznamů · ${c.tasks} úkolů`};
const shell=()=>`<div class="card"><div class="card-head"><div><div class="eyebrow">RECOVERY SHIELD 32.4</div><h2>Cloudové recovery snapshoty</h2><p class="muted">Denní append-only kopie hlavního cloud state + povinná záloha těsně před obnovou.</p></div><span class="status warn">NAČÍTÁM</span></div></div>`;

async function confirmRestore(row){
 const valid=validateRecoverySnapshot32(row);if(!valid.ok){toast('Tento snapshot nelze obnovit.');return}
 const c=valid.counts,first=await modal('Náhled obnovy',`<div class="decision-note">Snapshot ${h(dateTime(row.created_at))}</div><div class="row"><span>Vstupenky</span><b>${c.tickets}</b></div><div class="row"><span>Historie vstupenek</span><b>${c.ticketHistory}</b></div><div class="row"><span>Trade historie</span><b>${c.tradeHistory}</b></div><div class="row"><span>Úkoly</span><b>${c.tasks}</b></div><div class="decision-note warn">Obnova přepíše aktuální cloud state tímto snapshotem. Kamil OS nejdřív automaticky vytvoří PRE_RESTORE snapshot současného stavu.</div>`,[{label:'Zrušit',value:null},{label:'Pokračovat',value:'next',primary:true}]);if(first!=='next')return;
 const second=await modal('Opravdu obnovit?',`<p>Ještě jedno potvrzení: obnovit stav z <b>${h(dateTime(row.created_at))}</b>?</p><div class="decision-note">Současný stav bude předem uložen jako samostatná recovery kopie.</div>`,[{label:'Ne',value:null},{label:'Ano, obnovit',value:'restore',danger:true,primary:true}]);if(second!=='restore')return;
 const result=await restoreRecoverySnapshot32(row);toast(result.ok?'Recovery snapshot obnoven.':'Obnova selhala: '+(result.error||result.reason||'chyba'));schedule1100(OWNER,'post-restore',render,0,{pauseWhenHidden:true});
}
async function render(){
 const n=++seq,view=qs('#moreView');if(!view)return;const isSystem=[...view.querySelectorAll('h1')].some(x=>String(x.textContent||'').includes('Kamil OS'));let host=qs('#recoveryShield32Host',view);if(!isSystem){host?.remove();return}if(!host){host=document.createElement('div');host.id='recoveryShield32Host';const anchor=qs('#dataEngine31Host',view)||qs('#systemHealth31Host',view)||view.querySelector('.view-head');anchor?.insertAdjacentElement('afterend',host)}host.innerHTML=shell();
 const list=await listRecoverySnapshots32(8);if(n!==seq||!host.isConnected)return;const status=recoveryShieldStatus32(),rows=list.rows||[];lastRows=rows;
 host.innerHTML=`<div class="card"><div class="card-head"><div><div class="eyebrow">RECOVERY SHIELD 32.4</div><h2>Cloudové recovery snapshoty</h2><p class="muted">Automaticky maximálně 1× denně z autoritativního cloud state. Obnova je vždy dvoukrokově potvrzená.</p></div><div class="row-actions"><span class="status ${list.ok?'good':'warn'}">${list.ok?rows.length+' snapshotů':h(list.reason||'NEDOSTUPNÉ')}</span><button class="btn" data-recovery-now>Snapshot teď</button></div></div>${rows.length?rows.map(r=>`<div class="row"><div><b>${h(dateTime(r.created_at))}</b><div class="muted">${h(r.payload?.reason||'DAILY')} · ${h(summary(r))}</div></div><button class="btn" data-recovery-restore="${r.id}">Náhled obnovy</button></div>`).join(''):'<div class="empty">Zatím není žádný recovery snapshot. Po připojení cloudu ho 32.4 vytvoří automaticky.</div>'}<div class="decision-note">Snapshoty neobsahují device-local undo. Klientská 32.4 logika žádné snapshoty nemaže. ${status.lastError?`Poslední chyba: ${h(status.lastError)}.`:''}</div></div>`;
}
async function onClick(e){const host=e.target.closest?.('#recoveryShield32Host');if(!host)return;const now=e.target.closest?.('[data-recovery-now]');if(now){now.disabled=true;const r=await maybeCreateRecoverySnapshot32({force:true,reason:'MANUAL'});toast(r.ok?'Recovery snapshot vytvořen.':'Snapshot se nepodařil: '+(r.error||r.reason||'chyba'));render();return}const b=e.target.closest?.('[data-recovery-restore]');if(!b)return;const row=lastRows.find(r=>String(r.id)===String(b.dataset.recoveryRestore));if(row)confirmRestore(row)}
function start(){if(bound)return;bound=true;ownEvent1100(OWNER,window,'kamil:navigate',()=>queueMicrotask(render));ownEvent1100(OWNER,document,'click',onClick);store.subscribe(()=>{if(qs('#moreView #recoveryShield32Host'))queueMicrotask(render)});schedule1100(OWNER,'initial-render',render,500,{pauseWhenHidden:true});if(!scheduled){scheduled=true;schedule1100(OWNER,'daily-bootstrap',()=>maybeCreateRecoverySnapshot32().then(()=>render()),5000,{pauseWhenHidden:true})}}
if(document.readyState==='loading')ownEvent1100(OWNER,document,'DOMContentLoaded',start,{once:true});else start();
