import {decisionJournal161,captureDecisionJournal161} from './decisionJournal161.js';
import {marketQuoteForSymbol32} from './marketQuoteIngest32.js';
import {loadTicketCloud660} from './ticketCloud660.js';
import {h} from './utils.js';
const N=v=>Number(v||0),U=v=>String(v||'').toUpperCase();
function xtbDirection(action){action=U(action);if(['BUY','ADD'].includes(action))return 1;if(['SELL','TRIM'].includes(action))return -1;return 0}
async function currentTicketPrices(){const m=new Map();try{const c=await loadTicketCloud660();if(c?.ok)for(const r of c.inventory||[]){const s=c.latest?.get(r.id),p=N(s?.market_price_czk);if(p)m.set(String(r.id),p)}}catch{}return m}
export async function recommendationPerformance162(){await captureDecisionJournal161();const rows=decisionJournal161(),tickets=await currentTicketPrices(),now=Date.now(),evaluated=[];for(const x of rows){const age=(now-Date.parse(x.createdAt||0))/36e5;if(age<24||!N(x.baselinePrice))continue;let current=null;if(x.kind==='XTB'){const q=marketQuoteForSymbol32(x.id);if(q?.fresh&&N(q.price))current=N(q.price)}else current=tickets.get(String(x.id))||null;if(!current)continue;const move=(current-N(x.baselinePrice))/N(x.baselinePrice)*100,dir=x.kind==='XTB'?xtbDirection(x.action):0;evaluated.push({...x,currentPrice:current,movePct:move,directionalCorrect:dir?move*dir>0:null,evaluationKind:x.kind==='XTB'&&dir?'XTB_DIRECTION':'TICKET_MARKET_FOLLOWUP'})}const directional=evaluated.filter(x=>x.evaluationKind==='XTB_DIRECTION'),ticketFollowups=evaluated.filter(x=>x.evaluationKind==='TICKET_MARKET_FOLLOWUP'&&x.kind==='TICKET'),correct=directional.filter(x=>x.directionalCorrect).length;return{journal:rows.length,evaluated:evaluated.length,directional:directional.length,ticketFollowups:ticketFollowups.length,correct,hitRate:directional.length?correct/directional.length*100:null,rows:evaluated}}
export async function enhanceRecommendationPerformance162(){const host=document.querySelector('#moneyView');if(!host)return;host.querySelector('[data-recperf162]')?.remove();const x=await recommendationPerformance162(),sec=document.createElement('section');sec.dataset.recperf162='1';sec.className='card money-section rp162';sec.dataset.moneyGroup='wealth';sec.innerHTML=`<div class="eyebrow">OS 161–162 · DECISION JOURNAL</div><h2>Jak se doporučení chovají po čase</h2><div class="rp162-kpis"><article><small>Zapsaná doporučení</small><b>${x.journal}</b></article><article><small>Vyhodnotitelná ≥24 h</small><b>${x.evaluated}</b></article><article><small>XTB směrově vyhodnocená</small><b>${x.directional}</b></article><article><small>XTB směrová úspěšnost</small><b>${x.hitRate===null?'—':`${x.hitRate.toFixed(1)} %`}</b></article><article><small>Ticket market follow-up</small><b>${x.ticketFollowups}</b></article></div><p class="muted">XTB hit-rate měří pouze následný směr čerstvé ceny po BUY/ADD/SELL/TRIM doporučení. Ticket RAISE/LOWER/LIST je repricing nebo listing akce, ne predikce směru trhu, proto se do hit-rate nezapočítává. Ani jedna metrika není realizovaný výnos ani backtest.</p>${x.rows.slice(-6).reverse().map(r=>`<div class="rp162-row"><span>${h(r.kind)} · ${h(r.id)} · ${h(r.action)}</span><b>${r.movePct>=0?'+':''}${r.movePct.toFixed(1)} %${r.kind==='TICKET'?' · follow-up':''}</b></div>`).join('')}`;host.appendChild(sec);window.__KAMIL_REC_PERF162__={at:Date.now(),...x};return x}
export const recommendationPerformance162Info={minimumAgeHours:24,notRealizedReturn:true,freshCurrentPriceRequired:true,xtbDirectionalOnly:true,ticketRepricingNotPrediction:true};
