import {store} from './state.js';
import {fetchRemoteChanges31} from './smartSync31.js';
import {syncProjection31} from './syncJournal31.js';
import {remoteInbox31,remoteInboxKind31} from './remoteInbox31.js';
import {remoteInboxMeta31,markRemoteInboxSeen31} from './indexedDb31.js';
import {qs,h,date} from './utils.js';
const id='remoteInbox31Host';let loaded=false,loading=false,remoteRows=[],fetchState=null,seq=0;
const label=x=>String(x?.payload?.title||x?.payload?.name||x?.payload?.label||x?.payload?.description||x?.entityId||'Položka').trim().slice(0,90);
const kindClass=k=>k==='CONFLICT'?'bad':k==='REMOTE_DELETE'?'warn':k==='REMOTE_NEW'?'good':'good';
const shell=()=>`<div class="card"><div class="card-head"><div><div class="eyebrow">CORE V2 / REMOTE INBOX 31.5</div><h2>Remote Change Inbox</h2><p class="muted">Kontroluji změny z ostatních zařízení. Nic se automaticky neslučuje.</p></div><span class="status warn">READ ONLY</span></div><div class="decision-note">Načítám vzdálený shadow journal a porovnávám ho s tímto zařízením.</div></div>`;
async function model(){const meta=await remoteInboxMeta31(),projection=syncProjection31(store.get()),inbox=remoteInbox31(remoteRows,projection.records,meta.seenIds);return {...inbox,lastCheckedAt:meta.lastCheckedAt}}
async function load(){if(loading)return;loading=true;const result=await fetchRemoteChanges31({limit:150});fetchState=result;if(result.ok)remoteRows=result.rows||[];loaded=true;loading=false;render()}
async function render(){
 const n=++seq,view=qs('#moreView');if(!view)return;const isSystem=[...view.querySelectorAll('h1')].some(x=>String(x.textContent||'').includes('Kamil OS'));let host=qs(`#${id}`,view);if(!isSystem){host?.remove();return}
 if(!host){host=document.createElement('div');host.id=id;const smart=qs('#smartSync31Host',view),data=qs('#dataEngine31Host',view),health=qs('#systemHealth31Host',view),target=smart||data||health||view.querySelector('.view-head');if(target)target.insertAdjacentElement('afterend',host);else view.prepend(host)}
 if(!loaded){host.innerHTML=shell();load();return}const s=await model();if(n!==seq||!host.isConnected)return;
 if(!fetchState?.ok){const reason=fetchState?.reason==='LOCAL_ONLY'||fetchState?.reason==='NO_SESSION'?'Cloud není připojený. Remote Inbox zůstává prázdný a Supabase SDK se v čistě lokálním režimu nenačítá.':fetchState?.reason==='OFFLINE'?'Jsi offline. Remote Inbox se načte po připojení.':`Vzdálené změny se nepodařilo načíst${fetchState?.error?`: ${h(fetchState.error)}`:'.'}`;host.innerHTML=`<div class="card"><div class="card-head"><div><div class="eyebrow">CORE V2 / REMOTE INBOX 31.5</div><h2>Remote Change Inbox</h2><p class="muted">Read-only pohled na změny z ostatních zařízení.</p></div><span class="status warn">READ ONLY</span></div><div class="decision-note">${reason}</div><button class="btn" data-remote-refresh>Zkusit znovu</button></div>`;host.querySelector('[data-remote-refresh]')?.addEventListener('click',()=>{loaded=false;render()});return}
 const rows=s.actionable.slice(0,10).map(x=>`<div class="row"><span><b>${h(label(x))}</b><small class="muted">${h(x.domain)} · ${h(x.entityId)}${x.changedFields?.length?` · pole: ${h(x.changedFields.join(', '))}`:''}</small></span><span><span class="status ${kindClass(x.kind)}">${h(remoteInboxKind31[x.kind]||x.kind)}</span><small class="muted">${x.seen?'přečteno · ':''}${h(date(x.createdAt))}</small></span></div>`).join('');
 host.innerHTML=`<div class="card"><div class="card-head"><div><div class="eyebrow">CORE V2 / REMOTE INBOX 31.5</div><h2>Remote Change Inbox</h2><p class="muted">Změny z jiných zařízení jsou jen ke kontrole. 31.5 je nikdy automaticky neaplikuje.</p></div><span class="status ${s.unseenCount?'warn':'good'}">READ ONLY</span></div><div class="metric-strip"><div class="metric"><span>Nepřečtené</span><b>${Number(s.unseenCount).toLocaleString('cs-CZ')}</b></div><div class="metric"><span>Konflikty</span><b>${Number(s.conflicts).toLocaleString('cs-CZ')}</b></div><div class="metric"><span>Nové / smazané</span><b>${Number(s.remoteNew+s.remoteDeletes).toLocaleString('cs-CZ')}</b></div></div>${rows||'<div class="empty">Žádná vzdálená změna teď nevyžaduje pozornost.</div>'}<div class="decision-note">Lokální kamil_os_state zůstává autoritativní. „Přečteno“ se ukládá pouze do IndexedDB tohoto browseru; cloudový journal ani hlavní state se tím nemění.${fetchState?.fetchedAt?` Kontrola ${h(date(fetchState.fetchedAt))}.`:''}</div><div class="actions"><button class="btn" data-remote-refresh>Obnovit inbox</button>${s.unseenCount?'<button class="btn" data-remote-seen>Označit zobrazené jako přečtené</button>':''}</div></div>`;
 host.querySelector('[data-remote-refresh]')?.addEventListener('click',()=>{loaded=false;render()});host.querySelector('[data-remote-seen]')?.addEventListener('click',async e=>{e.currentTarget.disabled=true;await markRemoteInboxSeen31(s.unseen.map(x=>x.id),new Date().toISOString());render()});
}
function start(){const view=qs('#moreView');if(!view)return;new MutationObserver(()=>queueMicrotask(render)).observe(view,{childList:true,subtree:false});window.addEventListener('kamil:navigate',()=>queueMicrotask(render));window.addEventListener('online',()=>{loaded=false;queueMicrotask(render)});render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
