import {runtimeSnapshot1100,installRuntimeOwnership1100} from './runtimeOwnership1100.js';

const VERSION='1210.0.0';
const state=globalThis.__KAMIL_RUNTIME_LEAK1210__||(globalThis.__KAMIL_RUNTIME_LEAK1210__={version:VERSION,checks:[],last:null});
const pick=s=>({owners:s.totals.owners,listeners:s.totals.listeners,timers:s.totals.timers,observers:s.totals.observers,cleanups:s.totals.cleanups,scheduled:s.totals.scheduled,deferred:s.totals.deferred,jobs:s.totals.jobs});
export function beginLeakCheck1210(label='check'){installRuntimeOwnership1100();return{label,startedAt:Date.now(),runtime:pick(runtimeSnapshot1100()),dom:typeof document!=='undefined'?document.querySelectorAll('*').length:0}}
export function finishLeakCheck1210(baseline,{listenerTolerance=1,timerTolerance=1,observerTolerance=1,ownerTolerance=1,domTolerance=80}={}){const current=pick(runtimeSnapshot1100()),dom=typeof document!=='undefined'?document.querySelectorAll('*').length:0,delta={listeners:current.listeners-baseline.runtime.listeners,timers:current.timers-baseline.runtime.timers,observers:current.observers-baseline.runtime.observers,owners:current.owners-baseline.runtime.owners,dom:dom-baseline.dom},violations=[];if(delta.listeners>listenerTolerance)violations.push(`listeners +${delta.listeners}`);if(delta.timers>timerTolerance)violations.push(`timers +${delta.timers}`);if(delta.observers>observerTolerance)violations.push(`observers +${delta.observers}`);if(delta.owners>ownerTolerance)violations.push(`owners +${delta.owners}`);if(delta.dom>domTolerance)violations.push(`DOM +${delta.dom}`);const out={version:VERSION,label:baseline.label,startedAt:baseline.startedAt,completedAt:Date.now(),baseline:baseline.runtime,current,delta,dom:{before:baseline.dom,after:dom},ok:violations.length===0,violations};state.last=out;state.checks.push(out);if(state.checks.length>50)state.checks.shift();return out}
export function runtimeLeak1210(){return{version:VERSION,last:state.last,checks:state.checks.slice(-20)}}
export function installRuntimeLeak1210(){installRuntimeOwnership1100();globalThis.__KAMIL_RUNTIME_LEAK1210_API__={begin:beginLeakCheck1210,finish:finishLeakCheck1210,snapshot:runtimeLeak1210};return runtimeLeak1210()}
