export const RUNTIME_MANIFEST=Object.freeze([
 {id:'audit',path:'./audit525.js',fn:'installAudit525',phase:'critical',priority:1,provides:['audit']},
 {id:'personal-shell',path:'./personalShell640.js',fn:'bindPersonalShell640',phase:'critical',priority:1,provides:['personal-more']},
 {id:'personal-hardening',path:'./personalHardening650.js',fn:'bindPersonalHardening650',phase:'critical',priority:1,provides:['personal-guard']},
 {id:'ux-foundation',path:'./uxFoundation238.js',fn:'installUxFoundation238',phase:'critical',priority:2,provides:['quick-add','mobile-nav']},
 {id:'production-chrome',path:'./productionChrome228.js',fn:'installProductionChrome228',phase:'critical',priority:2,provides:['chrome']},
 {id:'release-health',path:'./releaseHealth362.js',fn:'installReleaseHealth362',phase:'critical',priority:2,provides:['release-health']},

 {id:'navigation-os',path:'./navigationOS342.js',fn:'installNavigation342',phase:'deferred',priority:3},
 {id:'workspace',path:'./appWorkspace211.js',fn:'installAppWorkspaces211',phase:'deferred',priority:3},
 {id:'compact-nav',path:'./compactNavigation212.js',fn:'installCompactNavigation212',phase:'deferred',priority:3},
 {id:'navigation-302',path:'./navigation302.js',fn:'installNavigation302',phase:'deferred',priority:3},
 {id:'today-wake',path:'./todayWake226.js',fn:'installTodayWake226',phase:'deferred',priority:4},
 {id:'finance-command',path:'./financeCommand258.js',fn:'installFinanceCommand258',phase:'deferred',priority:4},
 {id:'ticket-command',path:'./ticketCommand268.js',fn:'installTicketCommand268',phase:'deferred',priority:4},
 {id:'core-312',path:'./kamilCore312.js',fn:'installKamilCore312',phase:'deferred',priority:4},
 {id:'intelligence-318',path:'./intelligence318.js',fn:'installIntelligence318',phase:'deferred',priority:4},
 {id:'domain-os',path:'./domainOS328.js',fn:'installDomainOS328',phase:'deferred',priority:5},
 {id:'design-304',path:'./design304.js',fn:'installDesign304',phase:'deferred',priority:5},
 {id:'unified-307',path:'./unified307.js',fn:'installUnified307',phase:'deferred',priority:5},
 {id:'hardening-329',path:'./hardening329.js',fn:'installHardening329',phase:'deferred',priority:5},
 {id:'ticket-on-demand',path:'./ticketOnDemand346.js',fn:'installTicketOnDemand346',phase:'deferred',priority:6},
 {id:'unified-command',path:'./unifiedCommand333.js',fn:'installUnifiedCommand333',phase:'deferred',priority:6},
 {id:'resilience-333',path:'./os333Resilience.js',fn:'installOS333Resilience',phase:'deferred',priority:6},
 {id:'focus-queue',path:'./focusQueue335.js',fn:'installFocusQueue335',phase:'deferred',priority:6},
 {id:'manager-os',path:'./managerOS341.js',fn:'installManagerOS341',phase:'deferred',priority:6},
 {id:'execution-state',path:'./executionState364.js',fn:'installExecutionState364',phase:'deferred',priority:6},
 {id:'urgency-draft',path:'./urgencyDraft367.js',fn:'installUrgencyDraft367',phase:'deferred',priority:6},
 {id:'command-center',path:'./commandCenter467.js',fn:'installCommandCenter467',phase:'deferred',priority:6},
 {id:'cashflow',path:'./cashflow468.js',fn:'installCashflow468',phase:'deferred',priority:6},

 {id:'xtb-decision',path:'./xtbDecision368.js',fn:'installXtbDecision368',phase:'idle',priority:8},
 {id:'ticket-decision',path:'./ticketDecision369.js',fn:'installTicketDecision369',phase:'idle',priority:8},
 {id:'opportunity-score',path:'./opportunityScore370.js',fn:'installOpportunityScore370',phase:'idle',priority:8},
 {id:'xtb-targets',path:'./xtbTargets371.js',fn:'installXtbTargets371',phase:'idle',priority:8},
 {id:'ticket-targets',path:'./ticketTargets372.js',fn:'installTicketTargets372',phase:'idle',priority:8},
 {id:'position-sizing',path:'./positionSizing373.js',fn:'installPositionSizing373',phase:'idle',priority:8},
 {id:'capital-plan',path:'./capitalPlan469.js',fn:'installCapitalPlan469',phase:'idle',priority:9},
 {id:'free-cash',path:'./freeCashForecast470.js',fn:'installFreeCashForecast470',phase:'idle',priority:9},
 {id:'property-decision',path:'./propertyDecision472.js',fn:'installPropertyDecision472',phase:'idle',priority:9},
 {id:'investment-battle',path:'./investmentBattle480.js',fn:'installInvestmentBattle480',phase:'idle',priority:9},
 {id:'manager-deadlines',path:'./managerDeadlines481.js',fn:'installManagerDeadlines481',phase:'idle',priority:9},
 {id:'morning-director',path:'./morningDirector483.js',fn:'installMorningDirector483',phase:'idle',priority:9},
 {id:'personal-upgrade',path:'./personalUpgrade600.js',fn:'installPersonalUpgrade600',phase:'idle',priority:9},
 {id:'ticket-risk-summary',path:'./ticketRiskSummary610.js',fn:'installTicketRiskSummary610',phase:'idle',priority:9},
 {id:'focus-radar',path:'./focusRadar334.js',fn:'installFocusRadar334',phase:'idle',priority:10},
 {id:'action-execution',path:'./actionExecution336.js',fn:'installActionExecution336',phase:'idle',priority:10},
 {id:'today-cockpit',path:'./todayCockpit363.js',fn:'installTodayCockpit363',phase:'idle',priority:10},
 {id:'performance',path:'./performance330.js',fn:'installPerformance330',phase:'idle',priority:10},
 {id:'ticket-qa',path:'./ticketQa332.js',fn:'installTicketQa332',phase:'idle',priority:10},
 {id:'workspaces',path:'./workspaces305.js',fn:'installWorkspaces305',phase:'idle',priority:10}
]);

export const runtimePhase=phase=>RUNTIME_MANIFEST.filter(x=>x.phase===phase).sort((a,b)=>a.priority-b.priority);
export const runtimePriorities=phase=>[...new Set(runtimePhase(phase).map(x=>x.priority))];
