import {smartSyncStatus31,runSmartSync31,uploadPendingSmartSync31} from './smartSync31.js';
import {qs,h,date} from './utils.js';
import {ownEvent1100,ownObserver1100} from './runtimeOwnership1100.js';
const OWNER='sync.smart31';
const id='smartSync31Host';let seq=0,bound=false;
const opLabel=x=>x.op==='DELETE'?'SMAZÁNÍ':'ZMĚNA';
const shell=()=>`<div class="card"><div class="card-head"><div><div class="eyebrow">CORE V2 / SMART SYNC 31.4</div><h2>Item-level shadow sync</h2><p class="muted">Vedle bezpečného celého JSON snapshotu vzniká audit změn po jednotlivých položkách. 31.4 vzdálené operace automaticky nepoužívá.</p></div><span class="status warn">SHADOW ONLY</span></div><div class="decision-note">Kontroluji lokální outbox. Snapshot \`kamil_os_state\` zůstává autoritativní.</div></div>`;
async function render(){
 const n=++seq,view=qs('#moreView');if(!view)return;const isSystem=[...view.querySelectorAll('h1')].some(x=>String(x.textContent||'').includes('Kamil OS'));let host=qs(`#${id}`,view);if(!isSystem){host?.remove();return}
 if(!host){host=document.createElement('div');host.id=id;const data=qs('#dataEngine31Host',view),health=qs('#systemHealth31Host',view),target=data||health||view.querySelector('.view-head');if(target)target.insertAdjacentElement('afterend',host);else view.prepend(host)}host.innerHTML=shell();
 const s=await smartSyncStatus31();if(n!==seq||!host.isConnected)return;
 const recent=(s.ops||[]).slice(0,5).map(x=>`<div class="row"><span>${h(x.domain)} · ${h(x.entityId)}</span><span><b>${h(opLabel(x))}</b> · ${h(x.status||'PENDING')}</span></div>`).join('');
 host.innerHTML=`<div class="card"><div class="card-head"><div><div class="eyebrow">CORE V2 / SMART SYNC 31.4</div><h2>Item-level shadow sync</h2><p class="muted">Vedle bezpečného celého JSON snapshotu vzniká audit změn po jednotlivých položkách. 31.4 vzdálené operace automaticky nepoužívá.</p></div><span class="status ${s.supported&&s.baseline?'good':'warn'}">SHADOW ONLY</span></div><div class="metric-strip"><div class="metric"><span>Čeká lokálně</span><b>${Number(s.pending||0).toLocaleString('cs-CZ')}</b></div><div class="metric"><span>Odesláno</span><b>${Number(s.uploaded||0).toLocaleString('cs-CZ')}</b></div><div class="metric"><span>Cloud operace</span><b>${Number(s.lastCloudCount||0).toLocaleString('cs-CZ')}</b></div></div>${recent||'<div class="empty">Zatím žádná item-level změna.</div>'}<div class="decision-note">Snapshot \`kamil_os_state\` zůstává autoritativní. Vault, auth tokeny, Emergency File, raw OCR a další citlivé oblasti nejsou součástí Smart Sync allowlistu.${s.lastUploadAt?` Poslední upload ${h(date(s.lastUploadAt))}.`:''}${s.lastError?` Chyba: ${h(s.lastError)}`:''}</div><div class="actions"><button class="btn" data-smart-sync-run>Zkontrolovat změny</button><button class="btn" data-smart-sync-upload>Odeslat čekající</button></div></div>`;
}
async function onClick(e){const host=e.target.closest?.(`#${id}`);if(!host)return;const run=e.target.closest?.('[data-smart-sync-run]'),upload=e.target.closest?.('[data-smart-sync-upload]');if(!run&&!upload)return;const button=run||upload;button.disabled=true;if(run)await runSmartSync31({upload:true});else await uploadPendingSmartSync31();render()}
function start(){const view=qs('#moreView');if(!view||bound)return;bound=true;ownObserver1100(OWNER,view,{childList:true,subtree:false},()=>queueMicrotask(render));ownEvent1100(OWNER,view,'click',onClick);ownEvent1100(OWNER,window,'kamil:navigate',()=>queueMicrotask(render));ownEvent1100(OWNER,window,'kamil:smart-sync',()=>queueMicrotask(render));render()}
if(document.readyState==='loading')ownEvent1100(OWNER,document,'DOMContentLoaded',start,{once:true});else start();
