import {store} from './state.js';
import {previewImport,smartImportSafetyNote} from './smartImport29.js';
import {buildSmartImportPlan,importPlanSafety} from './smartImportPlan29.js';
import {applySmartImport,xtbImportSafety} from './smartImportApply29.js';
import {h,qs,modal,toast} from './utils.js';

let rawText='',fileName='',forcedSource='AUTO',preview=null,plan=null;
const labels={SPENDING:'Bank / transakce',REVOLUT:'Revolut',XTB:'XTB',TICKETS:'Vstupenky',ADMIN:'Administrativa'};
const money=(v,c='')=>`${Number(v||0).toLocaleString('cs-CZ',{maximumFractionDigits:2})}${c?` ${h(c)}`:''}`;
function candidateLabel(c){const d=c.data||{};if(c.kind==='SPENDING')return `${d.date} · ${d.description} · ${d.amount>0?'+':''}${money(d.amount,d.currency)}`;if(c.kind==='XTB')return `${d.ticker} · ${d.name} · ${money(d.value,d.currency)}`;if(c.kind==='TICKETS')return `${d.date} · ${d.name} · ${d.qty} ks${d.sector?` · ${d.sector}`:''}`;if(c.kind==='ADMIN')return `${d.title}${d.provider?` · ${d.provider}`:''}${d.amount!==null?` · ${money(d.amount,d.currency)}`:''}`;return c.key}
function historyRows(){const rows=store.get().importCenter?.history||[];return rows.slice(0,8).map(x=>`<div class="row"><span>${h(new Date(x.at).toLocaleString('cs-CZ'))} · ${h(labels[x.source]||x.source||'Import')}${x.fileName?` · ${h(x.fileName)}`:''}</span><b>${x.imported||0} změn${x.duplicates?` · ${x.duplicates} dup.`:''}</b></div>`).join('')||'<div class="empty">Zatím bez potvrzeného importu.</div>'}
function previewHtml(){if(!preview)return '<div class="empty">Nahraj CSV/TSV/JSON nebo vlož tabulku a dej Náhled. Nic se do dat nezapíše před potvrzením.</div>';const rows=preview.accepted.slice(0,10).map(c=>`<div class="row"><span>ř. ${c.row} · ${h(candidateLabel(c))}</span><b>${h(c.kind)}</b></div>`).join('')||'<div class="empty bad">Nebyl nalezen žádný bezpečně použitelný řádek.</div>';const warns=(preview.warnings||[]).map(x=>`<div class="decision-note warn">${h(x)}</div>`).join('');return `<div class="metric-strip"><div class="metric"><span>Rozpoznáno</span><b>${h(preview.label)}</b></div><div class="metric"><span>Nové</span><b class="good">${plan?.newCount||0}</b></div><div class="metric"><span>Aktualizace</span><b>${plan?.updateCount||0}</b></div><div class="metric"><span>Duplicity</span><b>${plan?.duplicateCount||0}</b></div><div class="metric"><span>Odmítnuté</span><b class="${preview.rejected.length?'warn':'good'}">${preview.rejected.length}</b></div></div>${warns}<div class="card"><h3>Náhled prvních řádků</h3>${rows}${preview.accepted.length>10?`<p class="muted">+ dalších ${preview.accepted.length-10} použitelných řádků.</p>`:''}</div>${plan?`<div class="decision-note"><b>Po potvrzení:</b> ${plan.newCount} nových položek${plan.updateCount?` · ${plan.updateCount} XTB aktualizací`:''}. ${plan.duplicateCount} shodných duplicit se přeskočí.</div>`:''}`}
export function resetSmartImport(){rawText='';fileName='';forcedSource='AUTO';preview=null;plan=null}
export function smartImportView(back=''){
 const cloud=store.get().meta?.cloudMode==='cloud';
 return `${back}<div class="view-head compact"><div><div class="eyebrow">SMART IMPORT CENTER / 29.4</div><h1>Nejdřív náhled, až potom zápis</h1><p>Importuj banku/Revolut, XTB pozice, vstupenky nebo osobní administrativu. Kamil OS nejdřív ukáže, co přesně rozpoznal, a shodné duplicity znovu nevloží.</p></div><div class="view-head-stat"><b class="good">2×</b><span>kontrola před zápisem</span></div></div>
 <div class="grid two"><div class="card"><h2>1. Vstupní data</h2><label>Typ dat<select id="smartImportSource"><option value="AUTO"${forcedSource==='AUTO'?' selected':''}>Automaticky rozpoznat</option><option value="SPENDING"${forcedSource==='SPENDING'?' selected':''}>Banka / transakce</option><option value="REVOLUT"${forcedSource==='REVOLUT'?' selected':''}>Revolut</option><option value="XTB"${forcedSource==='XTB'?' selected':''}>XTB pozice</option><option value="TICKETS"${forcedSource==='TICKETS'?' selected':''}>Vstupenky</option><option value="ADMIN"${forcedSource==='ADMIN'?' selected':''}>Osobní administrativa</option></select></label><label class="btn">Vybrat CSV / TSV / JSON<input id="smartImportFile" type="file" accept=".csv,.tsv,.txt,.json,text/csv,text/tab-separated-values,application/json" hidden></label>${fileName?`<p class="muted">Soubor: <b>${h(fileName)}</b></p>`:''}<label>Nebo vlož tabulku / CSV<textarea id="smartImportText" rows="8" placeholder="Datum;Popis;Částka;Měna&#10;20.08.2026;Lidl;-1250,50;CZK">${h(rawText)}</textarea></label><button class="btn primary" id="smartImportPreview">Vytvořit bezpečný náhled</button><p class="muted">PDF a fotky sem záměrně neposíláme naslepo. Pro ně bude samostatný Document Scanner s potvrzením vytěžených polí.</p></div><div class="card"><h2>2. Co se skutečně zapíše</h2>${previewHtml()}${plan?.total?'<button class="btn primary wide" id="smartImportApply">Potvrdit a zapsat změny</button>':''}</div></div>
 <div class="decision-note"><b>Bezpečnost:</b> ${h(smartImportSafetyNote)} ${h(importPlanSafety)} ${h(xtbImportSafety)}</div><div class="decision-note ${cloud?'warn':''}"><b>Soukromí:</b> Importovaná data jsou součást běžného stavu Kamil OS. ${cloud?'Cloud je připojený, takže se po potvrzení synchronizují do tvého Supabase účtu.':'Teď běžíš lokálně; pokud později připojíš cloud, budou součástí synchronizovaného stavu.'}</div><div class="card"><h2>Historie importů</h2>${historyRows()}</div>`;
}
function rebuild(){preview=previewImport(rawText,{fileName,source:forcedSource});plan=buildSmartImportPlan(store.get(),preview)}
export function bindSmartImport(rerender){
 qs('#smartImportSource')?.addEventListener('change',e=>{forcedSource=e.target.value;preview=null;plan=null});
 qs('#smartImportText')?.addEventListener('input',e=>{rawText=e.target.value;fileName='';preview=null;plan=null});
 qs('#smartImportFile')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;fileName=f.name;try{rawText=await f.text();rebuild();rerender()}catch{toast('Soubor se nepodařilo přečíst.')}});
 qs('#smartImportPreview')?.addEventListener('click',()=>{rawText=qs('#smartImportText')?.value||rawText;if(!rawText.trim())return toast('Nejdřív vlož nebo vyber data.');rebuild();rerender()});
 qs('#smartImportApply')?.addEventListener('click',async()=>{if(!plan?.total)return;const kinds=Object.entries(plan.byKind||{}).map(([k,v])=>`${labels[k]||k}: ${v}`).join(' · '),cloud=store.get().meta?.cloudMode==='cloud';const ok=await modal('Potvrdit import?',`<p>Provedu <b>${plan.total}</b> potvrzených změn: ${plan.newCount} nových${plan.updateCount?` a ${plan.updateCount} XTB aktualizací`:''}.</p><p>${h(kinds)}</p><p class="muted">Duplicity (${plan.duplicateCount}) a odmítnuté řádky (${plan.rejected.length}) zůstanou beze změny. Import neprovádí platby ani obchody.${cloud?' Data se následně synchronizují do připojeného Supabase účtu.':''}</p>`,[{label:'Zrušit',value:false},{label:'Ano, zapsat',value:true,primary:true}]);if(!ok)return;let summary;store.mutate(`Smart Import: ${plan.total} změn`,s=>{summary=applySmartImport(s,plan)});toast(`Import hotov: ${summary.imported} změn, ${summary.duplicates} duplicit přeskočeno.`);rawText='';fileName='';preview=null;plan=null;rerender()});
}