import {store} from './state.js';
const VERSION=484,DAY=86400000;
const N=v=>Number.isFinite(Number(v))?Number(v):0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`;
const isMoneyEvent=e=>{const d=e?.detail;return d==='money'||d?.view==='money'};
function ensureCss(){if(document.querySelector('link[data-spending484-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./spendingIntelligence484.css';l.dataset.spending484Css='1';document.head.appendChild(l)}
function dateValue(x){for(const v of [x?.date,x?.at,x?.bookedAt,x?.postedAt,x?.when]){const t=Date.parse(v||'');if(Number.isFinite(t))return t}return null}
function amountValue(x){for(const v of [x?.amountCzk,x?.amount,x?.valueCzk,x?.value]){const n=Number(v);if(Number.isFinite(n)&&n!==0)return n}return 0}
function isExpense(x,amount){const type=String(x?.type||x?.kind||x?.direction||'').toLowerCase();return amount<0||/(expense|out|debit|purchase|withdraw)/.test(type)}
function explicitCategory(x){for(const v of [x?.category,x?.categoryName,x?.group])if(String(v||'').trim())return String(v).trim();return null}
function explicitMerchant(x){for(const v of [x?.merchant,x?.payee,x?.counterparty,x?.merchantName])if(String(v||'').trim())return String(v).trim();return null}
function recurrence(x){if(x?.recurring===true||x?.isRecurring===true)return'RECURRING';if(x?.recurring===false||x?.isRecurring===false)return'VARIABLE';return'UNKNOWN'}
function normalized(s,now=Date.now()){const raw=Array.isArray(s?.personalSpending?.transactions)?s.personalSpending.transactions:[],rows=[];let invalid=0;for(const x of raw){const at=dateValue(x),signed=amountValue(x);if(at===null||!isExpense(x,signed)){invalid++;continue}rows.push({at,daysAgo:Math.floor((now-at)/DAY),amount:Math.abs(signed),category:explicitCategory(x),merchant:explicitMerchant(x),recurrence:recurrence(x)})}rows.sort((a,b)=>b.at-a.at);return{rawCount:raw.length,invalidCount:invalid,rows}}
function windowSum(rows,minDays,maxDays){const hit=rows.filter(x=>x.daysAgo>=minDays&&x.daysAgo<=maxDays);return{count:hit.length,spend:hit.reduce((a,x)=>a+x.amount,0),rows:hit}}
function rank(rows,key){const map=new Map();for(const x of rows){const label=x[key];if(!label)continue;const v=map.get(label)||{label,spend:0,count:0};v.spend+=x.amount;v.count++;map.set(label,v)}return[...map.values()].sort((a,b)=>b.spend-a.spend||b.count-a.count).slice(0,5)}
function median(values){if(!values.length)return 0;const a=[...values].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function anomalies(rows){if(rows.length<5)return[];const med=median(rows.map(x=>x.amount));if(!med)return[];const threshold=Math.max(med*3,med+2000);return rows.filter(x=>x.amount>=threshold).sort((a,b)=>b.amount-a.amount).slice(0,5).map(x=>({...x,threshold}))}
function freshness(rows,now){const newest=rows[0]?.at??null,ageDays=newest===null?null:Math.floor((now-newest)/DAY);return{newest,ageDays,fresh:ageDays!==null&&ageDays<=40}}
export function buildSpendingIntelligence484(s=store.get(),now=Date.now()){
 const norm=normalized(s,now),w7=windowSum(norm.rows,0,6),w30=windowSum(norm.rows,0,29),prev30=windowSum(norm.rows,30,59),w90=windowSum(norm.rows,0,89),fresh=freshness(norm.rows,now),validRatio=norm.rawCount?norm.rows.length/norm.rawCount:0,complete=norm.rows.length>0&&fresh.fresh&&validRatio>=.8;
 const changeAmount=w30.spend-prev30.spend,changePct=prev30.spend>0?changeAmount/prev30.spend:null,categories=rank(w90.rows,'category'),merchants=rank(w90.rows,'merchant'),unknownCategories=w90.rows.filter(x=>!x.category).length,recurrence={recurring:w90.rows.filter(x=>x.recurrence==='RECURRING').reduce((a,x)=>a+x.amount,0),variable:w90.rows.filter(x=>x.recurrence==='VARIABLE').reduce((a,x)=>a+x.amount,0),unknown:w90.rows.filter(x=>x.recurrence==='UNKNOWN').reduce((a,x)=>a+x.amount,0)},spikes=anomalies(w90.rows);
 let recommendation={code:'STABLE',action:'BEZ MIMOŘÁDNÉ AKCE',reason:'Výdaje nemají z dostupných dat výrazný statistický signál.'};if(!complete)recommendation={code:'INCOMPLETE',action:'DOPLNIT TRANSAKCE',reason:!norm.rows.length?'Nejsou dostupné použitelné výdajové transakce.':!fresh.fresh?`Nejnovější výdaj je ${fresh.ageDays} dní starý.`:`Použitelných je jen ${Math.round(validRatio*100)} % záznamů.`};else if(changePct!==null&&changePct>=.25&&changeAmount>=1000)recommendation={code:'SPEND_UP',action:'ZKONTROLOVAT RŮST VÝDAJŮ',reason:`Posledních 30 dní je o ${money(changeAmount)} výš než předchozích 30 dní.`};else if(spikes.length)recommendation={code:'ANOMALY',action:'ZKONTROLOVAT VELKOU PLATBU',reason:`Největší statistická odchylka je ${money(spikes[0].amount)}.`};
 return{version:VERSION,healthy:true,complete,source:{rawCount:norm.rawCount,validCount:norm.rows.length,invalidCount:norm.invalidCount,validRatio:Math.round(validRatio*100),newestAt:fresh.newest?new Date(fresh.newest).toISOString():null,ageDays:fresh.ageDays,fresh:fresh.fresh},windows:{d7:w7.spend,d30:w30.spend,previous30:prev30.spend,d90:w90.spend},counts:{d7:w7.count,d30:w30.count,previous30:prev30.count,d90:w90.count},change30:{amount:changeAmount,pct:changePct},categories,merchants,unknownCategories,recurrence,anomalies:spikes,recommendation,generatedAt:new Date(now).toISOString(),guardrails:{noNewStore:true,readOnly:true,noInventedCategories:true,explicitRecurrenceOnly:true,incompleteCannotBeAllClear:true,autoMutate:false}}
}
function card(m){const r=m.recommendation,trend=m.change30.pct===null?'bez srovnání':`${m.change30.pct>=0?'+':''}${Math.round(m.change30.pct*100)} %`;const cats=m.categories.slice(0,3).map(x=>`<span><b>${esc(x.label)}</b><small>${money(x.spend)}</small></span>`).join('')||'<span><b>Bez explicitních kategorií</b><small>nic nedoplňuju automaticky</small></span>';return `<section class="os484" data-spending484-root><header><div><small>OS484 · SPENDING INTELLIGENCE</small><h3>Kam mizí peníze?</h3></div><b>${m.complete?'DATA OK':'DATA NEÚPLNÁ'}</b></header><div class="os484-metrics"><span><small>7 dní</small><b>${money(m.windows.d7)}</b></span><span><small>30 dní</small><b>${money(m.windows.d30)}</b></span><span><small>90 dní</small><b>${money(m.windows.d90)}</b></span><span><small>vs. předchozích 30</small><b>${esc(trend)}</b></span></div><div class="os484-verdict ${String(r.code).toLowerCase()}"><small>${esc(r.action)}</small><b>${esc(r.reason)}</b></div><div class="os484-grid"><div><small>TOP EXPLICITNÍ KATEGORIE</small><div class="os484-ranks">${cats}</div></div><div><small>RECURRENCE</small><div class="os484-ranks"><span><b>${money(m.recurrence.recurring)}</b><small>explicitně recurring</small></span><span><b>${money(m.recurrence.variable)}</b><small>explicitně variable</small></span><span><b>${money(m.recurrence.unknown)}</b><small>neznámé</small></span></div></div></div><footer>${m.unknownCategories} transakcí bez kategorie · ${m.anomalies.length} statistických odchylek · read-only</footer></section>`}
function mount(){const anchor=document.querySelector('#moneyView [data-spending484-anchor]');if(!anchor)return false;const m=buildSpendingIntelligence484(),first=!window.__KAMIL_SPENDING484__;let host=anchor.querySelector('[data-spending484-root]');const wrap=document.createElement('div');wrap.innerHTML=card(m);const next=wrap.firstElementChild;let changed=false;if(host){if(host.innerHTML!==next.innerHTML||host.className!==next.className){host.replaceWith(next);host=next;changed=true}}else{anchor.replaceChildren(next);host=next;changed=true}window.__KAMIL_SPENDING484__={version:VERSION,healthy:true,mounted:!!host,model:m,refresh:renderSafe,build:buildSpendingIntelligence484,at:Date.now()};document.documentElement.dataset.spending484='1';if(first||changed)window.dispatchEvent(new CustomEvent('kamil:spending484-updated',{detail:{complete:m.complete,code:m.recommendation.code,changed}}));return true}
function renderSafe(){try{return mount()}catch(error){console.error('[spendingIntelligence484]',error);window.__KAMIL_SPENDING484__={version:VERSION,healthy:false,error:String(error?.message||error),refresh:renderSafe,at:Date.now()};return false}}
let timer=0,bound=false;const schedule=(delay=70)=>{clearTimeout(timer);timer=setTimeout(renderSafe,delay)};
export function installSpendingIntelligence484(){ensureCss();document.documentElement.dataset.spending484='1';if(!bound){bound=true;store.subscribe?.(()=>schedule(90));window.addEventListener('kamil:release-stamp',()=>schedule(25));window.addEventListener('kamil:view-change',e=>{if(isMoneyEvent(e))schedule(35)});window.addEventListener('focus',()=>schedule(40))}renderSafe();setTimeout(()=>schedule(20),950);setTimeout(()=>schedule(20),1900)}
