import {localInboxSummary660} from './inboxHub660.js';
import {ownEvent1100} from './runtimeOwnership1100.js';
import {loadProductAdvancedStyles} from './productAdvancedStyles.js';

const OWNER='product.tasksOverview';
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function when(x){if(x.days===null||x.days===undefined)return'bez termínu';if(x.days<0)return Math.abs(x.days)+' d po termínu';if(x.days===0)return'dnes';if(x.days===1)return'zítra';return'za '+x.days+' d'}
function rows(items){if(!items.length)return '<div class="pr1300-empty">Nic otevřeného.</div>';return items.slice(0,8).map(x=>'<button type="button" class="pr1300-row pr1300-clickrow" data-task-id="'+esc(x.id)+'" data-task-route="'+esc(x.route||'today')+'"><div class="pr1300-row-main"><b>'+esc(x.title)+'</b><small>'+esc(x.sourceLabel||x.bucket||'Úkol')+(x.detail?' · '+esc(x.detail).slice(0,90):'')+'</small></div><div class="pr1300-row-side '+(x.days!==null&&x.days<0?'bad':x.days===0?'warn':'')+'">'+esc(when(x))+'</div></button>').join('')}

export function renderTasksOverview(){
 const host=document.querySelector('#inboxView');if(!host)return false;const m=localInboxSummary660(),top=m.top;
 host.innerHTML='<div class="pr1300-shell" data-tasks-overview>' +
 '<div class="pr1300-head"><div><div class="pr1300-kicker">Úkoly a čekání</div><h1>Jedna fronta všeho, co je potřeba vyřídit.</h1><p>Úkoly, follow-upy, platby, dokumenty a termíny. Bez technického Inbox slovníku.</p></div><span class="pr1300-status '+(m.counts.urgent?'bad':m.counts.total?'warn':'good')+'">'+(m.counts.total?m.counts.total+' otevřených':'čisto')+'</span></div>' +
 '<section class="pr1300-hero"><div><div class="pr1300-kicker">Vyřešit jako první</div><h2>'+esc(top?.title||'Nic akutního')+'</h2><p>'+esc(top?.detail||'Žádná otevřená položka teď nemá vysokou prioritu.')+'</p></div><div class="pr1300-hero-value"><b>'+m.counts.urgent+'</b><span>urgentní položky</span></div></section>' +
 '<div class="pr1300-kpis"><div class="pr1300-kpi"><span>Odpovědět</span><b>'+m.counts.reply+'</b><small>reakce a maily</small></div><div class="pr1300-kpi"><span>Vyřešit</span><b>'+m.counts.do+'</b><small>konkrétní kroky</small></div><div class="pr1300-kpi"><span>Čekám</span><b>'+m.counts.waiting+'</b><small>follow-upy</small></div><div class="pr1300-kpi"><span>Termíny</span><b>'+m.counts.deadline+'</b><small>časově omezené</small></div></div>' +
 '<div class="pr1300-actions"><button class="pr1300-btn primary" type="button" data-task-add>＋ Přidat úkol</button><button class="pr1300-btn" type="button" data-task-wait>Čekám na někoho</button><button class="pr1300-btn" type="button" data-task-advanced>Celá fronta + Gmail</button></div>' +
 '<section class="pr1300-panel"><div class="pr1300-panel-head"><h2>Nejdůležitější otevřené věci</h2><span>nejvyšší priorita nahoře</span></div>'+rows(m.rows)+'</section></div>';
 if(!host.dataset.tasksOverviewBound){host.dataset.tasksOverviewBound='1';ownEvent1100(OWNER,host,'click',async e=>{if(e.target.closest('[data-task-add]')){window.dispatchEvent(new CustomEvent('kamil:capture',{detail:'task'}));return}if(e.target.closest('[data-task-wait]')){window.dispatchEvent(new CustomEvent('kamil:capture',{detail:'waiting'}));return}const route=e.target.closest('[data-task-route]');if(route){const current=localInboxSummary660().rows.find(x=>String(x.id)===route.dataset.taskId);if(current?.action){const {openPersonalAction641}=await import('./personalActionExecution641.js');await openPersonalAction641(current.action)}else window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:route.dataset.taskRoute||'today'}));return}if(e.target.closest('[data-task-advanced]')){await loadProductAdvancedStyles(["./core70.css","./personal64.css"]);const m=await import('./inboxAdvanced141.js');await m.renderInboxPage141?.()}})}
 window.__KAMIL_TASKS_OVERVIEW__={healthy:true,total:m.counts.total,urgent:m.counts.urgent,at:Date.now()};return true;
}