import {ownEvent1100,schedule1100} from './runtimeOwnership1100.js';

const VERSION=456,OWNER='tickets.recovery456';let bound=false,lastRecovery=0;const errors=[];const MAX=12,COOLDOWN=60000;
const now=()=>Date.now(),active=()=>!!document.querySelector('#view-tickets.on');
function ticketish(v=''){return /ticket|tickets|kamil:ticket/i.test(String(v||''))}
function moduleOf(v=''){const m=String(v||'').match(/ticket([A-Za-z0-9_-]*?)(\d{3})?\.js/i);return m?`ticket${m[1]||''}${m[2]||''}`:'ticket-runtime'}
function add(kind,message,source,stack=''){const rec={at:now(),kind,module:moduleOf(source||stack||message),message:String(message||'Unknown error').slice(0,240),source:String(source||'').slice(0,180),stack:String(stack||'').slice(0,500)};errors.unshift(rec);if(errors.length>MAX)errors.length=MAX;window.__KAMIL_TICKET_ERRORS456__={version:VERSION,errors:[...errors],at:now()};schedule();maybeRecover()}
function recent(ms=60000){const cut=now()-ms;return errors.filter(x=>x.at>=cut)}
function maybeRecover(){const r=recent();if(!active()||r.length<3||now()-lastRecovery<COOLDOWN)return;lastRecovery=now();window.dispatchEvent(new CustomEvent('kamil:ticket-recovery456-start',{detail:{errors:r.length}}));schedule1100(OWNER,'recover',()=>{if(!active())return;window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}));window.dispatchEvent(new CustomEvent('kamil:ticket-refresh397-done',{detail:{source:'recovery456'}}));window.dispatchEvent(new CustomEvent('kamil:ticket-engine426-updated',{detail:{source:'recovery456'}}));window.dispatchEvent(new CustomEvent('kamil:ticket-recovery456-done',{detail:{at:now()}}))},350,{pauseWhenHidden:true})}
function ensureCss(){if(document.querySelector('style[data-rec456]'))return;const s=document.createElement('style');s.dataset.rec456='1';s.textContent=`#ticketIntelView .rec456{margin:0 0 10px;border:1px solid rgba(255,255,255,.08);border-radius:12px;background:#11161d;color:#e7ebf0;overflow:hidden}.rec456-head{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:8px 11px}.rec456-title{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.rec456 span{font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#7f8996}.rec456 b{font-size:10px}.rec456-bad{color:#eb8d94}.rec456-warn{color:#e7be71}.rec456-list{display:none;border-top:1px solid rgba(255,255,255,.06);padding:8px 10px}.rec456.open .rec456-list{display:block}.rec456-row{padding:6px 0;border-top:1px solid rgba(255,255,255,.05)}.rec456-row:first-child{border-top:0}.rec456-row small{display:block;color:#77818d;font-size:8px;margin-top:2px}.rec456-btn{border:1px solid rgba(255,255,255,.09);border-radius:9px;background:#151b23;color:#d6dbe2;padding:5px 8px;font-size:8px;font-weight:900;cursor:pointer}`;document.head.appendChild(s)}
function paint(){
 if(!active())return;
 const r=recent(),status=r.length>=3?'RECOVERY':r.length?'WATCH':'CLEAN';
 window.__KAMIL_TICKET_RECOVERY456__={version:VERSION,healthy:r.length<3,status,recent:r.length,total:errors.length,lastRecovery,runtimeOwner:OWNER,at:now()};
 document.documentElement.dataset.ticketRecovery456=status.toLowerCase();
 const existing=document.querySelector('#ticketIntelView [data-recovery456]');
 if(status==='CLEAN'){existing?.remove();return}
 ensureCss();const host=document.querySelector('#ticketIntelView .td331');if(!host)return;
 let box=existing;if(!box){box=document.createElement('section');box.dataset.recovery456='1';box.className='rec456';const health=document.querySelector('#ticketIntelView [data-runtime455]');health?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.prepend(box)}
 const tone=status==='RECOVERY'?'bad':'warn',open=box.classList.contains('open');
 box.innerHTML=`<div class="rec456-head"><div class="rec456-title"><span>CLIENT RECOVERY</span><b class="rec456-${tone}">${status}</b><span>60s ${r.length}</span><span>session ${errors.length}</span></div><button class="rec456-btn" data-rec456-clear>Vyčistit log</button></div><div class="rec456-list">${errors.map(e=>`<div class="rec456-row"><span>${e.kind} · ${e.module}</span><b class="rec456-bad">${e.message}</b><small>${new Date(e.at).toLocaleTimeString('cs-CZ')}${e.source?` · ${e.source}`:''}</small></div>`).join('')}</div>`;
 if(open)box.classList.add('open');box.querySelector('.rec456-head')?.addEventListener('click',e=>{if(e.target.closest('[data-rec456-clear]'))return;box.classList.toggle('open')});box.querySelector('[data-rec456-clear]')?.addEventListener('click',()=>{errors.length=0;window.__KAMIL_TICKET_ERRORS456__={version:VERSION,errors:[],at:now()};paint()})
}
function schedule(ms=100){if(!active())return;schedule1100(OWNER,'paint',paint,ms,{pauseWhenHidden:true})}
function cadence(){if(active())schedule(0);schedule1100(OWNER,'cadence',cadence,60000,{pauseWhenHidden:true})}
export function installTicketRecovery456(){if(bound)return;bound=true;ownEvent1100(OWNER,window,'error',e=>{const src=e.filename||e.error?.stack||'';if(ticketish(src)||ticketish(e.message))add('ERROR',e.message||e.error?.message,src,e.error?.stack||'')});ownEvent1100(OWNER,window,'unhandledrejection',e=>{const reason=e.reason,stack=reason?.stack||'',msg=reason?.message||reason;if(ticketish(stack)||ticketish(msg))add('PROMISE',msg,stack,stack)});for(const ev of ['kamil:view-change','kamil:ticket-recovery456-start','kamil:ticket-recovery456-done'])ownEvent1100(OWNER,window,ev,()=>schedule());schedule(15500);schedule1100(OWNER,'cadence',cadence,60000,{pauseWhenHidden:true})}
