import {h,formModal,modal} from './utils.js';
import {loadTicketCloud660,updateTicketTracking660} from './ticketCloud660.js';
import {ownEvent1100,ownObserver1100,schedule1100} from './runtimeOwnership1100.js';
const VERSION=382,OWNER='tickets.source382';
let bound=false,observing=false,retries=0,busy=false;
const active=()=>!!document.querySelector('#view-tickets.on,#view-tickets.active,[data-view-panel="tickets"].on,[data-view-panel="tickets"].active');
const valid=(url,host)=>!url||new RegExp(`^https:\\/\\/(?:[^/]+\\.)?${host.replace('.','\\.')}\\/`,'i').test(url);
async function edit(id){if(!active())return;const cloud=await loadTicketCloud660();if(!cloud?.ok)throw cloud?.error||new Error('Ticket cloud není dostupný');if(!active())return;const r=(cloud.inventory||[]).find(x=>String(x.id)===String(id));if(!r)return;const data=await formModal(`Tržní zdroje · ${h(r.event_name||'Vstupenka')}`,`<label class="field"><span>Viagogo event URL</span><input name="viagogo" type="url" value="${h(r.viagogo_url||'')}" placeholder="https://www.viagogo.com/.../E-123456"></label><label class="field"><span>StubHub event URL</span><input name="stubhub" type="url" value="${h(r.stubhub_url||'')}" placeholder="https://www.stubhub.com/.../event/123456789/"></label><label class="field"><span>Řada</span><input name="row" value="${h(r.row_label||'')}" placeholder="např. 12, A, B5"></label><p class="muted">Přímé event URL zvyšují přesnost trhu. Řada umožní porovnávat skutečně podobná místa.</p>`,{submitLabel:'Uložit a přepočítat'});if(!data||!active())return;const viagogo=String(data.viagogo||'').trim(),stubhub=String(data.stubhub||'').trim(),row=String(data.row||'').trim();if(!valid(viagogo,'viagogo.com')){await modal('Neplatný Viagogo odkaz','<p>Vlož přímý odkaz na konkrétní event z Viagogo.</p>',[{label:'OK',value:null,primary:true}]);return}if(!valid(stubhub,'stubhub.com')){await modal('Neplatný StubHub odkaz','<p>Vlož přímý odkaz na konkrétní event ze StubHub.</p>',[{label:'OK',value:null,primary:true}]);return}const out=await updateTicketTracking660(r.id,{viagogoUrl:viagogo||null,stubhubUrl:stubhub||null,rowLabel:row||null});if(!out?.ok)throw out?.error||new Error('Uložení zdrojů selhalo');if(!active())return;window.dispatchEvent(new CustomEvent('kamil:ticket-source382-saved',{detail:{id:r.id}}));window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}))}
function wire(){if(!active())return false;const host=document.querySelector('#ticketIntelView');if(!host)return false;for(const current of host.querySelectorAll('[data-ticket-source]')){if(current.dataset.source382==='1')continue;const btn=current.cloneNode(true);btn.dataset.source382='1';btn.textContent='Zdroj + řada';current.replaceWith(btn)}return true}
function observe(){if(observing)return true;const host=document.querySelector('#ticketIntelView');if(!host)return false;wire();ownObserver1100(OWNER,host,{childList:true,subtree:true},()=>wire());observing=true;return true}
function attachCadence(){if(observe())return;retries++;if(retries<32)schedule1100(OWNER,'cadence',attachCadence,250,{pauseWhenHidden:true})}
export function installTicketSourceEditor382(){if(bound)return;bound=true;document.documentElement.dataset.ticketSource382='1';ownEvent1100(OWNER,document,'click',async e=>{if(!active()||busy)return;const btn=e.target?.closest?.('#ticketIntelView [data-ticket-source][data-source382="1"]');if(!btn)return;e.preventDefault();busy=true;btn.disabled=true;const old=btn.textContent;btn.textContent='Ukládám…';try{await edit(btn.dataset.ticketSource)}catch(error){console.error('[ticket-source382]',error);await modal('Uložení selhalo',`<p>${h(error?.message||'Zdroj se nepodařilo uložit.')}</p>`,[{label:'OK',value:null,primary:true}])}finally{busy=false;if(btn.isConnected){btn.disabled=false;btn.textContent=old}}},true);ownEvent1100(OWNER,window,'kamil:view-change',()=>{if(!active())return;retries=0;schedule1100(OWNER,'wire',()=>{wire();attachCadence()},200,{pauseWhenHidden:true})});attachCadence();window.__KAMIL_TICKET_SOURCE382__={version:VERSION,healthy:true,at:Date.now()}}
