import {loadTicketCloud660,markTicketAlertsSeen660} from './ticketCloud660.js';
import {cloudClient,session} from './cloud.js';

const VERSION=413,N=v=>Number(v||0),ACTIVE=new Set(['LISTED','NOT_LISTED']);let bound=false,timer=0,busy=false;
const sorted=rows=>[...(rows||[])].filter(x=>N(x.market_price_czk)>0).sort((a,b)=>Date.parse(b.checked_at||0)-Date.parse(a.checked_at||0));
function modelMap(){return new Map((window.__KAMIL_TICKET_AUTOPILOT407__?.models||[]).map(m=>[String(m.r?.id),m]))}
function marketSignals(cloud){const out=[],models=modelMap();for(const r of cloud.inventory||[]){if(!ACTIVE.has(String(r.market_status||'')))continue;const rows=sorted(cloud.history?.get(r.id)||[]),now=rows[0],prev=rows.find((x,i)=>i>0&&N(x.market_price_czk)!==N(now?.market_price_czk));if(now&&prev){const a=N(prev.market_price_czk),b=N(now.market_price_czk),chg=a?((b/a)-1)*100:0;if(Math.abs(chg)>=8)out.push({ticket:r,severity:Math.abs(chg)>=18?'high':'medium',code:chg<0?'PRICE_DROP':'PRICE_RISE',title:`${chg<0?'Cena klesla':'Cena vzrostla'} ${Math.abs(chg).toFixed(0)} %`,body:`${r.event_name}: ${Math.round(a).toLocaleString('cs-CZ')} → ${Math.round(b).toLocaleString('cs-CZ')} Kč/ks.`})}const m=models.get(String(r.id));if(m?.a&&['PRODAT DNES','ZLEVNIT','ZDRAŽIT','VYSTAVIT'].includes(String(m.a.code))&&N(m.a.price)>0)out.push({ticket:r,severity:m.a.code==='PRODAT DNES'?'critical':m.a.code==='ZLEVNIT'?'high':'medium',code:m.a.code,title:`Autopilot: ${m.a.code}`,body:`${r.event_name}: cíl ${Math.round(N(m.a.price)).toLocaleString('cs-CZ')} Kč/ks. ${m.a.why||''}`});if(now?.multi_market_conflict)out.push({ticket:r,severity:'high',code:'VERIFY_DATA',title:'Konflikt marketů',body:`${r.event_name}: Viagogo a StubHub se výrazně rozcházejí. Automatické přecenění je blokované.`})}return out}
async function recentKeys(c,userId){const since=new Date(Date.now()-18*36e5).toISOString(),{data}=await c.from('ticket_market_alerts').select('ticket_id,recommendation_code,title,created_at').eq('user_id',userId).gte('created_at',since).limit(200);return new Set((data||[]).map(x=>`${x.ticket_id}|${x.recommendation_code}|${x.title}`))}
async function generate(){if(busy)return;busy=true;try{const cloud=await loadTicketCloud660();if(!cloud?.ok)return;const c=await cloudClient(),sess=await session();if(!c||!sess)return;const keys=await recentKeys(c,sess.user.id),signals=marketSignals(cloud),rows=[];for(const s of signals){const key=`${s.ticket.id}|${s.code}|${s.title}`;if(keys.has(key))continue;rows.push({user_id:sess.user.id,ticket_id:s.ticket.id,created_at:new Date().toISOString(),severity:s.severity,recommendation_code:s.code,title:s.title,body:s.body,seen_at:null});keys.add(key)}if(rows.length){const {error}=await c.from('ticket_market_alerts').insert(rows);if(error)throw error;window.dispatchEvent(new CustomEvent('kamil:ticket-alert413-created',{detail:{count:rows.length}}));window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}))}window.__KAMIL_TICKET_ALERTS413__={version:VERSION,healthy:true,generated:rows.length,signals:signals.length,at:Date.now()}}catch(e){console.error('[ticket413]',e);window.__KAMIL_TICKET_ALERTS413__={version:VERSION,healthy:false,error:String(e?.message||e),at:Date.now()}}finally{busy=false}}
function wireSeen(){const host=document.querySelector('#ticketIntelView');if(!host)return;const b=host.querySelector('[data-seen]');if(!b||b.dataset.alert413==='1')return;b.dataset.alert413='1';b.addEventListener('click',async()=>{const cloud=await loadTicketCloud660();const ids=(cloud.alerts||[]).map(x=>x.id).filter(Boolean);if(ids.length)await markTicketAlertsSeen660(ids)},true)}
function schedule(ms=350){clearTimeout(timer);timer=setTimeout(()=>{wireSeen();generate()},ms)}
export function installTicketAlerts413(){if(bound)return;bound=true;for(const ev of ['kamil:ticket-refresh397-done','kamil:ticket-manual398-saved','kamil:ticket-clipboard403-saved','kamil:ticket-target410-saved'])window.addEventListener(ev,()=>schedule());window.addEventListener('kamil:view-change',()=>setTimeout(wireSeen,120));new MutationObserver(()=>setTimeout(wireSeen,80)).observe(document.body,{childList:true,subtree:true});setTimeout(wireSeen,900);window.__KAMIL_TICKET_ALERTS413__={version:VERSION,healthy:true,ready:true,generate}}
