const VERSION=459;let bound=false,timer=0;
const FILTERS=[['ALL','Vše'],['UDĚLEJ TEĎ','Teď'],['UDĚLEJ DNES','Dnes'],['SLEDUJ','Sleduj'],['NECHEJ BÝT','Klid']];
function currentFilter(){try{return localStorage.getItem('kamil.ticket.focus459')||'ALL'}catch{return'ALL'}}
function saveFilter(v){try{localStorage.setItem('kamil.ticket.focus459',v)}catch{}}
function ensureCss(){if(document.querySelector('style[data-focus459]'))return;const s=document.createElement('style');s.dataset.focus459='1';s.textContent=`
#ticketIntelView .focus459{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:7px 10px;border:1px solid #263e4e;border-radius:9px;background:#0a1720;color:#dce9f2;margin:0 0 6px}
#ticketIntelView .focus459-left{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.focus459-label{font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#7898ad}.focus459-btn{border:1px solid #304b5d;border-radius:999px;background:#0e2230;color:#9eb7c8;padding:5px 9px;font-size:8px;font-weight:900;cursor:pointer}.focus459-btn.active{background:#17334a;color:#dcefff;border-color:#4a7796}.focus459-btn[data-filter="UDĚLEJ TEĎ"].active{color:#ffacb4;border-color:#74414a}.focus459-btn[data-filter="UDĚLEJ DNES"].active{color:#efc17c;border-color:#6d5633}.focus459-btn[data-filter="SLEDUJ"].active{color:#9fc9e4}.focus459-btn[data-filter="NECHEJ BÝT"].active{color:#8bd8ad}.focus459-meta{font-size:8px;color:#7890a2;white-space:nowrap}
#ticketIntelView [data-inventory-card][data-focus459-hidden="1"]{display:none!important}
#ticketIntelView [data-inventory-card] .focus459-priority{display:inline-flex;margin-left:5px;padding:2px 5px;border-radius:999px;border:1px solid #2e4b5e;color:#85a4b9;font-size:7px;font-weight:900;vertical-align:middle}
@media(max-width:760px){#ticketIntelView .focus459{align-items:flex-start;flex-direction:column}.focus459-meta{white-space:normal}}
`;document.head.appendChild(s)}
function model(){const c=window.__KAMIL_TICKET_COMMANDER465__;if(!c?.rows?.length)return null;const rows=c.rows.map((x,i)=>({id:String(x.id),bucket:x.bucket||'SLEDUJ',score:Number(x.score||0),rank:i+1,code:x.what||'—'}));return{rows,map:new Map(rows.map(x=>[x.id,x]))}}
function cardId(card){const d=card.querySelector('[data-ticket-detail]');return d?String(d.dataset.ticketDetail||''):String(card.dataset.ticketId||'')}
function ensureBar(host,m,filter){let bar=host.querySelector('[data-focus459]');if(!bar){bar=document.createElement('section');bar.dataset.focus459='1';bar.className='focus459';const section=host.querySelector('.td331-section');section?.insertAdjacentElement('beforebegin',bar);if(!bar.isConnected){const overview=host.querySelector('.td331-overview');overview?.insertAdjacentElement('afterend',bar)}}const counts=Object.fromEntries(FILTERS.map(([k])=>[k,k==='ALL'?m.rows.length:m.rows.filter(x=>x.bucket===k).length]));bar.innerHTML=`<div class="focus459-left"><span class="focus459-label">OPERAČNÍ FOCUS</span>${FILTERS.map(([k,label])=>`<button type="button" class="focus459-btn ${filter===k?'active':''}" data-filter="${k}">${label} · ${counts[k]||0}</button>`).join('')}</div><div class="focus459-meta">Commander priorita</div>`;for(const b of bar.querySelectorAll('[data-filter]'))b.addEventListener('click',()=>{saveFilter(b.dataset.filter);schedule(0)})}
function applyCards(host,m,filter){const cards=[...host.querySelectorAll('[data-inventory-card]')],grid=cards[0]?.parentElement;let visible=0,known=0;const decorated=[];for(const card of cards){const id=cardId(card),x=m.map.get(id);if(x)known++;const show=filter==='ALL'||x?.bucket===filter;card.dataset.focus459Hidden=show?'0':'1';if(show)visible++;const h=card.querySelector('h3');if(h&&x){let chip=h.querySelector('.focus459-priority');if(!chip){chip=document.createElement('span');chip.className='focus459-priority';h.appendChild(chip)}chip.textContent=`#${x.rank} ${x.bucket==='UDĚLEJ TEĎ'?'TEĎ':x.bucket==='UDĚLEJ DNES'?'DNES':x.bucket==='SLEDUJ'?'SLED':'KLID'}`;decorated.push({card,score:x.score,rank:x.rank})}else decorated.push({card,score:-1,rank:9999})}
if(grid){decorated.sort((a,b)=>b.score-a.score||a.rank-b.rank);for(const x of decorated)grid.appendChild(x.card)}return{cards:cards.length,visible,known}}
function render(){ensureCss();const host=document.querySelector('#ticketIntelView .td331'),m=model();if(!host||!m)return;let filter=currentFilter();if(!FILTERS.some(([k])=>k===filter))filter='ALL';ensureBar(host,m,filter);const stats=applyCards(host,m,filter);window.__KAMIL_TICKET_FOCUS459__={version:VERSION,healthy:true,source:'commander465',filter,...stats,at:Date.now()};document.documentElement.dataset.ticketFocus459='1';window.dispatchEvent(new CustomEvent('kamil:ticket-focus459-updated',{detail:{filter,visible:stats.visible}}))}
function schedule(ms=100){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketOperationalFocus459(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-commander465-updated','kamil:ticket-ui457-updated','kamil:ticket-layout458-updated','kamil:ticket-refresh397-done'])window.addEventListener(ev,()=>schedule());schedule(1200)}
