import {store} from './state.js';
import {h,money,date,dayDiff,uid,qs,qsa,modal,toast} from './utils.js';
import {ticketStatus} from './intelligence.js';
import {ticketDecision,ticketOpportunityDecision,ticketIntelligenceAge,actionLabel} from './live24.js';
import {ticketSellCockpit} from './ticketCockpit24.js';
import {ticketEventGroups,ticketEventStats} from './ticketEvents25.js';
import {ticketLessons} from './ticketLessons25.js';
import {refreshIntelligence} from './cloud.js';

let ticketFilter='active',selectedEventKey=null;
const flowLabel=x=>({HOLD:'Držím',LISTED:'V prodeji',SOLD:'Prodáno','PAYOUT WAIT':'Čekám na výplatu','PAYOUT RECEIVED':'Vyplaceno'}[x.workflow||'HOLD']||x.workflow||'Držím');
const statusClass=st=>st.score>=85?'bad':st.score>=65?'warn':'good';
const workflow=x=>x.workflow||'HOLD';
const expectedProfit=x=>(Number(x.listPrice||0)*Number(x.qty||1))-Number(x.buy||0),actualProfit=x=>Number(x.sell||0)-Number(x.buy||0)-Number(x.fees||0);
const matchesFilter=x=>ticketFilter==='all'||(ticketFilter==='active'&&['HOLD','LISTED'].includes(workflow(x)))||(ticketFilter==='payout'&&['SOLD','PAYOUT WAIT'].includes(workflow(x)))||(ticketFilter==='done'&&workflow(x)==='PAYOUT RECEIVED');

export function renderTickets(){
 const s=store.get(),groups=ticketEventGroups(s);
 if(selectedEventKey){const g=groups.find(x=>x.key===selectedEventKey);if(g){renderEventDetail(s,g);return}selectedEventKey=null}
 const items=[...(s.ticketBook?.items||[])].sort((a,b)=>new Date(a.date||'9999')-new Date(b.date||'9999')),watch=[...(s.ticketBook?.watchlist||[])],liveAge=ticketIntelligenceAge(s),cockpit=ticketSellCockpit(s),eventStats=ticketEventStats(groups),lessons=ticketLessons(s);
 const active=items.filter(x=>['HOLD','LISTED'].includes(workflow(x))),decisions=active.map(x=>({x,d:ticketDecision(x,s)})).sort((a,b)=>b.d.priority-a.d.priority);
 const waiting=items.filter(x=>['SOLD','PAYOUT WAIT'].includes(workflow(x))).length,done=items.filter(x=>workflow(x)==='PAYOUT RECEIVED').length,capital=active.reduce((n,x)=>n+Number(x.buy||0),0),urgency=decisions.filter(x=>x.d.priority>=80).length,realized=items.filter(x=>Number(x.sell||0)>0).reduce((n,x)=>n+actualProfit(x),0),shown=items.filter(matchesFilter),buyNow=watch.map(x=>({x,d:ticketOpportunityDecision(x,s)})).filter(y=>y.d.action==='BUY').length;
 qs('#ticketsView').innerHTML=`
  <div class="view-head"><div><div class="eyebrow">VSTUPENKY / INTELLIGENCE</div><h1>Kdy koupit a kdy prodat</h1><p>Portfolio, sell timing, cenová pravidla a radar oficiálních nákupních příležitostí.</p></div><div class="view-head-stat"><b>${money(capital)}</b><span>kapitál v aktivních pozicích</span></div></div>
  <div class="metric-strip ticket-metrics"><div class="metric"><span>Aktivní pozice</span><b>${active.length}</b></div><div class="metric"><span>K řešení teď</span><b class="${urgency?'warn':'good'}">${urgency}</b></div><div class="metric"><span>Nákupní radar</span><b class="${buyNow?'good':''}">${buyNow}</b></div><div class="metric"><span>Realizovaný P/L</span><b class="${realized>=0?'good':'bad'}">${money(realized)}</b></div></div>

  <div class="card"><div class="card-head"><div><div class="eyebrow">TICKET LESSONS</div><h2>Co říká realizovaná historie</h2></div><span class="status ${lessons.totalProfit<0?'warn':'good'}">${lessons.trades} obchodů · ${lessons.hitRate===null?'—':Math.round(lessons.hitRate)+' %'} win rate</span></div>
   <div class="metric-strip"><div class="metric"><span>Realizovaný P/L historie</span><b class="${lessons.totalProfit>=0?'good':'bad'}">${money(lessons.totalProfit)}</b></div><div class="metric"><span>ROI realizovaných</span><b class="${Number(lessons.roi||0)>=0?'good':'bad'}">${lessons.roi===null?'—':lessons.roi.toFixed(1)+' %'}</b></div><div class="metric"><span>Nejlepší obchod</span><b class="good">${lessons.best?money(lessons.best.lessonProfit):'—'}</b></div><div class="metric"><span>Nejhorší obchod</span><b class="${lessons.worst&&lessons.worst.lessonProfit<0?'bad':''}">${lessons.worst?money(lessons.worst.lessonProfit):'—'}</b></div></div>
   <div class="intel-list">${lessons.lessons.map((x,i)=>`<div class="intel-row"><div class="intel-main"><b>${i===0?'Hlavní poučení':'Další signál'}</b><span>${h(x)}</span></div></div>`).join('')}</div>
   ${lessons.categories.length?`<div class="intel-rules">${lessons.categories.slice(0,4).map(x=>`<div class="intel-rule"><span>${h(x.category)}</span><b class="${x.profit>=0?'good':'bad'}">${money(x.profit)} · ${Math.round(x.hitRate)} % win · Ø ${x.avgQty.toFixed(1)} ks</b></div>`).join('')}</div>`:''}
   <div class="decision-note">${h(lessons.evidence)} Lessons jsou zpětný pohled, ne živá predikce trhu.</div>
  </div>

  <div class="card ticket-events-card"><div class="card-head"><div><div class="eyebrow">EVENT PORTFOLIO</div><h2>Akce místo jednotlivých sektorů</h2></div><span class="status ${eventStats.urgentEvents?'warn':'good'}">${eventStats.activeEvents} aktivních akcí · ${eventStats.activeQty} ks</span></div>
   <div class="event-portfolio-grid">${groups.filter(g=>g.activeQty>0||g.soldQty>0).slice(0,10).map(eventCard).join('')||'<div class="empty">Zatím nejsou žádné vstupenkové akce.</div>'}</div>
   <div class="decision-note">Pozice se seskupují pouze pro přehled. Původní vstupenky, ceny a workflow zůstávají beze změny; stejné datum + rozpoznaný sektor se počítají jako jedna akce.</div>
  </div>

  <div class="card"><div class="card-head"><div><div class="eyebrow">SELL COCKPIT</div><h2>Riziko neprodané zásoby</h2></div><span class="status ${cockpit.urgent?'warn':'good'}">${cockpit.urgent} urgentních</span></div><div class="metric-strip"><div class="metric"><span>Neprodané kusy</span><b>${cockpit.openQty}</b></div><div class="metric"><span>Kapitál v riziku</span><b>${money(cockpit.capitalAtRisk)}</b></div><div class="metric"><span>Cenový plán</span><b class="${cockpit.pricingCoverage<60?'warn':'good'}">${cockpit.pricingCoverage} %</b></div><div class="metric"><span>Nejbližší akce</span><b>${cockpit.nextEventDays===null?'—':cockpit.nextEventDays===0?'dnes':`za ${cockpit.nextEventDays} d`}</b></div></div>${cockpit.projectedProfit===null?'<div class="decision-note warn">Projektovaný výstup nepočítám, dokud nemá aspoň jedna aktivní pozice reálnou uloženou nebo živou cenu.</div>':`<div class="decision-note">U pozic s cenovým plánem je orientační výstup ${money(cockpit.projectedExit)} a rozdíl proti jejich nákladu ${money(cockpit.projectedProfit)}. Nezaceněné pozice nejsou do odhadu započtené.</div>`}<div class="intel-list">${cockpit.top.map(x=>`<div class="intel-row"><div class="intel-main"><b>${h(x.name)}</b><span>${x.qty} ks · ${h(x.when||x.reason||'')}</span></div><div class="row-actions"><span class="decision-action ${x.priority>=90?'bad':x.priority>=80?'warn':''}">${h(actionLabel(x.action))}</span><span class="intel-source">priorita ${Math.round(x.priority)}${x.confidence!==null?` · ${Math.round(Number(x.confidence)||0)} %`:''}</span></div></div>`).join('')||'<div class="empty">Žádná aktivní zásoba.</div>'}</div></div>
  <div class="ticket-intel-grid">
   <div class="card"><div class="card-head"><div><div class="eyebrow">SELL / HOLD RADAR</div><h2>Co udělat s pozicemi</h2></div><div class="intel-toolbar"><span class="live-chip ${liveAge.fresh?'':'stale'}"><i></i>${liveAge.fresh?'živý trh':'pravidlový režim'} · ${h(liveAge.label)}</span><button class="btn refresh-intel" id="refreshTicketIntel">Načíst analýzu</button></div></div><div class="intel-list">${decisions.slice(0,10).map(({x,d})=>intelRow(x,d)).join('')||'<div class="empty">Žádná aktivní pozice.</div>'}</div><div class="decision-note ${liveAge.fresh?'live':''}">${liveAge.fresh?'Čerstvá živá vrstva může doplnit tržní cenu, doporučený listing a confidence.':'Bez čerstvé živé vrstvy rozhoduje čas do akce a tvoje uložená cenová strategie.'}</div></div>
   <div class="card"><div class="card-head"><div><div class="eyebrow">BUY RADAR</div><h2>Co koupit oficiálně</h2></div><button class="btn" id="addTicketOpportunity">＋ Příležitost</button></div>${watch.sort((a,b)=>new Date(a.saleAt||'9999')-new Date(b.saleAt||'9999')).map(x=>opportunityRow(x,s)).join('')||'<div class="empty">Přidej akci, presale/on-sale termín a maximální nákupní cenu. Kamil OS pak řekne, kdy nakoupit.</div>'}</div>
  </div>
  <div class="card ticket-table-card"><div class="card-head ticket-card-head"><div><div class="eyebrow">POZICE</div><h2>${filterTitle()}</h2></div><div class="row-actions"><span class="status">${shown.length} z ${items.length}</span><button class="btn" data-capture-tickets>＋ Přidat</button></div></div><div class="ticket-filters" role="tablist" aria-label="Filtr vstupenek">${filterBtn('active',`Aktivní · ${active.length}`)}${filterBtn('payout',`Čekám na peníze · ${waiting}`)}${filterBtn('done',`Vyplaceno · ${done}`)}${filterBtn('all',`Vše · ${items.length}`)}</div><div class="ticket-table"><div class="ticket-head"><span>Akce</span><span>Stav</span><span>Datum</span><span>Nákup</span><span>Listing / prodej</span><span>P/L</span><span></span></div>${shown.map(row).join('')||'<div class="empty">V tomto filtru nejsou žádné vstupenky.</div>'}</div></div>`;
 bindOverviewActions();
}

function eventCard(g){
 const d=g.topDecision,days=g.days===null?'bez data':g.days<0?`${Math.abs(g.days)} d po akci`:g.days===0?'dnes':`za ${g.days} d`;
 return `<button class="event-card25" data-ticket-event="${h(g.key)}"><div class="event-card-top"><div><b>${h(g.name)}</b><span>${g.date?date(g.date):'Bez data'} · ${days}</span></div>${d?`<span class="decision-action ${d.tone||''}">${h(actionLabel(d.action))}</span>`:''}</div><div class="event-card-metrics"><span><b>${g.activeQty}</b> neprodáno</span><span><b>${g.soldQty}</b> prodáno</span><span><b>${money(g.capitalAtRisk)}</b> v riziku</span></div><div class="event-card-bottom"><span>${g.items.length} pozic / sektorů</span><strong>${d?h(d.when||d.reason||'Otevřít detail'):'Otevřít detail'} →</strong></div></button>`;
}

function renderEventDetail(s,g){
 const d=g.topDecision,pricedMissing=g.activeQty-g.pricedQty;
 qs('#ticketsView').innerHTML=`
  <div class="subview-bar"><button class="btn" id="ticketEventBack">← Vstupenky</button><div><span>VSTUPENKY / AKCE</span><b>${h(g.name)}</b></div></div>
  <div class="view-head event-detail-head"><div><div class="eyebrow">EVENT COMMAND CENTER</div><h1>${h(g.name)}</h1><p>${g.date?date(g.date):'Datum není vyplněné'} · ${g.items.length} pozic / sektorů · ${g.totalQty} ks celkem</p></div>${d?`<div class="event-primary-decision"><span class="decision-action ${d.tone||''}">${h(actionLabel(d.action))}</span><small>${h(d.when||d.reason||'')}</small></div>`:''}</div>
  <div class="metric-strip"><div class="metric"><span>Neprodané kusy</span><b class="${g.activeQty?'warn':'good'}">${g.activeQty}</b></div><div class="metric"><span>Prodané kusy</span><b>${g.soldQty}</b></div><div class="metric"><span>Kapitál v riziku</span><b>${money(g.capitalAtRisk)}</b></div><div class="metric"><span>Realizovaný P/L</span><b class="${g.realizedProfit>=0?'good':'bad'}">${money(g.realizedProfit)}</b></div></div>
  <div class="grid two event-summary-grid"><div class="card"><div class="eyebrow">CELÁ AKCE</div><div class="row"><span>Celkem investováno</span><b>${money(g.invested)}</b></div><div class="row"><span>Realizované tržby</span><b>${money(g.realizedRevenue)}</b></div><div class="row"><span>Poplatky prodaných</span><b>${money(g.fees)}</b></div><div class="row"><span>Vyplaceno kusů</span><b>${g.payoutQty} / ${g.totalQty}</b></div></div><div class="card"><div class="eyebrow">CENOVÝ PLÁN ZBYTKU</div>${g.projectedRevenue===null?'<div class="decision-note warn">Aktivní pozice nemají dost reálných listingových cen. Projektovaný výstup proto nevymýšlím.</div>':`<div class="row"><span>Zaceněno kusů</span><b>${g.pricedQty} / ${g.activeQty}</b></div><div class="row"><span>Projektovaný výstup</span><b>${money(g.projectedRevenue)}</b></div><div class="row"><span>Rozdíl proti nákladu zaceněných</span><b class="${g.projectedProfit>=0?'good':'bad'}">${money(g.projectedProfit)}</b></div>`}${pricedMissing>0?`<div class="decision-note warn">${pricedMissing} aktivních kusů nemá uloženou listingovou cenu a není zahrnuto do projekce.</div>`:''}</div></div>
  <div class="card event-positions-card"><div class="card-head"><div><div class="eyebrow">POZICE / SEKTORY</div><h2>${g.items.length} částí jedné akce</h2></div></div><div class="event-position-list">${g.items.map(x=>eventPositionRow(x,s)).join('')}</div></div>`;
 qs('#ticketEventBack').onclick=()=>{selectedEventKey=null;renderTickets()};
 bindTicketActions();
}

function eventPositionRow(x,s){
 const d=ticketDecision(x,s),qty=Number(x.qty||1),pl=Number(x.sell||0)>0?actualProfit(x):(Number(x.listPrice||0)>0?expectedProfit(x):null);
 return `<div class="event-position-row"><div class="event-position-main"><b>${h(x.name)}</b><span>${qty} ks · ${h(flowLabel(x))}${x.platform?` · ${h(x.platform)}`:''}</span><small>${h(d.reason||'')}</small></div><div class="event-position-number"><span>Nákup</span><b>${money(x.buy)}</b></div><div class="event-position-number"><span>${Number(x.sell||0)>0?'Prodej':'Listing'}</span><b>${Number(x.sell||0)>0?money(x.sell):Number(x.listPrice||0)>0?`${money(Number(x.listPrice)*qty)}`:'—'}</b></div><div class="event-position-number"><span>P/L</span><b class="${pl===null?'':pl>=0?'good':'bad'}">${pl===null?'—':money(pl)}</b></div><div class="event-position-actions"><span class="decision-action ${d.tone||''}">${h(actionLabel(d.action))}</span><button class="btn" data-ticket-edit24="${x.id}">Strategie</button>${buttons(x)}</div></div>`;
}

function bindOverviewActions(){
 qsa('[data-ticket-event]',qs('#ticketsView')).forEach(b=>b.onclick=()=>{selectedEventKey=b.dataset.ticketEvent;renderTickets();window.scrollTo({top:0,behavior:'smooth'})});
 qsa('[data-ticket-filter]',qs('#ticketsView')).forEach(b=>b.onclick=()=>{ticketFilter=b.dataset.ticketFilter;renderTickets()});qsa('[data-capture-tickets]',qs('#ticketsView')).forEach(b=>b.onclick=()=>window.dispatchEvent(new CustomEvent('kamil:capture',{detail:'ticket'})));qsa('[data-ticket-strategy]',qs('#ticketsView')).forEach(b=>b.onclick=()=>editTicket(b.dataset.ticketStrategy));qs('#addTicketOpportunity')?.addEventListener('click',addOpportunity);qsa('[data-opportunity-done]',qs('#ticketsView')).forEach(b=>b.onclick=()=>store.mutate('Nákupní příležitost uzavřena',s=>{const x=s.ticketBook.watchlist.find(y=>y.id===b.dataset.opportunityDone);if(x)x.status='BOUGHT'}));qs('#refreshTicketIntel')?.addEventListener('click',refreshTickets);bindTicketActions();
}
function bindTicketActions(){
 qsa('[data-ticket-edit24]',qs('#ticketsView')).forEach(b=>b.onclick=()=>editTicket(b.dataset.ticketEdit24));qsa('[data-ticket-sell24]',qs('#ticketsView')).forEach(b=>b.onclick=()=>sellTicket(b.dataset.ticketSell24));qsa('[data-ticket-state24]',qs('#ticketsView')).forEach(b=>b.onclick=()=>store.mutate(`Vstupenka → ${b.dataset.ticketState24}`,s=>{const x=s.ticketBook.items.find(y=>y.id===b.dataset.ticketId24);if(x){x.workflow=b.dataset.ticketState24;if(x.workflow==='PAYOUT RECEIVED')x.payoutAt=new Date().toISOString()}}));
}

const filterBtn=(id,label)=>`<button class="ticket-filter ${ticketFilter===id?'on':''}" data-ticket-filter="${id}" role="tab" aria-selected="${ticketFilter===id}">${label}</button>`;
const filterTitle=()=>({active:'Aktivní prodej',payout:'Prodané / čekám na výplatu',done:'Vyplacené obchody',all:'Všechny vstupenky'})[ticketFilter]||'Všechny vstupenky';
const priceTags=d=>{const x=[];if(d.marketPricePerTicket)x.push(`trh ${money(d.marketPricePerTicket)}`);if(d.recommendedListPricePerTicket)x.push(`doporučeno ${money(d.recommendedListPricePerTicket)}`);if(d.floorPricePerTicket)x.push(`floor ${money(d.floorPricePerTicket)}`);return x.length?`<div class="intel-prices">${x.map(v=>`<span>${h(v)}/ks</span>`).join('')}</div>`:''};
const intelRow=(x,d)=>`<div class="intel-row"><div class="intel-main"><b>${h(x.name)}</b><span>${h(d.reason)}</span>${d.headline?`<span class="live-headline">${h(d.headline)}</span>`:''}<div class="intel-rules"><div class="intel-rule"><span>Kdy koupit</span><b>${h(d.buyRule)}</b></div><div class="intel-rule"><span>Kdy prodat</span><b>${h(d.sellRule)}</b></div></div>${priceTags(d)}</div><div class="row-actions"><span class="decision-action ${d.tone||''}">${h(actionLabel(d.action))}</span>${d.source?`<span class="intel-source">${h(d.source)}${d.confidence!==null&&d.confidence!==undefined?` · ${Math.round(Number(d.confidence)||0)} %`:''}</span>`:''}<button class="btn" data-ticket-strategy="${x.id}">Strategie</button></div></div>`;
function opportunityRow(x,s){const d=ticketOpportunityDecision(x,s);return `<div class="opportunity-row"><div class="opportunity-top"><div><b>${h(x.name||'Akce')}</b><span>${x.saleAt?'prodej '+date(x.saleAt):'termín prodeje chybí'}${x.platform?' · '+h(x.platform):''}</span></div><span class="decision-action ${d.tone||''}">${h(actionLabel(d.action))}</span></div><div class="opportunity-rule">${h(d.when)} · ${h(d.reason)}</div>${priceTags(d)}<div class="row-actions" style="margin-top:7px"><span class="status">max ${money(x.maxBuyPrice||0)}/ks</span><span class="status">cíl ${money(x.targetResale||0)}/ks</span>${d.source?`<span class="intel-source">${h(d.source)}${d.confidence!==null&&d.confidence!==undefined?` · ${Math.round(Number(d.confidence)||0)} %`:''}</span>`:''}${x.status!=='BOUGHT'?`<button class="btn" data-opportunity-done="${x.id}">Nakoupeno</button>`:''}</div></div>`}
function row(x){const st=ticketStatus(x),qty=Number(x.qty||1),days=x.date?dayDiff(x.date):null,expected=expectedProfit(x),actual=actualProfit(x),hasActual=Number(x.sell||0)>0,pl=hasActual?actual:expected,roi=Number(x.buy||0)>0?pl/Number(x.buy||0)*100:0;return `<div class="ticket-tr ${st.score>=85?'urgent-row':''}"><div class="ticket-event"><b>${h(x.name)}</b><span>${qty} ks · ${h(x.platform||'platforma neuvedena')}</span></div><div><span class="status ${statusClass(st)}">${h(flowLabel(x))}</span><small>${h(st.label)}</small></div><div><b>${date(x.date)}</b><small>${days===null?'':days<0?`${Math.abs(days)} d po akci`:days===0?'dnes':`za ${days} d`}</small></div><div><b>${money(x.buy)}</b><small>${qty} ks</small></div><div><b>${hasActual?money(x.sell):money(Number(x.listPrice||0)*qty)}</b><small>${hasActual?'prodej celkem':'listing celkem'}</small></div><div><b class="${pl>=0?'good':'bad'}">${money(pl)}</b><small>${Number.isFinite(roi)?roi.toFixed(1):'0.0'} %</small></div><div class="ticket-actions"><button class="btn" data-ticket-edit24="${x.id}">Upravit</button>${buttons(x)}</div></div>`}
function buttons(x){if(workflow(x)==='HOLD')return `<button class="btn primary" data-ticket-state24="LISTED" data-ticket-id24="${x.id}">Do prodeje</button>`;if(workflow(x)==='LISTED')return `<button class="btn primary" data-ticket-sell24="${x.id}">Prodáno</button>`;if(workflow(x)==='SOLD')return `<button class="btn" data-ticket-state24="PAYOUT WAIT" data-ticket-id24="${x.id}">Čekám na výplatu</button>`;if(workflow(x)==='PAYOUT WAIT')return `<button class="btn primary" data-ticket-state24="PAYOUT RECEIVED" data-ticket-id24="${x.id}">Vyplaceno</button>`;return ''}
async function refreshTickets(){const b=qs('#refreshTicketIntel');if(b){b.disabled=true;b.textContent='Načítám…'}const r=await refreshIntelligence();toast(!r.ok?(r.error?.message||'Cloud není dostupný'):r.tickets?'Živá ticket intelligence načtena':'V cloudu zatím není nová ticket analýza');renderTickets()}
async function editTicket(id){const x=store.get().ticketBook.items.find(y=>y.id===id);if(!x)return;const body=`<div class="form-grid"><label>Platforma<input id="t24platform" autofocus value="${h(x.platform||'')}"></label><label>Počet ks<input id="t24qty" type="number" value="${Number(x.qty)||1}"></label><label>Nákup celkem<input id="t24buy" type="number" value="${Number(x.buy)||0}"></label><label>Datum akce<input id="t24date" type="date" value="${x.date?String(x.date).slice(0,10):''}"></label><label>Listing / cílová cena za kus<input id="t24list" type="number" value="${Number(x.listPrice)||0}"></label><label>Tržní cena za kus<input id="t24market" type="number" value="${Number(x.marketPrice)||0}"></label><label>Floor cena za kus<input id="t24floor" type="number" value="${Number(x.floorPrice)||0}"></label><label>Max cena pro další nákup / ks<input id="t24maxbuy" type="number" value="${Number(x.maxBuyPrice)||0}"></label><label>Chci prodat nejpozději<input id="t24sellby" type="date" value="${x.sellBy?String(x.sellBy).slice(0,10):''}"></label><label>Prodej celkem<input id="t24sell" type="number" value="${Number(x.sell)||0}"></label><label>Poplatky<input id="t24fees" type="number" value="${Number(x.fees)||0}"></label></div>`,ok=await modal('Upravit vstupenku a strategii',body,[{label:'Zrušit',value:false},{label:'Uložit',value:true,primary:true}]);if(!ok)return;store.mutate('Upravena vstupenka',s=>{const t=s.ticketBook.items.find(y=>y.id===id);if(!t)return;t.platform=qs('#t24platform')?.value||'';t.qty=Number(qs('#t24qty')?.value||1);t.buy=Number(qs('#t24buy')?.value||0);t.date=qs('#t24date')?.value||t.date;t.listPrice=Number(qs('#t24list')?.value||0);t.marketPrice=Number(qs('#t24market')?.value||0);t.floorPrice=Number(qs('#t24floor')?.value||0);t.maxBuyPrice=Number(qs('#t24maxbuy')?.value||0);t.sellBy=qs('#t24sellby')?.value||null;t.sell=Number(qs('#t24sell')?.value||0);t.fees=Number(qs('#t24fees')?.value||0);t.strategyUpdatedAt=new Date().toISOString()})}
async function sellTicket(id){const x=store.get().ticketBook.items.find(y=>y.id===id);if(!x)return;const suggested=Number(x.listPrice||0)*Number(x.qty||1),body=`<div class="form-grid"><label>Prodej celkem<input id="t24sale" autofocus type="number" value="${suggested||Number(x.sell)||0}"></label><label>Poplatky<input id="t24saleFees" type="number" value="${Number(x.fees)||0}"></label></div>`,ok=await modal('Vstupenka prodána',body,[{label:'Zrušit',value:false},{label:'Uložit prodej',value:true,primary:true}]);if(!ok)return;const sell=Number(qs('#t24sale')?.value||0),fees=Number(qs('#t24saleFees')?.value||0);store.mutate('Vstupenka prodána',s=>{const t=s.ticketBook.items.find(y=>y.id===id);if(!t||t.workflow==='SOLD')return;t.workflow='SOLD';t.sell=sell;t.fees=fees;t.soldAt=new Date().toISOString()})}
async function addOpportunity(){const body=`<div class="form-grid capture-form"><label class="wide-field">Akce<input id="oppName" autofocus placeholder="Např. Sparta – Real Madrid"></label><label>Oficiální prodej / presale<input id="oppSale" type="datetime-local"></label><label>Datum akce<input id="oppDate" type="date"></label><label>Platforma<input id="oppPlatform" placeholder="Ticketmaster / klub…"></label><label>Max nákup / ks<input id="oppMaxBuy" type="number" min="0"></label><label>Cílový resale / ks<input id="oppTarget" type="number" min="0"></label></div>`,ok=await modal('Nákupní příležitost',body,[{label:'Zrušit',value:false},{label:'Přidat do radaru',value:true,primary:true}]);if(!ok)return;const name=qs('#oppName')?.value?.trim();if(!name)return;const sale=qs('#oppSale')?.value||'',event=qs('#oppDate')?.value||'';store.mutate(`Ticket radar: ${name}`,s=>{s.ticketBook=s.ticketBook||{items:[],watchlist:[]};s.ticketBook.watchlist=s.ticketBook.watchlist||[];s.ticketBook.watchlist.unshift({id:uid('ticket-watch'),name,saleAt:sale?new Date(sale).toISOString():null,date:event||null,platform:qs('#oppPlatform')?.value?.trim()||'',maxBuyPrice:Number(qs('#oppMaxBuy')?.value||0),targetResale:Number(qs('#oppTarget')?.value||0),status:'WATCH',createdAt:new Date().toISOString()})})}
