import {cloudClient,session} from './cloud.js';
const VERSION=402,N=v=>Number(v||0);let bound=false,timer=0,cache=null,cacheAt=0;
const fmt=v=>N(v)>0?`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`:'—';
const ageLabel=iso=>{const t=Date.parse(iso||'');if(!Number.isFinite(t))return'čas neznámý';const h=Math.max(0,(Date.now()-t)/36e5);return h<1?'< 1 h':h<24?`${Math.round(h)} h`:`${Math.round(h/24)} d`};
async function load(){if(cache&&Date.now()-cacheAt<60000)return cache;const c=await cloudClient(),sess=await session();if(!c||!sess)return new Map();const {data,error}=await c.from('ticket_market_snapshots').select('ticket_id,checked_at,market_price_czk,median_price_czk,p25_price_czk,confidence,source_message,resolved_url,same_section_count,same_row_count,quantity_matched').eq('user_id',sess.user.id).gt('market_price_czk',0).order('checked_at',{ascending:false}).limit(1000);if(error)throw error;const m=new Map();for(const r of data||[])if(!m.has(String(r.ticket_id)))m.set(String(r.ticket_id),r);cache=m;cacheAt=Date.now();return m}
function patchCard(card,row){if(!row||N(row.market_price_czk)<=0)return false;const cells=[...card.querySelectorAll('.td331-price')],market=cells.find(x=>/Trh\s*\/\s*ks/i.test(x.querySelector('span')?.textContent||''));if(!market)return false;const b=market.querySelector('b'),small=market.querySelector('small');if(!b||String(b.textContent||'').trim()!=='—')return false;b.textContent=fmt(row.market_price_czk);market.classList.add('low-confidence');if(small)small.textContent=`poslední známá · ${ageLabel(row.checked_at)}`;else market.insertAdjacentHTML('beforeend',`<small>poslední známá · ${ageLabel(row.checked_at)}</small>`);card.dataset.priceMemory402='1';const reason=card.querySelector('.td331-reason');if(reason&&/Chybí ověřená tržní cena/i.test(reason.textContent||''))reason.textContent=`Aktuální scan cenu nezískal. Zobrazuji poslední známou cenu ${fmt(row.market_price_czk)} (${ageLabel(row.checked_at)} starou); nepoužívám ji pro automatické doporučení.`;return true}
async function render(){const host=document.querySelector('#ticketIntelView');if(!host)return;try{const map=await load();let restored=0;for(const card of host.querySelectorAll('[data-inventory-card]')){const id=card.querySelector('[data-ticket-detail]')?.dataset.ticketDetail;if(!id)continue;if(patchCard(card,map.get(String(id))))restored++}window.__KAMIL_TICKET_PRICE_MEMORY402__={version:VERSION,healthy:true,restored,count:map.size,at:Date.now()};document.documentElement.dataset.ticketPriceMemory402='1';window.dispatchEvent(new CustomEvent('kamil:ticket-price-memory402',{detail:{restored,count:map.size}}))}catch(error){window.__KAMIL_TICKET_PRICE_MEMORY402__={version:VERSION,healthy:false,error:String(error?.message||error),at:Date.now()}}}
function schedule(ms=250){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketPriceMemory402(){if(bound)return;bound=true;const host=document.querySelector('#ticketIntelView');if(host)new MutationObserver(()=>schedule(300)).observe(host,{childList:true,subtree:true});for(const ev of ['kamil:view-change','kamil:ticket-refresh397-done','kamil:ticket-manual398-saved','kamil:ticket-price374-updated'])window.addEventListener(ev,()=>schedule(300));schedule(900);window.__KAMIL_TICKET_PRICE_MEMORY402__={version:VERSION,healthy:true,ready:true,refresh:render,at:Date.now()}}
