import {loadTicketCloud660} from './ticketCloud660.js';

const VERSION=415,N=v=>Number(v||0),ACTIVE=new Set(['LISTED','NOT_LISTED']),SOLD=new Set(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT']);
let bound=false,timer=0,busy=false;
const LIMIT=.30;
const fmt=v=>Number.isFinite(Number(v))?`${Math.round(Number(v)).toLocaleString('cs-CZ')} Kč`:'—';
const pct=v=>Number.isFinite(v)?`${v.toFixed(1)} %`:'—';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const days=iso=>{const t=Date.parse(iso||'');return Number.isFinite(t)?Math.ceil((t-Date.now())/864e5):null};
const buy=r=>N(r.buy_total_czk)||N(r.buy_each_czk)*Math.max(1,N(r.qty)||1);
function groupName(r){let name=String(r.event_name||'Neznámá akce').trim(),sec=String(r.section||'').trim();if(sec){const e=sec.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');name=name.replace(new RegExp(`\\s+-\\s+${e}(?:\\s+-.*)?$`,'i'),'').trim()}if(/^clash\s+17\s+-/i.test(name))return'Clash 17';if(/^asap\s+-/i.test(name))return'ASAP';return name||String(r.event_name||'Neznámá akce')}
function trusted(s,r){const p=N(s?.market_price_czk)||N(s?.viagogo_price_czk)||N(s?.stubhub_price_czk),q=N(s?.multi_market_confidence)||0,pair=Math.max(1,N(r.qty)||1)<=1||s?.quantity_matched===true;return !!p&&q>=65&&pair}
function model(cloud){const active=(cloud.inventory||[]).filter(r=>ACTIVE.has(String(r.market_status||''))),sold=(cloud.inventory||[]).filter(r=>SOLD.has(String(r.market_status||''))),capital=active.reduce((a,r)=>a+buy(r),0),unlisted=active.filter(r=>r.market_status==='NOT_LISTED').reduce((a,r)=>a+buy(r),0),near14=active.filter(r=>{const d=days(r.event_date);return d!==null&&d>=0&&d<=14}).reduce((a,r)=>a+buy(r),0),covered=active.filter(r=>trusted(cloud.latest?.get(r.id),r)).reduce((a,r)=>a+buy(r),0),pairRisk=active.filter(r=>Math.max(1,N(r.qty)||1)>1&&cloud.latest?.get(r.id)?.quantity_matched!==true).reduce((a,r)=>a+buy(r),0),receivable=sold.reduce((a,r)=>a+(N(r.payout_received_czk)||N(r.sell_total_czk)),0),locked=capital+receivable,groups=new Map();for(const r of active){const k=groupName(r),g=groups.get(k)||{name:k,capital:0,tickets:0,rows:0,earliest:null,listed:0,covered:0};const b=buy(r);g.capital+=b;g.tickets+=Math.max(1,N(r.qty)||1);g.rows++;if(r.market_status==='LISTED')g.listed+=b;if(trusted(cloud.latest?.get(r.id),r))g.covered+=b;const d=days(r.event_date);if(d!==null&&(g.earliest===null||d<g.earliest))g.earliest=d;groups.set(k,g)}const eventRows=[...groups.values()].map(g=>({...g,share:capital?g.capital/capital*100:0,coverage:g.capital?g.covered/g.capital*100:0,limit:capital*LIMIT,over:g.capital>capital*LIMIT})).sort((a,b)=>b.capital-a.capital),top=eventRows[0]||null,payoutBuckets={d7:0,d14:0,d30:0,undated:0};for(const r of sold){const amount=N(r.payout_received_czk)||N(r.sell_total_czk),d=days(r.payout_expected_at);if(d===null)payoutBuckets.undated+=amount;else if(d<=7)payoutBuckets.d7+=amount;else if(d<=14)payoutBuckets.d14+=amount;else if(d<=30)payoutBuckets.d30+=amount;else payoutBuckets.undated+=amount}const risk=top&&top.share>=35?'STOP NOVÝM NÁKUPŮM':top&&top.share>=LIMIT*100?'NÁKUPNÍ BRZDA':pairRisk>capital*.35||covered<capital*.45?'DATA RISK':'KAPITÁL OK';return{active,sold,capital,unlisted,near14,covered,pairRisk,receivable,locked,eventRows,top,payoutBuckets,risk}}
function tone(g){return g.share>=35?'bad':g.share>=30?'warn':g.share>=20?'mid':'good'}
function ensureCss(){if(document.querySelector('style[data-cap415]'))return;const s=document.createElement('style');s.dataset.cap415='1';s.textContent=`#ticketIntelView .cap415{margin:0 0 14px;border:1px solid #2f4d60;border-radius:13px;background:#0b1720;color:#dceaf4;overflow:hidden}.cap415-head{display:grid;grid-template-columns:1.25fr repeat(5,1fr);gap:8px;padding:11px 12px}.cap415 span{display:block;font-size:8px;font-weight:800;letter-spacing:.07em;text-transform:uppercase;color:#7999b2}.cap415 b{display:block;margin-top:3px;font-size:13px}.cap415 small{display:block;color:#8298aa;font-size:9px;margin-top:2px}.cap415-events{border-top:1px solid #203746}.cap415-row{display:grid;grid-template-columns:1.4fr .7fr .7fr .8fr .8fr;gap:8px;padding:9px 12px;align-items:center;border-top:1px solid #172b37}.cap415-row:first-child{border-top:0}.cap415-row strong{font-size:10px}.cap415-row .bad{color:#efa2a2}.cap415-row .warn{color:#efca89}.cap415-row .mid{color:#d8d49a}.cap415-row .good{color:#8fd4ad}.cap415-cash{padding:9px 12px;border-top:1px solid #203746;display:flex;gap:7px;flex-wrap:wrap}.cap415-chip{border:1px solid #263f50;border-radius:999px;padding:5px 8px;font-size:9px;color:#9ab0bf}.cap415-note{padding:0 12px 10px;color:#8aa0b1;font-size:9px}@media(max-width:900px){.cap415-head{grid-template-columns:1fr 1fr}.cap415-row{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function eventRow(g){const d=g.earliest===null?'?':g.earliest<0?'po akci':`${g.earliest} d`;return`<div class="cap415-row"><div><strong>${esc(g.name)}</strong><small>${g.tickets} ks · ${g.rows} pozic · nejbližší ${d}</small></div><div><span>EXPOZICE</span><b class="${tone(g)}">${fmt(g.capital)}</b><small>${pct(g.share)} portfolia</small></div><div><span>LIMIT 30 %</span><b>${fmt(g.limit)}</b><small>${g.over?'nad limitem':'rezerva '+fmt(Math.max(0,g.limit-g.capital))}</small></div><div><span>MARKET COVERAGE</span><b>${pct(g.coverage)}</b><small>${fmt(g.covered)} ověřeno</small></div><div><span>VERDIKT</span><b class="${tone(g)}">${g.share>=35?'REDUKOVAT':g.share>=30?'NEPŘIKUPOVAT':g.coverage<50?'DOPLNIT DATA':'OK'}</b></div></div>`}
async function render(){if(busy)return;const host=document.querySelector('#ticketIntelView .td331');if(!host)return;busy=true;try{ensureCss();const cloud=await loadTicketCloud660();if(!cloud?.ok)return;const m=model(cloud);let box=host.querySelector('[data-capital415]');if(!box){box=document.createElement('section');box.dataset.capital415='1';box.className='cap415';const perf=host.querySelector('[data-performance414]');perf?.insertAdjacentElement('afterend',box);if(!box.isConnected){const auto=host.querySelector('[data-ticket-autopilot407]');auto?.insertAdjacentElement('afterend',box)}}const sig=[m.capital,m.unlisted,m.near14,m.covered,m.pairRisk,m.receivable,...m.eventRows.map(g=>`${g.name}:${g.capital}:${g.covered}`)].join('|');if(box.dataset.sig!==sig){box.dataset.sig=sig;const p=m.payoutBuckets,events=m.eventRows.slice(0,8);box.innerHTML=`<div class="cap415-head"><div><span>CAPITAL ALLOCATOR · OS415</span><b>${m.risk}</b><small>${m.top?`${m.top.name} = ${pct(m.top.share)} aktivního kapitálu.`:'Bez aktivních pozic.'}</small></div><div><span>AKTIVNÍ KAPITÁL</span><b>${fmt(m.capital)}</b><small>${m.active.length} pozic</small></div><div><span>RECEIVABLE</span><b>${fmt(m.receivable)}</b><small>prodané, ještě ne cash</small></div><div><span>MARKET COVERAGE</span><b>${m.capital?pct(m.covered/m.capital*100):'—'}</b><small>${fmt(m.covered)} kapitálu</small></div><div><span>NEVYSTAVENO</span><b>${fmt(m.unlisted)}</b><small>${m.capital?pct(m.unlisted/m.capital*100):'—'} aktivního kapitálu</small></div><div><span>PAIR RISK</span><b>${fmt(m.pairRisk)}</b><small>více ks bez potvrzeného páru</small></div></div><div class="cap415-cash"><span class="cap415-chip">Payout ≤7 dní: ${fmt(p.d7)}</span><span class="cap415-chip">8–14 dní: ${fmt(p.d14)}</span><span class="cap415-chip">15–30 dní: ${fmt(p.d30)}</span><span class="cap415-chip">Bez termínu / později: ${fmt(p.undated)}</span><span class="cap415-chip">Do akce ≤14 dní je ${fmt(m.near14)} kapitálu</span></div>${events.length?`<div class="cap415-events">${events.map(eventRow).join('')}</div>`:''}<div class="cap415-note">Limit 30 % je risk guard pro jednu akci. Je to brzda proti koncentraci, ne automatický zákaz obchodu.</div>`}window.__KAMIL_TICKET_CAPITAL415__={version:VERSION,healthy:true,model:m,at:Date.now()};document.documentElement.dataset.ticketCapital415='1'}finally{busy=false}}
function schedule(ms=260){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketCapital415(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-refresh397-done','kamil:ticket-sale408-saved','kamil:ticket-settlement411-saved','kamil:ticket-target410-saved'])window.addEventListener(ev,()=>schedule());new MutationObserver(()=>schedule(360)).observe(document.body,{childList:true,subtree:true});schedule();setTimeout(()=>schedule(),1800)}
