import {loadTicketCloud660} from './ticketCloud660.js';

const VERSION=450,N=v=>Number(v||0);let bound=false,timer=0,busy=false;
const SOLD=new Set(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID']);
const fmt=v=>Number.isFinite(Number(v))?`${Math.round(Number(v)).toLocaleString('cs-CZ')} Kč`:'—';
function actionKey(r){return `${String(r.ticket_id)}|${String(r.recommendation_code||'')}`}
function outcome(ex,inv){const sold=SOLD.has(String(inv?.market_status||'')),profit=sold?N(inv?.sell_total_czk)-N(inv?.buy_total_czk):null,done=ex.action_status==='DONE',ignored=ex.action_status==='IGNORED';let result='OPEN',score=null;if(sold){result=profit>=0?'WIN':'LOSS';score=profit}else if(done){result='PENDING'}else if(ignored){result='IGNORED_OPEN'}return{...ex,event_name:inv?.event_name||ex.ticket_id,sold,profit,result,score}}
function summarize(rows){const resolved=rows.filter(x=>x.sold),done=resolved.filter(x=>x.action_status==='DONE'),ignored=resolved.filter(x=>x.action_status==='IGNORED');const avg=a=>a.length?a.reduce((s,x)=>s+N(x.profit),0)/a.length:null,byCode={};for(const x of resolved){const k=x.recommendation_code||'—',g=byCode[k]||(byCode[k]={code:k,n:0,profit:0,wins:0});g.n++;g.profit+=N(x.profit);if(N(x.profit)>=0)g.wins++}const effectiveness=Object.values(byCode).map(g=>({...g,avg:g.n?g.profit/g.n:0,winRate:g.n?g.wins/g.n:0})).sort((a,b)=>b.avg-a.avg);return{resolved:resolved.length,done:done.length,ignored:ignored.length,doneAvg:avg(done),ignoredAvg:avg(ignored),modelEdge:done.length&&ignored.length?N(avg(done))-N(avg(ignored)):null,effectiveness}}
function ensureCss(){if(document.querySelector('style[data-eo450]'))return;const s=document.createElement('style');s.dataset.eo450='1';s.textContent=`#ticketIntelView .eo450{margin:0 0 12px;border:1px solid #294657;border-radius:11px;background:#091923;color:#dceaf3;padding:9px 11px}.eo450-grid{display:grid;grid-template-columns:1.4fr repeat(4,1fr);gap:8px}.eo450 span{display:block;font-size:8px;font-weight:900;color:#7898ad;text-transform:uppercase}.eo450 b{display:block;margin-top:3px;font-size:11px}.eo450 small{display:block;margin-top:2px;color:#7890a1;font-size:8.5px}.eo450-good{color:#8bd8ad}.eo450-warn{color:#efc17c}@media(max-width:850px){.eo450-grid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function paint(m){ensureCss();const host=document.querySelector('#ticketIntelView [data-ex449-summary]')||document.querySelector('#ticketIntelView .td331');if(!host)return;let box=document.querySelector('#ticketIntelView [data-eo450]');if(!box){box=document.createElement('section');box.dataset.eo450='1';box.className='eo450';host.insertAdjacentElement('afterend',box)}const best=m.effectiveness[0];box.innerHTML=`<div class="eo450-grid"><div><span>EXECUTION OUTCOMES · OS450</span><b>${m.resolved} uzavřených execution rozhodnutí</b><small>Porovnává skutečný výsledek po provedené vs. ignorované akci.</small></div><div><span>DONE AVG</span><b>${fmt(m.doneAvg)}</b></div><div><span>IGNORED AVG</span><b>${fmt(m.ignoredAvg)}</b></div><div><span>USER vs MODEL</span><b class="${N(m.modelEdge)>=0?'eo450-good':'eo450-warn'}">${m.modelEdge===null?'sbírám data':fmt(m.modelEdge)}</b><small>done minus ignored</small></div><div><span>BEST ACTION</span><b>${best?.code||'—'}</b><small>${best?`${Math.round(best.winRate*100)} % win · ${fmt(best.avg)} avg`:'čekám na výsledky'}</small></div></div>`}
async function refresh(){if(busy)return;busy=true;try{const cloud=await loadTicketCloud660(),ex=window.__KAMIL_TICKET_EXECUTION449__?.rows||[];if(!cloud?.ok)return;const inv=new Map((cloud.inventory||[]).map(x=>[String(x.id),x])),rows=ex.map(x=>outcome(x,inv.get(String(x.ticket_id)))),summary=summarize(rows);window.__KAMIL_TICKET_EXECUTION_OUTCOME450__={version:VERSION,healthy:true,rows,...summary,at:Date.now()};document.documentElement.dataset.ticketOutcome450='1';paint(summary);window.dispatchEvent(new CustomEvent('kamil:ticket-outcome450-updated',{detail:{resolved:summary.resolved}}))}finally{busy=false}}
function schedule(ms=600){clearTimeout(timer);timer=setTimeout(refresh,ms)}
export function installTicketExecutionOutcomes450(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-action449-saved','kamil:ticket-reconcile412-saved'])window.addEventListener(ev,()=>schedule());schedule(10500);setInterval(()=>schedule(0),10*60*1000)}
