import {ownEvent1100,ownObserver1100,schedule1100} from './runtimeOwnership1100.js';

const VERSION='505.0.1',OWNER='tickets.anchor505';
let bound=false,resizeObserver=null,observedCommander=null;
const active=()=>!!document.querySelector('#view-tickets.on,#view-tickets.active,[data-view-panel="tickets"].on,[data-view-panel="tickets"].active');
function observeCommander(commander){if(observedCommander===commander)return;resizeObserver?.disconnect();resizeObserver=null;observedCommander=commander||null;if(!commander||typeof ResizeObserver!=='function')return;resizeObserver=new ResizeObserver(()=>schedule(55));ownObserver1100(OWNER,resizeObserver);resizeObserver.observe(commander)}
function clear(side,host){document.documentElement.dataset.ticketAnchor505='mobile';observeCommander(null);host?.style.removeProperty('position');if(!side)return;for(const key of ['position','top','right','left','bottom','width','margin','z-index','transform'])side.style.removeProperty(key)}
function anchor(){if(!active())return false;const host=document.querySelector('#ticketIntelView .td331');if(!host)return false;const commander=host.querySelector(':scope > [data-c465]'),side=host.querySelector('[data-ticket-side500]');if(matchMedia('(max-width:1180px)').matches){clear(side,host);return true}if(!commander||!side)return false;document.documentElement.dataset.ticketAnchor505='1';side.setAttribute('data-focus459','');if(side.parentElement!==host)host.appendChild(side);observeCommander(commander);host.style.setProperty('position','relative','important');side.style.setProperty('position','absolute','important');side.style.setProperty('right','auto','important');side.style.setProperty('bottom','auto','important');side.style.setProperty('margin','0','important');side.style.setProperty('transform','none','important');side.style.setProperty('z-index','20','important');schedule1100(OWNER,'measure',()=>{if(!active()||!host.isConnected||!commander.isConnected||!side.isConnected)return;const parent=side.offsetParent||host,parentRect=parent.getBoundingClientRect(),commanderRect=commander.getBoundingClientRect(),top=Math.max(0,Math.round(commanderRect.bottom-parentRect.top+12)),left=Math.max(0,Math.round(commanderRect.left-parentRect.left)),width=Math.max(300,Math.round(commanderRect.width));side.style.setProperty('top',`${top}px`,'important');side.style.setProperty('left',`${left}px`,'important');side.style.setProperty('width',`${width}px`,'important');host.style.setProperty('--td503-side-top',`${top}px`);host.style.setProperty('--td503-right-width',`${width}px`);host.style.setProperty('--td502-side-offset','0px');window.__KAMIL_TICKET_ANCHOR505__={version:VERSION,healthy:true,top,left,width,offsetParent:parent.id||parent.className||parent.tagName,gap:Math.round(side.getBoundingClientRect().top-commanderRect.bottom),runtimeOwner:OWNER,at:Date.now()}},0,{pauseWhenHidden:true});return true}
function schedule(ms=75){schedule1100(OWNER,'anchor',()=>{if(active())anchor()},ms,{pauseWhenHidden:true})}
export function installTicketAnchor505(){if(bound)return;bound=true;for(const event of ['kamil:view-change','kamil:ticket-desk331-updated','kamil:ticket-boot466-updated','kamil:ticket-commander465-updated','kamil:ticket-risk438-updated','kamil:ticket-refresh397-done'])ownEvent1100(OWNER,window,event,()=>schedule());ownEvent1100(OWNER,window,'resize',()=>schedule(100),{passive:true});const root=document.querySelector('#ticketIntelView');if(root)ownObserver1100(OWNER,root,{childList:true,subtree:true},()=>schedule(70));if(active()){anchor();schedule(160);schedule(520);schedule(1400)}}
