import {loadTicketCloud660} from './ticketCloud660.js';
import {h,money} from './utils.js';
const N=v=>Number(v||0);
const statusLabel=s=>({SOLD_UNDELIVERED:'Doručit',SOLD_WAITING_PAYMENT:'Čeká payout',PAYOUT_RECEIVED:'Vyplaceno',PAID:'Vyplaceno'}[String(s||'').toUpperCase()]||'Prodej');
const fmtDate=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?new Date(t).toLocaleString('cs-CZ',{dateStyle:'medium',timeStyle:'short'}):'—'};
function ensureDrawer(){let wrap=document.querySelector('[data-sale-detail151]');if(wrap)return wrap;wrap=document.createElement('div');wrap.dataset.saleDetail151='1';wrap.className='ts151-wrap';wrap.hidden=true;wrap.innerHTML='<div class="ts151-backdrop" data-ts151-close></div><aside class="ts151-drawer" role="dialog" aria-modal="true" aria-labelledby="ts151-title"><button class="ts151-close" type="button" data-ts151-close aria-label="Zavřít">×</button><div data-ts151-body></div></aside>';document.body.appendChild(wrap);wrap.querySelectorAll('[data-ts151-close]').forEach(x=>x.addEventListener('click',()=>close()));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!wrap.hidden)close()});return wrap}
function close(){const w=document.querySelector('[data-sale-detail151]');if(w)w.hidden=true}
function render(row){const wrap=ensureDrawer(),body=wrap.querySelector('[data-ts151-body]'),buy=N(row.buy_total_czk),sell=N(row.sell_total_czk),pl=sell-buy,roi=buy>0?pl/buy*100:null,qty=Math.max(1,N(row.qty)||1),buyEach=N(row.buy_each_czk)||(buy/qty),sellEach=N(row.sell_each_czk)||(sell/qty);body.innerHTML=`<div class="ts151-eyebrow">SALE DETAIL · ${h(statusLabel(row.market_status))}</div><h2 id="ts151-title">${h(row.event_name||'Událost')}</h2><p class="ts151-meta">${h(row.section||'bez sektoru')} · ${qty} ks${row.event_date?` · ${h(new Date(row.event_date).toLocaleDateString('cs-CZ'))}`:''}</p><div class="ts151-kpis"><article><small>Nákup celkem</small><b>${money(buy)}</b><span>${buyEach?`${money(buyEach)} / ks`:'—'}</span></article><article><small>Prodej celkem</small><b>${money(sell)}</b><span>${sellEach?`${money(sellEach)} / ks`:'—'}</span></article><article><small>Hrubý P/L</small><b class="${pl>=0?'good':'bad'}">${pl>=0?'+':''}${money(pl)}</b><span>${roi===null?'ROI —':`ROI ${roi>=0?'+':''}${roi.toFixed(1)} %`}</span></article></div><section class="ts151-section"><small>WORKFLOW</small><div class="ts151-stage"><b>${h(statusLabel(row.market_status))}</b><span>Poslední známá změna: ${h(fmtDate(row.updated_at))}</span></div></section><section class="ts151-section"><small>ZDROJOVÁ DATA</small><div class="ts151-row"><span>ID</span><b>${h(row.id||'—')}</b></div><div class="ts151-row"><span>Zdroj</span><b>${h(row.source_name||row.source_sheet||'—')}</b></div><div class="ts151-row"><span>Import</span><b>${h(fmtDate(row.imported_at))}</b></div></section><div class="ts151-note">P/L a ROI jsou hrubé z uložené nákupní a prodejní ceny. Poplatky ani skutečný payout zde neodečítám, pokud nejsou uložené jako samostatná ověřená data.</div>`;wrap.hidden=false}
export async function enhanceTicketSaleDetail151(){const host=document.querySelector('#ticketIntelView');if(!host)return;let cloud;try{cloud=await loadTicketCloud660()}catch{return}if(!cloud?.ok)return;const rows=new Map((cloud.inventory||[]).map(x=>[String(x.id),x]));host.querySelectorAll('[data-ticket-sale-detail]').forEach(btn=>{if(btn.dataset.bound151==='1')return;btn.dataset.bound151='1';btn.addEventListener('click',()=>{const row=rows.get(String(btn.dataset.id));if(row)render(row)})});}
export const ticketSaleDetail151Info={grossOnly:true,feeEstimate:false,payoutEstimate:false,historyClaim:'current-row-timestamps-only'};
