import {loadTicketCloud660} from './ticketCloud660.js';
import {scanTicketsFull399} from './ticketScan399.js';
import {ownEvent1100,ownObserver1100,schedule1100} from './runtimeOwnership1100.js';
const VERSION=399,OWNER='tickets.refresh395';let busy=false,bound=false,observing=false,retries=0;
const active=()=>!!document.querySelector('#view-tickets.on,#view-tickets.active,[data-view-panel="tickets"].on,[data-view-panel="tickets"].active');
async function run(btn){if(busy||!active())return;busy=true;const old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Skenuji všechny zdroje…'}try{const cloud=await loadTicketCloud660();if(!cloud?.ok)throw cloud?.error||new Error('Ticket cloud není dostupný');if(!active())return;const out=await scanTicketsFull399(cloud.inventory||[]),d=out?.diagnostics||{};if(!active())return out;window.__KAMIL_TICKET_REFRESH395__={version:VERSION,healthy:true,result:out,at:Date.now()};if(btn)btn.title=`OK: uloženo ${d.savedUsefulSnapshots||0} použitelných cen · sektor ${d.sectionMatched||0} · řada ${d.rowMatched||0}`;window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}));window.dispatchEvent(new CustomEvent('kamil:ticket-refresh399-done',{detail:d}));return out}catch(error){window.__KAMIL_TICKET_REFRESH395__={version:VERSION,healthy:false,error:String(error?.message||error),at:Date.now()};if(btn)btn.title=String(error?.message||error);throw error}finally{busy=false;if(btn){btn.disabled=false;btn.textContent=old||'↻ Obnovit trh'}}}
function wire(){if(!active())return false;const host=document.querySelector('#ticketIntelView');if(!host)return false;const current=host.querySelector('[data-refresh]');if(!current||current.dataset.refresh399==='1')return !!current;const btn=current.cloneNode(true);btn.dataset.refresh399='1';delete btn.dataset.refresh397;delete btn.dataset.refresh395;delete btn.dataset.refresh375;current.replaceWith(btn);return true}
function observe(){if(observing)return true;const host=document.querySelector('#ticketIntelView');if(!host)return false;wire();ownObserver1100(OWNER,host,{childList:true,subtree:true},()=>wire());observing=true;return true}
function attachCadence(){if(observe())return;retries++;if(retries<40)schedule1100(OWNER,'cadence',attachCadence,250,{pauseWhenHidden:true})}
export function installTicketRefresh395(){if(bound)return;bound=true;document.documentElement.dataset.ticketRefresh399='1';ownEvent1100(OWNER,document,'click',e=>{if(!active())return;const btn=e.target?.closest?.('#ticketIntelView [data-refresh399]');if(!btn)return;e.preventDefault();run(btn).catch(error=>console.error('[ticket-refresh399]',error))},true);ownEvent1100(OWNER,window,'kamil:view-change',()=>{if(!active())return;retries=0;schedule1100(OWNER,'wire',()=>{wire();attachCadence()},120,{pauseWhenHidden:true})});attachCadence();window.__KAMIL_TICKET_REFRESH395__={version:VERSION,healthy:true,ready:true,run,at:Date.now()}}
