import {loadTicketCloud660} from './ticketCloud660.js';
import {scanTicketsFull395} from './ticketScan395.js';
import {modal} from './utils.js';

const VERSION=418,N=v=>Number(v||0),ACTIVE=new Set(['LISTED','NOT_LISTED']);let bound=false,timer=0,busy=false,running=false;
const fmt=v=>`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const buy=r=>N(r.buy_total_czk)||N(r.buy_each_czk)*Math.max(1,N(r.qty)||1);
const ageH=s=>{const t=Date.parse(s?.checked_at||'');return Number.isFinite(t)?Math.max(0,(Date.now()-t)/36e5):null};
const days=r=>{const t=Date.parse(r?.event_date||'');return Number.isFinite(t)?Math.ceil((t-Date.now())/864e5):999};
function issues(r,s){const out=[];const price=N(s?.market_price_czk)||N(s?.viagogo_price_czk)||N(s?.stubhub_price_czk),age=ageH(s),q=Math.max(1,N(r.qty)||1),conf=N(s?.multi_market_confidence);if(!r.viagogo_url&&!r.stubhub_url)out.push('CHYBÍ ZDROJ');if(!price)out.push('CHYBÍ CENA');if(price&&age!==null&&age>72)out.push('STARÁ CENA');if(q>1&&s?.quantity_matched!==true)out.push('NEOVĚŘENÝ PÁR');if(price&&conf&&conf<65)out.push('NÍZKÁ CONFIDENCE');if(s?.multi_market_conflict)out.push('KONFLIKT MARKETŮ');return out}
function score(r,iss,total){const cap=total?buy(r)/total*100:0,d=days(r);let s=cap*2;if(d<=3)s+=45;else if(d<=14)s+=25;else if(d<=30)s+=10;if(iss.includes('CHYBÍ CENA'))s+=30;if(iss.includes('CHYBÍ ZDROJ'))s+=25;if(iss.includes('NEOVĚŘENÝ PÁR'))s+=15;if(iss.includes('KONFLIKT MARKETŮ'))s+=20;return Math.round(s)}
function model(cloud){const active=(cloud.inventory||[]).filter(r=>ACTIVE.has(String(r.market_status||''))),total=active.reduce((a,r)=>a+buy(r),0),rows=[];for(const r of active){const s=cloud.latest?.get(r.id),iss=issues(r,s);if(!iss.length)continue;rows.push({r,s,issues:iss,capital:buy(r),d:days(r),score:score(r,iss,total)})}rows.sort((a,b)=>b.score-a.score||b.capital-a.capital);const atRisk=rows.reduce((a,x)=>a+x.capital,0),noPrice=rows.filter(x=>x.issues.includes('CHYBÍ CENA')).length,noSource=rows.filter(x=>x.issues.includes('CHYBÍ ZDROJ')).length,pair=rows.filter(x=>x.issues.includes('NEOVĚŘENÝ PÁR')).length;return{active,total,rows,atRisk,noPrice,noSource,pair}}
function ensureCss(){if(document.querySelector('style[data-rep418]'))return;const s=document.createElement('style');s.dataset.rep418='1';s.textContent=`#ticketIntelView .rep418{margin:0 0 14px;border:1px solid #345269;border-radius:13px;background:#0b1821;color:#dce9f4;overflow:hidden}.rep418-head{display:grid;grid-template-columns:1.5fr repeat(4,1fr);gap:8px;padding:11px 12px}.rep418 span{display:block;font-size:8px;font-weight:800;letter-spacing:.07em;text-transform:uppercase;color:#7c9db5}.rep418 b{display:block;margin-top:3px;font-size:13px}.rep418 small{display:block;color:#8197a8;font-size:9px;margin-top:2px}.rep418-head button,.rep418-row button{border:1px solid #3a5d73;background:#132a39;color:#c9e0ee;border-radius:999px;padding:5px 9px;font-size:9px;font-weight:800;cursor:pointer}.rep418-list{border-top:1px solid #203746}.rep418-row{display:grid;grid-template-columns:1.5fr .7fr 1.3fr auto;gap:9px;align-items:center;padding:9px 12px;border-top:1px solid #172b37}.rep418-row:first-child{border-top:0}.rep418-row strong{font-size:10px}.rep418-tags{display:flex;gap:5px;flex-wrap:wrap}.rep418-tag{border:1px solid #4d4652;border-radius:999px;padding:3px 6px;font-size:8px;color:#e0bcbe}.rep418-score{color:#efcc87}@media(max-width:850px){.rep418-head{grid-template-columns:1fr 1fr}.rep418-row{grid-template-columns:1fr 1fr}.rep418-tags{grid-column:1/-1}}`;document.head.appendChild(s)}
async function repair(rows,button){if(running||!rows.length)return;running=true;const old=button?.textContent;if(button){button.disabled=true;button.textContent='Opravuji…'}try{const out=await scanTicketsFull395(rows.map(x=>x.r));window.dispatchEvent(new CustomEvent('kamil:ticket-repair418-done',{detail:out?.diagnostics||{}}));window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}))}catch(e){await modal('Oprava market dat selhala',`<p>${esc(e?.message||String(e))}</p>`,[{label:'OK',value:null,primary:true}])}finally{running=false;if(button){button.disabled=false;button.textContent=old}}}
function jump(id){const card=document.querySelector(`#ticketIntelView [data-ta407="${CSS.escape(String(id))}"]`)||document.querySelector(`#ticketIntelView [data-ticket-detail="${CSS.escape(String(id))}"]`)?.closest('article');card?.scrollIntoView({behavior:'smooth',block:'center'})}
async function render(){if(busy)return;const host=document.querySelector('#ticketIntelView .td331');if(!host)return;busy=true;try{ensureCss();const cloud=await loadTicketCloud660();if(!cloud?.ok)return;const m=model(cloud);let box=host.querySelector('[data-repair418]');if(!box){box=document.createElement('section');box.dataset.repair418='1';box.className='rep418';const health=host.querySelector('[data-ticket-health397]');health?.insertAdjacentElement('afterend',box);if(!box.isConnected){const hero=host.querySelector('.td331-hero');hero?.insertAdjacentElement('afterend',box)}}const top=m.rows.slice(0,6),sig=top.map(x=>`${x.r.id}:${x.score}:${x.issues.join(',')}:${x.s?.checked_at||''}`).join('|')+`#${m.rows.length}`;if(box.dataset.sig!==sig){box.dataset.sig=sig;box.innerHTML=`<div class="rep418-head"><div><span>DATA REPAIR QUEUE · OS418</span><b>${m.rows.length?`${m.rows.length} položek k opravě`:'MARKET DATA V POŘÁDKU'}</b><small>Řazeno podle kapitálu, času do akce a závažnosti chyby.</small>${m.rows.length?'<button data-repair-top418>Opravit TOP 3</button>':''}</div><div><span>KAPITÁL V RIZIKU</span><b>${fmt(m.atRisk)}</b><small>${m.total?Math.round(m.atRisk/m.total*100):0}% aktivního kapitálu</small></div><div><span>BEZ CENY</span><b>${m.noPrice}</b><small>cílený refresh + search discovery</small></div><div><span>BEZ ZDROJE</span><b>${m.noSource}</b><small>OS417 hledá event URL</small></div><div><span>PÁR NEOVĚŘEN</span><b>${m.pair}</b><small>více vstupenek spolu</small></div></div>${top.length?`<div class="rep418-list">${top.map(x=>`<div class="rep418-row"><div><strong>${esc(x.r.event_name)}</strong><small>${esc(x.r.section||'bez sektoru')} · ${Math.max(1,N(x.r.qty)||1)} ks · ${x.d===999?'?':x.d} dní · ${fmt(x.capital)}</small></div><div><span>PRIORITA</span><b class="rep418-score">${x.score}</b></div><div class="rep418-tags">${x.issues.map(i=>`<span class="rep418-tag">${esc(i)}</span>`).join('')}</div><div><button data-fix418="${esc(x.r.id)}">Opravit</button> <button data-jump418="${esc(x.r.id)}">Karta</button></div></div>`).join('')}</div>`:''}`;const map=new Map(m.rows.map(x=>[String(x.r.id),x]));box.querySelector('[data-repair-top418]')?.addEventListener('click',e=>repair(m.rows.slice(0,3),e.currentTarget));box.querySelectorAll('[data-fix418]').forEach(b=>b.addEventListener('click',()=>{const x=map.get(String(b.dataset.fix418));if(x)repair([x],b)}));box.querySelectorAll('[data-jump418]').forEach(b=>b.addEventListener('click',()=>jump(b.dataset.jump418)))}window.__KAMIL_TICKET_REPAIR418__={version:VERSION,healthy:true,model:m,at:Date.now()};document.documentElement.dataset.ticketRepair418='1'}finally{busy=false}}
function schedule(ms=280){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketRepair418(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-refresh397-done','kamil:ticket-repair418-done','kamil:ticket-manual398-saved','kamil:ticket-clipboard403-saved'])window.addEventListener(ev,()=>schedule());new MutationObserver(()=>schedule(380)).observe(document.body,{childList:true,subtree:true});schedule();setTimeout(()=>schedule(),1600)}
