import {ownEvent1100,ownObserver1100,schedule1100} from './runtimeOwnership1100.js';

const VERSION='503.0.1',OWNER='tickets.rail503';
let bound=false;
const active=()=>!!document.querySelector('#view-tickets.on,#view-tickets.active,[data-view-panel="tickets"].on,[data-view-panel="tickets"].active');
function clearRail(host,side){document.documentElement.dataset.ticketRail503='mobile';host?.style.removeProperty('--td503-side-top');host?.style.removeProperty('--td503-right-width');if(side)for(const key of ['position','top','right','width','margin','z-index'])side.style.removeProperty(key)}
function placeRail(){if(!active())return false;const host=document.querySelector('#ticketIntelView .td331');if(!host)return false;const side=host.querySelector('[data-ticket-side500]');if(matchMedia('(max-width:1180px)').matches){clearRail(host,side);return true}const commander=host.querySelector('[data-c465]');if(!commander||!side)return false;if(side.parentElement!==host)host.appendChild(side);side.setAttribute('data-focus459','');const hostRect=host.getBoundingClientRect(),commanderRect=commander.getBoundingClientRect(),top=Math.max(0,Math.round(commanderRect.bottom-hostRect.top+12)),width=Math.max(300,Math.round(commanderRect.width||360));host.style.setProperty('--td503-side-top',`${top}px`);host.style.setProperty('--td503-right-width',`${width}px`);document.documentElement.dataset.ticketRail503='1';window.__KAMIL_TICKET_RAIL503__={version:VERSION,healthy:true,sideTop:top,rightWidth:width,runtimeOwner:OWNER,at:Date.now()};return true}
function schedule(ms=80){schedule1100(OWNER,'place',()=>{if(active())placeRail()},ms,{pauseWhenHidden:true})}
export function installTicketRail503(){if(bound)return;bound=true;for(const event of ['kamil:view-change','kamil:ticket-desk331-updated','kamil:ticket-boot466-updated','kamil:ticket-commander465-updated','kamil:ticket-risk438-updated','kamil:ticket-refresh397-done'])ownEvent1100(OWNER,window,event,()=>schedule());ownEvent1100(OWNER,window,'resize',()=>schedule(120),{passive:true});const root=document.querySelector('#ticketIntelView');if(root)ownObserver1100(OWNER,root,{childList:true,subtree:true},()=>schedule(90));if(active())placeRail()}
