import {cloudClient,session} from './cloud.js';
import {h,modal,formModal,money} from './utils.js';
import {scoreBuyCandidate674} from './buyRadarScore674.js';
export {scoreBuyCandidate674} from './buyRadarScore674.js';

const TABLE='ticket_buy_candidates';
const daysTo=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?Math.ceil((t-Date.now())/86400000):999};
const date=v=>v?new Date(v).toLocaleString('cs-CZ',{dateStyle:'medium',timeStyle:'short'}):'—';

export async function loadBuyRadar674(){const c=await cloudClient(),sess=await session();if(!c||!sess)return{ok:false,reason:'NO_SESSION',items:[]};const q=await c.from(TABLE).select('*').order('official_sale_start',{ascending:true});return q.error?{ok:false,error:q.error,items:q.data||[]}:{ok:true,items:q.data||[],session:sess}}
export async function updateBuyCandidate674(id,patch={}){const c=await cloudClient(),sess=await session();if(!c||!sess)return{ok:false,reason:'NO_SESSION'};const safe={updated_at:new Date().toISOString()};for(const [a,b] of [['status','status'],['notes','notes'],['sourceUrl','source_url'],['secondarySpreadPct','secondary_spread_pct'],['officialStatus','official_status']])if(a in patch)safe[b]=patch[a]||null;const r=await c.from(TABLE).update(safe).eq('user_id',sess.user.id).eq('id',id);return{ok:!r.error,error:r.error}}
export async function addBuyCandidate674(input){const c=await cloudClient(),sess=await session();if(!c||!sess)return{ok:false,reason:'NO_SESSION'};const id=input.id||`manual-${Date.now()}`,payload={user_id:sess.user.id,id,event_name:String(input.eventName||'').trim(),event_date:input.eventDate||null,venue:input.venue||null,city:input.city||null,source_name:input.sourceName||'Ruční kandidát',source_url:input.sourceUrl||null,official_sale_start:input.saleStart||null,official_price_min_czk:Number(input.priceMin||0)||null,official_price_max_czk:Number(input.priceMax||0)||null,capacity:Number(input.capacity||0)||null,official_status:input.officialStatus||null,extra_dates:Number(input.extraDates||0)||0,secondary_spread_pct:Number(input.secondarySpreadPct||0)||null,status:'NEW',notes:input.notes||null,updated_at:new Date().toISOString()};if(!payload.event_name)return{ok:false,error:new Error('Chybí název akce')};const r=await c.from(TABLE).upsert(payload,{onConflict:'user_id,id'});return{ok:!r.error,error:r.error,id}}

const row=x=>{const s=scoreBuyCandidate674(x),sale=daysTo(x.official_sale_start);return `<article class="card buy674-row"><div class="row"><div><b>${h(x.event_name)}</b><div class="muted">${h(x.city||'')} ${x.venue?`· ${h(x.venue)}`:''}${x.event_date?` · ${h(new Date(`${x.event_date}T12:00:00`).toLocaleDateString('cs-CZ'))}`:''}</div></div><span class="tmw-rec ${s.tone}">${s.label} · ${s.score}/100</span></div><div class="row"><span>Oficiální prodej</span><b>${h(x.official_status||'neověřeno')}${x.official_price_min_czk?` · od ${money(x.official_price_min_czk)}`:''}</b></div><div class="row"><span>Sale start</span><b>${date(x.official_sale_start)}${sale<999?` · ${sale<=0?'běží':sale===1?'zítra':`za ${sale} dní`}`:''}</b></div>${x.secondary_spread_pct?`<div class="row"><span>Secondary spread</span><b>${Math.round(Number(x.secondary_spread_pct)*100)} %</b></div>`:''}<div class="row-actions"><button class="btn" data-buy674-watch="${h(x.id)}">Hlídat</button><button class="btn" data-buy674-skip="${h(x.id)}">Přeskočit</button><button class="btn" data-buy674-bought="${h(x.id)}">Koupil jsem</button></div></article>`};
async function addManual(){const data=await formModal('Přidat kandidáta do Buy Radaru',`<label class="field"><span>Akce</span><input name="eventName" required autofocus></label><label class="field"><span>Datum akce</span><input name="eventDate" type="date"></label><label class="field"><span>Město</span><input name="city"></label><label class="field"><span>Venue</span><input name="venue"></label><label class="field"><span>Začátek oficiálního prodeje</span><input name="saleStart" type="datetime-local"></label><label class="field"><span>Oficiální cena od (Kč)</span><input name="priceMin" type="number" min="0"></label><label class="field"><span>Oficiální zdroj</span><input name="sourceUrl" type="url"></label>`,{submitLabel:'Přidat do radaru'});if(!data)return false;const r=await addBuyCandidate674(data);if(!r.ok)await modal('Buy Radar',`<p>${h(r.error?.message||'Kandidáta se nepodařilo uložit.')}</p>`,[{label:'OK',value:null,primary:true}]);return r.ok}
export async function openTicketBuyRadar674(){const cloud=await loadBuyRadar674();if(!cloud.ok)return modal('Buy Radar 67.4','<p>Buy Radar potřebuje připojený privátní cloud.</p>',[{label:'Zavřít',value:null,primary:true}]);const visible=cloud.items.filter(x=>x.status!=='SKIP'),ranked=visible.map(x=>({...x,_score:scoreBuyCandidate674(x).score})).sort((a,b)=>b._score-a._score||String(a.official_sale_start||'').localeCompare(String(b.official_sale_start||'')));const body=`<div class="card"><div class="eyebrow">BUY RADAR 67.4</div><h2>Co stojí za prověření před nákupem</h2><div class="row"><span>Kandidáti</span><b>${ranked.length}</b></div><div class="row"><span>Score 80+</span><b>${ranked.filter(x=>x._score>=80).length}</b></div><p class="muted">Radar pouze doporučuje a eviduje. Nikdy sám nenakupuje vstupenky ani neodesílá objednávku.</p></div>${ranked.map(row).join('')||'<div class="card"><div class="empty">Zatím žádný kandidát.</div></div>'}`;const choice=await modal('Ticket Buy Radar',body,[{label:'Přidat kandidáta',value:'add',primary:true},{label:'Zavřít',value:null}]);if(choice==='add'){if(await addManual())return openTicketBuyRadar674()};return choice}
let bound=false;export function bindTicketBuyRadar674(){if(bound)return;bound=true;document.addEventListener('click',async e=>{const b=e.target.closest?.('[data-buy674-watch],[data-buy674-skip],[data-buy674-bought]');if(!b)return;const id=b.dataset.buy674Watch||b.dataset.buy674Skip||b.dataset.buy674Bought,status=b.dataset.buy674Watch?'WATCH':b.dataset.buy674Skip?'SKIP':'BOUGHT';b.disabled=true;const r=await updateBuyCandidate674(id,{status});if(r.ok){b.textContent=status==='WATCH'?'Hlídám':status==='SKIP'?'Přeskočeno':'Zapsáno jako koupené'}else b.disabled=false})}
