import {cloudClient,session} from './cloud.js';
const VERSION=461;let bound=false,timer=0,busy=false;const now=()=>Date.now(),iso=t=>new Date(t).toISOString();
async function ctx(){const c=await cloudClient(),s=await session();if(!c||!s)throw new Error('Cloud session chybí.');return{c,s}}
function sla(bucket){const n=now();if(bucket==='UDĚLEJ TEĎ')return n+2*36e5;if(bucket==='UDĚLEJ DNES'){const d=new Date();d.setHours(20,0,0,0);return d.getTime()>n?d.getTime():n+4*36e5}return n+24*36e5}
function mapRows(){const c=window.__KAMIL_TICKET_COMMANDER454__;return (c?.rows||[]).map(x=>({id:String(x.id),code:x.commander5?.code||x.finalCode||'—',bucket:x.commander5?.bucket||'SLEDUJ',title:x.title||x.r?.event_name||x.id,score:Number(x.commander5?.score||0)}))}
async function save(id,code,patch){const {c,s}=await ctx();const ex=window.__KAMIL_TICKET_EXECUTION449__?.rows||[],cur=ex.find(r=>String(r.ticket_id)===id&&String(r.recommendation_code)===code);const base={user_id:s.user.id,ticket_id:id,recommendation_code:code,model_version:'461',...patch};let error;if(cur?.id)({error}=await c.from('ticket_action_executions').update(base).eq('id',cur.id).eq('user_id',s.user.id));else({error}=await c.from('ticket_action_executions').insert(base));if(error)throw error;window.dispatchEvent(new CustomEvent('kamil:ticket-action449-saved',{detail:{ticketId:id,code}}));}
function ensureCss(){if(document.querySelector('style[data-w461]'))return;const s=document.createElement('style');s.dataset.w461='1';s.textContent=`#ticketIntelView .w461{margin:0 0 6px;padding:7px 9px;border:1px solid #2d4657;border-radius:9px;background:#0a1821;color:#dce8f1;display:flex;gap:10px;align-items:center;flex-wrap:wrap}.w461 span{font-size:8px;font-weight:900;color:#7898ad;text-transform:uppercase}.w461 b{font-size:10px}.w461-over{color:#ff9aa5}.w461 button{border:1px solid #35566b;border-radius:7px;background:#102735;color:#cce0ec;padding:4px 7px;font-size:8px;font-weight:900;cursor:pointer}`;document.head.appendChild(s)}
async function refresh(){if(busy)return;busy=true;try{ensureCss();const {c,s}=await ctx();const {data,error}=await c.from('ticket_action_executions').select('id,ticket_id,recommendation_code,action_status,due_at,snoozed_until,ignore_reason,note,next_check_at,created_at,acted_at').eq('user_id',s.user.id).order('created_at',{ascending:false}).limit(400);if(error)throw error;const latest=new Map();for(const r of data||[]){const k=`${r.ticket_id}|${r.recommendation_code}`;if(!latest.has(k))latest.set(k,r)}const rows=mapRows().map(x=>{const e=latest.get(`${x.id}|${x.code}`);const due=e?.due_at?Date.parse(e.due_at):sla(x.bucket),snooze=e?.snoozed_until?Date.parse(e.snoozed_until):0,active=!['DONE','IGNORED','CANCELLED'].includes(e?.action_status||'RECOMMENDED'),overdue=active&&due<now()&&snooze<=now();return{...x,execution:e||null,due,overdue,snoozed:snooze>now()}}).sort((a,b)=>Number(b.overdue)-Number(a.overdue)||b.score-a.score);window.__KAMIL_TICKET_WORKFLOW461__={version:VERSION,healthy:true,rows,overdue:rows.filter(x=>x.overdue).length,at:now()};document.documentElement.dataset.ticketWorkflow461='1';const host=document.querySelector('#ticketIntelView .td331');if(host){let box=host.querySelector('[data-w461]');if(!box){box=document.createElement('section');box.dataset.w461='1';box.className='w461';host.querySelector('[data-inbox460]')?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.querySelector('[data-focus459]')?.insertAdjacentElement('beforebegin',box)}if(box)box.innerHTML=`<span>ACTION SLA · OS461</span><b class="${rows.some(x=>x.overdue)?'w461-over':''}">${rows.filter(x=>x.overdue).length} po termínu</b><span>${rows.filter(x=>x.snoozed).length} odloženo</span><span>${rows.filter(x=>x.execution?.note).length} s poznámkou</span>`}window.dispatchEvent(new CustomEvent('kamil:ticket-workflow461-updated',{detail:{overdue:rows.filter(x=>x.overdue).length}}))}catch(e){window.__KAMIL_TICKET_WORKFLOW461__={version:VERSION,healthy:false,error:String(e?.message||e),at:now()}}finally{busy=false}}
export async function setTicketActionMeta461(id,code,kind,value){if(kind==='DUE')await save(id,code,{due_at:value});if(kind==='SNOOZE'){const t=value==='2H'?now()+2*36e5:value==='EVENING'?(()=>{const d=new Date();d.setHours(19,0,0,0);return d.getTime()>now()?d.getTime():now()+2*36e5})():now()+24*36e5;await save(id,code,{snoozed_until:iso(t)})}if(kind==='IGNORE')await save(id,code,{action_status:'IGNORED',acted_at:iso(now()),ignore_reason:String(value||'bez důvodu')});if(kind==='NOTE')await save(id,code,{note:String(value||'')});if(kind==='NEXT')await save(id,code,{next_check_at:value});refresh()}
function schedule(ms=150){clearTimeout(timer);timer=setTimeout(refresh,ms)}
export function installTicketWorkflow461(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-commander454-updated','kamil:ticket-action449-saved'])window.addEventListener(ev,()=>schedule());schedule(1800)}
