const n=x=>Number(x||0);
const clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,x));
const active=s=>['LISTED','NOT_LISTED'].includes(s);
const sold=s=>['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAID'].includes(s);
const daysTo=d=>{if(!d)return 999;const x=new Date(`${String(d).slice(0,10)}T12:00:00`);return Math.ceil((x-Date.now())/86400000)};
const pct=(a,b)=>b?((a/b)-1):0;
const latest=(cloud,id)=>cloud.latest?.get(id)||null;
const history=(cloud,id)=>cloud.history?.get(id)||[];

export function sellThroughVelocity671(cloud,row){
 const h=history(cloud,row.id).filter(x=>n(x.market_price_czk)||n(x.competitor_count)).slice(0,8),cur=latest(cloud,row.id);if(!cur)return{score:0,label:'bez dat'};
 const old=h[h.length-1]||cur,compNow=n(cur.competitor_count),compOld=n(old.competitor_count),priceNow=n(cur.market_price_czk),priceOld=n(old.market_price_czk);
 let score=50;if(compOld&&compNow<compOld)score+=Math.min(25,(compOld-compNow)*5);if(compOld&&compNow>compOld)score-=Math.min(25,(compNow-compOld)*4);if(priceOld&&priceNow>priceOld)score+=Math.min(20,pct(priceNow,priceOld)*100);if(priceOld&&priceNow<priceOld)score-=Math.min(20,Math.abs(pct(priceNow,priceOld))*100);if(cur.official_status==='SOLD_OUT')score+=15;if(cur.official_status==='LOW_STOCK')score+=7;if(cur.official_status==='AVAILABLE')score-=10;
 score=Math.round(clamp(score));return{score,label:score>=70?'rychle mizí':score<=35?'nabídka roste':'stabilní',competitorDelta:compOld?compNow-compOld:null,priceDelta:priceOld?pct(priceNow,priceOld):null};
}
export function officialSpread671(snap){const sec=n(snap?.market_price_czk),off=n(snap?.official_price_czk);return sec&&off?{czk:sec-off,pct:sec/off-1}:null}
export function ticketRisk671(cloud,row){const s=latest(cloud,row.id)||{},d=daysTo(row.event_date),v=sellThroughVelocity671(cloud,row),buy=n(row.buy_each_czk),ask=n(row.ask_each_czk)||n(s.recommended_ask_czk)||n(s.market_price_czk);let risk=25;if(d<=7)risk+=35;else if(d<=21)risk+=22;else if(d<=45)risk+=10;if(['AVAILABLE','LOW_STOCK'].includes(s.official_status))risk+=18;if(s.official_status==='SOLD_OUT')risk-=12;if(v.score<=35)risk+=18;if(v.score>=70)risk-=12;if(b&&ask&&ask<buy)risk+=20;if(n(s.competitor_count)>=10)risk+=12;if(n(row.qty)>=4)risk+=8;risk=Math.round(clamp(risk));return{score:risk,label:risk>=75?'vysoké':risk>=50?'střední':'nízké',days:d,velocity:v}}
export function capitalCommander671(cloud,target=30000){const rows=cloud.inventory.filter(x=>active(x.market_status)).map(row=>{const s=latest(cloud,row.id)||{},r=ticketRisk671(cloud,row),market=n(s.recommended_ask_czk)||n(s.market_price_czk)||n(row.ask_each_czk)||n(row.buy_each_czk),qty=n(row.qty)||1;return{row,s,risk:r,liquidity:market*qty,score:r.score+(s.recommendation_code==='LOWER'?15:0)+(s.recommendation_code==='OFFICIAL_COMPETITION'?15:0)}}).sort((a,b)=>b.score-a.score);let freed=0;const picks=[];for(const x of rows){if(freed>=target)break;picks.push(x);freed+=x.liquidity}return{target,freed,picks,locked:rows.reduce((a,x)=>a+n(x.row.buy_total_czk),0)}}
export function fulfillmentCommander671(cloud){const deliver=cloud.inventory.filter(x=>x.market_status==='SOLD_UNDELIVERED'),payout=cloud.inventory.filter(x=>x.market_status==='SOLD_WAITING_PAYMENT');return{deliver,deliverQty:deliver.reduce((a,x)=>a+n(x.qty),0),payout,payoutQty:payout.reduce((a,x)=>a+n(x.qty),0),payoutCzk:payout.reduce((a,x)=>a+n(x.sell_total_czk),0)}}
export function profitReality671(row,snap,{sellerFeePct=0,fxCostPct=0}={}){const qty=n(row.qty)||1,buy=n(row.buy_total_czk)||n(row.buy_each_czk)*qty,sell=n(row.sell_total_czk)||(n(snap?.recommended_ask_czk)||n(snap?.market_price_czk))*qty;if(!buy||!sell)return null;const fees=sell*(n(sellerFeePct)+n(fxCostPct))/100,net=sell-fees-buy;return{buy,sell,fees,net,roi:net/buy}}
export function oneDailyDecision671(cloud){const activeRows=cloud.inventory.filter(x=>active(x.market_status)).map(row=>({row,s:latest(cloud,row.id)||{},risk:ticketRisk671(cloud,row)}));activeRows.sort((a,b)=>{const pa=x=>x.s.recommendation_code==='OFFICIAL_COMPETITION'?100:x.s.recommendation_code==='LOWER'?90:x.s.recommendation_code==='LIST'?75:x.s.recommendation_code==='RAISE'?55:20;return (pa(b)+b.risk.score)-(pa(a)+a.risk.score)});const x=activeRows[0];if(!x)return null;return{event:x.row.event_name,code:x.s.recommendation_code||'HOLD',label:x.s.recommendation_label||'DRŽET',reason:x.s.recommendation_reason||`Riziko ${x.risk.score}/100`,risk:x.risk.score}}
export function opportunityScore671(event={}){let score=50;if(event.officialSoldOut)score+=20;if(event.lowStock)score+=10;if(n(event.capacity)&&n(event.capacity)<8000)score+=8;if(n(event.secondarySpreadPct)>.25)score+=15;if(n(event.secondarySpreadPct)<.05)score-=15;if(n(event.extraDates)>=2)score-=12;if(n(event.daysToSale)<=2)score+=5;return Math.round(clamp(score))}
export function learningSummary671(history=[]){const sold=history.filter(x=>sold(x.marketStatus||x.market_status||x.workflow));const rows=sold.map(x=>{const buy=n(x.buy||x.buy_total_czk),sell=n(x.sell||x.sell_total_czk);return{...x,profit:sell-buy,roi:buy?(sell-buy)/buy:null}});const profitable=rows.filter(x=>x.profit>0);return{count:rows.length,profitable:profitable.length,profit:rows.reduce((a,x)=>a+x.profit,0),avgRoi:rows.filter(x=>x.roi!==null).length?rows.reduce((a,x)=>a+(x.roi||0),0)/rows.filter(x=>x.roi!==null).length:null}}
