const VERSION=464,N=v=>Number(v||0),clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));let bound=false,timer=0;
function norm(s=''){return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function marketplaceId(r){const urls=[r.viagogo_url,r.stubhub_url,r.official_url].filter(Boolean);for(const u of urls){const s=String(u),m=s.match(/(?:E-|event\/|event-)(\d{6,})/i)||s.match(/[?&](?:eventId|event_id)=(\d{6,})/i);if(m)return m[1]}return null}
function eventKey(r){const id=marketplaceId(r);if(id)return`event:${id}`;const d=String(r.event_date||'').slice(0,10);return`fallback:${norm(r.event_name)}|${d}`}
function rowScore(r){const row=norm(r.row_label||r.row||'');if(!row)return 0;if(/standing|general admission|stani/.test(row))return 2;const m=row.match(/(?:row|rada)?\s*(\d{1,3})/),n=m?Number(m[1]):NaN;if(!Number.isFinite(n))return 0;if(n<=5)return 12;if(n<=12)return 7;if(n<=25)return 2;if(n>=50)return-5;return 0}
function comparableScore(m){const s=m.best?.s||{};let q=0;if(N(s.same_row_count)>=2)q+=10;else if(N(s.same_section_count)>=3)q+=6;if(s.quantity_matched===true)q+=5;else if(N(s.quantity_required)>1&&s.quantity_matched===false)q-=8;if(N(s.competitor_count)>=4)q+=4;return q}
function quantityPlan(m){const q=Math.max(1,N(m.r.qty)||1),paired=m.best?.s?.quantity_matched===true,liq=N(m.liquidity?.score);if(q>=4){if(paired&&liq>=65)return'4 spolu';if(liq>=45)return'2 + 2';return'1 + 1 + 1 + 1'}if(q===3)return liq>=60?'3 spolu':'2 + 1';if(q===2)return paired?'2 spolu':'1 + 1';return'1 ks'}
function demandWindow(m){const d=N(m.days),liq=N(m.liquidity?.score),mom=N(m.momentum?.score);if(d<=3)return'vrchol poptávky nyní';if(d<=7)return liq>=55?'silnější okno 48–72 h':'čekat jen s kontrolou';if(d<=14)return mom>=50?'pravděpodobný růst zájmu 5–9 d':'nejisté, hlídat trend';return'časná fáze · likvidita může růst'}
function median(a){const x=a.filter(v=>Number.isFinite(v)&&v>0).sort((a,b)=>a-b);if(!x.length)return 0;const i=Math.floor(x.length/2);return x.length%2?x[i]:(x[i-1]+x[i])/2}
function build(){const eng=window.__KAMIL_TICKET_ENGINE426__;if(!eng?.models)return{rows:[],events:[]};const groups=new Map();for(const m of eng.models){const k=eventKey(m.r),a=groups.get(k)||[];a.push(m);groups.set(k,a)}const rows=[];for(const [k,models] of groups){const med=median(models.map(m=>N(m.market)));for(const m of models){const market=N(m.market),relative=med&&market?clamp((market/med-1)*100,-25,25):0,seatQuality=clamp(50+rowScore(m.r)+comparableScore(m)+relative*.6),premium=(seatQuality-50)*.2;rows.push({id:String(m.r.id),eventKey:k,r:m.r,quantityPlan:quantityPlan(m),seatQuality,seatPremiumPct:premium,relativeMarketPct:relative,liquidityForecast:demandWindow(m),market,score:N(m.liquidity?.score)+N(m.momentum?.score)*.35+premium})}}
const events=[];for(const [k,models] of groups){const rr=rows.filter(x=>x.eventKey===k),first=models[0]?.r||{};events.push({key:k,name:first.event_name||'Event',date:first.event_date||null,positions:rr.length,tickets:rr.reduce((a,x)=>a+Math.max(1,N(x.r.qty)||1),0),capital:rr.reduce((a,x)=>a+N(x.r.buy_total_czk),0),score:rr.reduce((a,x)=>Math.max(a,x.score),0),plans:rr.map(x=>x.quantityPlan),marketplaceId:marketplaceId(first)})}events.sort((a,b)=>b.capital-a.capital);return{rows,events}}
function ensureCss(){if(document.querySelector('style[data-es464]'))return;const s=document.createElement('style');s.dataset.es464='1';s.textContent=`#ticketIntelView .es464{margin:0 0 6px;padding:7px 9px;border:1px solid #2c4759;border-radius:9px;background:#0a1923;color:#dce9f2;display:flex;gap:12px;align-items:center;flex-wrap:wrap}.es464 span{font-size:8px;font-weight:900;color:#7898ad;text-transform:uppercase}.es464 b{font-size:10px}`;document.head.appendChild(s)}
function render(){ensureCss();const m=build();window.__KAMIL_TICKET_EVENT_STRATEGY464__={version:VERSION,healthy:true,eventKeyVersion:'466',...m,at:Date.now()};document.documentElement.dataset.ticketEventStrategy464='1';const host=document.querySelector('#ticketIntelView .td331');if(!host)return;let box=host.querySelector('[data-es464]');if(!box){box=document.createElement('section');box.dataset.es464='1';box.className='es464';host.appendChild(box)}const split=m.rows.filter(x=>/\+/.test(x.quantityPlan)).length,hi=m.rows.filter(x=>x.seatQuality>=65).length,ids=m.events.filter(x=>x.marketplaceId).length;box.innerHTML=`<span>EVENT STRATEGY</span><b>${m.events.length} eventů</b><b>${ids} s marketplace ID</b><b>${split} split strategií</b><b>${hi} relative-premium pozic</b>`;window.dispatchEvent(new CustomEvent('kamil:ticket-event464-updated',{detail:{events:m.events.length}}))}
function schedule(ms=180){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketEventStrategy464(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-engine426-updated','kamil:ticket-cadence463-updated'])window.addEventListener(ev,()=>schedule());schedule(3800)}
