const VERSION=431;
let bound=false,timer=0;
const N=v=>Number(v||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ensureCss(){if(document.querySelector('style[data-eh431]'))return;const s=document.createElement('style');s.dataset.eh431='1';s.textContent=`
#ticketIntelView .eh431{margin:0 0 10px;border:1px solid #284557;border-radius:11px;background:#0a1822;color:#dce9f2;overflow:hidden}
#ticketIntelView .eh431-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 12px}
#ticketIntelView .eh431-title span{display:block;font-size:8px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;color:#7899b2}
#ticketIntelView .eh431-title b{display:block;margin-top:3px;font-size:11px}
#ticketIntelView .eh431-title small{display:block;margin-top:2px;font-size:8.5px;color:#7d91a2}
#ticketIntelView .eh431-metrics{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}
#ticketIntelView .eh431-chip{display:inline-flex;align-items:center;min-height:24px;padding:0 8px;border:1px solid #2d4a5e;border-radius:999px;background:#0e202c;color:#a6bdd0;font-size:8px;font-weight:850}
#ticketIntelView .eh431-chip.good{border-color:#2c5a46;background:#10251d;color:#8ed9ae}
#ticketIntelView .eh431-chip.warn{border-color:#614d29;background:#2d2415;color:#efc278}
#ticketIntelView .eh431-chip.bad{border-color:#60343d;background:#2c181d;color:#f29aa4}
#ticketIntelView .eh431-details{display:none;padding:8px 12px 10px;border-top:1px solid #203746}
#ticketIntelView .eh431.open .eh431-details{display:block}
#ticketIntelView .eh431-row{display:grid;grid-template-columns:minmax(180px,1.4fr) repeat(3,minmax(80px,.5fr));gap:8px;padding:5px 0;font-size:8.5px;color:#8ea3b4}
#ticketIntelView .eh431-row b{color:#d9e6ef;font-size:8.5px}
#ticketIntelView .eh431-actions{display:flex;gap:6px;margin-top:7px}
#ticketIntelView .eh431 button{min-height:29px;padding:0 9px;border:1px solid #35566c;border-radius:8px;background:#112735;color:#c7ddea;font-size:8.5px;font-weight:850;cursor:pointer}
@media(max-width:760px){#ticketIntelView .eh431-head{align-items:flex-start;flex-direction:column}#ticketIntelView .eh431-metrics{justify-content:flex-start}#ticketIntelView .eh431-row{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(s)}
function host(){return document.querySelector('#ticketIntelView .td331')}
function ensureBox(root){let el=root.querySelector('[data-engine-health431]');if(el)return el;el=document.createElement('section');el.className='eh431';el.dataset.engineHealth431='1';const brief=root.querySelector('[data-daily-brief419]');const hub=root.querySelector('[data-ticket-hub421]');if(brief)brief.insertAdjacentElement('afterend',el);else if(hub)hub.insertAdjacentElement('beforebegin',el);else root.prepend(el);return el}
function ageLabel(h){if(h===null||h===undefined)return'—';if(h<1)return'<1 h';if(h<24)return`${Math.round(h)} h`;return`${Math.round(h/24)} d`}
function analyze(){const engine=window.__KAMIL_TICKET_ENGINE426__,cards=[...document.querySelectorAll('#ticketIntelView [data-inventory-card]')],models=Array.isArray(engine?.models)?engine.models:[],byId=new Map(models.map(m=>[String(m?.r?.id),m])),rows=[];let painted=0,priced=0,goodConf=0,stale=0,errors=0;for(const card of cards){const id=card.querySelector('[data-ticket-detail]')?.dataset.ticketDetail||'',m=byId.get(String(id));const okPaint=card.dataset.engine427==='1';if(okPaint)painted++;if(m?.market)priced++;if(N(m?.confidence)>=65)goodConf++;if(m?.best?.age>72)stale++;if(!m)errors++;rows.push({id,name:card.querySelector('h3')?.textContent?.trim()||id,model:!!m,painted:okPaint,market:N(m?.market),confidence:N(m?.confidence),age:m?.best?.age??null,code:m?.code||'—'})}const total=cards.length,coverage=total?Math.round(models.filter(m=>cards.some(c=>String(c.querySelector('[data-ticket-detail]')?.dataset.ticketDetail)===String(m?.r?.id))).length/total*100):0,paintCoverage=total?Math.round(painted/total*100):0,priceCoverage=total?Math.round(priced/total*100):0,confCoverage=total?Math.round(goodConf/total*100):0;const healthy=total>0&&coverage===100&&paintCoverage===100&&errors===0;return{engine,total,models:models.length,coverage,paintCoverage,priceCoverage,confCoverage,stale,errors,healthy,rows}}
function render(){const root=host();if(!root)return;ensureCss();const d=analyze(),el=ensureBox(root),tone=d.healthy?'good':d.coverage<80||d.errors?'bad':'warn',status=d.healthy?'ENGINE OK':d.engine?.models?.length?'ENGINE ČÁSTEČNÝ':'ENGINE ČEKÁ';el.innerHTML=`<div class="eh431-head"><div class="eh431-title"><span>ENGINE HEALTH · OS431</span><b class="${tone}">${status}</b><small>${d.total} aktivních karet · ${d.models} modelů · canonical writer OS426/427</small></div><div class="eh431-metrics"><span class="eh431-chip ${d.coverage===100?'good':d.coverage<80?'bad':'warn'}">model ${d.coverage}%</span><span class="eh431-chip ${d.paintCoverage===100?'good':d.paintCoverage<80?'bad':'warn'}">UI ${d.paintCoverage}%</span><span class="eh431-chip ${d.priceCoverage>=80?'good':'warn'}">cena ${d.priceCoverage}%</span><span class="eh431-chip ${d.confCoverage>=70?'good':'warn'}">conf≥65 ${d.confCoverage}%</span>${d.stale?`<span class="eh431-chip warn">stará data ${d.stale}</span>`:''}${d.errors?`<span class="eh431-chip bad">bez modelu ${d.errors}</span>`:''}</div></div><div class="eh431-details">${d.rows.slice(0,20).map(r=>`<div class="eh431-row"><b>${esc(r.name)}</b><span>${r.model?'model ✓':'model ✕'}</span><span>${r.market?`${Math.round(r.market).toLocaleString('cs-CZ')} Kč`:'bez ceny'}</span><span>${r.confidence?`conf ${r.confidence}% · ${ageLabel(r.age)}`:r.code}</span></div>`).join('')}<div class="eh431-actions"><button data-eh431-toggle>Skrýt detail</button><button data-eh431-recalc>Přepočítat</button></div></div>`;el.classList.toggle('open',el.dataset.open431==='1');const head=el.querySelector('.eh431-head');head?.addEventListener('click',()=>{el.dataset.open431=el.dataset.open431==='1'?'0':'1';el.classList.toggle('open',el.dataset.open431==='1')});el.querySelector('[data-eh431-toggle]')?.addEventListener('click',e=>{e.stopPropagation();el.dataset.open431='0';el.classList.remove('open')});el.querySelector('[data-eh431-recalc]')?.addEventListener('click',e=>{e.stopPropagation();window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}));window.dispatchEvent(new CustomEvent('kamil:ticket-refresh397-done',{detail:{source:'health431'}}));schedule(1200)});document.documentElement.dataset.ticketEngineHealth431='1';window.__KAMIL_TICKET_ENGINE_HEALTH431__={version:VERSION,...d,at:Date.now()}}
function schedule(ms=240){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketEngineHealth431(){if(bound)return;bound=true;ensureCss();for(const ev of ['kamil:view-change','kamil:ticket-refresh397-done','kamil:ticket-price374-updated','kamil:ticket-reconcile412-saved'])window.addEventListener(ev,()=>schedule(700));const h=document.querySelector('#ticketIntelView');if(h)new MutationObserver(()=>schedule(450)).observe(h,{childList:true,subtree:true});schedule(2300);setInterval(()=>schedule(0),10000)}