import {loadTicketCloud660} from './ticketCloud660.js';

const VERSION=433,N=v=>Number(v||0),clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));let bound=false,timer=0,busy=false;
const sigmoid=x=>1/(1+Math.exp(-x));
const fmt=v=>Number.isFinite(Number(v))?`${Math.round(Number(v)).toLocaleString('cs-CZ')} Kč`:'—';
const pct=v=>Number.isFinite(Number(v))?`${v>=0?'+':''}${Number(v).toFixed(1)} %`:'—';
const daysHeld=r=>{const t=Date.parse(r?.imported_at||r?.created_at||'');return Number.isFinite(t)?Math.max(1,(Date.now()-t)/864e5):30};
function sellProb(m,price,hours=72){if(!m?.market||!price)return 0;const rel=price/m.market,liq=N(m.liquidity?.score)/100,conf=N(m.confidence)/100,pressure=N(m.pressure)/100,mom=(N(m.momentum?.score)-50)/50,time=Math.log1p(hours)/Math.log(169);const x=-.9+(1.75*(1-rel))+(1.35*liq)+(.55*conf)+(.7*pressure)+(.3*mom)+(.9*time);return clamp(sigmoid(x),.02,.98)}
function demandScore(m){const p72=sellProb(m,m.market,72);return Math.round(clamp(.42*(N(m.liquidity?.score)/100)+.28*p72+.16*(N(m.pressure)/100)+.14*(N(m.momentum?.score)/100))*100)}
function elasticity(m){if(!m?.market)return{p0:0,p2:0,p5:0,p10:0,e2:0,e5:0,e10:0};const p0=sellProb(m,m.market,72),p2=sellProb(m,m.market*.98,72),p5=sellProb(m,m.market*.95,72),p10=sellProb(m,m.market*.90,72);return{p0,p2,p5,p10,e2:p2-p0,e5:p5-p0,e10:p10-p0}}
function evAt(m,price,hours=72){const q=Math.max(1,N(m.r?.qty)||1),buy=N(m.r?.buy_total_czk)||N(m.r?.buy_each_czk)*q,fee=N(m.fee?.rate)||.15,p=sellProb(m,price,hours),net=price*q*(1-fee)-buy,unsoldPenalty=Math.max(0,buy*.025*(hours/168));return{price,p,profit:net,ev:p*net-(1-p)*unsoldPenalty}}
function optimum(m){if(!m?.market)return{price:0,ev:0,p:0,grid:[]};const lo=Math.max(N(m.emergency)||0,m.market*.84),hi=Math.max(lo,m.market*1.12),grid=[];for(let i=0;i<=14;i++){const price=Math.round((lo+(hi-lo)*i/14)/10)*10;grid.push(evAt(m,price,72))}grid.sort((a,b)=>b.ev-a.ev);return{...grid[0],grid:grid.sort((a,b)=>a.price-b.price)}}
function riskAdjusted(m,opt){const base=N(m.r?.buy_total_czk)||N(m.r?.buy_each_czk)*Math.max(1,N(m.r?.qty)||1);if(!base)return null;const risk=(100-N(m.confidence))/100*.35+(100-N(m.liquidity?.score))/100*.35+N(m.pressure)/100*.30;return (opt.ev/base*100)*(1-.55*risk)}
function modelOne(m){const opt=optimum(m),el=elasticity(m),demand=demandScore(m),held=daysHeld(m.r),capital=N(m.r?.buy_total_czk)||N(m.r?.buy_each_czk)*Math.max(1,N(m.r?.qty)||1),ra=riskAdjusted(m,opt),eff=capital?opt.ev/capital*1000/Math.max(1,held):null,timeWeighted=capital&&opt.ev>0?(opt.ev/capital*365/held*100):null,opp=held>45&&eff!==null&&eff<2,base72=sellProb(m,N(m.r?.ask_each_czk)||m.market,72);return{...m,predict:{demand,p24:sellProb(m,N(m.r?.ask_each_czk)||m.market,24),p72:base72,p7:sellProb(m,N(m.r?.ask_each_czk)||m.market,168),elasticity:el,opt,riskAdjustedRoi:ra,capitalEfficiency:eff,timeWeightedRoi:timeWeighted,opportunityCost:opp,heldDays:held}}}
function comparableKey(name=''){const s=String(name).toLowerCase();if(/sparta.*slavia|slavia.*sparta/.test(s))return'pražské derby';if(/davis cup/.test(s))return'davis cup';if(/clash/.test(s))return'clash';if(/asap|katseye|iheart/.test(s))return'koncert';if(/sparta|slavia|jablonec|teplice|fotbal/.test(s))return'fotbal';return'ostatní'}
function comparableStats(cloud,models){const groups=new Map();for(const r of cloud.inventory||[]){const k=comparableKey(r.event_name),g=groups.get(k)||{n:0,profit:0,capital:0};if(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID'].includes(String(r.market_status||''))){g.n++;g.profit+=N(r.sell_total_czk)-N(r.buy_total_czk);g.capital+=N(r.buy_total_czk)}groups.set(k,g)}return Object.fromEntries([...groups].map(([k,g])=>[k,{...g,roi:g.capital?g.profit/g.capital*100:null}]))}
function portfolioRisk(models){const exposed=models.map(x=>{const cap=N(x.r?.buy_total_czk)||0,p=x.predict?.p7||0;return cap*(1-p)}),var95=exposed.reduce((a,x)=>a+x,0)*.65,worst=models.reduce((a,x)=>a+Math.min(0,N(x.emergency)*(Math.max(1,N(x.r?.qty)||1))*(1-(N(x.fee?.rate)||.15))-(N(x.r?.buy_total_czk)||0)),0);return{var95,worst}}
function ensureCss(){if(document.querySelector('style[data-pred433]'))return;const s=document.createElement('style');s.dataset.pred433='1';s.textContent=`#ticketIntelView .pred433{margin:0 0 12px;border:1px solid #29485d;border-radius:13px;background:#091720;color:#dceaf4;overflow:hidden}.pred433-head{display:grid;grid-template-columns:1.3fr repeat(5,1fr);gap:8px;padding:11px 12px}.pred433 span{display:block;font-size:8px;font-weight:900;letter-spacing:.075em;text-transform:uppercase;color:#789ab3}.pred433 b{display:block;margin-top:3px;font-size:13px}.pred433 small{display:block;margin-top:2px;color:#7b91a3;font-size:9px}.pred433-list{border-top:1px solid #203746}.pred433-row{display:grid;grid-template-columns:1.4fr repeat(5,.75fr);gap:8px;padding:8px 12px;border-top:1px solid #172c38}.pred433-row strong{font-size:10px}.pred433-hot{color:#f0b68e}.pred433-good{color:#8bd8ad}@media(max-width:900px){.pred433-head{grid-template-columns:1fr 1fr}.pred433-row{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function renderPanel(models,risk){const host=document.querySelector('#ticketIntelView .td331');if(!host)return;let box=host.querySelector('[data-pred433]');if(!box){box=document.createElement('section');box.dataset.pred433='1';box.className='pred433';const eng=host.querySelector('[data-engine426]')||host.querySelector('.eng426');eng?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.querySelector('.td331-hero')?.insertAdjacentElement('afterend',box)}const best=[...models].sort((a,b)=>N(b.predict.opt.ev)-N(a.predict.opt.ev)).slice(0,6),avg=arr=>arr.length?arr.reduce((a,x)=>a+x,0)/arr.length:0;box.innerHTML=`<div class="pred433-head"><div><span>PREDICTIVE ENGINE · OS433</span><b>${models.length} aktivních pozic</b><small>Demand, sell probability, elasticita a EV jsou heuristické odhady kalibrované z vlastních market signálů.</small></div><div><span>AVG DEMAND</span><b>${Math.round(avg(models.map(x=>x.predict.demand)))}/100</b></div><div><span>AVG P(72H)</span><b>${Math.round(avg(models.map(x=>x.predict.p72))*100)} %</b></div><div><span>EV TOP 6</span><b>${fmt(best.reduce((a,x)=>a+N(x.predict.opt.ev),0))}</b></div><div><span>PORTFOLIO VAR</span><b>${fmt(risk.var95)}</b><small>heuristický 95% downside proxy</small></div><div><span>WORST-CASE</span><b>${fmt(risk.worst)}</b><small>při emergency exitu</small></div></div><div class="pred433-list">${best.map(x=>`<div class="pred433-row"><div><strong>${x.r.event_name}</strong><small>${x.r.section||'bez sektoru'} · ${Math.max(1,N(x.r.qty)||1)} ks</small></div><div><span>DEMAND</span><b>${x.predict.demand}</b></div><div><span>P 24H</span><b>${Math.round(x.predict.p24*100)} %</b></div><div><span>P 72H</span><b>${Math.round(x.predict.p72*100)} %</b></div><div><span>OPT EXIT</span><b class="pred433-good">${fmt(x.predict.opt.price)}</b></div><div><span>EV</span><b class="${x.predict.opt.ev>=0?'pred433-good':'pred433-hot'}">${fmt(x.predict.opt.ev)}</b></div></div>`).join('')}</div>`}
async function refresh(){if(busy)return;const engine=window.__KAMIL_TICKET_ENGINE426__;if(!engine?.models?.length)return;busy=true;try{ensureCss();const cloud=await loadTicketCloud660();if(!cloud?.ok)return;const models=engine.models.map(modelOne),comparables=comparableStats(cloud,models),risk=portfolioRisk(models);window.__KAMIL_TICKET_PREDICT433__={version:VERSION,healthy:true,models,comparables,risk,at:Date.now()};document.documentElement.dataset.ticketPredict433='1';renderPanel(models,risk);window.dispatchEvent(new CustomEvent('kamil:ticket-predict433-updated',{detail:{count:models.length}}))}finally{busy=false}}
function schedule(ms=500){clearTimeout(timer);timer=setTimeout(refresh,ms)}
export function installTicketPredictive433(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-refresh397-done','kamil:ticket-engine426-updated','kamil:ticket-repair432-done'])window.addEventListener(ev,()=>schedule());schedule(2200);setInterval(()=>schedule(0),15000)}
