import {cloudClient,session} from './cloud.js';
import {formModal} from './utils.js';
import {setTicketActionMeta461} from './ticketWorkflow461.js';

const VERSION=466;let bound=false,timer=0,busy=false;const N=v=>Number(v||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=(id,code)=>`${String(id)}|${String(code||'')}`;
const money=v=>`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`;
async function ctx(){const c=await cloudClient(),s=await session();if(!c||!s)throw new Error('Cloud session chybí.');return{c,s}}
function ensureCss(){if(document.querySelector('style[data-con466]'))return;const s=document.createElement('style');s.dataset.con466='1';s.textContent=`
#ticketIntelView [data-c454],#ticketIntelView [data-inbox460]{display:none!important}
#ticketIntelView [data-td-filter]{display:none!important}
#ticketIntelView .td331-overview{grid-template-columns:repeat(5,minmax(0,1fr))!important}
#ticketIntelView .system466{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:7px 10px;margin:0 0 6px;border:1px solid #294657;border-radius:9px;background:#091923;color:#dce9f2}
#ticketIntelView .system466-left{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.system466 span{font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#7898ad}.system466 b{font-size:10px}.system466-ok{color:#8bd8ad}.system466-warn{color:#efc17c}.system466-bad{color:#ff9aa5}.system466-btn,.c466-btn{border:1px solid #35566b;border-radius:7px;background:#102735;color:#cce0ec;padding:5px 8px;font-size:8px;font-weight:900;cursor:pointer}.system466-btn:hover,.c466-btn:hover{background:#153246}.c466-btn:disabled{opacity:.45;cursor:default}
#ticketIntelView .c465:not(.show-all) [data-c465-row]:nth-of-type(n+7){display:none!important}
#ticketIntelView .c466-head-actions{display:flex;align-items:center;gap:6px;margin-left:auto}.c466-more{white-space:nowrap}
#ticketIntelView .c466-actions{grid-column:2/-1;display:flex;align-items:center;gap:5px;flex-wrap:wrap;padding-top:2px}.c466-state{display:inline-flex;align-items:center;padding:3px 6px;border:1px solid #35566b;border-radius:999px;font-size:8px;font-weight:900}.c466-done{color:#8bd8ad}.c466-confirmed{color:#efc17c}.c466-ignored{color:#8499a7}.c466-overdue{color:#ff9aa5;border-color:#73404a}.c466-note{color:#8cb3ca;font-size:8px;max-width:340px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
#ticketIntelView .analytics466{margin-top:8px;border:1px solid #294657;border-radius:10px;background:#081720;color:#dce9f2;overflow:hidden}.analytics466-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 10px;cursor:pointer}.analytics466-head span{font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#7898ad}.analytics466-head b{font-size:10px}.analytics466-body{display:none;padding:8px;border-top:1px solid #203744}.analytics466.open .analytics466-body{display:grid;gap:7px}.analytics466-body>*{margin:0!important}.analytics466-body [data-c454],.analytics466-body [data-inbox460]{display:none!important}
#ticketIntelView [data-sold-card]{min-height:0!important}
#ticketIntelView [data-sold-card] .td331-signal{display:none!important}
#ticketIntelView [data-sold-card] .td331-reason{display:none!important}
#ticketIntelView [data-sold-card] .td420-price{min-height:42px!important}
@media(max-width:1100px){#ticketIntelView .td331-overview{grid-template-columns:repeat(3,minmax(0,1fr))!important}}
@media(max-width:760px){#ticketIntelView .td331-overview{grid-template-columns:1fr 1fr!important}.system466{align-items:flex-start;flex-direction:column}.c466-actions{grid-column:1/-1}}
`;document.head.appendChild(s)}
function latestExecution(){const m=new Map();for(const r of window.__KAMIL_TICKET_EXECUTION449__?.rows||[]){const k=key(r.ticket_id,r.recommendation_code);if(!m.has(k))m.set(k,r)}return m}
function commanderMap(){return new Map((window.__KAMIL_TICKET_COMMANDER465__?.rows||[]).map(x=>[String(x.id),x]))}
function dueFor(bucket){const t=Date.now();if(bucket==='UDĚLEJ TEĎ')return new Date(t+2*36e5).toISOString();if(bucket==='UDĚLEJ DNES'){const d=new Date();d.setHours(20,0,0,0);return new Date(d.getTime()>t?d:t+4*36e5).toISOString()}return new Date(t+24*36e5).toISOString()}
async function currentDb(c,s,id,code){const {data,error}=await c.from('ticket_action_executions').select('id,action_status,due_at,note,ignore_reason,snoozed_until').eq('user_id',s.user.id).eq('ticket_id',String(id)).eq('recommendation_code',String(code)).order('created_at',{ascending:false}).limit(1);if(error)throw error;return data?.[0]||null}
async function saveStatus(action,status,btn){if(busy)return;busy=true;if(btn)btn.disabled=true;try{const {c,s}=await ctx(),cur=await currentDb(c,s,action.id,action.what),t=new Date().toISOString(),payload={user_id:s.user.id,ticket_id:String(action.id),recommendation_code:String(action.what),recommendation_reason:action.why||null,recommended_price_czk:N(action.price)||null,action_status:status,acted_at:t,model_version:'466',...(!cur?.due_at?{due_at:dueFor(action.bucket)}:{})};let error;if(cur?.id)({error}=await c.from('ticket_action_executions').update(payload).eq('id',cur.id).eq('user_id',s.user.id));else({error}=await c.from('ticket_action_executions').insert(payload));if(error)throw error;window.dispatchEvent(new CustomEvent('kamil:ticket-action449-saved',{detail:{ticketId:action.id,code:action.what,status,source:'commander466'}}))}catch(e){console.error('[ticket466] action save failed',e)}finally{busy=false;if(btn)btn.disabled=false;schedule(180)}}
async function snooze(action){const data=await formModal('Odložit akci',`<label class="field"><span>Do kdy</span><select name="when"><option value="2H">Za 2 hodiny</option><option value="EVENING">Dnes večer</option><option value="TOMORROW">Zítra</option></select></label>`,{submitLabel:'Odložit'});if(!data)return;await setTicketActionMeta461(action.id,action.what,'SNOOZE',data.when||'2H')}
async function ignore(action){const data=await formModal('Ignorovat doporučení',`<label class="field"><span>Důvod</span><select name="reason" required><option value="">Vyber důvod…</option><option value="MANUAL_MARKET">Mám lepší informace o trhu</option><option value="PRICE_STRATEGY">Chci jinou cenovou strategii</option><option value="HOLD_STRATEGY">Chci pozici držet</option><option value="DATA_ISSUE">Nevěřím vstupním datům</option><option value="OTHER">Jiný důvod</option></select></label><label class="field"><span>Poznámka</span><input name="note" maxlength="180" placeholder="Volitelně doplň proč"></label>`,{submitLabel:'Ignorovat'});if(!data)return;const reason=String(data.reason||'').trim();if(!reason)return;await setTicketActionMeta461(action.id,action.what,'IGNORE',`${reason}${data.note?` · ${String(data.note).trim()}`:''}`)}
async function note(action){const cur=latestExecution().get(key(action.id,action.what));const data=await formModal('Poznámka k akci',`<label class="field"><span>Poznámka</span><input name="note" maxlength="220" value="${esc(cur?.note||'')}" placeholder="Např. čekám na změnu ceny"></label>`,{submitLabel:'Uložit'});if(!data)return;await setTicketActionMeta461(action.id,action.what,'NOTE',data.note||'')}
function jump(id){const safe=globalThis.CSS?.escape?CSS.escape(String(id)):String(id).replace(/["\\]/g,'\\$&'),d=document.querySelector(`#ticketIntelView [data-ticket-detail="${safe}"]`),card=d?.closest('[data-inventory-card]');if(card){card.dataset.focus459Hidden='0';card.scrollIntoView({behavior:'smooth',block:'center'})}}
function statusLabel(s){return s==='DONE'?'HOTOVO':s==='CONFIRMED'?'POTVRZENO':s==='IGNORED'?'IGNOROVÁNO':'NOVÉ'}
function decorateCommander(){const box=document.querySelector('#ticketIntelView [data-c465]'),model=commanderMap(),states=latestExecution();if(!box)return;let headActions=box.querySelector('.c466-head-actions');if(!headActions){headActions=document.createElement('div');headActions.className='c466-head-actions';box.querySelector('.c465-head')?.appendChild(headActions)}const count=model.size;headActions.innerHTML=`<button type="button" class="c466-btn c466-more" data-c466-more>${box.classList.contains('show-all')?'Top 5':`Všechny akce · ${count}`}</button>`;headActions.querySelector('[data-c466-more]')?.addEventListener('click',()=>{box.classList.toggle('show-all');decorateCommander()});for(const row of box.querySelectorAll('[data-c465-row]')){const id=String(row.dataset.c465Id||''),action=model.get(id);if(!action)continue;const st=states.get(key(id,action.what)),status=st?.action_status||'RECOMMENDED';let controls=row.querySelector('.c466-actions');if(!controls){controls=document.createElement('div');controls.className='c466-actions';row.appendChild(controls)}const overdue=!!window.__KAMIL_TICKET_WORKFLOW461__?.rows?.find(x=>String(x.id)===id)?.overdue;controls.innerHTML=`<span class="c466-state ${status==='DONE'?'c466-done':status==='CONFIRMED'?'c466-confirmed':status==='IGNORED'?'c466-ignored':''} ${overdue?'c466-overdue':''}">${overdue?'PO TERMÍNU · ':''}${statusLabel(status)}</span><button class="c466-btn" data-c466-act="JUMP">Karta</button><button class="c466-btn" data-c466-act="CONFIRMED" ${status==='DONE'?'disabled':''}>Potvrdit</button><button class="c466-btn" data-c466-act="DONE">Hotovo</button><button class="c466-btn" data-c466-act="SNOOZE" ${status==='DONE'||status==='IGNORED'?'disabled':''}>Odložit</button><button class="c466-btn" data-c466-act="NOTE">Pozn.</button><button class="c466-btn" data-c466-act="IGNORE" ${status==='DONE'?'disabled':''}>Ignorovat</button>${st?.note?`<span class="c466-note">${esc(st.note)}</span>`:''}`;for(const b of controls.querySelectorAll('[data-c466-act]'))b.addEventListener('click',()=>{const a=b.dataset.c466Act;if(a==='JUMP')jump(id);else if(a==='SNOOZE')snooze(action);else if(a==='IGNORE')ignore(action);else if(a==='NOTE')note(action);else saveStatus(action,a,b)})}}
function ensureDrawer(host){let drawer=host.querySelector('[data-analytics466]');if(drawer)return drawer;drawer=document.createElement('section');drawer.dataset.analytics466='1';drawer.className='analytics466';let open=false;try{open=localStorage.getItem('kamil.ticket.analytics466')==='1'}catch{}if(open)drawer.classList.add('open');drawer.innerHTML=`<div class="analytics466-head"><div><span>ANALYTIKA & DIAGNOSTIKA</span><b>Modely, health, calibration, risk a technické detaily</b></div><button type="button" class="system466-btn" data-analytics466-toggle>${open?'Skrýt':'Otevřít'}</button></div><div class="analytics466-body" data-analytics466-body></div>`;drawer.querySelector('[data-analytics466-toggle]')?.addEventListener('click',e=>{e.stopPropagation();drawer.classList.toggle('open');const on=drawer.classList.contains('open');drawer.querySelector('[data-analytics466-toggle]').textContent=on?'Skrýt':'Otevřít';try{localStorage.setItem('kamil.ticket.analytics466',on?'1':'0')}catch{}});drawer.querySelector('.analytics466-head')?.addEventListener('click',()=>drawer.querySelector('[data-analytics466-toggle]')?.click());host.appendChild(drawer);return drawer}
function coreChild(el){return el.matches('.td331-hero,[data-c465],[data-system466],.td331-overview,.td331-modes,[data-focus459],.td331-section,[data-analytics466],[data-c454],[data-inbox460]')}
function moveAnalytics(host,drawer){const body=drawer.querySelector('[data-analytics466-body]');for(const el of [...host.children]){if(el===drawer||coreChild(el))continue;body.appendChild(el)}return body.children.length}
function systemModel(){const rt=window.__KAMIL_TICKET_RUNTIME455__,rec=window.__KAMIL_TICKET_RECOVERY456__,lay=window.__KAMIL_TICKET_LAYOUT458__,models=window.__KAMIL_TICKET_ENGINE426__?.models||[],priced=models.filter(x=>N(x.market)>0).length;let status='OK';if(rt?.status==='ERROR'||rec?.status==='RECOVERY')status='ERROR';else if(!rt||['STALE','PARTIAL','STARTING'].includes(rt.status)||rec?.status==='WATCH'||lay?.status==='WARN')status='WATCH';return{status,errors:N(rt?.hard)+N(rec?.recent),priced,total:models.length,layout:lay?.status||'WAIT'}}
function ensureSystem(host,drawer){let box=host.querySelector('[data-system466]');if(!box){box=document.createElement('section');box.dataset.system466='1';box.className='system466'}const m=systemModel(),tone=m.status==='OK'?'ok':m.status==='ERROR'?'bad':'warn';box.innerHTML=`<div class="system466-left"><span>SYSTÉM</span><b class="system466-${tone}">${m.status==='OK'?'OK':m.status==='ERROR'?'CHYBA':'KONTROLA'}</b><span>trh ${m.priced}/${m.total}</span><span>${m.errors} chyb</span><span>layout ${m.layout}</span></div><button type="button" class="system466-btn" data-system466-analytics>Analytika & diagnostika</button>`;box.querySelector('[data-system466-analytics]')?.addEventListener('click',()=>{drawer.classList.add('open');drawer.querySelector('[data-analytics466-toggle]').textContent='Skrýt';try{localStorage.setItem('kamil.ticket.analytics466','1')}catch{}drawer.scrollIntoView({behavior:'smooth',block:'start'})});return box}
function enhanceKpis(host){const overview=host.querySelector('.td331-overview');if(!overview)return;const stats=[...overview.querySelectorAll('.td331-stat')],cap=window.__KAMIL_TICKET_CAPITAL453__,pred=window.__KAMIL_TICKET_PREDICT433__,risk=window.__KAMIL_TICKET_RISK438__;if(stats[0]&&N(cap?.total)>0){stats[0].querySelector('span').textContent='Aktivní kapitál';stats[0].querySelector('b').textContent=money(cap.total);const sm=stats[0].querySelector('small');if(sm)sm.textContent=`${cap.rows?.length||0} aktivních pozic`}if(stats[1]){const vals=(pred?.models||[]).map(x=>Number(x.predict?.opt?.ev)).filter(Number.isFinite);if(vals.length){const ev=vals.reduce((a,b)=>a+b,0);stats[1].querySelector('span').textContent='Expected NET P/L';stats[1].querySelector('b').textContent=`${ev>=0?'+':''}${money(ev)}`;const sm=stats[1].querySelector('small');if(sm)sm.textContent='heuristický EV po fee'}}if(stats[2])stats[2].querySelector('span').textContent='Realizovaný P/L';if(stats[3])stats[3].querySelector('span').textContent='Čeká na payout';let r=overview.querySelector('[data-kpi-risk466]');if(!r){r=document.createElement('div');r.className='td331-stat';r.dataset.kpiRisk466='1';overview.appendChild(r)}const var95=N(risk?.var95);r.innerHTML=`<span>Capital at Risk</span><b>${var95?money(var95):'—'}</b><small>heuristický downside proxy</small>`}
function hideLegacyFilters(host){for(const b of host.querySelectorAll('[data-td-filter]'))b.hidden=true;const parents=new Set([...host.querySelectorAll('[data-td-filter]')].map(x=>x.parentElement));for(const p of parents){if(p&&[...p.children].every(x=>x.hidden||x.matches('[data-td-filter]')))p.hidden=true}}
function cleanLabels(host){const k=host.querySelector('.td331-kicker');if(k)k.textContent='Kamil OS · Ticket Portfolio';const hero=host.querySelector('.td331-hero h1');if(hero)hero.textContent='Ticket Trading Desk';const p=host.querySelector('.td331-hero p');if(p)p.textContent='Co udělat, kdy to udělat a jak chránit kapitál. Detailní modely jsou schované v analytice.'}
function reorder(host,system,drawer){const hero=host.querySelector('.td331-hero'),cmd=host.querySelector('[data-c465]'),overview=host.querySelector('.td331-overview'),modes=host.querySelector('.td331-modes'),focus=host.querySelector('[data-focus459]'),sections=[...host.querySelectorAll(':scope > .td331-section')];let a=hero;if(cmd&&a){a.insertAdjacentElement('afterend',cmd);a=cmd}if(system&&a){a.insertAdjacentElement('afterend',system);a=system}if(overview&&a){a.insertAdjacentElement('afterend',overview);a=overview}if(modes&&a){a.insertAdjacentElement('afterend',modes);a=modes}if(focus&&a){a.insertAdjacentElement('afterend',focus);a=focus}for(const s of sections){if(a){a.insertAdjacentElement('afterend',s);a=s}}host.appendChild(drawer)}
function render(){ensureCss();const host=document.querySelector('#ticketIntelView .td331');if(!host)return;const drawer=ensureDrawer(host),system=ensureSystem(host,drawer);cleanLabels(host);hideLegacyFilters(host);enhanceKpis(host);decorateCommander();const moved=moveAnalytics(host,drawer);reorder(host,system,drawer);window.__KAMIL_TICKET_CONSOLIDATION466__={version:VERSION,healthy:!!window.__KAMIL_TICKET_COMMANDER465__,analyticsPanels:moved,at:Date.now()};document.documentElement.dataset.ticketConsolidation466='1';window.dispatchEvent(new CustomEvent('kamil:ticket-consolidation466-updated',{detail:{analyticsPanels:moved}}))}
function schedule(ms=120){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketConsolidation466(){if(bound)return;bound=true;ensureCss();for(const ev of ['kamil:view-change','kamil:ticket-commander465-updated','kamil:ticket-action449-saved','kamil:ticket-workflow461-updated','kamil:ticket-cadence463-updated','kamil:ticket-event464-updated','kamil:ticket-runtime455-updated','kamil:ticket-recovery456-done','kamil:ticket-layout458-updated','kamil:ticket-focus459-updated','kamil:ticket-capital453-updated','kamil:ticket-predict433-updated'])window.addEventListener(ev,()=>schedule());const host=document.querySelector('#ticketIntelView .td331');if(host)new MutationObserver(()=>schedule(220)).observe(host,{childList:true});schedule(5200)}
