import {cloudClient,session} from './cloud.js';
import {loadTicketCloud660} from './ticketCloud660.js';
import {formModal,modal,h} from './utils.js';

const VERSION=408,N=v=>Number(v||0),ACTIVE=new Set(['LISTED','NOT_LISTED']);let bound=false,timer=0;
const clean=s=>String(s||'').replace(/\r/g,'').trim();
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const money=s=>{const m=String(s||'').replace(/[^0-9,.-]/g,'').replace(',','.');const n=Number(m);return Number.isFinite(n)?n:0};
function field(text,label){const re=new RegExp(`${label}\\s*:?\\s*([^\\n]+)`,'i'),m=String(text||'').match(re);return m?m[1].trim():''}
function parse(text){const s=clean(text),order=(s.match(/(?:Číslo objednávky|Cislo objednavky|order(?: number)?|objednávk(?:a|y)|transactionid)[^0-9]{0,25}(\d{6,})/i)||[])[1]||'',event=field(s,'Akce')||field(s,'Event')||'',section=(s.match(/(?:Sekce|Section)\s*([^,\n]+)/i)||[])[1]?.trim()||'',qty=N((s.match(/Počet vstupenek\s*:\s*(\d+)/i)||s.match(/(\d+)\s*(?:Vstupenka\/y|tickets?)/i)||[])[1])||1,price=money((s.match(/Cena za vstupenku\s*:\s*([0-9\s.,]+)\s*Kč/i)||s.match(/Price per ticket\s*:\s*([0-9\s.,]+)/i)||[])[1]),total=money((s.match(/Výdělěk celkem\s*:\s*([0-9\s.,]+)\s*Kč/ig)||[]).at?.(-1)?.match(/[0-9\s.,]+/)?.[0])||price*qty,dateLine=field(s,'Datum')||field(s,'Date')||'',delivered=/úspěšně jste potvrdili převod|successfully confirmed.*transfer|tickets? transferred|převod.*potvrzen/i.test(s),needsDelivery=/please (?:send|upload).*tickets|převeďte prosím|upload your e-tickets/i.test(s),source=/viagogo/i.test(s)?'viagogo-email':'email';return{order,event,section,qty,price,total,dateLine,delivered,needsDelivery,source,text:s}}
function score(r,p){let s=0,a=norm(r.event_name),b=norm(p.event);if(b){const toks=b.split(' ').filter(x=>x.length>=3);s+=toks.filter(x=>a.includes(x)).length*3;if(a.includes(b)||b.includes(a))s+=8}if(p.section&&norm(r.section)===norm(p.section))s+=10;if(p.qty===N(r.qty))s+=2;return s}
function statusFor(p){return p.delivered?'SOLD_WAITING_PAYMENT':'SOLD_UNDELIVERED'}
async function clip(){try{return await navigator.clipboard.readText()}catch{return''}}
async function save(parsed,parent){const c=await cloudClient(),sess=await session();if(!c||!sess)throw new Error('Cloud session chybí.');const existing=await c.from('ticket_inventory').select('*').eq('user_id',sess.user.id).eq('marketplace_order_id',parsed.order).maybeSingle();if(existing.error)throw existing.error;const soldQty=Math.min(Math.max(1,N(parsed.qty)||1),Math.max(1,N(parent.qty)||1)),sellEach=N(parsed.price)||Math.round(N(parsed.total)/Math.max(1,N(parsed.qty)||1)),status=statusFor(parsed),now=new Date().toISOString();if(existing.data){const patch={market_status:parsed.delivered?'SOLD_WAITING_PAYMENT':existing.data.market_status,delivered_at:parsed.delivered?(existing.data.delivered_at||now):existing.data.delivered_at,updated_at:now};const u=await c.from('ticket_inventory').update(patch).eq('user_id',sess.user.id).eq('id',existing.data.id);if(u.error)throw u.error;return{mode:'update',id:existing.data.id,qty:N(existing.data.qty),status:patch.market_status}}
 const base={user_id:sess.user.id,source_row:parent.source_row,event_name:parent.event_name,qty:soldQty,event_date:parent.event_date,section:parent.section,row_label:parent.row_label,buy_each_czk:N(parent.buy_each_czk),buy_total_czk:N(parent.buy_each_czk)*soldQty,sell_each_czk:sellEach,sell_total_czk:sellEach*soldQty,market_status:status,viagogo_url:parent.viagogo_url,stubhub_url:parent.stubhub_url,official_url:parent.official_url,ask_each_czk:null,source_name:parent.source_name,source_sheet:parent.source_sheet,imported_at:parent.imported_at||now,updated_at:now,marketplace_order_id:parsed.order,sold_at:now,delivered_at:parsed.delivered?now:null,payout_expected_at:null,sale_source:parsed.source};
 if(soldQty<N(parent.qty)){const child={...base,id:`${parent.id}-sale-${parsed.order}`,parent_inventory_id:parent.id};const ins=await c.from('ticket_inventory').insert([child]);if(ins.error)throw ins.error;const left=N(parent.qty)-soldQty,upd=await c.from('ticket_inventory').update({qty:left,buy_total_czk:N(parent.buy_each_czk)*left,updated_at:now}).eq('user_id',sess.user.id).eq('id',parent.id);if(upd.error)throw upd.error;return{mode:'split',id:child.id,parentId:parent.id,qty:soldQty,left,status}}
 const upd=await c.from('ticket_inventory').update({...base,id:undefined,user_id:undefined,source_row:undefined,parent_inventory_id:null}).eq('user_id',sess.user.id).eq('id',parent.id);if(upd.error)throw upd.error;return{mode:'full',id:parent.id,qty:soldQty,left:0,status}}
}
async function open(){let text=await clip();if(!text||!/(viagogo|objednávk|order|ticket)/i.test(text)){const d=await formModal('Synchronizovat prodej z e-mailu','<label class="field"><span>Vlož celý e-mail od Viagogo / marketplace</span><textarea name="text" rows="14" required placeholder="Číslo objednávky, akce, sekce, počet vstupenek, cena…"></textarea></label><p class="muted">OS408 umí i částečný prodej: prodané kusy oddělí a zbytek nechá aktivní.</p>',{submitLabel:'Rozpoznat prodej'});if(!d)return;text=d.text||''}const p=parse(text);if(!p.order||!p.price)throw new Error('V e-mailu chybí číslo objednávky nebo cena za vstupenku.');const cloud=await loadTicketCloud660();if(!cloud?.ok)throw new Error('Ticket cloud není dostupný.');const candidates=(cloud.inventory||[]).filter(r=>ACTIVE.has(String(r.market_status||'').toUpperCase())).map(r=>({r,score:score(r,p)})).sort((a,b)=>b.score-a.score);const best=candidates[0];if(!best||best.score<4)throw new Error('Nenašel jsem dostatečně jistou aktivní vstupenku pro tento prodej.');const ownQty=Math.min(p.qty,Math.max(1,N(best.r.qty)||1)),split=ownQty<N(best.r.qty),confirm=await formModal(`Prodej ${h(p.order)}`,`<div class="field"><span>Spárovaná položka</span><strong>${h(best.r.event_name)}</strong><small>${h(best.r.section||'bez sektoru')} · v OS ${N(best.r.qty)} ks</small></div><div class="field"><span>Prodej</span><strong>${ownQty} ks × ${Math.round(p.price).toLocaleString('cs-CZ')} Kč = ${(ownQty*p.price).toLocaleString('cs-CZ')} Kč</strong><small>${split?`Částečný prodej — ${N(best.r.qty)-ownQty} ks zůstane aktivních.`:'Celá sledovaná položka se přesune do Sold.'}</small></div><div class="field"><span>Stav</span><strong>${p.delivered?'Převedeno · čeká payout':'Prodáno · doručit'}</strong></div>`,{submitLabel:'Synchronizovat'});if(!confirm)return;const out=await save(p,best.r);window.dispatchEvent(new CustomEvent('kamil:ticket-sale408-saved',{detail:out}));window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}));return out}
function wire(){const host=document.querySelector('#ticketIntelView');if(!host)return;const bar=host.querySelector('.td331-toolbar');if(!bar||bar.querySelector('[data-sale-sync408]'))return;const b=document.createElement('button');b.type='button';b.className='td331-btn';b.dataset.saleSync408='1';b.textContent='✉ Prodej z e-mailu';b.title='Načíst prodejní e-mail a bezpečně rozdělit i částečný prodej';b.addEventListener('click',async()=>{b.disabled=true;const old=b.textContent;b.textContent='Páruji prodej…';try{const out=await open();if(out)b.textContent=out.mode==='split'?'Rozděleno ✓':'Uloženo ✓'}catch(e){await modal('Synchronizace prodeje selhala',`<p>${h(e?.message||String(e))}</p>`,[{label:'OK',value:null,primary:true}])}finally{setTimeout(()=>{b.disabled=false;b.textContent=old},1400)}});bar.appendChild(b)}
function schedule(ms=120){clearTimeout(timer);timer=setTimeout(wire,ms)}
export function installTicketSaleSync408(){if(bound)return;bound=true;new MutationObserver(()=>schedule()).observe(document.body,{childList:true,subtree:true});for(const ev of ['kamil:view-change','kamil:ticket-sale408-saved'])window.addEventListener(ev,()=>schedule());schedule();setTimeout(()=>schedule(),1000);window.__KAMIL_TICKET_SALE_SYNC408__={version:VERSION,healthy:true,open,parse}}
