import {loadTicketCloud660} from './ticketCloud660.js';
import {cloudClient,session} from './cloud.js';
import {h,money} from './utils.js';
const N=v=>Number(v||0),A=v=>Array.isArray(v)?v:[],DAY=86400000;
const active=s=>['LISTED','NOT_LISTED'].includes(String(s||'').toUpperCase());
function latest(c,id){return c.latest?.get(id)||null}
function days(d){const t=d?new Date(d).getTime():NaN;return Number.isFinite(t)?Math.ceil((t-Date.now())/DAY):null}
function line(vals,w=720,hg=210){const a=A(vals).map(N).filter(Number.isFinite);if(a.length<2)return'<div class="tv135-emptychart">Více bodů se objeví po dalších market scanech.</div>';const min=Math.min(...a),max=Math.max(...a),r=Math.max(1,max-min),pts=a.map((v,i)=>`${(i/(a.length-1)*w).toFixed(1)},${(hg-12-((v-min)/r)*(hg-28)).toFixed(1)}`).join(' ');const up=a.at(-1)>=a[0];return `<svg class="tv135-line ${up?'up':'down'}" viewBox="0 0 ${w} ${hg}" preserveAspectRatio="none"><defs><linearGradient id="tv135g" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="currentColor" stop-opacity=".24"/><stop offset="100%" stop-color="currentColor" stop-opacity="0"/></linearGradient></defs><polygon points="0,${hg} ${pts} ${w},${hg}" fill="url(#tv135g)"/><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
async function loadSnapshots(){try{const c=await cloudClient(),sess=await session();if(!c||!sess)return[];const since=new Date(Date.now()-60*DAY).toISOString();const {data,error}=await c.from('ticket_market_snapshots').select('ticket_id,checked_at,market_price_czk,median_price_czk').eq('user_id',sess.user.id).gte('checked_at',since).order('checked_at',{ascending:true}).limit(2500);return error?[]:A(data)}catch{return[]}}
function portfolioSeries(inv,rows){const act=inv.filter(x=>active(x.market_status)),byDay=new Map();for(const s of rows){const r=act.find(x=>String(x.id)===String(s.ticket_id));if(!r)continue;const m=N(s.market_price_czk)||N(s.median_price_czk),buy=N(r.buy_each_czk),qty=N(r.qty||1);if(!m||!buy)continue;const day=String(s.checked_at||'').slice(0,10);if(!day)continue;if(!byDay.has(day))byDay.set(day,new Map());byDay.get(day).set(String(r.id),{value:m*qty,pl:(m-buy)*qty,buy:buy*qty})}const days=[...byDay.keys()].sort().slice(-30),last=new Map(),value=[],pl=[],roi=[];for(const d of days){for(const [id,v] of byDay.get(d))last.set(id,v);const vals=[...last.values()],v=vals.reduce((a,x)=>a+x.value,0),p=vals.reduce((a,x)=>a+x.pl,0),b=vals.reduce((a,x)=>a+x.buy,0);value.push(v);pl.push(p);roi.push(b?p/b*100:0)}return{days,value,pl,roi}}
function movers(cloud,rows){const by=new Map();for(const s of rows){if(!by.has(String(s.ticket_id)))by.set(String(s.ticket_id),[]);by.get(String(s.ticket_id)).push(s)}const out=[];for(const r of A(cloud.inventory).filter(x=>active(x.market_status))){const a=(by.get(String(r.id))||[]).map(x=>N(x.market_price_czk)||N(x.median_price_czk)).filter(x=>x>0);if(a.length<2)continue;const pct=(a.at(-1)/a[0]-1)*100;out.push({r,pct,last:a.at(-1)})}return out.sort((a,b)=>Math.abs(b.pct)-Math.abs(a.pct)).slice(0,5)}
function tasks(cloud){const out=[];for(const r of A(cloud.inventory)){const s=latest(cloud,r.id)||{},d=days(r.event_date),code=String(s.recommendation_code||'');if(r.market_status==='SOLD_UNDELIVERED')out.push({p:100,label:'Doručit',r,detail:'Prodáno, čeká na doručení'});else if(r.market_status==='SOLD_WAITING_PAYMENT')out.push({p:90,label:'Payout',r,detail:'Doručeno, čeká na peníze'});else if(active(r.market_status)&&['LOWER','VERIFY_DATA'].includes(code))out.push({p:80,label:code==='LOWER'?'Zlevnit':'Ověřit',r,detail:s.recommendation_reason||'Vyžaduje kontrolu'});else if(active(r.market_status)&&d!==null&&d>=0&&d<=3)out.push({p:70,label:d===0?'Dnes':'Brzy',r,detail:`Event za ${d} ${d===1?'den':'dny'}`})}return out.sort((a,b)=>b.p-a.p).slice(0,6)}
function fmt(metric,v){if(metric==='roi')return `${v>=0?'+':''}${v.toFixed(1)} %`;return `${v>=0&&metric==='pl'?'+':''}${money(v)}`}
function hero(shell,series){const old=shell.querySelector('.tv134-hero-chart');if(old)old.hidden=true;const wrap=document.createElement('section');wrap.className='tv135-home';wrap.innerHTML=`<div class="tv135-main"><div class="tv135-head"><div><div class="eyebrow">TICKET PORTFOLIO</div><h2>Vývoj portfolia</h2><p>Živá historie z market snapshotů aktuálně držených vstupenek.</p></div><div class="tv135-switch"><button class="on" data-tv135-metric="value">Hodnota</button><button data-tv135-metric="pl">P&L</button><button data-tv135-metric="roi">ROI</button></div></div><div class="tv135-number"><b data-tv135-number>—</b><span data-tv135-change>—</span></div><div class="tv135-chart" data-tv135-chart></div></div><aside class="tv135-side"><div class="tv135-sidehead"><div><small>DNES</small><h3>Dnes řešit</h3></div><span data-tv135-taskcount>0</span></div><div data-tv135-tasks></div></aside>`;shell.querySelector('.tv132-kpis')?.after(wrap);const paint=metric=>{wrap.querySelectorAll('[data-tv135-metric]').forEach(b=>b.classList.toggle('on',b.dataset.tv135Metric===metric));const vals=series[metric]||[],last=vals.at(-1)||0,first=vals[0]||0,delta=last-first;wrap.querySelector('[data-tv135-number]').textContent=fmt(metric,last);wrap.querySelector('[data-tv135-change]').textContent=metric==='roi'?`${delta>=0?'+':''}${delta.toFixed(1)} b. za 30 dní`:`${delta>=0?'+':''}${money(delta)} za 30 dní`;wrap.querySelector('[data-tv135-change]').className=delta>=0?'good':'bad';wrap.querySelector('[data-tv135-chart]').innerHTML=line(vals)};wrap.querySelectorAll('[data-tv135-metric]').forEach(b=>b.onclick=()=>paint(b.dataset.tv135Metric));paint('value');return wrap}
function renderTasks(wrap,rows){const box=wrap.querySelector('[data-tv135-tasks]');wrap.querySelector('[data-tv135-taskcount]').textContent=String(rows.length);box.innerHTML=rows.map(x=>`<article class="tv135-task"><span>${h(x.label)}</span><div><b>${h(x.r.event_name||'Událost')}</b><small>${h(x.r.section||'')} · ${h(x.detail)}</small></div></article>`).join('')||'<p class="tv135-clear">Nic urgentního. Ticket portfolio je čisté.</p>'}
function addMovers(shell,rows){if(shell.querySelector('.tv135-movers'))return;const sec=document.createElement('section');sec.className='tv135-movers';sec.innerHTML=`<div class="tv135-sectiontitle"><div><small>MARKET</small><h3>Top Movers</h3></div><span>změna za dostupnou historii</span></div><div class="tv135-movergrid">${rows.map(x=>`<article><div><b>${h(x.r.event_name||'Událost')}</b><small>${h(x.r.section||'')} · ${N(x.r.qty||1)} ks</small></div><strong class="${x.pct>=0?'good':'bad'}">${x.pct>=0?'+':''}${x.pct.toFixed(1)} %</strong><span>${money(x.last)}</span></article>`).join('')||'<p class="tv135-clear">Top movers se objeví po více market scanech.</p>'}</div>`;const home=shell.querySelector('.tv135-home');home?.after(sec)}
export async function enhanceTicketVisual135(){const shell=document.querySelector('.tv132-shell');if(!shell||shell.dataset.tv135==='1')return;shell.dataset.tv135='1';let cloud;try{cloud=await loadTicketCloud660()}catch{return}if(!cloud?.ok)return;const rows=await loadSnapshots(),series=portfolioSeries(A(cloud.inventory),rows),wrap=hero(shell,series);renderTasks(wrap,tasks(cloud));addMovers(shell,movers(cloud,rows));window.__KAMIL_TICKET_VISUAL135__={at:Date.now(),snapshots:rows.length,tasks:tasks(cloud).length,movers:movers(cloud,rows).length}}
