const VERSION=458;let bound=false,timer=0;
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
function ensureCss(){if(q('style[data-lg458]'))return;const s=document.createElement('style');s.dataset.lg458='1';s.textContent=`
#ticketIntelView{overflow-x:clip}
#ticketIntelView .td420-card:not(.td420-expanded) .eng427-line,#ticketIntelView .td420-card:not(.td420-expanded) .cmd439-chip,#ticketIntelView .td420-card:not(.td420-expanded) .pred436-line{display:none!important}
#ticketIntelView .td420-card:not(.td420-expanded){max-height:104px!important;overflow:hidden!important}
#ticketIntelView .td420-card.td420-expanded{max-height:none!important;overflow:visible!important}
#ticketIntelView .lg458-chip{display:inline-flex;align-items:center;min-height:18px;padding:0 6px;margin-left:5px;border:1px solid #35566b;border-radius:999px;font-size:7px;font-weight:900;letter-spacing:.04em}
#ticketIntelView .lg458-ok{color:#8bd8ad}.lg458-warn{color:#efc17c}.lg458-bad{color:#ff9aa5}
`;document.head.appendChild(s)}
function moveAfter(el,anchor){if(el&&anchor&&el.previousElementSibling!==anchor)anchor.insertAdjacentElement('afterend',el);return el||anchor}
function hideDuplicates(host,selector){const all=qa(selector,host);all.forEach((el,i)=>{el.hidden=i>0;el.dataset.layoutDuplicate458=i>0?'1':'0'});return Math.max(0,all.length-1)}
function repairOrder(host){const hero=q('.td331-hero',host);if(!hero)return false;const commander=q('[data-c454]',host),runtime=q('[data-runtime455]',host),recovery=q('[data-recovery456]',host),overview=q('.td331-overview',host);let a=hero;a=moveAfter(commander,a);a=moveAfter(runtime,a);a=moveAfter(recovery,a);moveAfter(overview,a);return true}
function inspect(){const host=q('#ticketIntelView .td331');if(!host)return null;ensureCss();const duplicates=hideDuplicates(host,'[data-c454]')+hideDuplicates(host,'[data-runtime455]')+hideDuplicates(host,'[data-recovery456]');repairOrder(host);const commander=q('[data-c454]',host),runtime=q('[data-runtime455]',host),recovery=q('[data-recovery456]',host),overview=q('.td331-overview',host),cards=qa('[data-inventory-card]',host),closed=cards.filter(c=>!c.classList.contains('td420-expanded')),heights=closed.map(c=>Math.round(c.getBoundingClientRect().height)).filter(Boolean),tall=heights.filter(h=>h>108).length,maxHeight=heights.length?Math.max(...heights):0,engineCount=Number(window.__KAMIL_TICKET_ENGINE426__?.models?.length||0),domCount=cards.length,countMismatch=engineCount>0&&domCount!==engineCount,root=q('#ticketIntelView'),overflow=!!root&&root.scrollWidth>root.clientWidth+6;const orderOk=!!(commander&&runtime&&recovery&&overview&&commander.previousElementSibling===q('.td331-hero',host)&&runtime.previousElementSibling===commander&&recovery.previousElementSibling===runtime&&overview.previousElementSibling===recovery);const issues=[];if(!orderOk)issues.push('ORDER');if(duplicates)issues.push(`DUP ${duplicates}`);if(overflow)issues.push('OVERFLOW');if(tall)issues.push(`TALL ${tall}`);if(countMismatch)issues.push(`CARDS ${domCount}/${engineCount}`);return{host,commander,runtime,recovery,overview,cards:domCount,engineCount,countMismatch,orderOk,duplicates,overflow,tall,maxHeight,issues,status:issues.length?'WARN':'OK'}}
function paintChip(m){const health=m.runtime;if(!health)return;let title=q('.rh455-title',health)||q('.rh455-head',health);if(!title)return;let chip=q('[data-lg458-chip]',health);if(!chip){chip=document.createElement('span');chip.dataset.lg458Chip='1';chip.className='lg458-chip';title.appendChild(chip)}chip.className=`lg458-chip ${m.status==='OK'?'lg458-ok':'lg458-warn'}`;chip.textContent=m.status==='OK'?`LAYOUT OK · ${m.cards} cards`:`LAYOUT ${m.issues.join(' · ')}`}
function run(){const m=inspect();if(!m)return;paintChip(m);window.__KAMIL_TICKET_LAYOUT458__={version:VERSION,healthy:m.status==='OK',status:m.status,orderOk:m.orderOk,duplicates:m.duplicates,overflow:m.overflow,tall:m.tall,maxHeight:m.maxHeight,cards:m.cards,engineCount:m.engineCount,countMismatch:m.countMismatch,issues:m.issues,at:Date.now()};document.documentElement.dataset.ticketLayout458=m.status.toLowerCase();window.dispatchEvent(new CustomEvent('kamil:ticket-layout458-updated',{detail:{status:m.status,issues:m.issues}}))}
function schedule(ms=160){clearTimeout(timer);timer=setTimeout(run,ms)}
export function installTicketLayoutGuard458(){if(bound)return;bound=true;ensureCss();for(const ev of ['kamil:view-change','kamil:ticket-ui457-updated','kamil:ticket-engine427-updated','kamil:ticket-commander454-updated','kamil:ticket-recovery456-done'])window.addEventListener(ev,()=>schedule());const host=q('#ticketIntelView');if(host)new MutationObserver(()=>schedule(260)).observe(host,{childList:true,subtree:true});schedule(1300);setTimeout(()=>schedule(),5000)}
