import {loadTicketCloud660} from './ticketCloud660.js';

const VERSION=426,N=v=>Number(v||0),ACTIVE=new Set(['LISTED','NOT_LISTED']),SOLD=new Set(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID']);
let bound=false,timer=0,busy=false,lastSignature='';
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
const round10=v=>Math.round(N(v)/10)*10;
const fmt=v=>Number.isFinite(Number(v))&&Number(v)!==0?`${Math.round(Number(v)).toLocaleString('cs-CZ')} Kč`:'—';
const pct=v=>Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(1)} %`:'—';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const parse=iso=>{const t=Date.parse(iso||'');return Number.isFinite(t)?t:null};
const ageH=s=>{const t=parse(s?.checked_at||s?.official_checked_at);return t===null?null:Math.max(0,(Date.now()-t)/36e5)};
const days=r=>{const t=parse(r?.event_date);return t===null?null:Math.ceil((t-Date.now())/864e5)};
const qty=r=>Math.max(1,N(r?.qty)||1);
const buyEach=r=>N(r?.buy_each_czk)||(N(r?.buy_total_czk)/qty(r));
const buyTotal=r=>N(r?.buy_total_czk)||buyEach(r)*qty(r);
function median(a=[]){const x=a.filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return null;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}
function quantile(a=[],q=.5){const x=a.filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return null;const p=(x.length-1)*q,i=Math.floor(p),f=p-i;return x[i+1]!==undefined?x[i]+f*(x[i+1]-x[i]):x[i]}
function filterOutliers(prices=[]){const x=prices.map(N).filter(v=>v>0);if(x.length<4)return x;const m=median(x),dev=x.map(v=>Math.abs(v-m)),mad=median(dev)||1,lo=m-3.5*1.4826*mad,hi=m+3.5*1.4826*mad;const y=x.filter(v=>v>=lo&&v<=hi);return y.length>=2?y:x}
function sourceClass(s){const c=String(s?.confidence||'').toLowerCase(),u=String(s?.resolved_url||'').toLowerCase(),m=String(s?.source_message||'').toLowerCase();if(c.includes('row')||N(s?.same_row_count)>0)return'row';if(c.includes('section')||N(s?.same_section_count)>0)return'section';if(c.includes('manual')||c.includes('clipboard'))return'manual';if(u.includes('stubhub')||m.includes('stubhub'))return'stubhub';if(c.includes('search-index'))return'index';if(c.includes('official-api')||c.includes('event-floor'))return'official';return'event'}
function freshness(age){if(age===null)return .55;if(age<=2)return 1;if(age<=6)return .96;if(age<=24)return .88;if(age<=48)return .72;if(age<=72)return .58;if(age<=168)return .38;return .20}
function comparableScore(r,s){const cls=sourceClass(s);let c={row:96,section:88,manual:90,stubhub:72,index:55,official:50,event:58}[cls]||55;if(qty(r)>1){if(s?.quantity_matched===true)c+=4;else c-=22}c+=Math.min(6,N(s?.competitor_count));if(s?.multi_market_conflict)c-=24;return clamp(c)}
function snapshotPrice(s){const candidates=[N(s?.market_price_czk),N(s?.viagogo_price_czk),N(s?.stubhub_price_czk),N(s?.median_price_czk)].filter(v=>v>0);return median(candidates)||0}
function historyRows(cloud,id){return [...(cloud.history?.get(id)||[])].filter(x=>snapshotPrice(x)>0).sort((a,b)=>(parse(a.checked_at)||0)-(parse(b.checked_at)||0))}
function pickCurrent(r,cloud){const rows=historyRows(cloud,r.id),latest=cloud.latest?.get(r.id)||null,cands=[];for(const s of rows.slice(-12)){const p=snapshotPrice(s);if(!p)continue;const score=comparableScore(r,s)*freshness(ageH(s));cands.push({s,p,score,age:ageH(s),cls:sourceClass(s)})}if(latest&&snapshotPrice(latest)>0&&!cands.some(x=>x.s===latest))cands.push({s:latest,p:snapshotPrice(latest),score:comparableScore(r,latest)*freshness(ageH(latest)),age:ageH(latest),cls:sourceClass(latest)});cands.sort((a,b)=>b.score-a.score||N(b.s?.competitor_count)-N(a.s?.competitor_count));return{best:cands[0]||null,alternates:cands.slice(1,4),rows}}
function depth(best){const raw=best?.s?.top_prices_czk;const arr=Array.isArray(raw)?raw.map(N).filter(v=>v>0):[];const clean=filterOutliers(arr);if(clean.length)return{prices:clean,market:quantile(clean,.25)||median(clean),median:median(clean),p75:quantile(clean,.75),count:clean.length,removed:arr.length-clean.length};return{prices:[],market:best?.p||0,median:best?.p||0,p75:best?.p||0,count:N(best?.s?.competitor_count)||0,removed:0}}
function momentum(rows,current){const now=Date.now(),priceAt=ms=>{const cut=now-ms,eligible=rows.filter(x=>(parse(x.checked_at)||0)<=cut);return snapshotPrice(eligible.at(-1)||rows[0])||current};const p24=priceAt(24*36e5),p7=priceAt(7*864e5),p30=priceAt(30*864e5),chg=p=>p?((current/p)-1)*100:null,m24=chg(p24),m7=chg(p7),m30=chg(p30),score=clamp(50+(m24||0)*1.8+(m7||0)*.9+(m30||0)*.35,0,100);return{h24:m24,d7:m7,d30:m30,score}}
function benchmark(rows,current){const ps=rows.map(snapshotPrice).filter(v=>v>0);if(!ps.length||!current)return{percentile:null,min:null,max:null};const below=ps.filter(v=>v<=current).length;return{percentile:below/ps.length*100,min:Math.min(...ps),max:Math.max(...ps)}}
function feeModel(cloud){const rates=(cloud.inventory||[]).filter(r=>SOLD.has(String(r.market_status||''))&&N(r.marketplace_fee_czk)>0&&(N(r.sell_total_czk)>0||N(r.payout_received_czk)>0)).map(r=>{const payout=N(r.payout_received_czk)||N(r.sell_total_czk),fee=N(r.marketplace_fee_czk);return fee/(payout+fee)}).filter(x=>x>.02&&x<.35);const med=median(rates),p75=quantile(rates,.75),rate=clamp(Number.isFinite(p75)?p75:.15,.10,.18);return{rate,n:rates.length,median:med,p75}}
function liquidity(r,best,rows,d){let score=18;score+=Math.min(32,N(best?.s?.competitor_count)*5);score+=Math.min(18,rows.length*2);if(best?.s?.same_row_count)score+=12;else if(best?.s?.same_section_count)score+=8;if(qty(r)>1&&best?.s?.quantity_matched!==true)score-=18;if(d!==null&&d<=14)score+=8;return{score:clamp(score),label:score>=72?'Vysoká':score>=45?'Střední':'Nízká'}}
function priceCurve(market,d,liq,mom){if(!market)return{};const mult={d30:1.05,d14:1.01,d7:.99,d3:.97,d1:.94};if(liq.score<40){mult.d14-=.02;mult.d7-=.03;mult.d3-=.03;mult.d1-=.03}if(mom.score<42){mult.d14-=.01;mult.d7-=.02;mult.d3-=.02;mult.d1-=.02}return Object.fromEntries(Object.entries(mult).map(([k,v])=>[k,round10(market*v)]))}
function actionPrice(market,liq,d,depthInfo,mom){if(!market)return 0;let undercut=0;if(depthInfo.count>=5&&liq.score>=65)undercut=.008;else if(liq.score>=45)undercut=.015;else undercut=.03;if(d!==null&&d<=3)undercut+=.02;if(mom.score<42)undercut+=.01;return round10(market*(1-undercut))}
function sellPressure(r,market,ask,d,liq,mom,conf){let s=0;if(d!==null){if(d<=1)s+=45;else if(d<=3)s+=36;else if(d<=7)s+=25;else if(d<=14)s+=14}if(liq.score<35)s+=18;else if(liq.score<50)s+=10;if(mom.score<35)s+=18;else if(mom.score<45)s+=9;if(ask&&market&&ask>market*1.05)s+=15;if(conf<60)s+=8;return clamp(s)}
function modelOne(r,cloud,fee){const picked=pickCurrent(r,cloud),best=picked.best,dp=depth(best),market=round10(dp.market||best?.p||0),baseConf=best?comparableScore(r,best.s):0,conf=Math.round(clamp(baseConf*freshness(best?.age),0,100)),mom=momentum(picked.rows,market),bench=benchmark(picked.rows,market),d=days(r),liq=liquidity(r,best,picked.rows,d),ask=N(r.ask_each_czk),buy=buyEach(r),min=buy?round10(buy/(1-fee.rate)):0,target=buy?round10(buy*1.20/(1-fee.rate)):0,emergency=buy?round10(buy*.95/(1-fee.rate)):0,act=actionPrice(market,liq,d,dp,mom),pressure=sellPressure(r,market,ask,d,liq,mom,conf),pairBlocked=qty(r)>1&&best?.s?.quantity_matched!==true,curve=priceCurve(market,d,liq,mom);let code='DRŽET',price=act,why='Cena je blízko trhu.';if(!market){code='DOPLNIT CENU';price=0;why='Chybí použitelná tržní cena.'}else if(pairBlocked){code='OVĚŘIT PÁR';price=0;why=`${qty(r)} ks spolu není potvrzeno.`}else if(conf<55){code='OVĚŘIT DATA';price=0;why=`Confidence ${conf} % je příliš nízká.`}else if(d!==null&&d<=1){code='PRODAT DNES';price=Math.max(emergency,curve.d1||act);why='Akce je do 24 hodin.'}else if(d!==null&&d<=3){code='PRODAT DNES';price=Math.max(emergency,curve.d3||act);why='Akce je do 72 hodin.'}else if(r.market_status==='NOT_LISTED'&&market>target){code='VYSTAVIT';price=Math.max(min,act);why='Trh je nad cílovým ROI.'}else if(ask&&ask>act*1.05){code='ZLEVNIT';price=Math.max(min,act);why='Tvoje cena je nad dynamickým cílem.'}else if(ask&&ask<act*.92&&pressure<55){code='ZDRAŽIT';price=act;why='Tvoje cena je výrazně pod trhem.'}else if(pressure>=70){code='PRODAT RYCHLE';price=Math.max(emergency,act);why='Vysoký sell pressure.'}const net=price?price*(1-fee.rate)-buy:null,roi=buy&&net!==null?net/buy*100:null;return{r,best,market,depth:dp,confidence:conf,momentum:mom,benchmark:bench,days:d,liquidity:liq,fee,min,target,emergency,curve,pressure,code,price,why,net,roi,pairBlocked}}
function events(models){const map=new Map();for(const m of models){const key=String(m.r.event_name||'').split(' - ')[0]||m.r.event_name,g=map.get(key)||{name:key,capital:0,market:0,positions:0,tickets:0,pressure:0};g.capital+=buyTotal(m.r);g.market+=m.market*qty(m.r);g.positions++;g.tickets+=qty(m.r);g.pressure=Math.max(g.pressure,m.pressure);map.set(key,g)}const total=[...map.values()].reduce((a,g)=>a+g.capital,0);return[...map.values()].map(g=>({...g,share:total?g.capital/total*100:0})).sort((a,b)=>b.capital-a.capital)}
function cashflow(cloud){const out={d7:0,d14:0,d30:0,later:0,undated:0};for(const r of (cloud.inventory||[]).filter(x=>SOLD.has(String(x.market_status||''))&&!['PAYOUT_RECEIVED','PAID'].includes(String(x.market_status||'')))){const amt=N(r.payout_received_czk)||N(r.sell_total_czk),d=days({event_date:r.payout_expected_at});if(d===null)out.undated+=amt;else if(d<=7)out.d7+=amt;else if(d<=14)out.d14+=amt;else if(d<=30)out.d30+=amt;else out.later+=amt}return out}
function buyWatch(models){return models.filter(m=>{const off=N(m.best?.s?.official_price_czk);return off>0&&m.market>off*1.25&&m.confidence>=60}).map(m=>({id:m.r.id,name:m.r.event_name,official:N(m.best.s.official_price_czk),market:m.market,edge:(m.market/N(m.best.s.official_price_czk)-1)*100})).sort((a,b)=>b.edge-a.edge).slice(0,5)}
function commander(models,eventRows,flow){const items=[];for(const m of models){let score=m.pressure;if(['PRODAT DNES','PRODAT RYCHLE'].includes(m.code))score+=45;else if(m.code==='ZLEVNIT')score+=28;else if(m.code==='VYSTAVIT')score+=18;else if(m.code.includes('OVĚŘIT')||m.code==='DOPLNIT CENU')score+=15;if(m.days!==null&&m.days<=7)score+=10;items.push({id:m.r.id,name:m.r.event_name,code:m.code,price:m.price,score,why:m.why})}for(const e of eventRows.filter(x=>x.share>=30))items.push({id:null,name:e.name,code:'NEPŘIKUPOVAT',price:0,score:85+(e.share-30),why:`Koncentrace ${e.share.toFixed(1)} % aktivního kapitálu.`});return items.sort((a,b)=>b.score-a.score).slice(0,8)}
function ensureCss(){if(document.querySelector('style[data-eng426]'))return;const s=document.createElement('style');s.dataset.eng426='1';s.textContent=`
#ticketIntelView .eng426{margin:0 0 12px;border:1px solid #29485d;border-radius:13px;background:#091721;color:#dceaf4;overflow:hidden}.eng426-head{display:grid;grid-template-columns:1.3fr repeat(5,1fr);gap:8px;padding:11px 12px}.eng426 span{display:block;font-size:8px;font-weight:900;letter-spacing:.075em;text-transform:uppercase;color:#789ab3}.eng426 b{display:block;margin-top:3px;font-size:13px}.eng426 small{display:block;margin-top:2px;color:#7b91a3;font-size:9px}.eng426-list{border-top:1px solid #203746}.eng426-row{display:grid;grid-template-columns:34px 1.4fr .8fr .8fr .8fr auto;gap:9px;align-items:center;padding:9px 12px;border-top:1px solid #172c38}.eng426-row:first-child{border-top:0}.eng426-num{width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:#163044;border:1px solid #34566c;font-size:10px;font-weight:900}.eng426-row strong{font-size:10px}.eng426-code{font-size:9px;font-weight:900;color:#a9cdef}.eng426-btn{border:1px solid #355970;background:#122936;color:#c9e1ef;border-radius:8px;padding:6px 9px;font-size:9px;font-weight:850;cursor:pointer}.eng426-chip{display:inline-flex;margin:4px 5px 0 0;padding:3px 6px;border:1px solid #284357;border-radius:999px;color:#89a1b3;font-size:8px}@media(max-width:950px){.eng426-head{grid-template-columns:1fr 1fr}.eng426-row{grid-template-columns:28px 1fr 1fr}.eng426-row>*:nth-child(n+4){grid-column:2/-1}}
`;document.head.appendChild(s)}
function jump(id){const el=document.querySelector(`#ticketIntelView [data-ticket-detail="${CSS.escape(String(id))}"]`)?.closest('article');el?.scrollIntoView({behavior:'smooth',block:'center'})}
function signature(models,eventRows,flow,watch,cmd,fee){return JSON.stringify({m:models.map(x=>[x.r?.id,x.market,x.confidence,x.pressure,x.code,x.price]),e:eventRows.map(x=>[x.name,x.capital,x.market,x.share,x.pressure]),f:flow,w:watch.map(x=>[x.id,x.official,x.market,x.edge]),c:cmd.map(x=>[x.id,x.code,x.price,x.score]),fee:[fee.rate,fee.n]})}
async function render(){
  if(busy)return false;
  const host=document.querySelector('#ticketIntelView .td331');if(!host)return false;
  busy=true;
  try{
    ensureCss();const cloud=await loadTicketCloud660();if(!cloud?.ok)return false;
    const fee=feeModel(cloud),models=(cloud.inventory||[]).filter(r=>ACTIVE.has(String(r.market_status||''))).map(r=>modelOne(r,cloud,fee)),eventRows=events(models),flow=cashflow(cloud),watch=buyWatch(models),cmd=commander(models,eventRows,flow);
    let box=host.querySelector('[data-engine426]');if(!box){box=document.createElement('section');box.dataset.engine426='1';box.className='eng426';const brief=host.querySelector('[data-daily-brief419]');brief?.insertAdjacentElement('afterend',box);if(!box.isConnected){const overview=host.querySelector('.td331-overview');overview?.insertAdjacentElement('afterend',box)}lastSignature=''}
    const top=cmd.slice(0,6),avgConf=models.length?models.reduce((a,m)=>a+m.confidence,0)/models.length:0,avgPressure=models.length?models.reduce((a,m)=>a+m.pressure,0)/models.length:0;
    const markup=`<div class="eng426-head"><div><span>MARKET ENGINE + COMMANDER 2.0 · OS426</span><b>${top.length?`${top.length} priorit`:'NIC URGENTNÍHO'}</b><small>Jedna kanonická cena, confidence, momentum, likvidita, sell pressure a dynamický cíl.</small></div><div><span>AVG CONFIDENCE</span><b>${avgConf.toFixed(0)} %</b><small>freshness-weighted</small></div><div><span>SELL PRESSURE</span><b>${avgPressure.toFixed(0)}/100</b><small>čas + trend + likvidita</small></div><div><span>FEE MODEL</span><b>${(fee.rate*100).toFixed(1)} %</b><small>${fee.n} historických vzorků</small></div><div><span>PAYOUT ≤14 D</span><b>${fmt(flow.d7+flow.d14)}</b><small>cashflow forecast</small></div><div><span>BUY WATCH</span><b>${watch.length}</b><small>známé eventy s official edge</small></div></div>${top.length?`<div class="eng426-list">${top.map((x,i)=>{const m=models.find(y=>String(y.r.id)===String(x.id));return`<div class="eng426-row"><div class="eng426-num">${i+1}</div><div><span class="eng426-code">${esc(x.code)}</span><strong>${esc(x.name)}</strong><small>${esc(x.why)}</small>${m?`<div><span class="eng426-chip">conf ${m.confidence}%</span><span class="eng426-chip">pressure ${m.pressure}</span><span class="eng426-chip">liq ${m.liquidity.score}</span><span class="eng426-chip">30d ${m.momentum.d30===null?'—':pct(m.momentum.d30)}</span></div>`:''}</div><div><span>CÍL</span><b>${x.price?fmt(x.price):'—'}</b></div><div><span>TRH</span><b>${m?fmt(m.market):'—'}</b></div><div><span>ROI</span><b>${m&&Number.isFinite(m.roi)?pct(m.roi):'—'}</b></div><button class="eng426-btn" data-eng426-jump="${esc(x.id||'')}">${x.id?'Karta':'Portfolio'}</button></div>`}).join('')}</div>`:''}`;
    const sig=signature(models,eventRows,flow,watch,cmd,fee),changed=sig!==lastSignature;
    if(changed){box.innerHTML=markup;lastSignature=sig;box.querySelectorAll('[data-eng426-jump]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.eng426Jump;if(id)jump(id);else document.querySelector('#ticketIntelView [data-capital415]')?.scrollIntoView({behavior:'smooth',block:'center'})}))}
    window.__KAMIL_TICKET_ENGINE426__={version:VERSION,healthy:true,fee,models,eventRows,cashflow:flow,buyWatch:watch,commander:cmd,at:Date.now(),stable:true};
    document.documentElement.dataset.ticketEngine426='1';
    if(changed)window.dispatchEvent(new CustomEvent('kamil:ticket-engine426-updated',{detail:{models:models.length,at:Date.now()}}));
    return true;
  }finally{busy=false}
}
function schedule(ms=120){clearTimeout(timer);timer=setTimeout(render,ms)}
export async function installTicketMarketEngine426(){
  if(bound)return window.__KAMIL_TICKET_ENGINE426__;
  bound=true;
  for(const ev of ['kamil:view-change','kamil:ticket-refresh397-done','kamil:ticket-price374-updated','kamil:ticket-sale408-saved','kamil:ticket-settlement411-saved'])window.addEventListener(ev,()=>schedule());
  await render();
  return window.__KAMIL_TICKET_ENGINE426__;
}
