import {h,money,modal} from './utils.js';
import {loadTicketCloud660,scanTicketsNow660,markTicketAlertsSeen660} from './ticketCloud660.js';
import {openTicketExcelImport660,exportTicketInventory660,openTicketRecoveryCenter185} from './ticketImport660.js';
import {openTicketCommander660} from './ticketCommander660.js';

const n=x=>Number(x||0);
const ACTIVE=new Set(['LISTED','NOT_LISTED']);
const SOLD=new Set(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID']);
let rendering=null;
let lastRenderAt=0;

const code=s=>String(s?.recommendation_code||'').toUpperCase();
const latest=(cloud,id)=>cloud?.latest?.get(id)||null;
const active=r=>ACTIVE.has(String(r?.market_status||'').toUpperCase());
const sold=r=>SOLD.has(String(r?.market_status||'').toUpperCase());
const actionCode=s=>!['','HOLD','NO_PRICE','FETCH_ERROR','SOURCE_MISSING'].includes(code(s));
const status=x=>({LISTED:'V nabídce',NOT_LISTED:'Nenabízíš',SOLD_UNDELIVERED:'Prodáno · doručit',SOLD_WAITING_PAYMENT:'Prodáno · čeká platba',PAYOUT_RECEIVED:'Vyplaceno',PAID:'Vyplaceno'})[String(x||'').toUpperCase()]||String(x||'Neurčeno');
const verdict=s=>({LIST:'PRODAT',LOWER:'ZLEVNIT',RAISE:'ZVÝŠIT',VERIFY_DATA:'OVĚŘIT',OFFICIAL_COMPETITION:'POZOR',HOLD:'DRŽET',NO_PRICE:'ČEKAT',SOURCE_MISSING:'DOPLNIT ZDROJ',FETCH_ERROR:'ZDROJ CHYBÍ'})[code(s)]||String(s?.recommendation_label||'SLEDOVAT').toUpperCase();
function tone(s){const c=code(s);return ['LOWER','VERIFY_DATA','OFFICIAL_COMPETITION'].includes(c)?'critical':['LIST','RAISE','BUY'].includes(c)?'success':'warning'}
function price(v){return n(v)>0?money(v):'—'}
function eventDate(r){if(!r?.event_date)return'Bez data';const d=new Date(r.event_date);return Number.isNaN(+d)?h(r.event_date):new Intl.DateTimeFormat('cs-CZ',{day:'numeric',month:'short',year:'numeric'}).format(d)}
function potential(r,s){const rec=n(s?.recommended_ask_czk)||n(s?.market_price_czk)||n(r?.ask_each_czk),buy=n(r?.buy_each_czk),qty=Math.max(1,n(r?.qty));return rec&&buy?(rec-buy)*qty:null}
function summary(cloud){const rows=cloud?.inventory||[],current=rows.filter(active),soldRows=rows.filter(sold);let invested=0,potentialProfit=0,realized=0,actions=0;for(const r of current){const s=latest(cloud,r.id);invested+=n(r.buy_total_czk)||n(r.buy_each_czk)*Math.max(1,n(r.qty));const p=potential(r,s);if(Number.isFinite(p))potentialProfit+=p;if(actionCode(s))actions++}for(const r of soldRows)if(['PAYOUT_RECEIVED','PAID'].includes(String(r.market_status||'').toUpperCase()))realized+=n(r.sell_total_czk)-n(r.buy_total_czk);return{current,soldRows,invested,potentialProfit,realized,actions}}
function card(r,s){const p=potential(r,s),market=n(s?.market_price_czk)||n(s?.stubhub_price_czk),rec=n(s?.recommended_ask_czk)||market,t=tone(s);return `<article class="td331-ticket" data-ticket-card data-group="${sold(r)?'sold':actionCode(s)?'action':'hold'}" data-tone="${t}"><div class="td331-ticket-top"><div><h3>${h(r.event_name||'Neznámá akce')}</h3><div class="td331-meta">${eventDate(r)} · ${h(r.section||'bez sekce')} · ${Math.max(1,n(r.qty||1))} ks · ${h(status(r.market_status))}</div></div><span class="td331-badge ${t}">${h(verdict(s))}</span></div><div class="td331-priceflow"><div class="td331-price"><span>Nákup / ks</span><b>${price(r.buy_each_czk)}</b></div><div class="td331-price"><span>Trh</span><b>${price(market)}</b></div><div class="td331-price"><span>Moje cena</span><b>${price(r.ask_each_czk)}</b></div><div class="td331-price recommended"><span>Doporučení</span><b>${price(rec)}</b></div></div><div class="td331-signal"><div class="td331-signal-main"><div><strong>${market?'Tržní signál dostupný':'Tržní data nejsou kompletní'}</strong><br><small>${h(s?.recommendation_reason||s?.source_message||'Čekám na další ověření trhu.')}</small></div></div><b>${Number.isFinite(p)?`${p>=0?'+':''}${money(p)}`:'—'}</b></div><div class="td331-ticket-actions"><button class="td331-btn" data-ticket-detail="${h(r.id)}">Detail</button></div></article>`}
function applyFilter(host,filter){host.querySelectorAll('[data-td-filter]').forEach(x=>x.classList.toggle('on',x.dataset.tdFilter===filter));host.querySelectorAll('[data-ticket-card]').forEach(x=>x.classList.toggle('hidden',filter!=='all'&&x.dataset.group!==filter))}
function ensureCss(){if(document.querySelector('link[data-ticket-desk331]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./ticketDesk331.css';l.dataset.ticketDesk331='1';document.head.appendChild(l)}
function bind(host,cloud){host.querySelectorAll('[data-td-filter]').forEach(x=>x.addEventListener('click',()=>applyFilter(host,x.dataset.tdFilter)));
 host.querySelector('[data-refresh]')?.addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;b.textContent='Obnovuji…';try{await scanTicketsNow660();await render338(true)}catch(err){b.disabled=false;b.textContent='↻ Obnovit trh';await modal('Refresh selhal',`<p>${h(err?.message||'Nepodařilo se obnovit trh.')}</p>`,[{label:'OK',value:null,primary:true}])}});
 host.querySelector('[data-import]')?.addEventListener('click',async()=>{await openTicketExcelImport660();await render338(true)});
 host.querySelector('[data-export]')?.addEventListener('click',()=>exportTicketInventory660());
 host.querySelector('[data-commander]')?.addEventListener('click',()=>openTicketCommander660());
 host.querySelector('[data-recovery]')?.addEventListener('click',()=>openTicketRecoveryCenter185());
 host.querySelector('[data-seen]')?.addEventListener('click',async()=>{await markTicketAlertsSeen660();await render338(true)});
 host.querySelectorAll('[data-ticket-detail]').forEach(x=>x.addEventListener('click',()=>openTicketCommander660(x.dataset.ticketDetail)));
}
async function doRender(force=false){const host=document.querySelector('#ticketIntelView');if(!host)return;if(!force&&host.querySelector('.td331[data-ticket-stable338]'))return;
 const first=!host.querySelector('.td331');if(first)host.innerHTML='<div class="td331" data-ticket-stable338><div class="td331-empty">Načítám Ticket Trading Desk…</div></div>';
 const cloud=await loadTicketCloud660();if(!cloud?.ok){host.innerHTML='<div class="td331" data-ticket-stable338><section class="td331-hero"><div class="td331-kicker">Ticket Trading Desk</div><h1>Vstupenky se nepodařilo načíst.</h1><p>Data zůstala beze změny.</p><div class="td331-toolbar"><button class="td331-btn" data-recovery>Recovery Center</button></div></section></div>';host.setAttribute('data-ticket-render-owner','ticketDesk338');host.querySelector('[data-recovery]')?.addEventListener('click',()=>openTicketRecoveryCenter185());return}
 const s=summary(cloud),cards=[...(cloud.inventory||[])].sort((a,b)=>Number(!actionCode(latest(cloud,a.id)))-Number(!actionCode(latest(cloud,b.id)))||String(a.event_date||'').localeCompare(String(b.event_date||''))).map(r=>card(r,latest(cloud,r.id))).join('');
 host.innerHTML=`<div class="td331" data-ticket-stable338><section class="td331-hero"><div class="td331-kicker">Kamil OS · Ticket Trading Desk</div><h1>Vstupenky</h1><p>Stabilní portfolio, akce a tržní rozhodnutí bez přepisování obrazovky.</p><div class="td331-toolbar"><button class="td331-btn primary" data-refresh>↻ Obnovit trh</button><button class="td331-btn" data-import>＋ Import</button><button class="td331-btn" data-export>Export</button><button class="td331-btn" data-commander>Commander</button>${cloud.alerts?.length?'<button class="td331-btn" data-seen>Označit změny přečtené</button>':''}</div></section><section class="td331-overview"><div class="td331-stat"><span>Aktivní portfolio</span><b>${s.current.length}</b><small>${money(s.invested)} investováno</small></div><div class="td331-stat accent"><span>Potenciální zisk</span><b>${s.potentialProfit>=0?'+':''}${money(s.potentialProfit)}</b><small>podle doporučených cen</small></div><div class="td331-stat"><span>Vyžaduje akci</span><b>${s.actions}</b><small>prodat · zlevnit · ověřit</small></div><div class="td331-stat"><span>Realizovaný zisk</span><b>${s.realized>=0?'+':''}${money(s.realized)}</b><small>${s.soldRows.length} prodaných položek</small></div></section><section class="td331-section"><div class="td331-section-head"><div><h2>Portfolio</h2><p>Řazené podle potřeby rozhodnutí.</p></div><div class="td331-filters"><button class="td331-filter on" data-td-filter="all">Vše</button><button class="td331-filter" data-td-filter="action">Akce ${s.actions}</button><button class="td331-filter" data-td-filter="hold">Držet</button><button class="td331-filter" data-td-filter="sold">Prodané</button></div></div><div class="td331-grid">${cards||'<div class="td331-empty">Zatím tu nejsou žádné vstupenky.</div>'}</div></section><section class="td331-tech"><div class="left"><strong>OS338 stable renderer</strong><span class="td331-chip ok">1 render owner</span></div><button class="td331-btn" data-recovery>Recovery / diagnostika</button></section></div>`;
 host.setAttribute('data-ticket-render-owner','ticketDesk338');bind(host,cloud);lastRenderAt=Date.now();window.__KAMIL_TICKET_DESK331__={version:338,inventory:cloud.inventory?.length||0,actions:s.actions,renderedAt:lastRenderAt,refresh:()=>render338(true)};window.__KAMIL_TICKET_DESK338__=window.__KAMIL_TICKET_DESK331__;
}
export async function render338(force=false){if(rendering)return rendering;rendering=doRender(force);try{return await rendering}finally{rendering=null}}
export function installTicketDesk338(){ensureCss();document.documentElement.dataset.ticketDesk331='1';document.documentElement.dataset.ticketDesk338='1';const mount=()=>{const host=document.querySelector('#ticketIntelView');if(host?.querySelector('.td331[data-ticket-stable338]'))return;render338(false).catch(console.error)};window.addEventListener('kamil:view-change',e=>{if(e?.detail?.view==='tickets')setTimeout(mount,0)});document.addEventListener('click',e=>{if(e.target.closest('#mainNav [data-view="tickets"],#bottomNav [data-view="tickets"]'))setTimeout(()=>render338(false).catch(console.error),0)},true);window.__KAMIL_TICKET_DESK331__={version:338,refresh:()=>render338(true)};window.__KAMIL_TICKET_DESK338__=window.__KAMIL_TICKET_DESK331__}
