const VERSION=451,N=v=>Number(v||0);let bound=false,timer=0;
const ttl=code=>/PANIC|DORUČIT|URGOVAT/.test(code)?2:/ZLEVNIT|PRODAT|EXIT|UVOLNIT/.test(code)?6:/OVĚŘIT/.test(code)?4:/NEPŘIKUPOVAT/.test(code)?12:18;
const key=x=>String(x?.id||'');
function build(){const c=window.__KAMIL_TICKET_COMMANDER448__;if(!c?.actions)return null;const now=Date.now(),groups=new Map();for(const a of c.actions){const k=key(a),g=groups.get(k)||[];g.push({...a,createdAt:c.at||now,ttlHours:ttl(a.code)});groups.set(k,g)}const rows=[];for(const [id,g] of groups){g.sort((a,b)=>b.priority-a.priority);const winner=g[0],conflicts=g.filter(x=>x.code!==winner.code).map(x=>x.code),age=(now-N(winner.createdAt))/36e5,expired=age>winner.ttlHours;rows.push({...winner,id,conflicts,expired,ageHours:age,halfLife:winner.ttlHours,finalCode:expired?'OBNOVIT DOPORUČENÍ':winner.code})}return{rows,conflictCount:rows.filter(x=>x.conflicts.length).length,expiredCount:rows.filter(x=>x.expired).length}}
function ensureCss(){if(document.querySelector('style[data-g451]'))return;const s=document.createElement('style');s.dataset.g451='1';s.textContent=`#ticketIntelView .g451{margin:0 0 12px;padding:8px 11px;border:1px solid #2e4b5d;border-radius:10px;background:#0a1922;color:#dce9f2;display:flex;gap:18px;flex-wrap:wrap}.g451 span{font-size:8px;font-weight:900;color:#7898ad;text-transform:uppercase}.g451 b{margin-left:4px;font-size:10px}.g451-warn{color:#efc17c}`;document.head.appendChild(s)}
function paint(m){ensureCss();const host=document.querySelector('#ticketIntelView [data-c448]');if(!host)return;let box=document.querySelector('#ticketIntelView [data-g451]');if(!box){box=document.createElement('div');box.dataset.g451='1';box.className='g451';host.insertAdjacentElement('afterend',box)}box.innerHTML=`<span>ACTION GOVERNANCE · OS451</span><span>finální akcí <b>${m.rows.length}</b></span><span>konflikty <b class="${m.conflictCount?'g451-warn':''}">${m.conflictCount}</b></span><span>expired <b class="${m.expiredCount?'g451-warn':''}">${m.expiredCount}</b></span><span>autorita <b>Commander 4 → Governance</b></span>`}
function refresh(){const m=build();if(!m)return;window.__KAMIL_TICKET_GOVERNANCE451__={version:VERSION,healthy:true,...m,at:Date.now()};document.documentElement.dataset.ticketGovernance451='1';paint(m);window.dispatchEvent(new CustomEvent('kamil:ticket-governance451-updated',{detail:{rows:m.rows.length}}))}
function schedule(ms=500){clearTimeout(timer);timer=setTimeout(refresh,ms)}
export function installTicketActionGovernance451(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-commander448-rendered','kamil:ticket-action449-saved'])window.addEventListener(ev,()=>schedule());schedule(11200);setInterval(()=>schedule(0),60*1000)}
