import {loadTicketCloud660} from './ticketCloud660.js';
import {cloudClient,session} from './cloud.js';
import {formModal,modal,h} from './utils.js';

const VERSION=411,N=v=>Number(v||0),SOLD=new Set(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID']);
let bound=false,timer=0,busy=false;
const fmt=v=>N(v)?`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`:'—';
const pct=v=>Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(1)} %`:'—';
const esc=s=>h(String(s??''));
const parse=iso=>{const t=Date.parse(iso||'');return Number.isFinite(t)?t:null};
const date=iso=>{const t=parse(iso);return t===null?'—':new Intl.DateTimeFormat('cs-CZ',{day:'numeric',month:'short',year:'numeric'}).format(new Date(t))};
const dt=iso=>{const t=parse(iso);return t===null?'—':new Intl.DateTimeFormat('cs-CZ',{day:'numeric',month:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(t))};
const daysUntil=iso=>{const t=parse(iso);return t===null?null:Math.ceil((t-Date.now())/864e5)};
function status(r){const x=String(r.market_status||'').toUpperCase();if(x==='SOLD_UNDELIVERED')return{label:'DORUČIT',tone:'bad'};if(x==='SOLD_WAITING_PAYMENT')return{label:'ČEKÁ PAYOUT',tone:'warn'};return{label:'VYPLACENO',tone:'good'}}
function profit(r){const payout=N(r.payout_received_czk)||N(r.sell_total_czk),buy=N(r.buy_total_czk),p=payout-buy;return{payout,buy,p,roi:buy?p/buy*100:null,fee:N(r.marketplace_fee_czk)}}
function quality(r){const miss=[];if(!String(r.marketplace_order_id||'').trim())miss.push('order ID');if(!N(r.sell_total_czk)&&!N(r.payout_received_czk))miss.push('payout');if(String(r.market_status)==='SOLD_UNDELIVERED'&&!r.delivery_due_at)miss.push('termín doručení');if(String(r.market_status)==='SOLD_WAITING_PAYMENT'&&!r.payout_expected_at)miss.push('termín payoutu');return miss}
function model(cloud){const rows=(cloud.inventory||[]).filter(r=>SOLD.has(String(r.market_status||'').toUpperCase())),items=rows.map(r=>({r,st:status(r),p:profit(r),q:quality(r)})),undelivered=items.filter(x=>x.st.label==='DORUČIT'),waiting=items.filter(x=>x.st.label==='ČEKÁ PAYOUT'),paid=items.filter(x=>x.st.label==='VYPLACENO'),expected=waiting.reduce((a,x)=>a+x.p.payout,0),received=paid.reduce((a,x)=>a+x.p.payout,0),profitAll=items.reduce((a,x)=>a+x.p.p,0),fees=items.reduce((a,x)=>a+x.p.fee,0),missing=items.filter(x=>x.q.length).length,overdueDelivery=undelivered.filter(x=>{const d=daysUntil(x.r.delivery_due_at);return d!==null&&d<0}).length,overduePayout=waiting.filter(x=>{const d=daysUntil(x.r.payout_expected_at);return d!==null&&d<0}).length;return{items,undelivered,waiting,paid,expected,received,profitAll,fees,missing,overdueDelivery,overduePayout}}
function ensureCss(){if(document.querySelector('style[data-set411]'))return;const s=document.createElement('style');s.dataset.set411='1';s.textContent=`#ticketIntelView .set411{margin:0 0 14px;border:1px solid #2d495d;border-radius:13px;background:#0b1720;color:#deebf5;overflow:hidden}.set411-head{display:grid;grid-template-columns:1.4fr repeat(4,1fr);gap:8px;padding:11px 12px}.set411 span{display:block;font-size:8px;font-weight:800;letter-spacing:.07em;text-transform:uppercase;color:#7899b2}.set411 b{display:block;margin-top:3px;font-size:13px}.set411 small{display:block;color:#8096a7;font-size:9px;margin-top:2px}.set411-list{border-top:1px solid #203746}.set411-row{display:grid;grid-template-columns:1.6fr .65fr .8fr .7fr .7fr auto;gap:8px;align-items:center;padding:9px 12px;border-top:1px solid #172b37}.set411-row:first-child{border-top:0}.set411-row strong{font-size:10px}.set411-status{font-size:9px;font-weight:900}.set411-status.bad{color:#f2a0a0}.set411-status.warn{color:#efcd88}.set411-status.good{color:#8fd4ad}.set411-actions{display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end}.set411-btn{border:1px solid #38596d;background:#132733;color:#c0dceb;border-radius:999px;padding:5px 8px;font-size:9px;font-weight:800;cursor:pointer}.set411-q{color:#dba0a0}.set411-calendar{padding:9px 12px;border-top:1px solid #203746;display:flex;gap:7px;flex-wrap:wrap}.set411-chip{border:1px solid #263f50;border-radius:999px;padding:5px 8px;font-size:9px;color:#93a9ba}@media(max-width:900px){.set411-head{grid-template-columns:1fr 1fr}.set411-row{grid-template-columns:1fr 1fr}.set411-actions{justify-content:flex-start}}`;document.head.appendChild(s)}
async function dbUpdate(id,patch){const c=await cloudClient(),sess=await session();if(!c||!sess)throw new Error('Cloud session chybí.');const {error}=await c.from('ticket_inventory').update({...patch,updated_at:new Date().toISOString()}).eq('user_id',sess.user.id).eq('id',id);if(error)throw error}
async function markDelivered(r){const yes=await modal('Potvrdit předání',`<p>Označit <strong>${esc(r.event_name)}</strong> jako předané a čekající na payout?</p>`,[{label:'Zrušit',value:null},{label:'Předáno',value:'yes',primary:true}]);if(yes!=='yes')return;await dbUpdate(r.id,{market_status:'SOLD_WAITING_PAYMENT',delivered_at:new Date().toISOString()});window.dispatchEvent(new CustomEvent('kamil:ticket-settlement411-saved',{detail:{id:r.id,stage:'delivered'}}));window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}))}
async function markPaid(r){const d=await formModal('Payout přijat',`<label class="field"><span>Přijatá částka</span><input name="amount" type="number" min="0" step="1" value="${N(r.payout_received_czk)||N(r.sell_total_czk)||''}" required></label><p class="muted">Částka se použije jako skutečný payout pro realizovaný P/L.</p>`,{submitLabel:'Označit jako vyplaceno'});if(!d)return;const amount=N(d.amount);if(!amount)throw new Error('Zadej přijatou částku.');const now=new Date().toISOString();await dbUpdate(r.id,{market_status:'PAYOUT_RECEIVED',payout_received_czk:amount,payout_recorded_at:now});window.dispatchEvent(new CustomEvent('kamil:ticket-settlement411-saved',{detail:{id:r.id,stage:'paid',amount}}));window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}))}
function calendar(m){const list=[...m.waiting].filter(x=>x.r.payout_expected_at).sort((a,b)=>parse(a.r.payout_expected_at)-parse(b.r.payout_expected_at)).slice(0,6);return list.length?`<div class="set411-calendar">${list.map(x=>{const d=daysUntil(x.r.payout_expected_at);return`<span class="set411-chip">${date(x.r.payout_expected_at)} · ${fmt(x.p.payout)} · ${esc(x.r.marketplace_order_id||x.r.event_name)}${d!==null&&d<0?' · po termínu':''}</span>`}).join('')}</div>`:''}
function row(x){const {r,st,p,q}=x,deadline=st.label==='DORUČIT'?r.delivery_due_at:r.payout_expected_at,dd=daysUntil(deadline);return`<div class="set411-row"><div><strong>${esc(r.event_name)}</strong><small>${esc(r.section||'bez sektoru')} · ${N(r.qty)||1} ks · order ${esc(r.marketplace_order_id||'—')}</small>${q.length?`<small class="set411-q">Chybí: ${esc(q.join(', '))}</small>`:''}</div><div><span>STAV</span><b class="set411-status ${st.tone}">${st.label}</b></div><div><span>${st.label==='DORUČIT'?'DORUČIT DO':'PAYOUT'}</span><b>${deadline?date(deadline):'—'}</b><small>${dd===null?'':dd<0?`${Math.abs(dd)} d po termínu`:dd===0?'dnes':`za ${dd} d`}</small></div><div><span>OČEKÁVÁM</span><b>${fmt(p.payout)}</b><small>fee ${fmt(p.fee)}</small></div><div><span>P/L</span><b>${p.p>=0?'+':''}${fmt(p.p)}</b><small>${pct(p.roi)}</small></div><div class="set411-actions">${st.label==='DORUČIT'?`<button class="set411-btn" data-del411="${esc(r.id)}">Předáno ✓</button>`:''}${st.label==='ČEKÁ PAYOUT'?`<button class="set411-btn" data-paid411="${esc(r.id)}">Payout přijat</button>`:''}</div></div>`}
async function render(){if(busy)return;const host=document.querySelector('#ticketIntelView .td331');if(!host)return;busy=true;try{ensureCss();const cloud=await loadTicketCloud660();if(!cloud?.ok)return;const m=model(cloud);let box=host.querySelector('[data-settlement411]');if(!box){box=document.createElement('section');box.dataset.settlement411='1';box.className='set411';const guard=host.querySelector('[data-sold-guard408]');guard?.insertAdjacentElement('afterend',box);if(!box.isConnected){const auto=host.querySelector('[data-ticket-autopilot407]');auto?.insertAdjacentElement('afterend',box)}}const sig=m.items.map(x=>[x.r.id,x.r.market_status,x.r.sell_total_czk,x.r.payout_received_czk,x.r.marketplace_order_id,x.r.delivery_due_at,x.r.payout_expected_at,x.r.marketplace_fee_czk].join(':')).sort().join('|');if(box.dataset.sig!==sig){box.dataset.sig=sig;const focus=[...m.undelivered,...m.waiting,...m.paid].sort((a,b)=>{const sa=a.st.label==='DORUČIT'?0:a.st.label==='ČEKÁ PAYOUT'?1:2,sb=b.st.label==='DORUČIT'?0:b.st.label==='ČEKÁ PAYOUT'?1:2;return sa-sb||(parse(a.r.delivery_due_at||a.r.payout_expected_at)||9e15)-(parse(b.r.delivery_due_at||b.r.payout_expected_at)||9e15)}).slice(0,12);box.innerHTML=`<div class="set411-head"><div><span>SETTLEMENT LEDGER · OS411</span><b>${m.overdueDelivery||m.overduePayout?'VYŽADUJE POZORNOST':'PRODEJE POD KONTROLOU'}</b><small>${m.missing?`${m.missing} řádků má neúplná settlement data.`:'Ordery, payouty i termíny jsou spárované.'}</small></div><div><span>ČEKÁM NA PAYOUT</span><b>${fmt(m.expected)}</b><small>${m.waiting.length} prodejů</small></div><div><span>VYPLACENO</span><b>${fmt(m.received)}</b><small>${m.paid.length} uzavřených</small></div><div><span>PRODEJNÍ P/L</span><b>${m.profitAll>=0?'+':''}${fmt(m.profitAll)}</b><small>z payoutu minus nákup</small></div><div><span>VIAGOGO FEE</span><b>${fmt(m.fees)}</b><small>evidované poplatky</small></div></div>${calendar(m)}${focus.length?`<div class="set411-list">${focus.map(row).join('')}</div>`:''}`;const byId=new Map(m.items.map(x=>[String(x.r.id),x.r]));box.querySelectorAll('[data-del411]').forEach(b=>b.addEventListener('click',()=>{const r=byId.get(String(b.dataset.del411));if(r)markDelivered(r).catch(e=>modal('Uložení selhalo',`<p>${esc(e?.message||String(e))}</p>`,[{label:'OK',value:null,primary:true}]))}));box.querySelectorAll('[data-paid411]').forEach(b=>b.addEventListener('click',()=>{const r=byId.get(String(b.dataset.paid411));if(r)markPaid(r).catch(e=>modal('Uložení selhalo',`<p>${esc(e?.message||String(e))}</p>`,[{label:'OK',value:null,primary:true}]))}))}window.__KAMIL_TICKET_SETTLEMENT411__={version:VERSION,healthy:true,model:m,at:Date.now()};document.documentElement.dataset.ticketSettlement411='1'}finally{busy=false}}
function schedule(ms=220){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketSettlement411(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-sale408-saved','kamil:ticket-settlement411-saved'])window.addEventListener(ev,()=>schedule());new MutationObserver(()=>schedule(320)).observe(document.body,{childList:true,subtree:true});schedule();setTimeout(()=>schedule(),1500)}
