import {cloudClient,session} from './cloud.js';
import {loadTicketCloud660} from './ticketCloud660.js';
import {ownEvent1100,ownObserver1100,schedule1100} from './runtimeOwnership1100.js';

const VERSION=430,OWNER='tickets.gmail429',N=v=>Number(v||0),SOLD=new Set(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID']);let bound=false,busy=false,state={configured:false,count:0,updates:[],unmatched:[],error:null};
const active=()=>!!document.querySelector('#view-tickets.on,#view-tickets.active,[data-view-panel="tickets"].on,[data-view-panel="tickets"].active');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(){const r=await fetch('/api/ticket-gmail-sync',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}),j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||`Gmail sync HTTP ${r.status}`);return j}
async function update(id,patch){const c=await cloudClient(),sess=await session();if(!c||!sess)throw new Error('Cloud session chybí.');const {error}=await c.from('ticket_inventory').update({...patch,updated_at:new Date().toISOString()}).eq('user_id',sess.user.id).eq('id',id);if(error)throw error}
function patchFor(r,m){const p={},status=String(r.market_status||''),tracked=Math.max(1,N(r.qty)||1),orderQty=Math.max(tracked,N(m.qty)||tracked),share=Math.min(1,tracked/orderQty);if(m.type==='transfer_confirmed'&&status==='SOLD_UNDELIVERED'){p.market_status='SOLD_WAITING_PAYMENT';p.delivered_at=m.ts||new Date().toISOString()}else if(['buyer','delivery_required'].includes(m.type)&&!['SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID'].includes(status)){p.market_status='SOLD_UNDELIVERED'}if(m.payout_czk&&(!N(r.sell_total_czk)||String(r.sale_source||'').includes('email'))){p.sell_total_czk=Math.round(N(m.payout_czk)*share*100)/100;p.sell_each_czk=p.sell_total_czk/tracked}if(m.fee_czk&&(!N(r.marketplace_fee_czk)||String(r.sale_source||'').includes('email')))p.marketplace_fee_czk=Math.round(N(m.fee_czk)*share*100)/100;if(Object.keys(p).length)p.sale_source='viagogo-gmail-auto';return p}
async function reconcile(messages,cloud){const byOrder=new Map((cloud.inventory||[]).filter(r=>SOLD.has(String(r.market_status||''))&&r.marketplace_order_id).map(r=>[String(r.marketplace_order_id),r])),seen=new Set(),updates=[],unmatched=[];for(const m of messages||[]){if(!m.order_id||seen.has(`${m.order_id}:${m.type}`))continue;seen.add(`${m.order_id}:${m.type}`);const r=byOrder.get(String(m.order_id));if(!r){unmatched.push(m);continue}const patch=patchFor(r,m);if(!Object.keys(patch).length)continue;await update(r.id,patch);updates.push({id:r.id,order:m.order_id,type:m.type,patch})}return{updates,unmatched}}
function ensureCss(){if(document.querySelector('style[data-gm429]'))return;const s=document.createElement('style');s.dataset.gm429='1';s.textContent=`#ticketIntelView .gm429{margin:10px 0 0;border:1px solid rgba(255,255,255,.07);border-radius:12px;background:#11161d;color:#d9e1e9;padding:10px 12px}.gm429-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.gm429 span{display:block;font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#7d8793}.gm429 b{display:block;margin-top:3px;font-size:11px}.gm429 small{display:block;margin-top:2px;color:#7f8996;font-size:8.5px}.gm429 button{min-height:30px;padding:0 10px;border:1px solid rgba(255,255,255,.09);border-radius:9px;background:#151b23;color:#d4dae1;font-size:9px;font-weight:850;cursor:pointer}.gm429-list{margin-top:8px;padding-top:8px;border-top:1px solid rgba(255,255,255,.06)}.gm429-item{display:flex;justify-content:space-between;gap:10px;padding:5px 0;font-size:9px;color:#8f99a5}.gm429-good{color:#7fd0a2}.gm429-warn{color:#e7be71}`;document.head.appendChild(s)}
function box(){if(!active())return null;const host=document.querySelector('#ticketIntelView .hub421-body')||document.querySelector('#ticketIntelView .td331');if(!host)return null;let el=document.querySelector('#ticketIntelView [data-gmail429]');if(!el){el=document.createElement('section');el.dataset.gmail429='1';el.className='gm429';host.appendChild(el)}return el}
function paint(){if(!active())return;ensureCss();const el=box();if(!el)return;const {configured=false,count=0,updates=[],unmatched=[],error=null}=state;el.innerHTML=`<div class="gm429-head"><div><span>GMAIL RECONCILIATION</span><b class="${configured?'gm429-good':'gm429-warn'}">${error?'CHYBA':configured?'PŘIPOJENO':'BACKEND NEPŘIPOJEN'}</b><small>${error?esc(error):configured?`${count} Viagogo mailů · ${updates.length} bezpečných změn · ${unmatched.length} bez přesného order ID v evidenci`:'Kód je připravený; chybí Google OAuth proměnné ve Vercelu.'}</small></div><button data-gm429-sync>${busy?'Synchronizuji…':'Synchronizovat'}</button></div>${unmatched.length?`<div class="gm429-list">${unmatched.slice(0,5).map(m=>`<div class="gm429-item"><span>${esc(m.type)} · ${esc(m.order_id)}</span><span>${esc(m.subject)}</span></div>`).join('')}</div>`:''}`;const b=el.querySelector('[data-gm429-sync]');if(b){b.disabled=busy;b.addEventListener('click',()=>run(true))}}
async function run(force=false){if(busy||!active())return;let last=0;try{last=N(localStorage.getItem('kamil.gmail429.last')||0)}catch{}if(!force&&Date.now()-last<6*36e5){paint();return}busy=true;paint();try{const j=await api();if(!active())return;if(!j.configured){state={configured:false,count:0,updates:[],unmatched:[],error:null};return}const cloud=await loadTicketCloud660();if(!active())return;if(!cloud?.ok)throw new Error('Ticket cloud není dostupný.');const result=await reconcile(j.messages||[],cloud);state={configured:true,count:j.count||0,...result,error:null};try{localStorage.setItem('kamil.gmail429.last',String(Date.now()))}catch{}if(result.updates.length){window.dispatchEvent(new CustomEvent('kamil:ticket-reconcile412-saved',{detail:{source:'gmail-auto',count:result.updates.length}}));window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}))}}catch(e){state={configured:true,count:0,updates:[],unmatched:[],error:String(e?.message||e)}}finally{busy=false;window.__KAMIL_TICKET_GMAIL429__={version:VERSION,healthy:!state.error,...state,runtimeOwner:OWNER,at:Date.now()};paint()}}
function schedule(ms=900){if(!active())return;schedule1100(OWNER,'sync',()=>{if(!active())return;paint();void run(false)},ms,{pauseWhenHidden:true})}
export function installTicketGmailSync429(){if(bound)return;bound=true;ensureCss();ownEvent1100(OWNER,window,'kamil:view-change',e=>{if(e.detail==='tickets')schedule()});const host=document.querySelector('#ticketIntelView');if(host)ownObserver1100(OWNER,host,{childList:true,subtree:true},()=>{if(active())paint()});if(active())schedule(2500)}
