import {cloudClient,session} from './cloud.js';
import {store} from './state.js';
import {appendTicketWorkflowEvent152} from './ticketWorkflowHistory152.js';
import {openTicketPayout154} from './ticketPayout154.js';
const MAP={SOLD_UNDELIVERED:{next:'SOLD_WAITING_PAYMENT',workflow:'PAYOUT WAIT',transferStatus:'DELIVERED'},SOLD_WAITING_PAYMENT:{next:'PAYOUT_RECEIVED',workflow:'PAYOUT RECEIVED',transferStatus:'DELIVERED'}};
async function advance(id,current,settlement=null){const from=String(current||'').toUpperCase(),step=MAP[from];if(!step)return{ok:false,reason:'INVALID_STAGE'};if(from==='SOLD_WAITING_PAYMENT'&&(!settlement||!Number.isFinite(Number(settlement.payout))||Number(settlement.payout)<=0))return{ok:false,reason:'PAYOUT_REQUIRED'};const c=await cloudClient(),sess=await session();if(!c||!sess)return{ok:false,reason:'NO_SESSION'};const changedAt=new Date().toISOString(),patch={market_status:step.next,updated_at:changedAt};if(from==='SOLD_WAITING_PAYMENT'){patch.payout_received_czk=Number(settlement.payout);patch.marketplace_fee_czk=settlement.fee===null||settlement.fee===undefined?null:Number(settlement.fee);patch.payout_recorded_at=changedAt}const {data,error}=await c.from('ticket_inventory').update(patch).eq('user_id',sess.user.id).eq('id',id).eq('market_status',from).select('id,market_status,payout_received_czk,marketplace_fee_czk,payout_recorded_at').maybeSingle();if(error)return{ok:false,error};if(!data)return{ok:false,reason:'STALE_STATE'};const audit=await appendTicketWorkflowEvent152(id,from,step.next,{source:'ticket_sales_ui',changed_at:changedAt,settlement_recorded:from==='SOLD_WAITING_PAYMENT'});store.mutate('Aktualizován stav prodeje vstupenky',s=>{const item=(s.ticketBook?.items||[]).find(x=>String(x.id)===String(id));if(item){item.marketStatus=step.next;item.workflow=step.workflow;item.transferStatus=step.transferStatus;if(from==='SOLD_WAITING_PAYMENT'){item.payoutReceivedCzk=Number(settlement.payout);item.marketplaceFeeCzk=settlement.fee===null||settlement.fee===undefined?null:Number(settlement.fee);item.payoutRecordedAt=changedAt}}}, {undo:true,cloud:false,audit:true});return{ok:true,status:step.next,auditOk:!!audit?.ok,auditError:audit?.ok?null:String(audit?.error?.message||audit?.reason||'AUDIT_WRITE_FAILED'),settlementRecorded:from==='SOLD_WAITING_PAYMENT'}}
function label(status){return status==='SOLD_UNDELIVERED'?'Označit doručeno':status==='SOLD_WAITING_PAYMENT'?'Označit vyplaceno':''}
export function enhanceTicketSales150(){const host=document.querySelector('#ticketIntelView');if(!host)return;host.querySelectorAll('[data-ticket-sale-action]').forEach(btn=>{if(btn.dataset.bound150==='1')return;btn.dataset.bound150='1';const status=String(btn.dataset.status||'').toUpperCase();btn.textContent=label(status)||btn.textContent;btn.addEventListener('click',async()=>{if(btn.disabled)return;const original=btn.textContent;let settlement=null;if(status==='SOLD_WAITING_PAYMENT'){const captured=await openTicketPayout154(btn.dataset.id);if(!captured)return;if(!captured.ok){btn.title=String(captured.error?.message||captured.reason||'Payout se nepodařilo připravit');return}settlement={payout:captured.payout,fee:captured.fee}}btn.disabled=true;btn.textContent='Ukládám…';const result=await advance(btn.dataset.id,status,settlement);if(!result.ok){btn.disabled=false;btn.textContent=original;btn.title=result.reason==='STALE_STATE'?'Stav se mezitím změnil. Obnov přehled.':String(result.error?.message||result.reason||'Aktualizace se nepodařila');return}if(!result.auditOk)console.warn('[ticket workflow history 152]',result.auditError);window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:'tickets'}))})})}
export const ticketSales150Info={statuses:['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED'],serverScopedByUser:true,feeMath:false,payoutMath:false,workflowHistoryFrom152:true,actualPayoutRequiredFrom154:true};
