const VERSION='465.1',N=v=>Number(v||0);let bound=false,timer=0;
const fmt=v=>N(v)?`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`:'—';
const bucketFor=code=>/DORUČIT|URGOVAT PAYOUT|PANIC/.test(code)?'UDĚLEJ TEĎ':/PRODAT|ZLEVNIT|EXIT|UVOLNIT|OVĚŘIT|OBNOVIT/.test(code)?'UDĚLEJ DNES':/DRŽET|NEPŘIKUPOVAT|SLEDUJ/.test(code)?'SLEDUJ':'NECHEJ BÝT';
function whenLabel(ca,w){if(w?.overdue)return'IHNED · PO TERMÍNU';if(!ca?.nextCheckAt)return ca?.hours===2?'do 2 h':ca?.hours===6?'do 6 h':ca?.hours===12?'do 12 h':'zítra';const d=new Date(ca.nextCheckAt),today=new Date(),tomorrow=new Date();tomorrow.setDate(today.getDate()+1);const same=d.toDateString()===today.toDateString(),next=d.toDateString()===tomorrow.toDateString(),time=d.toLocaleTimeString('cs-CZ',{hour:'2-digit',minute:'2-digit'});return ca.dueNow?`TEĎ · ${time}`:same?`dnes ${time}`:next?`zítra ${time}`:d.toLocaleDateString('cs-CZ',{day:'numeric',month:'numeric'})+` ${time}`}

function baseRows(){
  const c454=window.__KAMIL_TICKET_COMMANDER454__;
  if(c454?.rows?.length)return{source:'454',rows:c454.rows};
  const c439=window.__KAMIL_TICKET_COMMANDER439__;
  if(c439?.rows?.length)return{source:'439',rows:c439.rows.map(x=>({id:x.r?.id,r:x.r,title:x.r?.event_name,reason:x.portfolio?.reason||x.commander?.reason,commander5:{code:x.portfolio?.action||x.commander?.code||'SLEDUJ',bucket:bucketFor(x.portfolio?.action||x.commander?.code||'SLEDUJ'),score:N(x.portfolio?.urgency)||N(x.pressure)+50,regime:'portfolio'}}))};
  const c435=window.__KAMIL_TICKET_COMMANDER435__;
  if(c435?.rows?.length)return{source:'435',rows:c435.rows.map(x=>({id:x.r?.id,r:x.r,title:x.r?.event_name,reason:x.commander?.reason,commander5:{code:x.commander?.code||'SLEDUJ',bucket:bucketFor(x.commander?.code||'SLEDUJ'),score:(/PRODAT/.test(x.commander?.code||'')?100:/ZLEVNIT|EXIT|UVOLNIT/.test(x.commander?.code||'')?80:40)+N(x.pressure),regime:'predictive'}}))};
  const eng=window.__KAMIL_TICKET_ENGINE426__;
  if(eng?.models?.length)return{source:'426',rows:eng.models.map(m=>{const market=N(m.market),pressure=N(m.pressure),days=m.days;let code='SLEDUJ';if(!market)code='OVĚŘIT DATA';else if(pressure>=75||days!==null&&days<=3)code='PRODAT / ZLEVNIT TEĎ';else if(pressure>=55)code='SLEDUJ';return{id:m.r?.id,r:m.r,title:m.r?.event_name,reason:market?`Fallback z market engine · pressure ${Math.round(pressure)}`:'Chybí použitelná tržní cena.',commander5:{code,bucket:bucketFor(code),score:pressure+(market?0:180),regime:'engine-fallback'}}})};
  return{source:'WAIT',rows:[]};
}

function build(){
  const base=baseRows(),wf=window.__KAMIL_TICKET_WORKFLOW461__,cad=window.__KAMIL_TICKET_CADENCE463__,ev=window.__KAMIL_TICKET_EVENT_STRATEGY464__,eng=window.__KAMIL_TICKET_ENGINE426__;
  if(!base.rows.length)return{rows:[],urgent:0,source:base.source,waiting:true};
  const wMap=new Map((wf?.rows||[]).map(x=>[String(x.id),x])),cMap=new Map((cad?.rows||[]).map(x=>[String(x.id),x])),eMap=new Map((ev?.rows||[]).map(x=>[String(x.id),x])),mMap=new Map((eng?.models||[]).map(x=>[String(x.r?.id),x]));
  const rows=base.rows.map((x,i)=>{const id=String(x.id||x.r?.id||''),w=wMap.get(id),ca=cMap.get(id),es=eMap.get(id),m=mMap.get(id);let what=x.commander5?.code||x.finalCode||'SLEDUJ',price=N(m?.price)||N(m?.market)||N(x.r?.ask_each_czk)||0,why=x.reason||x.why||`${x.commander5?.regime||'market'} režim`,risk='ztráta času a horší kapitálová rotace',score=N(x.commander5?.score);if(w?.overdue)score+=800;if(/DORUČIT/.test(what))risk='ohrožen payout / objednávka';else if(/URGOVAT PAYOUT/.test(what))risk='zpoždění cashflow';else if(/PANIC|PRODAT|ZLEVNIT|EXIT/.test(what))risk='pokles ceny nebo neprodaná pozice';else if(/DRŽET/.test(what))risk='předčasný prodej může zkrátit upside';else if(/OVĚŘIT/.test(what))risk='rozhodnutí nad neúplnými tržními daty';if(es?.quantityPlan)why+=` · ${es.quantityPlan}`;if(es?.liquidityForecast)why+=` · ${es.liquidityForecast}`;return{id,title:x.title||x.r?.event_name||x.name||id,what,when:whenLabel(ca,w),nextCheckAt:ca?.nextCheckAt||null,dueNow:!!ca?.dueNow,price,why,risk,score,quantityPlan:es?.quantityPlan||null,seatPremiumPct:N(es?.seatPremiumPct),bucket:x.commander5?.bucket||bucketFor(what),rank:i+1,overdue:!!w?.overdue}}).sort((a,b)=>b.score-a.score);
  return{rows,urgent:rows.filter(x=>x.overdue||x.dueNow||/IHNED|TEĎ/.test(x.when)).length,source:base.source,waiting:false};
}
function ensureCss(){if(document.querySelector('style[data-c465]'))return;const s=document.createElement('style');s.dataset.c465='1';s.textContent=`#ticketIntelView .c465{margin:0 0 8px;border:1px solid #4c6b7e;border-radius:11px;background:#071821;color:#e3edf4;overflow:hidden}.c465-head{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:9px 11px;border-bottom:1px solid #203847}.c465-head span,.c465 span{font-size:9px;font-weight:900;color:#7898ad;text-transform:uppercase}.c465-head b{font-size:12px}.c465-row{display:grid;grid-template-columns:34px 1.15fr .78fr .78fr 1.35fr 1fr;gap:9px;align-items:center;padding:8px 11px;border-top:1px solid #172b36}.c465-row:first-child{border-top:0}.c465-row strong{font-size:11px}.c465-row small{display:block;color:#8095a4;font-size:9px;line-height:1.3;margin-top:2px}.c465-num{width:24px;height:24px;border-radius:50%;display:grid;place-items:center;background:#173044;font-size:9px;font-weight:900}.c465-risk{color:#ff9aa5}.c465-when{color:#efc17c;font-size:10px}.c465-wait{padding:12px;color:#8ba2b2;font-size:10px}@media(max-width:900px){.c465-row{grid-template-columns:28px 1fr 1fr}.c465-row>*:nth-child(n+4){grid-column:2/-1}}`;document.head.appendChild(s)}
function render(){ensureCss();const m=build();window.__KAMIL_TICKET_COMMANDER465__={version:VERSION,healthy:!m.waiting,...m,at:Date.now()};document.documentElement.dataset.ticketCommander465=m.waiting?'waiting':'1';const host=document.querySelector('#ticketIntelView .td331');if(!host)return;let box=host.querySelector('[data-c465]');if(!box){box=document.createElement('section');box.dataset.c465='1';box.className='c465';host.querySelector('.td331-hero')?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.prepend(box)}if(m.waiting){box.innerHTML=`<div class="c465-head"><div><span>COMMANDER 6</span><b>CO → KDY → CENA → DŮVOD → RIZIKO</b></div><b>čekám na model</b></div><div class="c465-wait">Market engine ještě neposkytl pozice. Commander zůstává viditelný a doplní se automaticky.</div>`;return}box.innerHTML=`<div class="c465-head"><div><span>COMMANDER 6 · SOURCE ${m.source}</span><b>CO → KDY → CENA → DŮVOD → RIZIKO</b></div><b>${m.urgent} urgent</b></div>${m.rows.map((x,i)=>`<div class="c465-row" data-c465-row data-c465-id="${String(x.id).replace(/"/g,'&quot;')}" data-c465-code="${String(x.what).replace(/"/g,'&quot;')}"><div class="c465-num">${i+1}</div><div><span>CO</span><strong>${x.what}</strong><small>${x.title}</small></div><div><span>KDY</span><b class="c465-when">${x.when}</b></div><div><span>CENA</span><b>${fmt(x.price)}</b><small>${x.quantityPlan||''}</small></div><div><span>DŮVOD</span><small>${x.why}</small></div><div><span>NEČINNOST</span><small class="c465-risk">${x.risk}</small></div></div>`).join('')}`;window.dispatchEvent(new CustomEvent('kamil:ticket-commander465-updated',{detail:{urgent:m.urgent,count:m.rows.length,source:m.source}}))}
function schedule(ms=100){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketCommander465(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-commander454-updated','kamil:ticket-commander439-updated','kamil:ticket-commander435-updated','kamil:ticket-workflow461-updated','kamil:ticket-cadence463-updated','kamil:ticket-event464-updated','kamil:ticket-engine426-updated'])window.addEventListener(ev,()=>schedule());schedule(0);setTimeout(()=>schedule(0),900);setTimeout(()=>schedule(0),2600);setInterval(()=>schedule(0),15000)}
