import {updateTicketTracking660} from './ticketCloud660.js';
import {modal,h} from './utils.js';
import {ownEvent1100,ownObserver1100,schedule1100} from './runtimeOwnership1100.js';

const VERSION=412,OWNER='tickets.action410',N=v=>Number(v||0);let bound=false;
const active=()=>!!document.querySelector('#view-tickets.on,#view-tickets.active,[data-view-panel="tickets"].on,[data-view-panel="tickets"].active');
const fmt=v=>N(v)?`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`:'—';
const esc=s=>h(String(s??''));
const ACTIONS=new Set(['PRODAT DNES','ZLEVNIT','ZDRAŽIT','VYSTAVIT']);
function modelMap(){return new Map((window.__KAMIL_TICKET_AUTOPILOT407__?.models||[]).map(m=>[String(m.r?.id),m]))}
async function copy(text){try{await navigator.clipboard.writeText(String(text));return true}catch{return false}}
async function setTarget(m,b){if(!active())return;const price=Math.round(N(m?.a?.price));if(!price)return;b.disabled=true;const old=b.textContent;b.textContent='Ukládám…';try{const out=await updateTicketTracking660(m.r.id,{askEachCzk:price});if(!out?.ok)throw out?.error||new Error('Uložení ceny selhalo.');await copy(price);b.textContent='Cíl uložen ✓';window.dispatchEvent(new CustomEvent('kamil:ticket-target410-saved',{detail:{id:m.r.id,price,code:m.a.code}}));window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}))}catch(e){await modal('Cílová cena se neuložila',`<p>${esc(e?.message||String(e))}</p>`,[{label:'OK',value:null,primary:true}]);b.textContent=old}finally{schedule1100(OWNER,`restore-${m.r.id}`,()=>{if(!b.isConnected)return;b.disabled=false;b.textContent=old},1300,{pauseWhenHidden:true})}}
function ensureCss(){if(document.querySelector('style[data-aq410]'))return;const s=document.createElement('style');s.dataset.aq410='1';s.textContent=`#ticketIntelView .aq410{margin:0 0 14px;border:1px solid rgba(255,255,255,.07);border-radius:13px;background:#11161d;color:#dce4ec;overflow:hidden}.aq410-head{padding:10px 12px;border-bottom:1px solid rgba(255,255,255,.06)}.aq410-head span{display:block;font-size:8px;font-weight:800;letter-spacing:.07em;color:#7d8793;text-transform:uppercase}.aq410-head b{display:block;margin-top:3px;font-size:13px}.aq410-list{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;padding:10px 12px}.aq410-item{border:1px solid rgba(255,255,255,.06);border-radius:10px;padding:9px;background:#0f141a}.aq410-item strong{display:block;font-size:10px}.aq410-item small{display:block;color:#87919d;font-size:9px;margin:4px 0 7px}.aq410-actions{display:flex;gap:6px;flex-wrap:wrap}.aq410-actions button,.aq410-actions a,.aq410-cardbtn{border:1px solid rgba(255,255,255,.09);background:#151b23;color:#d3d9e0;border-radius:999px;padding:5px 8px;font-size:9px;font-weight:800;text-decoration:none;cursor:pointer}.aq410-actions .primary,.aq410-cardbtn.primary{background:#eef3f9;color:#0f141a;border-color:#eef3f9}.aq410-cardbtn{margin-left:7px}@media(max-width:780px){.aq410-list{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function priority(m){const d=m.d??999,code=m.a?.code||'';let s=0;if(code==='PRODAT DNES')s+=100;else if(code==='ZLEVNIT')s+=80;else if(code==='VYSTAVIT')s+=65;else if(code==='ZDRAŽIT')s+=45;if(d<=3)s+=35;else if(d<=14)s+=15;s+=Math.min(20,Math.max(0,N(m.net?.roi))/5);return s}
function item(m){const url=m.r?.viagogo_url||m.r?.stubhub_url||'',price=Math.round(N(m.a?.price));return`<div class="aq410-item"><strong>${esc(m.r?.event_name||'Vstupenka')}</strong><small>${esc(m.a?.code||'AKCE')} · ${price?fmt(price):'bez cíle'} · ${m.d==null?'?':m.d} dní do akce</small><div class="aq410-actions">${price?`<button class="primary" data-set410="${esc(m.r.id)}">Nastavit cíl v OS</button><button data-copy410="${price}">Kopírovat ${fmt(price)}</button>`:''}${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Otevřít trh ↗</a>`:''}</div></div>`}
function render(){if(!active())return;const host=document.querySelector('#ticketIntelView .td331');if(!host)return;ensureCss();const map=modelMap(),models=[...map.values()],actions=models.filter(m=>ACTIONS.has(String(m.a?.code||''))&&N(m.a?.price)>0).sort((a,b)=>priority(b)-priority(a));let box=host.querySelector('[data-action-queue410]');if(!box){box=document.createElement('section');box.dataset.actionQueue410='1';box.className='aq410';const auto=host.querySelector('[data-ticket-autopilot407]');auto?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.querySelector('.td331-hero')?.insertAdjacentElement('afterend',box)}const top=actions.slice(0,6),sig=top.map(x=>[x.r.id,x.a.code,Math.round(N(x.a.price)),x.d,Math.round(priority(x))].join(':')).join('|')+`#${actions.length}`;if(box.dataset.sig!==sig){box.dataset.sig=sig;box.innerHTML=`<div class="aq410-head"><span>ACTION QUEUE</span><b>${actions.length?`${actions.length} cenových akcí k provedení`:'ŽÁDNÁ CENOVÁ AKCE'}</b><small>${actions.length?'Cíl se uloží pouze do Kamil‑OS; marketplace cenu měníš až na otevřeném trhu.':'Autopilot teď nemá bezpečné přecenění.'}</small></div>${top.length?`<div class="aq410-list">${top.map(item).join('')}</div>`:''}`}for(const card of host.querySelectorAll('[data-ta407]')){const id=card.dataset.ta407,m=map.get(String(id));if(!m||!ACTIONS.has(String(m.a?.code||''))||!N(m.a?.price))continue;const dec=card.querySelector('.ta407-decision');if(!dec||dec.querySelector('[data-cardtarget410]'))continue;const b=document.createElement('button');b.type='button';b.className='aq410-cardbtn primary';b.dataset.cardtarget410='1';b.textContent=`Cíl ${fmt(m.a.price)}`;b.title='Uložit doporučenou cílovou cenu do Kamil-OS';dec.appendChild(b)}window.__KAMIL_TICKET_ACTION_QUEUE410__={version:VERSION,healthy:true,count:actions.length,actions:top.map(x=>({id:x.r.id,code:x.a.code,price:x.a.price,priority:priority(x)})),runtimeOwner:OWNER,at:Date.now()};document.documentElement.dataset.ticketActionQueue410='1'}
async function onClick(event){if(!active())return;const set=event.target.closest('[data-set410]');if(set){const m=modelMap().get(String(set.dataset.set410));if(m)await setTarget(m,set);return}const cp=event.target.closest('[data-copy410]');if(cp){const ok=await copy(cp.dataset.copy410),old=cp.textContent;cp.textContent=ok?'Zkopírováno ✓':'Kopírování selhalo';schedule1100(OWNER,`copy-${cp.dataset.copy410}`,()=>{if(cp.isConnected)cp.textContent=old},900,{pauseWhenHidden:true});return}const cardBtn=event.target.closest('[data-cardtarget410]');if(cardBtn){const card=cardBtn.closest('[data-ta407]'),m=modelMap().get(String(card?.dataset.ta407||''));if(m)await setTarget(m,cardBtn)}}
function schedule(ms=250){if(!active())return;schedule1100(OWNER,'render',render,ms,{pauseWhenHidden:true})}
export function installTicketActionQueue410(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-refresh397-done','kamil:ticket-target410-saved','kamil:ticket-sale408-saved'])ownEvent1100(OWNER,window,ev,()=>schedule());const root=document.querySelector('#ticketIntelView');if(root){ownObserver1100(OWNER,root,{childList:true,subtree:true},()=>{if(active())schedule(320)});ownEvent1100(OWNER,root,'click',e=>void onClick(e))}schedule();schedule1100(OWNER,'settle',()=>schedule(),1500,{pauseWhenHidden:true})}
