const VERSION=420;
let bound=false,timer=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ensureCss(){if(document.querySelector('style[data-ticket-ui420]'))return;const s=document.createElement('style');s.dataset.ticketUi420='1';s.textContent=`
#ticketIntelView .td331-grid{gap:12px!important;padding:12px!important;background:#08121b!important}
#ticketIntelView .td331-ticket.td420-card{display:grid!important;grid-template-columns:minmax(260px,.9fr) minmax(480px,1.55fr) 170px!important;grid-template-areas:"identity summary actions"!important;gap:14px 18px!important;align-items:center!important;margin:0!important;padding:18px!important;border:1px solid #263c4e!important;border-left:3px solid #3b5870!important;border-radius:14px!important;background:linear-gradient(180deg,#0d1924 0%,#0b1620 100%)!important;overflow:visible!important;box-shadow:0 8px 26px rgba(0,0,0,.12)}
#ticketIntelView .td331-grid .td331-ticket.td420-card:nth-child(even){background:linear-gradient(180deg,#0f1c28 0%,#0c1822 100%)!important}
#ticketIntelView .td331-ticket.td420-card[data-tone="success"]{border-left-color:#65d59b!important}#ticketIntelView .td331-ticket.td420-card[data-tone="warning"]{border-left-color:#f0b761!important}#ticketIntelView .td331-ticket.td420-card[data-tone="critical"]{border-left-color:#ff7885!important}
#ticketIntelView .td420-card .td331-ticket-top{grid-area:identity!important;display:block!important;align-self:center!important;min-width:0!important;padding-right:4px!important;overflow:visible!important;position:relative!important}
#ticketIntelView .td420-card .td331-ticket-top>div{overflow:visible!important}
#ticketIntelView .td420-card .td331-ticket-top>span.td331-badge{display:inline-flex!important;margin-top:10px!important;padding:5px 9px!important;font-size:9px!important;letter-spacing:.04em!important}
#ticketIntelView .td420-card h3{font-size:15px!important;line-height:1.25!important;white-space:normal!important;overflow:visible!important;text-overflow:clip!important;max-width:310px!important}
#ticketIntelView .td420-card .td331-meta{margin-top:6px!important;font-size:10px!important;line-height:1.45!important;white-space:normal!important;color:#91a6b8!important}
#ticketIntelView .td420-source{margin-top:8px;color:#718ba1;font-size:9px;line-height:1.45}
#ticketIntelView .td420-summary{grid-area:summary;display:grid;grid-template-columns:repeat(4,minmax(108px,1fr));gap:9px;min-width:0}
#ticketIntelView .td420-price{min-width:0;padding:13px 12px;border:1px solid #243c4d;border-radius:10px;background:#0f202c}
#ticketIntelView .td420-price span{display:block;color:#7896ad;font-size:8px;font-weight:850;letter-spacing:.065em;text-transform:uppercase;white-space:nowrap}
#ticketIntelView .td420-price b{display:block;margin-top:5px;font-size:16px;line-height:1.1;color:#f2f7fb;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
#ticketIntelView .td420-price small{display:block;margin-top:4px;color:#71879a;font-size:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
#ticketIntelView .td420-price.market b{color:#ffd17d}#ticketIntelView .td420-price.mine b{color:#dbe8f4}#ticketIntelView .td420-price.floor b{color:#b3c8d9}#ticketIntelView .td420-price.decision{border-color:#2c5870;background:#102533}#ticketIntelView .td420-price.decision b{color:#8fc8ff}
#ticketIntelView .td420-card .td331-ticket-actions{grid-area:actions!important;display:grid!important;grid-template-columns:1fr!important;gap:7px!important;align-self:center!important;min-width:0!important}
#ticketIntelView .td420-card .td331-ticket-actions .td331-btn,#ticketIntelView .td420-more{min-height:34px!important;padding:0 10px!important;border-radius:8px!important;font-size:9px!important;font-weight:800!important;white-space:nowrap!important}
#ticketIntelView .td420-more{border:1px solid #30485b;background:#122330;color:#a9c3d6;cursor:pointer}
#ticketIntelView .td420-card .td331-ticket-actions>*:nth-child(n+4):not(.td420-more){display:none!important}
#ticketIntelView .td420-card.td420-expanded .td331-ticket-actions>*{display:inline-flex!important}
#ticketIntelView .td420-card .td331-priceflow,#ticketIntelView .td420-card .td331-signal,#ticketIntelView .td420-card .td331-reason{display:none!important}
#ticketIntelView .td420-card.td420-expanded .td331-priceflow{display:grid!important;grid-column:1/-1!important;grid-area:auto!important;grid-template-columns:repeat(5,minmax(110px,1fr))!important;gap:8px!important;padding:14px 0 0!important;border-top:1px solid #213746!important}
#ticketIntelView .td420-card .td331-price{padding:9px!important;border:1px solid #233a4a!important;border-radius:8px!important;background:#0d1d28!important;text-align:left!important}
#ticketIntelView .td420-card .td331-price span{font-size:8px!important}#ticketIntelView .td420-card .td331-price b{font-size:11px!important;margin-top:4px!important}#ticketIntelView .td420-card .td331-price small{display:block!important;margin-top:3px!important;font-size:8px!important;color:#6e8497!important;white-space:normal!important}
#ticketIntelView .td420-card.td420-expanded .td331-signal{display:flex!important;grid-column:1/-1!important;grid-area:auto!important;padding:12px!important;border:1px solid #223a4b!important;border-radius:9px!important;background:#0c1b26!important}
#ticketIntelView .td420-card.td420-expanded .td331-reason{display:block!important;grid-column:1/-1!important;grid-area:auto!important;margin:0!important;padding:10px 12px!important;border:1px solid #223a4b!important;border-radius:9px!important;background:#0b1923!important;font-size:9px!important;line-height:1.45!important;white-space:normal!important;color:#7790a4!important}
#ticketIntelView .td420-card .ta407-card,#ticketIntelView .td420-card .ph409-strip{display:none!important}
#ticketIntelView .td420-card.td420-expanded .ta407-card,#ticketIntelView .td420-card.td420-expanded .ph409-strip{display:block!important;grid-column:1/-1!important;grid-area:auto!important}
#ticketIntelView .td331-section-head{padding:14px 16px!important}#ticketIntelView .td331-section{overflow:visible!important;border-radius:12px!important}
@media(max-width:1180px){#ticketIntelView .td331-ticket.td420-card{grid-template-columns:minmax(240px,.9fr) minmax(400px,1.4fr) 150px!important}#ticketIntelView .td420-summary{grid-template-columns:repeat(2,minmax(120px,1fr))!important}}
@media(max-width:860px){#ticketIntelView .td331-ticket.td420-card{grid-template-columns:1fr!important;grid-template-areas:"identity" "summary" "actions"!important}#ticketIntelView .td420-card .td331-ticket-actions{grid-template-columns:repeat(2,minmax(0,1fr))!important}#ticketIntelView .td420-card h3{max-width:none!important}}
@media(max-width:560px){#ticketIntelView .td420-summary{grid-template-columns:1fr 1fr!important}#ticketIntelView .td420-price{padding:11px 10px!important}#ticketIntelView .td420-price b{font-size:14px!important}#ticketIntelView .td420-card.td420-expanded .td331-priceflow{grid-template-columns:1fr 1fr!important}}
`;document.head.appendChild(s)}
function cellByLabel(flow,label){return [...(flow?.children||[])].find(x=>String(x.querySelector('span')?.textContent||'').trim().toLowerCase()===label.toLowerCase())||null}
function clonePrice(flow,label,cls,fallback='—'){const src=cellByLabel(flow,label),b=src?.querySelector('b')?.textContent?.trim()||fallback,small=src?.querySelector('small')?.textContent?.trim()||'';return `<div class="td420-price ${cls}"><span>${esc(label==='Trh / ks'?'Trh':label==='Doporučit'?'Doporučení':label)}</span><b>${esc(b)}</b>${small?`<small>${esc(small)}</small>`:''}</div>`}
function signature(card){const flow=card.querySelector('.td331-priceflow'),parts=[...flow?.querySelectorAll('.td331-price')||[]].map(x=>`${x.querySelector('span')?.textContent}:${x.querySelector('b')?.textContent}:${x.querySelector('small')?.textContent}`).join('|'),sig=card.querySelector('.td331-signal small')?.textContent||'',reason=card.querySelector('.td331-reason')?.textContent||'';return `${parts}#${sig}#${reason}`}
function renderCard(card){if(!card.matches('[data-inventory-card]'))return;card.classList.add('td420-card');const flow=card.querySelector('.td331-priceflow'),top=card.querySelector('.td331-ticket-top'),signal=card.querySelector('.td331-signal');if(!flow||!top)return;let summary=card.querySelector(':scope > .td420-summary');if(!summary){summary=document.createElement('div');summary.className='td420-summary';top.insertAdjacentElement('afterend',summary)}const sig=signature(card);if(summary.dataset.sig!==sig){summary.dataset.sig=sig;summary.innerHTML=[clonePrice(flow,'Trh / ks','market'),clonePrice(flow,'Moje cena','mine'),clonePrice(flow,'Minimum','floor'),clonePrice(flow,'Doporučit','decision')].join('')}let source=top.querySelector('.td420-source');if(!source){source=document.createElement('div');source.className='td420-source';top.querySelector('div')?.appendChild(source)}const signalStrong=signal?.querySelector('strong')?.textContent?.trim()||'',signalSmall=signal?.querySelector('small')?.textContent?.trim()||'';source.textContent=[signalStrong,signalSmall].filter(Boolean).join(' · ');const actions=card.querySelector('.td331-ticket-actions');if(actions&&!actions.querySelector('[data-ui420-more]')){const b=document.createElement('button');b.type='button';b.className='td420-more';b.dataset.ui420More='1';b.textContent='Více';b.addEventListener('click',()=>{card.classList.toggle('td420-expanded');b.textContent=card.classList.contains('td420-expanded')?'Méně':'Více'});actions.appendChild(b)}}
function render(){ensureCss();const host=document.querySelector('#ticketIntelView');if(!host)return;for(const card of host.querySelectorAll('[data-inventory-card]'))renderCard(card);document.documentElement.dataset.ticketUi420='1';window.__KAMIL_TICKET_UI420__={version:VERSION,healthy:true,count:host.querySelectorAll('.td420-card').length,at:Date.now()}}
function schedule(ms=120){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketUi420(){if(bound)return;bound=true;ensureCss();for(const ev of ['kamil:view-change','kamil:ticket-price374-updated','kamil:ticket-refresh397-done','kamil:ticket-manual398-saved','kamil:ticket-clipboard403-saved','kamil:ticket-source382-saved'])window.addEventListener(ev,()=>schedule());const host=document.querySelector('#ticketIntelView');if(host)new MutationObserver(()=>schedule(180)).observe(host,{childList:true,subtree:true});schedule();setTimeout(()=>schedule(),900)}
