import {cloudClient,session} from './cloud.js';
import {loadTicketCloud660} from './ticketCloud660.js';
import {ownEvent1100,ownObserver1100,schedule1100} from './runtimeOwnership1100.js';
import {planTicketGmailBatch1215} from '../lib/ticket-gmail-batch1215.js';

const VERSION=1216,OWNER='tickets.gmail429',N=v=>Number(v||0);let bound=false,busy=false,state={configured:false,count:0,updates:[],unmatched:[],review:[],replays:[],error:null};
const active=()=>!!document.querySelector('#view-tickets.on,#view-tickets.active,[data-view-panel="tickets"].on,[data-view-panel="tickets"].active');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function durableContext(){const c=await cloudClient(),sess=await session();if(!c||!sess)throw new Error('Cloud session chybí.');const [sync,tx]=await Promise.all([c.from('ticket_gmail_sync1215').select('checkpoint').eq('user_id',sess.user.id).maybeSingle(),c.from('ticket_gmail_state1215').select('ticket_id,payload').eq('user_id',sess.user.id)]);if(sync.error)throw new Error(`OS1215 sync state není dostupný: ${sync.error.message||sync.error.code||'MIGRATION_REQUIRED'}`);if(tx.error)throw new Error(`OS1215 ticket state není dostupný: ${tx.error.message||tx.error.code||'MIGRATION_REQUIRED'}`);return{c,sess,checkpoint:sync.data?.checkpoint||null,states:tx.data||[]}}
async function api(checkpoint){const r=await fetch('/api/ticket-gmail-sync?mode=tickets',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({checkpoint:checkpoint||null})}),raw=await r.text();let j;try{j=JSON.parse(raw)}catch{throw new Error(`Gmail sync nevrátil JSON (${r.status})`)}if(!r.ok||!j.ok)throw new Error(j.error||`Gmail sync HTTP ${r.status}`);return j}
async function reconcile(messages,cloud,durable,nextCheckpoint){const plan=planTicketGmailBatch1215({messages,inventory:cloud.inventory||[],states:durable.states||[],checkpoint:nextCheckpoint}),blocked=plan.unmatched.length+plan.review.length>0,checkpoint=blocked?(durable.checkpoint||{}):(nextCheckpoint||durable.checkpoint||{});const {data,error}=await durable.c.rpc('commit_ticket_gmail_batch1215',{p_items:plan.items,p_checkpoint:checkpoint});if(error)throw new Error(`OS1215 atomic commit selhal: ${error.message||error.code||'RPC_FAILED'}`);if(!data?.ok)throw new Error('OS1215 atomic commit nebyl potvrzen.');return{updates:plan.items.map(x=>({id:x.ticketId,order:x.orderId,patch:x.patch})),unmatched:plan.unmatched,review:plan.review,replays:plan.replays,checkpointCommitted:!blocked,commit:data}}
function ensureCss(){if(document.querySelector('style[data-gm429]'))return;const s=document.createElement('style');s.dataset.gm429='1';s.textContent=`#ticketIntelView .gm429{margin:10px 0 0;border:1px solid rgba(255,255,255,.07);border-radius:12px;background:#11161d;color:#d9e1e9;padding:10px 12px}.gm429-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.gm429 span{display:block;font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#7d8793}.gm429 b{display:block;margin-top:3px;font-size:11px}.gm429 small{display:block;margin-top:2px;color:#7f8996;font-size:8.5px}.gm429 button{min-height:30px;padding:0 10px;border:1px solid rgba(255,255,255,.09);border-radius:9px;background:#151b23;color:#d4dae1;font-size:9px;font-weight:850;cursor:pointer}.gm429-list{margin-top:8px;padding-top:8px;border-top:1px solid rgba(255,255,255,.06)}.gm429-item{display:flex;justify-content:space-between;gap:10px;padding:5px 0;font-size:9px;color:#8f99a5}.gm429-good{color:#7fd0a2}.gm429-warn{color:#e7be71}`;document.head.appendChild(s)}
function box(){if(!active())return null;const host=document.querySelector('#ticketIntelView .hub421-body')||document.querySelector('#ticketIntelView .td331');if(!host)return null;let el=document.querySelector('#ticketIntelView [data-gmail429]');if(!el){el=document.createElement('section');el.dataset.gmail429='1';el.className='gm429';host.appendChild(el)}return el}
function paint(){if(!active())return;ensureCss();const el=box();if(!el)return;const {configured=false,count=0,updates=[],unmatched=[],review=[],replays=[],error=null}=state,blocked=unmatched.length+review.length;el.innerHTML=`<div class="gm429-head"><div><span>GMAIL RECONCILIATION · OS1216</span><b class="${configured?'gm429-good':'gm429-warn'}">${error?'CHYBA':configured?'PŘIPOJENO':'BACKEND NEPŘIPOJEN'}</b><small>${error?esc(error):configured?`${count} Viagogo mailů · ${updates.length} atomických změn · ${replays.length} replay · ${unmatched.length} bez order ID · ${review.length} k ověření${blocked?' · checkpoint pozastaven':''}`:'Kód je připravený; chybí Google OAuth proměnné ve Vercelu.'}</small></div><button data-gm429-sync ${busy?'disabled':''}>${busy?'Synchronizuji…':'Synchronizovat'}</button></div>${blocked?`<div class="gm429-list">${[...review,...unmatched].slice(0,5).map(m=>`<div class="gm429-item"><span>${esc(m.type)} · ${esc(m.order_id)}</span><span>${esc(m.reviewReason||m.subject||'ověřit')}</span></div>`).join('')}</div>`:''}`}
async function run(force=false){if(busy||!active())return;let last=0;try{last=N(localStorage.getItem('kamil.gmail429.last')||0)}catch{}if(!force&&Date.now()-last<6*36e5){paint();return}busy=true;paint();try{const durable=await durableContext();if(!active())return;const j=await api(durable.checkpoint);if(!active())return;if(!j.configured){state={configured:false,count:0,updates:[],unmatched:[],review:[],replays:[],error:null};return}const cloud=await loadTicketCloud660();if(!active())return;if(!cloud?.ok)throw new Error('Ticket cloud není dostupný.');const result=await reconcile(j.messages||[],cloud,durable,j.checkpoint||null);state={configured:true,count:j.count||0,...result,error:null};try{localStorage.setItem('kamil.gmail429.last',String(Date.now()))}catch{}if(result.updates.length){window.dispatchEvent(new CustomEvent('kamil:ticket-reconcile412-saved',{detail:{source:'gmail-os1216',count:result.updates.length}}));window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}))}}catch(e){state={configured:true,count:0,updates:[],unmatched:[],review:[],replays:[],error:String(e?.message||e)}}finally{busy=false;window.__KAMIL_TICKET_GMAIL429__={version:VERSION,healthy:!state.error,...state,runtimeOwner:OWNER,at:Date.now()};paint()}}
function schedule(ms=900){if(!active())return;schedule1100(OWNER,'sync',()=>{if(!active())return;paint();void run(false)},ms,{pauseWhenHidden:true})}
function onClick(event){if(!active())return;const b=event.target.closest('[data-gm429-sync]');if(b&&!busy)void run(true)}
export function installTicketGmailSync429(){if(bound)return;bound=true;ensureCss();ownEvent1100(OWNER,window,'kamil:view-change',e=>{if(e.detail==='tickets')schedule()});const host=document.querySelector('#ticketIntelView');if(host){ownObserver1100(OWNER,host,{childList:true,subtree:true},()=>{if(active())paint()});ownEvent1100(OWNER,host,'click',onClick)}if(active())schedule(2500)}
