const VERSION=439,N=v=>Number(v||0);let bound=false,timer=0;
const fmt=v=>Number.isFinite(Number(v))?`${Math.round(Number(v)).toLocaleString('cs-CZ')} Kč`:'—';
const pct=v=>Number.isFinite(Number(v))?`${v>=0?'+':''}${Number(v).toFixed(1)} %`:'—';
const key=s=>String(s||'').split(' - ')[0].trim().toLowerCase();
function build(){const cmd=window.__KAMIL_TICKET_COMMANDER435__,risk=window.__KAMIL_TICKET_RISK438__,comp=window.__KAMIL_TICKET_COMPARABLE437__;if(!cmd?.rows?.length||!risk)return null;const compMap=new Map((comp?.rows||[]).map(x=>[String(x.r.id),x])),eventMap=new Map((risk.eventRows||[]).map(x=>[key(x.name),x]));const rows=cmd.rows.map(x=>{const c=compMap.get(String(x.r.id)),er=eventMap.get(key(x.r.event_name)),share=N(er?.share),histEdge=N(c?.comparable?.edgeRoi),base=x.commander.code,portfolioPenalty=Math.max(0,share-25)*2+Math.max(0,N(er?.var95)/(Math.max(1,N(er?.capital)))*100-20),fit=Math.max(0,Math.min(100,75+histEdge*.6-portfolioPenalty+(N(x.predict?.demand)-50)*.25));let action=base,reason=x.commander.reason,budget=N(x.buyBudget?.max);if(share>=30){budget=0;if(!/PRODAT|ZLEVNIT|UVOLNIT/.test(action))action='NEPŘIKUPOVAT';reason=`Event tvoří ${share.toFixed(1)} % kapitálu; portfolio limit má přednost.`}else if(fit<35&&budget>0){budget=Math.round(budget*.35/100)*100;reason+=` Portfolio fit pouze ${Math.round(fit)}/100.`}else if(histEdge<-10&&/DRŽET/.test(action)){action='ZVÁŽIT EXIT';reason=`Risk ROI je o ${pct(Math.abs(histEdge))} pod historií comparable skupiny.`}const urgency=(/PRODAT/.test(action)?100:/ZLEVNIT|EXIT|UVOLNIT/.test(action)?80:/NEPŘIKUPOVAT/.test(action)?65:40)+N(x.pressure)+(100-fit)*.35;return{...x,portfolio:{fit,share,histEdge,var95:N(er?.var95),action,reason,budget,urgency}}}).sort((a,b)=>b.portfolio.urgency-a.portfolio.urgency);return{rows,var95:risk.var95,stressLoss:risk.stressLoss,rotation:risk.rotation}}
function ensureCss(){if(document.querySelector('style[data-cmd439]'))return;const s=document.createElement('style');s.dataset.cmd439='1';s.textContent=`#ticketIntelView .cmd439{margin:0 0 12px;border:1px solid #365a72;border-radius:13px;background:#081923;color:#deedf6;overflow:hidden}.cmd439-head{display:grid;grid-template-columns:1.45fr repeat(4,1fr);gap:8px;padding:11px 12px}.cmd439 span{display:block;font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#789ab3}.cmd439 b{display:block;margin-top:3px;font-size:13px}.cmd439 small{display:block;margin-top:2px;color:#7b91a3;font-size:9px}.cmd439-list{border-top:1px solid #203746}.cmd439-row{display:grid;grid-template-columns:1.35fr .75fr .75fr .85fr .9fr;gap:8px;padding:9px 12px;border-top:1px solid #172c38}.cmd439-sell{color:#ff9aa5}.cmd439-good{color:#8bd8ad}.cmd439-warn{color:#efc17c}.cmd439-chip{display:inline-flex;margin-top:5px;padding:3px 6px;border:1px solid #355267;border-radius:999px;font-size:8px;color:#a9c6dd}@media(max-width:900px){.cmd439-head,.cmd439-row{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function paintCards(rows){for(const x of rows){const card=document.querySelector(`#ticketIntelView [data-ticket-detail="${CSS.escape(String(x.r.id))}"]`)?.closest('[data-inventory-card]');if(!card)continue;let chip=card.querySelector('.cmd439-chip');const top=card.querySelector('.td331-ticket-top>div');if(!chip&&top){chip=document.createElement('span');chip.className='cmd439-chip';top.appendChild(chip)}if(chip){chip.textContent=`portfolio fit ${Math.round(x.portfolio.fit)}/100 · share ${x.portfolio.share.toFixed(1)}%`;chip.classList.toggle('cmd439-warn',x.portfolio.fit<45)}card.dataset.portfolioFit439=String(Math.round(x.portfolio.fit))}}
function panel(m){const host=document.querySelector('#ticketIntelView .td331');if(!host)return;let box=host.querySelector('[data-cmd439]');if(!box){box=document.createElement('section');box.dataset.cmd439='1';box.className='cmd439';const old=host.querySelector('[data-cmd435]');old?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.querySelector('.td331-hero')?.insertAdjacentElement('afterend',box)}const top=m.rows.slice(0,8),avg=top.length?top.reduce((a,x)=>a+x.portfolio.fit,0)/top.length:0;box.innerHTML=`<div class="cmd439-head"><div><span>COMMANDER 3.1 · OS439</span><b>EV × historie × portfolio risk</b><small>Finální priorita zohledňuje comparable eventy, event share a portfolio stress.</small></div><div><span>AVG PORTFOLIO FIT</span><b>${Math.round(avg)}/100</b></div><div><span>VAR 95</span><b>${fmt(m.var95)}</b></div><div><span>STRESS P/L</span><b class="${m.stressLoss<0?'cmd439-sell':'cmd439-good'}">${fmt(m.stressLoss)}</b></div><div><span>ROTACE / ROK</span><b>${N(m.rotation?.turns).toFixed(1)}×</b></div></div><div class="cmd439-list">${top.map(x=>`<div class="cmd439-row"><div><span>${x.portfolio.action}</span><b class="${/PRODAT|ZLEVNIT|EXIT|UVOLNIT/.test(x.portfolio.action)?'cmd439-sell':x.portfolio.action==='NEPŘIKUPOVAT'?'cmd439-warn':'cmd439-good'}">${x.r.event_name}</b><small>${x.portfolio.reason}</small></div><div><span>FIT</span><b>${Math.round(x.portfolio.fit)}/100</b></div><div><span>EVENT SHARE</span><b>${x.portfolio.share.toFixed(1)} %</b></div><div><span>VS HIST</span><b>${pct(x.portfolio.histEdge)}</b></div><div><span>MAX BUY</span><b>${fmt(x.portfolio.budget)}</b></div></div>`).join('')}</div>`;paintCards(m.rows)}
function refresh(){ensureCss();const m=build();if(!m)return;window.__KAMIL_TICKET_COMMANDER439__={version:VERSION,healthy:true,...m,at:Date.now()};document.documentElement.dataset.ticketCommander439='1';panel(m)}
function schedule(ms=700){clearTimeout(timer);timer=setTimeout(refresh,ms)}
export function installTicketCommander439(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-commander435-updated','kamil:ticket-risk438-updated','kamil:ticket-comparable437-updated'])window.addEventListener(ev,()=>schedule());schedule(5600);setInterval(()=>schedule(0),30000)}
