import {store} from './state.js';
import {h,qs,money,date} from './utils.js';
import {ticketMarketBrain34} from './ticketBrain34.js';

const id='ticketBrain34Host';let queued=false;
const label=a=>({VERIFY_DATA:'OPRAVIT DATA',SELL_NOW:'PRODAT TEĎ',REPRICE:'ZLEVNIT',LIST_NOW:'VYSTAVIT',CHECK_MARKET:'OBNOVIT TRH',HOLD:'DRŽET'})[a]||a;
const fmt=v=>v===null||v===undefined?'—':money(v);
function row(x){
 const seats=[x.section?`sektor ${x.section}`:'',x.row?`řada ${x.row}`:''].filter(Boolean).join(' · '),mismatch=x.listedQty!==x.qty;
 return `<div class="card"><div class="card-head"><div><div class="eyebrow">${h(date(x.date))} · ${x.qty} ks${seats?` · ${h(seats)}`:''}</div><h3>${h(x.eventName)}</h3><p class="muted">${h(x.reason)}</p></div><span class="decision-action ${h(x.tone)}">${h(label(x.action))}</span></div>${x.inventoryWarning?`<div class="decision-note bad"><b>Evidence nesedí:</b> ${h(x.inventoryWarning)}</div>`:''}${mismatch&&!x.inventoryWarning?`<div class="decision-note warn">Evidence má ${x.qty} ks, listing ${x.listedQty} ks. Než měnit cenu, ověř počet kusů.</div>`:''}<div class="ticket-brain34-price"><span>Nákup / ks<b>${fmt(x.buyPer)}</b></span><span>Tvoje nabídka<b>${fmt(x.currentListPrice)}</b></span><span>Doporučení / market<b>${fmt(x.recommendedPrice)}</b></span><span>Bezpečný floor<b>${fmt(x.breakEven)}</b></span></div><div class="row"><span>Do akce</span><b>${x.eventDays===null?'—':x.eventDays<0?`${Math.abs(x.eventDays)} dní po akci`:x.eventDays===0?'dnes':`${x.eventDays} dní`}</b></div><div class="row"><span>Navržená cena</span><b class="${h(x.tone)}">${fmt(x.suggestedPrice)}</b></div><div class="row"><span>Hrubý rozdíl při současném listingu</span><b class="${Number(x.grossAtList||0)>=0?'good':'bad'}">${x.grossAtList===null?'—':`${x.grossAtList>=0?'+':''}${fmt(x.grossAtList)}`}</b></div><div class="row"><span>Zdroj srovnání</span><b>${h(x.recommendedSource==='VIAGOGO_SNAPSHOT'?'Viagogo snapshot':x.recommendedSource==='MARKET'?'market data':'chybí')}</b></div></div>`;
}
function render(){
 const view=qs('#ticketsView');if(!view?.querySelector('.view-head'))return;qs(`#${id}`,view)?.remove();const brain=ticketMarketBrain34(store.get()),host=document.createElement('div');host.id=id;host.className='ticket-brain34';
 host.innerHTML=`<div class="card brain34-card"><div class="card-head"><div><div class="eyebrow">TICKET MARKET BRAIN 2.0 / 34.0</div><h2>Co držet, zlevnit a prodat</h2><p class="muted">Jedna vrstva nad starým repricingem: nákupní cena + tvoje nabídka + doporučení/market + čas do akce + kontrola evidence.</p></div><span class="status ${brain.counts.verify||brain.counts.sell?'bad':brain.counts.reprice?'warn':'good'}">${brain.total} aktivních pozic</span></div><div class="metric-strip"><div class="metric"><span>Opravit data</span><b class="${brain.counts.verify?'bad':''}">${brain.counts.verify}</b></div><div class="metric"><span>Prodat teď</span><b class="${brain.counts.sell?'bad':''}">${brain.counts.sell}</b></div><div class="metric"><span>Zlevnit</span><b class="${brain.counts.reprice?'warn':''}">${brain.counts.reprice}</b></div><div class="metric"><span>Vystavit</span><b>${brain.counts.list}</b></div><div class="metric"><span>Obnovit trh</span><b>${brain.counts.market}</b></div></div><div class="decision-note">${h(brain.note)}</div></div>${brain.rows.slice(0,12).map(row).join('')}`;
 const anchor=qs('#currentTicketSnapshot33',view)||qs('#ticketMarketIntel32Host',view)||view.querySelector('.view-head');anchor?.insertAdjacentElement('afterend',host);
}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;render()})}
function start(){const view=qs('#ticketsView');if(view)new MutationObserver(()=>{if(!qs(`#${id}`,view))schedule()}).observe(view,{childList:true,subtree:false});store.subscribe(()=>{if(qs('#view-tickets')?.classList.contains('on'))schedule()});window.addEventListener('kamil:navigate',schedule);setTimeout(render,450)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
