import {loadTicketCloud660} from './ticketCloud660.js';
import {h,money} from './utils.js';

const n=x=>Number(x||0);
const active=r=>['LISTED','NOT_LISTED'].includes(r?.market_status);
const code=s=>s?.recommendation_code||null;
const daysTo=date=>{if(!date)return null;const t=Date.parse(`${String(date).slice(0,10)}T12:00:00Z`);return Number.isFinite(t)?Math.ceil((t-Date.now())/86400000):null};
const conf=s=>{const x=Number(s?.multi_market_confidence);return Number.isFinite(x)?x:null};
const label=c=>({LOWER:'ZLEVNIT',LIST:'VYSTAVIT',RAISE:'ZDRAŽIT',VERIFY_DATA:'OVĚŘIT DATA',OFFICIAL_COMPETITION:'HLÍDAT OFICIÁL',ASK_MISSING:'DOPLNIT CENU',HOLD:'DRŽET',FETCH_ERROR:'OPRAVIT ZDROJ',SOURCE_MISSING:'DOPLNIT ZDROJ',NO_PRICE:'OVĚŘIT CENU'})[c]||'SLEDOVAT';
const tone=c=>['LOWER','VERIFY_DATA','FETCH_ERROR','SOURCE_MISSING','OFFICIAL_COMPETITION'].includes(c)?'critical':['LIST','RAISE'].includes(c)?'success':'neutral';
const roundPrice=x=>Math.max(0,Math.round(n(x)/10)*10);
function floorMargin(d){if(d===null||d>30)return .25;if(d>14)return .20;if(d>7)return .15;return .10}
function reviewIn(d){if(d===null)return 7;if(d<=3)return 1;if(d<=7)return 1;if(d<=14)return 2;if(d<=30)return 3;return 7}
function repricingFor(r,s,d,market,ask,buy,confidence){if(!buy)return{status:'NO_BUY',target:0,floor:0,margin:null,review:reviewIn(d),note:'chybí nákupní cena'};const floorPct=floorMargin(d),floor=roundPrice(buy*(1+floorPct)),rec=n(s?.recommended_ask_czk),marketTarget=market?roundPrice(market*.98):0;let raw=rec||marketTarget||ask||floor;if(marketTarget&&raw)raw=Math.min(raw,marketTarget);let target=roundPrice(Math.max(floor,raw));const marketBelowFloor=!!(market&&market<floor),lowConfidence=confidence!==null&&confidence<65;if(marketBelowFloor)return{status:'EXIT_RISK',target:roundPrice(market),floor,margin:(market/buy-1)*100,review:1,note:'trh je pod orientačním minimem; nerozhodovat automaticky'};if(lowConfidence&&!market)return{status:'VERIFY',target:0,floor,margin:null,review:1,note:'nejdřív ověřit market data'};if(ask&&target>ask*1.15&&code(s)!=='RAISE')target=ask;const margin=(target/buy-1)*100;return{status:'OK',target,floor,margin,review:reviewIn(d),note:`orientační minimum drží hrubou marži ${Math.round(floorPct*100)} % před poplatky`}}
function pressureFactor(d,c,confidence,ask,market){let p=0;if(d!==null){if(d<=3)p+=.55;else if(d<=7)p+=.4;else if(d<=14)p+=.25;else if(d<=30)p+=.1}if(c==='LOWER')p+=.3;else if(['VERIFY_DATA','FETCH_ERROR','SOURCE_MISSING'].includes(c))p+=.2;if(confidence!==null&&confidence<65)p+=.12;if(market&&ask>market*1.15)p+=.2;return Math.min(1,p)}
function actionFor(r,s,d,market,ask,repricing){const c=code(s);if(repricing.status==='EXIT_RISK')return{key:'verify',label:'EXIT RISK',detail:`trh ${money(repricing.target)} je pod minimem ${money(repricing.floor)} / ks`};if(repricing.status==='VERIFY')return{key:'verify',label:'Ověřit zdroj',detail:'bez spolehlivé ceny nerepricingovat'};if(c==='LOWER')return{key:'lower',label:'Zlevnit teď',detail:repricing.target?`cílit kolem ${money(repricing.target)} / ks`:'srovnat cenu s trhem'};if(c==='LIST')return{key:'list',label:'Vystavit',detail:repricing.target?`start kolem ${money(repricing.target)} / ks`:'doplnit prodejní cenu'};if(c==='RAISE')return{key:'raise',label:'Zvážit zdražení',detail:repricing.target?`cílit kolem ${money(repricing.target)} / ks`:'ověřit horní hranici trhu'};if(['VERIFY_DATA','FETCH_ERROR','SOURCE_MISSING','NO_PRICE'].includes(c))return{key:'verify',label:'Ověřit zdroj',detail:r.stubhub_url?'otevřít StubHub / obnovit market scan':'doplnit spolehlivý market zdroj'};if(c==='ASK_MISSING')return{key:'price',label:'Doplnit cenu',detail:repricing.target?`návrh ${money(repricing.target)} / ks`:'nejdřív ověřit trh'};if(c==='OFFICIAL_COMPETITION')return{key:'watch',label:'Hlídát oficiál',detail:'nepřestřelit cenu dokud běží primární prodej'};if(d!==null&&d<=7&&ask&&market&&ask>market*1.1)return{key:'lower',label:'Snížit tlakem času',detail:repricing.target?`cílit ${money(repricing.target)} / ks`:`akce za ${Math.max(0,d)} d a cena je nad trhem`};return{key:'hold',label:'Držet',detail:repricing.target?`další kontrola za ${repricing.review} d`:'bez silného důvodu k zásahu'}}
function scoreOne(r,s){let score=0,reasons=[],c=code(s),d=daysTo(r.event_date),market=n(s?.market_price_czk),ask=n(r.ask_each_czk),buy=n(r.buy_each_czk),confidence=conf(s),qty=n(r.qty)||1;
 if(d!==null){if(d<=3){score+=38;reasons.push(`akce za ${Math.max(0,d)} d`)}else if(d<=7){score+=30;reasons.push(`akce za ${d} d`)}else if(d<=14){score+=20;reasons.push(`akce za ${d} d`)}else if(d<=30){score+=10;reasons.push(`akce za ${d} d`)}}
 if(c==='LOWER'){score+=38;reasons.push('trh doporučuje zlevnit')}else if(c==='VERIFY_DATA'){score+=34;reasons.push('rozhodnutí blokují data')}else if(c==='FETCH_ERROR'||c==='SOURCE_MISSING'){score+=30;reasons.push('chybí spolehlivý zdroj')}else if(c==='OFFICIAL_COMPETITION'){score+=24;reasons.push('stále běží oficiální prodej')}else if(c==='LIST'){score+=22;reasons.push('je vhodné vystavit')}else if(c==='RAISE'){score+=14;reasons.push('je prostor zdražit')}else if(c==='ASK_MISSING'){score+=18;reasons.push('chybí tvoje prodejní cena')}
 if(confidence!==null&&confidence<65){score+=15;reasons.push(`confidence ${Math.round(confidence)} %`)}
 if(market&&ask&&ask>market*1.15){score+=18;reasons.push(`tvoje cena je ${Math.round((ask/market-1)*100)} % nad trhem`)}
 if(market&&buy){const roi=market/buy-1;if(roi>=1){score+=12;reasons.push(`tržní spread +${Math.round(roi*100)} %`)}else if(roi>=.5){score+=8;reasons.push(`tržní spread +${Math.round(roi*100)} %`)}}
 if(r.stubhub_url&&!n(s?.stubhub_price_czk)){score+=5;reasons.push('StubHub URL je spárovaná, cena čeká na API')}
 const repricing=repricingFor(r,s,d,market,ask,buy,confidence);if(repricing.status==='EXIT_RISK'){score+=35;reasons.push('trh pod orientačním minimem')}const reference=n(s?.recommended_ask_czk)||market,profit=Math.max(0,(reference-buy)*qty),pressure=pressureFactor(d,c,confidence,ask,market),profitAtRisk=Math.round(profit*pressure),capitalNoMarket=!market?Math.max(n(r.buy_total_czk),buy*qty):0,action=actionFor(r,s,d,market,ask,repricing);
 return{row:r,snap:s,score,c,d,reasons:reasons.slice(0,3),market,ask,buy,confidence,profit,profitAtRisk,capitalNoMarket,pressure,action,repricing};
}
function allRows(cloud){return cloud.inventory.filter(active).map(r=>scoreOne(r,cloud.latest?.get(r.id)||null))}
function priorityRows(rows){return rows.filter(x=>x.score>0).sort((a,b)=>b.score-a.score||(a.d??999)-(b.d??999)).slice(0,5)}
function portfolioRisk(rows){return{profitAtRisk:rows.reduce((a,x)=>a+x.profitAtRisk,0),capitalNoMarket:rows.reduce((a,x)=>a+x.capitalNoMarket,0),urgent:rows.filter(x=>x.d!==null&&x.d>=0&&x.d<=14).length,overpriced:rows.filter(x=>x.market&&x.ask>x.market*1.15).length,exitRisk:rows.filter(x=>x.repricing.status==='EXIT_RISK').length}}
function actionSummary(rows){const out={lower:0,list:0,raise:0,verify:0,price:0,watch:0,hold:0};for(const x of rows)out[x.action.key]=(out[x.action.key]||0)+1;return out}
function itemHtml(x,i){const c=x.c,why=x.reasons.join(' · ')||'čeká na další tržní kontrolu',rp=x.repricing;return `<div class="card" style="padding:12px;margin:8px 0"><div class="row"><div><b>${i+1}. ${h(x.row.event_name)}</b><div class="muted">${h(x.row.section||'bez sekce')} · ${n(x.row.qty)||1} ks${x.d!==null?` · ${x.d<0?'po akci':x.d===0?'dnes':`za ${x.d} dní`}`:''}</div></div><span class="tmw-rec ${rp.status==='EXIT_RISK'?'critical':tone(c)}">${rp.status==='EXIT_RISK'?'EXIT RISK':h(label(c))}</span></div><div class="row"><span>Další nejlepší krok</span><b>${h(x.action.label)} · ${h(x.action.detail)}</b></div><div class="row"><span>Auto repricing dnes</span><b>${rp.target?money(rp.target):'—'} / ks · minimum ${rp.floor?money(rp.floor):'—'} · kontrola za ${rp.review} d</b></div>${rp.margin!==null?`<div class="row"><span>Hrubá marže návrhu</span><b>${Math.round(rp.margin)} % <span class="muted">před poplatky</span></b></div>`:''}<div class="row"><span>Proč je nahoře</span><b>${h(why)}</b></div><div class="row"><span>Nákup / moje cena / trh</span><b>${money(x.buy)} · ${x.ask?money(x.ask):'—'} · ${x.market?money(x.market):'—'}</b></div>${x.profitAtRisk?`<div class="row"><span>Odhad zisku v riziku</span><b>${money(x.profitAtRisk)}</b></div>`:''}<div class="muted" style="margin-top:6px">${h(rp.note)}</div></div>`}
export async function enhanceTicketPriority87(){const host=document.querySelector('#ticketIntelView');if(!host||host.querySelector('[data-ticket-priority87]'))return;const cloud=await loadTicketCloud660();if(!cloud?.ok)return;const rows=allRows(cloud),top=priorityRows(rows),risk=portfolioRisk(rows),actions=actionSummary(rows),wrap=document.createElement('section');wrap.dataset.ticketPriority87='1';wrap.className='card';wrap.style.margin='18px 0';wrap.innerHTML=`<div class="row"><div><div class="eyebrow">TICKETS 90 · AUTO REPRICING</div><h2 style="margin:4px 0">Co řešit jako první</h2><p class="muted">OS navrhuje dnešní cenu a minimální hrubou hranici podle nákupky a času do akce. Minimum je před poplatky platformy; pokud je trh níž, automatiku zastaví jako EXIT RISK.</p></div><span class="tmw-rec ${top.length?'critical':'success'}">${top.length?`${top.length} priorit`:'NIC NEHOŘÍ'}</span></div><div class="metric-strip" style="margin:12px 0"><div class="metric"><span>Profit at Risk</span><b>${money(risk.profitAtRisk)}</b></div><div class="metric"><span>Kapitál bez market ceny</span><b>${money(risk.capitalNoMarket)}</b></div><div class="metric"><span>Akce do 14 dní</span><b>${risk.urgent}</b></div><div class="metric"><span>EXIT RISK</span><b>${risk.exitRisk}</b></div></div><div class="ticket-source-line" style="margin:10px 0"><span class="tmw-rec critical">ZLEVNIT ${actions.lower}</span><span class="tmw-rec success">VYSTAVIT ${actions.list}</span><span class="tmw-rec neutral">OVĚŘIT ${actions.verify}</span><span class="tmw-rec neutral">DOPLNIT CENU ${actions.price}</span><span class="tmw-rec neutral">DRŽET ${actions.hold}</span></div>${top.map(itemHtml).join('')||'<p class="muted">Aktivní vstupenky teď nemají žádný silný zásahový signál.</p>'}`;const hero=host.querySelector('.ticket-page-hero');if(hero?.parentNode)hero.parentNode.insertBefore(wrap,hero.nextSibling);else host.prepend(wrap)}
