import {h,formModal,modal} from './utils.js';
import {loadTicketCloud660,updateTicketTracking660} from './ticketCloud660.js';
const VERSION=382;
let observer=null;
const valid=(url,host)=>!url||new RegExp(`^https:\\/\\/(?:[^/]+\\.)?${host.replace('.','\\.')}\\/`,'i').test(url);
async function edit(id){const cloud=await loadTicketCloud660();if(!cloud?.ok)throw cloud?.error||new Error('Ticket cloud není dostupný');const r=(cloud.inventory||[]).find(x=>String(x.id)===String(id));if(!r)return;const data=await formModal(`Tržní zdroje · ${h(r.event_name||'Vstupenka')}`,`<label class="field"><span>Viagogo event URL</span><input name="viagogo" type="url" value="${h(r.viagogo_url||'')}" placeholder="https://www.viagogo.com/.../E-123456"></label><label class="field"><span>StubHub event URL</span><input name="stubhub" type="url" value="${h(r.stubhub_url||'')}" placeholder="https://www.stubhub.com/.../event/123456789/"></label><label class="field"><span>Řada</span><input name="row" value="${h(r.row_label||'')}" placeholder="např. 12, A, B5"></label><p class="muted">Přímé event URL zvyšují přesnost trhu. Řada umožní porovnávat skutečně podobná místa.</p>`,{submitLabel:'Uložit a přepočítat'});if(!data)return;const viagogo=String(data.viagogo||'').trim(),stubhub=String(data.stubhub||'').trim(),row=String(data.row||'').trim();if(!valid(viagogo,'viagogo.com')){await modal('Neplatný Viagogo odkaz','<p>Vlož přímý odkaz na konkrétní event z Viagogo.</p>',[{label:'OK',value:null,primary:true}]);return}if(!valid(stubhub,'stubhub.com')){await modal('Neplatný StubHub odkaz','<p>Vlož přímý odkaz na konkrétní event ze StubHub.</p>',[{label:'OK',value:null,primary:true}]);return}const out=await updateTicketTracking660(r.id,{viagogoUrl:viagogo||null,stubhubUrl:stubhub||null,rowLabel:row||null});if(!out?.ok)throw out?.error||new Error('Uložení zdrojů selhalo');window.dispatchEvent(new CustomEvent('kamil:ticket-source382-saved',{detail:{id:r.id}}));window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}))}
function wire(){const host=document.querySelector('#ticketIntelView');if(!host)return;for(const current of host.querySelectorAll('[data-ticket-source]')){if(current.dataset.source382==='1')continue;const btn=current.cloneNode(true);btn.dataset.source382='1';btn.textContent='Zdroj + řada';current.replaceWith(btn);btn.addEventListener('click',async()=>{btn.disabled=true;const old=btn.textContent;btn.textContent='Ukládám…';try{await edit(btn.dataset.ticketSource)}catch(e){console.error('[ticket-source382]',e);await modal('Uložení selhalo',`<p>${h(e?.message||'Zdroj se nepodařilo uložit.')}</p>`,[{label:'OK',value:null,primary:true}])}finally{btn.disabled=false;btn.textContent=old}})}}
function observe(){const host=document.querySelector('#ticketIntelView');if(!host)return false;wire();observer?.disconnect();observer=new MutationObserver(()=>wire());observer.observe(host,{childList:true,subtree:true});window.__KAMIL_TICKET_SOURCE382_OBSERVER__=observer;return true}
export function installTicketSourceEditor382(){if(document.documentElement.dataset.ticketSource382==='1')return;document.documentElement.dataset.ticketSource382='1';if(!observe()){const t=setInterval(()=>{if(observe())clearInterval(t)},250);setTimeout(()=>clearInterval(t),8000)}window.addEventListener('kamil:view-change',e=>{if(e.detail==='tickets')setTimeout(wire,200)});window.__KAMIL_TICKET_SOURCE382__={version:VERSION,healthy:true,at:Date.now()}}
