const VERSION=446,N=v=>Number(v||0),clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));let bound=false,timer=0;
const SOLD=new Set(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID']);
const fmt=v=>Number.isFinite(Number(v))?`${Math.round(Number(v)).toLocaleString('cs-CZ')} Kč`:'—';
function days(date){const t=Date.parse(date||'');return Number.isFinite(t)?(t-Date.now())/864e5:999}
function grade(s){return s>=82?'A':s>=68?'B':s>=54?'C':s>=40?'D':'E'}
function build(){const pred=window.__KAMIL_TICKET_PREDICT433__,risk=window.__KAMIL_TICKET_RISK438__,cons=window.__KAMIL_TICKET_CONSENSUS445__;if(!pred?.models?.length)return null;const consMap=new Map((cons?.rows||[]).map(x=>[String(x.r.id),x.consensus])),rows=pred.models.map(m=>{const q=Math.max(1,N(m.r.qty)||1),cap=N(m.r.buy_total_czk)||N(m.r.buy_each_czk)*q,market=N(consMap.get(String(m.r.id))?.price)||N(m.market),d=days(m.r.event_date),liq=N(m.liquidity?.score),conf=N(m.confidence),fit=N(m.portfolio?.fit)||60,lockDays=Math.max(1,N(m.predict?.heldDays)||1),ev=N(m.predict?.opt?.ev),lockScore=clamp((lockDays/60)*55+(cap/Math.max(1000,ev>0?ev:1000))*5+(100-liq)*.25),riskScore=clamp(liq*.25+conf*.25+fit*.2+(100-N(m.pressure))*.15+(d>7?80:d>2?65:40)*.15),scenarios=[.10,0,-.10,-.25].map(move=>{const p=market*(1+move),fee=N(m.fee?.rate)||.15,pl=p*q*(1-fee)-cap;return{move,price:p,pl}}),panic=d<=1&&d>=0,positionGrade=grade(riskScore);return{...m,riskOps:{capital:cap,market,days:d,lockDays,lockScore,riskScore,grade:positionGrade,panic,scenarios}}}),events=new Map();for(const x of rows){const k=String(x.r.event_name||'').split(' - ')[0].trim().toLowerCase(),g=events.get(k)||{name:x.r.event_name,capital:0,n:0,score:0};g.capital+=x.riskOps.capital;g.n++;g.score+=x.riskOps.riskScore;events.set(k,g)}const eventRows=[...events.values()].map(x=>({...x,riskScore:x.score/x.n,grade:grade(x.score/x.n)}));const inv=window.__KAMIL_TICKET_ENGINE426__?.models?.map(x=>x.r)||[];let booked=0,receivable=0,cash=0;const delivery=[],payout=[];for(const r of inv){if(!SOLD.has(String(r.market_status||'')))continue;const profit=N(r.sell_total_czk)-N(r.buy_total_czk);if(['PAYOUT_RECEIVED','PAID'].includes(String(r.market_status||'')))cash+=profit;else receivable+=profit;booked+=profit;if(String(r.market_status)==='SOLD_UNDELIVERED')delivery.push(r);if(String(r.market_status)==='SOLD_WAITING_PAYMENT'&&r.payout_expected_at&&Date.parse(r.payout_expected_at)<Date.now())payout.push(r)}return{rows,eventRows,delivery,payout,cash:{booked,receivable,cash},portfolio:risk}}
function ensureCss(){if(document.querySelector('style[data-ro446]'))return;const s=document.createElement('style');s.dataset.ro446='1';s.textContent=`#ticketIntelView .ro446{margin:0 0 12px;border:1px solid #5a4248;border-radius:12px;background:#160f13;color:#f0e1e3;padding:10px 11px}.ro446-grid{display:grid;grid-template-columns:1.4fr repeat(5,1fr);gap:8px}.ro446 span{display:block;font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#a9878d}.ro446 b{display:block;margin-top:3px;font-size:12px}.ro446 small{display:block;margin-top:2px;color:#a68f94;font-size:8.5px}.ro446-good{color:#8bd8ad}.ro446-warn{color:#efc17c}.ro446-bad{color:#ff9aa5}@media(max-width:900px){.ro446-grid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function paint(m){ensureCss();const host=document.querySelector('#ticketIntelView .td331');if(!host)return;let box=host.querySelector('[data-ro446]');if(!box){box=document.createElement('section');box.dataset.ro446='1';box.className='ro446';const c=host.querySelector('[data-cs445]');c?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.appendChild(box)}const panic=m.rows.filter(x=>x.riskOps.panic).length,weak=m.rows.filter(x=>['D','E'].includes(x.riskOps.grade)).length;box.innerHTML=`<div class="ro446-grid"><div><span>RISK OPS · OS446</span><b>${m.rows.length} pozic · ${m.eventRows.length} eventů</b><small>Risk rating A–E, scenario stress, panic mode, delivery/payout guard a skutečný cash P/L.</small></div><div><span>PANIC &lt;24H</span><b class="${panic?'ro446-bad':'ro446-good'}">${panic}</b></div><div><span>D/E RISK</span><b class="${weak?'ro446-warn':'ro446-good'}">${weak}</b></div><div><span>DELIVERY GUARD</span><b class="${m.delivery.length?'ro446-bad':'ro446-good'}">${m.delivery.length}</b></div><div><span>PAYOUT OVERDUE</span><b class="${m.payout.length?'ro446-bad':'ro446-good'}">${m.payout.length}</b></div><div><span>CASH / RECEIVABLE</span><b>${fmt(m.cash.cash)} / ${fmt(m.cash.receivable)}</b><small>booked ${fmt(m.cash.booked)}</small></div></div>`}
function refresh(){const m=build();if(!m)return;window.__KAMIL_TICKET_RISKOPS446__={version:VERSION,healthy:true,...m,at:Date.now()};document.documentElement.dataset.ticketRiskOps446='1';paint(m);window.dispatchEvent(new CustomEvent('kamil:ticket-riskops446-updated',{detail:{delivery:m.delivery.length,payout:m.payout.length}}))}
function schedule(ms=650){clearTimeout(timer);timer=setTimeout(refresh,ms)}
export function installTicketRiskOps446(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-predict433-updated','kamil:ticket-consensus445-updated','kamil:ticket-reconcile412-saved'])window.addEventListener(ev,()=>schedule());schedule(7400);setInterval(()=>schedule(0),30000)}