const VERSION=444,N=v=>Number(v||0),clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));let bound=false,timer=0;
const strong=a=>/PRODAT|ZLEVNIT|EXIT|UVOLNIT|BUY|KOUPIT|VYSTAVIT/.test(String(a||'').toUpperCase());
function ageHours(m){const t=Date.parse(m?.best?.s?.captured_at||m?.best?.s?.created_at||m?.latest?.captured_at||'');return Number.isFinite(t)?Math.max(0,(Date.now()-t)/36e5):999}
function scoreOne(x){const conf=N(x.confidence),liq=N(x.liquidity?.score),fit=N(x.portfolio?.fit??x.portfolioFit),fresh=ageHours(x),freshScore=fresh<=6?100:fresh<=24?85:fresh<=48?65:fresh<=72?45:20,pair=x.best?.s?.row_label||x.best?.s?.section_label||x.r?.row_label||x.r?.section?90:55,cal=window.__KAMIL_TICKET_CAL_READINESS443__,calScore=cal?.mode==='active'?95:cal?.mode==='drift-stop'?45:75,q=clamp(conf*.32+liq*.20+fit*.18+freshScore*.18+pair*.08+calScore*.04),issues=[];if(conf<60)issues.push('nízká confidence');if(fresh>48)issues.push('stará data');if(pair<70)issues.push('slabý pair match');if(liq<40)issues.push('nízká likvidita');if(cal?.mode==='drift-stop')issues.push('calibration drift-stop');const requested=x.portfolio?.action||x.commander?.code||'DRŽET',blocked=strong(requested)&&(q<62||conf<55||fresh>72),action=blocked?'OVĚŘIT DATA':requested;return{...x,quality:{score:q,freshHours:fresh,pairScore:pair,issues,blocked,requested,action,grade:q>=82?'A':q>=70?'B':q>=58?'C':q>=45?'D':'E'}}}
function build(){const src=window.__KAMIL_TICKET_COMMANDER439__?.rows||window.__KAMIL_TICKET_COMMANDER435__?.rows||window.__KAMIL_TICKET_PREDICT433__?.models||[];if(!src.length)return null;const rows=src.map(scoreOne).sort((a,b)=>N(b.quality.score)-N(a.quality.score)),avg=rows.reduce((a,x)=>a+x.quality.score,0)/rows.length,blocked=rows.filter(x=>x.quality.blocked).length;return{rows,avg,blocked}}
function ensureCss(){if(document.querySelector('style[data-dq444]'))return;const s=document.createElement('style');s.dataset.dq444='1';s.textContent=`#ticketIntelView .dq444{margin:0 0 12px;border:1px solid #355465;border-radius:12px;background:#0a1820;color:#dfedf6;padding:10px 11px}.dq444-grid{display:grid;grid-template-columns:1.4fr repeat(4,1fr);gap:8px}.dq444 span{display:block;font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#7e9bb0}.dq444 b{display:block;margin-top:3px;font-size:12px}.dq444 small{display:block;margin-top:2px;color:#7e929f;font-size:8.5px}.dq444-good{color:#8bd8ad}.dq444-warn{color:#efc17c}.dq444-bad{color:#ff9aa5}@media(max-width:850px){.dq444-grid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function paint(m){ensureCss();const host=document.querySelector('#ticketIntelView .td331');if(!host)return;let box=host.querySelector('[data-dq444]');if(!box){box=document.createElement('section');box.dataset.dq444='1';box.className='dq444';const cmd=host.querySelector('[data-cmd439]');cmd?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.appendChild(box)}const a=m.rows.filter(x=>x.quality.grade==='A').length,weak=m.rows.filter(x=>['D','E'].includes(x.quality.grade)).length;box.innerHTML=`<div class="dq444-grid"><div><span>DECISION QUALITY · OS444</span><b>${Math.round(m.avg)}/100</b><small>Confidence × freshness × liquidity × pair quality × portfolio fit. Silná akce se při slabých datech automaticky zablokuje.</small></div><div><span>A-GRADE</span><b class="dq444-good">${a}</b></div><div><span>BLOCKED ACTIONS</span><b class="${m.blocked?'dq444-bad':'dq444-good'}">${m.blocked}</b></div><div><span>D/E QUALITY</span><b class="${weak?'dq444-warn':'dq444-good'}">${weak}</b></div><div><span>MODE</span><b>${m.blocked?'SAFE GATE':'NORMAL'}</b></div></div>`}
function refresh(){const m=build();if(!m)return;window.__KAMIL_TICKET_QUALITY444__={version:VERSION,healthy:true,...m,at:Date.now()};document.documentElement.dataset.ticketQuality444='1';paint(m);window.dispatchEvent(new CustomEvent('kamil:ticket-quality444-updated',{detail:{avg:m.avg,blocked:m.blocked}}))}
function schedule(ms=600){clearTimeout(timer);timer=setTimeout(refresh,ms)}
export function installTicketDecisionQuality444(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-risk438-updated','kamil:ticket-calibration442-updated'])window.addEventListener(ev,()=>schedule());schedule(6200);setInterval(()=>schedule(0),30000)}