const VERSION=438,N=v=>Number(v||0);let bound=false,timer=0;
const fmt=v=>Number.isFinite(Number(v))?`${Math.round(Number(v)).toLocaleString('cs-CZ')} Kč`:'—';
const pct=v=>Number.isFinite(Number(v))?`${v>=0?'+':''}${Number(v).toFixed(1)} %`:'—';
function eventKey(s=''){return String(s).split(' - ')[0].trim().toLowerCase()}
function build(){const pred=window.__KAMIL_TICKET_PREDICT433__,cmd=window.__KAMIL_TICKET_COMMANDER435__,comp=window.__KAMIL_TICKET_COMPARABLE437__;if(!pred?.models?.length)return null;const rows=pred.models.map(m=>{const q=Math.max(1,N(m.r.qty)||1),cap=N(m.r.buy_total_czk)||N(m.r.buy_each_czk)*q,fee=N(m.fee?.rate)||.15,emergency=N(m.emergency),emergencyNet=emergency?q*emergency*(1-fee)-cap:-cap,unsold=cap*(1-N(m.predict?.p7)),var95=unsold*.65,stressLoss=Math.min(0,emergencyNet);return{...m,cap,unsold,var95,stressLoss}}),total=rows.reduce((a,x)=>a+x.cap,0),var95=rows.reduce((a,x)=>a+x.var95,0),stressLoss=rows.reduce((a,x)=>a+x.stressLoss,0),unsold=rows.reduce((a,x)=>a+x.unsold,0),events=new Map();for(const x of rows){const k=eventKey(x.r.event_name),g=events.get(k)||{name:x.r.event_name,capital:0,var95:0,stressLoss:0,unsold:0};g.capital+=x.cap;g.var95+=x.var95;g.stressLoss+=x.stressLoss;g.unsold+=x.unsold;events.set(k,g)}const eventRows=[...events.values()].map(x=>({...x,share:total?x.capital/total*100:0})).sort((a,b)=>b.var95-a.var95),rot=cmd?.rotation||{medianDays:30,turns:365/30},turnDays=Math.max(1,N(rot.medianDays)||30),released30=total*Math.min(1,30/turnDays),released90=total*Math.min(3,90/turnDays),annualGrossRotation=total*(365/turnDays),usableComp=(comp?.rows||[]).filter(x=>x.comparable?.n>0).length;return{rows,total,var95,stressLoss,unsold,eventRows,rotation:{turnDays,released30,released90,annualGrossRotation,turns:365/turnDays},usableComp}}
function ensureCss(){if(document.querySelector('style[data-risk438]'))return;const s=document.createElement('style');s.dataset.risk438='1';s.textContent=`#ticketIntelView .risk438{margin:0 0 12px;border:1px solid #5b4247;border-radius:13px;background:#160f13;color:#f0e1e3;overflow:hidden}.risk438-head{display:grid;grid-template-columns:1.3fr repeat(5,1fr);gap:8px;padding:11px 12px}.risk438 span{display:block;font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#a9878d}.risk438 b{display:block;margin-top:3px;font-size:13px}.risk438 small{display:block;margin-top:2px;color:#a68f94;font-size:9px}.risk438-list{border-top:1px solid #402b30}.risk438-row{display:grid;grid-template-columns:1.35fr .8fr .8fr .8fr .8fr;gap:8px;padding:9px 12px;border-top:1px solid #352329}.risk438-bad{color:#ff9ba7}.risk438-good{color:#8bd8ad}@media(max-width:900px){.risk438-head,.risk438-row{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function panel(m){const host=document.querySelector('#ticketIntelView .td331');if(!host)return;let box=host.querySelector('[data-risk438]');if(!box){box=document.createElement('section');box.dataset.risk438='1';box.className='risk438';const c=host.querySelector('[data-comp437]');c?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.querySelector('.td331-hero')?.insertAdjacentElement('afterend',box)}const top=m.eventRows.slice(0,6);box.innerHTML=`<div class="risk438-head"><div><span>PORTFOLIO STRESS · OS438</span><b>Downside + cash rotation</b><small>Heuristický stress test; VaR není účetní ani statistická garance.</small></div><div><span>VAR 95 PROXY</span><b class="risk438-bad">${fmt(m.var95)}</b></div><div><span>UNSOLD EXPOSURE</span><b>${fmt(m.unsold)}</b></div><div><span>EMERGENCY P/L</span><b class="${m.stressLoss<0?'risk438-bad':'risk438-good'}">${fmt(m.stressLoss)}</b></div><div><span>ROTACE 30D</span><b>${fmt(m.rotation.released30)}</b></div><div><span>ROČNÍ OBRAT KAP.</span><b>${fmt(m.rotation.annualGrossRotation)}</b><small>${m.rotation.turns.toFixed(1)}× / rok</small></div></div><div class="risk438-list">${top.map(x=>`<div class="risk438-row"><div><span>EVENT</span><b>${x.name}</b><small>${pct(x.share)} kapitálu</small></div><div><span>KAPITÁL</span><b>${fmt(x.capital)}</b></div><div><span>VAR</span><b class="risk438-bad">${fmt(x.var95)}</b></div><div><span>UNSOLD</span><b>${fmt(x.unsold)}</b></div><div><span>EMERGENCY</span><b class="${x.stressLoss<0?'risk438-bad':'risk438-good'}">${fmt(x.stressLoss)}</b></div></div>`).join('')}</div>`}
function refresh(){ensureCss();const m=build();if(!m)return;window.__KAMIL_TICKET_RISK438__={version:VERSION,healthy:true,...m,at:Date.now()};document.documentElement.dataset.ticketRisk438='1';panel(m);window.dispatchEvent(new CustomEvent('kamil:ticket-risk438-updated',{detail:{var95:m.var95}}))}
function schedule(ms=650){clearTimeout(timer);timer=setTimeout(refresh,ms)}
export function installTicketRisk438(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-predict433-updated','kamil:ticket-commander435-updated','kamil:ticket-comparable437-updated'])window.addEventListener(ev,()=>schedule());schedule(4800);setInterval(()=>schedule(0),30000)}
