import {cloudClient,session} from './cloud.js';

const VERSION=442,N=v=>Number(v||0),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));let bound=false,timer=0,busy=false;
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
const fmt=v=>Number.isFinite(Number(v))?Number(v).toFixed(3):'—';
async function ctx(){const c=await cloudClient(),s=await session();if(!c||!s)throw new Error('Cloud session chybí.');return{c,s}}
function point(r){const p=clamp(N(r.sell_probability_72h),0,1),created=Date.parse(r.created_at||''),resolved=Date.parse(r.resolved_at||''),sold=String(r.outcome_status||'').toUpperCase()!=='UNSOLD_EXPIRED',y=Number.isFinite(created)&&Number.isFinite(resolved)&&sold&&(resolved-created<=72*36e5)?1:0;return{p,y,brier:(p-y)**2,created}}
function summarize(rows){const pts=rows.map(point).sort((a,b)=>b.created-a.created),n=pts.length,avgP=mean(pts.map(x=>x.p))??0,actual=mean(pts.map(x=>x.y))??0,brier=mean(pts.map(x=>x.brier)),enough=n>=8;let probabilityScale=1;if(enough&&avgP>.05)probabilityScale=clamp(actual/avgP,.85,1.15);const oc=window.__KAMIL_TICKET_OUTCOME441__?.calibration,pricingBias=enough?clamp(N(oc?.pricingBias)||1,.97,1.03):1;let drift=false,driftReason='';let recentBrier=null,priorBrier=null,recentGap=null;if(n>=16){const recent=pts.slice(0,8),prior=pts.slice(8),rp=mean(recent.map(x=>x.p))??0,ry=mean(recent.map(x=>x.y))??0;recentBrier=mean(recent.map(x=>x.brier));priorBrier=mean(prior.map(x=>x.brier));recentGap=Math.abs(rp-ry);if(Number.isFinite(recentBrier)&&Number.isFinite(priorBrier)&&recentBrier>priorBrier+.12){drift=true;driftReason=`Recent Brier ${recentBrier.toFixed(3)} je o více než 0.12 horší než starší vzorek.`}else if(recentGap>.22){drift=true;driftReason=`Recent calibration gap ${(recentGap*100).toFixed(0)} p.b. překročil bezpečný limit.`}}const mode=!enough?'shadow':drift?'drift-stop':'active';if(mode!=='active'){probabilityScale=1}const evScale=mode==='active'?clamp(.65+.35*probabilityScale,.94,1.06):1;return{mode,n,avgP,actual,brier,probabilityScale,pricingBias:mode==='active'?pricingBias:1,evScale,drift,driftReason,recentBrier,priorBrier,recentGap}}
function ensureCss(){if(document.querySelector('style[data-cf442]'))return;const s=document.createElement('style');s.dataset.cf442='1';s.textContent=`#ticketIntelView .cf442{margin:8px 0 0;border:1px solid #294457;border-radius:10px;background:#0a1923;color:#dbe9f3;padding:9px 11px}.cf442-grid{display:grid;grid-template-columns:1.4fr repeat(5,1fr);gap:8px}.cf442 span{display:block;font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#7796ad}.cf442 b{display:block;margin-top:3px;font-size:11px}.cf442 small{display:block;margin-top:2px;color:#748a9b;font-size:8.5px}.cf442-good{color:#8bd8ad}.cf442-warn{color:#efc17c}.cf442-stop{color:#ff9aa5}@media(max-width:850px){.cf442-grid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function paint(m){ensureCss();const host=document.querySelector('#ticketIntelView .hub421-body')||document.querySelector('#ticketIntelView .td331');if(!host)return;let box=document.querySelector('#ticketIntelView [data-feedback442]');if(!box){box=document.createElement('section');box.dataset.feedback442='1';box.className='cf442';const outcome=document.querySelector('#ticketIntelView [data-outcome441]');outcome?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.appendChild(box)}const label=m.mode==='active'?'AKTIVNÍ':m.mode==='drift-stop'?'DRIFT STOP':'SHADOW MODE',cls=m.mode==='active'?'cf442-good':m.mode==='drift-stop'?'cf442-stop':'cf442-warn',note=m.mode==='shadow'?`0 zásahů do modelu. Aktivace až od 8 uzavřených snapshotů.`:m.mode==='drift-stop'?`Korekce automaticky vypnuta: ${m.driftReason}`:`Korekce je konzervativně omezená: probability 0.85–1.15×, EV 0.94–1.06×.`;box.innerHTML=`<div class="cf442-grid"><div><span>CALIBRATION FEEDBACK · OS442</span><b class="${cls}">${label}</b><small>${note}</small></div><div><span>RESOLVED</span><b>${m.n}</b></div><div><span>P72 SCALE</span><b>${m.probabilityScale.toFixed(3)}×</b></div><div><span>EV SCALE</span><b>${m.evScale.toFixed(3)}×</b></div><div><span>BRIER</span><b>${fmt(m.brier)}</b></div><div><span>DRIFT</span><b class="${m.drift?'cf442-stop':'cf442-good'}">${m.drift?'STOP':'OK / NEDOSTATEK DAT'}</b><small>${m.n>=16?`recent ${fmt(m.recentBrier)} · prior ${fmt(m.priorBrier)}`:'vyhodnocuji až od n=16'}</small></div></div>`}
async function refresh(){if(busy)return;busy=true;try{const {c,s}=await ctx();const {data,error}=await c.from('ticket_decision_snapshots').select('created_at,resolved_at,outcome_status,sell_probability_72h').eq('user_id',s.user.id).not('resolved_at','is',null).order('created_at',{ascending:false}).limit(1000);if(error)throw error;const m=summarize(data||[]);window.__KAMIL_TICKET_CAL_FEEDBACK442__={version:VERSION,healthy:true,...m,at:Date.now()};document.documentElement.dataset.ticketCalibration442=m.mode;paint(m);window.dispatchEvent(new CustomEvent('kamil:ticket-calibration442-updated',{detail:{mode:m.mode,n:m.n,probabilityScale:m.probabilityScale,evScale:m.evScale}}))}catch(e){window.__KAMIL_TICKET_CAL_FEEDBACK442__={version:VERSION,healthy:false,mode:'shadow',probabilityScale:1,evScale:1,error:String(e?.message||e),at:Date.now()}}finally{busy=false}}
function schedule(ms=1200){clearTimeout(timer);timer=setTimeout(refresh,ms)}
export function installTicketCalibrationFeedback442(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-outcome441-updated','kamil:ticket-journal440-updated'])window.addEventListener(ev,()=>schedule());schedule(7600);setInterval(()=>schedule(0),30*60*1000)}
