import {modal,h,toast,formModal} from './utils.js';
import {loadTicketCloud660,replaceTicketInventory660} from './ticketCloud660.js';
import {ticketImportPreview183,ticketImportResult183} from './ticketImportReport183.js';
import {saveTicketImportBackup184,loadTicketImportBackup184,clearTicketImportBackup184,ticketImportBackupSummary184} from './ticketImportRollback184.js';
import {saveTicketRecoverySnapshot185,loadTicketRecoveryHistory185,getTicketRecoverySnapshot185,ticketRecoverySummary185} from './ticketRecovery185.js';

const XLSX_URL='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/+esm';
const STATUS_LABEL={LISTED:'Nabízíš',NOT_LISTED:'Nenabízíš',SOLD_UNDELIVERED:'Prodáno / nedoručeno',SOLD_WAITING_PAYMENT:'Čekáš na peníze',PAYOUT_RECEIVED:'Peníze přijaty',PAID:'Peníze přijaty'};
const STATUS_FILL={LISTED:'FFFF00',NOT_LISTED:'FF0000',SOLD_UNDELIVERED:'00B0F0',SOLD_WAITING_PAYMENT:'FFFFFF',PAYOUT_RECEIVED:'92D050',PAID:'92D050'};
let xlsxPromise=null;
const loadXlsx=()=>xlsxPromise||(xlsxPromise=import(XLSX_URL));
const rgb=x=>String(x||'').replace(/^FF/i,'').toUpperCase();

export function statusFromFill660(fill){
 if(!fill||String(fill.patternType||'').toLowerCase()!=='solid')return null;
 const fg=fill.fgColor||{},c=rgb(fg.rgb);
 if(c==='FFFF00')return'LISTED';if(c==='FF0000')return'NOT_LISTED';if(c==='00B0F0')return'SOLD_UNDELIVERED';if(c==='92D050')return'PAYOUT_RECEIVED';
 if(c==='FFFFFF'||Number(fg.theme)===0)return'SOLD_WAITING_PAYMENT';return null;
}
const excelDate=v=>{if(v instanceof Date)return v.toISOString().slice(0,10);if(typeof v==='string'){const t=Date.parse(v);return Number.isFinite(t)?new Date(t).toISOString().slice(0,10):null}const n=Number(v);if(!Number.isFinite(n)||n<20000)return null;return new Date(Math.round((n-25569)*86400*1000)).toISOString().slice(0,10)};
const number=v=>Number.isFinite(Number(v))?Number(v):0;
function sectionOf(name){const s=String(name||'').trim();const clash=s.match(/\b(A\d+)\b/i);if(clash)return clash[1].toUpperCase();const parts=s.split(/\s+-\s+/).map(x=>x.trim()).filter(Boolean),last=parts.at(-1)||'';const m=last.match(/^(?:sector\s*)?([A-Z]?\d[\w-]*|Standing)$/i);return m?m[1]:last.length<=18?last:''}
export function parseWorkbook660(workbook,{sheetName='Flipování 2026',sourceName='Excel import'}={}){
 const ws=workbook?.Sheets?.[sheetName];if(!ws)throw new Error(`Chybí list „${sheetName}“`);const ref=ws['!ref'];if(!ref)return[];const range=(globalThis.XLSX?.utils||workbook.__xlsxUtils)?.decode_range?.(ref);if(!range)throw new Error('List nemá čitelný rozsah.');const rows=[];
 for(let r=range.s.r;r<=range.e.r;r++){const row=r+1,a=ws[`A${row}`],status=statusFromFill660(a?.s?.fill);if(!status)continue;const eventName=String(a?.v||'').trim(),qty=number(ws[`B${row}`]?.v);if(!eventName||qty<=0)continue;const eventDate=excelDate(ws[`C${row}`]?.v),buyEach=number(ws[`D${row}`]?.v),buyTotal=number(ws[`E${row}`]?.v)||buyEach*qty,sellEach=number(ws[`F${row}`]?.v),sellTotal=number(ws[`G${row}`]?.v)||sellEach*qty;rows.push({id:`xlsx-2026-${row}`,sourceRow:row,eventName,qty,eventDate,section:sectionOf(eventName),buyEachCzk:buyEach,buyTotalCzk:buyTotal,sellEachCzk:sellEach,sellTotalCzk:sellTotal,marketStatus:status,sourceName,sourceSheet:sheetName})}
 return rows;
}
const comparable=x=>JSON.stringify([x.eventName||x.event_name,x.qty,x.eventDate||x.event_date,x.section,Number(x.buyTotalCzk??x.buy_total_czk??0),Number(x.sellTotalCzk??x.sell_total_czk??0),x.marketStatus||x.market_status]);
export function diffInventory660(next,current=[]){const old=new Map(current.map(x=>[x.id,x])),neu=new Map(next.map(x=>[x.id,x])),added=[],changed=[],removed=[];for(const x of next){const p=old.get(x.id);if(!p)added.push(x);else if(comparable(x)!==comparable(p))changed.push({before:p,after:x,statusChanged:(p.market_status||p.marketStatus)!==(x.marketStatus||x.market_status)})}for(const x of current)if(!neu.has(x.id))removed.push(x);return{added,changed,removed}}
const qtyByStatus=rows=>rows.reduce((a,x)=>{const k=x.marketStatus||x.market_status;a[k]=(a[k]||0)+Number(x.qty||0);return a},{});
const chooseFile=()=>new Promise(resolve=>{const i=document.createElement('input');i.type='file';i.accept='.xlsx,.xls';i.hidden=true;i.onchange=()=>{const f=i.files?.[0]||null;i.remove();resolve(f)};document.body.appendChild(i);i.click()});
const fmtDate=x=>{try{return new Date(x).toLocaleString('cs-CZ',{dateStyle:'short',timeStyle:'short'})}catch{return x||'—'}};
function diffHtml(rows,diff){const q=qtyByStatus(rows),changes=diff.changed.filter(x=>x.statusChanged).slice(0,12),p=ticketImportPreview183(diff);return `<div class="card"><div class="eyebrow">NÁHLED IMPORTU</div><h2>${rows.length} řádků z Excelu</h2>${Object.entries(STATUS_LABEL).filter(([k])=>k!=='PAID').map(([k,v])=>`<div class="row"><span>${h(v)}</span><b>${q[k]||0} ks</b></div>`).join('')}<hr><div class="row"><span>Nové pozice</span><b>${p.added}</b></div><div class="row"><span>Změněné pozice</span><b>${p.changed}</b></div><div class="row"><span>Aktivní pozice budou odstraněny</span><b>${p.removedActive}</b></div><div class="row"><span>Prodané záznamy zůstanou zachované</span><b>${p.preservedClosed}</b></div></div>${changes.length?`<div class="card"><div class="eyebrow">ZMĚNY STAVU</div>${changes.map(x=>`<div class="row"><div><b>${h(x.after.eventName||x.after.event_name)}</b><div class="muted">${h(STATUS_LABEL[x.before.market_status||x.before.marketStatus]||'—')} → ${h(STATUS_LABEL[x.after.marketStatus||x.after.market_status]||'—')}</div></div></div>`).join('')}</div>`:''}<p class="muted">OS 182/183 chrání uzavřený prodejní workflow, skutečný payout, fee a datum payoutu. OS 185 navíc uchovává historii bodů obnovy.</p>`}
function resultHtml(r,backup,recovery){const b=backup?.ok?ticketImportBackupSummary184(backup.backup):null,historyCount=recovery?.ok?recovery.snapshots.length:0;return `<div class="card"><div class="eyebrow">IMPORT HOTOVÝ</div><h2>Synchronizace proběhla bezpečně</h2><div class="row"><span>Řádků synchronizováno</span><b>${r.imported}</b></div><div class="row"><span>Nové pozice</span><b>${r.added}</b></div><div class="row"><span>Změněné pozice</span><b>${r.changed}</b></div><div class="row"><span>Aktivní pozice odstraněny</span><b>${r.removedActive}</b></div><div class="row"><span>Prodané záznamy zachovány</span><b>${r.preservedClosed}</b></div></div><div class="card"><div class="eyebrow">DATA INTEGRITY</div><div class="row"><span>Účetní data payout/fee</span><b>CHRÁNĚNA</b></div><div class="row"><span>Uzavřený workflow</span><b>CHRÁNĚN</b></div>${r.protectedSettlement?`<div class="row"><span>Vyplacené záznamy mimo Excel</span><b>${r.protectedSettlement}</b></div>`:''}</div>${b?`<div class="card"><div class="eyebrow">OS 185 · RECOVERY CENTER</div><div class="row"><span>Stav před importem</span><b>${b.rows} řádků / ${b.qty} ks</b></div><div class="row"><span>Uložených bodů obnovy</span><b>${historyCount||1} / 10</b></div><div class="row"><span>Okamžité vrácení</span><b>PŘIPRAVENO</b></div><p class="muted">Starší body zůstávají v Recovery Center i po dalším importu.</p></div>`:''}`}
function recoveryPreviewHtml(summary,diff){const p=ticketImportPreview183(diff);return `<div class="card"><div class="eyebrow">OS 185 · OBNOVA</div><h2>${h(summary.fileName||'Bod obnovy')}</h2><div class="row"><span>Uloženo</span><b>${h(fmtDate(summary.createdAt))}</b></div><div class="row"><span>Stav bodu</span><b>${summary.rows} řádků / ${summary.qty} ks</b></div><hr><div class="row"><span>Pozice, které se vrátí</span><b>${p.added}</b></div><div class="row"><span>Pozice, které se změní</span><b>${p.changed}</b></div><div class="row"><span>Současné aktivní pozice mimo bod</span><b>${p.removedActive}</b></div><p class="muted">Před obnovou OS automaticky uloží i současný stav, takže lze obnovu zase vrátit.</p></div>`}
async function guardCurrentState185(cloud,label,note=''){const history=saveTicketRecoverySnapshot185(cloud.inventory,{fileName:label,kind:'pre-restore',note});const backup=saveTicketImportBackup184(cloud.inventory,{fileName:label});return{history,backup,ok:history.ok||backup.ok}}
async function restoreSnapshot185(snapshot,summary){const cloud=await loadTicketCloud660();if(!cloud.ok)throw cloud.error||new Error('Cloud není připojený');const diff=diffInventory660(snapshot.rows,cloud.inventory),choice=await modal('Recovery Center',recoveryPreviewHtml(summary,diff),[{label:'Obnovit tento stav',value:'yes',primary:true},{label:'Zrušit',value:null}]);if(choice!=='yes')return false;const guard=await guardCurrentState185(cloud,`Před obnovou · ${summary.fileName||fmtDate(summary.createdAt)}`,`Automatický bod před obnovou ${summary.id}`);if(!guard.ok){const unsafe=await modal('Recovery Center','<div class="card"><h2>Nepodařilo se uložit současný stav.</h2><p class="muted">Bez vratného bodu obnovu nedoporučuji.</p></div>',[{label:'Přesto obnovit',value:'yes'},{label:'Zrušit',value:null,primary:true}]);if(unsafe!=='yes')return false}const out=await replaceTicketInventory660(snapshot.rows);if(!out.ok)throw out.error||new Error('Obnova selhala');toast(`Recovery Center · obnoveno ${out.count} řádků`);await modal('Recovery Center','<div class="card"><div class="eyebrow">OBNOVENO</div><h2>Vybraný stav je zpět.</h2><p class="muted">Stav před obnovou byl uložen jako nový bod, takže tento krok můžeš znovu vrátit.</p></div>',[{label:'Hotovo',value:null,primary:true}]);return true}
export async function openTicketRecoveryCenter185(){try{const history=loadTicketRecoveryHistory185();if(!history.ok||!history.snapshots.length){await modal('Recovery Center','<div class="card"><div class="eyebrow">OS 185</div><h2>Zatím není co obnovovat.</h2><p class="muted">První bod se vytvoří automaticky před příštím importem nebo obnovou.</p></div>',[{label:'OK',value:null,primary:true}]);return false}const options=history.summaries.map((s,i)=>`<option value="${h(s.id)}">${i+1}. ${h(fmtDate(s.createdAt))} · ${h(s.fileName||s.kind)} · ${s.rows} ř. / ${s.qty} ks</option>`).join(''),cards=history.summaries.slice(0,5).map((s,i)=>`<div class="row"><div><b>${i+1}. ${h(s.fileName||s.kind)}</b><div class="muted">${h(fmtDate(s.createdAt))} · ${s.rows} ř. · ${s.qty} ks${s.delta.changed||s.delta.added||s.delta.removed?` · Δ +${s.delta.added} / ~${s.delta.changed} / −${s.delta.removed}`:''}</div></div></div>`).join('');const data=await formModal('Recovery Center',`<div class="card"><div class="eyebrow">OS 185 · HISTORIE IMPORTŮ</div><h2>${history.snapshots.length} bodů obnovy</h2>${cards}${history.snapshots.length>5?`<p class="muted">+ ${history.snapshots.length-5} starších bodů</p>`:''}</div><label class="field"><span>Vyber stav k obnovení</span><select name="recoveryId">${options}</select></label><p class="muted">Uchovává se maximálně 10 posledních stavů.</p>`,{submitLabel:'Zkontrolovat obnovu'});if(!data?.recoveryId)return false;const selected=getTicketRecoverySnapshot185(String(data.recoveryId));if(!selected.ok)throw new Error('Vybraný bod obnovy už není dostupný');return await restoreSnapshot185(selected.snapshot,selected.summary)}catch(e){await modal('Recovery Center',`<p>${h(e?.message||e)}</p>`,[{label:'Zavřít',value:null,primary:true}]);return false}}
async function restoreLastImport184(){const saved=loadTicketImportBackup184();if(!saved.ok){await modal('Vrátit import','<p>Bod obnovy už není k dispozici.</p>',[{label:'OK',value:null,primary:true}]);return false}const s=saved.summary,choice=await modal('Vrátit poslední import',`<div class="card"><div class="eyebrow">OS 185 · RYCHLÁ OBNOVA</div><h2>Obnovit stav před posledním importem?</h2><div class="row"><span>Řádků</span><b>${s.rows}</b></div><div class="row"><span>Vstupenek</span><b>${s.qty} ks</b></div><div class="row"><span>Zdroj importu</span><b>${h(s.fileName||'—')}</b></div><p class="muted">Současný stav se před vrácením automaticky uloží do Recovery Center.</p></div>`,[{label:'Obnovit',value:'yes',primary:true},{label:'Nechat současný stav',value:null}]);if(choice!=='yes')return false;const cloud=await loadTicketCloud660();if(cloud.ok)await guardCurrentState185(cloud,`Před rychlou obnovou · ${s.fileName||'import'}`,'Automatický bod před OS 184 rollbackem');const out=await replaceTicketInventory660(saved.backup.rows);if(!out.ok)throw out.error||new Error('Obnova selhala');clearTicketImportBackup184();toast(`Import vrácen · obnoveno ${out.count} řádků`);await modal('Vrátit import','<div class="card"><div class="eyebrow">OBNOVENO</div><h2>Stav před importem je zpět.</h2><p class="muted">Původní současný stav najdeš v Recovery Center.</p></div>',[{label:'Hotovo',value:null,primary:true}]);return true}
export async function openTicketExcelImport660(){try{const file=await chooseFile();if(!file)return false;const XLSX=await loadXlsx(),ab=await file.arrayBuffer(),wb=XLSX.read(ab,{type:'array',cellStyles:true,cellDates:false});wb.__xlsxUtils=XLSX.utils;const rows=parseWorkbook660(wb,{sourceName:file.name}),cloud=await loadTicketCloud660();if(!cloud.ok){await modal('Import vstupenek','<p>Pro bezpečný serverový import musí být připojený cloud.</p>',[{label:'OK',value:null,primary:true}]);return false}const diff=diffInventory660(rows,cloud.inventory),choice=await modal('Import vstupenek',diffHtml(rows,diff),[{label:'Synchronizovat',value:'yes',primary:true},{label:'Zrušit',value:null}]);if(choice!=='yes')return false;const backup=saveTicketImportBackup184(cloud.inventory,{fileName:file.name}),recovery=saveTicketRecoverySnapshot185(cloud.inventory,{fileName:file.name,kind:'import',diff,note:'Stav před Excel importem'});if(!backup.ok&&!recovery.ok){const unsafe=await modal('Import vstupenek','<div class="card"><div class="eyebrow">OS 185 · RECOVERY CENTER</div><h2>Nepodařilo se uložit žádný bod obnovy.</h2><p class="muted">Import může pokračovat, ale nepůjde bezpečně vrátit.</p></div>',[{label:'Pokračovat bez obnovy',value:'yes'},{label:'Zrušit',value:null,primary:true}]);if(unsafe!=='yes')return false}const out=await replaceTicketInventory660(rows);if(!out.ok)throw out.error||new Error('Import selhal');const report=ticketImportResult183(out,diff);toast(`Vstupenky synchronizovány · ${out.count} řádků`);const actions=[{label:'Hotovo',value:null,primary:true}];if(backup.ok)actions.push({label:'Vrátit import',value:'undo'});if(recovery.ok)actions.push({label:'Recovery Center',value:'recovery'});const done=await modal('Import vstupenek',resultHtml(report,backup,recovery),actions);if(done==='undo')await restoreLastImport184();if(done==='recovery')await openTicketRecoveryCenter185();return{ok:true,rows,diff,out,report,backup:backup.ok?backup.backup:null,recovery:recovery.ok?recovery.snapshot:null}}catch(e){await modal('Import vstupenek',`<p>${h(e?.message||e)}</p>`,[{label:'Zavřít',value:null,primary:true}]);return false}}
export async function exportTicketInventory660(){try{const cloud=await loadTicketCloud660();if(!cloud.ok)throw cloud.error||new Error('Cloud není připojený');const XLSX=await loadXlsx(),data=[['Událost','Ks','Datum','Sekce','Nákup / ks','Nákup celkem','Prodej / ks','Prodej celkem','Stav','Moje cena','Viagogo URL'],...cloud.inventory.map(x=>[x.event_name,x.qty,x.event_date,x.section,Number(x.buy_each_czk||0),Number(x.buy_total_czk||0),Number(x.sell_each_czk||0),Number(x.sell_total_czk||0),STATUS_LABEL[x.market_status]||x.market_status,Number(x.ask_each_czk||0)||'',x.viagogo_url||''])],ws=XLSX.utils.aoa_to_sheet(data);for(let r=1;r<=cloud.inventory.length;r++){const cell=ws[`I${r+2}`],status=cloud.inventory[r-1]?.market_status;if(cell&&STATUS_FILL[status])cell.s={fill:{patternType:'solid',fgColor:{rgb:`FF${STATUS_FILL[status]}`}}}}const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Vstupenky');XLSX.writeFile(wb,`Kamil_OS_vstupenky_${new Date().toISOString().slice(0,10)}.xlsx`);return true}catch(e){await modal('Export vstupenek',`<p>${h(e?.message||e)}</p>`,[{label:'Zavřít',value:null,primary:true}]);return false}}
