import {loadTicketCloud660} from './ticketCloud660.js';
import {modal,h} from './utils.js';

const VERSION=410,N=v=>Number(v||0);let bound=false,timer=0,busy=false,cache=null;
const fmt=v=>N(v)?`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`:'—';
const pct=v=>Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(1)} %`:'—';
const esc=s=>h(String(s??''));
function rowsFor(cloud,id){return [...(cloud.history?.get(id)||[])].filter(x=>N(x.market_price_czk)>0&&Number.isFinite(Date.parse(x.checked_at||''))).sort((a,b)=>Date.parse(a.checked_at)-Date.parse(b.checked_at))}
function change(rows,ms){if(rows.length<2)return null;const last=rows.at(-1),cut=Date.parse(last.checked_at)-ms,base=rows.find(x=>Date.parse(x.checked_at)>=cut)||rows[0],a=N(base.market_price_czk),b=N(last.market_price_czk);return a?((b/a)-1)*100:null}
function stats(rows){if(!rows.length)return{last:0,min:0,max:0,median:0,c24:null,c7:null,c30:null};const vals=rows.map(x=>N(x.market_price_czk)).sort((a,b)=>a-b);return{last:N(rows.at(-1).market_price_czk),min:vals[0],max:vals.at(-1),median:vals[Math.floor(vals.length/2)],c24:change(rows,864e5),c7:change(rows,7*864e5),c30:change(rows,30*864e5)}}
function tone(v){return !Number.isFinite(v)?'flat':v>3?'up':v<-3?'down':'flat'}
function chart(rows){if(rows.length<2)return'<div class="ph409-empty">Na graf jsou potřeba alespoň dva cenové snapshoty.</div>';const w=520,hh=150,pad=12,vals=rows.map(x=>N(x.market_price_czk)),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1,t0=Date.parse(rows[0].checked_at),t1=Date.parse(rows.at(-1).checked_at),ts=t1-t0||1,pts=rows.map(x=>`${pad+((Date.parse(x.checked_at)-t0)/ts)*(w-pad*2)},${hh-pad-((N(x.market_price_czk)-min)/span)*(hh-pad*2)}`).join(' ');return`<svg class="ph409-chart" viewBox="0 0 ${w} ${hh}" role="img" aria-label="Historie tržní ceny"><line x1="${pad}" y1="${pad}" x2="${pad}" y2="${hh-pad}"/><line x1="${pad}" y1="${hh-pad}" x2="${w-pad}" y2="${hh-pad}"/><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="3" vector-effect="non-scaling-stroke"/><text x="${pad+4}" y="${pad+10}">${Math.round(max).toLocaleString('cs-CZ')}</text><text x="${pad+4}" y="${hh-pad-5}">${Math.round(min).toLocaleString('cs-CZ')}</text></svg>`}
function source(s){const c=String(s?.confidence||'').toLowerCase();if(c.includes('row-listing')||c.includes('section-listing'))return'LIVE';if(c.includes('search-index'))return'INDEX';if(c.includes('reader'))return'READER';if(c.includes('manual')||c.includes('clipboard'))return'RUČNÍ';if(c.includes('official'))return'API';return'TRH'}
async function open(id){const cloud=cache||await loadTicketCloud660();if(!cloud?.ok)return;const r=(cloud.inventory||[]).find(x=>String(x.id)===String(id)),rows=rowsFor(cloud,id),s=stats(rows),recent=[...rows].reverse().slice(0,12);await modal(`Historie ceny · ${esc(r?.event_name||'Vstupenka')}`,`<div class="ph409-modal"><div class="ph409-modalstats"><div><span>Aktuální</span><b>${fmt(s.last)}</b></div><div><span>24 h</span><b class="${tone(s.c24)}">${pct(s.c24)}</b></div><div><span>7 dní</span><b class="${tone(s.c7)}">${pct(s.c7)}</b></div><div><span>30 dní</span><b class="${tone(s.c30)}">${pct(s.c30)}</b></div><div><span>Rozpětí</span><b>${fmt(s.min)} – ${fmt(s.max)}</b></div><div><span>Medián</span><b>${fmt(s.median)}</b></div></div>${chart(rows)}<div class="ph409-table">${recent.map(x=>`<div><span>${new Intl.DateTimeFormat('cs-CZ',{day:'numeric',month:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(x.checked_at))}</span><b>${fmt(x.market_price_czk)}</b><small>${source(x)} · ${esc(x.confidence||'bez confidence')}</small></div>`).join('')||'<em>Zatím bez historie.</em>'}</div></div>`,[{label:'Zavřít',value:null,primary:true}])}
function ensureCss(){if(document.querySelector('style[data-ph409]'))return;const s=document.createElement('style');s.dataset.ph409='1';s.textContent=`#ticketIntelView .ph409-strip{display:flex;gap:7px;align-items:center;padding:7px 9px;margin:0 10px 9px;border:1px solid #203747;border-radius:9px;background:#0c1821}.ph409-strip span{font-size:8px;color:#7898b0;text-transform:uppercase;font-weight:800}.ph409-chip{font-size:9px;font-weight:800}.ph409-chip.up,.ph409-modal .up{color:#8bd6ae}.ph409-chip.down,.ph409-modal .down{color:#f2a2a2}.ph409-chip.flat,.ph409-modal .flat{color:#9badba}.ph409-btn{margin-left:auto;border:1px solid #34546a;background:#122331;color:#b9d7ea;border-radius:999px;padding:4px 8px;font-size:9px;font-weight:800;cursor:pointer}.ph409-modalstats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:10px}.ph409-modalstats>div{padding:8px;border:1px solid #d7e0e7;border-radius:8px}.ph409-modalstats span{display:block;font-size:10px;opacity:.68}.ph409-modalstats b{display:block;margin-top:3px}.ph409-chart{width:100%;height:auto;min-height:130px;color:#4d7895}.ph409-chart line{stroke:#b8c7d2;stroke-width:1}.ph409-chart text{font-size:9px;fill:#657682}.ph409-table{max-height:220px;overflow:auto;border-top:1px solid #dfe6eb;margin-top:8px}.ph409-table>div{display:grid;grid-template-columns:1fr .7fr 1.3fr;gap:8px;padding:6px 2px;border-bottom:1px solid #edf1f4;font-size:10px}.ph409-table small{opacity:.7}@media(max-width:700px){.ph409-modalstats{grid-template-columns:1fr 1fr}.ph409-strip{flex-wrap:wrap}.ph409-btn{margin-left:0}}`;document.head.appendChild(s)}
async function render(){if(busy)return;const host=document.querySelector('#ticketIntelView');if(!host)return;busy=true;try{ensureCss();const cloud=await loadTicketCloud660();if(!cloud?.ok)return;cache=cloud;for(const card of host.querySelectorAll('[data-ta407]')){const id=card.dataset.ta407;if(!id)continue;const rows=rowsFor(cloud,id),s=stats(rows);let strip=card.querySelector('[data-price-history409]');if(!strip){strip=document.createElement('div');strip.dataset.priceHistory409='1';strip.className='ph409-strip';card.querySelector('.ta407-market')?.insertAdjacentElement('afterend',strip)}if(!strip?.isConnected)continue;const sig=[rows.length,s.last,s.c24,s.c7,s.c30,rows.at(-1)?.checked_at].join('|');if(strip.dataset.sig!==sig){strip.dataset.sig=sig;strip.innerHTML=`<span>Momentum</span><b class="ph409-chip ${tone(s.c24)}">24h ${pct(s.c24)}</b><b class="ph409-chip ${tone(s.c7)}">7d ${pct(s.c7)}</b><b class="ph409-chip ${tone(s.c30)}">30d ${pct(s.c30)}</b><small>${rows.length} snapshotů</small><button class="ph409-btn" data-history409="${esc(id)}">Historie ↗</button>`;strip.querySelector('[data-history409]')?.addEventListener('click',()=>open(id))}}window.__KAMIL_TICKET_PRICE_HISTORY409__={version:VERSION,healthy:true,count:[...host.querySelectorAll('[data-ta407]')].length,at:Date.now()};document.documentElement.dataset.ticketPriceHistory409='1'}finally{busy=false}}
function schedule(ms=220){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketPriceHistory409(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-refresh397-done','kamil:ticket-manual398-saved','kamil:ticket-clipboard403-saved','kamil:ticket-sale408-saved'])window.addEventListener(ev,()=>schedule());new MutationObserver(()=>schedule(300)).observe(document.body,{childList:true,subtree:true});schedule();setTimeout(()=>schedule(),1300)}
