import {store} from './state.js';
import {ticketEventPortfolio32} from './ticketPortfolio32.js';
import {ownEvent1100} from './runtimeOwnership1100.js';
import {session} from './cloud.js';
import {loadProductAdvancedStyles} from './productAdvancedStyles.js';
import {openPersonalAction641} from './personalActionExecution641.js';
import {modal} from './utils.js';

const OWNER='product.ticketOverview';
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const money=v=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(Number(v||0));
const upper=v=>String(v||'').toUpperCase();

export function ticketData1300(input=null){
 const s=input||store.get(),p=ticketEventPortfolio32(s),items=s.ticketBook?.items||[],master=s.ticketBook?.masterMeta||null;
 const transfer=items.filter(x=>['SOLD_UNDELIVERED','TRANSFER_REQUIRED','SOLD_WAITING_TRANSFER'].includes(upper(x.market_status||x.workflow)));
 const payout=items.filter(x=>['PAYOUT_WAIT','SOLD_WAITING_PAYMENT','WAITING_PAYOUT'].includes(upper(x.market_status||x.workflow)));
 const issues=items.filter(x=>x.issue);
 const ticketTasks=(s.tasks||[]).filter(x=>!['DONE','CLOSED','ARCHIVED','RESOLVED','CANCELLED','CANCELED'].includes(upper(x.status))).filter(x=>upper(x.area)==='TICKETS'||upper(x.category)==='VIAGOGO').sort((a,b)=>Number(b.priority||0)-Number(a.priority||0));
 const attention=[];
 if(issues.length)attention.push({tone:'bad',title:issues.length+' reklamace / sporné prodeje',detail:'V soukromých datech mají příznak reklamace. Zkontroluj je před ostatními listingy.',action:'advanced'});
 if(transfer.length)attention.push({tone:'bad',title:transfer.length+' prodejů čeká na převod',detail:'Prodáno, ale předání kupujícímu ještě není dokončené.',action:'advanced'});
 if(p.missingListed)attention.push({tone:'warn',title:p.missingListed+' listingů nemá cenu',detail:'Bez skutečné list ceny OS neumí hlídat prodej správně.',action:'advanced'});
 if(p.staleMarket)attention.push({tone:'warn',title:p.staleMarket+' eventů má starý market',detail:'Aktualizuj tržní cenu před dalším rozhodnutím.',action:'advanced'});
 if(payout.length)attention.push({tone:'warn',title:payout.length+' prodejů čeká na payout',detail:'Zkontroluj stav platby z marketplace.',action:'advanced'});
 for(const t of ticketTasks.slice(0,4))attention.push({tone:Number(t.priority||0)>=90?'bad':'warn',title:t.title||'Ticket úkol',detail:t.notes||'Otevřený ticketový úkol.',action:'task',taskId:t.id});
 return {s,p,items,master,issues,transfer,payout,ticketTasks,attention:attention.slice(0,6)};
}
const data=()=>ticketData1300();
function attentionHtml(rows){if(!rows.length)return '<div class="pr1300-empty">Žádný transfer, payout ani pricing problém teď nehoří.</div>';return '<div class="pr1300-attention">'+rows.map(x=>'<button type="button" data-ticket-action="'+x.action+'" '+(x.taskId?'data-ticket-task-id="'+esc(x.taskId)+'"':'')+'><i class="pr1300-dot '+x.tone+'"></i><span><b>'+esc(x.title)+'</b><small>'+esc(x.detail)+'</small></span><em>řešit →</em></button>').join('')+'</div>'}
function eventRows(events){if(!events.length)return '<div class="pr1300-empty">Žádné aktivní vstupenky.</div>';return events.map((x,i)=>'<button type="button" class="pr1300-row pr1300-clickrow" data-ticket-event="'+i+'"><div class="pr1300-row-main"><b>'+esc(x.name)+'</b><small>'+x.qty+' ks · kapitál '+money(x.capitalAtRisk)+' · '+esc(x.nextAction||'sledovat')+'</small></div><div class="pr1300-row-side '+(x.priority>=85?'bad':x.priority>=70?'warn':'')+'">'+x.priority+'/100 <span class="os1500-row-arrow">→</span></div></button>').join('')}
function primaryAction(x,topEvent){if(x?.action==='sync')return '<button class="pr1300-btn primary" type="button" data-ticket-sync>Synchronizovat Viagogo →</button>';if(x?.action==='advanced')return '<button class="pr1300-btn primary" type="button" data-ticket-advanced>Otevřít případ →</button>';if(x?.action==='task'&&x.taskId)return '<button class="pr1300-btn primary" type="button" data-ticket-task-id="'+esc(x.taskId)+'">Vyřešit úkol →</button>';if(topEvent)return '<button class="pr1300-btn primary" type="button" data-ticket-event="0">Otevřít event →</button>';return '<button class="pr1300-btn primary" type="button" data-ticket-task>＋ Úkol k ticketům</button>'}

export function renderTicketOverview(){
 const host=document.querySelector('#ticketIntelView');if(!host)return false;if(host.dataset.productAdvanced==='1')return true;const d=data(),top=d.p.top,hasAttention=d.attention.length>0,hasEvents=d.p.events.length>0,blank=!d.items.length&&!d.ticketTasks.length;
 const status=x=>upper(x.market_status||x.marketStatus||x.workflow),sum=(rows,key)=>rows.reduce((a,x)=>a+Number(x?.[key]||0),0),paid=d.items.filter(x=>status(x)==='PAYOUT_RECEIVED'),waiting=d.items.filter(x=>['SOLD_WAITING_PAYMENT','WAITING_PAYOUT','PAYOUT WAIT'].includes(status(x))),listed=d.items.filter(x=>status(x)==='LISTED'),held=d.items.filter(x=>['NOT_LISTED','HOLD'].includes(status(x))),undelivered=d.items.filter(x=>['SOLD_UNDELIVERED','TRANSFER_REQUIRED','SOLD_WAITING_TRANSFER'].includes(status(x))),realized=sum(paid,'sellTotalCzk')-sum(paid,'buyTotalCzk'),waitingProfit=sum(waiting,'sellTotalCzk')-sum(waiting,'buyTotalCzk'),capitalExposure=sum([...listed,...held],'buyTotalCzk');
 const deadlineRisk=undelivered.map(x=>{const raw=x.eventDate||x.date,t=Date.parse(raw||''),days=Number.isFinite(t)?Math.ceil((t-Date.now())/86400000):null;return{x,days}}).sort((a,b)=>(a.days??999)-(b.days??999));
 const attentionBlock=hasAttention?'<section class="pr1300-panel"><div class="pr1300-panel-head"><h2>Teď řešit</h2><button class="pr1300-btn" type="button" data-ticket-advanced>Ticket desk</button></div>'+attentionHtml(d.attention)+'</section>':'';
 const eventsBlock=hasEvents?'<section class="pr1300-panel"><div class="pr1300-panel-head"><h3>Aktivní eventy</h3><span>nejvyšší priorita nahoře</span></div>'+eventRows(d.p.events)+'</section>':'';
 const clearBlock=!hasAttention&&!hasEvents?'<section class="pr1300-panel pr1327-ticket-clear"><div class="pr1300-panel-head"><h2>'+(blank?'Začni soukromým portfoliem':'Portfolio je klidné')+'</h2><button class="pr1300-btn" type="button" data-ticket-advanced>Ticket desk</button></div><div class="pr1300-empty">'+(blank?'OS neobsahuje žádné veřejné ticketové záznamy. Připoj cloud, synchronizaci nebo přidej ticketový úkol; tvoje data zůstanou soukromá.':'Žádný transfer, payout, pricing problém ani aktivní event teď nevyžaduje zásah.')+'</div></section>':'';
 const summaryBlock=blank?'':'<div class="os1500-summary-grid"><div class="os1500-summary"><span>Aktivní eventy</span><b>'+d.p.totalEvents+'</b></div><div class="os1500-summary"><span>Aktivní kusy</span><b>'+d.p.queue.activeQty+'</b></div><div class="os1500-summary"><span>Reklamace</span><b>'+d.issues.length+'</b></div><div class="os1500-summary"><span>Kapitál</span><b>'+money(d.p.totalCapital)+'</b></div></div>';
 const truthBlock=blank?'<section class="pr1300-panel os741-ticket-truth"><div class="pr1300-panel-head"><div><h2>Lifecycle a profit truth</h2><span>aktivuje se po načtení soukromého portfolia</span></div></div><div class="pr1300-empty">Nákup, listing, transfer, payout i skutečný profit se objeví až z tvých privátních dat. OS nic nevymýšlí.</div></section>':'<section class="pr1300-panel os741-ticket-truth"><div class="pr1300-panel-head"><div><h2>Lifecycle a profit truth</h2><span>od nákupu po skutečný payout</span></div></div><div class="os741-lifecycle"><span><small>Nenabízím</small><b>'+held.length+'</b></span><span><small>Nabízím</small><b>'+listed.length+'</b></span><span class="'+(undelivered.length?'bad':'')+'"><small>Prodat / doručit</small><b>'+undelivered.length+'</b></span><span class="'+(waiting.length?'warn':'')+'"><small>Čeká payout</small><b>'+waiting.length+'</b></span><span><small>Zaplaceno</small><b>'+paid.length+'</b></span></div><div class="os1500-summary-grid"><div class="os1500-summary"><span>Realizovaný profit</span><b>'+money(realized)+'</b></div><div class="os1500-summary"><span>Profit čekající na payout</span><b>'+money(waitingProfit)+'</b></div><div class="os1500-summary"><span>Kapitál v otevřených kusech</span><b>'+money(capitalExposure)+'</b></div><div class="os1500-summary '+(deadlineRisk.some(r=>r.days!==null&&r.days<=2)?'bad':'')+'"><span>Transfer deadline risk</span><b>'+deadlineRisk.filter(r=>r.days===null||r.days<=7).length+'</b></div></div>'+(deadlineRisk.length?'<div class="os741-deadline-list">'+deadlineRisk.slice(0,4).map(r=>'<div><b>'+esc(r.x.name||r.x.eventName||'Ticket')+'</b><small>'+(r.days===null?'termín neznámý':r.days<0?Math.abs(r.days)+' d po eventu':r.days===0?'event dnes':'event za '+r.days+' d')+'</small></div>').join('')+'</div>':'')+'</section>';
 const sourceLabel=Array.isArray(d.master?.sourceSheets)?d.master.sourceSheets.join(' · '):d.master?.sourceFile||'soukromý zdroj';
 host.innerHTML='<div class="pr1300-shell" data-ticket-overview>' +
 '<div class="pr1300-head"><div><div class="pr1300-kicker">Vstupenky</div><h1>Vstupenky.</h1><p>'+(d.master?'Zdroj: '+esc(sourceLabel)+' · stav určuje soukromý inventory.':blank?'Soukromé portfolio, transfery a payouty se načtou až z tvého zařízení nebo cloudu.':'Nejdřív transfery, payouty a otevřené případy. Aktivní eventy až potom.')+'</p></div><span class="pr1300-status '+(d.issues.length||d.transfer.length?'bad':hasAttention?'warn':'good')+'">'+(blank?'připraveno':hasAttention?d.attention.length+' k řešení':'klid')+'</span></div>' +
 '<section class="pr1320-now"><div><div class="pr1300-kicker">Teď</div><h2>'+esc(d.attention[0]?.title||top?.name||(blank?'Portfolio čeká na soukromá data':'Nic urgentního'))+'</h2><p>'+esc(d.attention[0]?.detail||top?.nextAction||(blank?'Ve veřejném OS nejsou žádné osobní ticketové záznamy.':'Aktivní portfolio teď nevyžaduje okamžitý zásah.'))+'</p></div><div class="pr1320-now-actions">'+primaryAction(d.attention[0],top)+'</div></section>' +
 attentionBlock + eventsBlock + clearBlock + summaryBlock + truthBlock +
 (d.master&&!blank?'<div class="os1500-section-note">Historie: 2024 '+Number(d.master.years?.[2024]?.qty||0)+' ks · 2025 '+Number(d.master.years?.[2025]?.qty||0)+' ks · 2026 '+Number(d.master.years?.[2026]?.qty||0)+' ks · nákup '+money(d.master.buyTotalCzk)+' · prodej '+money(d.master.sellTotalCzk)+' · rozdíl '+money(d.master.grossMarginCzk)+'</div>':'') +
 '<div class="pr1300-actions"><button class="pr1300-btn" type="button" data-ticket-task>＋ Úkol</button><button class="pr1300-btn" type="button" data-ticket-sync>Synchronizovat</button><button class="pr1300-btn" type="button" data-ticket-advanced>Detail</button></div></div>';
 host.__ticketOverview1500=d;
 if(!host.dataset.ticketOverviewBound){host.dataset.ticketOverviewBound='1';ownEvent1100(OWNER,host,'click',async e=>{if(e.target.closest('[data-ticket-task]')){window.dispatchEvent(new CustomEvent('kamil:capture',{detail:'ticket-task'}));return}const taskBtn=e.target.closest('[data-ticket-task-id]');if(taskBtn){const item=(store.get().tasks||[]).find(x=>String(x.id)===taskBtn.dataset.ticketTaskId);if(item)await openPersonalAction641({id:'task:'+item.id,kind:'task',title:item.title||'Ticket úkol',why:item.notes||'Aktuální ticketová záležitost.',next:'Vyřešit nebo posunout další krok.',route:'tickets'});renderTicketOverview();return}if(e.target.closest('[data-ticket-sync]')||e.target.closest('[data-ticket-action="sync"]')){if(!await session()){window.dispatchEvent(new CustomEvent('kamil:cloud-login'));return}const m=await import('./ticketGmailSync429.js');await m.syncTicketGmail429?.();renderTicketOverview();return}if(e.target.closest('[data-ticket-advanced]')||e.target.closest('[data-ticket-action="advanced"]')){host.dataset.productAdvanced='1';await loadProductAdvancedStyles(['./ticket68.css','./ticketWorkspace210.css','./ticketDesk353.css','./ticketDesk355.css','./ticketDesk356.css']);const m=await import('./ticketAdvanced100.js');await m.renderTicketPage100?.();return}const eventBtn=e.target.closest('[data-ticket-event]');if(eventBtn){const current=host.__ticketOverview1500||data(),x=current.p.events[Number(eventBtn.dataset.ticketEvent)];if(!x)return;const choice=await modal('Aktivní event',`<div class="card"><div class="eyebrow">VSTUPENKY</div><h2>${esc(x.name)}</h2><div class="row"><span>Aktivní kusy</span><b>${Number(x.qty||0)}</b></div><div class="row"><span>Kapitál v riziku</span><b>${money(x.capitalAtRisk)}</b></div><div class="row"><span>Priorita</span><b>${Number(x.priority||0)}/100</b></div><p class="muted">${esc(x.nextAction||'Sledovat event.')}</p></div>`,[{label:'Otevřít Ticket desk',value:'advanced',primary:true},{label:'Zavřít',value:null}]);if(choice==='advanced'){host.dataset.productAdvanced='1';await loadProductAdvancedStyles(['./ticket68.css','./ticketWorkspace210.css','./ticketDesk353.css','./ticketDesk355.css','./ticketDesk356.css']);const m=await import('./ticketAdvanced100.js');await m.renderTicketPage100?.()}return}})}
 window.__KAMIL_TICKET_OVERVIEW__={healthy:true,events:d.p.totalEvents,activeQty:d.p.queue.activeQty,capital:d.p.totalCapital,transfer:d.transfer.length,waitingPayout:waiting.length,realizedProfit:realized,waitingProfit,capitalExposure,deadlineRisk:deadlineRisk.length,issues:d.issues.length,attention:d.attention.length,masterId:d.s.ticketBook?.masterId||null,historyQty:d.master?.ticketQty||null,dynamicPrimary:true,directEvents:true,blank,at:Date.now()};return true;
}