import {loadTicketCloud660} from './ticketCloud660.js';
import {store} from './state.js';
import {h,money} from './utils.js';
const N=v=>Number(v||0),A=v=>Array.isArray(v)?v:[],U=v=>String(v||'').toUpperCase();
const ACTIVE=new Set(['LISTED','NOT_LISTED']),SOLD=new Set(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID']),PAID=new Set(['PAYOUT_RECEIVED','PAID']);
const daysBetween=(a,b)=>{const x=Date.parse(a||''),y=Date.parse(b||'');return Number.isFinite(x)&&Number.isFinite(y)?Math.max(1,Math.ceil((y-x)/86400000)):null};
function explicitNumber(values){for(const v of values)if(Number.isFinite(Number(v))&&Number(v)>=0)return Number(v);return null}
function buyBudget(){const s=store.get(),cash=explicitNumber([s.financePlan?.freeCashCzk,s.financePlan?.availableCashCzk,s.money?.freeCashCzk,s.cash?.availableCzk]),reserve=explicitNumber([s.financePlan?.cashReserveCzk,s.financePlan?.minimumReserveCzk,s.money?.minimumReserveCzk]);return{cash,reserve,budget:cash!==null?Math.max(0,cash-(reserve??0)):null}}
function rowState(r){const status=U(r.market_status),buy=N(r.buy_total_czk),sell=N(r.sell_total_czk),payout=Number(r.payout_received_czk),payoutKnown=Number.isFinite(payout)&&payout>0,fee=Number(r.marketplace_fee_czk),feeKnown=Number.isFinite(fee)&&fee>=0,net=payoutKnown?payout-buy:null,gross=SOLD.has(status)?sell-buy:null,holdDays=payoutKnown?daysBetween(r.imported_at,r.payout_recorded_at):null,efficiency=net!==null&&buy>0&&holdDays?net/buy/holdDays*100:null;return{r,status,buy,sell,payout:payoutKnown?payout:null,fee:feeKnown?fee:null,payoutKnown,net,gross,holdDays,efficiency,active:ACTIVE.has(status),sold:SOLD.has(status),paid:PAID.has(status)}}
function aggregate(rows){const s=rows.map(rowState),active=s.filter(x=>x.active),sold=s.filter(x=>x.sold),paid=s.filter(x=>x.paid),known=s.filter(x=>x.payoutKnown);return{rows:s,active,sold,paid,known,capitalLocked:active.reduce((a,x)=>a+x.buy,0),grossSales:sold.reduce((a,x)=>a+x.sell,0),grossPl:sold.reduce((a,x)=>a+(x.gross||0),0),actualPayout:known.reduce((a,x)=>a+x.payout,0),actualNetPl:known.reduce((a,x)=>a+(x.net||0),0),waitingGross:s.filter(x=>x.status==='SOLD_WAITING_PAYMENT').reduce((a,x)=>a+x.sell,0),undeliveredGross:s.filter(x=>x.status==='SOLD_UNDELIVERED').reduce((a,x)=>a+x.sell,0),buyBudget:buyBudget()}}
function eventRows(states){const m=new Map();for(const x of states){if(!x.sold)continue;const k=x.r.event_name||'Událost',z=m.get(k)||{name:k,trades:0,buy:0,sell:0,payout:0,net:0,known:0};z.trades++;z.buy+=x.buy;z.sell+=x.sell;if(x.payoutKnown){z.payout+=x.payout;z.net+=x.net;z.known++}m.set(k,z)}return [...m.values()].sort((a,b)=>b.net-a.net).slice(0,8)}
function efficiencyRows(states){return states.filter(x=>x.efficiency!==null).sort((a,b)=>b.efficiency-a.efficiency).slice(0,8)}
function card(label,value,sub=''){return `<article><small>${h(label)}</small><b>${value}</b>${sub?`<span>${h(sub)}</span>`:''}</article>`}
function renderSales(host,a){const sales=host.querySelector('[data-tv133-view="sales"]');if(!sales||sales.querySelector('[data-ticket-accounting155]'))return;const sec=document.createElement('section');sec.dataset.ticketAccounting155='1';sec.className='tv155-accounting';const events=eventRows(a.rows),eff=efficiencyRows(a.rows),b=a.buyBudget;sec.innerHTML=`<div class="tv133-section-head"><div><small>OS 155–159 · ACCOUNTING</small><h3>Ticket Accounting & Capital</h3></div></div><div class="tv155-kpis">${card('Kapitál v aktivních',money(a.capitalLocked),`${a.active.length} pozic`)}${card('Hrubé tržby',money(a.grossSales),'bez odečtu fee')}${card('Skutečné payouty',money(a.actualPayout),`${a.known.length}/${a.sold.length} prodejů`)}${card('Skutečný čistý P/L',a.known.length?`${a.actualNetPl>=0?'+':''}${money(a.actualNetPl)}`:'—','jen uložené payouty')}${card('Čeká payout · hrubá tržba',money(a.waitingGross),'není odhad čistého payoutu')}${card('OS 159 · max. cash nad rezervu',b.budget===null?'—':money(b.budget),b.cash===null?'volná hotovost není explicitně zadaná':`cash ${money(b.cash)}${b.reserve!==null?` · rezerva ${money(b.reserve)}`:' · rezerva není zadaná'}`)}</div><div class="tv155-grid"><section><small>OS 157 · PODLE AKCE</small>${events.map(x=>`<div class="tv155-row"><div><b>${h(x.name)}</b><span>${x.trades} obchodů · payout znám ${x.known}</span></div><strong>${x.known?`${x.net>=0?'+':''}${money(x.net)}`:'—'}</strong></div>`).join('')||'<p class="muted">Zatím nejsou prodané tickety.</p>'}</section><section><small>OS 158 · KAPITÁLOVÁ EFEKTIVITA</small>${eff.map(x=>`<div class="tv155-row"><div><b>${h(x.r.event_name||'Událost')}</b><span>${x.holdDays} dní · čistý P/L ${x.net>=0?'+':''}${money(x.net)}</span></div><strong>${x.efficiency.toFixed(3)} %/den</strong></div>`).join('')||'<p class="muted">Pro výpočet je potřeba skutečný payout a čas jeho zápisu.</p>'}</section></div><div class="tv155-note"><b>OS 156 · Cashflow:</b> čekající částky jsou hrubé evidované tržby, nikoli předpověď čistého payoutu. <b>OS 159:</b> uvedený budget je pouze matematický strop z explicitní hotovosti po odečtu explicitní rezervy; není to BUY doporučení.</div>`;sales.querySelector('.tv133-view-body')?.appendChild(sec);window.__KAMIL_TICKET_ACCOUNTING155__={at:Date.now(),...a}}
export async function enhanceTicketAccounting155(){const host=document.querySelector('#ticketIntelView');if(!host)return;let c;try{c=await loadTicketCloud660()}catch{return}if(!c?.ok)return;const a=aggregate(A(c.inventory));renderSales(host,a);return a}
export const ticketAccounting155Info={steps:[155,156,157,158,159],actualPayoutOnly:true,noForecastedNetPayout:true,buyBudget:'explicit free cash minus explicit reserve only'};