import {cloudClient,session} from './cloud.js';
import {loadTicketCloud660} from './ticketCloud660.js';

const VERSION=429,N=v=>Number(v||0),SOLD=new Set(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID']);let bound=false,timer=0,busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>N(v)?`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`:'—';
async function api(){const r=await fetch('/api/ticket-gmail-sync',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}),j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||`Gmail sync HTTP ${r.status}`);return j}
async function update(id,patch){const c=await cloudClient(),sess=await session();if(!c||!sess)throw new Error('Cloud session chybí.');const {error}=await c.from('ticket_inventory').update({...patch,updated_at:new Date().toISOString()}).eq('user_id',sess.user.id).eq('id',id);if(error)throw error}
function patchFor(r,m){const p={},status=String(r.market_status||''),tracked=Math.max(1,N(r.qty)||1),orderQty=Math.max(tracked,N(m.qty)||tracked),share=Math.min(1,tracked/orderQty);if(m.type==='transfer_confirmed'&&status==='SOLD_UNDELIVERED'){p.market_status='SOLD_WAITING_PAYMENT';p.delivered_at=m.ts||new Date().toISOString()}else if(['buyer','delivery_required'].includes(m.type)&&!['SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID'].includes(status)){p.market_status='SOLD_UNDELIVERED'}if(m.payout_czk&&(!N(r.sell_total_czk)||String(r.sale_source||'').includes('email'))){p.sell_total_czk=Math.round(N(m.payout_czk)*share*100)/100;p.sell_each_czk=p.sell_total_czk/tracked}if(m.fee_czk&&(!N(r.marketplace_fee_czk)||String(r.sale_source||'').includes('email')))p.marketplace_fee_czk=Math.round(N(m.fee_czk)*share*100)/100;if(Object.keys(p).length)p.sale_source='viagogo-gmail-auto';return p}
async function reconcile(messages,cloud){const byOrder=new Map((cloud.inventory||[]).filter(r=>SOLD.has(String(r.market_status||''))&&r.marketplace_order_id).map(r=>[String(r.marketplace_order_id),r])),seen=new Set(),updates=[],unmatched=[];for(const m of messages||[]){if(!m.order_id||seen.has(`${m.order_id}:${m.type}`))continue;seen.add(`${m.order_id}:${m.type}`);const r=byOrder.get(String(m.order_id));if(!r){unmatched.push(m);continue}const patch=patchFor(r,m);if(!Object.keys(patch).length)continue;await update(r.id,patch);updates.push({id:r.id,order:m.order_id,type:m.type,patch})}return{updates,unmatched}}
function ensureCss(){if(document.querySelector('style[data-gm429]'))return;const s=document.createElement('style');s.dataset.gm429='1';s.textContent=`#ticketIntelView .gm429{margin:10px 0 0;border:1px solid #253f51;border-radius:10px;background:#0a1923;color:#d9e7f1;padding:10px 12px}.gm429-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.gm429 span{display:block;font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#7899b1}.gm429 b{display:block;margin-top:3px;font-size:11px}.gm429 small{display:block;margin-top:2px;color:#7b90a1;font-size:8.5px}.gm429 button{min-height:30px;padding:0 10px;border:1px solid #35566c;border-radius:8px;background:#112735;color:#c7ddea;font-size:9px;font-weight:850;cursor:pointer}.gm429-list{margin-top:8px;padding-top:8px;border-top:1px solid #1e3443}.gm429-item{display:flex;justify-content:space-between;gap:10px;padding:5px 0;font-size:9px;color:#91a5b5}.gm429-good{color:#88d7aa}.gm429-warn{color:#efc17c}`;document.head.appendChild(s)}
function box(){const host=document.querySelector('#ticketIntelView .hub421-body')||document.querySelector('#ticketIntelView .td331');if(!host)return null;let el=document.querySelector('#ticketIntelView [data-gmail429]');if(!el){el=document.createElement('section');el.dataset.gmail429='1';el.className='gm429';host.appendChild(el)}return el}
function paint(state={}){ensureCss();const el=box();if(!el)return;const {configured=false,count=0,updates=[],unmatched=[],error=null}=state;el.innerHTML=`<div class="gm429-head"><div><span>GMAIL RECONCILIATION · OS429</span><b class="${configured?'gm429-good':'gm429-warn'}">${error?'CHYBA':configured?'PŘIPOJENO':'BACKEND NEPŘIPOJEN'}</b><small>${error?esc(error):configured?`${count} Viagogo mailů · ${updates.length} bezpečných změn · ${unmatched.length} bez přesného order ID v evidenci`:'Kód je připravený; chybí Google OAuth proměnné ve Vercelu.'}</small></div><button data-gm429-sync>${busy?'Synchronizuji…':'Synchronizovat'}</button></div>${unmatched.length?`<div class="gm429-list">${unmatched.slice(0,5).map(m=>`<div class="gm429-item"><span>${esc(m.type)} · ${esc(m.order_id)}</span><span>${esc(m.subject)}</span></div>`).join('')}</div>`:''}`;const b=el.querySelector('[data-gm429-sync]');if(b){b.disabled=busy;b.addEventListener('click',()=>run(true))}}
async function run(force=false){if(busy)return;const last=N(localStorage.getItem('kamil.gmail429.last')||0);if(!force&&Date.now()-last<6*36e5)return;busy=true;paint({configured:true});try{const j=await api();if(!j.configured){paint({configured:false,count:0,updates:[],unmatched:[]});return}const cloud=await loadTicketCloud660();if(!cloud?.ok)throw new Error('Ticket cloud není dostupný.');const result=await reconcile(j.messages||[],cloud);localStorage.setItem('kamil.gmail429.last',String(Date.now()));paint({configured:true,count:j.count||0,...result});if(result.updates.length){window.dispatchEvent(new CustomEvent('kamil:ticket-reconcile412-saved',{detail:{source:'gmail-auto',count:result.updates.length}}));window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}))}}catch(e){paint({configured:true,error:String(e?.message||e),updates:[],unmatched:[]})}finally{busy=false;setTimeout(()=>paint(window.__KAMIL_TICKET_GMAIL429__||{}),100)}window.__KAMIL_TICKET_GMAIL429__={version:VERSION,healthy:true,at:Date.now()}}
function schedule(ms=900){clearTimeout(timer);timer=setTimeout(()=>{paint(window.__KAMIL_TICKET_GMAIL429__||{});run(false)},ms)}
export function installTicketGmailSync429(){if(bound)return;bound=true;ensureCss();window.addEventListener('kamil:view-change',e=>{if(e.detail==='tickets')schedule()});const host=document.querySelector('#ticketIntelView');if(host)new MutationObserver(()=>paint(window.__KAMIL_TICKET_GMAIL429__||{})).observe(host,{childList:true,subtree:true});schedule(2500)}
