import {loadTicketCloud660} from './ticketCloud660.js';
import {cloudClient,session} from './cloud.js';
import {h,money} from './utils.js';
const N=v=>Number(v||0),A=v=>Array.isArray(v)?v:[],DAY=86400000;
const active=s=>['LISTED','NOT_LISTED'].includes(String(s||'').toUpperCase());
const sold=s=>['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID'].includes(String(s||'').toUpperCase());
const latest=(c,id)=>c.latest?.get(id)||null;
function days(d){const t=d?new Date(d).getTime():NaN;return Number.isFinite(t)?Math.ceil((t-Date.now())/DAY):null}
function score(r,s){const m=N(s?.market_price_czk)||N(s?.viagogo_price_czk)||N(s?.stubhub_price_czk),buy=N(r.buy_each_czk),d=days(r.event_date);let x=50;if(m&&buy){const spread=(m-buy)/Math.max(1,buy)*100;x+=Math.max(-25,Math.min(30,spread*.35))}const conf=N(s?.multi_market_confidence);if(conf)x+=(conf-50)*.18;if(d!==null&&d>=0&&d<=14)x+=6;if(String(s?.recommendation_code||'')==='LOWER')x-=10;if(String(s?.recommendation_code||'')==='RAISE')x+=7;return Math.max(5,Math.min(95,Math.round(x)))}
function stage(s){s=String(s||'').toUpperCase();if(s==='SOLD_UNDELIVERED')return'deliver';if(s==='SOLD_WAITING_PAYMENT')return'payout';if(['PAYOUT_RECEIVED','PAID'].includes(s))return'paid';return'sold'}
function miniCard(r,c){const s=latest(c,r.id)||{},m=N(s.market_price_czk)||N(s.viagogo_price_czk)||N(s.stubhub_price_czk),buy=N(r.buy_each_czk),ask=N(r.ask_each_czk),sc=score(r,s),d=days(r.event_date);return `<article class="tv133-radar-card"><div class="tv133-radar-top"><div><b>${h(r.event_name||'Událost')}</b><small>${h(r.section||'bez sektoru')} · ${N(r.qty||1)} ks${d!==null&&d>=0?` · ${d===0?'DNES':`${d} dní`}`:''}</small></div><span class="tv133-score ${sc>=75?'buy':sc<45?'avoid':'watch'}">${sc>=75?'BUY':sc<45?'AVOID':'WATCH'} ${sc}</span></div><div class="tv133-radar-metrics"><span>Nákup <b>${buy?money(buy):'—'}</b></span><span>Trh <b>${m?money(m):'—'}</b></span><span>Moje <b>${ask?money(ask):'—'}</b></span></div><div class="tv133-radar-foot"><span>${h(s.recommendation_label||s.recommendation_code||'SLEDOVAT')}</span><span>${N(s.multi_market_confidence)?`Confidence ${N(s.multi_market_confidence)} %`:'čeká na více dat'}</span></div></article>`}
function salesCard(r){const profit=N(r.sell_total_czk)-N(r.buy_total_czk),status=String(r.market_status||'').toUpperCase(),action=status==='SOLD_UNDELIVERED'?'<button class="btn" data-ticket-sale-action data-status="SOLD_UNDELIVERED" data-id="'+h(r.id)+'">Označit doručeno</button>':status==='SOLD_WAITING_PAYMENT'?'<button class="btn" data-ticket-sale-action data-status="SOLD_WAITING_PAYMENT" data-id="'+h(r.id)+'">Označit vyplaceno</button>':'<span class="muted">Workflow dokončen</span>';return `<article class="tv133-sale-card" data-ticket-sale-id="${h(r.id)}"><div><b>${h(r.event_name||'Událost')}</b><small>${h(r.section||'')} · ${N(r.qty||1)} ks</small></div><div class="tv133-sale-money"><span>${N(r.sell_each_czk)?money(r.sell_each_czk):'—'} / ks</span><b class="${profit>=0?'good':'bad'}">${profit>=0?'+':''}${money(profit)}</b></div><div class="tv133-sale-action"><button class="btn" data-ticket-sale-detail data-id="${h(r.id)}">Detail</button>${action}</div></article>`}
async function loadStats(){try{const c=await cloudClient(),sess=await session();if(!c||!sess)return[];const {data,error}=await c.from('ticket_strategy_stats').select('*').eq('user_id',sess.user.id).order('profit_czk',{ascending:false});return error?[]:A(data)}catch{return[]}}
function intelligence(stats){const overall=stats.find(x=>x.stat_type==='OVERALL')||{},cats=stats.filter(x=>x.stat_type==='CATEGORY'),families=stats.filter(x=>x.stat_type==='FAMILY');const best=[...families].sort((a,b)=>N(b.profit_czk)-N(a.profit_czk)).slice(0,7),max=Math.max(1,...best.map(x=>Math.abs(N(x.profit_czk))));return `<div class="tv133-intel-kpis"><article><small>Historické obchody</small><b>${N(overall.trades)||'—'}</b></article><article><small>Win rate</small><b>${N(overall.win_rate)?`${N(overall.win_rate).toFixed(1)} %`:'—'}</b></article><article><small>Historické ROI</small><b>${N(overall.roi)?`${N(overall.roi).toFixed(1)} %`:'—'}</b></article><article><small>Hrubý zisk</small><b>${N(overall.profit_czk)?money(overall.profit_czk):'—'}</b></article></div><div class="tv133-intel-grid"><section><div class="tv133-section-head"><div><small>HISTORIE</small><h3>Nejvýdělečnější rodiny</h3></div></div><div class="tv133-bars">${best.map(x=>`<div class="tv133-bar"><div><b>${h(x.stat_key)}</b><small>${N(x.trades)} obchodů · ROI ${N(x.roi).toFixed(1)} %</small></div><span><i style="width:${Math.max(4,Math.abs(N(x.profit_czk))/max*100)}%"></i></span><strong>${money(x.profit_czk)}</strong></div>`).join('')||'<p class="muted">Historické agregace zatím nejsou dostupné.</p>'}</div></section><section><div class="tv133-section-head"><div><small>STRATEGIE</small><h3>BUY / WATCH / AVOID</h3></div></div><div class="tv133-heat">${cats.map(x=>`<article class="${String(x.verdict||'WATCH').toLowerCase()}"><b>${h(x.stat_key)}</b><span>${h(x.verdict||'WATCH')}</span><small>${N(x.trades)} obchodů · win ${N(x.win_rate).toFixed(0)} % · ROI ${N(x.roi).toFixed(1)} %</small></article>`).join('')||'<p class="muted">Čeká na strategická data.</p>'}</div></section></div>`}
function mountView(shell,id,title,html){let v=shell.querySelector(`[data-tv133-view="${id}"]`);if(!v){v=document.createElement('section');v.className='tv133-view';v.dataset.tv133View=id;v.innerHTML=`<div class="tv133-view-head"><div><div class="eyebrow">VSTUPENKY · ${id.toUpperCase()}</div><h2>${title}</h2></div></div><div class="tv133-view-body">${html}</div>`;shell.querySelector('.tv132-tools')?.before(v)}return v}
function show(shell,id){shell.querySelectorAll('.tv132-nav button').forEach(b=>b.classList.toggle('on',String(b.textContent||'').trim().toLowerCase()===id));const portfolio=['portfolio'].includes(id);shell.querySelector('.tv132-kpis').hidden=!portfolio;shell.querySelector('.tv132-tools').hidden=!portfolio;shell.querySelector('.tv132-grid').hidden=!portfolio;shell.querySelectorAll('[data-tv133-view]').forEach(v=>v.hidden=v.dataset.tv133View!==id)}
export async function enhanceTicketVisual133(){const shell=document.querySelector('.tv132-shell');if(!shell||shell.dataset.tv133==='1')return;shell.dataset.tv133='1';let c;try{c=await loadTicketCloud660()}catch{return}if(!c?.ok)return;const inv=A(c.inventory),activeRows=inv.filter(x=>active(x.market_status)),soldRows=inv.filter(x=>sold(x.market_status));const radar=[...activeRows].sort((a,b)=>score(b,latest(c,b.id))-score(a,latest(c,a.id)));mountView(shell,'radar','Market Radar',`<div class="tv133-radar-summary"><article><small>Aktivní kandidáti</small><b>${radar.length}</b></article><article><small>BUY ≥ 75</small><b>${radar.filter(r=>score(r,latest(c,r.id))>=75).length}</b></article><article><small>Vyžaduje pozornost</small><b>${radar.filter(r=>['LOWER','VERIFY_DATA'].includes(String(latest(c,r.id)?.recommendation_code||''))).length}</b></article></div><div class="tv133-radar-grid">${radar.map(r=>miniCard(r,c)).join('')||'<p class="muted">Žádné aktivní tickety.</p>'}</div>`);const cols=[['deliver','DORUČIT'],['payout','ČEKÁ PAYOUT'],['paid','VYPLACENO']];const realized=soldRows.reduce((a,x)=>a+N(x.sell_total_czk)-N(x.buy_total_czk),0);mountView(shell,'sales','Sales & Payout',`<div class="tv133-sales-kpis"><article><small>Prodané kusy</small><b>${soldRows.reduce((a,x)=>a+N(x.qty),0)}</b></article><article><small>Tržby</small><b>${money(soldRows.reduce((a,x)=>a+N(x.sell_total_czk),0))}</b></article><article><small>Realizovaný P/L</small><b class="${realized>=0?'good':'bad'}">${realized>=0?'+':''}${money(realized)}</b></article></div><div class="tv133-kanban">${cols.map(([key,label])=>{const rows=soldRows.filter(x=>stage(x.market_status)===key);return`<section><header><b>${label}</b><span>${rows.length}</span></header><div>${rows.map(salesCard).join('')||'<p class="tv133-emptycol">Nic tady není.</p>'}</div></section>`}).join('')}</div>`);const stats=await loadStats();mountView(shell,'intelligence','Ticket Intelligence',intelligence(stats));shell.querySelectorAll('.tv133-view').forEach(v=>v.hidden=true);const nav=[...shell.querySelectorAll('.tv132-nav button')];for(const b of nav){const id=String(b.textContent||'').trim().toLowerCase();b.onclick=()=>show(shell,id)}show(shell,'portfolio');window.__KAMIL_TICKET_VISUAL133__={at:Date.now(),active:activeRows.length,sold:soldRows.length,stats:stats.length}}
