const VERSION=464,N=v=>Number(v||0);let bound=false,timer=0;
function quality(r){let s=50;const sec=String(r.section||r.sector||'').toLowerCase(),row=String(r.row_label||r.row||'').toLowerCase();if(/101|115|c11|a2|a3|standing/.test(sec))s+=12;if(/220|414|415|416|405/.test(sec))s+=3;if(/row ?1|řada ?1|front/.test(row))s+=12;return Math.max(0,Math.min(100,s))}
function quantityPlan(m){const q=Math.max(1,N(m.r.qty)||1),paired=m.best?.s?.quantity_matched===true,liq=N(m.liquidity?.score);if(q>=4){if(paired&&liq>=65)return'4 spolu';if(liq>=45)return'2 + 2';return'1 + 1 + 1 + 1'}if(q===3)return liq>=60?'3 spolu':'2 + 1';if(q===2)return paired?'2 spolu':'1 + 1';return'1 ks'}
function demandWindow(m){const d=N(m.days),liq=N(m.liquidity?.score),mom=N(m.momentum?.score);if(d<=3)return'vrchol poptávky nyní';if(d<=7)return liq>=55?'silnější okno 48–72 h':'čekat jen s kontrolou';if(d<=14)return mom>=50?'pravděpodobný růst zájmu 5–9 d':'nejisté, hlídat trend';return'časná fáze · likvidita může růst'}
function build(){const eng=window.__KAMIL_TICKET_ENGINE426__;if(!eng?.models)return{rows:[],events:[]};const rows=eng.models.map(m=>{const q=quality(m.r),premium=(q-50)*.18;return{id:String(m.r.id),r:m.r,quantityPlan:quantityPlan(m),seatQuality:q,seatPremiumPct:premium,liquidityForecast:demandWindow(m),market:N(m.market),score:N(m.liquidity?.score)+N(m.momentum?.score)*.35+premium}});const map=new Map();for(const x of rows){const k=String(x.r.event_name||'').split(' - ')[0]||x.r.event_name,g=map.get(k)||{name:k,positions:0,tickets:0,capital:0,score:0,plans:[]};g.positions++;g.tickets+=Math.max(1,N(x.r.qty)||1);g.capital+=N(x.r.buy_total_czk);g.score=Math.max(g.score,x.score);g.plans.push(x.quantityPlan);map.set(k,g)}return{rows,events:[...map.values()].sort((a,b)=>b.capital-a.capital)}}
function ensureCss(){if(document.querySelector('style[data-es464]'))return;const s=document.createElement('style');s.dataset.es464='1';s.textContent=`#ticketIntelView .es464{margin:0 0 6px;padding:7px 9px;border:1px solid #2c4759;border-radius:9px;background:#0a1923;color:#dce9f2;display:flex;gap:12px;align-items:center;flex-wrap:wrap}.es464 span{font-size:8px;font-weight:900;color:#7898ad;text-transform:uppercase}.es464 b{font-size:10px}`;document.head.appendChild(s)}
function render(){ensureCss();const m=build();window.__KAMIL_TICKET_EVENT_STRATEGY464__={version:VERSION,healthy:true,...m,at:Date.now()};document.documentElement.dataset.ticketEventStrategy464='1';const host=document.querySelector('#ticketIntelView .td331');if(!host)return;let box=host.querySelector('[data-es464]');if(!box){box=document.createElement('section');box.dataset.es464='1';box.className='es464';host.querySelector('[data-ca463]')?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.querySelector('[data-focus459]')?.insertAdjacentElement('beforebegin',box)}const split=m.rows.filter(x=>/\+/.test(x.quantityPlan)).length,hi=m.rows.filter(x=>x.seatQuality>=65).length;box.innerHTML=`<span>EVENT STRATEGY · OS464</span><b>${m.events.length} eventů</b><b>${split} split strategií</b><b>${hi} premium seat pozic</b>`;window.dispatchEvent(new CustomEvent('kamil:ticket-event464-updated',{detail:{events:m.events.length}}))}
function schedule(ms=180){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketEventStrategy464(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-engine426-updated','kamil:ticket-cadence463-updated'])window.addEventListener(ev,()=>schedule());schedule(3800)}
