import {loadTicketCloud660} from './ticketCloud660.js';
import {money} from './utils.js';
const A=v=>Array.isArray(v)?v:[];
const U=v=>String(v||'').toUpperCase();
const sold=s=>['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID'].includes(U(s));
const paid=s=>['PAYOUT_RECEIVED','PAID'].includes(U(s));
const payoutKeys=['payout_received_czk','payout_czk','payout_total_czk','net_payout_czk','net_received_czk','received_czk'];
const feeKeys=['marketplace_fee_czk','fee_czk','fees_czk','fee_total_czk','platform_fee_czk'];
const finite=v=>v!==null&&v!==''&&Number.isFinite(Number(v));
function firstNumber(row,keys){for(const k of keys)if(finite(row?.[k]))return Number(row[k]);return null}
export function ticketSettlementState153(row={}){const payout=firstNumber(row,payoutKeys),fee=firstNumber(row,feeKeys),status=U(row.market_status),workflowPaid=paid(status),buy=finite(row.buy_total_czk)?Number(row.buy_total_czk):null,netProfit=payout!==null&&buy!==null?payout-buy:null;return{status,workflowPaid,payout,fee,payoutKnown:payout!==null,feeKnown:fee!==null,accountingComplete:workflowPaid&&payout!==null,payoutRecordedAt:row.payout_recorded_at||null,netProfit,netProfitKnown:netProfit!==null};}
export async function enhanceTicketSettlement153(){const host=document.querySelector('#ticketIntelView');if(!host)return;let cloud;try{cloud=await loadTicketCloud660()}catch{return}if(!cloud?.ok)return;const rows=A(cloud.inventory).filter(x=>sold(x.market_status)),states=rows.map(ticketSettlementState153),known=states.filter(x=>x.payoutKnown).length,paidCount=states.filter(x=>x.workflowPaid).length,complete=states.filter(x=>x.accountingComplete).length,netKnown=states.filter(x=>x.netProfitKnown).reduce((a,x)=>a+x.netProfit,0);const sales=host.querySelector('[data-tv133-view="sales"]');if(!sales)return;const kpis=sales.querySelector('.tv133-sales-kpis');if(kpis&&!kpis.querySelector('[data-settlement153]')){const box=document.createElement('article');box.dataset.settlement153='1';box.innerHTML=`<small>Čistý payout znám</small><b>${known}/${rows.length}</b><span class="muted">Workflow vyplaceno ${paidCount} · účetně kompletní ${complete}${known?` · čistý P/L ${money(netKnown)}`:''}</span>`;kpis.appendChild(box)}for(const card of sales.querySelectorAll('[data-ticket-sale-id]')){if(card.querySelector('[data-settlement153-note]'))continue;const id=String(card.dataset.ticketSaleId||''),row=rows.find(x=>String(x.id)===id);if(!row)continue;const s=ticketSettlementState153(row);if(!s.workflowPaid)continue;const note=document.createElement('small');note.dataset.settlement153Note='1';note.className='muted';note.textContent=s.payoutKnown?`Skutečný payout ${money(s.payout)}${s.netProfitKnown?` · čistý P/L ${s.netProfit>=0?'+':''}${money(s.netProfit)}`:''}${s.feeKnown?` · fee ${money(s.fee)}`:''}`:'Workflow vyplaceno · čistá payout částka není uložená';card.appendChild(note)}window.__KAMIL_TICKET_SETTLEMENT153__={at:Date.now(),sold:rows.length,workflowPaid:paidCount,payoutKnown:known,accountingComplete:complete,knownNetProfitCzk:known?netKnown:null,schemaContract:'canonical payout_received_czk + optional marketplace_fee_czk from OS154'};}
export const ticketSettlement153Info={noEstimatedFees:true,noEstimatedPayout:true,workflowPaidIsNotAccountingComplete:true,canonicalPayoutField:'payout_received_czk'};
