import {cloudClient,session} from './cloud.js';
import {loadTicketCloud660,scanTicketsNow660,ACTIVE_TICKET_STATUSES} from './ticketCloud660.js';
const VERSION=397,N=v=>Number(v||0);
async function ctx(){return{c:await cloudClient(),sess:await session()}}
function itemsFrom(inventory=[]){return inventory.filter(x=>ACTIVE_TICKET_STATUSES.has(x.market_status||x.marketStatus)).map(x=>({id:x.id,label:x.event_name||x.eventName,event:x.event_name||x.eventName,date:x.event_date||x.eventDate,section:x.section||null,row:x.row_label||x.rowLabel||x.row||null,qty:Number(x.qty||1),buyEachCzk:N(x.buy_each_czk??x.buyEachCzk),status:x.market_status||x.marketStatus,viagogoUrl:x.viagogo_url||x.viagogoUrl||null,stubhubUrl:x.stubhub_url||x.stubhubUrl||null,officialUrl:x.official_url||x.officialUrl||null,askEachCzk:N(x.ask_each_czk??x.askEachCzk)||null}))}
async function post(url,body){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),raw=await r.text();let j;try{j=JSON.parse(raw)}catch{throw new Error(`${url} nevrátil JSON (${r.status})`)}if(!r.ok||!j.ok)throw new Error(j.error||`${url} HTTP ${r.status}`);return j}
function snapshot(x,userId){return{user_id:userId,ticket_id:x.id,checked_at:x.market?.checkedAt||new Date().toISOString(),market_price_czk:N(x.market?.marketPriceCzk??x.market?.priceCzk)||null,median_price_czk:N(x.market?.medianPriceCzk)||null,p25_price_czk:N(x.market?.p25PriceCzk)||null,p75_price_czk:N(x.market?.p75PriceCzk)||null,top_prices_czk:Array.isArray(x.market?.topPricesCzk)?x.market.topPricesCzk:[],competitor_count:N(x.market?.competitorCount)||null,same_section_count:N(x.market?.sameSectionCount)||null,same_row_count:N(x.market?.sameRowCount)||null,quantity_required:N(x.market?.quantityRequired)||null,quantity_matched:typeof x.market?.quantityMatched==='boolean'?x.market.quantityMatched:null,supply_pct:N(x.market?.supplyPct)||null,confidence:x.market?.confidence||null,resolved_url:x.market?.resolvedUrl||x.source?.url||null,recommendation_code:x.recommendation?.code||null,recommendation_label:x.recommendation?.label||null,recommendation_reason:x.recommendation?.reason||null,recommended_ask_czk:N(x.recommendation?.recommendedAskCzk)||null,source_status:x.source?.status||null,source_message:x.source?.message||null}}
async function saveDetailed(results,userId,c){const rows=(results||[]).map(x=>snapshot(x,userId));if(!rows.length)return 0;const {error}=await c.from('ticket_market_snapshots').insert(rows);if(error)throw new Error(error.message||'Uložení detailního market snapshotu selhalo.');return rows.length}
const safeViagogo=v=>{try{const u=new URL(v);return u.protocol==='https:'&&/(^|\.)viagogo\.com$/i.test(u.hostname)?u.toString():null}catch{return null}};
async function persistDiscoveredSources(items,results,userId,c){let count=0;for(const row of results||[]){const item=items.find(x=>String(x.id)===String(row.id));if(!item||item.viagogoUrl)continue;const discovered=safeViagogo(row.market?.resolvedUrl||row.source?.url);if(!discovered)continue;const {error}=await c.from('ticket_inventory').update({viagogo_url:discovered,updated_at:new Date().toISOString()}).eq('user_id',userId).eq('id',row.id);if(!error)count++;else console.warn('[ticket397] discovered Viagogo URL persist failed',row.id,error)}return count}
export async function scanTicketsFull395(inventory=null){let inv=Array.isArray(inventory)?inventory:null;if(!inv){const cloud=await loadTicketCloud660();if(!cloud?.ok)throw cloud?.error||new Error('Ticket cloud není dostupný');inv=cloud.inventory||[]}const items=itemsFrom(inv);if(!items.length)return{ok:true,version:VERSION,items:0,saved:0,base:null,detailed:{ok:true,results:[],summary:{total:0}},diagnostics:{message:'Žádné aktivní vstupenky ke skenování.'}};const {c,sess}=await ctx();if(!c||!sess)throw new Error('Cloud session chybí — market data nelze uložit.');let base=null,baseError=null;try{base=await scanTicketsNow660(inv)}catch(e){baseError=String(e?.message||e)}let detailed,detailedError=null,saved=0,persistedSources=0;try{detailed=await post('/api/ticket-market-watch-v4',{items});saved=await saveDetailed(detailed.results,sess.user.id,c);persistedSources=await persistDiscoveredSources(items,detailed.results,sess.user.id,c)}catch(e){detailedError=String(e?.message||e);detailed={ok:false,results:[],summary:{total:items.length,sourcesError:items.length}}}const ok=!!base||!!(detailed?.ok),summary=detailed?.summary||{},diagnostics={active:items.length,legacyOrOfficialOk:!!base,legacyOrOfficialError:baseError,detailedOk:!!detailed?.ok,detailedError,rowMatched:N(summary.rowMatched),sectionMatched:N(summary.sectionMatched),quantityMatched:N(summary.quantityMatched),fallbackNeeded:N(summary.fallbackNeeded),fallbackRecovered:N(summary.fallbackRecovered),sourcesOk:N(summary.sourcesOk),sourcesMissing:N(summary.sourcesMissing),sourcesError:N(summary.sourcesError),persistedSources,detailedSaved:saved};try{localStorage.setItem('kamil.ticket.scan.397',JSON.stringify({...diagnostics,at:new Date().toISOString()}))}catch{}window.__KAMIL_TICKET_SCAN395__={version:VERSION,healthy:ok,base,detailed,diagnostics,at:Date.now()};window.dispatchEvent(new CustomEvent('kamil:ticket-scan395-done',{detail:diagnostics}));if(!ok)throw new Error([baseError,detailedError].filter(Boolean).join(' | ')||'Ticket scan selhal.');return{ok:true,version:VERSION,items:items.length,saved:(N(base?.saved)+saved),base,detailed,diagnostics}}
