import {ownEvent1100,schedule1100} from './runtimeOwnership1100.js';

const VERSION=455,OWNER='tickets.runtime455';let bound=false;
const now=()=>Date.now(),active=()=>!!document.querySelector('#view-tickets.on'),age=s=>s?.at?Math.max(0,(now()-Number(s.at))/1000):null;
const modules=[
  ['ENGINE','__KAMIL_TICKET_ENGINE426__',900],['UI','__KAMIL_TICKET_ENGINE_UI427__',900],['PORTFOLIO','__KAMIL_TICKET_PORTFOLIO428__',900],
  ['QUALITY','__KAMIL_TICKET_QUALITY444__',900],['CONSENSUS','__KAMIL_TICKET_CONSENSUS445__',900],['RISK','__KAMIL_TICKET_RISKOPS446__',900],
  ['OPTIMIZER','__KAMIL_TICKET_OPTIMIZER447__',900],['GOVERNANCE','__KAMIL_TICKET_GOVERNANCE451__',900],['REGIME','__KAMIL_TICKET_REGIME452__',900],
  ['CAPITAL','__KAMIL_TICKET_CAPITAL453__',900],['COMMANDER CORE','__KAMIL_TICKET_COMMANDER454__',900],['WORKFLOW','__KAMIL_TICKET_WORKFLOW461__',900],
  ['ANALYTICS','__KAMIL_TICKET_ANALYTICS462__',900],['CADENCE','__KAMIL_TICKET_CADENCE463__',900],['EVENT STRATEGY','__KAMIL_TICKET_EVENT_STRATEGY464__',900],
  ['COMMANDER','__KAMIL_TICKET_COMMANDER465__',900]
];
function inspect(){const rows=modules.map(([label,key,max])=>{const s=window[key],a=age(s);let state='WAIT';if(s){if(s.healthy===false)state='ERROR';else if(a!==null&&a>max)state='STALE';else state='OK'}return{label,key,state,age:a,max,error:s?.error||null}});const engine=window.__KAMIL_TICKET_ENGINE426__,ui=window.__KAMIL_TICKET_ENGINE_UI427__,models=engine?.models?.length||0,painted=Number(ui?.painted||0),paintErrors=ui?.errors||[],coverage=models?Math.round(painted/models*100):0;const hard=rows.filter(x=>x.state==='ERROR').length+paintErrors.length,stale=rows.filter(x=>x.state==='STALE').length,waiting=rows.filter(x=>x.state==='WAIT').length,finalReady=!!window.__KAMIL_TICKET_COMMANDER465__?.healthy;const status=hard?'ERROR':stale?'STALE':waiting||!finalReady?'STARTING':coverage<100&&models?'PARTIAL':'OK';return{rows,status,hard,stale,waiting,models,painted,coverage,paintErrors,finalReady}}
function ensureCss(){if(document.querySelector('style[data-rh455]'))return;const s=document.createElement('style');s.dataset.rh455='1';s.textContent=`#ticketIntelView .rh455{margin:0 0 10px;border:1px solid rgba(255,255,255,.08);border-radius:12px;background:#11161d;color:#e7ebf0;overflow:hidden}.rh455-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 11px;cursor:pointer}.rh455-title{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.rh455 span{font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#7f8996}.rh455 b{font-size:10px}.rh455-ok{color:#7fd0a2}.rh455-warn{color:#e7be71}.rh455-bad{color:#eb8d94}.rh455-body{display:none;border-top:1px solid rgba(255,255,255,.06);padding:9px 10px}.rh455.open .rh455-body{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.rh455-row{padding:7px 8px;border:1px solid rgba(255,255,255,.06);border-radius:9px;background:#0d1218}.rh455-row small{display:block;margin-top:2px;color:#77818d;font-size:8px}.rh455-btn{border:1px solid rgba(255,255,255,.09);border-radius:9px;background:#151b23;color:#d6dbe2;padding:6px 9px;font-size:8px;font-weight:900;cursor:pointer}@media(max-width:800px){.rh455.open .rh455-body{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function retry(){if(!active())return;window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}));window.dispatchEvent(new CustomEvent('kamil:ticket-refresh397-done',{detail:{source:'health455'}}));schedule1100(OWNER,'retry-paint',paint,900,{pauseWhenHidden:true})}
function paint(){if(!active())return;ensureCss();const host=document.querySelector('#ticketIntelView .td331');if(!host)return;const m=inspect();let box=document.querySelector('#ticketIntelView [data-runtime455]');if(!box){box=document.createElement('section');box.dataset.runtime455='1';box.className='rh455';host.appendChild(box)}const open=box.classList.contains('open'),tone=m.status==='OK'?'ok':m.status==='ERROR'?'bad':'warn';box.innerHTML=`<div class="rh455-head"><div class="rh455-title"><span>RUNTIME HEALTH</span><b class="rh455-${tone}">${m.status}</b><span>cards ${m.painted}/${m.models}</span><span>coverage ${m.coverage}%</span><span>stale ${m.stale}</span><span>errors ${m.hard}</span></div><button class="rh455-btn" data-rh455-retry>Obnovit řetězec</button></div><div class="rh455-body">${m.rows.map(x=>`<div class="rh455-row"><span>${x.label}</span><b class="rh455-${x.state==='OK'?'ok':x.state==='ERROR'?'bad':'warn'}">${x.state}</b><small>${x.age===null?'čeká na první běh':`${Math.round(x.age)} s`}${x.error?` · ${String(x.error).slice(0,80)}`:''}</small></div>`).join('')}${m.paintErrors.map(x=>`<div class="rh455-row"><span>CARD ${x.id}</span><b class="rh455-bad">PAINT ERROR</b><small>${String(x.error).slice(0,100)}</small></div>`).join('')}</div>`;if(open)box.classList.add('open');box.querySelector('.rh455-head')?.addEventListener('click',e=>{if(e.target.closest('[data-rh455-retry]'))return;box.classList.toggle('open')});box.querySelector('[data-rh455-retry]')?.addEventListener('click',retry);window.__KAMIL_TICKET_RUNTIME455__={version:VERSION,healthy:m.status==='OK',...m,runtimeOwner:OWNER,at:now()};document.documentElement.dataset.ticketRuntime455=m.status.toLowerCase();window.dispatchEvent(new CustomEvent('kamil:ticket-runtime455-updated',{detail:{status:m.status}}))}
function schedule(ms=120){if(!active())return;schedule1100(OWNER,'paint',paint,ms,{pauseWhenHidden:true})}
function cadence(){if(active())schedule(0);schedule1100(OWNER,'cadence',cadence,60000,{pauseWhenHidden:true})}
export function installTicketRuntimeHealth455(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-engine426-updated','kamil:ticket-engine427-updated','kamil:ticket-portfolio428-updated','kamil:ticket-quality444-updated','kamil:ticket-governance451-updated','kamil:ticket-regime452-updated','kamil:ticket-capital453-updated','kamil:ticket-commander454-updated','kamil:ticket-workflow461-updated','kamil:ticket-analytics462-updated','kamil:ticket-cadence463-updated','kamil:ticket-event464-updated','kamil:ticket-commander465-updated'])ownEvent1100(OWNER,window,ev,()=>schedule());schedule(14500);schedule1100(OWNER,'cadence',cadence,60000,{pauseWhenHidden:true})}
