import {loadTicketCloud660} from './ticketCloud660.js';
const VERSION=410,N=v=>Number(v||0);let bound=false,timer=0,busy=false;
const CLOSED=new Set(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID']);
const fmt=v=>N(v)?`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`:'—';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const when=iso=>{const t=Date.parse(iso||'');if(!Number.isFinite(t))return'bez termínu';return new Intl.DateTimeFormat('cs-CZ',{day:'numeric',month:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(t))};
const hoursTo=iso=>{const t=Date.parse(iso||'');return Number.isFinite(t)?(t-Date.now())/36e5:null};
function ensureCss(){if(document.querySelector('style[data-sg408]'))return;const s=document.createElement('style');s.dataset.sg408='1';s.textContent=`#ticketIntelView .sg408{margin:0 0 14px;border:1px solid #31495b;border-radius:13px;background:#0c1720;color:#dce9f5;overflow:hidden}.sg408-head{display:grid;grid-template-columns:1.4fr repeat(3,1fr);gap:8px;padding:11px 12px}.sg408 span{display:block;font-size:8px;font-weight:800;letter-spacing:.07em;text-transform:uppercase;color:#7899b2}.sg408 b{display:block;margin-top:3px;font-size:13px}.sg408 small{display:block;color:#7f95a6;font-size:9px;margin-top:2px}.sg408-list{border-top:1px solid #203441}.sg408-row{display:grid;grid-template-columns:1.5fr .7fr .7fr .7fr;gap:9px;align-items:center;padding:9px 12px;border-top:1px solid #172a36}.sg408-row:first-child{border-top:0}.sg408-row strong{font-size:10px}.sg408-row.urgent{background:rgba(125,45,45,.12)}@media(max-width:760px){.sg408-head{grid-template-columns:1fr 1fr}.sg408-row{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function model(cloud){const rows=(cloud.inventory||[]).filter(r=>CLOSED.has(String(r.market_status||'').toUpperCase())),delivery=rows.filter(r=>String(r.market_status).toUpperCase()==='SOLD_UNDELIVERED'),waiting=rows.filter(r=>String(r.market_status).toUpperCase()==='SOLD_WAITING_PAYMENT'),paid=rows.filter(r=>['PAYOUT_RECEIVED','PAID'].includes(String(r.market_status||'').toUpperCase())),pending=waiting.reduce((a,r)=>a+N(r.sell_total_czk),0),urgent=delivery.filter(r=>{const h=hoursTo(r.delivery_due_at);return h!==null&&h<=72}).length;return{rows,delivery,waiting,paid,pending,urgent}}
function signature(m){return m.rows.map(r=>[r.id,r.market_status,r.qty,r.sell_total_czk,r.marketplace_order_id,r.delivery_due_at,r.delivered_at,r.payout_received_czk].join(':')).sort().join('|')}
async function render(){if(busy)return;const host=document.querySelector('#ticketIntelView .td331');if(!host)return;busy=true;try{ensureCss();const cloud=await loadTicketCloud660();if(!cloud?.ok)return;const m=model(cloud);let box=host.querySelector('[data-sold-guard408]');if(!box){box=document.createElement('section');box.dataset.soldGuard408='1';box.className='sg408';const auto=host.querySelector('[data-ticket-autopilot407]')||host.querySelector('.ta407');auto?.insertAdjacentElement('afterend',box);if(!box.isConnected){const hero=host.querySelector('.td331-hero');hero?.insertAdjacentElement('afterend',box)}}const sig=signature(m);if(box.dataset.sig!==sig){box.dataset.sig=sig;const focus=[...m.delivery,...m.waiting].sort((a,b)=>Date.parse(a.delivery_due_at||'9999')-Date.parse(b.delivery_due_at||'9999')).slice(0,6);box.innerHTML=`<div class="sg408-head"><div><span>SALE GUARD · OS410</span><b>${m.delivery.length?'DORUČIT '+m.delivery.length:m.waiting.length?'ČEKÁM NA PAYOUT':'PRODEJE V KLIDU'}</b><small>${m.urgent?`${m.urgent} prodejů má termín do 72 h.`:'Hlídám předání i následnou výplatu.'}</small></div><div><span>DORUČIT</span><b>${m.delivery.length}</b><small>${m.urgent?'urgentní '+m.urgent:'bez urgence'}</small></div><div><span>ČEKÁ PAYOUT</span><b>${m.waiting.length}</b><small>${fmt(m.pending)}</small></div><div><span>VYPLACENO</span><b>${m.paid.length}</b><small>uzavřené prodeje</small></div></div>${focus.length?`<div class="sg408-list">${focus.map(r=>{const hh=hoursTo(r.delivery_due_at),urgent=String(r.market_status)==='SOLD_UNDELIVERED'&&hh!==null&&hh<=72;return`<div class="sg408-row ${urgent?'urgent':''}"><div><strong>${esc(r.event_name)}</strong><small>${esc(r.section||'bez sektoru')} · ${N(r.qty)||1} ks · objednávka ${esc(r.marketplace_order_id||'—')}</small></div><div><span>STAV</span><b>${String(r.market_status)==='SOLD_UNDELIVERED'?'DORUČIT':'PAYOUT'}</b></div><div><span>TERMÍN</span><b>${String(r.market_status)==='SOLD_UNDELIVERED'?when(r.delivery_due_at):'—'}</b></div><div><span>PRODEJ</span><b>${fmt(r.sell_total_czk)}</b></div></div>`}).join('')}</div>`:''}`}
window.__KAMIL_TICKET_SOLD_GUARD408__={version:VERSION,healthy:true,model:m,at:Date.now()};document.documentElement.dataset.ticketSoldGuard408='1'}finally{busy=false}}
function schedule(ms=180){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketSoldGuard408(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-sale408-saved'])window.addEventListener(ev,()=>schedule());new MutationObserver(()=>schedule(260)).observe(document.body,{childList:true,subtree:true});schedule();setTimeout(()=>schedule(),1200)}
