import {cloudClient,session} from './cloud.js';

const VERSION=460;let bound=false,timer=0,busy=false;
const buckets=['UDĚLEJ TEĎ','UDĚLEJ DNES','SLEDUJ'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=(id,code)=>`${String(id)}|${String(code||'')}`;
async function ctx(){const c=await cloudClient(),s=await session();if(!c||!s)throw new Error('Cloud session chybí.');return{c,s}}
function commander(){const c=window.__KAMIL_TICKET_COMMANDER465__;if(!c?.rows?.length)return null;return c.rows.filter(x=>x.id&&buckets.includes(x.bucket)).map((x,i)=>({id:String(x.id),title:x.title||String(x.id),code:x.what||'—',bucket:x.bucket||'SLEDUJ',score:Number(x.score||0),price:Number(x.price||0)||null,reason:x.why||'',rank:i+1})).sort((a,b)=>b.score-a.score)}
function latest(rows){const m=new Map();for(const r of rows||[]){const k=key(r.ticket_id,r.recommendation_code);if(!m.has(k))m.set(k,r)}return m}
function statusLabel(s){return s==='CONFIRMED'?'POTVRZENO':s==='DONE'?'HOTOVO':s==='IGNORED'?'IGNOROVÁNO':'NOVÉ'}
function tone(b){return b==='UDĚLEJ TEĎ'?'now':b==='UDĚLEJ DNES'?'today':'watch'}
function ensureCss(){if(document.querySelector('style[data-inbox460]'))return;const s=document.createElement('style');s.dataset.inbox460='1';s.textContent=`#ticketIntelView .inbox460{margin:0 0 7px;border:1px solid #29495c;border-radius:10px;background:#081923;color:#dce9f2;overflow:hidden}.inbox460-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:8px 10px}.inbox460-head span,.inbox460 span{font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#7898ad}.inbox460-head b{font-size:11px}.inbox460-toggle{border:1px solid #35576d;border-radius:7px;background:#102735;color:#cfe1ec;padding:5px 8px;font-size:8px;font-weight:900;cursor:pointer}.inbox460-list{display:none;border-top:1px solid #203744}.inbox460.open .inbox460-list{display:block}.inbox460-row{display:grid;grid-template-columns:42px minmax(180px,1.4fr) minmax(100px,.8fr) auto;gap:8px;align-items:center;padding:7px 10px;border-top:1px solid #172d39}.inbox460-row:first-child{border-top:0}.inbox460-rank{font-size:10px;font-weight:900;color:#8fa9bb}.inbox460-title{min-width:0}.inbox460-title b{display:block;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.inbox460-title small{display:block;margin-top:2px;font-size:8px;color:#718798;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.inbox460-code b{font-size:9px}.inbox460-actions{display:flex;gap:4px;flex-wrap:wrap;justify-content:flex-end}.inbox460-btn{border:1px solid #304d60;border-radius:6px;background:#0f2431;color:#bcd1df;padding:4px 6px;font-size:7.5px;font-weight:900;cursor:pointer}.inbox460-btn:disabled{opacity:.45}.inbox460-status{display:inline-flex;padding:3px 6px;border-radius:999px;border:1px solid #304d60;font-size:7px;font-weight:900}.inbox460-now{color:#ff9aa5}.inbox460-today{color:#efc17c}.inbox460-watch{color:#9fc9e4}@media(max-width:800px){.inbox460-row{grid-template-columns:32px 1fr}.inbox460-code,.inbox460-actions{grid-column:2}.inbox460-actions{justify-content:flex-start}}`;document.head.appendChild(s)}
function jump(id){const escId=globalThis.CSS?.escape?CSS.escape(String(id)):String(id).replace(/["\\]/g,'\\$&'),d=document.querySelector(`#ticketIntelView [data-ticket-detail="${escId}"]`),card=d?.closest('[data-inventory-card]');if(card){card.dataset.focus459Hidden='0';card.scrollIntoView({behavior:'smooth',block:'center'})}}
async function save(a,status,current,btn){if(busy)return;busy=true;btn.disabled=true;try{const {c,s}=await ctx(),now=new Date().toISOString(),payload={user_id:s.user.id,ticket_id:a.id,recommendation_code:a.code,recommendation_reason:a.reason||null,recommended_price_czk:a.price,financial_impact_czk:null,action_status:status,acted_at:now,model_version:'466-inbox'};let error;if(current?.id)({error}=await c.from('ticket_action_executions').update(payload).eq('id',current.id).eq('user_id',s.user.id));else({error}=await c.from('ticket_action_executions').insert(payload));if(error)throw error;window.dispatchEvent(new CustomEvent('kamil:ticket-action449-saved',{detail:{ticketId:a.id,code:a.code,status,source:'inbox460'}}));schedule(120)}catch(e){console.error('[ticket460] action save failed',e)}finally{busy=false;btn.disabled=false}}
function paint(actions,states){ensureCss();const host=document.querySelector('#ticketIntelView .td331');if(!host)return;let box=host.querySelector('[data-inbox460]');if(!box){box=document.createElement('section');box.dataset.inbox460='1';box.className='inbox460';const focus=host.querySelector('[data-focus459]');focus?.insertAdjacentElement('beforebegin',box);if(!box.isConnected)host.querySelector('.td331-overview')?.insertAdjacentElement('afterend',box)}const open=box.classList.contains('open'),counts=Object.fromEntries(buckets.map(b=>[b,actions.filter(x=>x.bucket===b).length]));box.innerHTML=`<div class="inbox460-head"><div><span>ACTION INBOX</span><b>${counts['UDĚLEJ TEĎ']||0} teď · ${counts['UDĚLEJ DNES']||0} dnes · ${counts.SLEDUJ||0} sledovat</b></div><button type="button" class="inbox460-toggle" data-inbox460-toggle>${open?'Skrýt':'Otevřít'}</button></div><div class="inbox460-list">${actions.slice(0,12).map((a,i)=>{const st=states.get(key(a.id,a.code)),status=st?.action_status||'RECOMMENDED';return `<div class="inbox460-row" data-inbox460-id="${esc(a.id)}"><div class="inbox460-rank">#${i+1}</div><div class="inbox460-title"><b>${esc(a.title)}</b><small>${esc(a.bucket)} · ${esc(a.reason||'bez dalšího komentáře')}</small></div><div class="inbox460-code"><span class="inbox460-${tone(a.bucket)}">${esc(a.code)}</span><b>${a.price?`${Math.round(a.price).toLocaleString('cs-CZ')} Kč`:'—'}</b></div><div class="inbox460-actions"><span class="inbox460-status">${statusLabel(status)}</span><button class="inbox460-btn" data-act="JUMP">Karta</button><button class="inbox460-btn" data-act="CONFIRMED" ${status==='DONE'?'disabled':''}>Potvrdit</button><button class="inbox460-btn" data-act="DONE">Hotovo</button><button class="inbox460-btn" data-act="IGNORED" ${status==='DONE'?'disabled':''}>Ignorovat</button></div></div>`}).join('')||'<div class="inbox460-row"><div></div><div class="inbox460-title"><b>Nic k řešení</b><small>Commander nemá aktivní pracovní akce.</small></div></div>'}</div>`;if(open)box.classList.add('open');box.querySelector('[data-inbox460-toggle]')?.addEventListener('click',()=>{box.classList.toggle('open');schedule(0)});for(const row of box.querySelectorAll('[data-inbox460-id]')){const a=actions.find(x=>x.id===row.dataset.inbox460Id);if(!a)continue;const st=states.get(key(a.id,a.code));for(const btn of row.querySelectorAll('[data-act]'))btn.addEventListener('click',()=>btn.dataset.act==='JUMP'?jump(a.id):save(a,btn.dataset.act,st,btn))}window.__KAMIL_TICKET_INBOX460__={version:VERSION,healthy:true,source:'commander465',count:actions.length,counts,at:Date.now()};document.documentElement.dataset.ticketInbox460='1'}
async function refresh(){if(busy)return;const actions=commander();if(!actions)return;busy=true;try{const {c,s}=await ctx();const {data,error}=await c.from('ticket_action_executions').select('id,ticket_id,recommendation_code,action_status,created_at,acted_at').eq('user_id',s.user.id).order('created_at',{ascending:false}).limit(300);if(error)throw error;paint(actions,latest(data||[]))}catch(e){window.__KAMIL_TICKET_INBOX460__={version:VERSION,healthy:false,error:String(e?.message||e),at:Date.now()}}finally{busy=false}}
function schedule(ms=140){clearTimeout(timer);timer=setTimeout(refresh,ms)}
export function installTicketActionInbox460(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-commander465-updated','kamil:ticket-focus459-updated','kamil:ticket-action449-saved'])window.addEventListener(ev,()=>schedule());schedule(1800)}
