import {loadTicketCloud660} from './ticketCloud660.js';
const VERSION=435,N=v=>Number(v||0);let bound=false,timer=0,busy=false;
const fmt=v=>Number.isFinite(Number(v))?`${Math.round(Number(v)).toLocaleString('cs-CZ')} Kč`:'—';
const pct=v=>Number.isFinite(Number(v))?`${v>=0?'+':''}${Number(v).toFixed(1)} %`:'—';
const eventKey=s=>String(s||'').split(' - ')[0].trim().toLowerCase();
function hold48(m,cal){const p=m.predict,market=N(m.market),mom=((N(m.momentum?.d7)||0)/7)*2,future=market*(1+mom/100),bias=N(cal?.pricingBias)||1,price=Math.round(future*bias/10)*10,q=Math.max(1,N(m.r?.qty)||1),buy=N(m.r?.buy_total_czk)||N(m.r?.buy_each_czk)*q,fee=N(m.fee?.rate)||.15,prob=Math.min(.98,(p?.p72||0)*(N(cal?.probabilityScale)||1)*.82),profit=price*q*(1-fee)-buy,ev=prob*profit;return{price,prob,profit,ev}}
function currentAction(m,cal){const p=m.predict,opt=p.opt,ask=N(m.r.ask_each_czk),hold=hold48(m,cal),now=opt.ev,delta=now-hold.ev,cut=ask&&opt.price?((1-opt.price/ask)*100):0;let code='DRŽET 48 H',reason=`Modelovaný EV držení ${fmt(hold.ev)} vs. exit ${fmt(now)}.`;if(m.pressure>=75||m.days!==null&&m.days<=3){code='PRODAT / ZLEVNIT TEĎ';reason=`Sell pressure ${m.pressure}; optimal exit ${fmt(opt.price)}.`}else if(delta>250){code=cut>1?'ZLEVNIT TEĎ':'PRODAT TEĎ';reason=`Exit má o ${fmt(delta)} vyšší EV než držení 48 h.`}else if(delta<-250){code='DRŽET 48 H';reason=`Držení má o ${fmt(-delta)} vyšší modelovaný EV.`}else if(p.opportunityCost){code='UVOLNIT KAPITÁL';reason=`Kapitál je zamčený ${Math.round(p.heldDays)} dní a efektivita je nízká.`}return{code,reason,exitEv:now,holdEv:hold.ev,delta,cut,optPrice:opt.price,holdPrice:hold.price}}
function exposure(models){const total=models.reduce((a,m)=>a+(N(m.r.buy_total_czk)||0),0),map=new Map();for(const m of models){const k=eventKey(m.r.event_name),v=map.get(k)||{name:m.r.event_name,capital:0};v.capital+=N(m.r.buy_total_czk)||0;map.set(k,v)}return{total,map}}
function budget(m,exp){const key=eventKey(m.r.event_name),current=exp.map.get(key)?.capital||0,total=exp.total;if(!total)return{max:0,reason:'Bez aktivního kapitálu pro kalibraci.'};const concentration=current/total,room=Math.max(0,(.30*total-current)/.70),quality=(N(m.predict?.demand)/100)*(Math.max(0,N(m.predict?.riskAdjustedRoi))/20),cap=Math.min(12000,room,Math.max(0,total*.12*quality));if(concentration>=.30)return{max:0,reason:`Event už tvoří ${(concentration*100).toFixed(1)} % aktivního kapitálu.`};if(N(m.predict?.opt?.ev)<=0||N(m.predict?.riskAdjustedRoi)<=0)return{max:0,reason:'EV nebo risk-adjusted ROI není kladné.'};return{max:Math.round(cap/100)*100,reason:`Limit 30 % eventu · demand ${m.predict.demand}/100 · risk ROI ${pct(m.predict.riskAdjustedRoi)}.`}}
function rotation(cloud){const sold=(cloud.inventory||[]).filter(r=>['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID'].includes(String(r.market_status||''))),days=sold.map(r=>{const a=Date.parse(r.imported_at||r.created_at||''),b=Date.parse(r.sold_at||r.updated_at||'');return Number.isFinite(a)&&Number.isFinite(b)&&b>a?(b-a)/864e5:null}).filter(Number.isFinite).sort((a,b)=>a-b),med=days.length?days[Math.floor(days.length/2)]:30;return{sample:days.length,medianDays:med,turns:365/Math.max(1,med)}}
function model(pred,cal,cloud){const exp=exposure(pred.models),rows=pred.models.map(m=>({...m,commander:currentAction(m,cal),buyBudget:budget(m,exp)})),rot=rotation(cloud);rows.sort((a,b)=>{const score=x=>(x.commander.code.includes('PRODAT')?100:x.commander.code.includes('ZLEVNIT')?90:x.commander.code.includes('UVOLNIT')?80:40)+N(x.pressure)+Math.max(0,N(x.commander.delta))/100;return score(b)-score(a)});return{rows,rotation:rot,exposure:exp}}
function ensureCss(){if(document.querySelector('style[data-cmd435]'))return;const s=document.createElement('style');s.dataset.cmd435='1';s.textContent=`#ticketIntelView .cmd435{margin:0 0 12px;border:1px solid #31566f;border-radius:13px;background:#091720;color:#dceaf4;overflow:hidden}.cmd435-head{display:grid;grid-template-columns:1.4fr repeat(4,1fr);gap:8px;padding:11px 12px}.cmd435 span{display:block;font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#789ab3}.cmd435 b{display:block;margin-top:3px;font-size:13px}.cmd435 small{display:block;margin-top:2px;color:#7b91a3;font-size:9px}.cmd435-list{border-top:1px solid #203746}.cmd435-row{display:grid;grid-template-columns:1.3fr 1fr .8fr .8fr .9fr;gap:8px;padding:9px 12px;border-top:1px solid #172c38}.cmd435-row strong{font-size:10px}.cmd435-sell{color:#ff9aa5}.cmd435-good{color:#8bd8ad}.cmd435-warn{color:#efc17c}@media(max-width:900px){.cmd435-head,.cmd435-row{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function panel(m){const host=document.querySelector('#ticketIntelView .td331');if(!host)return;let box=host.querySelector('[data-cmd435]');if(!box){box=document.createElement('section');box.dataset.cmd435='1';box.className='cmd435';const bt=host.querySelector('[data-bt434]');bt?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.querySelector('.td331-hero')?.insertAdjacentElement('afterend',box)}const top=m.rows.slice(0,8),opp=m.rows.filter(x=>x.predict.opportunityCost).length,buyable=m.rows.filter(x=>x.buyBudget.max>0).length;box.innerHTML=`<div class="cmd435-head"><div><span>COMMANDER 3.0 · OS435</span><b>Optimalizace EV × času × kapitálu</b><small>Rozhoduje mezi exitem, zlevněním, 48h držením a uvolněním kapitálu. Nákupní limit je pouze doporučení; nic se automaticky nenakupuje.</small></div><div><span>ROTACE / ROK</span><b>${m.rotation.turns.toFixed(1)}×</b><small>median ${Math.round(m.rotation.medianDays)} dní · n=${m.rotation.sample}</small></div><div><span>OPPORTUNITY COST</span><b>${opp}</b></div><div><span>BUY BUDGET > 0</span><b>${buyable}</b></div><div><span>AKTIVNÍ KAPITÁL</span><b>${fmt(m.exposure.total)}</b></div></div><div class="cmd435-list">${top.map(x=>`<div class="cmd435-row"><div><span>${x.commander.code}</span><strong class="${/PRODAT|ZLEVNIT|UVOLNIT/.test(x.commander.code)?'cmd435-sell':'cmd435-good'}">${x.r.event_name}</strong><small>${x.commander.reason}</small></div><div><span>OPT EXIT</span><b>${fmt(x.commander.optPrice)}</b><small>${x.commander.cut>0?`změna ${pct(-x.commander.cut)}`:'bez nutné slevy'}</small></div><div><span>EXIT EV</span><b>${fmt(x.commander.exitEv)}</b></div><div><span>HOLD 48H EV</span><b>${fmt(x.commander.holdEv)}</b></div><div><span>MAX NOVÝ NÁKUP</span><b class="${x.buyBudget.max>0?'cmd435-good':'cmd435-warn'}">${fmt(x.buyBudget.max)}</b><small>${x.buyBudget.reason}</small></div></div>`).join('')}</div>`}
async function refresh(){if(busy)return;const pred=window.__KAMIL_TICKET_PREDICT433__,bt=window.__KAMIL_TICKET_BACKTEST434__;if(!pred?.models?.length)return;busy=true;try{ensureCss();const cloud=await loadTicketCloud660();if(!cloud?.ok)return;const m=model(pred,bt?.calibration||{},cloud);window.__KAMIL_TICKET_COMMANDER435__={version:VERSION,healthy:true,...m,at:Date.now()};document.documentElement.dataset.ticketCommander435='1';panel(m);window.dispatchEvent(new CustomEvent('kamil:ticket-commander435-updated',{detail:{count:m.rows.length}}))}finally{busy=false}}
function schedule(ms=850){clearTimeout(timer);timer=setTimeout(refresh,ms)}
export function installTicketCommander435(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-predict433-updated','kamil:ticket-backtest434-updated'])window.addEventListener(ev,()=>schedule());schedule(4200);setInterval(()=>schedule(0),30000)}
