const VERSION=455;let bound=false,timer=0;
const now=()=>Date.now(),age=s=>s?.at?Math.max(0,(now()-Number(s.at))/1000):null;
const modules=[
  ['ENGINE 426','__KAMIL_TICKET_ENGINE426__',90],['UI 427','__KAMIL_TICKET_ENGINE_UI427__',90],['PORTFOLIO 428','__KAMIL_TICKET_PORTFOLIO428__',90],
  ['QUALITY 444','__KAMIL_TICKET_QUALITY444__',120],['CONSENSUS 445','__KAMIL_TICKET_CONSENSUS445__',120],['RISK OPS 446','__KAMIL_TICKET_RISKOPS446__',120],
  ['OPTIMIZER 447','__KAMIL_TICKET_OPTIMIZER447__',120],['GOVERNANCE 451','__KAMIL_TICKET_GOVERNANCE451__',120],['REGIME 452','__KAMIL_TICKET_REGIME452__',120],
  ['CAPITAL 453','__KAMIL_TICKET_CAPITAL453__',120],['COMMANDER 454','__KAMIL_TICKET_COMMANDER454__',120]
];
function inspect(){const rows=modules.map(([label,key,max])=>{const s=window[key],a=age(s);let state='WAIT';if(s){if(s.healthy===false)state='ERROR';else if(a!==null&&a>max)state='STALE';else state='OK'}return{label,key,state,age:a,max,error:s?.error||null}});const engine=window.__KAMIL_TICKET_ENGINE426__,ui=window.__KAMIL_TICKET_ENGINE_UI427__,models=engine?.models?.length||0,painted=Number(ui?.painted||0),paintErrors=ui?.errors||[],coverage=models?Math.round(painted/models*100):0;const hard=rows.filter(x=>x.state==='ERROR').length+paintErrors.length,stale=rows.filter(x=>x.state==='STALE').length,waiting=rows.filter(x=>x.state==='WAIT').length;const status=hard?'ERROR':stale?'STALE':waiting?'STARTING':coverage<100&&models?'PARTIAL':'OK';return{rows,status,hard,stale,waiting,models,painted,coverage,paintErrors}}
function ensureCss(){if(document.querySelector('style[data-rh455]'))return;const s=document.createElement('style');s.dataset.rh455='1';s.textContent=`#ticketIntelView .rh455{margin:0 0 10px;border:1px solid #2c4758;border-radius:10px;background:#091821;color:#dceaf2;overflow:hidden}.rh455-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:8px 10px;cursor:pointer}.rh455-title{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.rh455 span{font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#7898ad}.rh455 b{font-size:10px}.rh455-ok{color:#8bd8ad}.rh455-warn{color:#efc17c}.rh455-bad{color:#ff9aa5}.rh455-body{display:none;border-top:1px solid #203744;padding:8px 10px}.rh455.open .rh455-body{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.rh455-row{padding:6px 7px;border:1px solid #203744;border-radius:7px;background:#0c1d27}.rh455-row small{display:block;margin-top:2px;color:#71889a;font-size:8px}.rh455-btn{border:1px solid #35566b;border-radius:7px;background:#102735;color:#cce0ec;padding:5px 8px;font-size:8px;font-weight:900;cursor:pointer}@media(max-width:800px){.rh455.open .rh455-body{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function retry(){window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:{view:'tickets',source:'health455'}}));window.dispatchEvent(new CustomEvent('kamil:ticket-refresh397-done',{detail:{source:'health455'}}));setTimeout(()=>paint(),900)}
function paint(){ensureCss();const host=document.querySelector('#ticketIntelView .td331');if(!host)return;const m=inspect();let box=document.querySelector('#ticketIntelView [data-runtime455]');if(!box){box=document.createElement('section');box.dataset.runtime455='1';box.className='rh455';const cmd=document.querySelector('#ticketIntelView [data-c454]');cmd?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.prepend(box)}const open=box.classList.contains('open'),tone=m.status==='OK'?'ok':m.status==='ERROR'?'bad':'warn';box.innerHTML=`<div class="rh455-head"><div class="rh455-title"><span>RUNTIME HEALTH · OS455</span><b class="rh455-${tone}">${m.status}</b><span>cards ${m.painted}/${m.models}</span><span>coverage ${m.coverage}%</span><span>stale ${m.stale}</span><span>errors ${m.hard}</span></div><button class="rh455-btn" data-rh455-retry>Obnovit řetězec</button></div><div class="rh455-body">${m.rows.map(x=>`<div class="rh455-row"><span>${x.label}</span><b class="rh455-${x.state==='OK'?'ok':x.state==='ERROR'?'bad':'warn'}">${x.state}</b><small>${x.age===null?'čeká na první běh':`${Math.round(x.age)} s`}${x.error?` · ${String(x.error).slice(0,80)}`:''}</small></div>`).join('')}${m.paintErrors.map(x=>`<div class="rh455-row"><span>CARD ${x.id}</span><b class="rh455-bad">PAINT ERROR</b><small>${String(x.error).slice(0,100)}</small></div>`).join('')}</div>`;if(open)box.classList.add('open');box.querySelector('.rh455-head')?.addEventListener('click',e=>{if(e.target.closest('[data-rh455-retry]'))return;box.classList.toggle('open')});box.querySelector('[data-rh455-retry]')?.addEventListener('click',retry);window.__KAMIL_TICKET_RUNTIME455__={version:VERSION,healthy:m.status==='OK',...m,at:now()};document.documentElement.dataset.ticketRuntime455=m.status.toLowerCase()}
function schedule(ms=120){clearTimeout(timer);timer=setTimeout(paint,ms)}
export function installTicketRuntimeHealth455(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-engine426-updated','kamil:ticket-engine427-updated','kamil:ticket-portfolio428-updated','kamil:ticket-quality444-updated','kamil:ticket-governance451-updated','kamil:ticket-regime452-updated','kamil:ticket-capital453-updated','kamil:ticket-commander454-updated'])window.addEventListener(ev,()=>schedule());schedule(14500);setInterval(()=>schedule(0),60000)}