import {store} from './state.js';
import {ticketDecision,ticketOpportunityDecision,ticketIntelligenceAge} from './live24.js';

const VERSION=369;
const N=v=>Number(v||0),U=v=>String(v||'').toUpperCase(),A=v=>Array.isArray(v)?v:[],clamp=v=>Math.max(0,Math.min(100,N(v)));
const LABEL={BUY:'KOUPIT',HOLD:'DRŽET',SELL:'PRODAT',LOWER:'SLEVIT',SKIP:'NEBRAT'};
const ACTIVE=new Set(['HOLD','LISTED','ACTIVE','']);
function freshness(s){const intel=ticketIntelligenceAge(s);return{intelligence:intel,stale:!!intel.stale,label:`Analýza ${intel.label}`}}
function confidence(d,f){let c=d?.confidence===null||d?.confidence===undefined?Math.max(35,Math.min(80,N(d?.priority)||50)):clamp(d.confidence);if(f.stale)c=Math.min(c,55);if(d?.liveTrust&&d.liveTrust!=='TRUSTED_FRESH')c=Math.min(c,50);return Math.round(c)}
function holdingVerdict(action){action=U(action);if(action==='SELL')return'SELL';if(action==='REPRICE')return'LOWER';return'HOLD'}
function opportunityVerdict(action){action=U(action);return action==='BUY'?'BUY':'SKIP'}
function perTicketBuy(x){const q=Math.max(1,N(x?.qty||x?.quantity||1));return N(x?.buy_each_czk||x?.buyEachCzk||x?.buyPriceCzk)||(N(x?.buy)/q)}
function riskFlags(x,d,f,type){const out=[];if(f.stale)out.push('STALE_DATA');if(d?.liveCandidate&&!d?.live)out.push('UNTRUSTED_LIVE_SIGNAL');if(type==='OPPORTUNITY'&&x?.resaleAllowed!==true)out.push('RESALE_UNVERIFIED');if(type==='OPPORTUNITY'&&x?.transferCompatible!==true)out.push('TRANSFER_UNVERIFIED');if(U(d?.action)==='REVIEW')out.push('REVIEW_REQUIRED');return out}
function holdingRow(x,f,s){const d=ticketDecision(x,s),verdict=holdingVerdict(d.action),q=Math.max(1,N(x.qty||1)),market=N(d.recommendedListPricePerTicket||d.marketPricePerTicket||x.marketPrice||x.listPrice),buy=perTicketBuy(x),fee=N(x.feeRate||.12),net=market?market*(1-fee):0,roi=buy&&net?Math.round(((net-buy)/buy)*1000)/10:null;return{id:x.id||x.eventId,type:'HOLDING',name:x.name||x.event||'Vstupenka',verdict,label:LABEL[verdict],confidence:confidence(d,f),priority:clamp(d.priority),reason:[d.reason,d.when].filter(Boolean).join(' · '),riskFlags:riskFlags(x,d,f,'HOLDING'),qty:q,marketPrice:market||null,buyPrice:buy||null,roiAfterFee:roi,dataFresh:!f.stale,source:d.source||'AUTO'}}
function opportunityRow(x,f,s){const d=ticketOpportunityDecision(x,s),verdict=opportunityVerdict(d.action),safe=N(d.netSafeMaxBuyPrice||d.maxBuyPrice||x.netSafeMaxBuyPrice||x.maxBuyPrice)||null;return{id:x.id||x.eventId,type:'OPPORTUNITY',name:x.name||x.event||'Příležitost',verdict,label:LABEL[verdict],confidence:confidence(d,f),priority:clamp(d.priority),reason:[d.reason,d.when].filter(Boolean).join(' · '),riskFlags:riskFlags(x,d,f,'OPPORTUNITY'),maxBuyPrice:safe,dataFresh:!f.stale,source:d.source||'AUTO'}}
export function ticketDecision369(s=store.get()){const f=freshness(s),items=A(s.ticketBook?.items||s.ticket_inventory),holdings=items.filter(x=>ACTIVE.has(U(x.workflow||x.status))).map(x=>holdingRow(x,f,s)),ops=A(s.ticketBook?.opportunities||s.ticketOpportunities||s.ticket_market_opportunities).map(x=>opportunityRow(x,f,s)),rows=[...holdings,...ops].sort((a,b)=>b.priority-a.priority),counts={BUY:0,HOLD:0,SELL:0,LOWER:0,SKIP:0};rows.forEach(x=>counts[x.verdict]++);const top=rows.find(x=>x.verdict!=='HOLD'&&x.verdict!=='SKIP')||rows[0]||null;return{version:VERSION,healthy:true,rows,holdings,opportunities:ops,counts,top,freshness:f,generatedAt:new Date().toISOString()}}
function publish(){try{const model=ticketDecision369();window.__KAMIL_TICKET_DECISION369__={version:VERSION,healthy:true,model,refresh:publish,at:Date.now()};document.documentElement.dataset.ticketDecision369='1';window.dispatchEvent(new CustomEvent('kamil:ticket-decision369-updated',{detail:{count:model.rows.length,actionable:model.rows.filter(x=>!['HOLD','SKIP'].includes(x.verdict)).length}}));return model}catch(error){console.error('[ticketDecision369]',error);window.__KAMIL_TICKET_DECISION369__={version:VERSION,healthy:false,error:String(error?.message||error),refresh:publish,at:Date.now()};return null}}
let bound=false,timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(publish,80)};
export function installTicketDecision369(){if(!bound){bound=true;store.subscribe?.(schedule);window.addEventListener('focus',schedule);window.addEventListener('kamil:view-change',schedule)}schedule();setTimeout(schedule,900)}
