const VERSION=419,N=v=>Number(v||0);let bound=false,timer=0,busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>`${Math.round(N(v)).toLocaleString('cs-CZ')} Kč`;
const parse=iso=>{const t=Date.parse(iso||'');return Number.isFinite(t)?t:null};
const hours=iso=>{const t=parse(iso);return t===null?null:(t-Date.now())/36e5};
function card(id){return document.querySelector(`#ticketIntelView [data-ta407="${CSS.escape(String(id))}"]`)||document.querySelector(`#ticketIntelView [data-ticket-detail="${CSS.escape(String(id))}"]`)?.closest('article')}
function jump(id){const x=card(id);x?.scrollIntoView({behavior:'smooth',block:'center'});if(x){x.animate?.([{outline:'2px solid rgba(255,255,255,.55)'},{outline:'2px solid transparent'}],{duration:1300})}}
function actionModels(){return window.__KAMIL_TICKET_AUTOPILOT407__?.models||[]}
function priorities(){const out=[],sett=window.__KAMIL_TICKET_SETTLEMENT411__?.model,repair=window.__KAMIL_TICKET_REPAIR418__?.model,cap=window.__KAMIL_TICKET_CAPITAL415__?.model;
 for(const x of sett?.undelivered||[]){const r=x.r,h=hours(r.delivery_due_at),urgent=h===null?70:h<0?120:h<=24?115:h<=72?105:85;out.push({kind:'delivery',score:urgent,id:r.id,title:'Doručit prodané vstupenky',name:r.event_name,detail:`${r.marketplace_order_id?`Order ${r.marketplace_order_id} · `:''}${h===null?'termín není uložen':h<0?'TERMÍN PROŠEL':h<=24?'do 24 hodin':h<=72?'do 72 hodin':'čeká na předání'}`,cta:'Přejít na prodej'})}
 for(const x of sett?.waiting||[]){const r=x.r,h=hours(r.payout_expected_at);if(h!==null&&h<0)out.push({kind:'payout',score:92,id:r.id,title:'Zkontrolovat opožděný payout',name:r.event_name,detail:`${r.marketplace_order_id?`Order ${r.marketplace_order_id} · `:''}${Math.ceil(Math.abs(h)/24)} dní po očekávaném termínu`,cta:'Přejít na payout'})}
 for(const x of (repair?.rows||[]).slice(0,5)){out.push({kind:'repair',score:60+N(x.score),id:x.r.id,title:'Opravit market data',name:x.r.event_name,detail:`${x.issues.join(' · ')} · v pozici ${fmt(x.capital)}`,cta:'Opravit data'})}
 for(const m of actionModels()){const code=String(m.a?.code||''),p=N(m.a?.price);if(!['PRODAT DNES','ZLEVNIT','ZDRAŽIT','VYSTAVIT'].includes(code)||!p)continue;const base=code==='PRODAT DNES'?108:code==='ZLEVNIT'?94:code==='VYSTAVIT'?78:68;out.push({kind:'price',score:base+(m.d!=null&&m.d<=7?12:0),id:m.r.id,title:code,name:m.r.event_name,detail:`Cíl ${fmt(p)} / ks · ${m.d==null?'datum ?':`${m.d} dní do akce`} · ${m.a.why||''}`,cta:'Přejít na cenu',price:p})}
 if(cap?.top&&cap.top.share>=30)out.push({kind:'capital',score:cap.top.share>=35?96:82,id:null,title:cap.top.share>=35?'Redukovat koncentraci':'Nepřikupovat do akce',name:cap.top.name,detail:`${cap.top.share.toFixed(1)} % aktivního kapitálu · ${fmt(cap.top.capital)}. Limit je 30 %.`,cta:'Zobrazit Capital Allocator'});
 const dedup=new Map();for(const x of out){const k=`${x.kind}|${x.id||x.name}`;if(!dedup.has(k)||dedup.get(k).score<x.score)dedup.set(k,x)}return[...dedup.values()].sort((a,b)=>b.score-a.score).slice(0,5)}
function ensureCss(){if(document.querySelector('style[data-db419]'))return;const s=document.createElement('style');s.dataset.db419='1';s.textContent=`#ticketIntelView .db419{margin:0 0 14px;border:1px solid #3a5c72;border-radius:14px;background:#0a1620;color:#e0edf6;overflow:hidden}.db419-head{display:grid;grid-template-columns:1.6fr repeat(3,1fr);gap:8px;padding:12px}.db419 span{display:block;font-size:8px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;color:#7fa2bc}.db419 b{display:block;margin-top:3px;font-size:14px}.db419 small{display:block;margin-top:2px;color:#849aaa;font-size:9px}.db419-list{border-top:1px solid #203847}.db419-row{display:grid;grid-template-columns:42px 1.5fr 1fr auto;gap:10px;align-items:center;padding:10px 12px;border-top:1px solid #172c38}.db419-row:first-child{border-top:0}.db419-num{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#173246;border:1px solid #3a5f77;font-weight:900;font-size:11px}.db419-row strong{display:block;font-size:11px}.db419-row em{font-style:normal;font-size:9px;color:#90a8b8}.db419-kind{font-size:9px;font-weight:900}.db419-kind.delivery,.db419-kind.payout{color:#f0aa9d}.db419-kind.price{color:#9fd6b8}.db419-kind.repair{color:#efcb88}.db419-kind.capital{color:#e4a8a8}.db419-btn{border:1px solid #3a5e74;background:#132b3a;color:#c9e1ef;border-radius:999px;padding:6px 10px;font-size:9px;font-weight:900;cursor:pointer}.db419-clear{color:#8fd4ad}@media(max-width:850px){.db419-head{grid-template-columns:1fr 1fr}.db419-row{grid-template-columns:32px 1fr}.db419-row>:nth-child(3),.db419-row>:nth-child(4){grid-column:2}}`;document.head.appendChild(s)}
function metrics(list){const price=list.filter(x=>x.kind==='price').length,repair=list.filter(x=>x.kind==='repair').length,ops=list.filter(x=>['delivery','payout'].includes(x.kind)).length;return{price,repair,ops}}
function doAction(x){if(x.kind==='repair'){const b=document.querySelector(`#ticketIntelView [data-fix418="${CSS.escape(String(x.id))}"]`);if(b){b.click();return}}if(x.kind==='capital'){document.querySelector('#ticketIntelView [data-capital415]')?.scrollIntoView({behavior:'smooth',block:'center'});return}if(x.id)jump(x.id)}
function render(){if(busy)return;const host=document.querySelector('#ticketIntelView .td331');if(!host)return;busy=true;try{ensureCss();const list=priorities(),m=metrics(list);let box=host.querySelector('[data-daily-brief419]');if(!box){box=document.createElement('section');box.dataset.dailyBrief419='1';box.className='db419';const hero=host.querySelector('.td331-hero');hero?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.prepend(box)}const sig=list.map(x=>[x.kind,x.id,x.score,x.title,x.detail,x.price].join(':')).join('|');if(box.dataset.sig!==sig){box.dataset.sig=sig;box.innerHTML=`<div class="db419-head"><div><span>DNES UDĚLEJ · OS419</span><b class="${list.length?'':'db419-clear'}">${list.length?`${list.length} priorit`:'NIC URGENTNÍHO'}</b><small>${list.length?'Jedna fronta pro cenu, market data, doručení, payout i koncentraci.':'Ticket portfolio teď nevyžaduje zásah.'}</small></div><div><span>CENOVÉ AKCE</span><b>${m.price}</b><small>prodat / zlevnit / vystavit</small></div><div><span>DATA</span><b>${m.repair}</b><small>zdroj, cena, pár, confidence</small></div><div><span>PROVOZ</span><b>${m.ops}</b><small>doručení a payout</small></div></div>${list.length?`<div class="db419-list">${list.map((x,i)=>`<div class="db419-row"><div class="db419-num">${i+1}</div><div><span class="db419-kind ${x.kind}">${esc(x.title)}</span><strong>${esc(x.name)}</strong><em>${esc(x.detail)}</em></div><div><span>PRIORITA</span><b>${Math.round(x.score)}</b></div><button class="db419-btn" data-db419="${i}">${esc(x.cta)}</button></div>`).join('')}</div>`:''}`;box.querySelectorAll('[data-db419]').forEach(b=>b.addEventListener('click',()=>doAction(list[N(b.dataset.db419)])))}window.__KAMIL_TICKET_DAILY_BRIEF419__={version:VERSION,healthy:true,items:list,at:Date.now()};document.documentElement.dataset.ticketDailyBrief419='1'}finally{busy=false}}
function schedule(ms=300){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketDailyBrief419(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-refresh397-done','kamil:ticket-repair418-done','kamil:ticket-sale408-saved','kamil:ticket-settlement411-saved','kamil:ticket-target410-saved'])window.addEventListener(ev,()=>schedule());new MutationObserver(()=>schedule(420)).observe(document.body,{childList:true,subtree:true});schedule();setTimeout(()=>schedule(),2200)}
