import {ticketDecision} from './live24.js';
import {ticketDataQuality32,ticketPricingPlan32} from './ticketTuning32.js';

const n=v=>Number(v||0),upper=v=>String(v||'').trim().toUpperCase(),active=x=>!['SOLD','PAYOUT WAIT','PAYOUT RECEIVED'].includes(upper(x?.workflow||'HOLD'));
const norm=v=>String(v||'').trim().toLowerCase().replace(/\s+/g,' ');
export function ticketEventName32(ticket={}){const raw=String(ticket.name||'Bez názvu').trim(),parts=raw.split(/\s+-\s+/);return (parts[0]||raw).trim()||raw}
export function ticketEventKey32(ticket={}){return `${String(ticket.date||'bez-data').slice(0,10)}|${norm(ticketEventName32(ticket))}`}
function actionRow(ticket,state,totalCapital){const d=ticketDecision(ticket,state),q=ticketDataQuality32(ticket),p=ticketPricingPlan32(ticket),capital=n(ticket.buy),capitalPct=totalCapital>0?capital/totalCapital*100:0,missing=q.criticalMissing.map(x=>x.key),marketStale=p.marketStatus==='STALE_MARKET',days=p.phase.days;let score=n(d.priority)+Math.min(12,missing.length*4)+Math.min(10,capitalPct/5);if(missing.includes('listPrice'))score+=12;if(marketStale)score+=8;if(days!==null&&days<=14&&missing.includes('transferStatus'))score+=10;score=Math.min(100,Math.round(score));let nextInput=null;if(missing.includes('listPrice'))nextInput='Doplnit skutečnou list cenu';else if(marketStale||!p.marketPrice)nextInput='Zkontrolovat aktuální market cenu';else if(missing.includes('floorPrice'))nextInput='Nastavit floor cenu';else if(missing.includes('sellBy'))nextInput='Nastavit sell-by';else if(missing.includes('transferStatus'))nextInput='Ověřit převod vstupenek';return {id:ticket.id,name:ticket.name,eventKey:ticketEventKey32(ticket),eventName:ticketEventName32(ticket),date:ticket.date||null,qty:Math.max(1,n(ticket.qty)||1),capitalAtRisk:capital,capitalPct:Math.round(capitalPct*10)/10,workflow:upper(ticket.workflow||'HOLD'),transferStatus:upper(ticket.transferStatus||'UNKNOWN'),decision:d,quality:q,pricing:p,score,nextInput}}

export function ticketActionQueue32(state={}){const items=(state.ticketBook?.items||[]).filter(active),totalCapital=items.reduce((s,x)=>s+n(x.buy),0),rows=items.map(x=>actionRow(x,state,totalCapital)).sort((a,b)=>b.score-a.score||String(a.date||'').localeCompare(String(b.date||'')));return {totalCapital,activePositions:items.length,activeQty:rows.reduce((s,x)=>s+x.qty,0),needsInput:rows.filter(x=>x.nextInput).length,urgent:rows.filter(x=>x.score>=85).length,rows,top:rows[0]||null}}

export function ticketEventPortfolio32(state={}){const queue=ticketActionQueue32(state),groups=new Map();for(const row of queue.rows){let g=groups.get(row.eventKey);if(!g){g={key:row.eventKey,name:row.eventName,date:row.date,rows:[],qty:0,capitalAtRisk:0,listedQty:0,holdQty:0,pricedPositions:0,freshSourcedMarket:0,transferReadyQty:0};groups.set(row.eventKey,g)}g.rows.push(row);g.qty+=row.qty;g.capitalAtRisk+=row.capitalAtRisk;if(row.workflow==='LISTED')g.listedQty+=row.qty;else if(row.workflow==='HOLD')g.holdQty+=row.qty;if(n(row.pricing.listPrice)>0)g.pricedPositions++;if(row.pricing.marketFresh&&row.pricing.marketSourced)g.freshSourcedMarket++;if(['READY','TRANSFERRED'].includes(row.transferStatus))g.transferReadyQty+=row.qty}
 const events=[...groups.values()].map(g=>{const capitalPct=queue.totalCapital>0?g.capitalAtRisk/queue.totalCapital*100:0,top=[...g.rows].sort((a,b)=>b.score-a.score)[0],missingListed=g.rows.filter(r=>r.workflow==='LISTED'&&n(r.pricing.listPrice)<=0).length,staleMarket=g.rows.filter(r=>r.pricing.marketStatus==='STALE_MARKET').length,missingTransfer=g.rows.filter(r=>r.quality.criticalMissing.some(x=>x.key==='transferStatus')).length,concentrationBump=capitalPct>=50?12:capitalPct>=30?8:capitalPct>=20?4:0,priority=Math.min(100,n(top?.score)+concentrationBump),exposure=capitalPct>=50?'HIGH':capitalPct>=30?'MEDIUM':'NORMAL';let nextAction=top?.nextInput||top?.decision?.when||'Sledovat';if(missingListed)nextAction=`Doplnit list cenu u ${missingListed} listingů`;else if(staleMarket)nextAction=`Obnovit market u ${staleMarket} balíků`;return {...g,capitalPct:Math.round(capitalPct*10)/10,priority,exposure,missingListed,staleMarket,missingTransfer,nextAction,topAction:top?.decision?.action||'HOLD',marketCoveragePct:g.rows.length?Math.round(g.freshSourcedMarket/g.rows.length*100):0,listCoveragePct:g.rows.length?Math.round(g.pricedPositions/g.rows.length*100):0,transferReadyPct:g.qty?Math.round(g.transferReadyQty/g.qty*100):0}}).sort((a,b)=>b.priority-a.priority||String(a.date||'').localeCompare(String(b.date||'')));
 return {events,totalCapital:queue.totalCapital,totalEvents:events.length,highExposure:events.filter(x=>x.exposure==='HIGH').length,missingListed:events.reduce((s,x)=>s+x.missingListed,0),staleMarket:events.reduce((s,x)=>s+x.staleMarket,0),top:events[0]||null,queue};
}

export const ticketPortfolio32Contract={groupsBy:'event-date + normalized title prefix',autoPrice:false,autoSell:false,staleMarketCanDrivePrice:false};
