import {cloudClient,session} from './cloud.js';
const VERSION=463,N=v=>Number(v||0);let bound=false,timer=0,busy=false,resetRequested=false;
const key=(id,code)=>`${String(id)}|${String(code||'')}`;
async function ctx(){const c=await cloudClient(),s=await session();if(!c||!s)throw new Error('Cloud session chybí.');return{c,s}}
function hours(m){const d=N(m.days),v=N(window.__KAMIL_TICKET_REGIME452__?.rows?.find(x=>String(x.r.id)===String(m.r.id))?.regime452?.volatility),p=N(m.pressure),c=N(m.confidence);if(d<=1||p>=75||v>=70)return 2;if(d<=3||p>=60||v>=55)return 6;if(d<=7||c<60)return 12;return 24}
function commanderMap(){const c=window.__KAMIL_TICKET_COMMANDER454__,m=new Map();for(const x of c?.rows||[])m.set(String(x.id),{code:x.commander5?.code||x.finalCode||'SLEDUJ',bucket:x.commander5?.bucket||'SLEDUJ'});return m}
function latestMap(rows=[]){const m=new Map();for(const r of rows){const k=key(r.ticket_id,r.recommendation_code);if(!m.has(k))m.set(k,r)}return m}
async function loadExec(c,s){const {data,error}=await c.from('ticket_action_executions').select('id,ticket_id,recommendation_code,action_status,next_check_at,created_at').eq('user_id',s.user.id).order('created_at',{ascending:false}).limit(500);if(error)throw error;return data||[]}
async function persistNext(c,s,cur,id,code,at){const patch={next_check_at:new Date(at).toISOString(),model_version:'466-cadence'};if(cur?.id){const {error}=await c.from('ticket_action_executions').update(patch).eq('id',cur.id).eq('user_id',s.user.id);if(error)throw error}else{const {error}=await c.from('ticket_action_executions').insert({user_id:s.user.id,ticket_id:String(id),recommendation_code:String(code),action_status:'RECOMMENDED',...patch});if(error)throw error}}
function ensureCss(){if(document.querySelector('style[data-ca463]'))return;const s=document.createElement('style');s.dataset.ca463='1';s.textContent=`#ticketIntelView .ca463{margin:0 0 6px;padding:7px 9px;border:1px solid #294657;border-radius:9px;background:#0a1922;color:#dce8f1;display:flex;gap:12px;align-items:center;flex-wrap:wrap}.ca463 span{font-size:8px;font-weight:900;color:#7898ad;text-transform:uppercase}.ca463 b{font-size:10px}.ca463-due{color:#ff9aa5}`;document.head.appendChild(s)}
async function refresh(){if(busy)return;busy=true;try{ensureCss();const eng=window.__KAMIL_TICKET_ENGINE426__,cmd=commanderMap();if(!eng?.models?.length)return;const {c,s}=await ctx(),exec=await loadExec(c,s),latest=latestMap(exec),reset=resetRequested;resetRequested=false;const rows=[];for(const m of eng.models){const id=String(m.r.id),cm=cmd.get(id);if(!cm||cm.bucket==='NECHEJ BÝT')continue;const code=cm.code,h=hours(m),cur=latest.get(key(id,code));if(['DONE','IGNORED','CANCELLED'].includes(cur?.action_status))continue;let at=cur?.next_check_at?Date.parse(cur.next_check_at):NaN;if(reset||!Number.isFinite(at)){at=Date.now()+h*36e5;await persistNext(c,s,cur,id,code,at)}rows.push({id,title:m.r.event_name,code,hours:h,nextCheckAt:new Date(at).toISOString(),dueNow:at<=Date.now(),reason:h===2?'vysoká urgence/volatilita':h===6?'blížící se event nebo tlak':h===12?'střední riziko':'stabilní pozice'})}rows.sort((a,b)=>Number(b.dueNow)-Number(a.dueNow)||Date.parse(a.nextCheckAt)-Date.parse(b.nextCheckAt));window.__KAMIL_TICKET_CADENCE463__={version:VERSION,healthy:true,persistent:true,rows,at:Date.now()};document.documentElement.dataset.ticketCadence463='1';const host=document.querySelector('#ticketIntelView .td331');if(host){let box=host.querySelector('[data-ca463]');if(!box){box=document.createElement('section');box.dataset.ca463='1';box.className='ca463';host.querySelector('[data-da462]')?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.querySelector('[data-focus459]')?.insertAdjacentElement('beforebegin',box)}const g=h=>rows.filter(x=>x.hours===h).length,due=rows.filter(x=>x.dueNow).length;box.innerHTML=`<span>SMART REPRICING</span><b class="${due?'ca463-due':''}">${due} ke kontrole</b><b>2h ${g(2)}</b><b>6h ${g(6)}</b><b>12h ${g(12)}</b><b>24h ${g(24)}</b>`}window.dispatchEvent(new CustomEvent('kamil:ticket-cadence463-updated',{detail:{count:rows.length,due:rows.filter(x=>x.dueNow).length}}))}catch(e){window.__KAMIL_TICKET_CADENCE463__={version:VERSION,healthy:false,error:String(e?.message||e),at:Date.now()}}finally{busy=false}}
function schedule(ms=180){clearTimeout(timer);timer=setTimeout(refresh,ms)}
export function installTicketCadence463(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-engine426-updated','kamil:ticket-regime452-updated','kamil:ticket-workflow461-updated'])window.addEventListener(ev,()=>schedule());window.addEventListener('kamil:ticket-refresh397-done',()=>{resetRequested=true;schedule(80)});schedule(3200)}
