import {cloudClient,session} from './cloud.js';
import {h,money} from './utils.js';
const N=v=>Number(v||0);
let pendingResolve=null;
function close(result=null){const wrap=document.querySelector('[data-payout154]');if(wrap)wrap.hidden=true;const r=pendingResolve;pendingResolve=null;r?.(result)}
function ensure(){let wrap=document.querySelector('[data-payout154]');if(wrap)return wrap;wrap=document.createElement('div');wrap.dataset.payout154='1';wrap.className='tp154-wrap';wrap.hidden=true;wrap.innerHTML=`<div class="tp154-backdrop" data-tp154-cancel></div><section class="tp154-dialog" role="dialog" aria-modal="true" aria-labelledby="tp154-title"><button type="button" class="tp154-close" data-tp154-cancel aria-label="Zavřít">×</button><div data-tp154-body></div></section>`;document.body.appendChild(wrap);wrap.querySelectorAll('[data-tp154-cancel]').forEach(x=>x.addEventListener('click',()=>close(null)));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!wrap.hidden)close(null)});return wrap}
async function rowFor(id){const c=await cloudClient(),sess=await session();if(!c||!sess)return{ok:false,reason:'NO_SESSION'};const {data,error}=await c.from('ticket_inventory').select('id,event_name,section,qty,buy_total_czk,sell_total_czk,market_status,payout_received_czk,marketplace_fee_czk').eq('user_id',sess.user.id).eq('id',id).maybeSingle();return error?{ok:false,error}:data?{ok:true,row:data}:{ok:false,reason:'NOT_FOUND'}}
export async function openTicketPayout154(id){const loaded=await rowFor(id);if(!loaded.ok)return loaded;const row=loaded.row,status=String(row.market_status||'').toUpperCase();if(status!=='SOLD_WAITING_PAYMENT')return{ok:false,reason:'INVALID_STAGE'};const wrap=ensure(),body=wrap.querySelector('[data-tp154-body]');body.innerHTML=`<div class="tp154-eyebrow">SKUTEČNÝ SETTLEMENT</div><h2 id="tp154-title">${h(row.event_name||'Vstupenka')}</h2><p class="tp154-meta">${h(row.section||'bez sektoru')} · ${Math.max(1,N(row.qty)||1)} ks</p><div class="tp154-reference"><span>Hrubá tržba z evidence</span><b>${money(N(row.sell_total_czk))}</b><small>Jen reference — payout automaticky nepředvyplňuji.</small></div><form data-tp154-form><label>Skutečně přijatý payout (Kč)<input name="payout" type="number" min="0.01" step="0.01" inputmode="decimal" required autocomplete="off" placeholder="např. 3950"></label><label>Skutečné marketplace fee (Kč) <small>volitelné</small><input name="fee" type="number" min="0" step="0.01" inputmode="decimal" autocomplete="off" placeholder="pokud ho znáš"></label><div class="tp154-preview" data-tp154-preview></div><div class="tp154-actions"><button type="button" class="btn" data-tp154-cancel-form>Zrušit</button><button type="submit" class="btn primary">Uložit a označit vyplaceno</button></div><p class="tp154-note">Čistý P/L = skutečně přijatý payout − nákupní cena. Fee neodhaduji; ukládá se jen pokud ho skutečně znáš.</p></form>`;wrap.hidden=false;const form=body.querySelector('[data-tp154-form]'),payout=form.elements.payout,fee=form.elements.fee,preview=form.querySelector('[data-tp154-preview]'),buy=N(row.buy_total_czk);const update=()=>{const p=Number(payout.value),f=fee.value===''?null:Number(fee.value);preview.innerHTML=Number.isFinite(p)&&p>0?`<span>Čistý P/L po skutečném payoutu</span><b class="${p-buy>=0?'good':'bad'}">${p-buy>=0?'+':''}${money(p-buy)}</b>${f!==null&&Number.isFinite(f)?`<small>Uložené fee: ${money(f)}</small>`:''}`:'<span>Zadej skutečně přijatou částku.</span>'};payout.addEventListener('input',update);fee.addEventListener('input',update);update();form.querySelector('[data-tp154-cancel-form]').addEventListener('click',()=>close(null));return await new Promise(resolve=>{pendingResolve=resolve;form.addEventListener('submit',e=>{e.preventDefault();const p=Number(payout.value),f=fee.value===''?null:Number(fee.value);if(!Number.isFinite(p)||p<=0){payout.setCustomValidity('Zadej skutečně přijatou částku vyšší než 0.');payout.reportValidity();payout.setCustomValidity('');return}if(f!==null&&(!Number.isFinite(f)||f<0)){fee.setCustomValidity('Fee nesmí být záporné.');fee.reportValidity();fee.setCustomValidity('');return}close({ok:true,payout:p,fee:f,row})})})}
export const ticketPayout154Info={actualPayoutRequired:true,feeOptional:true,noFeeEstimate:true,netProfitFormula:'payout_received_czk - buy_total_czk'};
