import {modal,formModal,h,money} from './utils.js';
import {loadTicketCloud660,scanTicketsNow660,updateTicketTracking660,markTicketAlertsSeen660} from './ticketCloud660.js';
import {openTicketExcelImport660,exportTicketInventory660} from './ticketImport660.js';
import {openTicketMarketWatch656} from './ticketMarketWatch656.js';

const ACTIVE=new Set(['LISTED','NOT_LISTED']);
const STATUS={LISTED:'Nabízíš',NOT_LISTED:'Nenabízíš',SOLD_UNDELIVERED:'Prodáno / nedoručeno',SOLD_WAITING_PAYMENT:'Čekáš na peníze',PAID:'Peníze přijaty'};
const PRIMARY={AVAILABLE:'DOSTUPNÉ',LIMITED:'OMEZENĚ',SOLD_OUT:'VYPRODÁNO',UNKNOWN:'NEJISTÉ',NO_SOURCE:'NENÍ ZDROJ'};
const n=x=>Number(x||0),pct=x=>Number.isFinite(Number(x))?`${Math.round(Number(x)*100)} %`:'—';
const action=x=>x?.recommendation_label||x?.recommendation?.label||'SLEDOVAT';
const code=x=>x?.recommendation_code||x?.recommendation?.code||null;
const latest=(cloud,id,live)=>live?.get(id)||cloud.latest?.get(id)||null;
function liveMap(scan){const m=new Map();for(const r of scan?.results||[])m.set(r.id,{ticket_id:r.id,checked_at:r.market?.checkedAt,market_price_czk:r.market?.marketPriceCzk,median_price_czk:r.market?.medianPriceCzk,p25_price_czk:r.market?.p25PriceCzk,p75_price_czk:r.market?.p75PriceCzk,top_prices_czk:r.market?.topPricesCzk,competitor_count:r.market?.competitorCount,same_section_count:r.market?.sameSectionCount,recommendation_code:r.recommendation?.code,recommendation_label:r.recommendation?.label,recommendation_reason:r.recommendation?.reason,recommended_ask_czk:r.recommendation?.recommendedAskCzk,official_status:r.official?.status,official_price_czk:r.official?.lowestPriceCzk,official_source_url:r.official?.sourceUrl,official_source_name:r.official?.sourceName,official_confidence:r.official?.confidence,official_checked_at:r.official?.checkedAt});return m}
function band(s){const a=n(s?.p25_price_czk)||n(s?.market_price_czk),b=n(s?.median_price_czk)||n(s?.market_price_czk);return a&&b&&a!==b?`${money(a)} – ${money(b)}`:a||b?money(a||b):'—'}
function primaryText(s){const st=s?.official_status||'NO_SOURCE',price=n(s?.official_price_czk),src=s?.official_source_name;return`${PRIMARY[st]||st}${price?` · od ${money(price)}`:''}${src?` · ${src}`:''}`}
function gross(row,s){const rec=n(s?.recommended_ask_czk)||n(s?.market_price_czk),buy=n(row.buy_each_czk),qty=n(row.qty)||1;if(!rec||!buy)return null;return{total:(rec-buy)*qty,roi:rec/buy-1}}
function rowHtml(row,s){const c=code(s),g=gross(row,s),ask=n(row.ask_each_czk),rec=n(s?.recommended_ask_czk),primary=s?.official_status||'NO_SOURCE';return`<article class="card ti66-row"><div class="row"><div><b>${h(row.event_name)}</b><div class="muted">${h(STATUS[row.market_status]||row.market_status)} · ${row.qty} ks · ${h(row.section||'bez sekce')}</div></div><span class="tmw-rec ${c==='LOWER'?'critical':c==='LIST'||c==='RAISE'?'success':'neutral'}">${h(action(s))}</span></div><div class="metric-strip ti66-metrics"><div class="metric"><span>Nákup / ks</span><b>${money(row.buy_each_czk)}</b></div><div class="metric"><span>Viagogo</span><b>${band(s)}</b></div><div class="metric"><span>Moje cena</span><b>${ask?money(ask):'—'}</b></div><div class="metric"><span>Doporučení</span><b>${rec?money(rec):'—'}</b></div></div><div class="row"><span>Oficiální prodej</span><b class="${primary==='SOLD_OUT'?'success':primary==='AVAILABLE'||primary==='LIMITED'?'warning':''}">${h(primaryText(s))}</b></div>${g?`<div class="row"><span>Hrubý potenciál před seller poplatky</span><b>${money(g.total)} · ROI ${pct(g.roi)}</b></div>`:''}<p class="muted">${h(s?.recommendation_reason||'Čekám na první společný snapshot sekundárního a oficiálního trhu.')}</p>${ACTIVE.has(row.market_status)?`<button class="btn" data-ti661-edit="${h(row.id)}">Upravit ceny a zdroje</button>`:''}</article>`}
function summary(cloud,live){const active=cloud.inventory.filter(x=>ACTIVE.has(x.market_status)),p={AVAILABLE:0,LIMITED:0,SOLD_OUT:0,UNKNOWN:0,NO_SOURCE:0},acts={LOWER:0,LIST:0,RAISE:0,HOLD:0,VERIFY:0};for(const r of active){const s=latest(cloud,r.id,live),st=s?.official_status||'NO_SOURCE';p[st]=(p[st]||0)+r.qty;const c=code(s);if(c==='LOWER')acts.LOWER+=r.qty;else if(c==='LIST')acts.LIST+=r.qty;else if(c==='RAISE')acts.RAISE+=r.qty;else if(c==='HOLD')acts.HOLD+=r.qty;else acts.VERIFY+=r.qty}return{active,p,acts}}
function html(cloud,live){const s=summary(cloud,live);return`<div class="card"><div class="eyebrow">TICKET INTELLIGENCE 66.1</div><h2>Sekundární + oficiální trh</h2><div class="row"><span>Ofiko dostupné / omezeně</span><b>${s.p.AVAILABLE+s.p.LIMITED} ks</b></div><div class="row"><span>Ofiko vyprodané</span><b>${s.p.SOLD_OUT} ks</b></div><div class="row"><span>Ofiko nejisté / bez zdroje</span><b>${s.p.UNKNOWN+s.p.NO_SOURCE} ks</b></div><div class="row"><span>Zlevnit / vystavit / zdražit</span><b>${s.acts.LOWER} / ${s.acts.LIST} / ${s.acts.RAISE} ks</b></div><p class="muted">Když je oficiální prodej stále dostupný levněji, doporučená sekundární cena dostává strop. Po vyprodání oficiálního trhu rozhoduje hlavně Viagogo.</p></div>${cloud.alerts.length?`<div class="card"><div class="eyebrow">ZMĚNY DOPORUČENÍ</div>${cloud.alerts.slice(0,8).map(a=>`<div class="row"><div><b>${h(a.title)}</b><div class="muted">${h(a.body||'')}</div></div></div>`).join('')}</div>`:''}${cloud.inventory.map(r=>rowHtml(r,latest(cloud,r.id,live))).join('')}`}
let current=null,bound=false;
async function edit(id){const row=current?.inventory.find(x=>x.id===id);if(!row)return false;const data=await formModal(`Trhy: ${row.event_name}`,`<label class="field"><span>Viagogo event URL</span><input name="viagogoUrl" type="url" value="${h(row.viagogo_url||'')}"></label><label class="field"><span>Oficiální prodej URL</span><input name="officialUrl" type="url" value="${h(row.official_url||'')}" placeholder="https://ticketmaster... / ticketportal... / eventim..."></label><label class="field"><span>Moje nabídková cena / ks (Kč)</span><input name="askEachCzk" type="number" min="0" step="1" value="${h(row.ask_each_czk||'')}"></label><p class="muted">Kamil OS tyto zdroje pouze čte. Nikdy na nich sám nic nekoupí, nevystaví ani nepřecení.</p>`,{submitLabel:'Uložit'});if(!data)return false;for(const [k,v] of [['Viagogo',data.viagogoUrl],['Oficiální',data.officialUrl]]){if(v){try{const u=new URL(v);if(u.protocol!=='https:')throw 0}catch{await modal('Neplatný odkaz',`<p>${k} odkaz musí být platná HTTPS URL.</p>`,[{label:'OK',value:null,primary:true}]);return false}}}const out=await updateTicketTracking660(id,{viagogoUrl:String(data.viagogoUrl||'').trim()||null,officialUrl:String(data.officialUrl||'').trim()||null,askEachCzk:Number(data.askEachCzk||0)||null});if(!out.ok)throw out.error||new Error('Uložení selhalo');return true}
function bind(){if(bound)return;bound=true;document.addEventListener('click',async e=>{const b=e.target?.closest?.('[data-ti661-edit]');if(!b||!current)return;e.preventDefault();e.stopPropagation();const root=b.closest('.modal');[...root?.querySelectorAll?.('[data-modal-buttons] button')||[]].find(x=>/Zavřít/i.test(x.textContent||''))?.click();try{if(await edit(b.dataset.ti661Edit))setTimeout(()=>openTicketCommander661(),0)}catch(err){await modal('Ticket Intelligence',`<p>${h(err?.message||err)}</p>`,[{label:'OK',value:null,primary:true}])}})}
export async function openTicketCommander661(live=null){bind();const cloud=await loadTicketCloud660();if(!cloud.ok){await modal('Ticket Intelligence 66.1','<p>Serverové sledování potřebuje připojený cloud. Otevírám lokální Viagogo Market Watch.</p>',[{label:'Pokračovat',value:null,primary:true}]);return openTicketMarketWatch656()}current=cloud;const lm=live instanceof Map?live:liveMap(live);const choice=await modal('Ticket Intelligence 66.1',html(cloud,lm),[{label:'Obnovit oba trhy teď',value:'refresh',primary:true},{label:'Importovat Excel',value:'import'},{label:'Exportovat stav.xlsx',value:'export'},{label:cloud.alerts.length?'Označit změny přečtené':'Zavřít',value:cloud.alerts.length?'seen':null},{label:'Zavřít',value:null}]);if(choice==='refresh'){try{return openTicketCommander661(await scanTicketsNow660(cloud.inventory))}catch(e){await modal('Obnovit trhy',`<p>${h(e?.message||e)}</p>`,[{label:'OK',value:null,primary:true}]);return openTicketCommander661()}}if(choice==='import'){const out=await openTicketExcelImport660();return out?openTicketCommander661():null}if(choice==='export'){await exportTicketInventory660();return openTicketCommander661()}if(choice==='seen'){await markTicketAlertsSeen660(cloud.alerts.map(x=>x.id));return openTicketCommander661()}return choice}
