import {qs,h,money,modal} from './utils.js';
import {loadTicketCloud660,scanTicketsNow660,markTicketAlertsSeen660} from './ticketCloud660.js';
import {scanTicketSearchFallback676} from './ticketSearchFallback676.js';
import {openTicketExcelImport660,exportTicketInventory660} from './ticketImport660.js';
import {openTicketCommander660} from './ticketCommander660.js';

const n=x=>Number(x||0);
const active=x=>['LISTED','NOT_LISTED'].includes(x.market_status);
const label=x=>x?.recommendation_label||'SLEDOVAT';
const code=x=>x?.recommendation_code||null;
const tone=x=>['LOWER','OFFICIAL_COMPETITION','VERIFY_DATA'].includes(code(x))?'critical':['LIST','RAISE'].includes(code(x))?'success':'neutral';
const status=x=>({LISTED:'Nabízíš',NOT_LISTED:'Nenabízíš',SOLD_UNDELIVERED:'Prodáno / doručit',SOLD_WAITING_PAYMENT:'Čekáš na peníze',PAID:'Peníze přijaty'})[x]||x;
function latest(cloud,id){return cloud.latest?.get(id)||null}
function needsAction(r,s){return active(r)&&!!code(s)&&!['HOLD','NO_PRICE','FETCH_ERROR','SOURCE_MISSING'].includes(code(s))}
function bucket(r,s){if(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAID'].includes(r.market_status))return'sold';if(needsAction(r,s))return'action';if(active(r))return'hold';return'all'}
function stubhubHealth(r,s){if(r?.stubhub_url)return{code:'DIRECT',tone:'success',detail:'uložený přímý event'};if(s?.stubhub_status==='VERIFIED'||n(s?.stubhub_price_czk))return{code:'DISCOVERY',tone:'neutral',detail:'nalezen při posledním scanu'};return{code:'MISSING',tone:'critical',detail:'bez ověřené event URL'}}
function summary(cloud){
 const a=cloud.inventory.filter(active),sold=cloud.inventory.filter(x=>x.market_status==='SOLD_UNDELIVERED'),wait=cloud.inventory.filter(x=>x.market_status==='SOLD_WAITING_PAYMENT'),paid=cloud.inventory.filter(x=>x.market_status==='PAID');let potential=0,action=0,hold=0,sell=0,lower=0,raise=0,verify=0,direct=0,discovery=0,missing=0;
 for(const r of a){const s=latest(cloud,r.id),c=code(s),sh=stubhubHealth(r,s);if(needsAction(r,s))action++;else hold++;if(c==='LIST')sell++;if(c==='LOWER')lower++;if(c==='RAISE')raise++;if(c==='VERIFY_DATA')verify++;if(sh.code==='DIRECT')direct++;else if(sh.code==='DISCOVERY')discovery++;else missing++;const rec=n(s?.recommended_ask_czk)||n(s?.market_price_czk);if(rec&&r.buy_each_czk&&c!=='VERIFY_DATA')potential+=(rec-n(r.buy_each_czk))*n(r.qty||1)}
 const invested=a.reduce((x,r)=>x+n(r.buy_total_czk),0),realized=paid.reduce((x,r)=>x+n(r.sell_total_czk)-n(r.buy_total_czk),0),roi=invested?potential/invested*100:0;
 return{a,sold,wait,paid,potential,action,hold,sell,lower,raise,verify,direct,discovery,missing,invested,realized,roi};
}
function sourceMeta(s){const msg=String(s?.source_message||'').toLowerCase(),conf=String(s?.confidence||'').toLowerCase();if(conf.includes('official')||msg.includes('official api')||msg.includes('oficiální api'))return{label:'Viagogo API',tone:'success',detail:'oficiální zdroj'};if(conf==='event-floor-search'||msg.includes('vyhledávací fallback'))return{label:'Veřejný fallback',tone:'neutral',detail:'orientační cena akce'};if(msg.includes('403'))return{label:'Viagogo blokuje',tone:'critical',detail:'HTTP 403'};if(s?.source_status==='missing'||code(s)==='SOURCE_MISSING')return{label:'Zdroj nenalezen',tone:'critical',detail:'bez spolehlivé ceny'};if(s?.market_price_czk)return{label:'Tržní zdroj',tone:'neutral',detail:'ověřený snapshot'};return{label:'Bez ceny',tone:'neutral',detail:'čeká na zdroj'}}
function multiMeta(s){const score=Number(s?.multi_market_confidence),has=Number.isFinite(score)&&score>0,viagogo=s?.viagogo_status||'UNAVAILABLE',stubhub=s?.stubhub_status||'UNAVAILABLE',conflict=!!s?.multi_market_conflict;return{has,score,label:s?.multi_market_label||'NEURČENO',viagogo,stubhub,conflict,tone:!has||score<65||conflict?'critical':score>=85?'success':'neutral'}}
function freshness(s){const t=Date.parse(s?.checked_at||'');if(!t)return{tone:'bad',text:'bez času kontroly'};const hh=(Date.now()-t)/36e5;return hh<=6?{tone:'fresh',text:hh<1?'čerstvé':`${Math.round(hh)} h staré`}:hh<=24?{tone:'stale',text:`${Math.round(hh)} h staré`}:{tone:'bad',text:`${Math.round(hh/24)} d staré`}}
function confidenceNote(s){return s?.confidence==='event-floor-search'?' · orientační minimum celé akce':''}
function marketBadges(r,s){const m=multiMeta(s),sh=stubhubHealth(r,s),vg=m.viagogo==='LIVE'?'VIAGOGO LIVE':'VIAGOGO NEDOSTUPNÝ';return `<div class="ticket-source-line"><span class="tmw-rec ${m.viagogo==='LIVE'?'success':'critical'}">${vg}</span><span class="tmw-rec ${sh.tone}">STUBHUB ${sh.code}</span>${m.has?`<span class="tmw-rec ${m.tone}">CONFIDENCE ${m.score} % · ${h(m.label)}</span>`:''}${m.conflict?'<span class="tmw-rec critical">CENOVÝ KONFLIKT</span>':''}</div><div class="muted">StubHub health: ${h(sh.detail)}</div>`}
function row(r,s){const rec=n(s?.recommended_ask_czk),market=n(s?.market_price_czk),ask=n(r.ask_each_czk),group=bucket(r,s),src=sourceMeta(s),fresh=freshness(s);return `<article class="card ti66-row ticket-filter-row" data-ticket-group="${group}"><div class="row"><div><b>${h(r.event_name)}</b><div class="muted">${h(status(r.market_status))} · ${n(r.qty)} ks · ${h(r.section||'bez sekce')}</div></div><span class="tmw-rec ${tone(s)}">${h(label(s))}</span></div><div class="metric-strip ti66-metrics"><div class="metric"><span>Nákup / ks</span><b>${money(r.buy_each_czk)}</b></div><div class="metric"><span>Viagogo trh</span><b>${market?money(market):'—'}</b></div><div class="metric"><span>StubHub</span><b>${n(s?.stubhub_price_czk)?money(s.stubhub_price_czk):'—'}</b></div><div class="metric"><span>Moje cena</span><b>${ask?money(ask):'—'}</b></div><div class="metric"><span>Doporučení</span><b>${rec?money(rec):'—'}</b></div></div>${marketBadges(r,s)}<div class="ticket-source-line"><span class="tmw-rec ${src.tone}">${h(src.label)}</span><span class="muted">${h(src.detail)}</span></div><div class="data70-line ${fresh.tone}"><i class="data70-dot"></i><span>${h(fresh.text)} · ${h(s?.confidence||'confidence neurčeno')}</span></div><p class="muted">${h(s?.recommendation_reason||s?.source_message||'Čekám na další ověření trhu.')}${h(confidenceNote(s))}</p><button class="btn" data-ticket-detail>Detail / upravit zdroje</button></article>`}
function applyFilter(host,filter){host.querySelectorAll('[data-ticket-filter]').forEach(b=>b.classList.toggle('on',b.dataset.ticketFilter===filter));host.querySelectorAll('.ticket-filter-row').forEach(r=>r.classList.toggle('hidden',filter!=='all'&&r.dataset.ticketGroup!==filter));const count=[...host.querySelectorAll('.ticket-filter-row')].filter(r=>!r.classList.contains('hidden')).length;const out=host.querySelector('[data-ticket-visible]');if(out)out.textContent=`Zobrazeno ${count}`}
async function apiState(){try{const r=await fetch('/api/viagogo-official',{cache:'no-store'}),j=await r.json();return{configured:!!j.configured,version:j.version||null}}catch{return{configured:false,error:true}}}
function apiBanner(state){if(state.configured)return `<section class="card ticket-api-status ok"><div><b>Viagogo API připojeno</b><div class="muted">Viagogo je primární cenový zdroj. StubHub health rozlišuje DIRECT, DISCOVERY a MISSING; finální doporučení pořád hlídá multi-market confidence.</div></div><span class="tmw-rec success">TICKETS 83</span></section>`;return `<section class="card ticket-api-status warn"><div><b>Viagogo API zatím není připojeno</b><div class="muted">Bez API může Viagogo serverové čtení blokovat. StubHub health ale dál ukáže, které akce mají přímé event párování.</div></div><div class="ticket-api-actions"><button class="btn" data-viagogo-help>Jak připojit</button><span class="tmw-rec critical">NEPŘIPOJENO</span></div></section>`}
async function showApiHelp(){await modal('Připojení Viagogo API',`<div class="card"><h2>Co chybí</h2><p>V projektu je integrace připravená. Do Vercelu je potřeba bezpečně uložit dvě serverové proměnné:</p><div class="decision-note"><b>VIAGOGO_CLIENT_ID</b><br><b>VIAGOGO_CLIENT_SECRET</b></div><p class="muted">Po jejich přidání se nic dalšího v aplikaci nepřepisuje.</p></div>`,[{label:'Rozumím',value:null,primary:true}])}
async function paint(host){host.innerHTML='<div class="card"><b>Načítám Ticket Intelligence…</b></div>';const [cloud,api]=await Promise.all([loadTicketCloud660(),apiState()]);if(!cloud.ok){host.innerHTML='<div class="card"><h2>Ticket Intelligence potřebuje cloud</h2><p class="muted">Připoj cloudový profil a vstupenky se zobrazí tady jako normální stránka.</p></div>';return}const s=summary(cloud),rows=[...cloud.inventory].sort((a,b)=>Number(!needsAction(a,latest(cloud,a.id)))-Number(!needsAction(b,latest(cloud,b.id)))||Number(!active(a))-Number(!active(b))||String(a.event_date||'').localeCompare(String(b.event_date||'')));host.innerHTML=`<div class="ux64-page ticket-page"><section class="ux64-hero ticket-page-hero"><div class="eyebrow">VSTUPENKY · TICKETS 83 PAIRING HEALTH</div><h1>Co prodat, zlevnit nebo držet.</h1><p>Viagogo je primární signál. StubHub má nyní trvalé event párování a health stav DIRECT / DISCOVERY / MISSING.</p><div class="ticket-page-actions"><button class="btn primary" data-ticket-refresh>Obnovit trh</button><button class="btn" data-ticket-import>Import Excel</button><button class="btn" data-ticket-export>Export</button>${cloud.alerts.length?'<button class="btn" data-ticket-seen>Označit změny přečtené</button>':''}</div></section>${apiBanner(api)}
 <section class="ticket69-status-grid"><div class="ticket69-status sell"><b>${s.sell+s.raise}</b><span>PRODAT / ZVEDNOUT</span></div><div class="ticket69-status lower"><b>${s.lower}</b><span>ZLEVNIT</span></div><div class="ticket69-status lower"><b>${s.verify}</b><span>OVĚŘIT DATA</span></div><div class="ticket69-status hold"><b>${s.hold}</b><span>DRŽET</span></div><div class="ticket69-status transfer"><b>${s.sold.length}</b><span>ČEKÁ NA TRANSFER</span></div><div class="ticket69-status payout"><b>${s.wait.length}</b><span>ČEKÁ NA PAYOUT</span></div></section>
 <section class="metric-strip ticket-summary-strip"><div class="metric ticket-metric money"><span>Aktivní kapitál</span><b>${money(s.invested)}</b></div><div class="metric ticket-metric profit"><span>Potenciál z ověřených doporučení</span><b>${money(s.potential)}</b></div><div class="metric ticket-metric action"><span>StubHub DIRECT</span><b>${s.direct}</b></div><div class="metric ticket-metric calm"><span>DISCOVERY / MISSING</span><b>${s.discovery} / ${s.missing}</b></div></section>
 <section class="ticket-filterbar card"><div><b>Co chceš vidět</b><div class="muted" data-ticket-visible>Zobrazeno ${rows.length}</div></div><div class="ticket-filter-buttons"><button class="btn on" data-ticket-filter="all">Vše (${rows.length})</button><button class="btn ticket-filter-action" data-ticket-filter="action">Řešit (${s.action})</button><button class="btn ticket-filter-hold" data-ticket-filter="hold">Držet (${s.hold})</button><button class="btn ticket-filter-sold" data-ticket-filter="sold">Prodáno (${s.sold.length+s.wait.length+s.paid.length})</button></div></section><section class="ticket-page-list">${rows.map(r=>row(r,latest(cloud,r.id))).join('')||'<div class="card">Žádné vstupenky.</div>'}</section></div>`;
host.querySelectorAll('[data-ticket-filter]').forEach(b=>b.addEventListener('click',()=>applyFilter(host,b.dataset.ticketFilter)));host.querySelector('[data-viagogo-help]')?.addEventListener('click',showApiHelp);host.querySelector('[data-ticket-refresh]')?.addEventListener('click',async b=>{b.currentTarget.disabled=true;b.currentTarget.textContent='Obnovuji…';try{await scanTicketsNow660(cloud.inventory);try{await scanTicketSearchFallback676(cloud.inventory)}catch{}await paint(host)}catch(e){await modal('Obnovit trh',`<p>${h(e?.message||e)}</p>`,[{label:'OK',value:null,primary:true}]);b.currentTarget.disabled=false;b.currentTarget.textContent='Obnovit trh'}});host.querySelector('[data-ticket-import]')?.addEventListener('click',async()=>{if(await openTicketExcelImport660())await paint(host)});host.querySelector('[data-ticket-export]')?.addEventListener('click',()=>exportTicketInventory660());host.querySelector('[data-ticket-seen]')?.addEventListener('click',async()=>{await markTicketAlertsSeen660(cloud.alerts.map(x=>x.id));await paint(host)});host.querySelectorAll('[data-ticket-detail]').forEach(b=>b.addEventListener('click',()=>openTicketCommander660()));}
export function renderTicketPage665(){const host=qs('#ticketIntelView');if(host)paint(host).catch(e=>{host.innerHTML=`<div class="card"><h2>Vstupenky se nepodařilo načíst</h2><p class="muted">${h(e?.message||e)}</p></div>`})}
