import {qs,h,money,modal} from './utils.js';
import {loadTicketCloud660,scanTicketsNow660,markTicketAlertsSeen660} from './ticketCloud660.js';
import {scanTicketSearchFallback676} from './ticketSearchFallback676.js';
import {openTicketExcelImport660,exportTicketInventory660} from './ticketImport660.js';
import {openTicketCommander660} from './ticketCommander660.js';

const n=x=>Number(x||0);
const active=x=>['LISTED','NOT_LISTED'].includes(x.market_status);
const label=x=>x?.recommendation_label||'SLEDOVAT';
const code=x=>x?.recommendation_code||null;
const tone=x=>['LOWER','OFFICIAL_COMPETITION'].includes(code(x))?'critical':['LIST','RAISE'].includes(code(x))?'success':'neutral';
const status=x=>({LISTED:'Nabízíš',NOT_LISTED:'Nenabízíš',SOLD_UNDELIVERED:'Prodáno / doručit',SOLD_WAITING_PAYMENT:'Čekáš na peníze',PAID:'Peníze přijaty'})[x]||x;
function latest(cloud,id){return cloud.latest?.get(id)||null}
function needsAction(r,s){return active(r)&&!!code(s)&&!['HOLD','NO_PRICE'].includes(code(s))}
function bucket(r,s){if(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAID'].includes(r.market_status))return'sold';if(needsAction(r,s))return'action';if(active(r))return'hold';return'all'}
function summary(cloud){const a=cloud.inventory.filter(active),sold=cloud.inventory.filter(x=>x.market_status==='SOLD_UNDELIVERED'),wait=cloud.inventory.filter(x=>x.market_status==='SOLD_WAITING_PAYMENT');let potential=0,action=0,hold=0;for(const r of a){const s=latest(cloud,r.id);if(needsAction(r,s))action++;else hold++;const rec=n(s?.recommended_ask_czk)||n(s?.market_price_czk);if(rec&&r.buy_each_czk)potential+=(rec-n(r.buy_each_czk))*n(r.qty||1)}return{a,sold,wait,potential,action,hold,invested:a.reduce((x,r)=>x+n(r.buy_total_czk),0)}}
function confidenceNote(s){return s?.confidence==='event-floor-search'?' · orientační minimum celé akce':''}
function row(r,s){const rec=n(s?.recommended_ask_czk),market=n(s?.market_price_czk),ask=n(r.ask_each_czk),group=bucket(r,s);return `<article class="card ti66-row ticket-filter-row" data-ticket-group="${group}"><div class="row"><div><b>${h(r.event_name)}</b><div class="muted">${h(status(r.market_status))} · ${n(r.qty)} ks · ${h(r.section||'bez sekce')}</div></div><span class="tmw-rec ${tone(s)}">${h(label(s))}</span></div><div class="metric-strip ti66-metrics"><div class="metric"><span>Nákup / ks</span><b>${money(r.buy_each_czk)}</b></div><div class="metric"><span>Trh</span><b>${market?money(market):'—'}</b></div><div class="metric"><span>Moje cena</span><b>${ask?money(ask):'—'}</b></div><div class="metric"><span>Doporučení</span><b>${rec?money(rec):'—'}</b></div></div><p class="muted">${h(s?.recommendation_reason||s?.source_message||'Čekám na další ověření trhu.')}${h(confidenceNote(s))}</p><button class="btn" data-ticket-detail>Detail / upravit zdroje</button></article>`}
function applyFilter(host,filter){host.querySelectorAll('[data-ticket-filter]').forEach(b=>b.classList.toggle('on',b.dataset.ticketFilter===filter));host.querySelectorAll('.ticket-filter-row').forEach(r=>{r.classList.toggle('hidden',filter!=='all'&&r.dataset.ticketGroup!==filter)});const count=[...host.querySelectorAll('.ticket-filter-row')].filter(r=>!r.classList.contains('hidden')).length;const out=host.querySelector('[data-ticket-visible]');if(out)out.textContent=`Zobrazeno ${count}`}
async function apiState(){try{const r=await fetch('/api/viagogo-official',{cache:'no-store'}),j=await r.json();return{configured:!!j.configured,version:j.version||null}}catch{return{configured:false,error:true}}}
function apiBanner(state){if(state.configured)return `<section class="card ticket-api-status ok"><div><b>Viagogo API připojeno</b><div class="muted">Oficiální API je primární zdroj cen. HTML scraping slouží jen jako záloha.</div></div><span class="tmw-rec success">PŘIPOJENO</span></section>`;return `<section class="card ticket-api-status warn"><div><b>Viagogo API zatím není připojeno</b><div class="muted">Chybí VIAGOGO_CLIENT_ID a VIAGOGO_CLIENT_SECRET. Proto se používá záložní čtení, které může Viagogo blokovat HTTP 403.</div></div><span class="tmw-rec critical">NEPŘIPOJENO</span></section>`}
async function paint(host){host.innerHTML='<div class="card"><b>Načítám Ticket Intelligence…</b></div>';const [cloud,api]=await Promise.all([loadTicketCloud660(),apiState()]);if(!cloud.ok){host.innerHTML='<div class="card"><h2>Ticket Intelligence potřebuje cloud</h2><p class="muted">Připoj cloudový profil a vstupenky se zobrazí tady jako normální stránka.</p></div>';return}const s=summary(cloud),rows=[...cloud.inventory].sort((a,b)=>Number(!needsAction(a,latest(cloud,a.id)))-Number(!needsAction(b,latest(cloud,b.id)))||Number(!active(a))-Number(!active(b))||String(a.event_date||'').localeCompare(String(b.event_date||'')));host.innerHTML=`<div class="ux64-page ticket-page"><section class="ux64-hero ticket-page-hero"><div class="eyebrow">VSTUPENKY</div><h1>Ticket Intelligence</h1><p>Nejdřív to, co vyžaduje zásah. Zbytek může počkat.</p><div class="ticket-page-actions"><button class="btn primary" data-ticket-refresh>Obnovit trh</button><button class="btn" data-ticket-import>Import Excel</button><button class="btn" data-ticket-export>Export</button>${cloud.alerts.length?'<button class="btn" data-ticket-seen>Označit změny přečtené</button>':''}</div></section>${apiBanner(api)}<section class="metric-strip ticket-summary-strip"><div class="metric ticket-metric money"><span>Aktivní kapitál</span><b>${money(s.invested)}</b></div><div class="metric ticket-metric profit"><span>Potenciál</span><b>${money(s.potential)}</b></div><div class="metric ticket-metric action"><span>Řešit teď</span><b>${s.action}</b></div><div class="metric ticket-metric calm"><span>Jen držet</span><b>${s.hold}</b></div></section><section class="ticket-filterbar card"><div><b>Co chceš vidět</b><div class="muted" data-ticket-visible>Zobrazeno ${rows.length}</div></div><div class="ticket-filter-buttons"><button class="btn on" data-ticket-filter="all">Vše (${rows.length})</button><button class="btn ticket-filter-action" data-ticket-filter="action">Řešit (${s.action})</button><button class="btn ticket-filter-hold" data-ticket-filter="hold">Držet (${s.hold})</button><button class="btn ticket-filter-sold" data-ticket-filter="sold">Prodáno (${s.sold.length+s.wait.length+cloud.inventory.filter(x=>x.market_status==='PAID').length})</button></div></section><section class="ticket-page-list">${rows.map(r=>row(r,latest(cloud,r.id))).join('')||'<div class="card">Žádné vstupenky.</div>'}</section></div>`;
host.querySelectorAll('[data-ticket-filter]').forEach(b=>b.addEventListener('click',()=>applyFilter(host,b.dataset.ticketFilter)));host.querySelector('[data-ticket-refresh]')?.addEventListener('click',async b=>{b.currentTarget.disabled=true;try{await scanTicketsNow660(cloud.inventory);try{await scanTicketSearchFallback676(cloud.inventory)}catch{}await paint(host)}catch(e){await modal('Obnovit trh',`<p>${h(e?.message||e)}</p>`,[{label:'OK',value:null,primary:true}]);b.currentTarget.disabled=false}});host.querySelector('[data-ticket-import]')?.addEventListener('click',async()=>{if(await openTicketExcelImport660())await paint(host)});host.querySelector('[data-ticket-export]')?.addEventListener('click',()=>exportTicketInventory660());host.querySelector('[data-ticket-seen]')?.addEventListener('click',async()=>{await markTicketAlertsSeen660(cloud.alerts.map(x=>x.id));await paint(host)});host.querySelectorAll('[data-ticket-detail]').forEach(b=>b.addEventListener('click',()=>openTicketCommander660()));}
export function renderTicketPage665(){const host=qs('#ticketIntelView');if(host)paint(host).catch(e=>{host.innerHTML=`<div class="card"><h2>Vstupenky se nepodařilo načíst</h2><p class="muted">${h(e?.message||e)}</p></div>`})}
