const VERSION=427;let bound=false,timer=0;
const fmt=v=>Number.isFinite(Number(v))&&Number(v)!==0?`${Math.round(Number(v)).toLocaleString('cs-CZ')} Kč`:'—';
const pct=v=>Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(1)} %`:'—';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ensureCss(){if(document.querySelector('style[data-engui427]'))return;const s=document.createElement('style');s.dataset.engui427='1';s.textContent=`
#ticketIntelView .eng427-line{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.eng427-chip{display:inline-flex;align-items:center;min-height:22px;padding:0 7px;border:1px solid #294457;border-radius:999px;background:#0c1d28;color:#89a4b7;font-size:8px;font-weight:800}.eng427-chip.hot{color:#f2b98b;border-color:#60462d;background:#241b13}.eng427-chip.good{color:#8bd8ad;border-color:#2d5946;background:#10251d}
#ticketIntelView .eng427-detail{display:none;grid-column:1/-1;padding:11px 12px;border:1px solid #223b4c;border-radius:10px;background:#091923}.td420-expanded .eng427-detail{display:grid;grid-template-columns:repeat(6,minmax(100px,1fr));gap:8px}.eng427-detail>div{padding:8px;border:1px solid #203746;border-radius:8px;background:#0d1c27}.eng427-detail span{display:block;color:#708da3;font-size:8px;font-weight:900;letter-spacing:.065em;text-transform:uppercase}.eng427-detail b{display:block;margin-top:4px;font-size:11px}.eng427-detail small{display:block;margin-top:3px;color:#718596;font-size:8px;line-height:1.3}
#ticketIntelView .td331-badge[data-engine-tone="sell"]{color:#ff9aa5!important;background:#311a20!important;border-color:#5d303a!important}#ticketIntelView .td331-badge[data-engine-tone="warn"]{color:#f0c67c!important;background:#302716!important;border-color:#5c4b28!important}#ticketIntelView .td331-badge[data-engine-tone="good"]{color:#88dcac!important;background:#132c22!important;border-color:#2c5c46!important}#ticketIntelView .td331-badge[data-engine-tone="hold"]{color:#a9c6dd!important;background:#182733!important;border-color:#355267!important}
@media(max-width:900px){.td420-expanded .eng427-detail{grid-template-columns:repeat(3,minmax(100px,1fr))}}@media(max-width:560px){.td420-expanded .eng427-detail{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(s)}
function priceBox(card,label){return [...card.querySelectorAll('.td420-summary .td420-price')].find(x=>String(x.querySelector('span')?.textContent||'').trim().toLowerCase()===label.toLowerCase())||null}
function tone(code){if(['PRODAT DNES','PRODAT RYCHLE','ZLEVNIT'].includes(code))return'sell';if(['VYSTAVIT','ZDRAŽIT'].includes(code))return'good';if(code==='DRŽET')return'hold';return'warn'}
function paint(m){const card=document.querySelector(`#ticketIntelView [data-ticket-detail="${CSS.escape(String(m.r.id))}"]`)?.closest('[data-inventory-card]');if(!card)return;const market=priceBox(card,'Trh'),minimum=priceBox(card,'Minimum'),decision=priceBox(card,'Doporučení');if(market){market.querySelector('b').textContent=fmt(m.market);const sm=market.querySelector('small');if(sm)sm.textContent=m.best?`${m.best.cls} · conf ${m.confidence}%`:'bez trhu'}if(minimum){minimum.querySelector('b').textContent=fmt(m.min);const sm=minimum.querySelector('small');if(sm)sm.textContent=`break-even · fee ${(m.fee.rate*100).toFixed(1)}%`}if(decision){decision.querySelector('b').textContent=m.price?fmt(m.price):m.code;const sm=decision.querySelector('small');if(sm)sm.textContent=m.price?`${m.code} · ${m.why}`:m.why}const badge=card.querySelector('.td331-badge');if(badge){badge.textContent=m.code;badge.dataset.engineTone=tone(m.code)}let line=card.querySelector('.eng427-line');const top=card.querySelector('.td331-ticket-top>div');if(!line&&top){line=document.createElement('div');line.className='eng427-line';top.appendChild(line)}if(line)line.innerHTML=`<span class="eng427-chip ${m.pressure>=70?'hot':''}">pressure ${m.pressure}</span><span class="eng427-chip ${m.confidence>=75?'good':''}">conf ${m.confidence}%</span><span class="eng427-chip">liq ${m.liquidity.score}</span><span class="eng427-chip">momentum ${m.momentum.score}</span>`;let detail=card.querySelector('.eng427-detail');if(!detail){detail=document.createElement('div');detail.className='eng427-detail';card.appendChild(detail)}const c=m.curve||{},b=m.benchmark||{};detail.innerHTML=`<div><span>24H</span><b>${m.momentum.h24===null?'—':pct(m.momentum.h24)}</b><small>krátký trend</small></div><div><span>7D</span><b>${m.momentum.d7===null?'—':pct(m.momentum.d7)}</b><small>střední trend</small></div><div><span>30D</span><b>${m.momentum.d30===null?'—':pct(m.momentum.d30)}</b><small>dlouhý trend</small></div><div><span>HIST. PERCENTIL</span><b>${b.percentile===null?'—':`${Math.round(b.percentile)}.`}</b><small>${b.min?`${fmt(b.min)} – ${fmt(b.max)}`:'bez historie'}</small></div><div><span>PROFIT TARGET</span><b>${fmt(m.target)}</b><small>cílové čisté ROI 20 %</small></div><div><span>STOP-LOSS</span><b>${fmt(m.emergency)}</b><small>cca -5 % čistě před eventem</small></div><div><span>30 D</span><b>${fmt(c.d30)}</b><small>cenová křivka</small></div><div><span>14 D</span><b>${fmt(c.d14)}</b><small>cenová křivka</small></div><div><span>7 D</span><b>${fmt(c.d7)}</b><small>cenová křivka</small></div><div><span>72 H</span><b>${fmt(c.d3)}</b><small>cenová křivka</small></div><div><span>24 H</span><b>${fmt(c.d1)}</b><small>cenová křivka</small></div><div><span>DEPTH</span><b>${m.depth.count||'—'}</b><small>${m.depth.removed?`${m.depth.removed} outlierů odfiltrováno`:'bez outlierů'}</small></div>`;card.dataset.engine427='1'}
function render(){ensureCss();const engine=window.__KAMIL_TICKET_ENGINE426__;if(!engine?.models?.length)return;for(const m of engine.models)paint(m);document.documentElement.dataset.ticketEngineUi427='1';window.__KAMIL_TICKET_ENGINE_UI427__={version:VERSION,healthy:true,count:engine.models.length,at:Date.now()}}
function schedule(ms=220){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installTicketEngineUi427(){if(bound)return;bound=true;ensureCss();for(const ev of ['kamil:view-change','kamil:ticket-refresh397-done','kamil:ticket-price374-updated'])window.addEventListener(ev,()=>schedule(450));const host=document.querySelector('#ticketIntelView');if(host)new MutationObserver(()=>schedule(320)).observe(host,{childList:true,subtree:true});schedule(1800);setInterval(()=>schedule(0),5000)}
