import {cloudClient,session} from './cloud.js';
import {loadTicketCloud660} from './ticketCloud660.js';
import {formModal,modal,h} from './utils.js';
const VERSION=398,N=v=>Number(v||0);let bound=false,timer=0;
async function ctx(){return{c:await cloudClient(),sess:await session()}}
const safeUrl=v=>{try{const u=new URL(String(v||''));return u.protocol==='https:'?u.toString():null}catch{return null}};
async function addManualSnapshot(id){const cloud=await loadTicketCloud660();if(!cloud?.ok)throw cloud?.error||new Error('Ticket cloud není dostupný');const r=(cloud.inventory||[]).find(x=>String(x.id)===String(id));if(!r)return;const qty=Math.max(1,N(r.qty)||1),hasRow=!!String(r.row_label||'').trim(),data=await formModal(`Tržní cena · ${h(r.event_name||'Vstupenka')}`,`<label class="field"><span>Tržní cena za 1 ks (Kč)</span><input name="price" type="number" min="1" step="1" required placeholder="např. 2490"></label><label class="field"><span>Zdroj / URL (volitelné)</span><input name="url" type="url" placeholder="https://..."></label><label class="field"><span><input name="sameSection" type="checkbox" checked> Cena je ze stejného sektoru ${h(r.section||'')}</span></label>${hasRow?`<label class="field"><span><input name="sameRow" type="checkbox"> Cena je i ze stejné řady ${h(r.row_label)}</span></label>`:''}${qty>1?`<label class="field"><span><input name="qtyMatched" type="checkbox"> Nabídka potvrzuje ${qty} ks společně / vedle sebe</span></label>`:''}<p class="muted">Ruční snapshot je bezpečný fallback, když Viagogo/StubHub blokují serverové čtení. Kamil OS ho označí jako ručně potvrzený a nebude předstírat automatický zdroj.</p>`,{submitLabel:'Uložit cenu'});if(!data)return;const price=N(data.price),sameSection=!!data.sameSection,sameRow=hasRow&&!!data.sameRow,qtyMatched=qty===1?true:!!data.qtyMatched,url=safeUrl(data.url);if(price<=0){await modal('Neplatná cena','<p>Zadej cenu větší než 0 Kč.</p>',[{label:'OK',value:null,primary:true}]);return}const {c,sess}=await ctx();if(!c||!sess)throw new Error('Cloud session chybí.');const confidence=sameRow?'manual-row-confirmed':sameSection?'manual-section-confirmed':'manual-event-confirmed',row={user_id:sess.user.id,ticket_id:r.id,checked_at:new Date().toISOString(),market_price_czk:Math.round(price),median_price_czk:Math.round(price),p25_price_czk:Math.round(price),p75_price_czk:Math.round(price),top_prices_czk:[Math.round(price)],competitor_count:1,same_section_count:sameSection?1:0,same_row_count:sameRow?1:0,quantity_required:qty,quantity_matched:qtyMatched,supply_pct:null,confidence,resolved_url:url,recommendation_code:'HOLD',recommendation_label:'RUČNĚ OVĚŘENO',recommendation_reason:`Ruční market snapshot: ${sameRow?'stejný sektor + řada':sameSection?'stejný sektor':'celá akce'}${qty>1?qtyMatched?`, ${qty} ks spolu potvrzeno`:`; ${qty} ks spolu nepotvrzeno`:''}.`,recommended_ask_czk:null,source_status:'ok',source_message:'Ruční market snapshot zadaný uživatelem.'};const saved=await c.from('ticket_market_snapshots').insert([row]);if(saved.error)throw saved.error;window.dispatchEvent(new CustomEvent('kamil:ticket-manual398-saved',{detail:{id:r.id,price:Math.round(price)}}));window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}));return row}
function wire(){const host=document.querySelector('#ticketIntelView');if(!host)return;for(const card of host.querySelectorAll('[data-inventory-card]')){if(card.dataset.manual398==='1')continue;card.dataset.manual398='1';const id=card.querySelector('[data-ticket-detail]')?.dataset.ticketDetail,actions=card.querySelector('.td331-ticket-actions');if(!id||!actions)continue;const b=document.createElement('button');b.type='button';b.className='td331-btn';b.dataset.manualMarket398='1';b.textContent='Zadat tržní cenu';b.addEventListener('click',async()=>{b.disabled=true;try{await addManualSnapshot(id);b.textContent='Cena uložena ✓'}catch(error){console.error('[ticket-manual398]',error);await modal('Uložení selhalo',`<p>${h(error?.message||String(error))}</p>`,[{label:'OK',value:null,primary:true}])}finally{setTimeout(()=>{b.disabled=false;b.textContent='Zadat tržní cenu'},1200)}});actions.appendChild(b)}}
function schedule(ms=100){clearTimeout(timer);timer=setTimeout(wire,ms)}
export function installTicketManualMarket398(){if(bound)return;bound=true;const host=document.querySelector('#ticketIntelView');if(host)new MutationObserver(()=>schedule()).observe(host,{childList:true,subtree:true});window.addEventListener('kamil:view-change',e=>{if(e.detail==='tickets')schedule(150)});schedule();setTimeout(()=>schedule(),1200);window.__KAMIL_TICKET_MANUAL_MARKET398__={version:VERSION,healthy:true,open:addManualSnapshot,refresh:wire}}
