import {cloudClient,session} from './cloud.js';
import {loadTicketCloud660} from './ticketCloud660.js';
import {formModal,modal,h} from './utils.js';
const VERSION=403,N=v=>Number(v||0);let bound=false,timer=0;
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const norm=s=>clean(String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' '));
const sectionNorm=s=>norm(String(s||'').replace(/\b(SECTION|SEKTOR|SEKCE|BLOCK|BLOK|TRIBUNE|TRIBUNA)\b/gi,' '));
const rowNorm=s=>norm(String(s||'').replace(/\b(ROW|RADA|ŘADA|REIHE)\b/gi,' '));
function parseNumber(raw){let x=String(raw||'').replace(/\s/g,'').replace(/[^0-9.,]/g,'');if(!x)return null;const c=x.lastIndexOf(','),d=x.lastIndexOf('.');if(c>d)x=x.replace(/\./g,'').replace(',','.');else x=x.replace(/,/g,'');const n=Number(x);return Number.isFinite(n)?n:null}
function currency(raw){const x=String(raw||'').toUpperCase();if(x.includes('KČ')||x.includes('CZK'))return'CZK';if(x.includes('€')||x.includes('EUR'))return'EUR';if(x.includes('£')||x.includes('GBP'))return'GBP';if(x.includes('$')||x.includes('USD'))return'USD';return null}
function prices(text){const s=String(text||''),out=[];for(const re of [/(CZK|Kč|€|EUR|£|GBP|US\$|USD|\$)\s*([0-9][0-9\s.,]*)/gi,/([0-9][0-9\s.,]*)\s*(CZK|Kč|€|EUR|£|GBP|US\$|USD|\$)/gi]){let m;while((m=re.exec(s))){const left=/\d/.test(m[1]),value=parseNumber(left?m[1]:m[2]),ccy=currency(left?m[2]:m[1]);if(value&&ccy&&value>=5&&value<=200000)out.push({value,ccy,index:m.index,raw:m[0]})}}return out}
async function toCzk(p){if(p.ccy==='CZK')return Math.round(p.value);try{const r=await fetch(`https://api.frankfurter.app/latest?from=${encodeURIComponent(p.ccy)}&to=CZK`,{headers:{accept:'application/json'}});if(!r.ok)return null;const j=await r.json(),fx=Number(j?.rates?.CZK);return fx?Math.round(p.value*fx):null}catch{return null}}
function evidence(text,r){const n=norm(text),section=sectionNorm(r.section),row=rowNorm(r.row_label),qty=Math.max(1,N(r.qty)||1),sectionMatched=!!section&&n.includes(section),rowMatched=!!row&&n.includes(row),qtyMatched=qty===1||[new RegExp(`\\b${qty}\\s+(?:TICKETS?|SEATS?|MISTA|MÍSTA|KS)\\b`,'i'),new RegExp(`(?:QUANTITY|QTY|POCET|POČET)[^0-9]{0,8}${qty}\\b`,'i'),/(SEATS TOGETHER|TICKETS TOGETHER|VEDLE SEBE)/i].some(x=>x.test(text));return{sectionMatched,rowMatched,qtyMatched,qty}}
function choosePrice(list,text,r){if(!list.length)return null;const sec=sectionNorm(r.section),row=rowNorm(r.row_label),n=norm(text),scored=list.map(p=>{const lo=Math.max(0,p.index-500),hi=Math.min(text.length,p.index+700),chunk=norm(text.slice(lo,hi));let score=0;if(sec&&chunk.includes(sec))score+=8;if(row&&chunk.includes(row))score+=8;if(/TICKET|SEAT|PRICE|CENA|TOTAL|EACH|ZA KS/.test(chunk))score+=3;return{...p,score}}).sort((a,b)=>b.score-a.score||a.value-b.value);return scored[0]||null}
async function saveSnapshot(r,priceCzk,ev,sourceText){const c=await cloudClient(),sess=await session();if(!c||!sess)throw new Error('Cloud session chybí.');const confidence=ev.rowMatched?'clipboard-row-confirmed':ev.sectionMatched?'clipboard-section-confirmed':'clipboard-event-confirmed',row={user_id:sess.user.id,ticket_id:r.id,checked_at:new Date().toISOString(),market_price_czk:priceCzk,median_price_czk:priceCzk,p25_price_czk:priceCzk,p75_price_czk:priceCzk,top_prices_czk:[priceCzk],competitor_count:1,same_section_count:ev.sectionMatched?1:0,same_row_count:ev.rowMatched?1:0,quantity_required:ev.qty,quantity_matched:ev.qtyMatched,supply_pct:null,confidence,resolved_url:null,recommendation_code:'HOLD',recommendation_label:'SCHRÁNKA',recommendation_reason:`Import ze schránky: ${ev.rowMatched?'stejný sektor + řada':ev.sectionMatched?'stejný sektor':'celá akce'}${ev.qty>1?ev.qtyMatched?`, ${ev.qty} ks spolu potvrzeno`:`; ${ev.qty} ks spolu nepotvrzeno`:''}.`,recommended_ask_czk:null,source_status:'ok',source_message:`Cena načtena z textu zkopírovaného z marketplace (${sourceText.includes('StubHub')?'StubHub':sourceText.includes('viagogo')||sourceText.includes('Viagogo')?'Viagogo':'ruční clipboard import'}).`};const out=await c.from('ticket_market_snapshots').insert([row]);if(out.error)throw out.error;return row}
async function clipboardText(){try{return await navigator.clipboard.readText()}catch{return''}}
async function open(id){const cloud=await loadTicketCloud660();if(!cloud?.ok)throw cloud?.error||new Error('Ticket cloud není dostupný');const r=(cloud.inventory||[]).find(x=>String(x.id)===String(id));if(!r)return;let text=await clipboardText();if(!text){const data=await formModal(`Vložit trh · ${h(r.event_name||'Vstupenka')}`,`<label class="field"><span>Vlož text z Viagogo / StubHub</span><textarea name="text" rows="12" required placeholder="Zkopíruj listing nebo stránku trhu a vlož sem text..."></textarea></label><p class="muted">OS403 zkusí sám najít cenu a ověřit sektor, řadu i počet kusů.</p>`,{submitLabel:'Rozpoznat cenu'});if(!data)return;text=String(data.text||'')}if(!clean(text)){await modal('Schránka je prázdná','<p>Nejdřív na marketplace označ a zkopíruj listing nebo text stránky.</p>',[{label:'OK',value:null,primary:true}]);return}const ps=prices(text),chosen=choosePrice(ps,text,r);if(!chosen){await modal('Cena nenalezena','<p>V textu jsem nenašel rozpoznatelnou cenu v CZK/EUR/USD/GBP. Zkopíruj větší část listingu.</p>',[{label:'OK',value:null,primary:true}]);return}const priceCzk=await toCzk(chosen);if(!priceCzk)throw new Error('Nepodařil se převod ceny do Kč.');const ev=evidence(text,r),confirm=await formModal(`Potvrdit cenu · ${h(r.event_name||'Vstupenka')}`,`<div class="field"><span>Nalezená cena</span><strong style="font-size:22px">${priceCzk.toLocaleString('cs-CZ')} Kč / ks</strong></div><p class="muted">${ev.sectionMatched?'Sektor potvrzen ✓':'Sektor v textu nepotvrzen'} · ${r.row_label?(ev.rowMatched?'řada potvrzena ✓':'řada nepotvrzena'):'řada není zadaná'} · ${ev.qty>1?(ev.qtyMatched?`${ev.qty} ks spolu ✓`:`${ev.qty} ks spolu nepotvrzeno`):'1 ks'}</p><label class="field"><span>Pokud cena není správná, oprav ji</span><input name="price" type="number" min="1" step="1" value="${priceCzk}"></label>`,{submitLabel:'Uložit snapshot'});if(!confirm)return;const finalPrice=Math.round(N(confirm.price)||priceCzk);await saveSnapshot(r,finalPrice,ev,text);window.dispatchEvent(new CustomEvent('kamil:ticket-clipboard403-saved',{detail:{id:r.id,price:finalPrice}}));window.dispatchEvent(new CustomEvent('kamil:view-change',{detail:'tickets'}));return{price:finalPrice,evidence:ev}}
function wire(){const host=document.querySelector('#ticketIntelView');if(!host)return;for(const card of host.querySelectorAll('[data-inventory-card]')){if(card.dataset.clipboard403==='1')continue;card.dataset.clipboard403='1';const id=card.querySelector('[data-ticket-detail]')?.dataset.ticketDetail,actions=card.querySelector('.td331-ticket-actions');if(!id||!actions)continue;const b=document.createElement('button');b.type='button';b.className='td331-btn';b.dataset.clipboardMarket403='1';b.textContent='Načíst ze schránky';b.title='Zkopíruj listing z Viagogo/StubHub a klikni sem';b.addEventListener('click',async()=>{b.disabled=true;const old=b.textContent;b.textContent='Čtu schránku…';try{await open(id);b.textContent='Cena uložena ✓'}catch(error){console.error('[ticket-clipboard403]',error);await modal('Import selhal',`<p>${h(error?.message||String(error))}</p>`,[{label:'OK',value:null,primary:true}])}finally{setTimeout(()=>{b.disabled=false;b.textContent=old},1200)}});actions.appendChild(b)}}
function schedule(ms=120){clearTimeout(timer);timer=setTimeout(wire,ms)}
export function installTicketClipboardMarket403(){if(bound)return;bound=true;const host=document.querySelector('#ticketIntelView');if(host)new MutationObserver(()=>schedule()).observe(host,{childList:true,subtree:true});for(const ev of ['kamil:view-change','kamil:ticket-refresh397-done','kamil:ticket-manual398-saved'])window.addEventListener(ev,()=>schedule(160));schedule();setTimeout(()=>schedule(),1000);window.__KAMIL_TICKET_CLIPBOARD403__={version:VERSION,healthy:true,open,refresh:wire}}
