import {cloudClient,session} from './cloud.js';
import {loadTicketCloud660} from './ticketCloud660.js';

const VERSION=440,N=v=>Number(v||0),ACTIVE=new Set(['LISTED','NOT_LISTED']),SOLD=new Set(['SOLD_UNDELIVERED','SOLD_WAITING_PAYMENT','PAYOUT_RECEIVED','PAID']);let bound=false,timer=0,busy=false;
const round=v=>Number.isFinite(Number(v))?Math.round(Number(v)*100)/100:null;
const eventKey=s=>String(s||'').split(' - ')[0].trim().toLowerCase();
async function ctx(){const c=await cloudClient(),s=await session();if(!c||!s)throw new Error('Cloud session chybí.');return{c,s}}
function stateRows(){const pred=window.__KAMIL_TICKET_PREDICT433__,cmd=window.__KAMIL_TICKET_COMMANDER435__,cmp=window.__KAMIL_TICKET_COMPARABLE437__,risk=window.__KAMIL_TICKET_RISK438__,c31=window.__KAMIL_TICKET_COMMANDER439__;if(!pred?.models?.length||!cmd?.rows?.length)return[];const cmdBy=new Map(cmd.rows.map(x=>[String(x.r.id),x])),fitBy=new Map((c31?.rows||[]).map(x=>[String(x.r.id),x])),cmpBy=new Map((cmp?.rows||[]).map(x=>[String(x.r.id),x]));return pred.models.filter(m=>ACTIVE.has(String(m.r.market_status||''))).map(m=>{const c=cmdBy.get(String(m.r.id)),f=fitBy.get(String(m.r.id)),co=cmpBy.get(String(m.r.id)),grp=(risk?.groups||[]).find(g=>eventKey(g.name)===eventKey(m.r.event_name));return{ticket_id:String(m.r.id),event_name:m.r.event_name||null,event_date:m.r.event_date||null,market_status:m.r.market_status||null,action_code:f?.finalCode||c?.commander?.code||m.code||null,action_reason:f?.reason||c?.commander?.reason||m.why||null,market_price_czk:round(m.market),ask_price_czk:round(m.r.ask_each_czk),recommended_price_czk:round(c?.commander?.optPrice||m.predict?.opt?.price||m.price),expected_value_czk:round(c?.commander?.exitEv||m.predict?.opt?.ev),hold_48h_ev_czk:round(c?.commander?.holdEv),sell_probability_24h:round(m.predict?.p24),sell_probability_72h:round(m.predict?.p72),sell_probability_7d:round(m.predict?.p7),confidence_score:round(m.confidence),liquidity_score:round(m.liquidity?.score),sell_pressure_score:round(m.pressure),demand_score:round(m.predict?.demand),risk_adjusted_roi:round(m.predict?.riskAdjustedRoi),portfolio_fit:round(f?.portfolioFit),comparable_roi:round(co?.hist?.roi),event_concentration_pct:round(grp?.share),model_version:'439.0'}})}
function materiallyChanged(a,b){if(!a)return true;if(String(a.action_code||'')!==String(b.action_code||''))return true;const pa=N(a.recommended_price_czk),pb=N(b.recommended_price_czk);if(pa&&pb&&Math.abs(pa-pb)/Math.max(pa,1)>=.03)return true;const ea=N(a.expected_value_czk),eb=N(b.expected_value_czk);if(Math.abs(ea-eb)>=250)return true;return false}
async function latestMap(c,userId,ids){if(!ids.length)return new Map();const {data,error}=await c.from('ticket_decision_snapshots').select('*').eq('user_id',userId).in('ticket_id',ids).order('created_at',{ascending:false}).limit(Math.max(100,ids.length*4));if(error)throw error;const map=new Map();for(const r of data||[])if(!map.has(String(r.ticket_id)))map.set(String(r.ticket_id),r);return map}
async function persist(){if(busy)return;const rows=stateRows();if(!rows.length)return;busy=true;try{const {c,s}=await ctx(),latest=await latestMap(c,s.user.id,rows.map(r=>r.ticket_id)),now=Date.now(),inserts=[];for(const r of rows){const prev=latest.get(r.ticket_id),age=prev?now-Date.parse(prev.created_at||0):Infinity;if(age<6*36e5&&!materiallyChanged(prev,r))continue;inserts.push({...r,user_id:s.user.id})}if(inserts.length){const {error}=await c.from('ticket_decision_snapshots').insert(inserts);if(error)throw error}await resolveOutcomes(c,s.user.id);window.__KAMIL_TICKET_JOURNAL440__={version:VERSION,healthy:true,written:inserts.length,active:rows.length,at:Date.now()};document.documentElement.dataset.ticketJournal440='1';window.dispatchEvent(new CustomEvent('kamil:ticket-journal440-updated',{detail:{written:inserts.length}}))}catch(e){window.__KAMIL_TICKET_JOURNAL440__={version:VERSION,healthy:false,error:String(e?.message||e),at:Date.now()}}finally{busy=false}}
async function resolveOutcomes(c,userId){const cloud=await loadTicketCloud660();if(!cloud?.ok)return;const sold=(cloud.inventory||[]).filter(r=>SOLD.has(String(r.market_status||'')));for(const r of sold){const actualSell=N(r.sell_each_czk)||(N(r.sell_total_czk)/Math.max(1,N(r.qty)||1)),actualProfit=N(r.sell_total_czk)-N(r.buy_total_czk);const {error}=await c.from('ticket_decision_snapshots').update({resolved_at:r.sold_at||r.updated_at||new Date().toISOString(),outcome_status:r.market_status,actual_sell_price_czk:actualSell||null,actual_profit_czk:Number.isFinite(actualProfit)?actualProfit:null}).eq('user_id',userId).eq('ticket_id',String(r.id)).is('resolved_at',null);if(error)throw error}}
async function stats(){try{const {c,s}=await ctx();const {data,error}=await c.from('ticket_decision_snapshots').select('ticket_id,created_at,resolved_at,action_code,expected_value_czk,sell_probability_72h,actual_profit_czk').eq('user_id',s.user.id).order('created_at',{ascending:false}).limit(500);if(error)throw error;const all=data||[],resolved=all.filter(x=>x.resolved_at),tickets=new Set(all.map(x=>x.ticket_id)).size,avgP=resolved.length?resolved.reduce((a,x)=>a+N(x.sell_probability_72h),0)/resolved.length:0,avgProfit=resolved.length?resolved.reduce((a,x)=>a+N(x.actual_profit_czk),0)/resolved.length:0;window.__KAMIL_TICKET_JOURNAL440_STATS__={version:VERSION,total:all.length,tickets,resolved:resolved.length,avgP72:avgP,avgActualProfit:avgProfit,at:Date.now()};paint()}catch{}}
function ensureCss(){if(document.querySelector('style[data-j440]'))return;const s=document.createElement('style');s.dataset.j440='1';s.textContent=`#ticketIntelView .j440{margin:8px 0 0;padding:9px 11px;border:1px solid #294457;border-radius:10px;background:#0a1923;color:#d9e7f1;display:grid;grid-template-columns:1.4fr repeat(3,1fr);gap:8px}.j440 span{display:block;font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#7694aa}.j440 b{display:block;margin-top:3px;font-size:11px}.j440 small{display:block;margin-top:2px;color:#768b9b;font-size:8.5px}@media(max-width:800px){#ticketIntelView .j440{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function paint(){ensureCss();const host=document.querySelector('#ticketIntelView .hub421-body')||document.querySelector('#ticketIntelView .td331');if(!host)return;let box=document.querySelector('#ticketIntelView [data-journal440]');if(!box){box=document.createElement('section');box.dataset.journal440='1';box.className='j440';host.appendChild(box)}const st=window.__KAMIL_TICKET_JOURNAL440_STATS__||{},run=window.__KAMIL_TICKET_JOURNAL440__||{};box.innerHTML=`<div><span>DECISION JOURNAL · OS440</span><b>${run.healthy===false?'CHYBA':'AKTIVNÍ'}</b><small>Ukládá rozhodnutí jen při změně nebo po 6 h; nic nemění na marketplace.</small></div><div><span>SNAPSHOTY</span><b>${st.total??'—'}</b><small>${st.tickets??0} pozic</small></div><div><span>UZAVŘENO</span><b>${st.resolved??'—'}</b><small>pro kalibraci modelu</small></div><div><span>POSLEDNÍ ZÁPIS</span><b>${run.written??0}</b><small>nových snapshotů</small></div>`}
function schedule(ms=900){clearTimeout(timer);timer=setTimeout(async()=>{paint();await persist();await stats()},ms)}
export function installTicketDecisionJournal440(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-commander439-updated','kamil:ticket-commander435-updated','kamil:ticket-reconcile412-saved','kamil:ticket-sale408-saved'])window.addEventListener(ev,()=>schedule());schedule(5000);setInterval(()=>schedule(0),6*36e5)}
