const VERSION=445,N=v=>Number(v||0),clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));let bound=false,timer=0;
const median=a=>{const x=a.filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return null;const i=Math.floor(x.length/2);return x.length%2?x[i]:(x[i-1]+x[i])/2};
function sourceName(s={}){return String(s.marketplace||s.source||s.source_name||s.provider||'unknown').toLowerCase()}
function price(s={}){return N(s.market_price_czk)||N(s.lowest_price_czk)||N(s.price_czk)||N(s.current_price_czk)||N(s.top_prices_czk?.[0])||0}
function rel(source,history){const h=history.filter(s=>sourceName(s)===source),prices=h.map(price).filter(x=>x>0);if(prices.length<2)return 58;const med=median(prices),mad=median(prices.map(x=>Math.abs(x-med)))||0,noise=med?mad/med:1,depth=Math.min(1,prices.length/8);return clamp(88-noise*180+depth*12,35,96)}
function one(m){const hist=(m.history||[]).filter(Boolean),latest=m.latest?[m.latest]:[],candidates=[...hist.slice(0,24),...latest].filter(s=>price(s)>0),by=new Map();for(const s of candidates){const n=sourceName(s);if(!by.has(n))by.set(n,s)}const sources=[...by.entries()].map(([name,s])=>({name,s,p:price(s),reliability:rel(name,hist)})),med=median(sources.map(x=>x.p)),valid=sources.map(x=>({...x,deviation:med?Math.abs(x.p/med-1):0,anomaly:med?Math.abs(x.p/med-1)>.32:false})),clean=valid.filter(x=>!x.anomaly),pool=clean.length?clean:valid,totalW=pool.reduce((a,x)=>a+x.reliability,0),consensus=totalW?pool.reduce((a,x)=>a+x.p*x.reliability,0)/totalW:(m.market||0),spread=pool.length>1&&consensus?Math.max(...pool.map(x=>x.p))/Math.min(...pool.map(x=>x.p))-1:0,confidence=clamp(45+pool.length*11-spread*80+(pool.reduce((a,x)=>a+x.reliability,0)/(Math.max(1,pool.length))-.5*0)*.22,25,96);return{...m,consensus:{price:Math.round(consensus),sources:valid,usable:pool.length,anomalies:valid.filter(x=>x.anomaly).length,spread,confidence}}}
function build(){const eng=window.__KAMIL_TICKET_ENGINE426__;if(!eng?.models?.length)return null;const rows=eng.models.map(one),anomalies=rows.reduce((a,x)=>a+x.consensus.anomalies,0),multi=rows.filter(x=>x.consensus.usable>=2).length;return{rows,anomalies,multi}}
function ensureCss(){if(document.querySelector('style[data-cs445]'))return;const s=document.createElement('style');s.dataset.cs445='1';s.textContent=`#ticketIntelView .cs445{margin:0 0 12px;border:1px solid #314d62;border-radius:12px;background:#081722;color:#ddecf5;padding:10px 11px}.cs445-grid{display:grid;grid-template-columns:1.5fr repeat(4,1fr);gap:8px}.cs445 span{display:block;font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#7898ae}.cs445 b{display:block;margin-top:3px;font-size:12px}.cs445 small{display:block;margin-top:2px;color:#7890a2;font-size:8.5px}.cs445-good{color:#8bd8ad}.cs445-warn{color:#efc17c}@media(max-width:850px){.cs445-grid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function paint(m){ensureCss();const host=document.querySelector('#ticketIntelView .td331');if(!host)return;let box=host.querySelector('[data-cs445]');if(!box){box=document.createElement('section');box.dataset.cs445='1';box.className='cs445';const q=host.querySelector('[data-dq444]');q?.insertAdjacentElement('afterend',box);if(!box.isConnected)host.appendChild(box)}const avg=m.rows.length?m.rows.reduce((a,x)=>a+x.consensus.confidence,0)/m.rows.length:0,src=m.rows.reduce((a,x)=>a+x.consensus.usable,0);box.innerHTML=`<div class="cs445-grid"><div><span>SOURCE CONSENSUS · OS445</span><b>${Math.round(avg)}/100 consensus confidence</b><small>Weighted consensus používá více market zdrojů; outlier >32 % od mediánu se odfiltruje z ceny.</small></div><div><span>MULTI-SOURCE</span><b class="cs445-good">${m.multi}/${m.rows.length}</b></div><div><span>USABLE SOURCES</span><b>${src}</b></div><div><span>ANOMALIES</span><b class="${m.anomalies?'cs445-warn':'cs445-good'}">${m.anomalies}</b></div><div><span>FALLBACK</span><b>${m.multi<m.rows.length?'ENABLED':'NOT NEEDED'}</b></div></div>`}
function refresh(){const m=build();if(!m)return;window.__KAMIL_TICKET_CONSENSUS445__={version:VERSION,healthy:true,...m,at:Date.now()};document.documentElement.dataset.ticketConsensus445='1';paint(m);window.dispatchEvent(new CustomEvent('kamil:ticket-consensus445-updated',{detail:{anomalies:m.anomalies,multi:m.multi}}))}
function schedule(ms=650){clearTimeout(timer);timer=setTimeout(refresh,ms)}
export function installTicketConsensus445(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-engine426-updated','kamil:ticket-refresh397-done'])window.addEventListener(ev,()=>schedule());schedule(6800);setInterval(()=>schedule(0),30000)}