import {cloudClient,session} from './cloud.js';

const VERSION=449;let bound=false,busy=false,timer=0;const N=v=>Number(v||0);
async function ctx(){const c=await cloudClient(),s=await session();if(!c||!s)throw new Error('Cloud session chybí.');return{c,s}}
const actionKey=(ticketId,code)=>`${String(ticketId)}|${String(code||'')}`;
function latestByAction(rows){const map=new Map();for(const r of rows||[]){const k=actionKey(r.ticket_id,r.recommendation_code);if(!map.has(k))map.set(k,r)}return map}
function commanderMap(){const m=new Map();for(const a of window.__KAMIL_TICKET_COMMANDER448__?.actions||[]){const k=actionKey(a.id,a.code);if(!m.has(k))m.set(k,a)}return m}
function ensureCss(){if(document.querySelector('style[data-ex449]'))return;const s=document.createElement('style');s.dataset.ex449='1';s.textContent=`#ticketIntelView .ex449-controls{grid-column:2/-1;display:flex;gap:6px;align-items:center;flex-wrap:wrap;margin-top:3px}.ex449-btn{border:1px solid #35566b;border-radius:7px;background:#0c2230;color:#cfe0ea;padding:4px 7px;font-size:8px;font-weight:900;letter-spacing:.04em;cursor:pointer}.ex449-btn:hover{background:#123146}.ex449-btn:disabled{opacity:.45;cursor:default}.ex449-status{display:inline-flex;padding:3px 7px;border-radius:999px;border:1px solid #35566b;font-size:8px;font-weight:900}.ex449-confirmed{color:#efc17c}.ex449-done{color:#8bd8ad}.ex449-ignored,.ex449-cancelled{color:#8fa1ad}.ex449-summary{margin:0 0 12px;padding:8px 11px;border:1px solid #294657;border-radius:10px;background:#0a1923;color:#dce9f2;display:flex;gap:18px;flex-wrap:wrap}.ex449-summary span{font-size:8px;color:#7898ad;text-transform:uppercase;font-weight:900}.ex449-summary b{margin-left:4px;font-size:10px}`;document.head.appendChild(s)}
function statusLabel(s){return s==='CONFIRMED'?'POTVRZENO':s==='DONE'?'HOTOVO':s==='IGNORED'?'IGNOROVÁNO':s==='CANCELLED'?'ZRUŠENO':'DOPORUČENO'}
function decorate(rows){ensureCss();const latest=latestByAction(rows),cmd=commanderMap(),box=document.querySelector('#ticketIntelView [data-c448]');if(!box)return;for(const row of box.querySelectorAll('[data-c448-action-id]')){const id=row.dataset.c448ActionId,code=row.dataset.c448ActionCode||'',k=actionKey(id,code),a=cmd.get(k),st=latest.get(k);let ctrl=row.querySelector('.ex449-controls');if(!ctrl){ctrl=document.createElement('div');ctrl.className='ex449-controls';row.appendChild(ctrl)}const status=st?.action_status||'RECOMMENDED';ctrl.innerHTML=`<span class="ex449-status ex449-${status.toLowerCase()}">${statusLabel(status)}</span><button class="ex449-btn" data-ex449="CONFIRMED" ${status==='DONE'?'disabled':''}>Potvrdit</button><button class="ex449-btn" data-ex449="DONE">Hotovo</button><button class="ex449-btn" data-ex449="IGNORED" ${status==='DONE'?'disabled':''}>Ignorovat</button>`;for(const btn of ctrl.querySelectorAll('[data-ex449]'))btn.addEventListener('click',()=>save(id,code,btn.dataset.ex449,a,st,btn));}
let sum=document.querySelector('#ticketIntelView [data-ex449-summary]');if(!sum){sum=document.createElement('div');sum.dataset.ex449Summary='1';sum.className='ex449-summary';box.insertAdjacentElement('afterend',sum)}const vals=[...latest.values()],confirmed=vals.filter(x=>x.action_status==='CONFIRMED').length,done=vals.filter(x=>x.action_status==='DONE').length,ignored=vals.filter(x=>x.action_status==='IGNORED').length;sum.innerHTML=`<span>EXECUTION</span><span>potvrzeno <b>${confirmed}</b></span><span>hotovo <b>${done}</b></span><span>ignorováno <b>${ignored}</b></span><span>sledovaných akcí <b>${vals.length}</b></span>`}
async function save(ticketId,code,status,a,current,btn){if(busy)return;busy=true;btn.disabled=true;try{const {c,s}=await ctx(),now=new Date().toISOString(),payload={user_id:s.user.id,ticket_id:String(ticketId),recommendation_code:code,recommendation_reason:a?.reason||null,recommended_price_czk:N(a?.recommendedPrice)||null,financial_impact_czk:N(a?.impact)||null,action_status:status,acted_at:status==='CONFIRMED'||status==='DONE'||status==='IGNORED'||status==='CANCELLED'?now:null,model_version:'449'};let error;if(current?.id){({error}=await c.from('ticket_action_executions').update(payload).eq('id',current.id).eq('user_id',s.user.id))}else{({error}=await c.from('ticket_action_executions').insert(payload))}if(error)throw error;window.dispatchEvent(new CustomEvent('kamil:ticket-action449-saved',{detail:{ticketId,code,status}}));}catch(e){console.error('[ticket449] save failed',e)}finally{busy=false;btn.disabled=false;schedule(100)}}
async function refresh(){if(busy)return;busy=true;try{const {c,s}=await ctx();const {data,error}=await c.from('ticket_action_executions').select('id,ticket_id,created_at,recommendation_code,recommendation_reason,recommended_price_czk,action_status,acted_at,actual_price_czk,financial_impact_czk,due_at,snoozed_until,ignore_reason,note,next_check_at').eq('user_id',s.user.id).order('created_at',{ascending:false}).limit(500);if(error)throw error;window.__KAMIL_TICKET_EXECUTION449__={version:VERSION,healthy:true,rows:data||[],at:Date.now()};document.documentElement.dataset.ticketExecution449='1';decorate(data||[]);window.dispatchEvent(new CustomEvent('kamil:ticket-execution449-updated',{detail:{count:(data||[]).length}}))}catch(e){window.__KAMIL_TICKET_EXECUTION449__={version:VERSION,healthy:false,error:String(e?.message||e),at:Date.now()}}finally{busy=false}}
function schedule(ms=500){clearTimeout(timer);timer=setTimeout(refresh,ms)}
export function installTicketActionExecution449(){if(bound)return;bound=true;for(const ev of ['kamil:view-change','kamil:ticket-commander448-rendered','kamil:ticket-action449-saved','kamil:ticket-commander465-updated'])window.addEventListener(ev,()=>schedule());schedule(9800);setInterval(()=>schedule(0),5*60*1000)}
