import {store} from './state.js';
import {h,qs} from './utils.js';
import {todayBrain34} from './todayBrain34.js';
import {decisionCenter36,recordDecisionMemory36} from './decisionCenter36.js';

const id='todayBrain34Host';let queued=false;
const targetLabel=t=>t==='director'?'Director Mode':t==='waiting'?'Waiting For':t==='money'?'Peníze':t==='tickets'?'Vstupenky':t==='home'?'Domov':'Otevřít';
const czk=v=>Number.isFinite(Number(v))&&Number(v)>0?`${Math.round(Number(v)).toLocaleString('cs-CZ')} Kč`:null;
function openTarget(t){if(t==='director'){window.dispatchEvent(new CustomEvent('kamil:director-open'));return}if(t==='waiting'){window.dispatchEvent(new CustomEvent('kamil:waiting-open'));return}window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:t||'today'}))}
function remember(id,status){const c=decisionCenter36(store.get()),row=c.rows.find(x=>x.id===id);if(!row)return;store.mutate(`Decision ${status}: ${row.title}`,s=>recordDecisionMemory36(s,row,status));}
function centerMeta(x){const parts=[x.urgency,x.evidence];if(czk(x.impactCzk))parts.push(`impact ${czk(x.impactCzk)}`);if(x.potentialGrossCzk!==null&&x.potentialGrossCzk!==undefined)parts.push(`hrubý rozdíl ${Math.round(x.potentialGrossCzk).toLocaleString('cs-CZ')} Kč`);if(x.memory?.status==='SNOOZED')parts.push('ODLOŽENO DO ZÍTŘKA');return parts.filter(Boolean).join(' · ')}
function centerHtml(c){return `<div class="card brain34-card today-brain34" data-decision-center36><div class="card-head"><div><div class="eyebrow">DECISION CENTER / 36.1</div><h2>${c.rows.length?'Co udělat s penězi a vstupenkami teď':'Teď není potřeba žádný zásah'}</h2><p class="muted">Decision Memory si pamatuje jen tvoje explicitní rozhodnutí. Hotovo zmizí, Odložit stáhne prioritu na 24 hodin, Ignorovat položku schová.</p></div><span class="status ${c.counts.critical?'bad':'good'}">${c.counts.critical} urgentní</span></div><div class="metric-strip"><div class="metric"><span>XTB</span><b>${c.counts.xtb}</b></div><div class="metric"><span>Vstupenky</span><b>${c.counts.tickets}</b></div><div class="metric"><span>Viditelný impact</span><b>${c.counts.visibleImpactCzk?Math.round(c.counts.visibleImpactCzk).toLocaleString('cs-CZ')+' Kč':'—'}</b></div><div class="metric"><span>Decision Memory</span><b>${c.counts.memory}</b></div></div><div class="brain34-list">${c.rows.map(x=>`<div class="brain34-row"><div style="display:flex;gap:10px;align-items:flex-start"><span class="rank34">${x.rank}</span><div><b>${h(x.title)}</b><small><strong>${h(centerMeta(x))}</strong><br>${h(x.reason)}${x.detail?` · ${h(x.detail)}`:''}<br><strong>Další krok:</strong> ${h(x.nextStep)}</small></div></div><div class="brain34-actions"><span class="status ${h(x.tone)}">${x.priority}</span><button class="btn" data-center36-target="${h(x.target)}">${h(targetLabel(x.target))}</button><button class="btn" data-memory36="DONE" data-memory36-id="${h(x.id)}">Hotovo</button><button class="btn" data-memory36="SNOOZED" data-memory36-id="${h(x.id)}">Odložit</button><button class="btn" data-memory36="IGNORED" data-memory36-id="${h(x.id)}">Ignorovat</button></div></div>`).join('')||'<div class="empty success-empty">Žádná konkrétní investiční ani ticketová akce teď není dost urgentní.</div>'}</div><div class="decision-note">${h(c.note)}</div></div>`}
function render(){const view=qs('#todayView');if(!view?.querySelector('.view-head'))return;qs(`#${id}`,view)?.remove();const b=todayBrain34(store.get()),c=decisionCenter36(store.get()),host=document.createElement('div');host.id=id;host.innerHTML=`<div class="card brain34-card today-brain34"><div class="card-head"><div><div class="eyebrow">KAMIL OS DOPORUČUJE DNES / 35.0</div><h2>${b.rows.length?'Těchto pár věcí má dnes největší smysl.':'Dnes není nic kritického.'}</h2><p class="muted">Práce, follow-upy, vstupenky, investice i osobní termíny v jednom pořadí.</p></div><span class="status ${b.critical?'bad':'good'}">${b.critical} kritické</span></div><div class="brain34-list">${b.rows.map(x=>`<div class="brain34-row"><div style="display:flex;gap:10px;align-items:flex-start"><span class="rank34">${x.rank}</span><div><b>${h(x.title)}</b><small>${h(x.kind)} · ${h(x.reason)}</small></div></div><div class="brain34-actions"><span class="status ${h(x.tone)}">${x.priority}</span><button class="btn" data-today34-target="${h(x.target)}">${h(targetLabel(x.target))}</button></div></div>`).join('')||'<div class="empty success-empty">OS z uložených dat nevidí nic, co by dnes potřebovalo zásah.</div>'}</div><div class="decision-note">${h(b.note)}</div></div>${centerHtml(c)}`;const anchor=view.querySelector('.view-head');anchor?.insertAdjacentElement('afterend',host);host.querySelectorAll('[data-today34-target],[data-center36-target]').forEach(btn=>btn.addEventListener('click',()=>openTarget(btn.dataset.today34Target||btn.dataset.center36Target)));host.querySelectorAll('[data-memory36]').forEach(btn=>btn.addEventListener('click',()=>remember(btn.dataset.memory36Id,btn.dataset.memory36)))}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;render()})}
function start(){const view=qs('#todayView');if(view)new MutationObserver(()=>{if(!qs(`#${id}`,view))schedule()}).observe(view,{childList:true,subtree:false});store.subscribe(()=>{if(qs('#view-today')?.classList.contains('on'))schedule()});window.addEventListener('kamil:navigate',schedule);setTimeout(render,450)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
