import {store} from './state.js';
import {h,money,date,dayDiff,qs,qsa} from './utils.js';
import {recommendation,signals,feedback,attentionCount,netWorth} from './intelligence.js';
import {xtbBoard,ticketDecision,actionLabel,xtbIntelligenceAge,ticketIntelligenceAge} from './live24.js';
import {buildTodayDecisions,todayDecisionStats} from './today25.js';

const eventStart=e=>{const s=e?.start;if(s&&typeof s==='object')return s.dateTime||s.date||null;return s||e?.startTime||e?.date||e?.begin||e?.dtstart||null};
const activeProjects=s=>(s.projects||[]).filter(x=>!/hotov|archiv/i.test(x.status||''));
const openTasks=s=>(s.tasks||[]).filter(x=>x.status!=='HOTOVO').sort((a,b)=>{const ad=a.due?new Date(a.due).getTime():Infinity,bd=b.due?new Date(b.due).getTime():Infinity;return ad-bd});
const waitAge=x=>{const at=x.lastContactAt||x.updatedAt||x.createdAt;if(!at)return 0;return Math.max(0,Math.floor((Date.now()-new Date(at).getTime())/86400000))};
function navigate(target){if(['today','work','money','tickets','more'].includes(target))window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:target}));else{window.dispatchEvent(new CustomEvent('kamil:more',{detail:target}));window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:'more'}))}}
const openProject=id=>window.dispatchEvent(new CustomEvent('kamil:project',{detail:id}));
const openSignal=x=>{if(x?.type==='Projekt'&&x.id)openProject(x.id);else navigate(x?.target||'work')};
const openDecision=x=>{if(x?.kind==='Projekt'&&x.id)openProject(x.id);else navigate(x?.target||({money:'money',tickets:'tickets',inbox:'inbox',waiting:'waiting'}[x?.domain]||'work'))};
function taskMeta(t){if(!t.due)return h(t.area||'Bez termínu');const d=dayDiff(t.due),label=d<0?`po termínu ${Math.abs(d)} d`:d===0?'dnes':d===1?'zítra':`za ${d} d`;return `${h(t.area||'Úkol')} · ${label}`}
function eventMeta(e){const start=eventStart(e);if(!start)return h(e.location||e.source||'Kalendář');const d=new Date(start),time=Number.isNaN(d.getTime())?'':d.toLocaleTimeString('cs-CZ',{hour:'2-digit',minute:'2-digit'});return `${date(start)}${time?' · '+time:''}${e.location?' · '+h(e.location):''}`}
const decisionTone=x=>x.priority>=85?'bad':x.priority>=70?'warn':'good';
const decisionSource=x=>`${h(x.kind||x.domain)}${x.confidence!==undefined&&x.confidence!==null?` · confidence ${Math.round(Number(x.confidence)||0)} %`:''}${x.source?` · ${h(x.source)}`:''}`;

export function renderToday(){
 const s=store.get(),rec=recommendation(s),sig=signals(s),nw=netWorth(s),tasks=openTasks(s),urgentAll=tasks.filter(x=>x.due&&dayDiff(x.due)<=1),urgentTasks=urgentAll.slice(0,5),projects=activeProjects(s).slice(0,4);
 const decisions=buildTodayDecisions(s),decisionStats=todayDecisionStats(s,decisions);
 const events=[...(s.calendar?.events||[])].filter(e=>{const v=eventStart(e);return !v||new Date(v).getTime()>=Date.now()-3600000}).sort((a,b)=>new Date(eventStart(a)||'9999')-new Date(eventStart(b)||'9999')).slice(0,5);
 const ticketActions=[...(s.ticketBook?.items||[])].filter(x=>['HOLD','LISTED'].includes(x.workflow||'HOLD')).map(x=>({x,d:ticketDecision(x,s)})).filter(y=>y.d.priority>=60).sort((a,b)=>b.d.priority-a.d.priority).slice(0,4);
 const xtbActions=xtbBoard(s).filter(y=>y.d.priority>=60).slice(0,3),xtbLive=xtbIntelligenceAge(s),ticketLive=ticketIntelligenceAge(s);
 const waitingAll=[...(s.delegations||[])].filter(x=>(x.status||'WAITING')!=='DONE').sort((a,b)=>waitAge(b)-waitAge(a)),waiting=waitingAll.slice(0,5),doneToday=(s.audit||[]).filter(x=>x.label?.startsWith('Hotovo')&&new Date(x.at).toDateString()===new Date().toDateString()).length,inbox=(s.inbox||[]).filter(x=>x.status!=='DONE').length,nextSignals=sig.slice(1,4);
 qs('#todayView').innerHTML=`
  <div class="view-head"><div><div class="eyebrow">DNES / DECISION COMMAND CENTER</div><h1>${decisionStats.critical?'Nejdřív vyřeš kritická rozhodnutí.':'Co dnes opravdu stojí za pozornost'}</h1><p>Kamil OS skládá práci, projekty, XTB, vstupenky, čekání a Inbox do jedné prioritní fronty.</p></div><div class="view-head-stat"><b class="${decisionStats.critical?'bad':decisionStats.high?'warn':'good'}">${decisionStats.count}</b><span>hlavních rozhodnutí</span></div></div>
  <div class="card today-decision-card"><div class="card-head"><div><div class="eyebrow">TOP 5 ROZHODNUTÍ</div><h2>Jedna fronta místo pěti aplikací</h2></div><span class="status ${decisionStats.critical?'bad':decisionStats.high?'warn':'good'}">${decisionStats.critical?`${decisionStats.critical} kritické`:decisionStats.high?`${decisionStats.high} důležité`:'pod kontrolou'}</span></div>
   <div class="today-decision-list">${decisions.map((x,i)=>`<div class="today-decision-row"><div class="today-rank ${decisionTone(x)}">${x.rank}</div><div class="today-decision-main"><div class="today-decision-top"><b>${h(x.title)}</b><span class="status ${decisionTone(x)}">${Math.round(x.priority)}</span></div><span>${h(x.reason||'Vyžaduje pozornost.')}</span><small>${decisionSource(x)}</small></div><button class="btn ${i===0?'primary':''}" data-today-decision="${i}">${i===0?'Řešit teď':'Otevřít'}</button></div>`).join('')||'<div class="empty success-empty">Nic zásadního teď nevyžaduje rozhodnutí.</div>'}</div>
  </div>
  <div class="metric-strip today-metrics"><div class="metric"><span>Kritické / dnes</span><b class="${urgentAll.length?'bad':'good'}">${urgentAll.length}</b></div><div class="metric"><span>Čekám na</span><b class="${waitingAll.length?'warn':'good'}">${waitingAll.length}</b></div><div class="metric"><span>Hotovo dnes</span><b>${doneToday}</b></div><div class="metric"><span>Celková pozornost</span><b>${attentionCount(s)}</b></div></div>
  <div class="grid two"><div class="card"><div class="eyebrow">DNES A PO TERMÍNU</div>${urgentTasks.map(t=>`<div class="row"><div><b>${h(t.title)}</b><div class="muted">${taskMeta(t)}</div></div><div class="row-actions"><button class="btn primary" data-today-done="${t.id}">Hotovo</button><button class="btn" data-today-tomorrow="${t.id}">Zítra</button></div></div>`).join('')||'<div class="empty">Nic nehoří. Můžeš řešit další krok.</div>'}${urgentAll.length>urgentTasks.length?`<div class="muted" style="padding-top:8px">+ ${urgentAll.length-urgentTasks.length} dalších kritických úkolů</div>`:''}${tasks.length>urgentTasks.length?`<button class="btn" data-nav="work" style="margin-top:10px">Všechny úkoly · ${tasks.length}</button>`:''}</div><div class="card"><div class="eyebrow">KALENDÁŘ</div>${events.map(e=>`<div class="row"><div><b>${h(e.title||e.summary||'Událost')}</b><div class="muted">${eventMeta(e)}</div></div></div>`).join('')||'<div class="empty">V kalendáři teď nic dalšího nevidím.</div>'}</div></div>
  <div class="grid" style="margin-top:2px">
    <div class="card"><div class="card-head"><div><div class="eyebrow">PENÍZE / XTB</div><h2>Rozhodnutí</h2></div><span class="live-chip ${xtbLive.fresh?'':'stale'}"><i></i>${xtbLive.fresh?'živě':'pravidla'}</span></div><div class="row"><span>Hotovost</span><b>${money(nw.cash)}</b></div><div class="row"><span>XTB</span><b>${money(nw.xtb)}</b></div>${xtbActions.map(({p,d})=>`<div class="row"><div><b>${h(p.ticker)}</b><div class="muted">${h(d.reason)}</div></div><span class="decision-action ${d.tone||''}">${h(actionLabel(d.action))}</span></div>`).join('')||'<div class="empty">Žádné výrazné XTB rozhodnutí.</div>'}<button class="btn" data-nav="money" style="margin-top:8px">Otevřít XTB cockpit</button></div>
    <div class="card"><div class="card-head"><div><div class="eyebrow">VSTUPENKY</div><h2>Co řešit</h2></div><span class="live-chip ${ticketLive.fresh?'':'stale'}"><i></i>${ticketLive.fresh?'živě':'pravidla'}</span></div>${ticketActions.map(({x,d})=>`<div class="row"><div><b>${h(x.name)}</b><div class="muted">${date(x.date)} · ${h(d.when||d.reason)}</div></div><span class="decision-action ${d.tone||''}">${h(actionLabel(d.action))}</span></div>`).join('')||'<div class="empty">U vstupenek nic akutního.</div>'}<button class="btn" data-nav="tickets" style="margin-top:8px">Otevřít ticket intelligence</button></div>
    <div class="card"><div class="eyebrow">AKTIVNÍ PROJEKTY</div>${projects.map(p=>`<div class="row"><div><b>${h(p.name)}</b><div class="muted">${p.owner?h(p.owner)+' · ':''}${h(p.next||'Chybí další krok')}</div></div><button class="btn" data-today-project="${p.id}">Otevřít</button></div>`).join('')||'<div class="empty">Žádný aktivní projekt.</div>'}<button class="btn" data-nav="work" style="margin-top:8px">Všechny projekty</button></div>
  </div>
  <div class="grid two" style="margin-top:2px"><div class="card"><div class="eyebrow">ČEKÁM NA</div>${waiting.map(x=>`<div class="row"><div><b>${h(x.title||x.person||'Čekající položka')}</b><div class="muted">${x.person?h(x.person)+' · ':''}${waitAge(x)} dní čekání</div></div><button class="btn" data-wait-done="${x.id}">Vyřešeno</button></div>`).join('')||'<div class="empty">Na nikoho kriticky nečekáš.</div>'}${waitingAll.length>waiting.length?`<div class="muted" style="padding-top:8px">+ ${waitingAll.length-waiting.length} dalších čekajících položek</div>`:''}<button class="btn" data-more-nav="waiting" style="margin-top:10px">Otevřít všechno čekání · ${waitingAll.length}</button></div><div class="card"><div class="eyebrow">RADAR</div>${nextSignals.map((x,i)=>`<div class="row"><div><b>${h(x.title)}</b><div class="muted">${h(x.type)} · ${h(x.reason)}</div></div><div class="row-actions"><span class="status ${x.score>=85?'bad':x.score>=65?'warn':'good'}">${x.score}</span><button class="btn" data-radar-open="${i}">Otevřít</button></div></div>`).join('')||'<div class="empty">Žádný další výrazný signál.</div>'}${inbox?`<div class="row"><div><b>Inbox</b><div class="muted">${inbox} položek čeká na rozhodnutí</div></div><button class="btn" data-more-nav="inbox">Projít</button></div>`:''}</div></div>`;
 qsa('[data-today-decision]',qs('#todayView')).forEach(b=>b.onclick=()=>openDecision(decisions[Number(b.dataset.todayDecision)]));qsa('[data-nav]',qs('#todayView')).forEach(b=>b.onclick=()=>navigate(b.dataset.nav));qsa('[data-more-nav]',qs('#todayView')).forEach(b=>b.onclick=()=>navigate(b.dataset.moreNav));qsa('[data-today-project]',qs('#todayView')).forEach(b=>b.onclick=()=>openProject(b.dataset.todayProject));qsa('[data-radar-open]',qs('#todayView')).forEach(b=>b.onclick=()=>openSignal(nextSignals[Number(b.dataset.radarOpen)]));qsa('[data-wait-done]',qs('#todayView')).forEach(b=>b.onclick=()=>store.mutate('Čekání vyřešeno',x=>{const w=x.delegations?.find(y=>y.id===b.dataset.waitDone);if(w){w.status='DONE';w.doneAt=new Date().toISOString();w.updatedAt=new Date().toISOString()}}));qsa('[data-today-done]',qs('#todayView')).forEach(b=>b.onclick=()=>store.mutate('Hotovo: úkol',x=>{const t=x.tasks.find(y=>y.id===b.dataset.todayDone);if(t){t.status='HOTOVO';t.updatedAt=new Date().toISOString()}}));qsa('[data-today-tomorrow]',qs('#todayView')).forEach(b=>b.onclick=()=>store.mutate('Úkol přesunut na zítra',x=>{const t=x.tasks.find(y=>y.id===b.dataset.todayTomorrow);if(t){const d=new Date();d.setDate(d.getDate()+1);d.setHours(9,0,0,0);t.due=d.toISOString();t.updatedAt=new Date().toISOString()}}));
}
