import {APP_VERSION} from './config.js';
import {store} from './state.js';
import {oneScreenAutopilot,onboardingWizard} from './personalPlus29.js';
import {personalMonthlyReview} from './monthlyReview29.js';
import {nextMonthPlan} from './nextMonthPlanner29.js';
import {yearAheadRadar} from './yearAheadRadar29.js';
import {personalInbox} from './autopilot28.js';
import {h,date,qs,qsa,modal} from './utils.js';

const tone=p=>Number(p)>=90?'bad':Number(p)>=75?'warn':'good';
const nav=(target='today',mode=null)=>{window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:target}));if(target==='home'&&mode)queueMicrotask(()=>window.dispatchEvent(new CustomEvent('kamil:home-open',{detail:mode})));if(target==='more'&&mode)queueMicrotask(()=>window.dispatchEvent(new CustomEvent('kamil:more',{detail:mode})))};
const row=(x,button=true)=>`<div class="autopilot29-row"><div><b>${h(x.title||'Osobní věc')}</b><small>${h(x.reason||x.detail||x.kind||'')}</small></div>${button?`<button class="btn" data-t29-open="${h(x.target||'today')}" data-t29-home="${h(x.homeMode||'')}">Otevřít</button>`:''}</div>`;
const money=(v,c='CZK')=>`${Number(v||0).toLocaleString('cs-CZ',{maximumFractionDigits:0})} ${h(c)}`;
const monthLabel=key=>new Intl.DateTimeFormat('cs-CZ',{month:'short',year:'numeric'}).format(new Date(`${key}-01T12:00:00`));

async function showMonthlyReview(){
 const r=personalMonthlyReview(store.get(),store.meta()),month=new Intl.DateTimeFormat('cs-CZ',{month:'long',year:'numeric'}).format(new Date(`${r.period.from}T12:00:00`));
 const att=r.attention.slice(0,5).map(x=>`<div class="autopilot29-row"><div><b>${h(x.title)}</b><small>${h(x.source)} · ${h(x.detail)}</small></div><span class="status ${tone(x.priority)}">${x.priority>=90?'TEĎ':'PROVĚŘIT'}</span></div>`).join('')||'<div class="empty success-empty">Před koncem měsíce není nový zásadní blokátor.</div>';
 const progress=r.progress.slice(0,6).map(x=>`<div class="autopilot29-row"><div><b>${h(x.title)}</b><small>${h(x.detail||x.kind)}</small></div>${x.amount?`<b>${money(x.amount,x.currency)}</b>`:''}</div>`).join('')||'<div class="empty">Tento měsíc zatím není uložený nový měřitelný posun.</div>';
 const costs=r.costChanges.slice(0,5).map(x=>`<div class="row"><span>${h(x.title)} <small class="muted">${h(x.cadence)}</small></span><b class="${x.delta>0?'bad':'good'}">${x.delta>0?'+':''}${money(x.delta,x.currency)}${x.pct===null?'':` · ${x.pct>0?'+':''}${Number(x.pct).toFixed(1)} %`}</b></div>`).join('')||'<div class="empty">Bez skutečně uložené změny ceny v tomto měsíci.</div>';
 const upcoming=r.upcoming.slice(0,6).map(x=>`<div class="row"><span>${h(x.title)}</span><b>${x.days===0?'dnes':`za ${x.days} dní`} · ${h(x.label)}</b></div>`).join('')||'<div class="empty">V dalších 31 dnech není uložený blízký termín.</div>';
 const byCurrency=Object.entries(r.goalProgressByCurrency).map(([c,v])=>`${money(v,c)}`).join(' · ')||'—';
 const body=`<div class="decision-note"><b>${h(month)}</b> · do konce měsíce ${r.period.daysLeft} dní. Review nevymýšlí chybějící data a měny nesčítá.</div><div class="metric-strip"><div class="metric"><span>K uzavření</span><b class="${r.status==='ACTION'?'bad':r.attentionCount?'warn':'good'}">${r.attentionCount}</b></div><div class="metric"><span>Skutečný posun</span><b>${r.progressCount}</b></div><div class="metric"><span>Příspěvky do cílů</span><b>${h(byCurrency)}</b></div><div class="metric"><span>Dalších 31 dní</span><b>${r.upcoming.length}</b></div></div><h3>Co uzavřít</h3>${att}<h3>Skutečný posun</h3>${progress}<h3>Změny uložených nákladů</h3>${costs}<h3>Dalších 31 dní</h3>${upcoming}<p class="muted">${h(r.note)}</p>`;
 const top=r.attention[0],result=await modal(`Měsíční review · ${month}`,body,top?[{label:'Zavřít',value:null},{label:'Otevřít nejdůležitější',value:'open',primary:true}]:[{label:'Hotovo',value:null,primary:true}]);
 if(result==='open'&&top)nav(top.target||'home',top.mode||null);
}

async function showNextMonthPlan(){
 const p=nextMonthPlan(store.get()),month=new Intl.DateTimeFormat('cs-CZ',{month:'long',year:'numeric'}).format(new Date(`${p.period.from}T12:00:00`)),c=p.cashflow.currency;
 const att=p.attention.slice(0,6).map(x=>`<div class="autopilot29-row"><div><b>${h(x.title)}</b><small>${h(x.source)} · ${h(x.detail)}</small></div><span class="status ${tone(x.priority)}">${x.priority>=90?'ŘEŠIT':'PŘIPRAVIT'}</span></div>`).join('')||'<div class="empty success-empty">Z uložených dat nevychází pro příští měsíc nový blokátor.</div>';
 const cash=p.cashflow.events.slice(0,7).map(x=>`<div class="row"><span>${date(x.at)} · ${h(x.label)}</span><b class="${x.amount<0?'bad':'good'}">${x.amount>0?'+':''}${money(x.amount,c)}</b></div>`).join('')||'<div class="empty">Bez známého cashflow v příštím měsíci.</div>';
 const goals=p.goals.items.slice(0,5).map(x=>`<div class="row"><span>${h(x.title)} <small class="muted">plán / potřebné tempo</small></span><b>${money(x.planned,x.currency)} / ${x.required===null?'—':money(x.required,x.currency)}</b></div>`).join('')||'<div class="empty">Bez aktivního finančního cíle.</div>';
 const deadlines=p.deadlines.items.slice(0,7).map(x=>`<div class="row"><span>${h(x.title)} <small class="muted">${h(x.domain)}</small></span><b>${date(x.at)}</b></div>`).join('')||'<div class="empty">Bez uloženého termínu v příštím měsíci.</div>';
 const tickets=p.tickets.items.slice(0,4).map(x=>`<div class="row"><span>${h(x.title)} · ${x.qty} ks</span><b>${date(x.date)}${x.listPrice===null?' · bez ceny':''}</b></div>`).join('')||'<div class="empty">Bez aktivní ticket pozice s akcí v příštím měsíci.</div>';
 const goalPlan=Object.entries(p.goals.byCurrency).map(([currency,v])=>`${money(v.planned,currency)}`).join(' · ')||'—';
 const body=`<div class="decision-note"><b>${h(month)}</b> · plán pouze z uložených dat. Neznámé příjmy/výdaje ani FX se nedopočítávají.</div><div class="metric-strip"><div class="metric"><span>Známý čistý cashflow</span><b class="${p.cashflow.net<0?'warn':'good'}">${p.cashflow.net>0?'+':''}${money(p.cashflow.net,c)}</b></div><div class="metric"><span>Známé minimum</span><b class="${p.cashflow.status==='RISK'?'bad':p.cashflow.status==='TIGHT'?'warn':'good'}">${money(p.cashflow.minBalance,c)}</b></div><div class="metric"><span>Termíny</span><b>${p.deadlines.total}</b></div><div class="metric"><span>Plán cílů</span><b>${h(goalPlan)}</b></div><div class="metric"><span>Ticket pozice</span><b>${p.tickets.positions}</b></div></div><h3>Připravit předem</h3>${att}<h3>Známý cashflow</h3>${cash}<h3>Cíle / fondy</h3>${goals}<h3>Termíny</h3>${deadlines}<h3>Vstupenky</h3>${tickets}<p class="muted">${h(p.note)}</p>`;
 const top=p.attention[0],result=await modal(`Plán příštího měsíce · ${month}`,body,top?[{label:'Zavřít',value:null},{label:'Otevřít nejdůležitější',value:'open',primary:true}]:[{label:'Hotovo',value:null,primary:true}]);
 if(result==='open'&&top)nav(top.target||'home',top.mode||null);
}

async function showYearAheadRadar(){
 const r=yearAheadRadar(store.get()),from=monthLabel(r.months[0].key),to=monthLabel(r.months[r.months.length-1].key);
 const annualOut=Object.entries(r.totalOutflowByCurrency).map(([c,v])=>money(v,c)).join(' · ')||'—',goalPlan=Object.entries(r.goalPlanByCurrency).map(([c,v])=>money(v,c)).join(' · ')||'—';
 const peakRows=Object.values(r.peaksByCurrency).map(x=>`<div class="row"><span>${h(x.currency)} · nejvyšší známé výdaje</span><b>${h(monthLabel(x.month))} · ${money(x.outflow,x.currency)}</b></div>`).join('')||'<div class="empty">Bez známých budoucích výdajů.</div>';
 const months=r.months.map(x=>{const cash=Object.entries(x.moneyByCurrency).map(([c,v])=>`${money(v.outflow,c)} ven / ${money(v.inflow,c)} dovnitř`).join(' · '),goals=Object.entries(x.goalPlanByCurrency).map(([c,v])=>`cíle ${money(v,c)}`).join(' · '),summary=[`${x.milestoneCount} termínů`,cash,goals].filter(Boolean).join(' · ');return `<div class="row"><span>${h(monthLabel(x.key))}</span><b>${h(summary||'bez známé položky')}</b></div>`}).join('');
 const milestones=r.milestones.slice(0,10).map(x=>`<div class="autopilot29-row"><div><b>${h(x.title)}</b><small>${h(x.domain)} · ${h(x.type)}</small></div><b>${date(x.at)}</b></div>`).join('')||'<div class="empty">Bez známého milníku v dalších 12 měsících.</div>';
 const gaps=(r.coverage.missingAmountItems||r.coverage.missingDateItems)?`<div class="decision-note"><b>Mezery v datech:</b> ${r.coverage.missingAmountItems} finančních položek bez částky · ${r.coverage.missingDateItems} opakovaných položek bez termínu. Radar je do součtů nedopočítává.</div>`:'';
 const body=`<div class="decision-note"><b>${h(from)} → ${h(to)}</b> · 12 celých budoucích měsíců. Měny zůstávají oddělené.</div><div class="metric-strip"><div class="metric"><span>Měsíce s daty</span><b>${r.coverage.monthsWithEvents}/12</b></div><div class="metric"><span>Známé milníky</span><b>${r.coverage.milestoneCount}</b></div><div class="metric"><span>Známé výdaje</span><b>${h(annualOut)}</b></div><div class="metric"><span>Plán cílů</span><b>${h(goalPlan)}</b></div></div>${gaps}<h3>Nejvyšší známé výdaje podle měny</h3>${peakRows}<h3>Rok po měsících</h3>${months}<h3>Nejbližší milníky</h3>${milestones}<p class="muted">${h(r.note)}</p>`;
 const top=r.milestones[0],result=await modal('12 měsíců dopředu',body,top?[{label:'Zavřít',value:null},{label:'Otevřít nejbližší',value:'open',primary:true}]:[{label:'Hotovo',value:null,primary:true}]);
 if(result==='open'&&top)nav(top.target||'home',top.mode||null);
}

export function renderToday(){
 const s=store.get(),meta=store.meta(),a=oneScreenAutopilot(s,meta),on=onboardingWizard(s,meta),inbox=personalInbox(s),review=personalMonthlyReview(s,meta),next=nextMonthPlan(s),year=yearAheadRadar(s),currency=a.money.primary||'CZK',safe=Number(a.money.safeToDeploy||0).toLocaleString('cs-CZ',{maximumFractionDigits:0});
 const changeRows=a.changes.slice(0,5).map(x=>`<div class="autopilot29-row"><div><b>${h(x.title)}</b><small>${h(x.kind)} · ${date(x.at)}</small></div></div>`).join('');
 qs('#todayView').innerHTML=`<div class="view-head"><div><div class="eyebrow">KAMIL OS ${h(APP_VERSION)} / OSOBNÍ AUTOPILOT</div><h1>${a.quiet?'Všechno důležité je pod kontrolou.':'Tady je jen to, co teď stojí za pozornost.'}</h1><p>Žádné pracovní moduly. Jen osobní akce, peníze, blížící se termíny a skutečné změny.</p></div><div class="view-head-stat"><b class="${a.escalation.urgent?'bad':a.quality.high?'warn':'good'}">${a.doToday.length}</b><span>věcí dnes</span></div></div>
 <div class="autopilot29-grid">
  <div class="card autopilot29-card"><div class="card-head"><div><div class="eyebrow">UDĚLEJ DNES</div><h2>Nejdůležitější osobní kroky</h2></div><span class="status ${a.doToday.some(x=>x.priority>=90)?'bad':a.doToday.length?'warn':'good'}">${a.doToday.length}</span></div>${a.doToday.map(x=>row(x)).join('')||'<div class="empty success-empty">Nic zásadního dnes nehoří.</div>'}</div>
  <div class="card autopilot29-card"><div class="card-head"><div><div class="eyebrow">POZOR NA PENÍZE</div><h2>Rezerva a rozhodnutí</h2></div><button class="btn" data-t29-open="money">Peníze</button></div>${a.moneyAlerts.map(x=>`<div class="autopilot29-alert"><b>${h(x)}</b></div>`).join('')||'<div class="empty success-empty">Známé cashflow teď nevytváří nový varovný signál.</div>'}<div class="row"><span>Bezpečný prostor před plánem</span><b>${safe} ${h(currency)}</b></div><div class="decision-note">Jde o plánovací prostor podle uložených dat; nic se automaticky neinvestuje.</div></div>
  <div class="card autopilot29-card"><div class="card-head"><div><div class="eyebrow">BLÍŽÍ SE</div><h2>Připravit → naplánovat → řešit</h2></div><button class="btn" data-t29-open="home" data-t29-home="timeline">Timeline</button></div>${a.approaching.map(x=>`<div class="autopilot29-row"><div><b>${h(x.title)}</b><small>${h(x.label)} · ${h(x.detail)} · ${h(x.domain)}</small></div><span class="status ${tone(x.priority)}">${h(x.label)}</span></div>`).join('')||'<div class="empty">Bez blízkého osobního termínu.</div>'}</div>
  <div class="card autopilot29-card"><div class="card-head"><div><div class="eyebrow">CO SE ZMĚNILO</div><h2>Posledních 14 dní</h2></div></div>${changeRows||'<div class="empty">Bez nové osobní změny v historii.</div>'}</div>
 </div>
 <div class="metric-strip autopilot29-strip"><button class="metric autopilot29-metric" data-t29-action="monthly-review"><span>Měsíční review</span><b class="${review.status==='ACTION'?'bad':review.attentionCount?'warn':'good'}">${review.status==='CLEAR'?'✓':review.attentionCount}</b><small>${review.period.daysLeft} dní do konce měsíce</small></button><button class="metric autopilot29-metric" data-t29-action="next-month"><span>Příští měsíc</span><b class="${next.status==='ACTION'?'bad':next.attentionCount?'warn':'good'}">${next.status==='CLEAR'?'✓':next.attentionCount}</b><small>${h(next.period.key)}</small></button><button class="metric autopilot29-metric" data-t29-action="year-ahead"><span>12 měsíců</span><b class="${year.coverage.milestoneCount?'warn':'good'}">${year.coverage.milestoneCount||'✓'}</b><small>${year.coverage.monthsWithEvents}/12 měsíců s daty</small></button><button class="metric autopilot29-metric" data-t29-action="inbox"><span>Personal Inbox</span><b class="${inbox.total?'warn':'good'}">${inbox.total}</b></button><button class="metric autopilot29-metric" data-t29-action="quality"><span>Kvalita dat</span><b class="${a.quality.high?'warn':'good'}">${a.quality.score}/100</b></button><button class="metric autopilot29-metric" data-t29-open="money"><span>Cíle / fondy</span><b class="${a.goals.attention?'warn':'good'}">${a.goals.total}</b></button><button class="metric autopilot29-metric" data-t29-action="onboarding"><span>Onboarding</span><b class="${on.complete?'good':on.steps.length?'warn':'good'}">${on.complete?'✓':on.steps.length}</b></button></div>`;
 qsa('[data-t29-open]',qs('#todayView')).forEach(b=>b.onclick=()=>nav(b.dataset.t29Open,b.dataset.t29Home||null));
 qsa('[data-t29-action]',qs('#todayView')).forEach(b=>b.onclick=()=>{if(b.dataset.t29Action==='monthly-review')showMonthlyReview();else if(b.dataset.t29Action==='next-month')showNextMonthPlan();else if(b.dataset.t29Action==='year-ahead')showYearAheadRadar();else if(b.dataset.t29Action==='inbox')nav('home','dashboard');else if(b.dataset.t29Action==='quality')nav('home','risk');else nav('home','dashboard')});
}
