import {store} from './state.js';
import {h,qs} from './utils.js';
import {todayBrain34} from './todayBrain34.js';
import {decisionCenter36,recordDecisionMemory36,recordDecisionOutcome36} from './decisionCenter36.js';
import {autopilot40,copilot40} from './os40.js';

const id='todayBrain34Host';let queued=false;
const targetLabel=t=>t==='director'?'Director Mode':t==='waiting'?'Waiting For':t==='money'?'Peníze':t==='tickets'?'Vstupenky':t==='home'?'Domov':'Otevřít';
const czk=v=>Number.isFinite(Number(v))&&Number(v)!==0?`${Math.round(Number(v)).toLocaleString('cs-CZ')} Kč`:null;
function openTarget(t){if(t==='director'){window.dispatchEvent(new CustomEvent('kamil:director-open'));return}if(t==='waiting'){window.dispatchEvent(new CustomEvent('kamil:waiting-open'));return}window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:t||'today'}))}
function remember(id,status){const c=decisionCenter36(store.get()),row=c.rows.find(x=>x.id===id);if(!row)return;store.mutate(`Decision ${status}: ${row.title}`,s=>recordDecisionMemory36(s,row,status));}
function rate(memoryId,outcome){store.mutate(`Outcome ${outcome}`,s=>recordDecisionOutcome36(s,memoryId,outcome));}
function ask40(query,host){const a=copilot40(store.get(),query),box=host.querySelector('[data-copilot40-answer]');if(box)box.innerHTML=`<b>Kamil Copilot:</b> ${h(a.answer)} <button class="btn" data-copilot40-open="${h(a.target)}">Otevřít</button>`;box?.querySelector('[data-copilot40-open]')?.addEventListener('click',e=>openTarget(e.currentTarget.dataset.copilot40Open))}

function os40TopRow(x,i){const conf=x.confidence?.score,doing=x.risk?.doing,waiting=x.risk?.waiting,cost=czk(x.opportunityCost?.czk),what=czk(x.whatIf?.estimatedCzk),guard=x.guardrails?.ok?'GUARDRAILS OK':'BLOK / POZOR';return `<div class="brain34-row"><div style="display:flex;gap:10px;align-items:flex-start"><span class="rank34">${i+1}</span><div><b>${h(x.title||'Doporučení')}</b><small><strong>Priorita ${Math.round(Number(x.priority)||0)} · Confidence ${conf??'—'} · ${h(guard)}</strong><br>${h(x.reason||x.explain?.why||'')}<br><strong>Riziko:</strong> provést ${doing??'—'} / nechat být ${waiting??'—'}${cost?` · cena odkladu ~ ${h(cost)}`:''}${what?` · what-if 10 % ~ ${h(what)}`:''}<br><strong>Co změní názor:</strong> ${h(x.explain?.changeMind||'Nová data a změna podmínek.')}</small></div></div><div class="brain34-actions"><button class="btn" data-os40-target="${h(x.target||'today')}">${h(targetLabel(x.target))}</button></div></div>`}
function warningHtml(rows=[]){return rows.length?rows.slice(0,4).map(x=>`<div class="brain34-row"><div><b>${h(x.title)}</b><small>${h(x.domain)}</small></div><span class="status ${x.severity>=90?'bad':x.severity>=70?'warn':'good'}">${Math.round(x.severity)}</span></div>`).join(''):'<div class="empty success-empty">Early Warning System nevidí žádný zásadní problém.</div>'}
function os40Html(a){const c=a.command,f=c.forecast?.windows||[],s=a.status;return `<div class="card brain34-card today-brain34" data-os40>
<div class="card-head"><div><div class="eyebrow">KAMIL OS / 40.0 AUTOPILOT</div><h2>${h(a.morning.headline)}</h2><p class="muted">Jedna vrstva přes práci, peníze, vstupenky, čekání a rozhodnutí. OS sleduje, vysvětluje a navrhuje; kritické akce nepotvrzuje za tebe.</p></div><span class="status ${c.warnings.length?'warn':'good'}">${c.warnings.length} varování</span></div>
<div class="metric-strip"><div class="metric"><span>Peníze</span><b>${h(s.money)}</b></div><div class="metric"><span>Práce</span><b>${h(s.work)}</b></div><div class="metric"><span>Vstupenky</span><b>${h(s.tickets)}</b></div><div class="metric"><span>Čekání</span><b>${h(s.waiting)}</b></div></div>
<div class="decision-note"><strong>TOP 3 · udělej / rozhodni</strong><div class="brain34-list">${c.top.map(os40TopRow).join('')||'<div class="empty">Nic kritického.</div>'}</div></div>
<div class="decision-note"><strong>Early Warning System</strong><div class="brain34-list">${warningHtml(c.warnings)}</div></div>
<div class="metric-strip"><div class="metric"><span>Cash</span><b>${czk(c.money.cash)||'—'}</b></div><div class="metric"><span>Investovatelný plán</span><b>${czk(c.money.investable)||'0 Kč'}</b></div><div class="metric"><span>Ticket kapitál</span><b>${czk(c.tickets.capital)||'—'}</b></div><div class="metric"><span>Realizovaný výkon</span><b>${czk(c.performance.total)||'0 Kč'}</b></div></div>
<div class="metric-strip"><div class="metric"><span>Práce score</span><b>${Math.round(c.director.score)}</b></div><div class="metric"><span>Po termínu</span><b>${c.director.overdue}</b></div><div class="metric"><span>Waiting</span><b>${c.waiting.count}</b></div><div class="metric"><span>Universal Inbox</span><b>${c.inbox.count}</b></div></div>
<div class="metric-strip">${f.map(x=>`<div class="metric"><span>${x.days} dní · pressure</span><b>${Math.round(x.pressure)}</b><small>${x.taskDeadlines} termínů · ${x.events} eventů</small></div>`).join('')}<div class="metric"><span>Entity Graph</span><b>${c.graph.nodes} / ${c.graph.links}</b><small>nodes / links</small></div></div>
<div class="decision-note"><strong>Morning / Evening</strong><div>${h(a.morning.headline)}</div><div class="muted">${h(a.evening.message)} · ${a.evening.reviewNeeded} výsledků čeká na hodnocení.</div></div>
<div class="decision-note"><strong>Kamil Copilot</strong><div class="brain34-actions"><button class="btn" data-copilot40="Co mám udělat teď?">Co teď?</button><button class="btn" data-copilot40="Můžu investovat 25k?">Můžu investovat?</button><button class="btn" data-copilot40="Co vstupenky?">Vstupenky?</button><button class="btn" data-copilot40="Na koho čekám?">Na koho čekám?</button></div><div class="muted" data-copilot40-answer>Zeptej se jedním klikem nad aktuálními daty OS.</div></div>
<div class="decision-note">${h(a.note)}</div></div>`}

function centerMeta(x){const parts=[x.urgency,x.evidence];if(czk(x.impactCzk))parts.push(`impact ${czk(x.impactCzk)}`);if(x.potentialGrossCzk!==null&&x.potentialGrossCzk!==undefined)parts.push(`hrubý rozdíl ${Math.round(x.potentialGrossCzk).toLocaleString('cs-CZ')} Kč`);if(x.memory?.status==='SNOOZED')parts.push('ODLOŽENO DO ZÍTŘKA');if(x.learning?.samples)parts.push(`learning ${x.learning.bias>=0?'+':''}${x.learning.bias} / ${x.learning.samples} hodn.`);return parts.filter(Boolean).join(' · ')}
function outcomesHtml(c){if(!c.pendingOutcomes?.length)return '';return `<div class="decision-note"><strong>Vyhodnotit dokončená rozhodnutí</strong><div class="brain34-list">${c.pendingOutcomes.map(x=>`<div class="brain34-row"><div><b>${h(x.title)}</b><small>${h(x.domain)} · ${h(x.action)}${czk(x.impactCzk)?` · impact ${h(czk(x.impactCzk))}`:''}</small></div><div class="brain34-actions"><button class="btn" data-outcome36="GOOD" data-outcome36-id="${h(x.id)}">Dobré</button><button class="btn" data-outcome36="NEUTRAL" data-outcome36-id="${h(x.id)}">Neutrální</button><button class="btn" data-outcome36="BAD" data-outcome36-id="${h(x.id)}">Špatné</button></div></div>`).join('')}</div></div>`}
function analyticsTone(x){if(!x||x.samples<3)return 'good';return x.scorePct>=40?'good':x.scorePct<=-40?'bad':'warn'}
function analyticsHtml(c){const a=c.analytics;if(!a)return '';return `<div class="decision-note"><strong>Decision Analytics / 36.3</strong><div class="muted">${a.rated} hodnocení · ${a.mature} použitelných typů · celkový score ${a.rated?`${a.overall.scorePct>=0?'+':''}${a.overall.scorePct}%`:'—'}</div>${a.rows.length?`<div class="brain34-list">${a.rows.slice(0,4).map(x=>`<div class="brain34-row"><div><b>${h(x.domain)} · ${h(x.label)}</b><small>${x.good} dobré · ${x.neutral} neutrální · ${x.bad} špatné</small></div><div class="brain34-actions"><span class="status ${analyticsTone(x)}">${h(x.confidence)}</span><span class="status ${analyticsTone(x)}">${x.scorePct>=0?'+':''}${x.scorePct}%</span></div></div>`).join('')}</div>`:''}</div>`}
function centerHtml(c){return `<div class="card brain34-card today-brain34" data-decision-center36><div class="card-head"><div><div class="eyebrow">DECISION CENTER / 36.3</div><h2>${c.rows.length?'Detail rozhodnutí':'Teď není potřeba žádný zásah'}</h2></div><span class="status ${c.counts.critical?'bad':'good'}">${c.counts.critical} urgentní</span></div><div class="brain34-list">${c.rows.map(x=>`<div class="brain34-row"><div style="display:flex;gap:10px;align-items:flex-start"><span class="rank34">${x.rank}</span><div><b>${h(x.title)}</b><small><strong>${h(centerMeta(x))}</strong><br>${h(x.reason)}<br><strong>Další krok:</strong> ${h(x.nextStep)}</small></div></div><div class="brain34-actions"><span class="status ${h(x.tone)}">${x.priority}</span><button class="btn" data-center36-target="${h(x.target)}">${h(targetLabel(x.target))}</button><button class="btn" data-memory36="DONE" data-memory36-id="${h(x.id)}">Hotovo</button><button class="btn" data-memory36="SNOOZED" data-memory36-id="${h(x.id)}">Odložit</button><button class="btn" data-memory36="IGNORED" data-memory36-id="${h(x.id)}">Ignorovat</button></div></div>`).join('')||'<div class="empty success-empty">Žádná urgentní investiční ani ticketová akce.</div>'}</div>${outcomesHtml(c)}${analyticsHtml(c)}</div>`}

function render(){const view=qs('#todayView');if(!view?.querySelector('.view-head'))return;qs(`#${id}`,view)?.remove();const s=store.get(),b=todayBrain34(s),c=decisionCenter36(s),a=autopilot40(s),host=document.createElement('div');host.id=id;host.innerHTML=`${os40Html(a)}<div class="card brain34-card today-brain34"><div class="card-head"><div><div class="eyebrow">DNEŠNÍ PRIORITY / 35.0</div><h2>${b.rows.length?'Co dnes nepustit z hlavy':'Dnes není nic kritického.'}</h2></div><span class="status ${b.critical?'bad':'good'}">${b.critical} kritické</span></div><div class="brain34-list">${b.rows.map(x=>`<div class="brain34-row"><div><b>${h(x.title)}</b><small>${h(x.kind)} · ${h(x.reason)}</small></div><div class="brain34-actions"><span class="status ${h(x.tone)}">${x.priority}</span><button class="btn" data-today34-target="${h(x.target)}">${h(targetLabel(x.target))}</button></div></div>`).join('')||'<div class="empty success-empty">Bez významných výjimek.</div>'}</div></div>${centerHtml(c)}`;view.querySelector('.view-head')?.insertAdjacentElement('afterend',host);host.querySelectorAll('[data-today34-target],[data-center36-target],[data-os40-target]').forEach(btn=>btn.addEventListener('click',()=>openTarget(btn.dataset.today34Target||btn.dataset.center36Target||btn.dataset.os40Target)));host.querySelectorAll('[data-memory36]').forEach(btn=>btn.addEventListener('click',()=>remember(btn.dataset.memory36Id,btn.dataset.memory36)));host.querySelectorAll('[data-outcome36]').forEach(btn=>btn.addEventListener('click',()=>rate(btn.dataset.outcome36Id,btn.dataset.outcome36)));host.querySelectorAll('[data-copilot40]').forEach(btn=>btn.addEventListener('click',()=>ask40(btn.dataset.copilot40,host)))}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;render()})}
function start(){const view=qs('#todayView');if(view)new MutationObserver(()=>{if(!qs(`#${id}`,view))schedule()}).observe(view,{childList:true,subtree:false});store.subscribe(()=>{if(qs('#view-today')?.classList.contains('on'))schedule()});window.addEventListener('kamil:navigate',schedule);setTimeout(render,450)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
