import {store} from './state.js';
import {h,date,qs,qsa} from './utils.js';
import {personalBriefing} from './personalToday26.js';
import {personalMoney} from './personalMoney26.js';
import {familyHome} from './familyHome25.js';
import {personalRiskCenter} from './personalRisk25.js';
import {xtbIntelligenceAge,ticketIntelligenceAge} from './live24.js';

const tone=p=>Number(p)>=90?'bad':Number(p)>=75?'warn':'good';
const moneyRows=pm=>Object.entries(pm.byCurrency||{}).map(([c,v])=>`${c} ${Number(v.monthly||0).toLocaleString('cs-CZ',{maximumFractionDigits:0})}/měs`).join(' · ')||'bez známých opakovaných nákladů';
const navigate=v=>window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:v}));
function openDecision(x){if(!x)return;if(x.target==='home'){navigate('home');queueMicrotask(()=>window.dispatchEvent(new CustomEvent('kamil:home-open',{detail:x.homeMode||'dashboard'})));return}navigate(x.target||'today')}

export function renderToday(){
 const s=store.get(),b=personalBriefing(s),pm=personalMoney(s),fam=familyHome(s),risk=personalRiskCenter(s),xtb=xtbIntelligenceAge(s),tickets=ticketIntelligenceAge(s);
 const next=b.timeline.items.filter(x=>x.days>=0).slice(0,5),hour=new Date().getHours();
 const personalChanges=(s.audit||[]).filter(x=>new Date(x.at).toDateString()===new Date().toDateString()&&/osob|pojist|platb|doklad|rodin|domov|vstup|xtb|invest/i.test(x.label||'')).length;
 qs('#todayView').innerHTML=`
 <div class="view-head"><div><div class="eyebrow">DNES / PERSONAL OS</div><h1>${b.critical?'Nejdřív vyřeš osobní věci, které opravdu hoří.':'Osobní briefing bez pracovního šumu'}</h1><p>Platby, pojistky, doklady, rodina, domov, XTB a vstupenky v jedné prioritní frontě.</p></div><div class="view-head-stat"><b class="${b.critical?'bad':b.high?'warn':'good'}">${b.decisions.length}</b><span>hlavních rozhodnutí</span></div></div>
 <div class="card today-decision-card"><div class="card-head"><div><div class="eyebrow">TOP 5 OSOBNÍCH ROZHODNUTÍ</div><h2>Co řešit jako první</h2></div><span class="status ${b.critical?'bad':b.high?'warn':'good'}">${b.critical?`${b.critical} kritické`:b.high?`${b.high} důležité`:'pod kontrolou'}</span></div><div class="today-decision-list">${b.decisions.map((x,i)=>`<div class="today-decision-row"><div class="today-rank ${tone(x.priority)}">${x.rank}</div><div class="today-decision-main"><div class="today-decision-top"><b>${h(x.title)}</b><span class="status ${tone(x.priority)}">${Math.round(x.priority)}</span></div><span>${h(x.reason||'Vyžaduje kontrolu.')}</span><small>${h(x.kind||x.domain)}${x.confidence!==undefined&&x.confidence!==null?` · confidence ${Math.round(Number(x.confidence)||0)} %`:''}${x.source?` · ${h(x.source)}`:''}</small></div><button class="btn ${i===0?'primary':''}" data-personal-decision="${i}">${i===0?'Řešit teď':'Otevřít'}</button></div>`).join('')||'<div class="empty success-empty">Nic zásadního teď nevyžaduje osobní rozhodnutí.</div>'}</div></div>
 <div class="metric-strip today-metrics"><div class="metric"><span>Dnes / po termínu</span><b class="${b.today?'bad':'good'}">${b.today}</b></div><div class="metric"><span>Do 7 dní</span><b class="${b.week?'warn':'good'}">${b.week}</b></div><div class="metric"><span>Osobní risk</span><b class="${risk.critical?'bad':risk.high?'warn':'good'}">${risk.score}/100</b></div><div class="metric"><span>Osobní změny dnes</span><b>${personalChanges}</b></div></div>
 <div class="grid two"><div class="card"><div class="card-head"><div><div class="eyebrow">OSOBNÍ TIMELINE</div><h2>Příštích 90 dní</h2></div><button class="btn" data-open-home="timeline">Celá timeline</button></div>${next.map(x=>`<div class="row"><div><b>${h(x.title)}</b><div class="muted">${h(x.domain)} · ${x.days===0?'dnes':`za ${x.days} dní`}</div></div><span>${date(x.at)}</span></div>`).join('')||'<div class="empty">Žádný uložený osobní termín v příštích 90 dnech.</div>'}</div>
 <div class="card"><div class="card-head"><div><div class="eyebrow">KOLIK STOJÍ ŽIVOT</div><h2>${h(moneyRows(pm))}</h2></div><button class="btn" data-nav="money">Peníze</button></div><div class="row"><span>Cashflow 90 dní</span><b class="${pm.cashflow.status==='RISK'?'bad':pm.cashflow.status==='TIGHT'?'warn':'good'}">${h(pm.cashflow.status)}</b></div><div class="row"><span>Minimum výhledu</span><b>${Number(pm.cashflow.minBalance||0).toLocaleString('cs-CZ')} Kč</b></div><div class="row"><span>Opakované položky bez částky</span><b>${pm.recurringMissing}</b></div><div class="decision-note">${h(pm.note)}</div></div></div>
 <div class="grid three"><div class="card"><div class="card-head"><div><div class="eyebrow">RODINA & DOMOV</div><h2>${fam.totalMembers} členů</h2></div><button class="btn" data-open-home="family">Otevřít</button></div>${fam.upcoming.slice(0,3).map(x=>`<div class="row"><div><b>${h(x.name)}</b><div class="muted">${h(x.kind)} · za ${x.days} dní</div></div><span>${date(x.at)}</span></div>`).join('')||'<div class="empty">Žádný rodinný moment v příštích 60 dnech.</div>'}</div>
 <div class="card"><div class="card-head"><div><div class="eyebrow">XTB</div><h2>${xtb.fresh?'Čerstvá intelligence':'Pravidlový / uložený stav'}</h2></div><button class="btn" data-nav="money">Otevřít</button></div><p class="muted">Investiční doporučení zůstávají oddělená podle původu dat. Žádný obchod se neprovádí automaticky.</p></div>
 <div class="card"><div class="card-head"><div><div class="eyebrow">VSTUPENKY</div><h2>${tickets.fresh?'Čerstvá intelligence':'Pravidlový / uložený stav'}</h2></div><button class="btn" data-nav="tickets">Otevřít</button></div><p class="muted">Prodejní a nákupní signály jsou pouze doporučení. Kamil OS nic sám nekupuje ani neprodává.</p></div></div>
 <div class="card"><div class="card-head"><div><div class="eyebrow">${hour>=17?'VEČERNÍ CLOSE':'DNEŠNÍ KLID'}</div><h2>${hour>=17?(b.decisions.length?`Zůstává ${b.decisions.length} hlavních osobních rozhodnutí`:'Osobní agenda je pro dnešek čistá'):'Pracovní agenda je z Personal OS skrytá'}</h2></div><button class="btn" data-open-home="risk">Osobní rizika</button></div><p class="muted">${hour>=17?'Večer kontroluj jen otevřené osobní závazky a zítřejší termíny.':'Dnes ukazuje jen osobní život, finance, vstupenky a rodinu/domov.'}</p></div>`;
 qsa('[data-personal-decision]',qs('#todayView')).forEach(btn=>btn.onclick=()=>openDecision(b.decisions[Number(btn.dataset.personalDecision)]));
 qsa('[data-open-home]',qs('#todayView')).forEach(btn=>btn.onclick=()=>{navigate('home');queueMicrotask(()=>window.dispatchEvent(new CustomEvent('kamil:home-open',{detail:btn.dataset.openHome})))});
 qsa('[data-nav]',qs('#todayView')).forEach(btn=>btn.onclick=()=>navigate(btn.dataset.nav));
}
