import {store} from './state.js';
import {h,qs} from './utils.js';
import {todayBrain34} from './todayBrain34.js';

const id='todayBrain34Host';let queued=false;
const targetLabel=t=>t==='director'?'Director Mode':t==='waiting'?'Waiting For':t==='money'?'Peníze':t==='tickets'?'Vstupenky':t==='home'?'Domov':'Otevřít';
function openTarget(t){if(t==='director'){window.dispatchEvent(new CustomEvent('kamil:director-open'));return}if(t==='waiting'){window.dispatchEvent(new CustomEvent('kamil:waiting-open'));return}window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:t||'today'}))}
function render(){const view=qs('#todayView');if(!view?.querySelector('.view-head'))return;qs(`#${id}`,view)?.remove();const b=todayBrain34(store.get()),host=document.createElement('div');host.id=id;host.className='card brain34-card today-brain34';host.innerHTML=`<div class="card-head"><div><div class="eyebrow">KAMIL OS DOPORUČUJE DNES / 35.0</div><h2>${b.rows.length?'Těchto pár věcí má dnes největší smysl.':'Dnes není nic kritického.'}</h2><p class="muted">Práce, follow-upy, vstupenky, investice i osobní termíny v jednom pořadí.</p></div><span class="status ${b.critical?'bad':'good'}">${b.critical} kritické</span></div><div class="brain34-list">${b.rows.map(x=>`<div class="brain34-row"><div style="display:flex;gap:10px;align-items:flex-start"><span class="rank34">${x.rank}</span><div><b>${h(x.title)}</b><small>${h(x.kind)} · ${h(x.reason)}</small></div></div><div class="brain34-actions"><span class="status ${h(x.tone)}">${x.priority}</span><button class="btn" data-today34-target="${h(x.target)}">${h(targetLabel(x.target))}</button></div></div>`).join('')||'<div class="empty success-empty">OS z uložených dat nevidí nic, co by dnes potřebovalo zásah.</div>'}</div><div class="decision-note">${h(b.note)}</div>`;const anchor=view.querySelector('.view-head');anchor?.insertAdjacentElement('afterend',host);host.querySelectorAll('[data-today34-target]').forEach(btn=>btn.addEventListener('click',()=>openTarget(btn.dataset.today34Target)))}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;render()})}
function start(){const view=qs('#todayView');if(view)new MutationObserver(()=>{if(!qs(`#${id}`,view))schedule()}).observe(view,{childList:true,subtree:false});store.subscribe(()=>{if(qs('#view-today')?.classList.contains('on'))schedule()});window.addEventListener('kamil:navigate',schedule);setTimeout(render,450)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
