import {APP_VERSION} from './releaseMeta.js';
import {store} from './state.js';
import {h,qs,toast} from './utils.js';

let fullModule=null,fullPromise=null,seq=0,personalPromise=null,dailyPromise=null,adminPromise=null,homePromise=null;
const CLOSED=new Set(['DONE','CLOSED','ARCHIVED','RESOLVED','PAID','SOLD','PAYOUT RECEIVED']);
const open=x=>!CLOSED.has(String(x?.status||x?.workflow||'').toUpperCase());
const activeTicket=x=>['HOLD','LISTED'].includes(String(x?.workflow||'HOLD').toUpperCase());
const WORK_RE=/zak[aá]zk|faktur|dodavat|cest[aá]k|doch[aá]zk|ředitel|reditel|pks|cpi|zbrojov|\bzl\b|projektov[aá] karta|pracovn/i;
const personal=x=>!WORK_RE.test(`${x?.title||''} ${x?.name||''} ${x?.area||''} ${x?.category||''} ${x?.project||''}`);
const dateMs=v=>{const t=new Date(v||0).getTime();return Number.isFinite(t)?t:null};
const fmt=v=>{const t=dateMs(v);return t===null?'—':new Date(t).toLocaleDateString('cs-CZ',{day:'numeric',month:'short'})};
const todayVisible=()=>document.visibilityState!=='hidden'&&!!qs('#view-today')?.classList.contains('on');
function nextTask(s={}){const rows=(s.tasks||[]).filter(open).filter(personal).map(x=>({title:x.title||x.name||'Úkol',due:x.due||x.dueAt||x.date||null,priority:Number(x.priority||0)}));return rows.sort((a,b)=>{const ad=dateMs(a.due),bd=dateMs(b.due);if(ad!==null&&bd!==null)return ad-bd;if(ad!==null)return-1;if(bd!==null)return 1;return b.priority-a.priority})[0]||null}
function metrics(s={}){const waiting=[...(s.delegations||[])].filter(open).filter(personal),inbox=(s.inbox||[]).filter(open).filter(personal),tasks=(s.tasks||[]).filter(open).filter(personal),tickets=(s.ticketBook?.items||[]).filter(activeTicket);return{tasks:tasks.length,waiting:waiting.length,inbox:inbox.length,tickets:tickets.length,next:nextTask(s)}}
async function hydrateFull(token){const host=qs('#todayView');if(!host||host.dataset.todayLite43!==token||!todayVisible())return false;try{if(!fullModule){fullPromise=fullPromise||import('./today29.js');fullModule=await fullPromise}const current=qs('#todayView');if(!current||current.dataset.todayLite43!==token||!todayVisible())return false;fullModule.renderToday?.();current.removeAttribute('data-today-lite43');window.__KAMIL_TODAY_FULL_AT__=performance.now();window.dispatchEvent(new CustomEvent('kamil:today-full-ready'));return true}catch(error){console.error('[todayLite43]',error);toast('Detail Today se nepodařilo načíst');return false}}
async function openPersonal(mode){try{personalPromise=personalPromise||import('./personalIntelligence441.js');const m=await personalPromise;return mode==='finance'?m.openPersonalFinance441():m.openPersonalMission441()}catch(error){console.error('[personal-intel]',error);toast('Osobní přehled se nepodařilo načíst')}}
async function openDaily(){try{dailyPromise=dailyPromise||import('./personalDailyHub442.js');const m=await dailyPromise;return m.openPersonalDailyHub442()}catch(error){console.error('[personal-daily]',error);toast('Můj dnešek se nepodařilo načíst')}}
async function openAdmin(){try{adminPromise=adminPromise||import('./personalAdmin443.js');const m=await adminPromise;return m.openPersonalAdmin443()}catch(error){console.error('[personal-admin]',error);toast('Osobní administrativa se nepodařila načíst')}}
async function openHome(){try{homePromise=homePromise||import('./familyHome444.js');const m=await homePromise;return m.openFamilyHome444()}catch(error){console.error('[family-home]',error);toast('Rodina & domov se nepodařilo načíst')}}
export function renderTodayLite43(){if(fullModule){fullModule.renderToday?.();return}const host=qs('#todayView');if(!host)return;const token=String(++seq),m=metrics(store.get());host.dataset.todayLite43=token;const next=m.next?`<div class="card"><div class="card-head"><div><div class="eyebrow">NEJBLIŽŠÍ OSOBNÍ ÚKOL</div><h2>${h(m.next.title)}</h2></div><b>${h(fmt(m.next.due))}</b></div><p class="muted">Jen tvoje soukromé věci. Pracovní zakázky a ředitelské povinnosti sem netahám.</p></div>`:'';host.innerHTML=`<div class="view-head"><div><div class="eyebrow">KAMIL OS ${APP_VERSION} / PERSONAL</div><h1>Tvoje soukromá appka pro život, peníze a rozhodnutí.</h1><p>XTB, vstupenky, osobní úkoly, čekání, Inbox, domácnost, rodina a osobní administrativa. Bez pracovního řízení.</p></div><button class="btn primary" data-personal-daily>Můj dnešek</button></div><div class="metric-strip"><div class="metric"><span>Osobní úkoly</span><b>${m.tasks}</b></div><div class="metric"><span>Čekám na</span><b>${m.waiting}</b></div><div class="metric"><span>Osobní Inbox</span><b>${m.inbox}</b></div><div class="metric"><span>Aktivní vstupenky</span><b>${m.tickets}</b></div></div><div class="card"><div class="card-head"><div><div class="eyebrow">PERSONAL INTELLIGENCE</div><h2>Co mám teď řešit?</h2></div></div><div class="row-actions"><button class="btn" data-personal-intel="finance">Peníze + vstupenky</button><button class="btn" data-personal-intel="mission">Osobní Mission Control</button><button class="btn" data-family-home>Rodina & domov</button><button class="btn" data-personal-admin>Osobní administrativa</button><button class="btn primary" data-personal-daily>Můj dnešek</button></div><div class="decision-note">Všechny přehledy se počítají až po kliknutí. Pracovní doména je z osobního režimu odfiltrovaná.</div></div>${next}<div class="decision-note">Personal 44.4 drží Safe Core: žádný analytický modul se nespouští automaticky na pozadí.</div>`;host.querySelectorAll('[data-personal-intel]').forEach(b=>b.addEventListener('click',()=>openPersonal(b.dataset.personalIntel)));host.querySelectorAll('[data-personal-daily]').forEach(b=>b.addEventListener('click',openDaily));host.querySelectorAll('[data-personal-admin]').forEach(b=>b.addEventListener('click',openAdmin));host.querySelectorAll('[data-family-home]').forEach(b=>b.addEventListener('click',openHome));window.dispatchEvent(new CustomEvent('kamil:app-interactive'))}
export function warmFullToday43(){if(fullModule)return Promise.resolve(fullModule);fullPromise=fullPromise||import('./today29.js');return fullPromise.then(m=>fullModule=m).catch(()=>null)}