import {APP_VERSION} from './releaseMeta.js';
import {store} from './state.js';
import {h,qs,toast} from './utils.js';

let fullModule=null,fullPromise=null,seq=0,intelPromise=null;
const CLOSED=new Set(['DONE','CLOSED','ARCHIVED','RESOLVED','PAID','SOLD','PAYOUT RECEIVED']);
const open=x=>!CLOSED.has(String(x?.status||x?.workflow||'').toUpperCase());
const activeTicket=x=>['HOLD','LISTED'].includes(String(x?.workflow||'HOLD').toUpperCase());
const dateMs=v=>{const t=new Date(v||0).getTime();return Number.isFinite(t)?t:null};
const fmt=v=>{const t=dateMs(v);return t===null?'—':new Date(t).toLocaleDateString('cs-CZ',{day:'numeric',month:'short'})};
const todayVisible=()=>document.visibilityState!=='hidden'&&!!qs('#view-today')?.classList.contains('on');
function nextTask(s={}){const rows=(s.tasks||[]).filter(open).map(x=>({title:x.title||x.name||'Úkol',due:x.due||x.dueAt||x.date||null,priority:Number(x.priority||0)}));return rows.sort((a,b)=>{const ad=dateMs(a.due),bd=dateMs(b.due);if(ad!==null&&bd!==null)return ad-bd;if(ad!==null)return-1;if(bd!==null)return 1;return b.priority-a.priority})[0]||null}
function metrics(s={}){const waiting=[...(s.directorBook?.waiting||[]),...(s.delegations||[])].filter(open),inbox=(s.inbox||[]).filter(open),tasks=(s.tasks||[]).filter(open),tickets=(s.ticketBook?.items||[]).filter(activeTicket);return{tasks:tasks.length,waiting:waiting.length,inbox:inbox.length,tickets:tickets.length,next:nextTask(s)}}
async function hydrateFull(token){const host=qs('#todayView');if(!host||host.dataset.todayLite43!==token||!todayVisible())return false;try{if(!fullModule){fullPromise=fullPromise||import('./today29.js');fullModule=await fullPromise}const current=qs('#todayView');if(!current||current.dataset.todayLite43!==token||!todayVisible())return false;fullModule.renderToday?.();current.removeAttribute('data-today-lite43');window.__KAMIL_TODAY_FULL_AT__=performance.now();window.dispatchEvent(new CustomEvent('kamil:today-full-ready'));return true}catch(error){console.error('[todayLite43]',error);toast('Detail Today se nepodařilo načíst');return false}}
async function openIntel(mode){try{intelPromise=intelPromise||import('./safeIntelligence438.js');const m=await intelPromise;return m.openSafeIntelligence438(mode)}catch(error){console.error('[safe-intel]',error);toast('Safe Intelligence se nepodařilo načíst')}}
export function renderTodayLite43(){if(fullModule){fullModule.renderToday?.();return}const host=qs('#todayView');if(!host)return;const token=String(++seq),m=metrics(store.get());host.dataset.todayLite43=token;const next=m.next?`<div class="card"><div class="card-head"><div><div class="eyebrow">NEJBLIŽŠÍ ÚKOL</div><h2>${h(m.next.title)}</h2></div><b>${h(fmt(m.next.due))}</b></div><p class="muted">Bezpečný základ nic těžkého nespouští sám.</p></div>`:'';host.innerHTML=`<div class="view-head"><div><div class="eyebrow">KAMIL OS ${APP_VERSION} / SAFE CORE</div><h1>Rychlý základ. Chytré vrstvy jen na kliknutí.</h1><p>Žádný autopilot, prefetch ani velký analytický modul se nespustí bez tvého explicitního pokynu.</p></div><button class="btn" data-today43-full>Načíst velký Today detail</button></div><div class="metric-strip"><div class="metric"><span>Otevřené úkoly</span><b>${m.tasks}</b></div><div class="metric"><span>Waiting For</span><b>${m.waiting}</b></div><div class="metric"><span>Inbox</span><b>${m.inbox}</b></div><div class="metric"><span>Aktivní vstupenky</span><b>${m.tickets}</b></div></div><div class="card"><div class="card-head"><div><div class="eyebrow">SAFE INTELLIGENCE</div><h2>Chytré moduly na vyžádání</h2></div></div><div class="row-actions"><button class="btn" data-safe-intel="finance">XTB + vstupenky</button><button class="btn" data-safe-intel="work">Work Command Center</button><button class="btn primary" data-safe-intel="mission">Mission Control</button></div><div class="decision-note">Tyto přehledy se počítají až po kliknutí a po zavření neběží na pozadí.</div></div>${next}<div class="decision-note">Safe Core: automatická hydratace velkého Today Brainu je vypnutá. Detail je dostupný ručně nahoře.</div>`;qs('[data-today43-full]',host)?.addEventListener('click',()=>hydrateFull(token),{once:true});host.querySelectorAll('[data-safe-intel]').forEach(b=>b.addEventListener('click',()=>openIntel(b.dataset.safeIntel)));window.dispatchEvent(new CustomEvent('kamil:app-interactive'))}
export function warmFullToday43(){if(fullModule)return Promise.resolve(fullModule);fullPromise=fullPromise||import('./today29.js');return fullPromise.then(m=>fullModule=m).catch(()=>null)}
