import {APP_VERSION} from './releaseMeta.js';
import {store} from './state.js';
import {h,qs} from './utils.js';

let fullModule=null,fullPromise=null,hydrateTimer=null,seq=0,lifePromise=null;
const CLOSED=new Set(['DONE','CLOSED','ARCHIVED','RESOLVED','PAID','SOLD','PAYOUT RECEIVED']);
const open=x=>!CLOSED.has(String(x?.status||x?.workflow||'').toUpperCase());
const activeTicket=x=>['HOLD','LISTED'].includes(String(x?.workflow||'HOLD').toUpperCase());
const dateMs=v=>{const t=new Date(v||0).getTime();return Number.isFinite(t)?t:null};
const fmt=v=>{const t=dateMs(v);return t===null?'—':new Date(t).toLocaleDateString('cs-CZ',{day:'numeric',month:'short'})};
const todayVisible=()=>document.visibilityState!=='hidden'&&!!qs('#view-today')?.classList.contains('on');
function nextTask(s={}){const rows=(s.tasks||[]).filter(open).map(x=>({title:x.title||x.name||'Úkol',due:x.due||x.dueAt||x.date||null,priority:Number(x.priority||0)}));return rows.sort((a,b)=>{const ad=dateMs(a.due),bd=dateMs(b.due);if(ad!==null&&bd!==null)return ad-bd;if(ad!==null)return-1;if(bd!==null)return 1;return b.priority-a.priority})[0]||null}
function metrics(s={}){const waiting=[...(s.directorBook?.waiting||[]),...(s.delegations||[])].filter(open),inbox=(s.inbox||[]).filter(open),tasks=(s.tasks||[]).filter(open),tickets=(s.ticketBook?.items||[]).filter(activeTicket);return{tasks:tasks.length,waiting:waiting.length,inbox:inbox.length,tickets:tickets.length,next:nextTask(s)}}
function loadLife42(){lifePromise=lifePromise||import('./lifeOs42Ui.js').catch(error=>{console.error('[todayLite43/life42]',error);lifePromise=null;return null});return lifePromise}
function scheduleFull(token,delay=15000){clearTimeout(hydrateTimer);hydrateTimer=setTimeout(()=>{const run=()=>{if(todayVisible())hydrateFull(token)};if('requestIdleCallback'in window)requestIdleCallback(run,{timeout:6000});else setTimeout(run,500)},Math.max(12000,delay))}
async function hydrateFull(token){clearTimeout(hydrateTimer);const host=qs('#todayView');if(!host||host.dataset.todayLite43!==token||!todayVisible())return false;try{if(!fullModule){fullPromise=fullPromise||import('./today29.js');fullModule=await fullPromise}const current=qs('#todayView');if(!current||current.dataset.todayLite43!==token||!todayVisible())return false;fullModule.renderToday?.();current.removeAttribute('data-today-lite43');window.__KAMIL_TODAY_FULL_AT__=performance.now();try{performance.mark('kamil-today-full')}catch{}window.dispatchEvent(new CustomEvent('kamil:today-full-ready'));return true}catch(error){console.error('[todayLite43]',error);return false}}
export function renderTodayLite43(){if(fullModule){fullModule.renderToday?.();loadLife42();return}const host=qs('#todayView');if(!host)return;const token=String(++seq),m=metrics(store.get());host.dataset.todayLite43=token;const next=m.next?`<div class="card"><div class="card-head"><div><div class="eyebrow">NEJBLIŽŠÍ ÚKOL</div><h2>${h(m.next.title)}</h2></div><b>${h(fmt(m.next.due))}</b></div><p class="muted">Plný prioritizační engine se dopočítá až později, aby nezamrazil start.</p></div>`:'';host.innerHTML=`<div class="view-head"><div><div class="eyebrow">KAMIL OS ${APP_VERSION} / SAFE FAST TODAY</div><h1>Jsi uvnitř. Těžký detail čeká.</h1><p>Základní lokální stav je interaktivní hned. Velký Today Brain se už nespouští okamžitě po prvním idle momentu.</p></div><button class="btn" data-today43-full>Načíst detail teď</button></div><div class="metric-strip"><div class="metric"><span>Otevřené úkoly</span><b>${m.tasks}</b></div><div class="metric"><span>Waiting For</span><b>${m.waiting}</b></div><div class="metric"><span>Inbox</span><b>${m.inbox}</b></div><div class="metric"><span>Aktivní vstupenky</span><b>${m.tickets}</b></div></div>${next}<div class="decision-note">Bezpečný start 42.1: těžké analýzy dostanou minimálně 15 s odstup. Pokud je chceš hned, použij tlačítko nahoře.</div>`;qs('[data-today43-full]',host)?.addEventListener('click',()=>hydrateFull(token),{once:true});setTimeout(()=>loadLife42(),700);window.dispatchEvent(new CustomEvent('kamil:app-interactive'));scheduleFull(token,15000)}
export function warmFullToday43(){if(fullModule)return Promise.resolve(fullModule);fullPromise=fullPromise||import('./today29.js');return fullPromise.then(m=>fullModule=m).catch(()=>null)}
