import {store} from './state.js';
import {h,qs} from './utils.js';
import {totalInvestmentPortfolio34,monthlyInvestmentPlan34,investmentSnapshot34,upsertInvestmentSnapshot34} from './totalPortfolio34.js';

const hostId='totalPortfolio34Host';
let budgetOverride=null,range='ALL',snapshotSeeded=false,queued=false;
const fmt=(v,c='CZK',digits=0)=>`${Number(v||0).toLocaleString('cs-CZ',{minimumFractionDigits:digits,maximumFractionDigits:digits})} ${h(c)}`;
const pct=v=>`${Number(v||0).toLocaleString('cs-CZ',{maximumFractionDigits:1})} %`;
const tone=(current,target)=>current<target-5?'warn':current>target+8?'bad':'good';

function seedSnapshot(){
 if(snapshotSeeded)return;snapshotSeeded=true;const s=store.get(),today=new Date().toISOString().slice(0,10),last=(s.investmentBook?.history||[]).find(x=>String(x.date||x.at||'').slice(0,10)===today);if(last)return;
 store.mutate('Denní investiční snapshot',x=>{upsertInvestmentSnapshot34(x,new Date())},{undo:false,audit:false});
}
function historyRows(s){
 const live=investmentSnapshot34(s,new Date()),rows=[...(s.investmentBook?.history||[])];if(live){const i=rows.findIndex(x=>String(x.date||x.at||'').slice(0,10)===live.date);if(i>=0)rows[i]=live;else rows.push(live)}
 return rows.filter(x=>Number.isFinite(Number(x.total))).sort((a,b)=>new Date(a.at||a.date)-new Date(b.at||b.date));
}
function filteredHistory(rows){
 if(range==='ALL')return rows;const now=new Date(),cut=new Date(now);if(range==='1M')cut.setMonth(cut.getMonth()-1);else if(range==='1Y')cut.setFullYear(cut.getFullYear()-1);else if(range==='YTD')cut.setMonth(0,1),cut.setHours(0,0,0,0);return rows.filter(x=>new Date(x.at||x.date)>=cut);
}
function chart(rows,currency){
 const data=filteredHistory(rows),w=760,hgt=190,pad=18;if(!data.length)return '<div class="empty">Historie investiční hodnoty zatím není k dispozici.</div>';
 const vals=data.map(x=>Number(x.total||0)),min=Math.min(...vals),max=Math.max(...vals),span=Math.max(1,max-min),x=i=>pad+(data.length===1?(w-2*pad)/2:i/(data.length-1)*(w-2*pad)),y=v=>hgt-pad-(v-min)/span*(hgt-2*pad),pts=data.map((r,i)=>[x(i),y(Number(r.total||0))]),path=pts.map((p,i)=>`${i?'L':'M'} ${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join(' '),start=data[0],end=data.at(-1),delta=Number(end.total)-Number(start.total);
 return `<div class="brain34-chart-wrap"><svg class="brain34-chart" viewBox="0 0 ${w} ${hgt}" preserveAspectRatio="none" role="img" aria-label="Vývoj celkové hodnoty investic"><line class="gridline" x1="${pad}" y1="${pad}" x2="${w-pad}" y2="${pad}"/><line class="gridline" x1="${pad}" y1="${hgt/2}" x2="${w-pad}" y2="${hgt/2}"/><line class="gridline" x1="${pad}" y1="${hgt-pad}" x2="${w-pad}" y2="${hgt-pad}"/><path class="line" d="${path}"/>${pts.map(p=>`<circle class="point" cx="${p[0]}" cy="${p[1]}" r="4"/>`).join('')}</svg><div class="brain34-chart-labels"><span>${h(new Date(start.at||start.date).toLocaleDateString('cs-CZ'))} · ${fmt(start.total,currency)}</span><span class="${delta>=0?'good':'bad'}">${delta>=0?'+':''}${fmt(delta,currency)}</span><span>${h(new Date(end.at||end.date).toLocaleDateString('cs-CZ'))} · ${fmt(end.total,currency)}</span></div></div>`;
}
function planHtml(plan,p){
 if(!plan.ok)return `<div class="decision-note ${plan.code==='CASH_FLOOR'?'bad':'warn'}"><b>${h(plan.routing?.status||'Plán není dostupný')}</b> · ${h(plan.message||plan.routing?.reason||'')}</div>`;
 const ext=plan.externalRecurring.totalCzk>0?`<div class="decision-note"><b>Efekta / mimo XTB pravidelně:</b> ${fmt(plan.externalRecurring.totalCzk,'CZK')} měsíčně. Tento pohyb se započítá do budoucí alokace dřív, než OS rozdělí nový XTB vklad.</div>`:'';
 const rows=plan.trades.map(t=>`<div class="brain34-row"><div><b>${h(t.label)}${t.ticker?` · ${h(t.ticker)}`:''}</b><small>${h(t.reason)}</small></div><div class="brain34-actions"><span class="status ${t.requiresChoice?'warn':'good'}">${fmt(t.baseAmount,plan.portfolio.baseCurrency)}</span>${t.nativeCurrency&&t.nativeCurrency!==plan.portfolio.baseCurrency?`<span class="status">≈ ${fmt(t.nativeAmount,t.nativeCurrency)}</span>`:''}</div></div>`).join('')||'<div class="empty success-empty">Nový vklad už není potřeba směrovat do konkrétní podvážené třídy.</div>';
 return `${ext}<div class="brain34-list">${rows}</div><div class="decision-note"><b>Odchylka od cíle:</b> ${pct(plan.beforeDriftPct)} → ${pct(plan.afterDriftPct)}. ${h(plan.note)}</div>`;
}
function providerHtml(p){return p.providers.map(x=>`<div class="row"><span>${h(x.provider)} <small class="muted">${x.positions} pozic</small></span><b>${fmt(x.value,p.baseCurrency)} · ${pct(x.pct)}</b></div>`).join('')||'<div class="empty">Bez poskytovatelů.</div>'}
function render(){
 const view=qs('#moneyView');if(!view?.querySelector('.view-head'))return;seedSnapshot();const s=store.get(),p=totalInvestmentPortfolio34(s);if(!p.ok)return;const budget=budgetOverride??Number(s.financePlan?.plannedInvestment||25000),plan=monthlyInvestmentPlan34(s,budget),hist=historyRows(s),snap=investmentSnapshot34(s,new Date()),host=document.createElement('div');host.id=hostId;
 const b=p.buckets;
 host.innerHTML=`<div class="card brain34-card"><div class="card-head"><div><div class="eyebrow">TOTAL PORTFOLIO BRAIN / 34.0</div><h2>Jedno portfolio. XTB + Efekta + další investice.</h2><p class="muted">Žádný CZK účet proti EUR účtu. Alokace se hodnotí přes všechny investice po společném FX přepočtu.</p></div><div class="view-head-stat"><b class="${p.complete?'good':'warn'}">${p.complete?fmt(p.total,p.baseCurrency):'—'}</b><span>${p.positionCount} investičních pozic</span></div></div>${p.missingCurrencies.length?`<div class="decision-note warn">Chybí FX pro ${h(p.missingCurrencies.join(', '))}; globální verdikt je proto blokovaný.</div>`:''}<div class="brain34-allocation"><div><span>Široké ETF</span><b class="${tone(b.broad.pct,b.broad.targetPct)}">${pct(b.broad.pct)}</b><small>cíl ${pct(b.broad.targetPct)}</small></div><div><span>Dluhopisy</span><b class="${tone(b.bond.pct,b.bond.targetPct)}">${pct(b.bond.pct)}</b><small>cíl ${pct(b.bond.targetPct)}</small></div><div><span>Satelity</span><b class="${tone(b.satellite.pct,b.satellite.targetPct)}">${pct(b.satellite.pct)}</b><small>cíl ${pct(b.satellite.targetPct)}</small></div><div><span>Alternativy</span><b>${pct(b.alternative.pctOfTotal)}</b><small>${fmt(b.alternative.value,p.baseCurrency)}</small></div></div><div class="decision-note"><b>Efekta S&P 500 / broad mimo XTB:</b> ${fmt(p.broadExternal,p.baseCurrency)} už je součástí širokého ETF jádra. ${h(p.note)}</div></div>
 <div class="card brain34-card"><div class="card-head"><div><div class="eyebrow">CO KOUPIT TENTO MĚSÍC</div><h2>Rozdělení dalšího vkladu</h2><p class="muted">Plán nejdřív zohlední rezervu, pravidelné investice mimo XTB a teprve pak rozdělí nový XTB rozpočet.</p></div><span class="status">návrh, ne auto-trade</span></div><div class="brain34-planbar"><label>Nový investiční rozpočet<input id="portfolioBudget34" type="number" min="0" step="1000" value="${Math.round(budget)}"></label><button class="btn primary" id="portfolioPlan34">Přepočítat</button><div class="brain34-plan-note muted">Rezervní brána: ${h(plan.routing?.status||'—')}</div></div><div id="portfolioPlan34Rows">${planHtml(plan,p)}</div></div>
 <div class="brain34-subgrid"><div class="card"><div class="card-head"><div><div class="eyebrow">INVESTMENT TIMELINE</div><h3>Vývoj celého investičního majetku</h3></div><div class="brain34-range">${['1M','YTD','1Y','ALL'].map(x=>`<button data-range34="${x}" class="${range===x?'on':''}">${x}</button>`).join('')}</div></div>${chart(hist,p.baseCurrency)}<div class="metric-strip"><div class="metric"><span>Aktuální hodnota</span><b>${fmt(snap?.total||p.total,p.baseCurrency)}</b></div><div class="metric"><span>Známý vložený kapitál</span><b>${snap?.knownInvested===null?'—':fmt(snap.knownInvested,p.baseCurrency)}</b></div><div class="metric"><span>Známý XTB P/L</span><b class="${Number(snap?.knownProfit||0)>=0?'good':'bad'}">${snap?.knownProfit===null?'—':fmt(snap.knownProfit,p.baseCurrency)}</b></div><div class="metric"><span>Evidované dividendy</span><b>${fmt(snap?.dividends||0,p.baseCurrency)}</b></div></div><div class="decision-note">Historie se ukládá denně od této verze. Kde chybí cost basis mimo XTB, OS raději ukáže „—“ než vymyšlený zisk.</div></div><div class="card"><div class="card-head"><div><div class="eyebrow">KDE JSOU INVESTICE</div><h3>Poskytovatelé</h3></div></div>${providerHtml(p)}<div class="decision-note"><b>Strategická odchylka:</b> ${p.driftPct===null?'—':pct(p.driftPct)}. Měna účtu není investiční třída.</div></div></div>`;
 qs(`#${hostId}`,view)?.remove();const anchor=view.querySelector('.view-head');anchor?.insertAdjacentElement('afterend',host);
 qs('#portfolioPlan34',host)?.addEventListener('click',()=>{budgetOverride=Math.max(0,Number(qs('#portfolioBudget34',host)?.value||0));render()});host.querySelectorAll('[data-range34]').forEach(b=>b.addEventListener('click',()=>{range=b.dataset.range34;render()}));
}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;render()})}
function start(){const view=qs('#moneyView');if(view)new MutationObserver(()=>{if(!qs(`#${hostId}`,view))schedule()}).observe(view,{childList:true,subtree:false});store.subscribe(()=>{if(qs('#view-money')?.classList.contains('on'))schedule()});window.addEventListener('kamil:navigate',schedule);setTimeout(render,350)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
