import {hydrateColdView42} from './coldPartition42.js';
import {APP_RELEASE} from './releaseMeta.js';
const modules=new Map(),warmViews=new Map();
const titles={today:'DNES',inbox:'INBOX',money:'PENÍZE',tickets:'VSTUPENKY',family:'RODINA',home:'DOMOV',more:'DOKUMENTY'};
const quick={today:'Osobní úkol',inbox:'Úkol',money:'Pohledávka',tickets:'Vstupenka',family:'Rodinný úkol',home:'Osobní položka',more:'Dokument'};
function ensurePolish142(){if(typeof document==='undefined')return;if(!document.querySelector('link[data-finalpolish142]')){const l=document.createElement('link');l.rel='stylesheet';l.href='./finalPolish142.css';l.dataset.finalpolish142='1';document.head.appendChild(l)}document.documentElement.dataset.os142='1'}
function syncChrome142(view){if(typeof document==='undefined')return;const p=document.querySelector('#pageTitle');if(p)p.textContent=titles[view]||'KAMIL OS';document.querySelectorAll('[data-view]').forEach(x=>{const on=x.dataset.view===view;x.toggleAttribute('aria-current',on);if(on)x.setAttribute('aria-current','page')});const add=document.querySelector('#quickAddBtn');if(add){const b=add.querySelector('b'),name=quick[view]||'Přidat';if(b)b.textContent=name;add.title=`Rychle přidat ${name.toLowerCase()} · Ctrl N`}}
function ensureInboxShell(){if(typeof document==='undefined')return;ensurePolish142();if(!document.querySelector('link[data-core70]')){const l=document.createElement('link');l.rel='stylesheet';l.href='./core70.css';l.dataset.core70='1';document.head.appendChild(l)}const main=document.querySelector('main');if(main&&!document.querySelector('#view-inbox')){const section=document.createElement('section');section.id='view-inbox';section.className='view';section.innerHTML='<div id="inboxView"></div>';main.prepend(section)}const nav=document.querySelector('#mainNav');if(nav&&!nav.querySelector('[data-view="inbox"]')){const b=document.createElement('button');b.dataset.view='inbox';b.innerHTML='<span>◎</span><span>Inbox</span>';const today=nav.querySelector('[data-view="today"]');today?.after(b)}const bottom=document.querySelector('#bottomNav');if(bottom&&!bottom.querySelector('[data-view="inbox"]')){const b=document.createElement('button');b.dataset.view='inbox';b.innerHTML='<span>◎</span>Inbox';const today=bottom.querySelector('[data-view="today"]');today?.after(b)}}
ensureInboxShell();syncChrome142('today');
window.addEventListener?.('kamil:view-change',e=>syncChrome142(e.detail));
const viewDefs={today:['./todayPage101.js','renderTodayPage101'],inbox:['./inboxPage141.js','renderInboxPage141'],money:['./moneyPage100.js','renderMoneyPage100'],tickets:['./ticketPage100.js','renderTicketPage100'],family:['./familyPage140.js','renderFamilyPage140'],home:['./homePage140.js','renderHomePage140'],more:['./documentsPage141.js','renderDocumentsPage141']};
export const validViews41=new Set(Object.keys(viewDefs));
function load(path){if(modules.has(path))return modules.get(path);const p=import(path).catch(err=>{modules.delete(path);throw err});modules.set(path,p);return p}
function warmView(name='today'){const key=validViews41.has(name)?name:'today';if(warmViews.has(key))return warmViews.get(key);const def=viewDefs[key],p=Promise.resolve().then(()=>hydrateColdView42(key)).then(()=>load(def[0])).then(m=>m[def[1]]).catch(err=>{warmViews.delete(key);throw err});warmViews.set(key,p);return p}
export function getViewRenderer41(name='today'){return warmView(name)}
export function prefetchView41(){return Promise.resolve(null)}
export async function setMoreMode41(){return Promise.resolve(null)}
export async function openCapture41(type='task'){const m=await load('./personalCapture643.js');return m.openPersonalCapture643(type)}
export async function renderCommandResults41(q=''){try{const c=await load('./capitalCommand100.js');if(c.isCapitalQuestion100(q)){const box=document.querySelector('#commandResults');if(box){const amount=c.parseCapitalAmount100(q);box.classList.remove('hidden');box.innerHTML=`<div class="search-row"><div><b>Rozhodnout, co s ${Number(amount||0).toLocaleString('cs-CZ')} Kč</b><div class="muted">Capital Allocation Brain 100 · XTB × vstupenky × hotovost</div></div><button class="btn" data-capital-command100>Vyhodnotit</button></div>`;box.querySelector('[data-capital-command100]')?.addEventListener('click',()=>{box.classList.add('hidden');c.openCapitalDecision100(q)});return}}}catch{}const m=await load('./command.js');return m.renderResults(q)}
export async function executeCommand41(q=''){try{const c=await load('./capitalCommand100.js');if(c.isCapitalQuestion100(q))return c.openCapitalDecision100(q)}catch(e){console.warn('[capital-command100]',e)}const m=await load('./command.js');return m.execute(q)}
export async function renderExtras41(view='today'){syncChrome142(view);if(view==='today'){const m=await load('./personalWeekly700.js');return m.appendWeeklyReset700()}return null}
export function refreshRiskBadge41(){return Promise.resolve(null)}
export async function runPreflight41(){try{const m=await load('./personalHardening650.js');return {...m.personalReleasePreflight650(),safeCore:true,personalUx:APP_RELEASE,canonicalViews:[...validViews41],commandBar:true,inbox:true,weeklyReset:true,marketIntelligence100:true,capitalCommand100:true,marketAction101:true,finalPolish142:true}}catch(error){return{ok:false,safeCore:true,personalUx:APP_RELEASE,error:String(error?.message||error)}}}
export function scheduleNotifications41(){return Promise.resolve(null)}
export function warmRuntime41(){ensurePolish142();load('./command.js').catch(()=>{});load('./capitalCommand100.js').catch(()=>{});load('./marketAction101.js').catch(()=>{});return Promise.resolve(null)}
