import {hydrateColdView42} from './coldPartition42.js';
import {APP_RELEASE} from './releaseMeta.js';
import {ownEvent1100} from './runtimeOwnership1100.js';
import {restoreCanonicalProductStyles} from './productAdvancedStyles.js';
import {VIEW_REGISTRY,VALID_VIEWS,viewMeta} from './viewRegistry.js';

const OWNER='core.viewRuntime41';
const modules=new Map(),warmViews=new Map();

export const validViews41=VALID_VIEWS;
function load(path){if(modules.has(path))return modules.get(path);const p=import(path).catch(err=>{modules.delete(path);throw err});modules.set(path,p);return p}
function syncChrome142(view){if(typeof document==='undefined')return;const meta=viewMeta(view),p=document.querySelector('#pageTitle');if(p)p.textContent=meta.title.toUpperCase();document.querySelectorAll('[data-view]').forEach(x=>{const on=x.dataset.view===view;x.classList.toggle('on',on);if(on)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current')});const add=document.querySelector('#quickAddBtn');if(add){add.classList.remove('hidden');const b=add.querySelector('b'),name=meta.quick||'Přidat';if(b)b.textContent=name;add.title=`Rychle přidat ${name.toLowerCase()} · Ctrl N`}}
ownEvent1100(OWNER,window,'kamil:view-change',e=>syncChrome142(e.detail));syncChrome142('today');
function warmView(name='today'){const key=validViews41.has(name)?name:'today';if(warmViews.has(key))return warmViews.get(key);const meta=VIEW_REGISTRY[key],p=Promise.resolve().then(()=>hydrateColdView42(key)).then(()=>load(meta.module)).then(m=>{const renderer=m?.[meta.renderer];if(typeof renderer!=='function')throw new Error(`Chybí renderer ${meta.renderer} pro ${key}`);return renderer}).catch(err=>{warmViews.delete(key);throw err});warmViews.set(key,p);return p}
export function getViewRenderer41(name='today'){return warmView(name)}
export function prefetchView41(name='today'){const key=validViews41.has(name)?name:'today';if(VIEW_REGISTRY[key]?.heavy&&!document.querySelector(`#view-${key}.on`))return Promise.resolve(false);return warmView(key).then(()=>true).catch(error=>{console.warn(`[viewRuntime41] prefetch ${key}`,error);return false})}
export async function setMoreMode41(){return Promise.resolve(null)}
export async function openCapture41(type='task'){if(type==='money-task'){const m=await load('./personalMoneyActions645.js');return m.createMoneyTask645()}if(type==='document-source'){const btn=document.querySelector('#documentInbox650');if(btn){btn.click();return true}return null}const m=await load('./personalCapture643.js');if(type==='work-task')return m.openPersonalCapture643('task',{area:'Práce',category:'Práce'});if(type==='property-task')return m.openPersonalCapture643('task',{area:'Reality',category:'Reality'});if(type==='betting-task')return m.openPersonalCapture643('task',{area:'Sázení',category:'Sázení'});if(type==='family-task')return m.openPersonalCapture643('task',{area:'Rodina',category:'Rodina'});if(type==='home-task')return m.openPersonalCapture643('task',{area:'Domov',category:'Domov'});if(type==='ticket-task')return m.openPersonalCapture643('task',{area:'Vstupenky',category:'Vstupenky'});return m.openPersonalCapture643(['task','waiting','admin','insurance','contract'].includes(type)?type:'task')}
export async function renderCommandResults41(q=''){try{const c=await load('./capitalCommand100.js');if(c.isCapitalQuestion100(q)){const box=document.querySelector('#commandResults');if(box){const amount=c.parseCapitalAmount100(q);box.classList.remove('hidden');box.innerHTML=`<div class="search-row"><div><b>Rozhodnout, co s ${Number(amount||0).toLocaleString('cs-CZ')} Kč</b><div class="muted">Capital Allocation Brain</div></div><button class="btn" data-capital-command100>Vyhodnotit</button></div>`;const btn=box.querySelector('[data-capital-command100]');if(btn)btn.onclick=()=>{box.classList.add('hidden');c.openCapitalDecision100(q)};return}}}catch(error){console.warn('[capital-command100:render]',error)}try{const x=await load('./commandSearch610.js');x.installCommandSearch610?.();if(x.renderExtendedResults610?.(q))return}catch(e){console.warn('[command-search610]',e)}try{const g=await load('./globalSearch.js'),box=document.querySelector('#commandResults');if(box&&g.renderGlobalSearch741?.(q,box))return true}catch(e){console.warn('[global-search741]',e)}const m=await load('./command.js');return m.renderResults(q)}
export async function executeCommand41(q=''){try{const c=await load('./capitalCommand100.js');if(c.isCapitalQuestion100(q))return c.openCapitalDecision100(q)}catch(e){console.warn('[capital-command100]',e)}try{const g=await load('./globalSearch.js'),hit=g.resolveCommand741?.(q);if(hit?.route){window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:hit.route}));return true}}catch(e){console.warn('[global-command741]',e)}try{const x=await load('./commandSearch610.js');x.installCommandSearch610?.();if(x.executeExtendedCommand610?.(q))return true}catch(e){console.warn('[command-search610]',e)}const m=await load('./command.js');return m.execute(q)}
export async function renderExtras41(view='today'){syncChrome142(view);return null}
export function refreshRiskBadge41(){return Promise.resolve(null)}
export async function runPreflight41(){try{const m=await load('./personalHardening650.js');return {...m.personalReleasePreflight650(),safeCore:true,personalUx:APP_RELEASE,canonicalViews:[...validViews41],commandBar:true,inbox:true,betting:true,os2:true}}catch(error){return{ok:false,safeCore:true,personalUx:APP_RELEASE,error:String(error?.message||error)}}}
export function scheduleNotifications41(){return Promise.resolve(null)}
export function warmRuntime41(){return Promise.resolve(null)}
