import {store} from './state.js';
import {h,formModal,modal,toast,uid} from './utils.js';
import {personalDaysTo650} from './personalDate650.js';
import {isPersonalScope527} from './personalScope527.js';

const VERSION='670.0.0';
const DAY=86400000;
const CLOSED=new Set(['DONE','CLOSED','ARCHIVED','RESOLVED','PAID','CANCELLED','CANCELED']);
const A=v=>Array.isArray(v)?v:[];
const U=v=>String(v||'').toUpperCase();
const clean=v=>String(v||'').replace(/\s+/g,' ').trim();
const open=x=>!CLOSED.has(U(x?.status||x?.workflow||''));
const dueOf=x=>x?.followUpAt||x?.follow_up_at||x?.due||x?.dueAt||x?.deadline||null;
const sinceOf=x=>x?.since||x?.createdAt||x?.created_at||x?.at||null;
const whoOf=x=>clean(x?.waitingOn||x?.person||x?.owner||x?.contact||x?.counterparty||'Druhá strana');
const expectedOf=x=>clean(x?.expected||x?.waitingForWhat||x?.deliverable||x?.notes||x?.note||'');
const dateInput=v=>{const t=Date.parse(v||'');if(!Number.isFinite(t))return'';const d=new Date(t),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const isoDate=v=>String(v||'').trim()?new Date(`${String(v).trim()}T12:00:00`).toISOString():null;
const ageDays=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?Math.max(0,Math.floor((Date.now()-t)/DAY)):null};
const fmt=v=>v?new Date(v).toLocaleDateString('cs-CZ'):'neurčeno';
const fmtTime=v=>v?new Date(v).toLocaleString('cs-CZ',{day:'numeric',month:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
let activeFilter='all',query='',currentRoot=null,currentModel=null,boundGlobal=false;

function ensureCss(){if(document.querySelector('link[data-waiting670-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./waitingHub670.css';l.dataset.waiting670Css='1';document.head.appendChild(l)}
function locate(s,id){return A(s.delegations).find(x=>String(x.id||x.title)===String(id))||null}
function sourceRecord(s,w){if(!w?.sourceId||!w?.sourceKind)return null;if(w.sourceKind==='task')return A(s.tasks).find(x=>String(x.id)===String(w.sourceId))||null;if(w.sourceKind==='admin')return A(s.personalAdmin?.items).find(x=>String(x.id)===String(w.sourceId))||null;return null}
function syncSourceFollowUp(s,w){const src=sourceRecord(s,w);if(src){src.waitingFor=true;src.followUpAt=w.followUpAt||null;src.updatedAt=new Date().toISOString()}}
function releaseSource(s,w){const src=sourceRecord(s,w);if(!src)return;if(String(src.followUpAt||'')===String(w.followUpAt||''))src.followUpAt=null;src.waitingFor=false;src.updatedAt=new Date().toISOString()}
function statusOf(days){if(days===null)return'unscheduled';if(days<0)return'overdue';if(days===0)return'today';if(days<=3)return'soon';return'scheduled'}
function labelOf(status,days){if(status==='overdue')return`${Math.abs(days)} D PO TERMÍNU`;if(status==='today')return'FOLLOW-UP DNES';if(status==='soon')return`ZA ${days} D`;if(status==='unscheduled')return'BEZ TERMÍNU';return'ČEKÁM'}
function scoreOf(status,days,age,followups){let s={overdue:210,today:190,unscheduled:160,soon:125,scheduled:85}[status]||80;if(status==='overdue')s+=Math.min(35,Math.abs(Number(days||0))*3);s+=Math.min(24,Math.floor(Number(age||0)/7));s+=Math.min(15,Number(followups||0)*2);return s}
function rowFrom(x){const followUpAt=dueOf(x),days=followUpAt?personalDaysTo650(followUpAt):null,since=sinceOf(x),age=ageDays(since),history=A(x.followUpHistory),followups=Number(x.followUpCount||history.length||0),status=statusOf(days);return{id:String(x.id||x.title||''),title:clean(x.title||x.name||'Čekám na odpověď'),who:whoOf(x),expected:expectedOf(x),since,age,followUpAt,days,status,label:labelOf(status,days),lastFollowUpAt:x.lastFollowUpAt||history.at(-1)?.at||null,followups,channel:clean(x.channel||''),notes:clean(x.notes||x.note||''),score:scoreOf(status,days,age,followups),sourceKind:x.sourceKind||null,sourceId:x.sourceId||null}}
export function buildWaitingModel670(s=store.get()){
 const rows=A(s.delegations).filter(open).filter(isPersonalScope527).map(rowFrom).sort((a,b)=>b.score-a.score||((a.days??999)-(b.days??999))||String(a.title).localeCompare(String(b.title),'cs'));
 const now=Date.now(),recent=rows.filter(x=>{const t=Date.parse(x.lastFollowUpAt||'');return Number.isFinite(t)&&t>=now-7*DAY}).length;
 const counts={all:rows.length,overdue:rows.filter(x=>x.status==='overdue').length,today:rows.filter(x=>x.status==='today').length,soon:rows.filter(x=>x.status==='soon').length,unscheduled:rows.filter(x=>x.status==='unscheduled').length,recent};
 const attention=rows.filter(x=>['overdue','today','unscheduled'].includes(x.status));
 return{version:VERSION,rows,counts,attention,top:attention[0]||rows[0]||null,generatedAt:new Date().toISOString()}
}
export function waitingSummary670(s=store.get()){const m=buildWaitingModel670(s);return{count:m.counts.all,overdue:m.counts.overdue,today:m.counts.today,soon:m.counts.soon,unscheduled:m.counts.unscheduled,recent:m.counts.recent,top:m.top}}
function event670(type,id=null){window.dispatchEvent(new CustomEvent('kamil:waiting670-updated',{detail:{type,id,summary:waitingSummary670(),at:Date.now()}}))}
function mutateWaiting(id,label,fn){let changed=false;store.mutate(label,s=>{const w=locate(s,id);if(!w)return;fn(w,s);w.updatedAt=new Date().toISOString();changed=true},{undo:true,cloud:true,audit:true});if(changed)event670(label,id);return changed}
export function postponeWaiting670(id,days=3){const next=new Date(Date.now()+Number(days||0)*DAY).toISOString();return mutateWaiting(id,`Posunuta kontrola čekání o ${days} dní`,(w,s)=>{w.followUpAt=next;syncSourceFollowUp(s,w)})}
export function recordWaitingFollowUp670(id,days=3){const now=new Date().toISOString(),next=new Date(Date.now()+Number(days||0)*DAY).toISOString();return mutateWaiting(id,`Zapsán follow-up čekání: +${days} dní`,(w,s)=>{w.lastFollowUpAt=now;w.followUpAt=next;w.followUpCount=Number(w.followUpCount||0)+1;w.followUpHistory=A(w.followUpHistory);w.followUpHistory.push({at:now,nextFollowUpAt:next,channel:w.channel||null,note:'Follow-up zapsán v Waiting Center 2.0'});if(w.followUpHistory.length>20)w.followUpHistory=w.followUpHistory.slice(-20);syncSourceFollowUp(s,w)})}
export function resolveWaiting670(id){return mutateWaiting(id,'Vyřešeno čekání',(w,s)=>{w.status='DONE';w.resolvedAt=new Date().toISOString();releaseSource(s,w)})}
function followText(row){const subject=row.title?`ohledně ${row.title}`:'ohledně naší předchozí domluvy',expected=row.expected?` Potřeboval bych prosím ${row.expected}.`:'';return `Dobrý den, připomínám se prosím ${subject}.${expected} Dejte mi prosím vědět, jaký je aktuální stav. Děkuji.`}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Text follow-upu zkopírován.');return true}catch{}try{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Text follow-upu zkopírován.');return true}catch{return false}}
async function editWaiting670(id){const s=store.get(),w=locate(s,id);if(!w)return null;const body=`<div class="form-grid"><label class="wide">Co čekáš<input name="title" required autofocus value="${h(w.title||w.name||'')}"></label><label>Na koho čekáš<input name="waitingOn" value="${h(whoOf(w)==='Druhá strana'?'':whoOf(w))}" placeholder="Jméno / firma"></label><label>Kanál<select name="channel"><option value=""${!w.channel?' selected':''}>Neurčeno</option><option value="email"${w.channel==='email'?' selected':''}>E-mail</option><option value="phone"${w.channel==='phone'?' selected':''}>Telefon</option><option value="message"${w.channel==='message'?' selected':''}>Zpráva</option><option value="other"${w.channel==='other'?' selected':''}>Jiné</option></select></label><label>Čekám od<input type="date" name="since" value="${h(dateInput(sinceOf(w)))}"></label><label>Další kontrola<input type="date" name="followUpAt" value="${h(dateInput(dueOf(w)))}"></label><label class="wide">Co přesně má přijít<input name="expected" value="${h(w.expected||w.waitingForWhat||w.deliverable||'')}" placeholder="Např. potvrzení, nabídka, platba"></label><label class="wide">Poznámka<textarea name="notes" rows="3">${h(w.notes||w.note||'')}</textarea></label></div>`;const data=await formModal('Upravit čekání',body,{submitLabel:'Uložit'});if(!data)return null;mutateWaiting(id,`Upraveno čekání: ${data.title||w.title}`,(x,s2)=>{x.title=clean(data.title)||x.title;x.waitingOn=clean(data.waitingOn);x.channel=clean(data.channel);x.since=isoDate(data.since)||x.since||x.createdAt||new Date().toISOString();x.followUpAt=isoDate(data.followUpAt);x.expected=clean(data.expected);x.notes=clean(data.notes);syncSourceFollowUp(s2,x)});toast('Čekání upraveno.');return true}
export async function createWaiting670(){const today=new Date(),next=new Date(Date.now()+3*DAY);const body=`<div class="form-grid"><label class="wide">Co čekáš<input name="title" required autofocus placeholder="Např. Odpověď od makléře"></label><label>Na koho čekáš<input name="waitingOn" placeholder="Jméno / firma"></label><label>Kanál<select name="channel"><option value="">Neurčeno</option><option value="email">E-mail</option><option value="phone">Telefon</option><option value="message">Zpráva</option><option value="other">Jiné</option></select></label><label>Čekám od<input type="date" name="since" value="${dateInput(today)}"></label><label>Další kontrola<input type="date" name="followUpAt" value="${dateInput(next)}"></label><label class="wide">Co přesně má přijít<input name="expected" placeholder="Např. potvrzení, nabídka, platba"></label><label class="wide">Poznámka<textarea name="notes" rows="3"></textarea></label></div>`;const data=await formModal('Přidat čekání',body,{submitLabel:'Přidat'});if(!data||!clean(data.title))return null;let created=null;store.mutate(`Přidáno čekání: ${clean(data.title)}`,s=>{s.delegations=A(s.delegations);created={id:uid('waiting'),title:clean(data.title),waitingOn:clean(data.waitingOn),channel:clean(data.channel),since:isoDate(data.since)||new Date().toISOString(),followUpAt:isoDate(data.followUpAt),expected:clean(data.expected),notes:clean(data.notes),status:'OPEN',area:'osobní',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),followUpCount:0,followUpHistory:[]};s.delegations.push(created)},{undo:true,cloud:true,audit:true});event670('created',created?.id||null);toast('Čekání přidáno.');return created}
function heroHtml(m){const x=m.top;if(!x)return`<section class="waiting670-hero"><span class="waiting670-kicker">STAV</span><h3>Na nic důležitého nečekáš.</h3><p>Waiting Center je čistý.</p></section>`;const needs=['overdue','today','unscheduled'].includes(x.status);return`<section class="waiting670-hero ${h(x.status)}"><span class="waiting670-kicker">${needs?'ŘEŠIT JAKO PRVNÍ':'NEJSTARŠÍ OTEVŘENÉ ČEKÁNÍ'}</span><h3>${h(x.title)}</h3><p>${h(x.expected||'Čekáš na reakci druhé strany.')}</p><div class="waiting670-chips"><span class="waiting670-chip">Na tahu: ${h(x.who)}</span><span class="waiting670-chip">${h(x.label)}</span><span class="waiting670-chip">čekáš ${x.age===null?'?':`${x.age} d`}</span><span class="waiting670-chip">follow-up ${x.followups}×</span></div><button class="primary" data-waiting670-follow="${h(x.id)}">${needs?'Udělám follow-up':'Otevřít follow-up'} →</button></section>`}
function metric(key,label,value,sub){return`<button class="waiting670-metric ${activeFilter===key?'active':''}" data-waiting670-filter="${key}"><span>${h(label)}</span><b>${Number(value||0)}</b><small>${h(sub)}</small></button>`}
function rowHtml(x){const search=clean(`${x.title} ${x.who} ${x.expected} ${x.notes}`).toLowerCase();return`<article class="waiting670-row" data-waiting670-row="${h(x.id)}" data-status="${h(x.status)}" data-search="${h(search)}"><div class="waiting670-status"><b>${h(x.label)}</b><small>${x.followups}× follow-up</small></div><div class="waiting670-main"><h4>${h(x.title)}</h4><p>${h(x.expected||x.notes||'Čekáš na reakci / výstup druhé strany.')}</p></div><div class="waiting670-person"><b>${h(x.who)}</b><small>${h(x.channel||'kanál neurčen')}</small></div><div class="waiting670-age"><b>${x.age===null?'—':`${x.age} dní`}</b><small>od ${h(fmt(x.since))}</small></div><div class="waiting670-next"><b>${h(fmt(x.followUpAt))}</b><small>naposledy ${h(fmtTime(x.lastFollowUpAt))}</small></div><div class="waiting670-row-actions"><button class="primary" data-waiting670-follow="${h(x.id)}">Follow-up</button><button data-waiting670-postpone="${h(x.id)}">+3 d</button><button data-waiting670-edit="${h(x.id)}">Upravit</button><button data-waiting670-done="${h(x.id)}">Vyřešeno</button></div></article>`}
function pageHtml(m){return`<div class="waiting670-shell" data-waiting-hub670><header class="waiting670-head"><div><small>OS670 · WAITING CENTER 2.0</small><h2>Na koho čekám.</h2><p>Každé čekání má protistranu, stáří, očekávaný výstup, další kontrolu a historii follow-upů. Nic se neposílá automaticky.</p></div><div class="waiting670-actions"><button data-waiting670-add>+ Přidat čekání</button><button data-waiting670-inbox>Otevřít Inbox</button><button data-waiting670-close>Zavřít</button></div></header><div class="waiting670-hero-grid">${heroHtml(m)}<aside class="waiting670-health"><div class="waiting670-kicker">DISCIPLÍNA</div><div class="waiting670-health-row"><span>Po termínu</span><b class="${m.counts.overdue?'waiting670-bad':'waiting670-good'}">${m.counts.overdue}</b></div><div class="waiting670-health-row"><span>Follow-up dnes</span><b class="${m.counts.today?'waiting670-warn':'waiting670-good'}">${m.counts.today}</b></div><div class="waiting670-health-row"><span>Bez další kontroly</span><b class="${m.counts.unscheduled?'waiting670-warn':'waiting670-good'}">${m.counts.unscheduled}</b></div><div class="waiting670-health-row"><span>Kontaktováno za 7 dní</span><b>${m.counts.recent}</b></div></aside></div><section class="waiting670-metrics">${metric('all','Celkem',m.counts.all,'otevřených čekání')}${metric('overdue','Po termínu',m.counts.overdue,'urgovat')}${metric('today','Dnes',m.counts.today,'follow-up dnes')}${metric('soon','Do 3 dní',m.counts.soon,'blížící kontrola')}${metric('unscheduled','Bez termínu',m.counts.unscheduled,'doplnit kontrolu')}</section><section class="waiting670-tools"><div class="waiting670-filters"><button class="waiting670-filter ${activeFilter==='all'?'active':''}" data-waiting670-filter="all">Vše</button><button class="waiting670-filter ${activeFilter==='overdue'?'active':''}" data-waiting670-filter="overdue">Po termínu</button><button class="waiting670-filter ${activeFilter==='today'?'active':''}" data-waiting670-filter="today">Dnes</button><button class="waiting670-filter ${activeFilter==='soon'?'active':''}" data-waiting670-filter="soon">Do 3 dní</button><button class="waiting670-filter ${activeFilter==='unscheduled'?'active':''}" data-waiting670-filter="unscheduled">Bez termínu</button></div><input class="waiting670-search" data-waiting670-search value="${h(query)}" placeholder="Hledat podle osoby, firmy nebo věci…"></section><section class="waiting670-list">${m.rows.map(rowHtml).join('')||'<div class="waiting670-empty"><b>Čisto.</b>Nemáš žádné otevřené čekání.</div>'}<div class="waiting670-empty waiting670-hidden" data-waiting670-empty><b>Nic nenalezeno.</b>Zkus jiný filtr nebo hledání.</div></section><div class="waiting670-note">„Follow-up“ pouze zapíše, že ses připomněl, a nastaví další kontrolu. Kamil OS neposílá e-mail ani zprávu bez tvé explicitní akce.</div></div>`}
function applyFilters(){if(!currentRoot)return;let visible=0,q=clean(query).toLowerCase();currentRoot.querySelectorAll('[data-waiting670-filter]').forEach(b=>b.classList.toggle('active',b.dataset.waiting670Filter===activeFilter));currentRoot.querySelectorAll('[data-waiting670-row]').forEach(r=>{const okFilter=activeFilter==='all'||r.dataset.status===activeFilter,okQuery=!q||String(r.dataset.search||'').includes(q),show=okFilter&&okQuery;r.classList.toggle('waiting670-hidden',!show);if(show)visible++});currentRoot.querySelector('[data-waiting670-empty]')?.classList.toggle('waiting670-hidden',visible!==0||!currentModel?.rows?.length)}
function closeHub(){currentRoot?.closest('.waiting670-modal')?.remove();currentRoot=null;currentModel=null}
function refreshHub(){if(!currentRoot)return;currentModel=buildWaitingModel670();currentRoot.outerHTML=pageHtml(currentModel);currentRoot=document.querySelector('[data-waiting-hub670]');bindRoot();applyFilters();window.__KAMIL_WAITING_HUB670__={version:VERSION,healthy:true,model:currentModel,refresh:refreshHub,open:openWaitingHub670,at:Date.now()}}
async function followMenu(id){const row=currentModel?.rows.find(x=>x.id===id)||rowFrom(locate(store.get(),id)||{});if(!row?.id)return;const body=`<div class="card"><div class="eyebrow">FOLLOW-UP</div><h3>${h(row.title)}</h3><p>${h(row.expected||'Čekáš na reakci druhé strany.')}</p><div class="decision-note"><b>Na tahu:</b> ${h(row.who)} · čekáš ${row.age===null?'?':`${row.age} dní`} · follow-up ${row.followups}×</div></div>`;const choice=await modal('Follow-up čekání',body,[{label:'Zapsat +1 den',value:'1',primary:row.status==='overdue'},{label:'Zapsat +3 dny',value:'3',primary:row.status!=='overdue'},{label:'Zapsat +7 dní',value:'7'},{label:'Kopírovat text',value:'copy'},{label:'Zavřít',value:null}]);if(choice==='copy'){await copyText(followText(row));return}if(['1','3','7'].includes(String(choice))){recordWaitingFollowUp670(id,Number(choice));toast(`Follow-up zapsán. Další kontrola za ${choice} ${choice==='1'?'den':'dny'}.`);refreshHub()}}
function bindRoot(){if(!currentRoot)return;currentRoot.querySelectorAll('[data-waiting670-filter]').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.waiting670Filter||'all';applyFilters()}));const input=currentRoot.querySelector('[data-waiting670-search]');input?.addEventListener('input',()=>{query=input.value||'';applyFilters()});currentRoot.querySelectorAll('[data-waiting670-follow]').forEach(b=>b.addEventListener('click',()=>followMenu(b.dataset.waiting670Follow)));currentRoot.querySelectorAll('[data-waiting670-postpone]').forEach(b=>b.addEventListener('click',()=>{postponeWaiting670(b.dataset.waiting670Postpone,3);toast('Další kontrola za 3 dny.');refreshHub()}));currentRoot.querySelectorAll('[data-waiting670-edit]').forEach(b=>b.addEventListener('click',async()=>{await editWaiting670(b.dataset.waiting670Edit);refreshHub()}));currentRoot.querySelectorAll('[data-waiting670-done]').forEach(b=>b.addEventListener('click',async()=>{const id=b.dataset.waiting670Done,row=currentModel?.rows.find(x=>x.id===id),choice=await modal('Uzavřít čekání',`<div class="card"><b>${h(row?.title||'Čekání')}</b><p class="muted">Označit jako vyřešené a vrátit případný zdrojový úkol z režimu čekání?</p></div>`,[{label:'Ano, vyřešeno',value:'yes',primary:true},{label:'Zrušit',value:null}]);if(choice==='yes'){resolveWaiting670(id);toast('Čekání uzavřeno.');refreshHub()}}));currentRoot.querySelector('[data-waiting670-add]')?.addEventListener('click',async()=>{await createWaiting670();refreshHub()});currentRoot.querySelector('[data-waiting670-inbox]')?.addEventListener('click',()=>{closeHub();window.dispatchEvent(new CustomEvent('kamil:navigate',{detail:'inbox'}));setTimeout(()=>window.dispatchEvent(new CustomEvent('kamil:focus610',{detail:{target:'inbox',focus:'inbox-waiting'}})),180)});currentRoot.querySelector('[data-waiting670-close]')?.addEventListener('click',closeHub)}
export function openWaitingHub670(){ensureCss();closeHub();currentModel=buildWaitingModel670();const wrap=document.createElement('div');wrap.className='waiting670-modal';wrap.innerHTML=pageHtml(currentModel);wrap.addEventListener('click',e=>{if(e.target===wrap)closeHub()});document.body.appendChild(wrap);currentRoot=wrap.querySelector('[data-waiting-hub670]');bindRoot();applyFilters();window.__KAMIL_WAITING_HUB670__={version:VERSION,healthy:true,model:currentModel,refresh:refreshHub,open:openWaitingHub670,at:Date.now()};return true}
export function installWaitingHub670(){ensureCss();if(boundGlobal)return true;boundGlobal=true;window.addEventListener('kamil:focus610',e=>{if(e?.detail?.focus==='waiting-center')openWaitingHub670()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('.waiting670-modal'))closeHub()});return true}
