import {store} from './state.js';
import {buildFinanceCommand258} from './financeCommand258.js';
import {buildLifeTimeline303} from './lifeTimeline303.js';
import {buildFollowUpEngine303} from './followUpEngine303.js';
const money=n=>`${Math.round(Number(n)||0).toLocaleString('cs-CZ')} Kč`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function mount(host,key,html){if(!host)return;let el=host.querySelector(`[data-${key}]`);if(!el){el=document.createElement('section');el.dataset[key]='1';host.prepend(el)}el.innerHTML=html}
function finance(){const m=buildFinanceCommand258(store.get()),top=m.positions?.[0],review=m.review?.[0];mount(document.querySelector('#moneyView'),'workspace305Money',`<div class="ws305 ws305-money"><div class="ws305-eyebrow">MONEY COCKPIT</div><div class="ws305-hero"><div><span>Čisté jmění</span><strong>${money(m.netWorth)}</strong><small>${money(m.cash)} likvidní hotovost</small></div><div class="ws305-signal"><span>Volný kapitál</span><b>${money(m.deployable)}</b><small>nad rezervu</small></div></div><div class="ws305-strip"><div><span>Investice</span><b>${money(m.investments)}</b></div><div><span>Majetek</span><b>${money(m.assets)}</b></div><div><span>Měsíční závazky</span><b>${money(m.monthlyOut)}</b></div><div><span>Top pozice</span><b>${esc(top?.ticker||top?.name||'—')}</b></div></div>${review?`<button class="ws305-callout" data-open305="finance"><span>Nejdůležitější review</span><b>${esc(review.name)} · ${esc(review.action)}</b><small>${esc(review.reason)}</small></button>`:''}</div>`)}
function retireTicketWorkspace(){document.querySelectorAll('#ticketIntelView [data-workspace305-tickets]').forEach(x=>x.remove())}
function life(){const s=store.get(),t=buildLifeTimeline303(s),f=buildFollowUpEngine303(s),admin=(s.personalAdmin?.items||[]).filter(x=>!['DONE','CLOSED','ARCHIVED'].includes(String(x.status||'').toUpperCase())).length;mount(document.querySelector('#ticketsView'),'workspace305Life',`<div class="ws305 ws305-life"><div class="ws305-eyebrow">LIFE HUB</div><div class="ws305-hero"><div><span>Život bez chaosu</span><strong>${t.today.length+t.week.length} věcí v horizontu</strong><small>${t.overdue.length} po termínu · ${admin} administrativa</small></div><div class="ws305-signal ${f.overdue.length?'bad':''}"><span>Follow-up radar</span><b>${f.rows.length}</b><small>${f.overdue.length?`${f.overdue.length} po termínu`:'vše pod kontrolou'}</small></div></div><div class="ws305-strip"><div><span>Dnes</span><b>${t.today.length}</b></div><div><span>Tento týden</span><b>${t.week.length}</b></div><div><span>Čekám</span><b>${f.rows.length}</b></div><div><span>Administrativa</span><b>${admin}</b></div></div></div>`)}
function today(){const root=document.querySelector('#todayView');if(!root)return;root.dataset.workspace305Today='1'}
function enhance(){finance();retireTicketWorkspace();life();today();window.__KAMIL_WORKSPACES305__={version:305,at:Date.now(),ticketOwnership:'retired'}}
function actions(){document.addEventListener('click',e=>{const b=e.target.closest?.('[data-open305]');if(!b)return;if(b.dataset.open305==='finance')window.dispatchEvent(new Event('kamil:open-finance-command'))},true)}
let timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(enhance,120)};
export function installWorkspaces305(){if(!document.querySelector('link[data-workspaces305]')){const l=document.createElement('link');l.rel='stylesheet';l.href='./workspaces305.css';l.dataset.workspaces305='1';document.head.appendChild(l)}actions();enhance();store.subscribe?.(schedule);window.addEventListener('kamil:view-change',schedule);new MutationObserver(schedule).observe(document.querySelector('main')||document.body,{childList:true,subtree:true});setTimeout(schedule,600)}
