import {store} from './state.js';
import {buildFinanceCommand258} from './financeCommand258.js';
import {buildTicketCommand268} from './ticketCommand268.js';
import {buildLifeTimeline303} from './lifeTimeline303.js';
import {buildFollowUpEngine303} from './followUpEngine303.js';
const money=n=>`${Math.round(Number(n)||0).toLocaleString('cs-CZ')} Kč`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function mount(host,key,html){if(!host)return;let el=host.querySelector(`[data-${key}]`);if(!el){el=document.createElement('section');el.dataset[key]='1';host.prepend(el)}el.innerHTML=html}
function finance(){const m=buildFinanceCommand258(store.get()),top=m.positions?.[0],review=m.review?.[0];mount(document.querySelector('#moneyView'),'workspace305Money',`<div class="ws305 ws305-money"><div class="ws305-eyebrow">MONEY COCKPIT</div><div class="ws305-hero"><div><span>Čisté jmění</span><strong>${money(m.netWorth)}</strong><small>${money(m.cash)} likvidní hotovost</small></div><div class="ws305-signal"><span>Volný kapitál</span><b>${money(m.deployable)}</b><small>nad rezervu</small></div></div><div class="ws305-strip"><div><span>Investice</span><b>${money(m.investments)}</b></div><div><span>Majetek</span><b>${money(m.assets)}</b></div><div><span>Měsíční závazky</span><b>${money(m.monthlyOut)}</b></div><div><span>Top pozice</span><b>${esc(top?.ticker||top?.name||'—')}</b></div></div>${review?`<button class="ws305-callout" data-open305="finance"><span>Nejdůležitější review</span><b>${esc(review.name)} · ${esc(review.action)}</b><small>${esc(review.reason)}</small></button>`:''}</div>`)}
function tickets(){const m=buildTicketCommand268(store.get()),best=m.opportunities?.[0],hot=m.active?.slice().sort((a,b)=>(a.daysTo??999)-(b.daysTo??999))[0];const projectedProfit=(m.projected||0)-(m.invested||0);mount(document.querySelector('#ticketIntelView'),'workspace305Tickets',`<div class="ws305 ws305-tickets"><div class="ws305-eyebrow">TICKET TRADING DESK</div><div class="ws305-hero"><div><span>Kapitál v trhu</span><strong>${money(m.invested)}</strong><small>${m.active.length} aktivních pozic</small></div><div class="ws305-signal ${projectedProfit>=0?'good':'bad'}"><span>Projektovaný výsledek</span><b>${money(projectedProfit)}</b><small>před realizací</small></div></div><div class="ws305-strip"><div><span>Realizovaný zisk</span><b>${money(m.realized)}</b></div><div><span>BUY READY</span><b>${m.opportunities.length}</b></div><div><span>BUY blokováno</span><b>${m.blocked.length}</b></div><div><span>Nejbližší akce</span><b>${hot?.daysTo!=null?`${hot.daysTo} dní`:'—'}</b></div></div>${best?`<button class="ws305-callout buy" data-open305="tickets"><span>Nejlepší BUY kandidát</span><b>${esc(best.name||best.event||'Příležitost')}</b><small>safe max ${money(best.netSafeMaxBuyPrice||best.maxBuyPrice)}</small></button>`:'<button class="ws305-callout" data-open305="tickets"><span>Trh</span><b>Žádný bezpečný BUY signál</b><small>Otevři Trading Desk pro aktivní portfolio.</small></button>'}</div>`)}
function life(){const s=store.get(),t=buildLifeTimeline303(s),f=buildFollowUpEngine303(s),admin=(s.personalAdmin?.items||[]).filter(x=>!['DONE','CLOSED','ARCHIVED'].includes(String(x.status||'').toUpperCase())).length;mount(document.querySelector('#ticketsView'),'workspace305Life',`<div class="ws305 ws305-life"><div class="ws305-eyebrow">LIFE HUB</div><div class="ws305-hero"><div><span>Život bez chaosu</span><strong>${t.today.length+t.week.length} věcí v horizontu</strong><small>${t.overdue.length} po termínu · ${admin} administrativa</small></div><div class="ws305-signal ${f.overdue.length?'bad':''}"><span>Follow-up radar</span><b>${f.rows.length}</b><small>${f.overdue.length?`${f.overdue.length} po termínu`:'vše pod kontrolou'}</small></div></div><div class="ws305-strip"><div><span>Dnes</span><b>${t.today.length}</b></div><div><span>Tento týden</span><b>${t.week.length}</b></div><div><span>Čekám</span><b>${f.rows.length}</b></div><div><span>Administrativa</span><b>${admin}</b></div></div></div>`)}
function today(){const root=document.querySelector('#todayView');if(!root)return;root.dataset.workspace305Today='1'}
function enhance(){finance();tickets();life();today();window.__KAMIL_WORKSPACES305__={version:305,at:Date.now()}}
function actions(){document.addEventListener('click',e=>{const b=e.target.closest?.('[data-open305]');if(!b)return;if(b.dataset.open305==='finance')window.dispatchEvent(new Event('kamil:open-finance-command'));if(b.dataset.open305==='tickets')window.dispatchEvent(new Event('kamil:open-ticket-command'))},true)}
let timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(enhance,120)};
export function installWorkspaces305(){if(!document.querySelector('link[data-workspaces305]')){const l=document.createElement('link');l.rel='stylesheet';l.href='./workspaces305.css';l.dataset.workspaces305='1';document.head.appendChild(l)}actions();enhance();store.subscribe?.(schedule);window.addEventListener('kamil:view-change',schedule);new MutationObserver(schedule).observe(document.querySelector('main')||document.body,{childList:true,subtree:true});setTimeout(schedule,600)}
