import {store} from './state.js';
import {h,money} from './utils.js';
import {installXtbDecision368} from './xtbDecision368.js';
import {installXtbTargets371} from './xtbTargets371.js';
import {installPositionSizing373} from './positionSizing373.js';
import {installXtbPortfolio385,xtbPortfolio385} from './xtbPortfolio385.js';
const VERSION=386,N=v=>Number(v||0),pct=v=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Math.round(Number(v)*10)/10} %`:'—',price=v=>N(v)>0?N(v).toLocaleString('cs-CZ',{maximumFractionDigits:2}):'—';
let bound=false,timer=0;
function ensureCss(){if(document.querySelector('link[data-xtb383]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./xtbCockpit383.css';l.dataset.xtb383='1';document.head.appendChild(l)}
function label(v){return({ADD:'PŘIKOUPIT',BUY:'PŘIKOUPIT',HOLD:'DRŽET',REDUCE:'REDUKOVAT',TRIM:'REDUKOVAT',SELL:'PRODAT',VERIFY:'OVĚŘIT',WAIT_EARNINGS:'POČKAT NA VÝSLEDKY'})[String(v||'').toUpperCase()]||String(v||'DRŽET').toUpperCase()}
function tone(v){v=String(v||'').toUpperCase();return v==='SELL'||v==='REDUCE'?'bad':v==='ADD'||v==='BUY'?'good':v==='VERIFY'||v==='WAIT_EARNINGS'?'warn':'neutral'}
function ladder(rows=[]){return rows.length?rows.map(x=>`${x.pct}% @ ${price(x.price)}`).join(' · '):'—'}
function topExposure(obj){const x=Object.entries(obj||{}).sort((a,b)=>N(b[1]?.pct)-N(a[1]?.pct))[0];return x?`${h(x[0])} ${Math.round(N(x[1].pct))}%`:'—'}
function coverage(x){const c=x.coverage||{},missing=(c.missing||[]).slice(0,3).map(v=>`${h(v.label)} ${v.pct}%`).join(' · ');return `<div class="xtb386-coverage"><div><span>DATA COVERAGE</span><b>${Math.round(N(c.score))}/100 · ${h(c.status||'—')}</b></div><div>${missing||'Všechny klíčové vstupy jsou pokryté.'}</div></div>`}
function card(x){const alloc=x.allocationReason?` · ${h(x.allocationReason)}`:'';return `<article class="xtb383-row"><div class="xtb383-main"><div><b>${h(x.ticker)}</b><span>${h(x.name||'')} · ${h(x.sector)} · ${h(x.currency)}</span></div><span class="xtb383-verdict ${tone(x.effectiveVerdict)}">${h(label(x.effectiveVerdict))}</span></div><div class="xtb383-grid"><div><span>Aktuální</span><b>${price(x.current)}</b></div><div><span>Váha → cíl</span><b>${x.weightPct}% → ${x.targetWeightPct}%</b></div><div><span>Rebalance</span><b>${x.rebalanceAmount>0?`+${money(x.rebalanceAmount)}`:x.rebalanceAmount<0?money(x.rebalanceAmount):'—'}</b></div><div><span>Quality / akce</span><b>${Math.round(N(x.qualityScore))} / ${Math.round(N(x.actionScore))}</b></div><div><span>Upside</span><b>${x.expected.upsidePct===null?'—':pct(x.expected.upsidePct)}</b></div><div><span>Risk / reward</span><b>${x.expected.ratio===null?'—':`${x.expected.ratio}×`}</b></div><div><span>Drawdown</span><b>${x.drawdown.pct===null?'—':pct(x.drawdown.pct)}</b></div><div><span>Doporučený nákup</span><b>${N(x.recommendedAmount)>0?money(x.recommendedAmount):'—'}</b></div></div><div class="xtb385-ladders"><div><span>Nákupní žebřík</span><b>${ladder(x.buyLadder)}</b></div><div><span>Prodejní žebřík</span><b>${ladder(x.sellLadder.filter(v=>v.step!=='protect'))}</b></div></div><div class="xtb383-note"><span>${x.fresh?'CENA ČERSTVÁ':'CENA ORIENTAČNÍ'}</span>${h(x.gateReason||x.reason||'Bez silného signálu ke změně pozice.')} · Koncentrace ${h(x.concentration)} · ${h(x.profitProtection.label)}${x.earningsDays!==null?` · výsledky za ${x.earningsDays} d.`:''}${alloc}</div></article>`}
function actionQueue(x){const rows=x.rows.filter(r=>(r.effectiveVerdict==='ADD'&&r.recommendedAmount>0)||['REDUCE','SELL'].includes(r.effectiveVerdict)).slice().sort((a,b)=>b.actionScore-a.actionScore).slice(0,5);if(!rows.length)return '<div class="xtb383-note"><span>AKČNÍ FRONTA</span>Žádná potvrzená změna portfolia.</div>';return `<div class="xtb383-note"><span>AKČNÍ FRONTA</span>${rows.map((r,i)=>`${i+1}. <b>${h(r.ticker)}</b> ${h(label(r.effectiveVerdict))}${N(r.recommendedAmount)>0?` ${money(r.recommendedAmount)}`:''}`).join(' &nbsp;→&nbsp; ')}</div>`}
function deployment(x){if(!x.deployment.length)return '<div class="xtb383-note"><span>CASH PLAN</span>Teď není potvrzený nákup, kterému by měl být přidělen kapitál.</div>';return `<div class="xtb386-plan"><div class="xtb383-note"><span>CASH PLAN</span>${x.deployment.map(v=>`<b>${h(v.ticker)}</b> ${money(v.amount)}${v.priceLimit?` pod ${price(v.priceLimit)}`:''}`).join(' · ')}</div>${x.deployment.map(v=>`<div class="xtb386-planrow"><b>${h(v.ticker)}</b>${(v.steps||[]).map(s=>`<span>${s.pct}% · ${money(s.amount)} @ ${price(s.price)}</span>`).join('')}</div>`).join('')}</div>`}
function scenarioLine(x){return x.scenarios.map(v=>`${h(v.name)} ${money(v.impact)}`).join(' · ')}
function render(){const host=document.querySelector('#moneyView');if(!host)return;let sec=host.querySelector('[data-xtb-cockpit383]');if(!sec){sec=document.createElement('section');sec.dataset.xtbCockpit383='1';sec.className='xtb383';host.prepend(sec)}const x=window.__KAMIL_XTB_PORTFOLIO385__?.model||xtbPortfolio385(store.get()),actions=x.rows.filter(r=>(r.effectiveVerdict==='ADD'&&r.recommendedAmount>0)||['REDUCE','SELL'].includes(r.effectiveVerdict)).length;sec.innerHTML=`<div class="xtb383-head"><div><div class="eyebrow">XTB COMMAND CENTER · OS386</div><h2>${h(x.today.title)}</h2><p>${h(x.today.detail)} Nic se neobchoduje automaticky.</p></div><div class="xtb383-status">${actions?`${actions} AKCE`:'BEZ AKCE'}</div></div><div class="xtb385-today"><b>CO UDĚLAT DNES</b><strong>${h(x.today.title)}</strong><span>${h(x.today.detail)}${N(x.today.amount)>0?` Doporučená částka ${money(x.today.amount)}.`:''}</span></div><div class="xtb383-stats"><div><span>Portfolio</span><b>${money(x.totalValue)}</b></div><div><span>Volný kapitál</span><b>${x.cashAvailable?money(x.cashAvailable):'není zadaný'}</b></div><div><span>Nasadit</span><b>${x.deployable?money(x.deployable):'—'}</b></div><div><span>Zůstane po plánu</span><b>${x.remainingCash===null?'—':money(x.remainingCash)}</b></div><div><span>Historická úspěšnost</span><b>${x.performance.hitRate===null?'čeká na historii':`${x.performance.hitRate}%`}</b></div></div>${coverage(x)}<div class="xtb385-risk"><div><span>FX expozice</span><b>${topExposure(x.currencyExposure)}</b></div><div><span>Největší sektor</span><b>${topExposure(x.sectorExposure)}</b></div><div><span>Position guard</span><b>${x.concentrationAlerts.length?`${x.concentrationAlerts.length} nad 12 %`:'OK'}</b></div><div><span>Sector guard</span><b>${x.sectorAlerts.length?`${x.sectorAlerts.length} nad 30 %`:'OK'}</b></div></div>${actionQueue(x)}${deployment(x)}<div class="xtb383-note"><span>STRESS TEST</span>${scenarioLine(x)}</div>${x.rotation?`<div class="xtb383-note"><span>ROTACE</span>${h(x.rotation.reason)}</div>`:''}<div class="xtb383-list">${x.rows.length?x.rows.map(card).join(''):'<div class="xtb383-empty">XTB data zatím nejsou načtená. Po importu se zde objeví celé portfolio.</div>'}</div>`;window.__KAMIL_XTB_COCKPIT383__={version:VERSION,healthy:true,model:x,at:Date.now()};document.documentElement.dataset.xtbCockpit383='1'}
function schedule(ms=80){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installXtbCockpit383(){ensureCss();installXtbDecision368();installXtbTargets371();installPositionSizing373();installXtbPortfolio385();if(!bound){bound=true;for(const ev of ['kamil:xtb-decision368-updated','kamil:xtb-targets371-updated','kamil:position-sizing373-updated','kamil:xtb-portfolio385-updated','kamil:market-quotes'])window.addEventListener(ev,()=>schedule());store.subscribe?.(()=>schedule(120))}schedule();setTimeout(()=>schedule(),1000)}
