import {store} from './state.js';
import {h,money} from './utils.js';
import {installXtbDecision368} from './xtbDecision368.js';
import {installXtbTargets371} from './xtbTargets371.js';
import {installPositionSizing373} from './positionSizing373.js';
import {installXtbPortfolio385} from './xtbPortfolio385.js';
import {installXtbStability388} from './xtbStability388.js';
import {installXtbCalibration389} from './xtbCalibration389.js';
import {installXtbExecution390,xtbExecution390,recordXtbExecution390} from './xtbExecution390.js';
const VERSION=390,N=v=>Number(v||0),pct=v=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Math.round(Number(v)*10)/10} %`:'—',price=v=>N(v)>0?N(v).toLocaleString('cs-CZ',{maximumFractionDigits:2}):'—';
let bound=false,timer=0;
function ensureCss(){if(document.querySelector('link[data-xtb383]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./xtbCockpit383.css';l.dataset.xtb383='1';document.head.appendChild(l)}
function label(v){return({ADD:'PŘIKOUPIT',BUY:'PŘIKOUPIT',HOLD:'DRŽET',REDUCE:'REDUKOVAT',TRIM:'REDUKOVAT',SELL:'PRODAT',VERIFY:'OVĚŘIT',WAIT_EARNINGS:'POČKAT NA VÝSLEDKY'})[String(v||'').toUpperCase()]||String(v||'DRŽET').toUpperCase()}
function tone(v){v=String(v||'').toUpperCase();return v==='SELL'||v==='REDUCE'?'bad':v==='ADD'||v==='BUY'?'good':v==='VERIFY'||v==='WAIT_EARNINGS'?'warn':'neutral'}
function ladder(rows=[]){return rows.length?rows.map(x=>`${x.pct}% @ ${price(x.price)}`).join(' · '):'—'}
function calibration(x){return x?.base||x}
function stability(x){const c=calibration(x);return c?.base||c}
function portfolio(x){const s=stability(x);return s?.base||s}
function topExposure(obj){const x=Object.entries(obj||{}).sort((a,b)=>N(b[1]?.pct)-N(a[1]?.pct))[0];return x?`${h(x[0])} ${Math.round(N(x[1].pct))}%`:'—'}
function coverage(x){const p=portfolio(x),c=p.coverage||{},missing=(c.missing||[]).slice(0,3).map(v=>`${h(v.label)} ${v.pct}%`).join(' · ');return `<div class="xtb386-coverage"><div><span>DATA COVERAGE</span><b>${Math.round(N(c.score))}/100 · ${h(c.status||'—')}</b></div><div>${missing||'Všechny klíčové vstupy jsou pokryté.'}</div></div>`}
function riskBar(x){const p=portfolio(x),s=window.__KAMIL_POSITION_SIZING373__?.model||{},reserve=N(s.riskReserveAmount),reservePct=s.riskReservePct,deployable=s.deployableCash,fresh=s.freshPriceRatio,coverageScore=N(p.coverage?.score),blocked=(p.rows||[]).filter(r=>r.effectiveVerdict==='VERIFY'||r.effectiveVerdict==='WAIT_EARNINGS').length;let state='READY',detail='Data dovolují standardní plán.';if(coverageScore<65||fresh<50){state='OPATRNĚ';detail='Slabší data drží větší část hotovosti v rezervě.'}if(!p.rows?.length||fresh===0){state='BLOKOVÁNO';detail='Bez čerstvých cen nevytvářím nákupní plán.'}return `<div class="xtb387-riskbar"><div><span>DECISION HEALTH</span><b>${state}</b><small>${h(detail)}</small></div><div><span>RIZIKOVÁ REZERVA</span><b>${reservePct===null||reservePct===undefined?'—':`${reservePct}% · ${money(reserve)}`}</b><small>Nasaditelný cash ${deployable===null||deployable===undefined?'—':money(deployable)}</small></div><div><span>ČERSTVÉ CENY</span><b>${fresh===null||fresh===undefined?'—':`${fresh}%`}</b><small>${blocked} pozic čeká na ověření / výsledky</small></div></div>`}
function stabilityBar(x){const s=stability(x).summary||{};return `<div class="xtb388-stability"><div><span>SIGNAL STABILITY</span><b>${N(s.pending)?'ČEKÁ NA POTVRZENÍ':'STABILNÍ'}</b></div><div><span>Potvrzené akce</span><b>${N(s.confirmed)}</b></div><div><span>Nové / nepotvrzené</span><b>${N(s.pending)}</b></div><div><span>Změny signálu</span><b>${N(s.flipCount)}</b></div></div>`}
function calibrationBar(x){const c=calibration(x),s=c.summary||{},stats=c.performance||{},rate=k=>stats[k]?.hitRate===null||stats[k]?.hitRate===undefined?'—':`${stats[k].hitRate}%`;return `<div class="xtb389-calibration"><div><span>CONVICTION CALIBRATION</span><b>${N(s.blocked)?'FILTRUJE':'READY'}</b><small>${N(s.blocked)} blokováno · ${N(s.caution)} opatrně</small></div><div><span>BUY HIT RATE</span><b>${rate('ADD')}</b><small>${N(stats.ADD?.evaluated)} vyhodnocení</small></div><div><span>SELL HIT RATE</span><b>${rate('SELL')}</b><small>${N(stats.SELL?.evaluated)} vyhodnocení</small></div><div><span>OVERTRADE GUARD</span><b>24 H</b><small>upside ≥5 % · R/R ≥1,2×</small></div></div>`}
function executionBar(x){const last=x.last?.[0];return `<div class="xtb390-execution"><div><span>EXECUTION JOURNAL</span><b>${x.todayCount?`${x.todayCount} DNES`:'BEZ PROVEDENÉ AKCE'}</b><small>Ruční potvrzení pouze zapisuje akci; nic neposílá brokerovi.</small></div><div><span>Dnes potvrzeno</span><b>${x.todayAmount?money(x.todayAmount):'—'}</b><small>${last?`Poslední: ${h(last.ticker)} ${h(label(last.action))}`:'Zatím bez záznamu'}</small></div></div>`}
function execButton(x){const action=String(x.effectiveVerdict||'').toUpperCase(),ready=['ADD','REDUCE','SELL'].includes(action)&&x.calibration?.status!=='BLOCKED';if(!ready)return'';return `<button type="button" class="xtb390-done" data-xtb-exec390 data-ticker="${h(x.ticker)}" data-action="${h(action)}" data-amount="${N(x.recommendedAmount)}" data-price="${N(x.current)}">Označit jako provedeno</button>`}
function card(x){const alloc=x.allocationReason?` · ${h(x.allocationReason)}`:'',st=x.stability,stText=st&&['ADD','REDUCE','SELL'].includes(String(x.effectiveVerdict).toUpperCase())?` · Signál ${st.stable?`potvrzen (${st.streak}×)`:`čeká na potvrzení (${st.streak}×)`}`:'',cal=x.calibration||{},calText=cal.status?` · Kalibrace ${h(cal.status)}${cal.reason?`: ${h(cal.reason)}`:''}`:'',last=x.lastExecution?` · Poslední ručně potvrzená akce ${new Date(x.lastExecution.at).toLocaleString('cs-CZ')}`:'';return `<article class="xtb383-row"><div class="xtb383-main"><div><b>${h(x.ticker)}</b><span>${h(x.name||'')} · ${h(x.sector)} · ${h(x.currency)}</span></div><div class="xtb390-action"><span class="xtb383-verdict ${tone(x.effectiveVerdict)}">${h(label(x.effectiveVerdict))}</span>${execButton(x)}</div></div><div class="xtb383-grid"><div><span>Aktuální</span><b>${price(x.current)}</b></div><div><span>Váha → cíl</span><b>${x.weightPct}% → ${x.targetWeightPct}%</b></div><div><span>Rebalance</span><b>${x.rebalanceAmount>0?`+${money(x.rebalanceAmount)}`:x.rebalanceAmount<0?money(x.rebalanceAmount):'—'}</b></div><div><span>Quality / kalibrace</span><b>${Math.round(N(x.qualityScore))} / ${Math.round(N(x.calibratedActionScore||x.actionScore))}</b></div><div><span>Upside</span><b>${x.expected?.upsidePct===null||x.expected?.upsidePct===undefined?'—':pct(x.expected.upsidePct)}</b></div><div><span>Risk / reward</span><b>${x.expected?.ratio===null||x.expected?.ratio===undefined?'—':`${x.expected.ratio}×`}</b></div><div><span>Drawdown</span><b>${x.drawdown?.pct===null||x.drawdown?.pct===undefined?'—':pct(x.drawdown.pct)}</b></div><div><span>Doporučený nákup</span><b>${N(x.recommendedAmount)>0&&cal.status!=='BLOCKED'?money(x.recommendedAmount):'—'}</b></div></div><div class="xtb385-ladders"><div><span>Nákupní žebřík</span><b>${ladder(x.buyLadder)}</b></div><div><span>Prodejní žebřík</span><b>${ladder((x.sellLadder||[]).filter(v=>v.step!=='protect'))}</b></div></div><div class="xtb383-note"><span>${x.fresh?'CENA ČERSTVÁ':'CENA ORIENTAČNÍ'}</span>${h(x.gateReason||x.reason||'Bez silného signálu ke změně pozice.')} · Koncentrace ${h(x.concentration)} · ${h(x.profitProtection?.label||'Bez zvláštní ochrany')}${x.earningsDays!==null&&x.earningsDays!==undefined?` · výsledky za ${x.earningsDays} d.`:''}${alloc}${stText}${calText}${last}</div></article>`}
function actionQueue(x){const c=calibration(x),rows=(x.rows||[]).filter(r=>['ADD','REDUCE','SELL'].includes(String(r.effectiveVerdict).toUpperCase())&&r.calibration?.status!=='BLOCKED').slice().sort((a,b)=>N(b.calibratedActionScore)-N(a.calibratedActionScore)).slice(0,5);if(!rows.length)return `<div class="xtb383-note"><span>AKČNÍ FRONTA</span>${N(c.summary?.blocked)?'Akční signály odfiltrovala kalibrace / cooldown.':'Žádná potvrzená změna portfolia.'}</div>`;return `<div class="xtb383-note"><span>AKČNÍ FRONTA</span>${rows.map((r,i)=>`${i+1}. <b>${h(r.ticker)}</b> ${h(label(r.effectiveVerdict))}${N(r.recommendedAmount)>0?` ${money(r.recommendedAmount)}`:''} · ${Math.round(N(r.calibratedActionScore))}/100`).join(' &nbsp;→&nbsp; ')}</div>`}
function deployment(x){const rows=calibration(x).deployment||[];if(!rows.length)return '<div class="xtb383-note"><span>CASH PLAN</span>Žádný nákup neprošel stabilitou, edge filtrem a cooldownem.</div>';return `<div class="xtb386-plan"><div class="xtb383-note"><span>CASH PLAN · KALIBROVÁNO</span>${rows.map(v=>`<b>${h(v.ticker)}</b> ${money(v.amount)}${v.priceLimit?` pod ${price(v.priceLimit)}`:''}`).join(' · ')}</div>${rows.map(v=>`<div class="xtb386-planrow"><b>${h(v.ticker)}</b>${(v.steps||[]).map(s=>`<span>${s.pct}% · ${money(s.amount)} @ ${price(s.price)}</span>`).join('')}</div>`).join('')}</div>`}
function scenarioLine(x){const p=portfolio(x);return (p.scenarios||[]).map(v=>`${h(v.name)} ${money(v.impact)}`).join(' · ')}
function bindExecution(sec){sec.querySelectorAll('[data-xtb-exec390]').forEach(btn=>btn.addEventListener('click',()=>{if(btn.disabled)return;btn.disabled=true;btn.textContent='Zapsáno ✓';recordXtbExecution390(btn.dataset.ticker,btn.dataset.action,{amount:N(btn.dataset.amount),price:N(btn.dataset.price)});setTimeout(()=>schedule(20),60)}))}
function render(){const host=document.querySelector('#moneyView');if(!host)return;let sec=host.querySelector('[data-xtb-cockpit383]');if(!sec){sec=document.createElement('section');sec.dataset.xtbCockpit383='1';sec.className='xtb383';host.prepend(sec)}const x=window.__KAMIL_XTB_EXECUTION390__?.model||xtbExecution390(store.get()),c=calibration(x),p=portfolio(x),actions=N(c.summary?.ready),today=c.today||p.today||{title:'Dnes nic nedělej',detail:'Bez potvrzené akce.'};sec.innerHTML=`<div class="xtb383-head"><div><div class="eyebrow">XTB COMMAND CENTER · OS390</div><h2>${h(today.title)}</h2><p>${h(today.detail)} Nic se neobchoduje automaticky.</p></div><div class="xtb383-status">${actions?`${actions} READY`:'BEZ READY AKCE'}</div></div><div class="xtb385-today"><b>CO UDĚLAT DNES</b><strong>${h(today.title)}</strong><span>${h(today.detail)}${N(today.amount)>0?` Doporučená částka ${money(today.amount)}.`:''}</span></div><div class="xtb383-stats"><div><span>Portfolio</span><b>${money(p.totalValue)}</b></div><div><span>Volný kapitál</span><b>${p.cashAvailable?money(p.cashAvailable):'není zadaný'}</b></div><div><span>Kalibrovaně nasadit</span><b>${c.deployable?money(c.deployable):'—'}</b></div><div><span>Zůstane po plánu</span><b>${c.remainingCash===null||c.remainingCash===undefined?'—':money(c.remainingCash)}</b></div><div><span>Historická úspěšnost</span><b>${p.performance?.hitRate===null||p.performance?.hitRate===undefined?'čeká na historii':`${p.performance.hitRate}%`}</b></div></div>${riskBar(x)}${stabilityBar(x)}${calibrationBar(x)}${executionBar(x)}${coverage(x)}<div class="xtb385-risk"><div><span>FX expozice</span><b>${topExposure(p.currencyExposure)}</b></div><div><span>Největší sektor</span><b>${topExposure(p.sectorExposure)}</b></div><div><span>Position guard</span><b>${p.concentrationAlerts?.length?`${p.concentrationAlerts.length} nad 12 %`:'OK'}</b></div><div><span>Sector guard</span><b>${p.sectorAlerts?.length?`${p.sectorAlerts.length} nad 30 %`:'OK'}</b></div></div>${actionQueue(x)}${deployment(x)}<div class="xtb383-note"><span>STRESS TEST</span>${scenarioLine(x)}</div>${p.rotation?`<div class="xtb383-note"><span>ROTACE</span>${h(p.rotation.reason)}</div>`:''}<div class="xtb383-list">${x.rows.length?x.rows.map(card).join(''):'<div class="xtb383-empty">XTB data zatím nejsou načtená. Po importu se zde objeví celé portfolio.</div>'}</div>`;bindExecution(sec);window.__KAMIL_XTB_COCKPIT383__={version:VERSION,healthy:true,model:x,at:Date.now()};document.documentElement.dataset.xtbCockpit383='1'}
function schedule(ms=80){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installXtbCockpit383(){ensureCss();installXtbDecision368();installXtbTargets371();installPositionSizing373();installXtbPortfolio385();installXtbStability388();installXtbCalibration389();installXtbExecution390();if(!bound){bound=true;for(const ev of ['kamil:xtb-decision368-updated','kamil:xtb-targets371-updated','kamil:position-sizing373-updated','kamil:xtb-portfolio385-updated','kamil:xtb-stability388-updated','kamil:xtb-calibration389-updated','kamil:xtb-execution390-updated','kamil:market-quotes'])window.addEventListener(ev,()=>schedule());store.subscribe?.(()=>schedule(120))}schedule();setTimeout(()=>schedule(),1000)}
