import {store} from './state.js';
import {h,money} from './utils.js';
import {installXtbDecision368,xtbDecision368} from './xtbDecision368.js';
import {installXtbTargets371,xtbTargets371} from './xtbTargets371.js';
import {installPositionSizing373,positionSizing373} from './positionSizing373.js';
const VERSION=384,N=v=>Number(v||0),pct=v=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Math.round(Number(v)*10)/10} %`:'—',price=v=>N(v)>0?N(v).toLocaleString('cs-CZ',{maximumFractionDigits:2}):'—';
let bound=false,timer=0;
function ensureCss(){if(document.querySelector('link[data-xtb383]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./xtbCockpit383.css';l.dataset.xtb383='1';document.head.appendChild(l)}
function label(v){return({ADD:'PŘIKOUPIT',BUY:'PŘIKOUPIT',HOLD:'DRŽET',REDUCE:'REDUKOVAT',TRIM:'REDUKOVAT',SELL:'PRODAT'})[String(v||'').toUpperCase()]||String(v||'DRŽET').toUpperCase()}
function tone(v){v=String(v||'').toUpperCase();return v==='SELL'||v==='REDUCE'?'bad':v==='ADD'||v==='BUY'?'good':'neutral'}
function model(){const s=store.get(),dec=window.__KAMIL_XTB_DECISION368__?.model||xtbDecision368(s),targets=window.__KAMIL_XTB_TARGETS371__?.model||xtbTargets371(s),sizing=window.__KAMIL_POSITION_SIZING373__?.model||positionSizing373(s),byTarget=new Map((targets.rows||[]).map(x=>[String(x.ticker||'').toUpperCase(),x])),bySize=new Map((sizing.rows||[]).map(x=>[String(x.ticker||'').toUpperCase(),x])),rows=(dec.positions||[]).map(x=>{const key=String(x.ticker||'').toUpperCase(),t=byTarget.get(key)?.targets||{},z=bySize.get(key)||{};return{...x,targets:t,size:z}});return{rows,dec,targets,sizing}}
function card(x){const t=x.targets||{},z=x.size||{},fresh=t.fresh===true,risks=[...(x.riskFlags||[]),...(z.riskFlags||[])],blocked=z.blockedReason?` · ${h(z.blockedReason)}`:'';return `<article class="xtb383-row"><div class="xtb383-main"><div><b>${h(x.ticker)}</b><span>${h(x.name||'')}</span></div><span class="xtb383-verdict ${tone(x.verdict)}">${h(label(x.verdict))}</span></div><div class="xtb383-grid"><div><span>Aktuální</span><b>${price(t.current)}</b></div><div><span>Přikoupit pod</span><b>${price(t.buyBelow)}</b></div><div><span>Redukovat od</span><b>${price(t.reduceFrom)}</b></div><div><span>Prodat od</span><b>${price(t.sellFrom)}</b></div><div><span>Pozice</span><b>${x.weightPct===null||x.weightPct===undefined?'—':`${Math.round(N(x.weightPct)*10)/10} %`}</b></div><div><span>P/L</span><b>${pct(x.profitPct)}</b></div><div><span>Quality</span><b>${N(z.qualityScore)?`${Math.round(N(z.qualityScore))}/100`:`${Math.round(N(x.confidence))}/100`}</b></div><div><span>Doporučený nákup</span><b>${N(z.recommendedAmount)>0?money(z.recommendedAmount):'—'}</b></div></div><div class="xtb383-note"><span>${fresh?'CENA ČERSTVÁ':'CENA ORIENTAČNÍ'}</span>${h(x.reason||'Bez silného signálu ke změně pozice.')}${blocked}${risks.length?` · Rizika: ${h([...new Set(risks)].join(', '))}`:''}</div></article>`}
function queue(x){const ranked=x.rows.filter(r=>String(r.verdict).toUpperCase()!=='HOLD').sort((a,b)=>{const az=N(a.size?.qualityScore),bz=N(b.size?.qualityScore);return bz-az||N(b.size?.recommendedAmount)-N(a.size?.recommendedAmount)||N(b.confidence)-N(a.confidence)}).slice(0,4);if(!ranked.length)return '<div class="xtb383-note"><span>DNES</span>Žádná pozice nemá dost silný signál ke změně.</div>';return `<div class="xtb383-note"><span>AKČNÍ FRONTa</span>${ranked.map((r,i)=>`${i+1}. <b>${h(r.ticker)}</b> ${h(label(r.verdict))}${N(r.size?.recommendedAmount)>0?` · ${money(r.size.recommendedAmount)}`:''}`).join(' &nbsp;→&nbsp; ')}</div>`}
function render(){const host=document.querySelector('#moneyView');if(!host)return;let sec=host.querySelector('[data-xtb-cockpit383]');if(!sec){sec=document.createElement('section');sec.dataset.xtbCockpit383='1';sec.className='xtb383';host.prepend(sec)}const x=model(),actionable=x.rows.filter(r=>String(r.verdict).toUpperCase()!=='HOLD'),fresh=x.targets.fresh||0,total=x.targets.priced||0,cash=x.sizing.cashAvailable,deploy=x.sizing.deployable,remaining=x.sizing.remainingCash;sec.innerHTML=`<div class="xtb383-head"><div><div class="eyebrow">XTB COMMAND CENTER · OS384</div><h2>Investice na jednom místě</h2><p>Verdikt, cílové ceny, priorita a kolik přikoupit. Rozpočet se přiděluje nejdřív nejsilnějším příležitostem; nic se neobchoduje automaticky.</p></div><div class="xtb383-status">${actionable.length?`${actionable.length} AKCE`:'BEZ AKCE'}</div></div><div class="xtb383-stats"><div><span>Pozic</span><b>${x.rows.length}</b></div><div><span>Čerstvé ceny</span><b>${fresh}/${total}</b></div><div><span>Volný kapitál</span><b>${cash?money(cash):'není zadaný'}</b></div><div><span>Navržené nákupy</span><b>${deploy?money(deploy):'—'}</b></div><div><span>Zůstane</span><b>${remaining===null?'—':money(remaining)}</b></div></div>${queue(x)}<div class="xtb383-list">${x.rows.length?x.rows.map(card).join(''):'<div class="xtb383-empty">XTB data zatím nejsou načtená. Po importu se zde objeví celé portfolio.</div>'}</div>`;window.__KAMIL_XTB_COCKPIT383__={version:VERSION,healthy:true,model:x,at:Date.now()};document.documentElement.dataset.xtbCockpit383='1'}
function schedule(ms=80){clearTimeout(timer);timer=setTimeout(render,ms)}
export function installXtbCockpit383(){ensureCss();installXtbDecision368();installXtbTargets371();installPositionSizing373();if(!bound){bound=true;for(const ev of ['kamil:xtb-decision368-updated','kamil:xtb-targets371-updated','kamil:position-sizing373-updated','kamil:market-quotes'])window.addEventListener(ev,()=>schedule());store.subscribe?.(()=>schedule(120))}schedule();setTimeout(()=>schedule(),900)}
