import {h,date} from './utils.js';
import {xtbBoard,xtbDataAge,xtbIntelligenceAge,actionLabel} from './live24.js';
import {xtbTradePlanner} from './xtbPlanner24.js';

const n=v=>Number(v||0);
const fmt=(v,d=2)=>Number(v||0).toLocaleString('cs-CZ',{maximumFractionDigits:d});
const when=v=>{if(!v)return '—';const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString('cs-CZ',{day:'numeric',month:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit'}):String(v)};
const safeUrl=v=>/^https?:\/\//i.test(String(v||''))?String(v):'';
const tradeText=t=>[t.ticker,t.symbol,t.instrument,t.name,t.asset,t.comment,t.note,t.side,t.type].filter(Boolean).join(' ');

export function xtbPositionDetail(s,ticker){
 const item=xtbBoard(s).find(x=>x.p.ticker===ticker);if(!item)return null;
 const {p,d}=item,planner=xtbTradePlanner(s),plan=planner.plans.find(x=>x.ticker===ticker)||null;
 const name=String(p.name||ticker),needle=String(ticker||'').toLowerCase(),nameNeedle=name.toLowerCase();
 const trades=(s.tradeJournal?.trades||[]).filter(t=>{const text=tradeText(t).toLowerCase();return text.includes(needle)||(nameNeedle.length>4&&text.includes(nameNeedle))}).slice(0,12).map(t=>({type:'trade',at:t.at||t.date||t.time||t.createdAt||t.open_time||t.close_time||null,label:t.side||t.type||t.action||'Obchod',detail:t.comment||t.note||t.instrument||t.symbol||t.ticker||name,raw:t}));
 const audit=(s.audit||[]).filter(x=>{const text=String(x.label||'').toLowerCase();return text.includes(needle)||(nameNeedle.length>4&&text.includes(nameNeedle))}).slice(0,12).map(x=>({type:'audit',at:x.at||null,label:x.label||'Akce',detail:'Uživatelská změna v Kamil OS'}));
 const history=[...trades,...audit].sort((a,b)=>new Date(b.at||0)-new Date(a.at||0)).slice(0,12);
 const sources=[...new Set((d.sourceUrls||[]).map(safeUrl).filter(Boolean))].slice(0,6);
 return {ticker,name,category:p.category||'',accountCurrency:p.accountCurrency||p.currency||'',value:n(p.value),volume:n(p.volume),openPrice:n(p.open_price),profit:n(p.net_profit),profitPct:n(p.net_profit_pct),weightPct:n(p.weightPct),decision:d,plan,sources,history,dataAge:xtbDataAge(s),liveAge:xtbIntelligenceAge(s)};
}

export function renderXtbPositionDetail(m){
 const d=m.decision,confidence=d.confidence===null||d.confidence===undefined?'—':`${Math.round(n(d.confidence))} %`,source=d.source||'AUTO',current=d.currentPrice?`${fmt(d.currentPrice,4)} ${h(d.priceCurrency||m.accountCurrency)}`:'není k dispozici',planSize=m.plan?.qty?`${fmt(m.plan.qty,4)} ks`:m.plan?.amount?`${fmt(m.plan.amount,0)} ${h(m.plan.currency||m.accountCurrency)}`:'neurčeno',destination=m.plan?.destination?`${h(m.plan.destination.name)} (${h(m.plan.destination.ticker)})`:'bez automatického přesunu';
 return `<div class="subview-bar"><button class="btn" id="xtbBack25">← XTB portfolio</button><div><span>PENÍZE / XTB POZICE</span><b>${h(m.ticker)}</b></div></div>
 <div class="view-head xtb-detail-head"><div><div class="eyebrow">XTB / POSITION DETAIL</div><h1>${h(m.name)}</h1><p>${h(m.ticker)} · ${h(m.category||'instrument')} · účet ${h(m.accountCurrency||'—')}</p></div><div class="row-actions"><span class="decision-action ${d.tone||''}">${h(actionLabel(d.action))}</span><button class="btn" data-xtb-rule="${h(m.ticker)}">Pravidlo</button><button class="btn quiet-action" data-xtb-sold="${h(m.ticker)}">Prodáno</button></div></div>
 <div class="metric-strip xtb-detail-metrics"><div class="metric"><span>Hodnota pozice</span><b>${fmt(m.value,0)} ${h(m.accountCurrency)}</b></div><div class="metric"><span>P/L</span><b class="${m.profitPct>=0?'good':'bad'}">${fmt(m.profitPct,1)} %</b><small>${fmt(m.profit,0)} ${h(m.accountCurrency)}</small></div><div class="metric"><span>Váha účtu</span><b>${fmt(m.weightPct,1)} %</b></div><div class="metric"><span>Množství</span><b>${fmt(m.volume,4)} ks</b></div></div>
 <div class="grid two xtb-detail-grid"><div class="card xtb-thesis-card"><div class="card-head"><div><div class="eyebrow">ROZHODNUTÍ</div><h2>${h(actionLabel(d.action))} · confidence ${h(confidence)}</h2></div><span class="status ${m.liveAge.fresh?'good':'warn'}">${h(source)} · ${h(d.live?m.liveAge.label:m.dataAge.label)}</span></div>${d.headline?`<div class="xtb-detail-headline">${h(d.headline)}</div>`:''}<div class="xtb-detail-reason">${h(d.reason||'Bez doplňujícího důvodu.')}</div><div class="xtb-rule-grid"><div><span>Kdy jednat</span><b>${h(d.when||'—')}</b></div><div><span>Kdy nakoupit</span><b>${h(d.buyRule||'—')}</b></div><div><span>Kdy prodat</span><b>${h(d.sellRule||'—')}</b></div></div><div class="decision-note ${m.dataAge.stale?'warn':''}">XTB import: ${h(m.dataAge.label)}. ${d.live?`Živá intelligence: ${h(m.liveAge.label)}.`:'Použitý verdikt není čerstvá živá analýza.'}</div></div>
 <div class="card xtb-execution-card"><div class="card-head"><div><div class="eyebrow">EXECUTION PLAN</div><h2>Jak velký krok dává smysl</h2></div></div><div class="project-fact"><span>Navržená velikost</span><b>${h(planSize)}</b></div><div class="project-fact"><span>Kam s kapitálem</span><b>${destination}</b></div><div class="project-fact"><span>FX / účet</span><b>${h(m.plan?.fx||'Bez konkrétního trade plánu.')}</b></div><div class="project-fact"><span>Aktuální cena z intelligence</span><b>${current}</b></div><div class="project-fact"><span>Importovaná open price</span><b>${m.openPrice?`${fmt(m.openPrice,4)} ${h(m.accountCurrency)}`:'—'}</b></div></div></div>
 <div class="grid two xtb-detail-lower"><div class="card"><div class="card-head"><div><div class="eyebrow">ZDROJE / EVIDENCE</div><h2>O co se verdikt opírá</h2></div></div>${m.sources.length?`<div class="xtb-source-list">${m.sources.map((u,i)=>`<a href="${h(u)}" target="_blank" rel="noopener noreferrer">Zdroj ${i+1} ↗</a>`).join('')}</div>`:'<div class="empty">K tomuto verdiktu nejsou uložené veřejné zdrojové odkazy. Kamil OS je nebude domýšlet.</div>'}<div class="decision-note">Zdrojové odkazy se zobrazí jen pokud je dodala živá intelligence. Pravidlový fallback žádné internetové zdroje nepředstírá.</div></div>
 <div class="card"><div class="card-head"><div><div class="eyebrow">HISTORIE</div><h2>Obchody a uživatelské změny</h2></div><span class="status">${m.history.length}</span></div>${m.history.length?`<div class="xtb-history">${m.history.map(x=>`<div class="xtb-history-row"><span>${h(when(x.at))}</span><div><b>${h(x.label)}</b><small>${h(x.detail)}</small></div></div>`).join('')}</div>`:'<div class="empty">Pro tuto pozici zatím není v trade journalu ani auditu dohledatelná historie.</div>'}</div></div>`;
}
