import {store} from './state.js';
import {xtbBoard,xtbDataAge,xtbIntelligenceAge,actionLabel} from './live24.js';

const VERSION=368;
const N=v=>Number(v||0),U=v=>String(v||'').toUpperCase(),clamp=v=>Math.max(0,Math.min(100,N(v)));
const VERDICT={BUY:'ADD',ADD:'ADD',HOLD:'HOLD',TRIM:'REDUCE',REDUCE:'REDUCE',SELL:'SELL',REVIEW:'HOLD',WAIT:'HOLD'};
const LABEL={ADD:'PŘIKOUPIT',HOLD:'DRŽET',REDUCE:'REDUKOVAT',SELL:'PRODAT'};
function freshness(s){const imported=xtbDataAge(s),intel=xtbIntelligenceAge(s);return{import:imported,intelligence:intel,stale:!!imported.stale||!!intel.stale,label:`Import ${imported.label} · analýza ${intel.label}`}}
function confidence(d,f){let c=d?.confidence===null||d?.confidence===undefined?Math.max(35,Math.min(80,N(d?.priority)||50)):clamp(d.confidence);if(f.stale)c=Math.min(c,55);if(d?.liveTrust&&d.liveTrust!=='TRUSTED_FRESH')c=Math.min(c,50);return Math.round(c)}
function risks(p,d,f){const out=[];if(f.stale)out.push('STALE_DATA');if(p?.weightScope!=='TOTAL_INVESTMENTS')out.push('WEIGHT_UNKNOWN');if(U(d?.action)==='REVIEW')out.push('THESIS_REVIEW');if(d?.liveCandidate&&!d?.live)out.push('UNTRUSTED_LIVE_SIGNAL');if(N(p?.weightPct)>=12)out.push('CONCENTRATION');return out}
function row(item,f){const p=item.p||{},d=item.d||{},raw=U(d.action||'HOLD'),verdict=VERDICT[raw]||'HOLD',riskFlags=risks(p,d,f),reason=[d.reason,d.when].filter(Boolean).join(' · ')||'Bez silného signálu ke změně pozice.';return{ticker:p.ticker,name:p.name||p.ticker,verdict,label:LABEL[verdict]||actionLabel(raw),sourceAction:raw,confidence:confidence(d,f),priority:clamp(d.priority),reason,buyRule:d.buyRule||'',sellRule:d.sellRule||'',riskFlags,dataFresh:!f.stale,weightPct:p.weightScope==='TOTAL_INVESTMENTS'?N(p.weightPct):null,profitPct:Number.isFinite(Number(p.net_profit_pct))?Number(p.net_profit_pct):null,source:d.source||'AUTO'}}
export function xtbDecision368(s=store.get()){const f=freshness(s),positions=xtbBoard(s).map(x=>row(x,f)).sort((a,b)=>b.priority-a.priority),counts={ADD:0,HOLD:0,REDUCE:0,SELL:0};positions.forEach(x=>counts[x.verdict]++);const actionable=positions.filter(x=>x.verdict!=='HOLD'),top=actionable[0]||positions[0]||null;return{version:VERSION,healthy:true,positions,counts,top,freshness:f,generatedAt:new Date().toISOString()}}
function publish(){try{const model=xtbDecision368();window.__KAMIL_XTB_DECISION368__={version:VERSION,healthy:true,model,refresh:publish,at:Date.now()};document.documentElement.dataset.xtbDecision368='1';window.dispatchEvent(new CustomEvent('kamil:xtb-decision368-updated',{detail:{count:model.positions.length,actionable:model.positions.filter(x=>x.verdict!=='HOLD').length}}));return model}catch(error){console.error('[xtbDecision368]',error);window.__KAMIL_XTB_DECISION368__={version:VERSION,healthy:false,error:String(error?.message||error),refresh:publish,at:Date.now()};return null}}
let bound=false,timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(publish,80)};
export function installXtbDecision368(){if(!bound){bound=true;store.subscribe?.(schedule);window.addEventListener('focus',schedule);window.addEventListener('kamil:view-change',schedule)}schedule();setTimeout(schedule,900)}
