import {store} from './state.js';
import {markXtbAction389,xtbCalibration389} from './xtbCalibration389.js';
const VERSION=390,KEY='kamil.xtb.execution.390',N=v=>Number(v||0),U=v=>String(v||'').toUpperCase();
function read(){if(typeof localStorage==='undefined')return[];try{return JSON.parse(localStorage.getItem(KEY)||'[]')||[]}catch{return[]}}
function write(rows){if(typeof localStorage==='undefined')return;try{localStorage.setItem(KEY,JSON.stringify(rows.slice(-200)))}catch{}}
function baseModel(s=store.get()){return window.__KAMIL_XTB_CALIBRATION389__?.model||xtbCalibration389(s)}
export function recordXtbExecution390(ticker,action,meta={}){const rows=read(),entry={id:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,at:new Date().toISOString(),ticker:String(ticker||''),action:U(action),amount:N(meta.amount)||null,price:N(meta.price)||null,source:'MANUAL_CONFIRMATION'};rows.push(entry);write(rows);markXtbAction389(ticker);window.dispatchEvent(new CustomEvent('kamil:xtb-execution390-recorded',{detail:entry}));return entry}
export function xtbExecution390(s=store.get()){const base=baseModel(s),history=read(),last=history.slice(-10).reverse(),today=new Date().toISOString().slice(0,10),todayRows=history.filter(x=>String(x.at||'').slice(0,10)===today),byTicker={};for(const x of history)byTicker[U(x.ticker)]=x;const rows=(base.rows||[]).map(r=>({...r,lastExecution:byTicker[U(r.ticker)]||null}));return{version:VERSION,healthy:true,base,rows,history,last,todayCount:todayRows.length,todayAmount:todayRows.reduce((z,x)=>z+N(x.amount),0),guardrails:{manualConfirmationOnly:true,brokerExecution:false,autoExecute:false},generatedAt:new Date().toISOString()}}
function publish(){try{const model=xtbExecution390();window.__KAMIL_XTB_EXECUTION390__={version:VERSION,healthy:true,model,record:recordXtbExecution390,refresh:publish,at:Date.now()};document.documentElement.dataset.xtbExecution390='1';window.dispatchEvent(new CustomEvent('kamil:xtb-execution390-updated',{detail:{todayCount:model.todayCount,todayAmount:model.todayAmount}}));return model}catch(error){window.__KAMIL_XTB_EXECUTION390__={version:VERSION,healthy:false,error:String(error?.message||error),record:recordXtbExecution390,refresh:publish,at:Date.now()};return null}}
let bound=false,timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(publish,180)};export function installXtbExecution390(){if(!bound){bound=true;for(const ev of ['kamil:xtb-calibration389-updated','kamil:xtb-execution390-recorded'])window.addEventListener(ev,schedule);store.subscribe?.(schedule)}schedule();setTimeout(schedule,2200)}
