import {store} from './state.js';
import {xtbReconciliation391} from './xtbReconciliation391.js';
const VERSION=392,N=v=>Number(v||0),U=v=>String(v||'').toUpperCase(),round=(v,d=2)=>Number(N(v).toFixed(d));
function side(action){return ['REDUCE','SELL'].includes(U(action))?'SELL':'BUY'}
function stats(history,ticker){const rows=(history||[]).filter(x=>U(x.ticker)===U(ticker)&&x.status!=='NO_DATA'),slips=rows.filter(x=>x.slippagePct!==null),fills=rows.filter(x=>x.fillPct!==null);return{count:rows.length,avgSlip:slips.length?slips.reduce((z,x)=>z+N(x.slippagePct),0)/slips.length:null,avgFill:fills.length?fills.reduce((z,x)=>z+N(x.fillPct),0)/fills.length:null,bad:rows.filter(x=>x.status==='BAD_PRICE').length,partial:rows.filter(x=>x.status==='PARTIAL').length}}
function advise(r,h){const s=stats(h,r.ticker),action=U(r.effectiveVerdict),direction=side(action),current=N(r.current),buyBelow=N(r.buyBelow),reduceFrom=N(r.reduceFrom),sellFrom=N(r.sellFrom),amount=N(r.recommendedAmount),poorSlip=s.avgSlip!==null&&s.avgSlip>.8,poorFill=s.avgFill!==null&&s.avgFill<80,unstable=N(r.stability?.flips)>=3;let mode='LIMIT',parts=amount>=15000?3:amount>=7000?2:1,reason='Použij limitní cenu a nehoň trh.';if(poorSlip||s.bad>=2){mode='LIMIT_STRICT';parts=Math.max(parts,3);reason='Historie ukazuje horší slippage; zpřísnit limit a rozdělit objednávku.'}else if(poorFill&&!poorSlip){mode='LIMIT_SPLIT';parts=Math.max(parts,2);reason='Fill bývá slabší; rozdělit objednávku na více částí.'}if(unstable){parts=Math.max(parts,3);reason+=' Signál je volatilnější, proto vstup po částech.'}let limit=null;if(direction==='BUY'){const anchor=buyBelow||current;if(anchor)limit=poorFill&&!poorSlip?anchor*1.003:anchor}else{const anchor=sellFrom||reduceFrom||current;if(anchor)limit=poorFill&&!poorSlip?anchor*.997:anchor}const maxSlip=poorSlip?.35:s.avgSlip!==null&&s.avgSlip>.4?.6:.9;return{ticker:r.ticker,action,direction,mode,parts,limitPrice:limit?round(limit):null,maxAcceptableSlippagePct:maxSlip,historyCount:s.count,avgSlippagePct:s.avgSlip===null?null:round(s.avgSlip),avgFillPct:s.avgFill===null?null:round(s.avgFill,0),reason,manualOnly:true}}
function model(base){const rows=(base.rows||[]).map(r=>({...r,orderAdvice:advise(r,base.history||[])})),actionable=rows.filter(r=>['ADD','REDUCE','SELL'].includes(U(r.effectiveVerdict))&&r.calibration?.status!=='BLOCKED'),advice=actionable.map(r=>r.orderAdvice),strict=advice.filter(x=>x.mode==='LIMIT_STRICT').length,split=advice.filter(x=>x.parts>1).length;return{version:VERSION,healthy:true,base,rows,advice,summary:{actionable:advice.length,strict,split,executionQuality:strict?'DISCIPLINED':base.summary?.avgSlippagePct!==null&&N(base.summary.avgSlippagePct)>.8?'WATCH':'NORMAL'},guardrails:{marketOrdersRecommended:false,manualOnly:true,autoExecute:false},generatedAt:new Date().toISOString()}}
export function xtbOrderAdvisor392(s=store.get()){const base=window.__KAMIL_XTB_RECONCILIATION391__?.model||xtbReconciliation391(s);return model(base)}
function publish(){try{const m=xtbOrderAdvisor392();window.__KAMIL_XTB_ORDER_ADVISOR392__={version:VERSION,healthy:true,model:m,refresh:publish,at:Date.now()};document.documentElement.dataset.xtbOrderAdvisor392='1';window.dispatchEvent(new CustomEvent('kamil:xtb-order-advisor392-updated',{detail:m.summary}));return m}catch(error){window.__KAMIL_XTB_ORDER_ADVISOR392__={version:VERSION,healthy:false,error:String(error?.message||error),refresh:publish,at:Date.now()};return null}}
let bound=false,timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(publish,180)};export function installXtbOrderAdvisor392(){if(!bound){bound=true;for(const ev of ['kamil:xtb-reconciliation391-updated','kamil:xtb-calibration389-updated','kamil:market-quotes'])window.addEventListener(ev,schedule);store.subscribe?.(schedule)}schedule();setTimeout(schedule,2600)}