import {store} from './state.js';
import {xtbPositions} from './decision24.js';
import {netWorthFxRate} from './netWorth29.js';
const N=v=>Number(v||0),A=v=>Array.isArray(v)?v:[];
const finite=v=>Number.isFinite(Number(v));
const qty=p=>N(p.quantity||p.qty||p.volume||p.units||p.shares||0);
const avg=p=>{for(const k of ['open_price','openPrice','avgPrice','averagePrice','purchasePrice','price_open'])if(finite(p?.[k])&&Number(p[k])>0)return Number(p[k]);return null};
const importedUnrealized=p=>{for(const k of ['net_profit','netProfit','profit'])if(finite(p?.[k]))return Number(p[k]);return null};
const ccy=v=>String(v||'CZK').toUpperCase();
function convert(s,value,from,to='CZK'){if(!finite(value))return null;const rate=netWorthFxRate(s,ccy(from),ccy(to));return rate===null?null:Number(value)*rate}
function journal(s){const trades=A(s.tradeJournal?.trades),realized=[],dividends=[];for(const t of trades){const kind=String(t.kind||t.type||'').toUpperCase(),amount=finite(t.realized)?Number(t.realized):finite(t.amount)?Number(t.amount):null;if(amount===null)continue;if(/DIVIDEND|DIVIDENDA/.test(kind))dividends.push({...t,amount});else if(/SELL|CLOSE|REALIZED|PRODEJ|UZAV/.test(kind))realized.push({...t,amount})}return{realized,dividends}}
function sumConverted(s,rows,base='CZK'){let total=0,covered=0;for(const x of rows){const v=convert(s,x.amount,x.currency||base,base);if(v===null)continue;total+=v;covered++}return{total,covered,rows:rows.length,complete:rows.length===covered}}
export function enhanceXtbPlQa146(){const root=document.querySelector('.dashboard110');if(!root)return;const s=store.get(),positions=xtbPositions(s),base=ccy(s.financePlan?.currency||'CZK');let basisCovered=0,importProfitCovered=0,importProfitCzk=0;for(const p of positions){if(qty(p)>0&&avg(p)>0)basisCovered++;const u=importedUnrealized(p);if(u===null)continue;const cv=convert(s,u,p.accountCurrency||p.currency||base,base);if(cv===null)continue;importProfitCzk+=cv;importProfitCovered++}const j=journal(s),real=sumConverted(s,j.realized,base),div=sumConverted(s,j.dividends,base);const bottom=root.querySelector('.d110-bottom');if(bottom){bottom.querySelector('[data-xtbpl146]')?.remove();const card=document.createElement('section');card.className='d110-card';card.dataset.xtbpl146='1';card.innerHTML=`<div class="d110-title"><b>XTB P/L — DATOVÁ KVALITA</b></div><div class="d110-kpi"><span>Cost basis pozic</span><b>${basisCovered}/${positions.length}</b></div><div class="d110-kpi"><span>Importovaný nerealizovaný P/L</span><b>${importProfitCovered}/${positions.length}${importProfitCovered?` · ${Math.round(importProfitCzk).toLocaleString('cs-CZ')} ${base}`:''}</b></div><div class="d110-kpi"><span>Realizované obchody v journalu</span><b>${real.rows?`${real.rows}${real.complete?` · ${Math.round(real.total).toLocaleString('cs-CZ')} ${base}`:' · neúplný FX'}`:'—'}</b></div><div class="d110-kpi"><span>Dividendové záznamy</span><b>${div.rows?`${div.rows}${div.complete?` · ${Math.round(div.total).toLocaleString('cs-CZ')} ${base}`:' · neúplný FX'}`:'—'}</b></div><p class="d110-note">Nerealizovaný P/L = otevřené pozice. Realizovaný P/L a dividendy ukazuju jen z explicitních journal záznamů; nic z otevřených pozic za realizovaný výsledek nepovažuju.</p>`;bottom.prepend(card)}window.__KAMIL_XTB_PL_QA146__={at:Date.now(),positions:positions.length,basisCovered,importProfitCovered,importProfitCzk,realizedRows:real.rows,realizedCzk:real.complete?real.total:null,dividendRows:div.rows,dividendCzk:div.complete?div.total:null,baseCurrency:base}}
