import {store} from './state.js';
import {xtbBoard} from './live24.js';
import {xtbTargets371} from './xtbTargets371.js';
import {positionSizing373} from './positionSizing373.js';

const VERSION=385,N=v=>Number(v||0),U=v=>String(v||'').toUpperCase(),clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,N(v))),round=(v,d=1)=>Number(N(v).toFixed(d));
const DAY=86400000,JOURNAL_KEY='kamil.xtb.decision.journal.385';
const arr=v=>Array.isArray(v)?v:[];
function dateDays(v){const t=Date.parse(v||'');return Number.isFinite(t)?Math.ceil((t-Date.now())/DAY):null}
function posValue(p){for(const v of [p.baseValue,p.value,p.marketValue,p.currentValue,p.investedValue])if(N(v)>0)return N(v);return 0}
function currency(p){return U(p.accountCurrency||p.currency||p.ccy||'UNKNOWN')||'UNKNOWN'}
function sector(p){return String(p.sector||p.industry||p.category||p.theme||'Nezařazeno').trim()||'Nezařazeno'}
function peak(p){for(const v of [p.high52w,p.highPrice52w,p.peakPrice,p.maxPrice,p.high])if(N(v)>0)return N(v);return null}
function quote(p,t){return N(t?.current)||N(p.currentPrice||p.marketPrice||p.price||p.lastPrice)||null}
function targetWeight(quality,currentWeight){const base=quality?2+(quality/100)*10:Math.max(2,Math.min(8,N(currentWeight)||4));return round(clamp(base,2,15),1)}
function ladderBuy(t,current){const anchor=N(t?.buyBelow)||N(current);if(!anchor)return[];return[{step:1,pct:25,price:round(anchor,2)},{step:2,pct:35,price:round(anchor*.96,2)},{step:3,pct:40,price:round(anchor*.91,2)}]}
function ladderSell(t,current,gain){const first=N(t?.reduceFrom)||N(current)*1.08,final=N(t?.sellFrom)||N(current)*1.18;if(!current)return[];const protect=N(gain)>=60?.97:N(gain)>=40?.94:N(gain)>=25?.90:null;return[{step:1,pct:25,price:round(first,2)},{step:2,pct:35,price:round((first+final)/2,2)},{step:3,pct:40,price:round(final,2)}].concat(protect?[{step:'protect',pct:100,price:round(current*protect,2)}]:[])}
function riskReward(current,t){if(!current)return{upsidePct:null,downsidePct:null,ratio:null};const upsideTarget=N(t?.sellFrom)||N(t?.reduceFrom),downsideRef=N(t?.buyBelow);const upside=upsideTarget?((upsideTarget/current)-1)*100:null,downside=downsideRef?Math.max(1,((current-downsideRef)/current)*100):null;return{upsidePct:upside===null?null:round(upside),downsidePct:downside===null?null:round(downside),ratio:upside!==null&&downside?round(Math.max(0,upside)/downside,2):null}}
function drawdown(p,current){const hi=peak(p);if(!hi||!current)return{peak:null,pct:null,status:'NO_DATA'};const pct=((current/hi)-1)*100;return{peak:hi,pct:round(pct),status:pct<=-30?'SEVERE':pct<=-20?'DEEP':pct<=-10?'NORMAL':'NEAR_HIGH'}}
function profitProtection(gain){gain=N(gain);if(gain>=60)return{level:'LOCK_60',label:'Chránit velký zisk',protectPct:3};if(gain>=40)return{level:'LOCK_40',label:'Aktivní ochrana zisku',protectPct:6};if(gain>=25)return{level:'LOCK_25',label:'Připravit částečný výběr',protectPct:10};return{level:'NONE',label:'Bez zvláštní ochrany',protectPct:null}}
function effectiveVerdict(raw,fresh,earnDays){raw=U(raw||'HOLD');if(raw==='BUY')raw='ADD';if(raw==='TRIM')raw='REDUCE';if(raw!=='HOLD'&&!fresh)return{raw,verdict:'VERIFY',reason:'Nejdřív obnovit tržní cenu.'};if((raw==='ADD')&&earnDays!==null&&earnDays>=0&&earnDays<=5)return{raw,verdict:'WAIT_EARNINGS',reason:`Výsledky za ${earnDays} d.; nový nákup pozastaven.`};return{raw,verdict:raw,reason:null}}
function watchlistRows(s){const raw=s.xtbStrategy?.watchlist||s.xtbHub?.watchlist||s.investments?.watchlist||[];return arr(raw).map(x=>({ticker:x.ticker||x.symbol||x.name,name:x.name||x.ticker||x.symbol,score:N(x.opportunityScore||x.score||x.priority),confidence:N(x.confidence),price:N(x.price||x.currentPrice)})).filter(x=>x.ticker).sort((a,b)=>b.score-a.score)}
function journalRead(){try{return JSON.parse(localStorage.getItem(JOURNAL_KEY)||'[]')}catch{return[]}}
function journalWrite(rows){if(typeof localStorage==='undefined')return;try{const old=journalRead(),day=new Date().toISOString().slice(0,10),seen=new Set(old.map(x=>`${x.day}:${x.ticker}:${x.verdict}`));for(const x of rows){const key=`${day}:${x.ticker}:${x.effectiveVerdict}`;if(seen.has(key))continue;old.push({day,at:new Date().toISOString(),ticker:x.ticker,verdict:x.effectiveVerdict,price:x.current,quality:x.qualityScore,target:x.sellFrom||null})}localStorage.setItem(JOURNAL_KEY,JSON.stringify(old.slice(-300)))}catch{}}
function journalPerformance(currentRows){const j=journalRead(),by=new Map(currentRows.map(x=>[U(x.ticker),x]));let evaluated=0,wins=0;const details=[];for(const e of j){const c=by.get(U(e.ticker));if(!c||!N(e.price)||!N(c.current))continue;const move=((c.current/e.price)-1)*100;let ok=null;if(['ADD','BUY'].includes(U(e.verdict)))ok=move>0;else if(['REDUCE','SELL'].includes(U(e.verdict)))ok=move<0;else continue;evaluated++;if(ok)wins++;details.push({...e,current:c.current,movePct:round(move),success:ok})}return{evaluated,wins,hitRate:evaluated?round(wins/evaluated*100):null,details:details.slice(-30)}}
function scenarios(total,rows,currencyExposure,sectorExposure){const biggest=[...rows].sort((a,b)=>b.value-a.value)[0],usd=N(currencyExposure.USD?.value),topSector=Object.entries(sectorExposure).sort((a,b)=>N(b[1].value)-N(a[1].value))[0];return[
 {name:'Akcie −20 %',impact:round(total*-.20,0)},
 {name:'USD −10 %',impact:round(usd*-.10,0)},
 {name:'Největší pozice −40 %',impact:round(N(biggest?.value)*-.40,0)},
 {name:`${topSector?.[0]||'Top sektor'} −30 %`,impact:round(N(topSector?.[1]?.value)*-.30,0)}
]}
function summaryText(rows,sizing){const action=rows.filter(x=>!['HOLD','VERIFY','WAIT_EARNINGS'].includes(x.effectiveVerdict)).sort((a,b)=>b.actionScore-a.actionScore)[0];if(!action)return{title:'Dnes nic nedělej',detail:rows.some(x=>x.effectiveVerdict==='VERIFY')?'Nejdřív obnov ceny u pozic označených OVĚŘIT.':'Portfolio nemá dost silný potvrzený signál ke změně.',ticker:null,amount:0};if(action.effectiveVerdict==='ADD')return{title:`Přikup ${action.ticker}`,detail:`Priorita ${Math.round(action.actionScore)}/100${action.buyBelow?` · ideálně pod ${action.buyBelow}`:''}.`,ticker:action.ticker,amount:N(action.recommendedAmount)};if(action.effectiveVerdict==='SELL')return{title:`Zvaž prodej ${action.ticker}`,detail:`Profit/risk signal ${Math.round(action.actionScore)}/100.`,ticker:action.ticker,amount:0};return{title:`Zvaž redukci ${action.ticker}`,detail:`Pozice je nad cílovou vahou nebo má zvýšené riziko.`,ticker:action.ticker,amount:0}}

export function xtbPortfolio385(s=store.get()){
 const board=xtbBoard(s),targets=window.__KAMIL_XTB_TARGETS371__?.model||xtbTargets371(s),sizing=window.__KAMIL_POSITION_SIZING373__?.model||positionSizing373(s),byT=new Map(arr(targets.rows).map(x=>[U(x.ticker),x.targets||{}])),byS=new Map(arr(sizing.rows).map(x=>[U(x.ticker),x])),total=board.reduce((z,x)=>z+posValue(x.p),0);
 const rows=board.map(({p,d})=>{const ticker=p.ticker||p.symbol||p.name,key=U(ticker),t=byT.get(key)||{},sz=byS.get(key)||{},current=quote(p,t),value=posValue(p),weight=N(p.weightPct)||(total&&value?value/total*100:0),quality=N(sz.qualityScore)||N(d.confidence)||N(d.priority)||50,earnDate=d.earningsDate||p.earningsDate||null,earnDays=dateDays(earnDate),eff=effectiveVerdict(d.action,t.fresh===true,earnDays),rr=riskReward(current,t),dd=drawdown(p,current),protect=profitProtection(p.net_profit_pct),target=targetWeight(quality,weight),delta=target-weight,rebalAmount=total?round(total*delta/100,0):0,concBlocked=weight>=15||target>15,sectorName=sector(p),ccy=currency(p),actionScore=clamp(quality+(rr.ratio?Math.min(15,rr.ratio*3):0)-(weight>=12?15:0)-(dd.status==='SEVERE'?12:0)-(eff.verdict==='VERIFY'?30:0)-(eff.verdict==='WAIT_EARNINGS'?25:0));let recommended=N(sz.recommendedAmount);if(concBlocked||eff.verdict!=='ADD')recommended=0;return{ticker,name:p.name||ticker,sector:sectorName,currency:ccy,value,weightPct:round(weight),targetWeightPct:target,rebalanceAmount:rebalAmount,current,buyBelow:N(t.buyBelow)||null,reduceFrom:N(t.reduceFrom)||null,sellFrom:N(t.sellFrom)||null,fresh:t.fresh===true,source:t.source||'MISSING',rawVerdict:eff.raw,effectiveVerdict:eff.verdict,gateReason:eff.reason,confidence:N(d.confidence)||N(d.priority),qualityScore:round(quality),actionScore:round(actionScore),recommendedAmount:recommended,allocationBlocked:concBlocked,concentration:N(weight)>=12?'HIGH':N(weight)>=9?'WATCH':'OK',expected:rr,buyLadder:ladderBuy(t,current),sellLadder:ladderSell(t,current,p.net_profit_pct),drawdown:dd,profitProtection:protect,profitPct:Number.isFinite(Number(p.net_profit_pct))?N(p.net_profit_pct):null,earningsDate:earnDate,earningsDays:earnDays,earningsBlackout:earnDays!==null&&earnDays>=0&&earnDays<=5,reason:d.reason||'',autoExecute:false}}).sort((a,b)=>b.actionScore-a.actionScore);
 const currencyExposure={},sectorExposure={};for(const r of rows){for(const [obj,key] of [[currencyExposure,r.currency],[sectorExposure,r.sector]]){if(!obj[key])obj[key]={value:0,pct:0,count:0};obj[key].value+=r.value;obj[key].count++}}for(const obj of [currencyExposure,sectorExposure])for(const v of Object.values(obj))v.pct=total?round(v.value/total*100):0;
 const concentrationAlerts=rows.filter(x=>x.weightPct>=12),sectorAlerts=Object.entries(sectorExposure).filter(([,v])=>v.pct>=30).map(([name,v])=>({name,...v})),watchlist=watchlistRows(s),bestHeld=Math.max(0,...rows.map(x=>x.actionScore)),bestWatch=watchlist[0]||null,rotation=bestWatch&&bestWatch.score>bestHeld+10?{candidate:bestWatch,reason:`Watchlist ${bestWatch.ticker} má o ${round(bestWatch.score-bestHeld)} bodů lepší skóre než nejlepší držená pozice.`}:null;
 const deployment=rows.filter(x=>x.recommendedAmount>0).map(x=>({ticker:x.ticker,amount:x.recommendedAmount,priceLimit:x.buyBelow,quality:x.qualityScore})),today=summaryText(rows,sizing),performance=journalPerformance(rows);journalWrite(rows);
 return{version:VERSION,healthy:true,rows,totalValue:total,cashAvailable:sizing.cashAvailable,deployable:deployment.reduce((z,x)=>z+x.amount,0),remainingCash:sizing.remainingCash,currencyExposure,sectorExposure,concentrationAlerts,sectorAlerts,watchlist,rotation,deployment,scenarios:scenarios(total,rows,currencyExposure,sectorExposure),today,performance,journalSize:journalRead().length,guardrails:{positionHardCapPct:15,positionWarningPct:12,sectorWarningPct:30,freshnessRequiredForAction:true,earningsBlackoutDays:5,autoExecute:false},generatedAt:new Date().toISOString()}
}

function publish(){try{const model=xtbPortfolio385();window.__KAMIL_XTB_PORTFOLIO385__={version:VERSION,healthy:true,model,refresh:publish,at:Date.now()};document.documentElement.dataset.xtbPortfolio385='1';window.dispatchEvent(new CustomEvent('kamil:xtb-portfolio385-updated',{detail:{actions:model.rows.filter(x=>!['HOLD','VERIFY','WAIT_EARNINGS'].includes(x.effectiveVerdict)).length,deployable:model.deployable}}));return model}catch(error){console.error('[xtbPortfolio385]',error);window.__KAMIL_XTB_PORTFOLIO385__={version:VERSION,healthy:false,error:String(error?.message||error),refresh:publish,at:Date.now()};return null}}
let bound=false,timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(publish,140)};
export function installXtbPortfolio385(){if(!bound){bound=true;store.subscribe?.(schedule);for(const ev of ['kamil:xtb-decision368-updated','kamil:xtb-targets371-updated','kamil:position-sizing373-updated','kamil:market-quotes'])window.addEventListener(ev,schedule)}schedule();setTimeout(schedule,1500)}
