import {store} from './state.js';
import {xtbExecution390} from './xtbExecution390.js';
const VERSION=391,N=v=>Number(v||0),U=v=>String(v||'').toUpperCase(),round=(v,d=1)=>Number(N(v).toFixed(d));
function slippagePct(action,planned,actual){if(!planned||!actual)return null;const raw=(actual/planned-1)*100;return ['REDUCE','SELL'].includes(U(action))?round(-raw,2):round(raw,2)}
function fillPct(planned,actual){if(!planned||!actual)return null;return round(actual/planned*100,0)}
function status(slip,fill){if(slip===null&&fill===null)return'NO_DATA';if(slip!==null&&slip>1.5)return'BAD_PRICE';if(fill!==null&&fill<70)return'PARTIAL';if(slip!==null&&slip<=.5&&fill!==null&&fill>=90)return'GOOD';return'OK'}
function model(base){const history=(base.history||[]).map(x=>{const plannedPrice=N(x.plannedPrice),actualPrice=N(x.actualPrice??x.price),plannedAmount=N(x.plannedAmount),actualAmount=N(x.actualAmount??x.amount),slippage=slippagePct(x.action,plannedPrice,actualPrice),fill=fillPct(plannedAmount,actualAmount);return{...x,plannedPrice,actualPrice,plannedAmount,actualAmount,slippagePct:slippage,fillPct:fill,status:status(slippage,fill)}}),last=history.slice(-10).reverse(),evaluated=history.filter(x=>x.status!=='NO_DATA'),good=evaluated.filter(x=>x.status==='GOOD').length,bad=evaluated.filter(x=>x.status==='BAD_PRICE').length,partial=evaluated.filter(x=>x.status==='PARTIAL').length,avgSlip=evaluated.filter(x=>x.slippagePct!==null).length?round(evaluated.filter(x=>x.slippagePct!==null).reduce((z,x)=>z+N(x.slippagePct),0)/evaluated.filter(x=>x.slippagePct!==null).length,2):null,avgFill=evaluated.filter(x=>x.fillPct!==null).length?round(evaluated.filter(x=>x.fillPct!==null).reduce((z,x)=>z+N(x.fillPct),0)/evaluated.filter(x=>x.fillPct!==null).length,0):null;const byTicker={};for(const x of history)byTicker[U(x.ticker)]=x;const rows=(base.rows||[]).map(r=>({...r,lastReconciliation:byTicker[U(r.ticker)]||null}));return{version:VERSION,healthy:true,base,rows,history,last,summary:{evaluated:evaluated.length,good,bad,partial,avgSlippagePct:avgSlip,avgFillPct:avgFill},guardrails:{warnSlippagePct:1.5,partialFillBelowPct:70,goodFillPct:90,autoExecute:false},generatedAt:new Date().toISOString()}}
export function xtbReconciliation391(s=store.get()){const base=window.__KAMIL_XTB_EXECUTION390__?.model||xtbExecution390(s);return model(base)}
function publish(){try{const m=xtbReconciliation391();window.__KAMIL_XTB_RECONCILIATION391__={version:VERSION,healthy:true,model:m,refresh:publish,at:Date.now()};document.documentElement.dataset.xtbReconciliation391='1';window.dispatchEvent(new CustomEvent('kamil:xtb-reconciliation391-updated',{detail:m.summary}));return m}catch(error){window.__KAMIL_XTB_RECONCILIATION391__={version:VERSION,healthy:false,error:String(error?.message||error),refresh:publish,at:Date.now()};return null}}
let bound=false,timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(publish,180)};export function installXtbReconciliation391(){if(!bound){bound=true;for(const ev of ['kamil:xtb-execution390-updated','kamil:xtb-execution390-recorded'])window.addEventListener(ev,schedule);store.subscribe?.(schedule)}schedule();setTimeout(schedule,2400)}
