import {store} from './state.js';
import {xtbPortfolio385} from './xtbPortfolio385.js';
const VERSION=388,KEY='kamil.xtb.signal.stability.388',N=v=>Number(v||0),U=v=>String(v||'').toUpperCase();
const actionable=v=>['ADD','REDUCE','SELL'].includes(U(v));
function read(){if(typeof localStorage==='undefined')return{};try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{return{}}}
function write(v){if(typeof localStorage==='undefined')return;try{localStorage.setItem(KEY,JSON.stringify(v))}catch{}}
function observe(rows){const now=Date.now(),day=new Date().toISOString().slice(0,10),state=read(),out=[];for(const r of rows||[]){const key=U(r.ticker),v=U(r.effectiveVerdict||'HOLD'),prev=state[key]||{},same=prev.verdict===v,seenToday=prev.day===day,streak=same?(seenToday?N(prev.streak)||1:(N(prev.streak)||1)+1):1,flips=same?N(prev.flips):N(prev.flips)+(prev.verdict?1:0),firstAt=same&&prev.firstAt?prev.firstAt:now,lastChangedAt=same?prev.lastChangedAt||now:now;state[key]={verdict:v,streak,flips,day,firstAt,lastSeenAt:now,lastChangedAt};const stable=!actionable(v)||streak>=2||((now-firstAt)>=6*3600000&&streak>=1),status=!actionable(v)?'NEUTRAL':stable?'CONFIRMED':'PENDING';out.push({ticker:r.ticker,verdict:v,streak,flips,stable,status,firstAt,lastChangedAt})}write(state);return out}
function model(base){const stability=observe(base.rows),by=new Map(stability.map(x=>[U(x.ticker),x])),rows=(base.rows||[]).map(r=>({...r,stability:by.get(U(r.ticker))||null})),confirmed=rows.filter(r=>actionable(r.effectiveVerdict)&&r.stability?.stable),pending=rows.filter(r=>actionable(r.effectiveVerdict)&&!r.stability?.stable),confirmedDeployment=(base.deployment||[]).filter(d=>by.get(U(d.ticker))?.stable),deployable=confirmedDeployment.reduce((z,x)=>z+N(x.amount),0),cash=N(base.cashAvailable),reserve=N(window.__KAMIL_POSITION_SIZING373__?.model?.riskReserveAmount),remaining=cash?Math.max(0,cash-reserve-deployable):base.remainingCash;let today=base.today;if(today?.ticker&&actionable(rows.find(r=>U(r.ticker)===U(today.ticker))?.effectiveVerdict)&&!by.get(U(today.ticker))?.stable)today={title:'Počkej na potvrzení signálu',detail:`${today.ticker}: nový akční signál zatím nemá druhé potvrzení.`,ticker:today.ticker,amount:0};return{version:VERSION,healthy:true,base,rows,stability,confirmed,pending,deployment:confirmedDeployment,deployable,remainingCash:remaining,today,summary:{confirmed:confirmed.length,pending:pending.length,unstableTickers:pending.map(x=>x.ticker),flipCount:stability.reduce((z,x)=>z+N(x.flips),0)},guardrails:{confirmationsRequired:2,timeConfirmationHours:6,autoExecute:false},generatedAt:new Date().toISOString()}}
export function xtbStability388(s=store.get()){const base=window.__KAMIL_XTB_PORTFOLIO385__?.model||xtbPortfolio385(s);return model(base)}
function publish(){try{const m=xtbStability388();window.__KAMIL_XTB_STABILITY388__={version:VERSION,healthy:true,model:m,refresh:publish,at:Date.now()};document.documentElement.dataset.xtbStability388='1';window.dispatchEvent(new CustomEvent('kamil:xtb-stability388-updated',{detail:m.summary}));return m}catch(error){window.__KAMIL_XTB_STABILITY388__={version:VERSION,healthy:false,error:String(error?.message||error),refresh:publish,at:Date.now()};return null}}
let bound=false,timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(publish,160)};export function installXtbStability388(){if(!bound){bound=true;for(const ev of ['kamil:xtb-portfolio385-updated','kamil:market-quotes','kamil:view-change'])window.addEventListener(ev,schedule);store.subscribe?.(schedule)}schedule();setTimeout(schedule,1800)}
