import {store} from './state.js';
import {xtbBoard} from './live24.js';
import {marketQuoteForPosition32} from './marketQuoteIngest32.js';
const VERSION=371,N=v=>Number(v||0),U=v=>String(v||'').toUpperCase(),round=(v,d=2)=>Number(N(v).toFixed(d));
function priceOf(p){const q=marketQuoteForPosition32(p);if(q?.fresh&&N(q.price)>0)return{price:N(q.price),fresh:true,source:q.provider||'MARKET_QUOTE',asOf:q.asOf||null};const v=N(p.currentPrice||p.marketPrice||p.price||p.lastPrice);return{price:v||null,fresh:false,source:v?'IMPORT':'MISSING',asOf:null}}
function bands(p,d){const q=priceOf(p),px=q.price,gain=Number.isFinite(Number(p.net_profit_pct))?Number(p.net_profit_pct):0,raw=U(d.action||'HOLD');if(!px)return{current:null,buyBelow:null,waitAbove:null,reduceFrom:null,sellFrom:null,fresh:false,source:q.source,note:'Chybí použitelná tržní cena.'};let buyPct=.94,reducePct=1.12,sellPct=1.22;if(raw==='BUY'){buyPct=.985;reducePct=1.14;sellPct=1.25}else if(raw==='TRIM'||raw==='REDUCE'){buyPct=.88;reducePct=.995;sellPct=1.08}else if(raw==='SELL'){buyPct=.82;reducePct=.94;sellPct=.99}else if(raw==='REVIEW'){buyPct=.90;reducePct=1.08;sellPct=1.16}if(gain>=25){buyPct=Math.min(buyPct,.90);reducePct=Math.min(reducePct,1.02);sellPct=Math.min(sellPct,1.10)}if(gain<=-15)buyPct=Math.min(buyPct,.88);return{current:round(px),buyBelow:round(px*buyPct),waitAbove:round(px*buyPct),reduceFrom:round(px*reducePct),sellFrom:round(px*sellPct),fresh:q.fresh,source:q.source,asOf:q.asOf,note:q.fresh?'Cenová pásma odvozena od čerstvé market quote a stávajícího verdiktu.':'Orientační pásma z importované ceny; před obchodem obnovit quote.'}}
export function xtbTargets371(s=store.get()){const rows=xtbBoard(s).map(({p,d})=>({ticker:p.ticker,name:p.name||p.ticker,verdict:U(d.action||'HOLD'),reason:d.reason||'',confidence:d.confidence??null,targets:bands(p,d)}));const priced=rows.filter(x=>x.targets.current!==null),fresh=priced.filter(x=>x.targets.fresh);return{version:VERSION,healthy:true,rows,priced:priced.length,fresh:fresh.length,generatedAt:new Date().toISOString()}}
function publish(){try{const model=xtbTargets371();window.__KAMIL_XTB_TARGETS371__={version:VERSION,healthy:true,model,refresh:publish,at:Date.now()};document.documentElement.dataset.xtbTargets371='1';window.dispatchEvent(new CustomEvent('kamil:xtb-targets371-updated',{detail:{priced:model.priced,fresh:model.fresh}}));return model}catch(error){window.__KAMIL_XTB_TARGETS371__={version:VERSION,healthy:false,error:String(error?.message||error),refresh:publish,at:Date.now()};return null}}
let bound=false,timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(publish,100)};export function installXtbTargets371(){if(!bound){bound=true;store.subscribe?.(schedule);window.addEventListener('kamil:market-quotes',schedule);window.addEventListener('kamil:xtb-decision368-updated',schedule)}schedule();setTimeout(schedule,1200)}
