import assert from 'node:assert/strict';
import fs from 'node:fs';
const js=fs.readFileSync('./js/appWorkspace211.js','utf8');
const shell=fs.readFileSync('./js/instantShell64.js','utf8');
for(const view of ['today','money','home','more'])assert.ok(js.includes(`${view}:`),`workspace compatibility missing ${view}`);
assert.ok(js.includes("view==='tickets'"),'ticket workspace must stay independently owned');
assert.ok(js.includes('data-app-workspace211'),'legacy workspace cleanup missing');
assert.ok(js.includes("mode:'compat-cleanup'"),'OS211 must run only as compatibility cleanup');
assert.ok(!js.includes('OS 211 · NO-SCROLL'),'legacy OS211 chrome must not be rendered');
assert.ok(!js.includes('data-prev211')&&!js.includes('data-next211'),'legacy pager must stay retired');
assert.ok(shell.includes("['./appWorkspace211.js','installAppWorkspaces211']"),'workspace compatibility cleanup not boot-wired in current module table');
console.log('OS 211 COMPATIBILITY CLEANUP PASS');
