import fs from 'node:fs';
const files=['js/copilot840.js','js/commandCopilot840.js','js/personalMore640.js','js/bettingBootstrap543.js'];
for(const f of files)if(!fs.existsSync(f))throw new Error(`missing ${f}`);
const c=fs.readFileSync('js/copilot840.js','utf8');
const q=fs.readFileSync('js/commandCopilot840.js','utf8');
const more=fs.readFileSync('js/personalMore640.js','utf8');
const boot=fs.readFileSync('js/bettingBootstrap543.js','utf8');
for(const x of ['840.0.0','buildCopilot840','openCopilot840','readOnlyByDefault','noAutoFinancialExecution','noInventedExternalRates','noInventedCLV','canonicalSourcesOnly'])if(!c.includes(x))throw new Error(`copilot contract missing ${x}`);
for(const x of ['installCommandCopilot840','kamil.command.history.840','OS840 · COPILOT'])if(!q.includes(x))throw new Error(`command contract missing ${x}`);
if(!more.includes('Copilot & Control')||!more.includes("import('./copilot840.js')"))throw new Error('More integration missing');
if(!boot.includes("import('./commandCopilot840.js')"))throw new Error('bootstrap integration missing');
console.log('OS840 Copilot & Control guard OK');
