const mem=new Map();globalThis.localStorage={getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)};
const assert=(x,m)=>{if(!x)throw new Error(m)},fresh=new Date().toISOString();
const {dailyProfitBrief32,dailyProfitBrief32Contract}=await import('./js/dailyProfitBrief32.js');
const base={meta:{schemaVersion:80},financePlan:{cashNow:40000,reserveFloor:100000,plannedInvestment:25000,expectedIncome:0},wealthProfile:{reserve:{floor:100000,target:214815},cashflow:{history:[{month:'2026-06',income:70000,expenses:50000,surplus:20000,closed:true},{month:'2026-07',income:76000,expenses:56000,surplus:20000,closed:true}]}},xtbHub:{asOf:fresh,accounts:{}},xtbReport:{asOf:fresh},xtbStrategy:{overrides:{}},tradeJournal:{trades:[{ticker:'WIN.US',name:'Winner',purchaseValue:10000,saleValue:12000,realized:2000,kind:'INVESTMENT',closeDate:'2026-08-10'}]},ticketBook:{items:[],watchlist:[],history:[]}};
let b=dailyProfitBrief32(base,new Date());
assert(b.top?.id==='money-floor','cash floor must be top action');assert(b.top.priority===100,'cash floor priority must be 100');assert(b.router.xtbBudget===0&&b.router.reserveBudget===25000,'cash floor must route full planned budget to reserve');assert(b.data.cashflow.months===2&&b.data.cashflow.averageExpenses===53000,'cashflow history must feed brief');assert(b.trades.realizedTotal===2000&&b.trades.count===1,'trade history must feed brief');assert(b.contract==='READ_ONLY_DAILY_BRIEF'&&!b.autoTrade&&!b.autoPrice&&b.neverMovesMoney,'daily brief safety contract failed');
const safe=structuredClone(base);safe.financePlan.cashNow=250000;b=dailyProfitBrief32(safe,new Date());assert(b.router.xtbBudget===25000&&b.actions.some(x=>x.id==='money-xtb'),'cash above reserve should surface XTB budget');
assert(dailyProfitBrief32Contract.readOnly&&!dailyProfitBrief32Contract.autoTrade&&!dailyProfitBrief32Contract.autoPrice&&dailyProfitBrief32Contract.neverMovesMoney&&dailyProfitBrief32Contract.maxVisibleActions===6,'exported contract failed');
console.log('KAMIL OS 32.8 DAILY PROFIT BRIEF UNIT PASS');
