import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
const fail=m=>{console.error(`OS738 guard: ${m}`);process.exitCode=1};
const read=p=>fs.readFileSync(p,'utf8');
execFileSync(process.execPath,['--check','js/dataTruthAudit738.js'],{stdio:'pipe'});
execFileSync(process.execPath,['--check','js/oneOS977.js'],{stdio:'pipe'});
const mod=read('js/dataTruthAudit738.js'),legacy=read('js/oneOS977.js');
for(const token of ['buildDataTruthAudit738','openDataTruthAudit738','LIVE CLOUD','LOCAL FALLBACK','propertyBook?.candidates','loadTicketCloud660','ticketIncomplete','score'])if(!mod.includes(token))fail(`audit missing ${token}`);
for(const token of ["audit:['./dataTruthAudit738.js','openDataTruthAudit738']",'Data Truth Audit · OS738','Pokročilé / legacy'])if(!legacy.includes(token))fail(`Legacy gateway missing ${token}`);
if(!process.exitCode)console.log('OS738 data truth audit guard OK · gateway OS977');
