import {buildPersonalToday} from './js/personalToday26.js';
import {decisionSnapshot30,decisionDelta30} from './js/decisionDelta30.js';
const assert=(x,m)=>{if(!x)throw new Error(m)};
const now=new Date('2026-08-20T10:00:00+02:00');
const base={financePlan:{currency:'CZK',cashNow:200000,reserveFloor:50000,cashflow:[]},tasks:[],personalAdmin:{items:[]},familyHome:{members:[]},assetBook:{items:[]},emergencyFile:{contacts:[],assets:[]},calendar:{events:[]},debtBook:{items:[]},audit:[],xtbStrategy:{closedTickers:{},overrides:{}},ticketBook:{items:[],watchlist:[]}};
const beforeState=structuredClone(base);beforeState.xtbHub={asOf:'2026-08-20T08:00:00Z',accounts:{czk:{currency:'CZK',value:100000,positions:[{ticker:'WDAY',name:'Workday',category:'STOCK',value:10000,net_profit_pct:-10}]}}};beforeState.ticketBook.items=[{id:'ticket-1',name:'Test koncert',workflow:'LISTED',date:'2026-08-26',qty:1,buy:1000,listPrice:1800,floorPrice:1200}];
const currentState=structuredClone(base);currentState.xtbHub={asOf:'2026-08-20T09:00:00Z',accounts:{czk:{currency:'CZK',value:100000,positions:[{ticker:'WDAY',name:'Workday',category:'STOCK',value:10000,net_profit_pct:30}]}}};currentState.ticketBook.items=[{id:'ticket-1',name:'Test koncert',workflow:'LISTED',date:'2026-08-22',qty:1,buy:1000,listPrice:1800,floorPrice:1200}];
const b0=JSON.stringify(beforeState),c0=JSON.stringify(currentState),before=buildPersonalToday(beforeState,now),current=buildPersonalToday(currentState,now);assert(JSON.stringify(beforeState)===b0&&JSON.stringify(currentState)===c0,'decision builds must not mutate integration states');
const oldX=before.find(x=>x.id==='WDAY'),newX=current.find(x=>x.id==='WDAY'),oldT=before.find(x=>x.id==='ticket-1'),newT=current.find(x=>x.id==='ticket-1');
assert(oldX?.action==='REVIEW'&&newX?.action==='TRIM','XTB action transition fixture invalid');assert(oldT?.action==='REPRICE'&&newT?.action==='SELL','ticket action transition fixture invalid');
const baseline=decisionSnapshot30(before,now),delta=decisionDelta30(current,baseline,new Date('2026-08-20T12:00:00+02:00'));
const xd=delta.items.find(x=>x.key==='money|WDAY'),td=delta.items.find(x=>x.key==='tickets|ticket-1');assert(xd?.type==='ACTION'&&xd.detail.includes('REVIEW → TRIM'),'XTB action delta missing');assert(td?.type==='ACTION'&&td.detail.includes('REPRICE → SELL'),'ticket action delta missing');
assert(delta.attention>=2,'action changes must require attention');assert(delta.items.every(x=>x.type!=='OUT'),'same stable IDs must not become false OUT changes');
console.log('DECISION DELTA 30.5 INTEGRATION TEST PASS');
