import {test,expect} from '@playwright/test';
const BASE='http://127.0.0.1:4173';
const ROOT='[data-property-decision472-root]';
async function boot(page){await page.goto(BASE,{waitUntil:'domcontentloaded'});await expect.poll(()=>page.evaluate(()=>window.__KAMIL_PROPERTY_DECISION472__?.healthy),{timeout:12000}).toBe(true);await expect(page.locator(ROOT)).toBeVisible({timeout:5000})}

test('OS472 evaluates a strong investment property as BUY',async({page})=>{await page.goto(BASE,{waitUntil:'domcontentloaded'});const m=await page.evaluate(async()=>{const {evaluateProperty472}=await import('./js/propertyDecision472.js');return evaluateProperty472({id:'good',name:'Generic A',purchasePrice:3000000,monthlyRent:15000,monthlyFund:1200,monthlyOwnerCosts:400,locationScore:85,conditionScore:85,liquidityScore:85},{targetNetYield:.04})});expect(m.dataReady).toBe(true);expect(m.netYield).toBeGreaterThan(0);expect(m.downsideYield).toBeGreaterThan(0);expect(m.decision.code).toBe('BUY');expect(m.guardrails.missingDataBlocksBuy).toBe(true);expect(m.guardrails.autoExecute).toBe(false)});

test('OS472 blocks incomplete data and provides negotiation target',async({page})=>{await page.goto(BASE,{waitUntil:'domcontentloaded'});const out=await page.evaluate(async()=>{const {evaluateProperty472}=await import('./js/propertyDecision472.js');return{missing:evaluateProperty472({purchasePrice:3000000}),neg:evaluateProperty472({purchasePrice:4200000,monthlyRent:15000,monthlyFund:1500,monthlyOwnerCosts:400,locationScore:80,conditionScore:80,liquidityScore:80})}});expect(out.missing.decision.code).toBe('INCOMPLETE');expect(out.missing.missing).toContain('monthlyRent');expect(['NEGOTIATE','PASS']).toContain(out.neg.decision.code);expect(out.neg.targetPrice).toBeGreaterThan(0);expect(out.neg.guardrails.autoExecute).toBe(false)});

test('OS472 ships with no hardcoded private candidates',async({page})=>{await boot(page);const m=await page.evaluate(()=>window.__KAMIL_PROPERTY_DECISION472__?.model);expect(m.guardrails.noHardcodedPrivateData).toBe(true);expect(m.guardrails.genericEngine).toBe(true);expect(Array.isArray(m.candidates)).toBe(true);expect(m.recommendation).toBeTruthy()});

test('OS472 remains deferred and mobile safe',async({page})=>{await page.setViewportSize({width:390,height:844});await boot(page);const state=await page.evaluate(()=>({critical:(window.__KAMIL_BOOT_BUDGET343__?.modules||[]).map(x=>x.path),deferred:(window.__KAMIL_DEFERRED345__?.modules||[]).map(x=>x.path)}));expect(state.critical).not.toContain('./propertyDecision472.js');expect(state.deferred).toContain('./propertyDecision472.js');const d=await page.locator(ROOT).evaluate(el=>({left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right,width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));expect(d.left).toBeGreaterThanOrEqual(-1);expect(d.right).toBeLessThanOrEqual(d.width+1);expect(d.scroll).toBeLessThanOrEqual(d.width+1)});
