import {test,expect} from '@playwright/test';
const BASE='http://127.0.0.1:4173';
const ROOT='[data-manager-deadlines481-root]';
async function build(page,manager){return page.evaluate(async manager=>{const {buildManagerDeadlines481}=await import('./js/managerDeadlines481.js');return buildManagerDeadlines481(manager)},manager)}

test('OS481 prioritizes overdue manager deadlines',async({page})=>{await page.goto(BASE,{waitUntil:'domcontentloaded'});const m=await build(page,{duties:[{id:'a',label:'Future',state:'soon',diff:2,isDone:false},{id:'b',label:'Late',state:'overdue',diff:-3,isDone:false}],work:[]});expect(m.recommendation.code).toBe('OVERDUE');expect(m.recommendation.title).toBe('Late');expect(m.overdue).toHaveLength(1);expect(m.rows[0].title).toBe('Late');expect(m.guardrails.noSecondTaskStore).toBe(true)});

test('OS481 never invents missing work deadlines',async({page})=>{await page.goto(BASE,{waitUntil:'domcontentloaded'});const m=await build(page,{duties:[],work:[{id:'w1',_title:'Unscheduled work',_state:'open',_diff:null,_due:null}]});expect(m.missingDeadline).toHaveLength(1);expect(m.missingDeadline[0].due).toBeNull();expect(m.missingDeadline[0].diff).toBeNull();expect(m.recommendation.code).toBe('ASSIGN_DATES');expect(m.guardrails.noInventedDeadlines).toBe(true)});

test('OS481 keeps completed duties out of the deadline queue',async({page})=>{await page.goto(BASE,{waitUntil:'domcontentloaded'});const m=await build(page,{duties:[{id:'done',label:'Done',state:'done',diff:-1,isDone:true},{id:'today',label:'Today',state:'today',diff:0,isDone:false}],work:[]});expect(m.rows.some(x=>x.sourceId==='done')).toBe(false);expect(m.recommendation.code).toBe('TODAY');expect(m.guardrails.existingCompletionOwner).toBe(true);expect(m.guardrails.noAutoComplete).toBe(true)});

test('OS481 remains deferred and mobile safe',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto(BASE,{waitUntil:'domcontentloaded'});await expect.poll(()=>page.evaluate(()=>window.__KAMIL_MANAGER_DEADLINES481__?.healthy),{timeout:12000}).toBe(true);await expect(page.locator(ROOT)).toBeVisible({timeout:5000});const state=await page.evaluate(()=>({critical:(window.__KAMIL_BOOT_BUDGET343__?.modules||[]).map(x=>x.path),deferred:(window.__KAMIL_DEFERRED345__?.modules||[]).map(x=>x.path)}));expect(state.critical).not.toContain('./managerDeadlines481.js');expect(state.deferred).toContain('./managerDeadlines481.js');const d=await page.locator(ROOT).evaluate(el=>({left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right,width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));expect(d.left).toBeGreaterThanOrEqual(-1);expect(d.right).toBeLessThanOrEqual(d.width+1);expect(d.scroll).toBeLessThanOrEqual(d.width+1)});
