import {test,expect} from '@playwright/test';
const BASE='http://127.0.0.1:4173';
const fake=`(()=>{const data={ticket_inventory:[{id:'a',event_name:'OS340 Concert',qty:2,event_date:'2026-09-10',section:'A1',buy_each_czk:1000,buy_total_czk:2000,market_status:'LISTED',ask_each_czk:1600},{id:'b',event_name:'OS340 Watch',qty:2,event_date:'2026-10-01',section:'B2',buy_each_czk:900,buy_total_czk:1800,market_status:'NOT_LISTED'}],ticket_market_snapshots:[{ticket_id:'a',checked_at:'2026-08-28T10:00:00Z',market_price_czk:1500,recommended_ask_czk:1490,recommendation_code:'LOWER',recommendation_label:'ZLEVNIT',recommendation_reason:'Cena je nad spodním pásmem.',multi_market_confidence:88,stubhub_price_czk:1520},{ticket_id:'a',checked_at:'2026-08-27T10:00:00Z',market_price_czk:1430},{ticket_id:'b',checked_at:'2026-08-28T10:00:00Z',market_price_czk:1300,recommended_ask_czk:1280,recommendation_code:'LIST',recommendation_label:'VYSTAVIT',recommendation_reason:'Trh je nad nákupem.'}],ticket_market_alerts:[]};function q(t){const api={select(){return api},order(){return api},limit(){return api},is(){return api},eq(){return api},in(){return api},update(){return api},upsert(){return api},delete(){return api},maybeSingle:async()=>({data:null,error:null}),then(resolve,reject){return Promise.resolve({data:data[t]||[],error:null}).then(resolve,reject)}};return api}window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{user:{id:'os340'}}}})},from:q})}})();`;
async function boot(page){
  await page.route('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2',r=>r.fulfill({status:200,contentType:'application/javascript',body:fake}));
  await page.goto(BASE,{waitUntil:'domcontentloaded'});
  await expect.poll(()=>page.evaluate(()=>window.__KAMIL_PERSONAL_SHELL_BOUND__===true),{timeout:10000}).toBe(true);
  await page.evaluate(()=>localStorage.setItem('sb-tswqfbkmxywxxczsoddr-auth-token','test'));
  try{await expect.poll(()=>page.evaluate(()=>!!window.__KAMIL_PLATFORM_BUS340__),{timeout:10000}).toBe(true)}catch(error){const diag=await page.evaluate(()=>({errors:window.__KAMIL_BOOT_ERRORS__||[],shell:!!window.__KAMIL_PERSONAL_SHELL_BOUND__,version:window.__KAMIL_PLATFORM_BUS340__?.version||null,body:document.body.innerText.slice(0,800)}));console.log('OS340 boot diagnostics',JSON.stringify(diag));throw error}
}
test('OS340 mounts executive, ticket and money desks',async({page})=>{await boot(page);await expect(page.locator('#todayView .exec340')).toBeVisible({timeout:10000});await page.locator('#mainNav [data-view="tickets"]').click();await expect(page.locator('#ticketIntelView .td340')).toBeVisible({timeout:10000});await expect(page.locator('#ticketIntelView')).toContainText('ACTION CENTER');await expect(page.locator('#ticketIntelView')).toContainText('OS340 Concert');await expect(page.locator('#ticketIntelView [data-filter="watch"]')).toBeVisible();await page.locator('#ticketIntelView [data-detail="a"]').first().click();await expect(page.locator('body')).toContainText('Vývoj ceny');await page.locator('#mainNav [data-view="money"]').click();await expect(page.locator('#moneyView .money340')).toBeVisible({timeout:10000});await expect(page.locator('#moneyView')).toContainText('INVESTMENT ACTION CENTER')});
test('OS340 runtime health exposes canonical modules',async({page})=>{await boot(page);await expect.poll(()=>page.evaluate(()=>window.__KAMIL_HEALTH340__?.modules?.domain===true),{timeout:10000}).toBe(true);const h=await page.evaluate(()=>window.__KAMIL_HEALTH340__);expect(h.modules.ticketDesk).toBe(true);expect(h.modules.moneyDesk).toBe(true)});
test('OS340 ticket desk fits a 390px mobile viewport',async({page})=>{await page.setViewportSize({width:390,height:844});await boot(page);await page.locator('#bottomNav [data-view="tickets"]').click();await expect(page.locator('#ticketIntelView .td340')).toBeVisible({timeout:10000});await expect(page.locator('#ticketIntelView [data-filter="watch"]')).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth);expect(overflow).toBeLessThanOrEqual(1)});
