import {test,expect} from '@playwright/test';
test('OS218 today dashboard is visible, dark and one-screen',async({page})=>{
 await page.setViewportSize({width:1792,height:828});
 await page.goto('http://127.0.0.1:4173/',{waitUntil:'domcontentloaded'});
 const dashboard=page.locator('[data-today-dashboard213]');
 await expect(dashboard).toBeVisible({timeout:20000});
 await expect(page.locator('#todayView [data-app-workspace211]')).toHaveCount(0);
 const actions=dashboard.locator('[data-action213]');
 expect(await actions.count()).toBe(6);
 const commander=dashboard.locator('.today213-commander');
 await expect(commander).toBeVisible();
 await expect(commander.locator('h2').first()).toBeVisible();
 const actionStyle=await actions.first().evaluate(el=>getComputedStyle(el).backgroundColor);
 expect(actionStyle).not.toBe('rgb(255, 255, 255)');
 const commanderBox=await commander.boundingBox();
 expect(commanderBox?.width||0).toBeGreaterThan(600);
 const fit=await page.locator('#todayView').evaluate(el=>({client:el.clientHeight,scroll:el.scrollHeight}));
 expect(fit.scroll).toBeLessThanOrEqual(fit.client+3);
 const body=await page.evaluate(()=>({client:document.documentElement.clientHeight,scroll:document.documentElement.scrollHeight}));
 expect(body.scroll).toBeLessThanOrEqual(body.client+3);
});
