import {test,expect} from '@playwright/test';
const BASE='http://127.0.0.1:4173';
const fakeSdk=`(()=>{const data={ticket_inventory:[{id:'a',event_name:'Test Concert A',qty:2,event_date:'2026-08-29',section:'A1',buy_each_czk:1000,buy_total_czk:2000,market_status:'LISTED',ask_each_czk:1700,viagogo_url:'https://www.viagogo.com/ww/E-1'},{id:'b',event_name:'Test Sport B',qty:3,event_date:'2026-09-10',section:'B2',buy_each_czk:1200,buy_total_czk:3600,market_status:'NOT_LISTED',ask_each_czk:null,viagogo_url:null},{id:'c',event_name:'Sold Show C',qty:2,event_date:'2026-09-01',section:'Floor',buy_each_czk:900,buy_total_czk:1800,market_status:'SOLD_UNDELIVERED'}],ticket_market_snapshots:[{ticket_id:'a',checked_at:'2026-08-24T05:50:00Z',market_price_czk:1450,p25_price_czk:1500,median_price_czk:1600,top_prices_czk:[1450,1500,1600],competitor_count:12,same_section_count:3,recommendation_code:'LOWER',recommendation_label:'ZLEVNIT',recommendation_reason:'Tvoje cena je nad doporučeným pásmem.',recommended_ask_czk:1490},{ticket_id:'b',checked_at:'2026-08-24T05:50:00Z',market_price_czk:1800,p25_price_czk:1850,median_price_czk:1950,top_prices_czk:[1800,1850,1950],competitor_count:8,same_section_count:2,recommendation_code:'LIST',recommendation_label:'VYSTAVIT',recommendation_reason:'Trh je nad nákupem.',recommended_ask_czk:1830}],ticket_market_alerts:[{id:1,ticket_id:'a',created_at:'2026-08-24T05:55:00Z',severity:'action',recommendation_code:'LOWER',title:'ZLEVNIT',body:'Cena potřebuje zásah.',seen_at:null},{id:2,ticket_id:'b',created_at:'2026-08-24T05:54:00Z',severity:'info',recommendation_code:'HOLD',title:'DRŽET',body:'Bez zásahu.',seen_at:null}]};function q(t){const api={select(){return api},order(){return api},limit(){return api},is(){return api},eq(){return api},in(){return api},update(){return api},upsert(){return api},delete(){return api},maybeSingle:async()=>({data:null,error:null}),then(resolve,reject){return Promise.resolve({data:data[t]||[],error:null}).then(resolve,reject)}};return api}window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{user:{id:'test-user'}}}})},from:q})}})();`;
async function boot(page){await page.route('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2',r=>r.fulfill({status:200,contentType:'application/javascript',body:fakeSdk}));await page.goto(BASE,{waitUntil:'domcontentloaded'});await expect.poll(()=>page.evaluate(()=>window.__KAMIL_PERSONAL_SHELL_BOUND__===true),{timeout:10000}).toBe(true);await page.evaluate(()=>localStorage.setItem('sb-tswqfbkmxywxxczsoddr-auth-token','test'));}

test('66.0 Profit Commander reads private server intelligence and keeps fulfillment separate',async({page})=>{await boot(page);await page.locator('#mainNav [data-personal-more]').click();await page.locator('#modalHost').getByRole('button',{name:'Ticket Intelligence'}).click();const m=page.locator('#modalHost');await expect(m).toContainText('TICKET PROFIT COMMANDER 66.0');await expect(m).toContainText('Zlevnit2 ks');await expect(m).toContainText('Vystavit3 ks');await expect(m).toContainText('Prodáno, doručit2 ks');await expect(m).toContainText('Hrubý potenciál před seller poplatky');await expect(m).toContainText('1 450 Kč · 1 500 Kč · 1 600 Kč');await expect(m).not.toContainText('AUTO SELL');});

test('66.0 workbook parser maps only solid user colors',async({page})=>{await boot(page);const out=await page.evaluate(async()=>{const m=await import('./js/ticketImport660.js');const wb={Sheets:{'Flipování 2026':{'!ref':'A1:G3',A2:{v:'Listed - A1',s:{fill:{patternType:'solid',fgColor:{rgb:'FFFFFF00'}}}},B2:{v:2},C2:{v:46263},D2:{v:1000},E2:{v:2000},A3:{v:'Sold - B2',s:{fill:{patternType:'solid',fgColor:{rgb:'FF00B0F0'}}}},B3:{v:1},C3:{v:46264},D3:{v:900},E3:{v:900}}},__xlsxUtils:{decode_range:()=>({s:{r:0},e:{r:2}})}};return{yellow:m.statusFromFill660({patternType:'solid',fgColor:{rgb:'FFFFFF00'}}),none:m.statusFromFill660({}),rows:m.parseWorkbook660(wb)}});expect(out.yellow).toBe('LISTED');expect(out.none).toBe(null);expect(out.rows.map(x=>x.marketStatus)).toEqual(['LISTED','SOLD_UNDELIVERED']);});

test('66.0 morning shows only a critical ticket handoff',async({page})=>{await page.clock.setFixedTime(new Date('2026-08-24T08:00:00+02:00'));await boot(page);await expect(page.locator('#todayView')).toContainText('TICKETY · JEN DŮLEŽITÉ',{timeout:10000});await expect(page.locator('#todayView')).toContainText('Test Concert A');await expect(page.locator('#todayView')).not.toContainText('Test Sport B');});
