import {test,expect} from '@playwright/test';
test('OS224 Smart Focus advances to the next exact action after completion without reload',async({page})=>{
 await page.setViewportSize({width:1792,height:828});
 await page.addInitScript(()=>{
  const yesterday=new Date(Date.now()-86400000).toISOString();
  const twoDaysAgo=new Date(Date.now()-2*86400000).toISOString();
  localStorage.setItem('kamil-os-state',JSON.stringify({meta:{schemaVersion:80},tasks:[],projects:[],calendar:{events:[]},ticketBook:{items:[],watchlist:[],history:[],review:[]},debtBook:{items:[],review:[]},personalAdmin:{items:[]},familyHome:{members:[]},personalSettings:{maskSensitive:true,notificationMode:'IMPORTANT'},emergencyFile:{contacts:[],assets:[]},personalInbox:{items:[]},assetBook:{items:[]},personalGoals:{items:[]},personalSpending:{transactions:[]},importCenter:{history:[]},netWorthBook:{items:[],history:[]},inbox:[],delegations:[{id:'wait-os224-a',title:'První overdue follow-up',status:'OPEN',followUpAt:twoDaysAgo},{id:'wait-os224-b',title:'Druhý overdue follow-up',status:'OPEN',followUpAt:yesterday}],learning:{typeBias:{},feedback:[]},audit:[],undo:[]}));
 });
 await page.goto('http://127.0.0.1:4173/',{waitUntil:'domcontentloaded'});
 const dashboard=page.locator('[data-today-dashboard213]');
 await expect(dashboard).toBeVisible({timeout:20000});
 await expect(page.locator('#todayView [data-app-workspace211]')).toHaveCount(0);
 const actions=dashboard.locator('[data-action213]');
 expect(await actions.count()).toBe(6);
 const stable=await page.evaluate(async()=>{const a=[...document.querySelectorAll('[data-today-dashboard213] [data-action213]')];await new Promise(r=>setTimeout(r,500));const b=[...document.querySelectorAll('[data-today-dashboard213] [data-action213]')];return a.length===6&&b.length===6&&a.every((n,i)=>n===b[i]&&n.isConnected)});
 expect(stable).toBeTruthy();
 const glance=dashboard.locator('[data-glance221]');
 await expect(glance).toBeVisible();
 const waiting=glance.locator('[data-glance-key221="waiting"]');
 await expect(waiting).toHaveAttribute('data-focus222','1');
 await expect(waiting).toHaveAttribute('data-direct223','1');
 await expect(waiting).toHaveAttribute('data-action-title223','První overdue follow-up');
 await expect(glance).toHaveAttribute('data-direct-action223','První overdue follow-up');
 await waiting.click();
 let dialog=page.locator('[role="dialog"]');
 await expect(dialog).toBeVisible();
 await expect(dialog.locator('h2')).toHaveText('První overdue follow-up');
 await dialog.getByRole('button',{name:'Hotovo'}).click();
 await expect(dialog).toHaveCount(0);
 await expect(glance).toHaveAttribute('data-completion224','done',{timeout:5000});
 await expect(waiting).toHaveAttribute('data-action-title223','Druhý overdue follow-up',{timeout:5000});
 await expect(glance).toHaveAttribute('data-direct-action223','Druhý overdue follow-up');
 await expect(waiting).toHaveAttribute('data-focus222','1');
 const debug=await page.evaluate(()=>window.__KAMIL_TODAY_DASHBOARD213__);
 expect(debug?.lastCompletion?.result).toBe('done');
 expect(debug?.lastCompletion?.title).toBe('První overdue follow-up');
 await waiting.click();
 dialog=page.locator('[role="dialog"]');
 await expect(dialog).toBeVisible();
 await expect(dialog.locator('h2')).toHaveText('Druhý overdue follow-up');
 await page.keyboard.press('Escape');
 const commander=dashboard.locator('.today213-commander');
 await expect(commander).toBeVisible();
 const boxes=await page.evaluate(()=>[...document.querySelectorAll('[data-today-dashboard213] [data-action213]')].map(el=>{const r=el.getBoundingClientRect();return {connected:el.isConnected,y:r.y,width:r.width,height:r.height}}));
 expect(boxes).toHaveLength(6);
 expect(boxes.every(b=>b.connected&&b.width>0&&b.height>0)).toBeTruthy();
 const ys=boxes.map(b=>Math.round(b.y));
 expect(Math.max(...ys)-Math.min(...ys)).toBeLessThanOrEqual(3);
 const fit=await page.locator('#todayView').evaluate(el=>({client:el.clientHeight,scroll:el.scrollHeight}));
 expect(fit.scroll).toBeLessThanOrEqual(fit.client+3);
 const body=await page.evaluate(()=>({client:document.documentElement.clientHeight,scroll:document.documentElement.scrollHeight}));
 expect(body.scroll).toBeLessThanOrEqual(body.client+3);
});
