import {test,expect} from '@playwright/test';
test('OS220 today dashboard reclaims vertical space and keeps one-row actions',async({page})=>{
 await page.setViewportSize({width:1792,height:828});
 await page.goto('http://127.0.0.1:4173/',{waitUntil:'domcontentloaded'});
 const dashboard=page.locator('[data-today-dashboard213]');
 await expect(dashboard).toBeVisible({timeout:20000});
 await expect(page.locator('#todayView [data-app-workspace211]')).toHaveCount(0);
 const actions=dashboard.locator('[data-action213]');
 expect(await actions.count()).toBe(6);
 const commander=dashboard.locator('.today213-commander');
 await expect(commander).toBeVisible();
 await expect(commander.locator('h2').first()).toBeVisible();
 const actionStyle=await actions.first().evaluate(el=>getComputedStyle(el).backgroundColor);
 expect(actionStyle).not.toBe('rgb(255, 255, 255)');
 const dashboardBox=await dashboard.boundingBox();
 const commanderBox=await commander.boundingBox();
 expect(commanderBox?.width||0).toBeGreaterThan((dashboardBox?.width||0)*.9);
 const boxes=[];for(let i=0;i<6;i++)boxes.push(await actions.nth(i).boundingBox());
 const ys=boxes.map(b=>Math.round(b?.y||0));
 expect(Math.max(...ys)-Math.min(...ys)).toBeLessThanOrEqual(3);
 const heights=boxes.map(b=>b?.height||0);
 expect(Math.max(...heights)).toBeLessThanOrEqual(72);
 const topbar=await page.locator('.topbar').boundingBox();
 expect(topbar?.height||999).toBeLessThanOrEqual(50);
 const command=await page.locator('.command-wrap').boundingBox();
 expect(command?.height||999).toBeLessThanOrEqual(38);
 const fit=await page.locator('#todayView').evaluate(el=>({client:el.clientHeight,scroll:el.scrollHeight}));
 expect(fit.scroll).toBeLessThanOrEqual(fit.client+3);
 const body=await page.evaluate(()=>({client:document.documentElement.clientHeight,scroll:document.documentElement.scrollHeight}));
 expect(body.scroll).toBeLessThanOrEqual(body.client+3);
});
