import {test,expect} from '@playwright/test';
const BASE='http://127.0.0.1:4173';
const ROOT='[data-capital-plan469-root]';
async function boot(page){await page.goto(BASE,{waitUntil:'domcontentloaded'});await expect.poll(()=>page.evaluate(()=>window.__KAMIL_CAPITAL_PLAN469__?.healthy),{timeout:12000}).toBe(true);await expect(page.locator(ROOT)).toBeVisible({timeout:5000})}

test('OS469 exposes a guarded 30-day capital plan',async({page})=>{await boot(page);const state=await page.evaluate(()=>({version:window.__KAMIL_CAPITAL_PLAN469__?.version,mounted:window.__KAMIL_CAPITAL_PLAN469__?.mounted,model:window.__KAMIL_CAPITAL_PLAN469__?.model,dataset:document.documentElement.dataset.capitalPlan469}));expect(state.version).toBe(469);expect(state.mounted).toBe(true);expect(state.dataset).toBe('1');expect(state.model.guardrails.cashflowGate).toBe(true);expect(state.model.guardrails.reserveUntouched).toBe(true);expect(state.model.guardrails.unsafeTicketsExcluded).toBe(true);expect(state.model.guardrails.explicitConfirmation).toBe(true);expect(state.model.guardrails.autoExecute).toBe(false);expect(state.model.planned).toBeLessThanOrEqual(state.model.safeCapital);await expect(page.locator(ROOT).getByRole('heading',{name:'30denní kapitálový plán',exact:true})).toBeVisible()});

test('OS469 never allocates unsafe tickets or more than OS468 deployable capital',async({page})=>{await page.goto(BASE,{waitUntil:'domcontentloaded'});const model=await page.evaluate(async()=>{const {buildCapitalPlan469}=await import('./js/capitalPlan469.js');return buildCapitalPlan469({cashflow:{version:468,healthy:true,deployable:10000,reserve:50000},sizing:{rows:[{ticker:'ABC',name:'ABC',recommendedAmount:4000,qualityScore:90,blockedReason:null,addBelow:100}]},tickets:{opportunities:[{id:'safe',name:'Safe Event',safeBuy:true,maxBuyPrice:3000},{id:'unsafe',name:'Unsafe Event',safeBuy:true,maxBuyPrice:9000}]},opportunities:{positive:[{domain:'XTB',id:'ABC',name:'ABC',score:90,confidence:80,riskFlags:[]},{domain:'TICKET',id:'safe',name:'Safe Event',score:85,confidence:80,riskFlags:[]},{domain:'TICKET',id:'unsafe',name:'Unsafe Event',score:99,confidence:99,riskFlags:['TRANSFER_UNVERIFIED']}]}})});expect(model.safeCapital).toBe(10000);expect(model.planned).toBeLessThanOrEqual(10000);expect(model.candidates).toBe(2);expect(model.steps.some(x=>x.name==='Unsafe Event')).toBe(false);expect(model.steps.some(x=>x.domain==='XTB'&&x.amount>0)).toBe(true);expect(model.steps.some(x=>x.name==='Safe Event'&&x.amount===3000)).toBe(true);expect(model.guardrails.partialTicketPurchase).toBe(false);expect(model.steps.every(x=>x.autoExecute===false)).toBe(true)});

test('OS469 stays inside mobile viewport',async({page})=>{await page.setViewportSize({width:390,height:844});await boot(page);const dims=await page.locator(ROOT).evaluate(el=>({left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right,width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));expect(dims.left).toBeGreaterThanOrEqual(-1);expect(dims.right).toBeLessThanOrEqual(dims.width+1);expect(dims.scroll).toBeLessThanOrEqual(dims.width+1)});
