import fs from 'node:fs';
const assert=(x,m)=>{if(!x)throw new Error(m)},text=f=>fs.readFileSync(f,'utf8');
const api=text('api/sec-filings.js'),source=text('js/sourceIngest32.js'),xtb=text('js/xtbTuning32.js'),tickets=text('js/ticketTuning32.js'),ui=text('js/marketEdgeUi32.js'),recovery=text('js/recoveryShield32.js'),preflight=text('js/preflight.js'),sw=text('sw.js'),html=text('index.html'),meta=text('js/releaseMeta.js');
assert(api.includes("USER_AGENT='KamilOS/32.4")&&api.includes('maxTickers')&&api.includes("req.method!=='GET'"),'SEC endpoint bounded GET contract missing');
assert(api.includes('factsOnly:true')&&api.includes('investmentAction:false'),'SEC endpoint must remain factual only');
assert(!api.includes('service_role')&&!api.includes('sb_secret_'),'server source must not embed Supabase secret');
assert(source.includes("KEY='kamil-os-source-ingest-32'")&&source.includes('device-local')&&source.includes('/api/sec-filings'),'source cache contract missing');
assert(xtb.includes("contract:'NO_AUTO_TRADE'")&&xtb.includes('executionBlocked')&&xtb.includes('reviewBeforeTrade'),'XTB execution safety missing');
assert(tickets.includes("priceBasis:marketTarget?'MARKET_INPUT':'INTERNAL_TARGET'")&&tickets.includes("action:'REVIEW'")&&tickets.includes('listPrice'),'ticket pricing/data-quality safety missing');
assert(ui.includes('market-backed target')&&ui.includes('interní target')&&ui.includes('data-ticket-tune'),'Market Edge UI missing provenance/tuning controls');
assert(recovery.includes("reason='PRE_RESTORE'")&&recovery.includes('maybeCreateRecoverySnapshot32({force:true')&&recovery.includes('cloudSchema32'),'Recovery pre-restore/future-schema guard missing');
assert(!recovery.includes('.delete(')&&!recovery.includes('.remove('),'32.4 client must not delete recovery snapshots');
assert(preflight.includes("import './marketEdgeUi32.js'")&&preflight.includes("import './recoveryShieldUi32.js'"),'32.4 side-effect modules not loaded');
assert(sw.includes('kamil-os-32.4.0-shell-r1')&&sw.includes('./js/marketEdgeUi32.js')&&sw.includes('./js/recoveryShield32.js')&&sw.includes("u.pathname.startsWith('/api/')===false"),'32.4 PWA cache contract missing');
assert(meta.includes("APP_VERSION='32.4.0'")&&html.includes('<title>Kamil OS 32.4</title>')&&html.includes('32.4.0'),'32.4 release shell mismatch');
console.log('KAMIL OS 32.4 MARKET EDGE STATIC PASS');
