import fs from 'node:fs';
const assert=(x,m)=>{if(!x)throw new Error(m)},text=f=>fs.readFileSync(f,'utf8');
const secApi=text('api/sec-filings.js'),quoteApi=text('api/market-quotes.js'),source=text('js/sourceIngest32.js'),quote=text('js/marketQuote32.js'),quoteIngest=text('js/marketQuoteIngest32.js'),xtb=text('js/xtbTuning32.js'),tickets=text('js/ticketTuning32.js'),ui=text('js/marketEdgeUi32.js'),recovery=text('js/recoveryShield32.js'),preflight=text('js/preflight.js'),sw=text('sw.js'),html=text('index.html'),meta=text('js/releaseMeta.js');
assert(secApi.includes("USER_AGENT='KamilOS/32.4.1")&&secApi.includes('maxTickers')&&secApi.includes("req.method!=='GET'"),'SEC endpoint bounded GET contract missing');
assert(secApi.includes('new URL(')&&secApi.includes("searchParams.get('tickers')")&&!secApi.includes('req.query'),'SEC endpoint must use WHATWG query parsing');
assert(secApi.includes('factsOnly:true')&&secApi.includes('investmentAction:false'),'SEC endpoint must remain factual only');
assert(!secApi.includes('service_role')&&!secApi.includes('sb_secret_'),'server source must not embed Supabase secret');
assert(source.includes("KEY='kamil-os-source-ingest-32'")&&source.includes('device-local')&&source.includes('/api/sec-filings'),'SEC source cache contract missing');
assert(quote.includes('changesDecisionAction:false')&&quote.includes('autoTrade:false')&&quote.includes("sourceQuality:'THIRD_PARTY_PUBLIC'"),'public quote facts-only contract missing');assert(quoteApi.includes('new URL(')&&quoteApi.includes("searchParams.get('symbols')")&&!quoteApi.includes('req.query'),'quote endpoint must use WHATWG query parsing');assert(quoteApi.includes('thirdPartyPublic:true')&&quoteApi.includes('investmentAction:false')&&quoteApi.includes('changesDecisionAction:false'),'quote endpoint action firewall missing');assert(quoteIngest.includes("KEY='kamil-os-market-quotes-32'")&&quoteIngest.includes('/api/market-quotes')&&quoteIngest.includes('device-local'),'quote cache contract missing');
assert(xtb.includes("contract:'NO_AUTO_TRADE'")&&xtb.includes('executionBlocked')&&xtb.includes('reviewBeforeTrade')&&xtb.includes('marketQuote'),'XTB execution/quote safety missing');
assert(tickets.includes("'SOURCED_MARKET'")&&tickets.includes("'STALE_MARKET'")&&tickets.includes('marketFresh')&&tickets.includes("action:'REVIEW'")&&tickets.includes('listPrice'),'ticket freshness/data-quality safety missing');
assert(ui.includes('PUBLIC / THIRD-PARTY')&&ui.includes('čerstvý market + zdroj')&&ui.includes('interní target')&&ui.includes('data-ticket-tune'),'Market Edge UI missing provenance/tuning controls');
assert(recovery.includes("reason:'PRE_RESTORE'")&&recovery.includes('maybeCreateRecoverySnapshot32({force:true')&&recovery.includes('cloudSchema32'),'Recovery pre-restore/future-schema guard missing');
assert(!recovery.includes('.delete(')&&!recovery.includes('.remove('),'32.4 client must not delete recovery snapshots');
assert(preflight.includes("import './marketEdgeUi32.js'")&&preflight.includes("import './recoveryShieldUi32.js'"),'32.4 side-effect modules not loaded');
assert(sw.includes('kamil-os-32.4.1-shell-r1')&&sw.includes('./js/marketEdgeUi32.js')&&sw.includes('./js/recoveryShield32.js')&&sw.includes('./js/marketQuoteIngest32.js')&&sw.includes("u.pathname.startsWith('/api/')===false"),'32.4.1 PWA cache contract missing');
assert(meta.includes("APP_VERSION='32.4.1'")&&html.includes('<title>Kamil OS 32.4</title>')&&html.includes('32.4.1'),'32.4.1 release shell mismatch');
console.log('KAMIL OS 32.4.1 MARKET EDGE STATIC PASS');
