import fs from 'node:fs';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const read=p=>fs.readFileSync(p,'utf8');
execFileSync(process.execPath,['--check','js/operator717.js'],{stdio:'pipe'});
const op=read('js/operator717.js');
const release=read('js/releaseMeta.js');
const version=release.match(/APP_VERSION='([^']+)'/)?.[1]||'0.0.0';
assert.ok(op.includes("propertyBook?.candidates||s.propertyBook?.items"),'Operator must read canonical Property Book candidates first');
assert.ok(op.includes("const closeOperator=()=>document.dispatchEvent(new KeyboardEvent('keydown'"),'Operator modal close helper missing');
assert.ok(op.includes("closeOperator();setTimeout(()=>nav(target),0)"),'Operator navigation must close modal before changing view');
assert.ok(op.includes("closeOperator();setTimeout(openOperator717,100)"),'Inbox conversion must close old Operator before reopening');
assert.ok(op.includes("document.querySelector('#modalHost [data-operator717]')"),'Operator event binding must target mounted modal DOM');
assert.ok(Number(version.split('.')[0])>=717,'Release must be OS717 or later');
console.log(`OS717 POLISH GUARD PASS · ${version}`);
