import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(p,'utf8');
const index=read('index.html');
const css=read('os1400.css');
const today=read('js/todayPage2000.js');
const runtime=read('js/viewRuntime41.js');
const advancedStyles=read('js/productAdvancedStyles.js');
const sw=read('sw.js');
const work=read('js/workPage1300.js');
const tasks=read('js/tasksOverview.js');
const tickets=read('js/ticketOverview.js');
const family=read('js/personalFamily640.js');
const home=read('js/personalHome640.js');

assert.match(index,/data-os1400="1"/,'OS1400 shell flag missing');
assert.match(index,/os-canonical\.css/,'canonical stylesheet must carry OS1400 runtime styles');
assert.match(index,/Co chceš udělat\?/,'command input must lead with user intent');
assert.match(today,/data-os1400-home/,'Today must render the OS1400 cockpit');
assert.match(today,/Nejdřív další krok\. Pak dnešní fronta a přehled oblastí\./,'Today must explain its solve-first purpose');
assert.match(today,/Po termínu/);
assert.match(today,/Čekám/);
assert.match(today,/Transfery/);
assert.match(today,/Další krok/);assert.match(today,/Dnes ještě/);assert.match(today,/Další kroky/);
assert.match(today,/Oblasti podle priority/,'Today must frame domain navigation by priority');
assert.match(today,/data-today1300-nav/,'domain navigation must stay one click');
assert.match(css,/\.os1400-focus/);
assert.match(css,/\.os1400-metrics/);
assert.match(css,/\.os1400-grid/);
assert.match(css,/\.os1400-domain/);
assert.match(css,/@media\(max-width:760px\)/,'mobile canonical layer missing');
assert.match(runtime,/restoreCanonicalProductStyles/,'runtime must delegate canonical stylesheet restoration');
assert.match(advancedStyles,/canonicalOrder=\['\.\/os-canonical\.css'\]/,'OS1400 must remain inside the single canonical runtime stylesheet');
assert.match(sw,/os-canonical\.css/,'service worker must precache canonical styles');
console.log('OS1400 usability guard PASS');