import fs from 'node:fs';
import assert from 'node:assert/strict';
const index=fs.readFileSync('index.html','utf8');
const app=fs.readFileSync('js/app.js','utf8');
const today=fs.readFileSync('js/todayPage2000.js','utf8');
const work=fs.readFileSync('js/workPage1300.js','utf8');
const tickets=fs.readFileSync('js/ticketOverview.js','utf8');
const money=fs.readFileSync('js/moneyOverview.js','utf8');
const property=fs.readFileSync('js/propertyPage1300.js','utf8');
const betting=fs.readFileSync('js/bettingOverview.js','utf8');
const css=fs.readFileSync('os-canonical.css','utf8');
const release=fs.readFileSync('js/releaseMeta.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');
assert.match(index,/data-os1700="1"/);
assert.doesNotMatch(app,/Waiting For/);
assert.match(app,/data-os1900-loading/);
assert.doesNotMatch(app,/Načítám aktuální priority/);
assert.match(today,/Dnes ještě/);
assert.match(css,/\.os1600-summary\{display:flex!important/);
assert.match(css,/\.os1600-next\{min-height:102px!important/);
assert.match(tickets,/attentionBlock \+ eventsBlock \+ clearBlock \+ summaryBlock \+ truthBlock/,'Ticket render must keep urgent flow before summaries and lifecycle truth');
assert.match(betting,/openBlock \+ summaryBlock/,'Betting render must keep open positions before summaries');
assert.match(work,/Termíny, rizika a zakázky v pořadí/);
assert.match(money,/Nejdřív akce, která něco mění/);
assert.match(property,/Nejdřív nejlepší kandidát a důvod/);
assert.match(release,/745\.0\.0/);
assert.match(sw,/kamil-os-745\.0\.0-core-r149/);
console.log('OS1700 canonical product reset: 13/13 PASS');