import fs from 'node:fs';
import * as os from './js/os42.js';
const assert=(x,m)=>{if(!x)throw new Error(m)};
const exports42=['universalSearch42','commandPalette42','decisionInbox42','personalSla42','relationshipMemory42','lifeTimeline42','smartDailyPlan42','delegationOs42','meetingCopilot42','afterMeetingProcessor42','financialWhatIf42','investmentThesis42','ticketMarketIntelligence42','opportunityRadar42','wasteDetector42','personalRiskMap42','goalEngine42','weeklyCeoReview42','agentLayer42','os42'];
for(const name of exports42)assert(typeof os[name]==='function',`OS42 export missing: ${name}`);
assert(os.OS42_VERSION==='42.0','OS42 version mismatch');
for(const [k,v] of Object.entries({autoSend:false,autoTrade:false,autoReprice:false,autoDelete:false,autoCalendarWrite:false,criticalActionsRequireConfirmation:true}))assert(os.OS42_CONTRACT[k]===v,`OS42 safety invariant mismatch: ${k}`);
const now=new Date('2026-08-21T12:00:00Z');
const state={financePlan:{cashNow:100000,reserveFloor:50000,plannedInvestment:25000},tasks:[{id:'t1',title:'D4 most',status:'OPEN',due:'2026-08-20'}],projects:[{id:'p1',name:'D4'}],delegations:[{id:'d1',person:'Petr',title:'Rozpočet D4',status:'WAITING',due:'2026-08-20',updatedAt:'2026-08-10T10:00:00Z'}],ticketBook:{items:[]},xtbHub:{},xtbReport:{},xtbStrategy:{overrides:{}},tradeJournal:{trades:[]},inbox:[],calendar:{events:[]},goals:[{id:'g1',title:'Rezerva',target:100000,current:50000}]};
assert(os.universalSearch42(state,'D4').some(x=>x.title.includes('D4')),'Universal Search does not find seeded item');
assert(os.personalSla42(state,now).breaches>=1,'SLA does not detect overdue item');
const after=os.afterMeetingProcessor42('Poslat rozpočet do 22. 8. Dohodli jsme cenu.');
assert(after.requiresConfirmation===true&&after.tasks.length>=1,'After-meeting proposals must require confirmation');
const scenario=os.financialWhatIf42(state,{monthly:25000,months:6});
assert(Number.isFinite(scenario.invested)&&scenario.note.includes('model'),'Financial what-if contract missing');
const agent=os.agentLayer42(state,'Vyřeš mi zítřek a připrav urgence',now);
assert(agent.status==='PROPOSAL_ONLY'&&agent.requiresConfirmation===true,'Agent must remain proposal-only');
for(const k of ['autoSend','autoTrade','autoReprice','autoDelete','autoCalendarWrite'])assert(agent.contract[k]===false,`Agent unsafe: ${k}`);
const core=os.os42(state,now);
assert(core.version==='42.0'&&core.contract.criticalActionsRequireConfirmation===true,'OS42 aggregate contract missing');
const meta=fs.readFileSync('js/releaseMeta.js','utf8'),index=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8'),pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
assert(meta.includes("APP_VERSION='42.0.0'")&&meta.includes("APP_RELEASE='42.0'"),'OS42 release metadata missing');
assert(index.includes('<title>Kamil OS 42.0</title>')&&index.includes('./js/os42Ui.js'),'OS42 shell integration missing');
assert(sw.includes('kamil-os-42.0.0-shell-r2')&&sw.includes('./js/os42.js')&&sw.includes('./js/os42Ui.js'),'OS42 PWA integration missing');
assert(pkg.version==='42.0.0','package version mismatch');
console.log('KAMIL OS 42 STATIC RELEASE GATE PASS');
