import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=f=>fs.readFileSync(f,'utf8');
const meta=read('js/releaseMeta.js'),index=read('index.html'),today=read('js/personalToday640.js'),assistant=read('js/personalAssistant650.js'),ask=read('js/personalAsk640.js'),waiting=read('js/personalWaiting650.js'),shell=read('js/personalShell640.js'),docs=read('js/personalDocuments640.js'),money=read('js/personalMoney640.js'),home=read('js/personalHome640.js'),family=read('js/personalFamily640.js'),usage=read('js/personalUsage650.js'),sw=read('sw.js');
assert.ok(meta.includes("APP_VERSION='65.0.0'")&&meta.includes("APP_RELEASE='65.0'"),'65.0 metadata missing');
assert.ok(index.includes('./personal65.css')&&index.includes('./js/instantShell64.js'),'65.0 shell wiring missing');
assert.ok(today.includes('ux65-primary')&&today.includes('POTOM')&&!today.includes('ux64-data-health'),'Today must remain one-action-first and free of data dashboard');
assert.ok(today.includes('data-waiting-open')&&today.includes('data-family-open'),'Today context shortcuts missing');
assert.ok(assistant.includes('personalActionCta650')&&assistant.includes('personalDailyAssistant650')&&assistant.includes('personalWaitingCenter650')&&assistant.includes('personalHomeTimeline650')&&assistant.includes('personalMoneyPlan650')&&assistant.includes('personalSearch650')&&assistant.includes('personalWeeklyReset650'),'65 assistant engine surface incomplete');
assert.ok(ask.includes("q.includes('cekam')")&&ask.includes("q.includes('do konce roku')")&&ask.includes('personalSearch650(question,s)'),'assistant question/search coverage missing');
assert.ok(waiting.includes('KDO JE TEĎ NA TAHU')&&!waiting.includes('data-waiting-choice'),'Waiting center must not render dead inline buttons');
assert.ok(shell.includes('Najít / zeptat se')&&shell.includes('openVaultRecord640')&&shell.includes('markPersonalUsage650'),'global assistant/search integration missing');
assert.ok(docs.includes('Proč tomu Kamil OS věří')&&docs.includes('+ Přidat dokument / zdroj'),'document simplification/source inbox missing');
assert.ok(money.includes('Měsíční plán domácnosti')&&money.includes('Neúplná data'),'household money/data-quality UX missing');
assert.ok(home.includes('DALŠÍCH 12 MĚSÍCŮ')&&family.includes('+ Rodinný úkol')&&family.includes('VÍKEND'),'home/family assistant upgrades missing');
assert.ok(usage.includes("localStorage.setItem(KEY")&&!usage.includes('fetch(')&&!usage.includes('store.'),'usage signals must remain local-only and content-free');
assert.ok(sw.includes("kamil-os-65.0-daily-personal-assistant-r1")&&sw.includes('./js/personalAssistant650.js')&&sw.includes('./personal65.css'),'65 service-worker cache missing');
for(const bad of ['XTB + vstupenky. Co přesně udělat teď?','KAMIL OS 64.1 / DNES','Personal Home'])assert.ok(!today.includes(bad)&&!index.includes(bad),`legacy personal UX leak: ${bad}`);
console.log('KAMIL OS 65.0 PERSONAL STATIC RELEASE PASS');
