import fs from 'node:fs';
import assert from 'node:assert/strict';

const read=f=>fs.readFileSync(f,'utf8');
const meta=read('js/releaseMeta.js');
const config=read('js/config.js');
const index=read('index.html');
const sw=read('sw.js');
const state=read('js/state.js');
const cloud=read('js/cloudPayload32.js');
const app=read('js/app.js');
const runtime=read('js/viewRuntime41.js');
const lazy=read('js/lazyBoot41.js');
const instant=read('js/instantShell42.js');
const today=read('js/todayLite43.js');
const safeIntel=read('js/safeIntelligence438.js');
const personalIntel=read('js/personalIntelligence441.js');
const diagnostics=read('js/systemDiagnostics421.js');
const rootPackage=JSON.parse(read('package.json'));
const desktopPackage=JSON.parse(read('desktop/package.json'));
const ticketSeed=read('js/currentTickets33.js');
const investmentSeed=read('js/externalInvestments33.js');
const platform43=read('js/platform43.js');
const lean431=read('js/platform431LeanUi.js');
const stability431=read('js/platform431Stability.js');
const desktop43=read('desktop/preload.cjs');
const desktopMain=read('desktop/main.cjs');

const version=meta.match(/APP_VERSION='([^']+)'/)?.[1];
const release=meta.match(/APP_RELEASE='([^']+)'/)?.[1];
assert.ok(version&&/^\d+\.\d+\.\d+$/.test(version),'release metadata must contain semantic APP_VERSION');
assert.ok(release&&/^\d+\.\d+(?:\.\d+)?$/.test(release),'release metadata must contain APP_RELEASE');
assert.ok(config.includes('SCHEMA_VERSION = 80'),'schema 80 must remain');
assert.ok(index.includes('./js/instantShell42.js'),'instant startup shell must remain wired');
assert.ok(sw.includes("self.addEventListener('fetch'"),'service worker fetch handler missing');
assert.ok(state.includes('export const store=new Store()'),'state store export missing');
assert.ok(cloud.includes('mergeColdState42'),'cloud payload must restore cold history before upload');
assert.ok(!cloud.includes('autoTrade:true'),'QA guard: cloud payload must not enable automatic trading');
assert.ok(app.includes("dataset.viewReady==='1'"),'rendered views must stay mounted');
assert.ok(app.includes('requestAnimationFrame(()=>{const runForce='),'UI renders must remain coalesced');
assert.ok(runtime.includes('warmViews=new Map()'),'runtime must cache warmed view renderers');
assert.ok(runtime.includes('hydrateColdView42(key)'),'opened views must hydrate required cold data before navigation');
assert.ok(!ticketSeed.includes('store.subscribe(')&&!ticketSeed.includes('queueMicrotask(ensure)'),'ticket seed must never mutate on import');
assert.ok(!investmentSeed.includes('store.subscribe(')&&!investmentSeed.includes('queueMicrotask(ensure)'),'investment seed must never mutate on import');
assert.ok(platform43.includes('export const ROADMAP43=['),'43 platform must expose the 60-feature delivery registry');
assert.ok(platform43.includes('startPlatform43')&&platform43.includes('dailyAutopilot43'),'43 resilience/autopilot engines missing');
assert.ok(platform43.includes('waitingAutopilot43')&&platform43.includes('portfolio43')&&platform43.includes('tickets43'),'43 domain engines missing');
assert.ok(lazy.includes("'./platform431LeanUi.js'")&&lazy.includes("'./platform431Stability.js'"),'43.1 lean/stability modules must remain available behind lazy loader');
assert.ok(!lazy.includes("'./platform43Ui.js'"),'43.1 must not load the old full 60-feature dashboard');
assert.ok(lean431.includes("let expanded=false")&&lean431.includes('Otevřít detail platformy'),'43.1 detail must be collapsed by default');
assert.ok(lean431.includes('setTimeout(()=>{if(document.visibilityState')&&lean431.includes('900'),'43.1 platform rerenders must be debounced');
assert.ok(stability431.includes("entryTypes:['longtask']")&&stability431.includes("lag>1200"),'43.1 freeze detector missing');
assert.ok(stability431.includes('recent.length>=3')&&stability431.includes('setSafeMode43(true)'),'43.1 automatic Safe Mode trip missing');
assert.ok(lazy.includes('safeMode()'),'Safe Mode guard missing from lazy loader');
assert.ok(desktop43.includes('kamilDesktop43')&&desktop43.includes('Ctrl+Alt+K'),'desktop palette bridge missing');
assert.ok(desktopMain.includes("globalShortcut.register('CommandOrControl+Alt+K'")&&desktopMain.includes('Universal Inbox'),'global desktop shortcut/tray actions missing');

assert.equal(version,'43.7.1','Safe Core release metadata must be aligned');
assert.equal(release,'43.7','43.7 release label must be aligned');
assert.equal(rootPackage.version,version,'root package version must match APP_VERSION');
assert.equal(desktopPackage.version,version,'desktop package version must match APP_VERSION');
assert.ok(index.includes('43.7.1'),'Safe Core static boot fallback must be aligned');
assert.ok(instant.includes("const VERSION='43.7.1'")&&instant.includes("kamil-os-fast-snapshot-43-7"),'Safe Core instant shell version/snapshot missing');
assert.ok(sw.includes("const CACHE='kamil-os-43.7.1-safe-core-r1'"),'Safe Core service-worker cache version missing');
assert.ok(instant.includes('SAFE CORE 43.7.1')&&instant.includes('window.__KAMIL_SAFE_CORE__=true'),'Safe Core boot contract missing');
assert.ok(runtime.includes('export function prefetchView41(){return Promise.resolve(null)}'),'Safe Core must disable hover/focus prefetch');
assert.ok(runtime.includes('export function renderExtras41(){return Promise.resolve([])}'),'Safe Core must disable background extras');
assert.ok(runtime.includes('export function refreshRiskBadge41(){return Promise.resolve(null)}'),'Safe Core must disable background risk badge');
assert.ok(runtime.includes('export function scheduleNotifications41(){return Promise.resolve(null)}'),'Safe Core must disable background notifications');
assert.ok(runtime.includes('export function warmRuntime41(){return Promise.resolve(null)}'),'Safe Core must disable runtime warming');
assert.ok(!today.includes('scheduleFull(')&&!today.includes('setTimeout(()=>loadLife42'),'Today must not auto-hydrate heavy modules');
assert.ok(today.includes("import('./personalIntelligence441.js')")&&today.includes('data-personal-intel="finance"')&&today.includes('data-personal-intel="mission"'),'Personal Intelligence controls missing');
assert.ok(!today.includes('data-safe-intel="work"')&&!today.includes('Work Command Center'),'Personal UI must not expose work controls');
assert.ok(personalIntel.includes('export function personalMission441')&&personalIntel.includes('openPersonalMission441')&&personalIntel.includes('openPersonalFinance441'),'Personal 44.1 engines missing');
assert.ok(personalIntel.includes('window.__KAMIL_PERSONAL_441_LAST__'),'Personal 44.1 performance measurement missing');
assert.ok(personalIntel.includes('WORK_RE')&&personalIntel.includes('filter(personal)'),'Personal 44.1 work-domain exclusion missing');
assert.ok(personalIntel.includes('ageHours>36')&&personalIntel.includes("action='PROVĚŘIT CENU'")&&personalIntel.includes("action='PRODAT BRZY'"),'Personal finance/ticket decision guards missing');
assert.ok(!personalIntel.includes('setInterval(')&&!personalIntel.includes('requestIdleCallback')&&!personalIntel.includes('store.subscribe('),'Personal Intelligence must remain on-demand only');
assert.ok(!personalIntel.includes('.set(')&&!personalIntel.includes('store.update(')&&!personalIntel.includes('store.patch('),'Personal Intelligence must remain read-only');
assert.ok(safeIntel.includes('export function financeTickets438')&&safeIntel.includes('export function work438')&&safeIntel.includes('export function mission438'),'Legacy Safe Intelligence compatibility engines missing');

assert.ok(lazy.includes('async function responsiveLoad')&&lazy.includes('navigator.scheduling?.isInputPending'),'responsive scheduler/input guard missing');
assert.ok(lazy.includes("document.visibilityState==='hidden'")&&lazy.includes('await sleep(250)'),'scheduler must yield while hidden or busy');
assert.ok(lazy.includes('window.__KAMIL_MODULE_TIMINGS__'),'per-module timing diagnostics missing');
assert.ok(lazy.includes("MODULE_STATS_KEY='kamil-os-module-stats-43-3'")&&lazy.includes('function recordTiming'),'persistent timing history missing');
assert.ok(lazy.includes('function adaptiveGap')&&lazy.includes('learnedDelay'),'adaptive module pacing missing');
assert.ok(lazy.includes('COLD_THRESHOLD_MS=1100')&&lazy.includes('COLD_MIN_SAMPLES=3'),'cold-load qualification guard missing');
assert.ok(lazy.includes("QUARANTINE_KEY='kamil-os-module-quarantine-43-5'"),'quarantine storage missing');
assert.ok(lazy.includes('SELF_HEAL_PROBE_DELAY_MS=20*60*1000')&&lazy.includes('SELF_HEAL_MAX_PROBES=3'),'43.6 self-healing probe limits missing');
assert.ok(lazy.includes('probeQuarantinedModule436')&&lazy.includes('runSelfHealingSweep436'),'43.6 self-healing engine missing');
assert.ok(lazy.includes("STABILITY_MEMORY_KEY='kamil-os-stability-memory-43-7'"),'43.7 stability memory storage missing');
assert.ok(lazy.includes('MEMORY_COLD_SCORE=6')&&lazy.includes('MEMORY_BLOCK_SCORE=10'),'43.7 memory policy thresholds missing');
assert.ok(lazy.includes('function updateMemory')&&lazy.includes('function stabilityPolicy')&&lazy.includes('refreshStabilityMemory'),'43.7 stability memory engine missing');
assert.ok(lazy.includes("status:'memory-blocked'")&&lazy.includes('allowMemoryRisk=false'),'43.7 automatic background isolation missing');
assert.ok(lazy.includes("window.__KAMIL_MEMORY_BLOCKED_MODULES__")&&lazy.includes("window.__KAMIL_MEMORY_COLD_MODULES__"),'43.7 memory diagnostics globals missing');
assert.ok(diagnostics.includes('43.7 STABILITY MEMORY')&&diagnostics.includes('Reset Stability Memory')&&diagnostics.includes('skóre'),'43.7 stability diagnostics missing');

console.log(`KAMIL OS CURRENT SMOKE QA PASS · ${version}`);
