import fs from 'node:fs';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const read=p=>fs.readFileSync(p,'utf8');
const index=read('index.html');
const meta=read('js/releaseMeta.js');
const config=read('js/config.js');
const sw=read('sw.js');
const state=read('js/state.js');
const cloud=read('js/cloud.js');
const app=read('js/app.js');
const runtime=read('js/viewRuntime41.js');
const ticketSeed=read('js/ticketSeed24.js');
const stability431=read('js/platform431Stability.js');
const desktop43=read('desktop/preload.cjs');
const desktopMain=read('desktop/main.cjs');
const lifeFiles=['lifePlanner446.js','cashflow447.js','wealth448.js','ticketIntel449.js','inbox450.js','maintenance451.js','family452.js','goals453.js','decision454.js','lifeDashboard455.js'].map(f=>read(`js/${f}`));
const lifePlus=read('js/personalLifePlus475.js');

const version=meta.match(/APP_VERSION='([^']+)'/)?.[1];
const release=meta.match(/APP_RELEASE='([^']+)'/)?.[1];
assert.ok(version&&/^\d+\.\d+\.\d+$/.test(version),'release metadata must contain semantic APP_VERSION');
assert.ok(release&&/^\d+\.\d+(?:\.\d+)?$/.test(release),'release metadata must contain APP_RELEASE');
assert.ok(config.includes('SCHEMA_VERSION = 80'),'schema 80 must remain');
assert.ok(index.includes('./js/instantShell64.js'),'current personal instant startup shell must remain wired');
assert.ok(index.includes('./personal65.css'),'65.0 Daily Personal Assistant styles must remain wired');
assert.ok(sw.includes("self.addEventListener('fetch'"),'service worker fetch handler missing');
assert.ok(state.includes('export const store=new Store()'),'state store export missing');
assert.ok(cloud.includes('mergeColdState42'),'cloud payload must restore cold history before upload');
assert.ok(!cloud.includes('autoTrade:true'),'QA guard: cloud payload must not enable automatic trading');
assert.ok(app.includes("dataset.viewReady==='1'"),'rendered views must stay mounted');
assert.ok(app.includes('requestAnimationFrame(()=>{const runForce='),'UI renders must remain coalesced');
assert.ok(runtime.includes('warmViews=new Map()'),'runtime must cache warmed view renderers');
assert.ok(runtime.includes('hydrateColdView42(key)'),'opened views must hydrate required cold data before navigation');
assert.ok(runtime.includes("personalHardening650.js")&&runtime.includes("personalUx:'65.0'"),'65.0 personal preflight must remain canonical');
assert.ok(!ticketSeed.includes('store.subscribe(')&&!ticketSeed.includes('queueMicrotask(ensure)'),'ticket seed must never mutate on import');
assert.ok(stability431.includes('export function'),'platform stability module missing');
assert.ok(desktop43.length>0&&desktopMain.length>0,'desktop shell files missing');
for(const file of lifeFiles)assert.ok(file.length>0,'legacy life engine missing');
assert.ok(lifePlus.length>0,'legacy personal life plus module missing');
console.log(`KAMIL OS ${version} QA STATIC PASS`);
