import fs from 'fs';
const assert=(x,m)=>{if(!x)throw new Error(m)};
const files=['index.html','manifest.webmanifest','sw.js','js/config.js','js/state.js','js/more26.js','js/preflight.js','js/cloud.js','js/smartImport29.js','js/smartImportApply29.js','js/smartImportUi29.js','smart_import_29_test.mjs','integration_29_4.mjs','release_gate_29_4.mjs'];
for(const f of files)assert(fs.existsSync(f),'Missing 29.4 file '+f);
const text=f=>fs.readFileSync(f,'utf8');
const html=text('index.html');assert(html.includes('Kamil OS 29.4')&&html.includes('29.4.0'),'29.4 visible shell version missing');for(const legacy of ['data-view="work"','id="view-work"','work24.js','directorUi25.js','projectMoneyUi25.js'])assert(!html.includes(legacy),'legacy work runtime leaked '+legacy);
const config=text('js/config.js');assert(config.includes("APP_VERSION = '29.4.0'")&&config.includes('SCHEMA_VERSION = 41'),'29.4 version/schema mismatch');for(const immutable of ['kamil_os_state','kamil_calendar_cache','kamil_xtb_data','kamil-os-state','kamil-os-22-meta','kamil-os-22-sync-queue'])assert(config.includes(immutable),'immutable storage key missing '+immutable);
const state=text('js/state.js');for(const x of ['personalSpending:{transactions:[]}','importCenter:{history:[]}','s.personalSpending.transactions','s.importCenter.history',"uid('txn')","uid('import')"])assert(state.includes(x),'schema 41 state missing '+x);
const more=text('js/more26.js');for(const x of ['Smart Import','smartImportView','bindSmartImport','Importované transakce','Historie importů'])assert(more.includes(x),'More missing Smart Import '+x);
const engine=text('js/smartImport29.js');for(const x of ['previewImport','buildImportPlan','parseDelimited','parseAmount','parseDate','detectImportSource','SPENDING','REVOLUT','XTB','TICKETS','ADMIN','dvoukrokový','duplicity','různé měny'])assert(engine.includes(x),'Smart Import engine missing '+x);assert(!engine.includes('totalMixed'),'Smart Import must never create mixed-currency total');
const apply=text('js/smartImportApply29.js');for(const x of ['applySmartImport','positionValue','account.source===\'SMART_IMPORT\'','nepřepisuje existující celkovou hodnotu'])assert(apply.includes(x),'Smart Import apply safety missing '+x);
const ui=text('js/smartImportUi29.js');for(const x of ['Vytvořit bezpečný náhled','Potvrdit a zapsat nové položky','Potvrdit import?','PDF a fotky','Document Scanner'])assert(ui.includes(x),'Smart Import UI missing '+x);
const backup=text('js/backupGuard26.js');for(const x of ['transactions:','imports:','personalSpending','importCenter'])assert(backup.includes(x),'Backup Guard missing import data '+x);
const preflight=text('js/preflight.js');for(const x of ['Importované transakce','Historie importů'])assert(preflight.includes(x),'Preflight missing '+x);
const cloud=text('js/cloud.js');for(const x of ['Importované transakce','Historie importů'])assert(cloud.includes(x),'Cloud conflict summary missing '+x);
const sw=text('sw.js');assert(sw.includes('29.4.0'),'PWA cache version mismatch');for(const x of ['smartImport29.js','smartImportApply29.js','smartImportUi29.js'])assert(sw.includes(x),'PWA missing '+x);
const manifest=text('manifest.webmanifest');assert(manifest.includes('Kamil OS 29.4')&&manifest.includes('Smart Import'),'Manifest not updated to 29.4');
const workflow=text('.github/workflows/qa.yml');assert(workflow.includes('smart_import_29_test.mjs'),'GitHub QA missing Smart Import engine test');
console.log('KAMIL OS 29.4 STATIC QA PASS');