import fs from 'fs';
const assert=(x,m)=>{if(!x)throw new Error(m)};
const text=f=>fs.readFileSync(f,'utf8');
const files=['index.html','manifest.webmanifest','sw.js','js/config.js','js/releaseMeta.js','js/releaseStamp.js','js/personalToday26.js','js/decisionExplain30.js','js/decisionNext30.js','js/decisionDelta30.js','js/decisionExplainUi30.js','js/today29.js','decision_delta_30_test.mjs','decision_delta_30_integration_test.mjs','release_gate_30_5.mjs'];
for(const f of files)assert(fs.existsSync(f),'Missing 30.5 file '+f);
const config=text('js/config.js');assert(config.includes('SCHEMA_VERSION = 42'),'30.5 must retain schema 42');for(const immutable of ['kamil_os_state','kamil_calendar_cache','kamil_xtb_data','kamil-os-state','kamil-os-22-meta','kamil-os-22-sync-queue'])assert(config.includes(immutable),'immutable storage key missing '+immutable);
const meta=text('js/releaseMeta.js');assert(meta.includes("APP_VERSION='30.5.0'")&&meta.includes("APP_RELEASE='30.5'"),'30.5 canonical release metadata missing');
const html=text('index.html');assert(html.includes('Kamil OS 30.5')&&html.includes('30.5.0'),'30.5 visible shell version missing');for(const x of ['./js/releaseStamp.js','./js/personalCopilotUi30.js','./js/documentScannerUi30.js','./js/documentFilingUi30.js','./js/decisionExplainUi30.js'])assert(html.includes(x),'30.5 runtime missing '+x);
const explain=text('js/decisionExplain30.js');for(const x of ['decisionExplain30','facts','source','confidence','nepřepočítává'])assert(explain.includes(x),'Decision Explain invariant missing '+x);for(const browser of ['document.','window.','localStorage','navigator.','fetch(','XMLHttpRequest','supabase','store.'])assert(!explain.includes(browser),'Decision Explain engine must stay pure: '+browser);
const next=text('js/decisionNext30.js');for(const x of ['decisionNext30','Co dělat teď','Kdy koupit / přikoupit','Kdy prodat / snížit','nedoplňuje odhadem'])assert(next.includes(x),'Next Trigger invariant missing '+x);for(const browser of ['document.','window.','localStorage','navigator.','fetch(','XMLHttpRequest','supabase','store.'])assert(!next.includes(browser),'Next Trigger engine must stay pure: '+browser);
const delta=text('js/decisionDelta30.js');for(const x of ['decisionSnapshot30','decisionDelta30','ACTION','TRIGGER','Vypadlo z aktuálního Top','Baseline je uložený jen na tomto zařízení'])assert(delta.includes(x),'Decision Delta invariant missing '+x);for(const browser of ['document.','window.','localStorage','navigator.','fetch(','XMLHttpRequest','supabase','store.'])assert(!delta.includes(browser),'Decision Delta engine must stay pure: '+browser);
const today=text('js/today29.js');for(const x of ["from './releaseMeta.js'",'decisionBaseline30','decisionDelta30','Decision Delta 30.5','Zkontrolováno','store.setMeta','ack-delta'])assert(today.includes(x),'30.5 Today integration missing '+x);assert(!today.includes("import {APP_VERSION} from './config.js'"),'Today must use canonical release metadata');assert(!today.includes('store.mutate'),'Decision baseline must remain local meta, not synced state mutation');
const decision=text('js/personalToday26.js');for(const x of ['XTB_DECISION','TICKET_DECISION','when:d.when','buyRule:d.buyRule','sellRule:d.sellRule'])assert(decision.includes(x),'30.4 decision propagation regression '+x);
const safety=[['js/netWorth29.js','Měny se nikdy nesčítají'],['js/spendingIntelligence29.js','měny se nikdy nesčítají'],['js/portfolioRebalancer29.js','MISSING_FX'],['js/portfolioRiskMap29.js','PARTIAL_FX'],['js/ticketProfit29.js','Měny se nikdy nesčítají']];for(const [f,x] of safety){const body=text(f);assert(body.includes(x)&&!body.includes('totalMixed'),`safety regression ${f}`)}
const sw=text('sw.js');assert(sw.includes('kamil-os-30.5.0-shell-r1'),'PWA cache version mismatch');for(const x of ['decisionExplain30.js','decisionNext30.js','decisionDelta30.js','decisionExplainUi30.js','documentScanner30.js','documentFiling30.js','personalCopilot30.js'])assert(sw.includes(x),'PWA missing '+x);
const manifest=text('manifest.webmanifest');assert(manifest.includes('Kamil OS 30.5')&&manifest.includes('Decision Delta'),'30.5 manifest missing');const workflow=text('.github/workflows/qa.yml');for(const x of ['decision_delta_30_test.mjs','decision_delta_30_integration_test.mjs'])assert(workflow.includes(x),'GitHub QA missing '+x);
console.log('KAMIL OS 30.5 STATIC QA PASS');
