import fs from 'fs';
const assert=(x,m)=>{if(!x)throw new Error(m)};
const text=f=>fs.readFileSync(f,'utf8');
const files=['index.html','manifest.webmanifest','sw.js','js/config.js','js/releaseMeta.js','js/releaseStamp.js','js/personalToday26.js','js/decisionExplain30.js','js/decisionExplainUi30.js','decision_explain_30_test.mjs','decision_explain_30_integration_test.mjs','release_gate_30_3.mjs'];
for(const f of files)assert(fs.existsSync(f),'Missing 30.3 file '+f);
const config=text('js/config.js');assert(config.includes('SCHEMA_VERSION = 42'),'30.3 must retain schema 42');for(const immutable of ['kamil_os_state','kamil_calendar_cache','kamil_xtb_data','kamil-os-state','kamil-os-22-meta','kamil-os-22-sync-queue'])assert(config.includes(immutable),'immutable storage key missing '+immutable);
const meta=text('js/releaseMeta.js');assert(meta.includes("APP_VERSION='30.3.0'")&&meta.includes("APP_RELEASE='30.3'"),'30.3 canonical release metadata missing');
const html=text('index.html');assert(html.includes('Kamil OS 30.3')&&html.includes('30.3.0'),'30.3 visible shell version missing');for(const x of ['./js/releaseStamp.js','./js/personalCopilotUi30.js','./js/documentScannerUi30.js','./js/documentFilingUi30.js','./js/decisionExplainUi30.js'])assert(html.includes(x),'30.3 runtime missing '+x);
const engine=text('js/decisionExplain30.js');for(const x of ['decisionExplain30','facts','source','confidence','nepřepočítává'])assert(engine.includes(x),'Decision Explain invariant missing '+x);for(const browser of ['document.','window.','localStorage','navigator.','fetch(','XMLHttpRequest','supabase','store.'])assert(!engine.includes(browser),'Decision Explain engine must stay pure: '+browser);
const today=text('js/personalToday26.js');for(const x of ['PERSONAL_TIMELINE','CASHFLOW_90','PERSONAL_RISK','RENEWAL_RADAR','XTB_DECISION','TICKET_DECISION','TICKET_OPPORTUNITY','po termínu → priorita 96','dnes → priorita 90','1–7 dní → priorita 82'])assert(today.includes(x),'Decision score mapping missing '+x);
const ui=text('js/decisionExplainUi30.js');for(const x of ['Proč teď?','type=\'button\'','aria-label','Skutečná fakta','Otevřít rozhodnutí'])assert(ui.includes(x),'Decision Explain UI missing '+x);for(const forbidden of ['store.mutate','localStorage','fetch(','XMLHttpRequest','supabase.'])assert(!ui.includes(forbidden),'Decision Explain UI write/network regression '+forbidden);
const safety=[['js/netWorth29.js','Měny se nikdy nesčítají'],['js/spendingIntelligence29.js','měny se nikdy nesčítají'],['js/portfolioRebalancer29.js','MISSING_FX'],['js/portfolioRiskMap29.js','PARTIAL_FX'],['js/ticketProfit29.js','Měny se nikdy nesčítají']];for(const [f,x] of safety){const body=text(f);assert(body.includes(x)&&!body.includes('totalMixed'),`safety regression ${f}`)}
const sw=text('sw.js');assert(sw.includes('kamil-os-30.3.0-shell-r1'),'PWA cache version mismatch');for(const x of ['decisionExplain30.js','decisionExplainUi30.js','documentScanner30.js','documentFiling30.js','personalCopilot30.js'])assert(sw.includes(x),'PWA missing '+x);
const manifest=text('manifest.webmanifest');assert(manifest.includes('Kamil OS 30.3')&&manifest.includes('Decision Explainability'),'30.3 manifest missing');const workflow=text('.github/workflows/qa.yml');for(const x of ['decision_explain_30_test.mjs','decision_explain_30_integration_test.mjs'])assert(workflow.includes(x),'GitHub QA missing '+x);
console.log('KAMIL OS 30.3 STATIC QA PASS');
