await import('./qa_32_6.mjs');
await import('./financial_decision_32_test.mjs');
await import('./financial_decision_32_static_test.mjs');
import fs from 'node:fs';
const t=f=>fs.readFileSync(f,'utf8'),assert=(x,m)=>{if(!x)throw new Error(m)};
const meta=t('js/releaseMeta.js'),config=t('js/config.js'),sw=t('sw.js'),pre=t('js/preflight.js'),engine=t('js/financialDecision32.js'),ui=t('js/financialDecisionUi32.js');
const vm=meta.match(/APP_VERSION='(\d+)\.(\d+)\.(\d+)'/),versionOk=vm&&(Number(vm[1])>32||(Number(vm[1])===32&&Number(vm[2])>=7));assert(versionOk,'release must retain 32.7+ Financial Command');
assert(config.includes('SCHEMA_VERSION = 80'),'schema 80 must remain');
assert(sw.includes('./js/financialDecision32.js')&&sw.includes('./js/financialDecisionUi32.js'),'Financial Command PWA shell missing');
assert(pre.includes("import './financialDecisionUi32.js'"),'Financial Command not loaded');
assert(engine.includes("contract:'ROUTING_PROPOSAL_ONLY'")&&engine.includes('hardFloorBeforeXtb:true'),'Financial Command routing safety missing');
assert(ui.includes('XTB & rozhodovací centrum')&&ui.includes('XTB je tady')&&ui.includes('Jak dopadly moje bývalé prodeje'),'Financial Command user-facing UI missing');
console.log('KAMIL OS 32.7+ FINANCIAL COMMAND REGRESSION PASS');
