import fs from 'fs';
const assert=(x,m)=>{if(!x)throw new Error(m)};
const text=f=>fs.readFileSync(f,'utf8');
const files=['index.html','manifest.webmanifest','sw.js','js/config.js','js/releaseMeta.js','js/releaseStamp.js','js/personalCopilot30.js','js/documentScanner30.js','js/documentScannerUi30.js','document_scanner_30_test.mjs','document_scanner_30_integration_test.mjs','release_gate_30_1.mjs'];
for(const f of files)assert(fs.existsSync(f),'Missing 30.1 file '+f);
const config=text('js/config.js');assert(config.includes('SCHEMA_VERSION = 42'),'30.1 must retain schema 42');for(const immutable of ['kamil_os_state','kamil_calendar_cache','kamil_xtb_data','kamil-os-state','kamil-os-22-meta','kamil-os-22-sync-queue'])assert(config.includes(immutable),'immutable storage key missing '+immutable);
const meta=text('js/releaseMeta.js');assert(meta.includes("APP_VERSION='30.1.0'")&&meta.includes("APP_RELEASE='30.1'"),'30.1 canonical release metadata missing');
const html=text('index.html');assert(html.includes('Kamil OS 30.1')&&html.includes('30.1.0'),'30.1 visible shell version missing');for(const x of ['./js/releaseStamp.js','./js/personalCopilotUi30.js','./js/documentScannerUi30.js','./js/ticketProfitUi29.js'])assert(html.includes(x),'30.1 runtime missing '+x);
const engine=text('js/documentScanner30.js');for(const x of ['documentScanCandidate','documentRecordDraft','findDocumentDuplicate','sensitiveKinds','safeCategory','safeCurrency','raw OCR text','filename','bez potvrzení'])assert(engine.includes(x),'Document Scanner invariant missing '+x);for(const browser of ['document.','window.','localStorage','navigator.','fetch(','FormData','XMLHttpRequest','supabase','store.'])assert(!engine.includes(browser),'Document Scanner engine must stay browser/network independent: '+browser);for(const x of ['sourceName:','fileName:','filename:','rawText:','ocrText:'])assert(!engine.includes(x),'Document Scanner persistence privacy regression '+x);
const ui=text('js/documentScannerUi30.js');for(const x of ['DOCUMENT SCANNER / 30.1','PRIVACY FIRST','capture="environment"','Vyfotit','Vybrat obrázek / soubor','Vložit text',"T.recognize(file,'ces+eng'",'raw OCR text ani filename ne','při uložení se zahodí'])assert(ui.includes(x),'Document Scanner UI missing '+x);assert(ui.includes('...draft.record')&&ui.includes('store.mutate'),'Document Scanner reviewed-save path missing');
const safety=[['js/netWorth29.js','Měny se nikdy nesčítají'],['js/spendingIntelligence29.js','měny se nikdy nesčítají'],['js/portfolioRebalancer29.js','MISSING_FX'],['js/portfolioRiskMap29.js','PARTIAL_FX'],['js/ticketProfit29.js','Měny se nikdy nesčítají']];for(const [f,x] of safety){const body=text(f);assert(body.includes(x)&&!body.includes('totalMixed'),`safety regression ${f}`)}
const sw=text('sw.js');assert(sw.includes('kamil-os-30.1.0-shell-r1'),'PWA cache version mismatch');for(const x of ['releaseMeta.js','releaseStamp.js','personalCopilot30.js','documentScanner30.js','documentScannerUi30.js'])assert(sw.includes(x),'PWA missing '+x);
const manifest=text('manifest.webmanifest');assert(manifest.includes('Kamil OS 30.1')&&manifest.includes('Document Scanner'),'30.1 manifest missing');const workflow=text('.github/workflows/qa.yml');assert(workflow.includes('document_scanner_30_test.mjs')&&workflow.includes('document_scanner_30_integration_test.mjs'),'GitHub QA missing Document Scanner coverage');
console.log('KAMIL OS 30.1 STATIC QA PASS');
