globalThis.localStorage={_d:new Map(),getItem(k){return this._d.has(k)?this._d.get(k):null},setItem(k,v){this._d.set(k,String(v))},removeItem(k){this._d.delete(k)}};
Object.defineProperty(globalThis,'navigator',{value:{serviceWorker:{}},configurable:true});
const {validateState,repairState,migrate,store}=await import('./js/state.js');
const {runPreflight}=await import('./js/preflight.js');
const assert=(x,m)=>{if(!x)throw new Error(m)};

const bad={tasks:{oops:true},projects:[],ticketBook:{items:[]},debtBook:{items:[]},personalAdmin:{items:{}},familyHome:{members:{}},emergencyFile:{contacts:{},assets:{}},personalInbox:{items:{}},assetBook:{items:{}}};
const v=validateState(bad);assert(v.ok===true,'recoverable shape');assert(v.issues.length>=6,'recoverable Personal Autopilot issues detected');
const repaired=repairState(bad).state;assert(Array.isArray(repaired.tasks),'repair tasks');assert(Array.isArray(repaired.personalAdmin.items),'repair personal admin');assert(Array.isArray(repaired.familyHome.members),'repair family');assert(Array.isArray(repaired.emergencyFile.contacts),'repair emergency contacts');assert(Array.isArray(repaired.emergencyFile.assets),'repair emergency assets');assert(Array.isArray(repaired.personalInbox.items),'repair Personal Inbox');assert(Array.isArray(repaired.assetBook.items),'repair Asset Book');assert(repaired.personalSettings.maskSensitive===true&&repaired.personalSettings.notificationMode==='IMPORTANT','personal settings defaults');
assert(validateState(null).ok===false,'null backup fatal');
const compacted=migrate({meta:{schemaVersion:38},undo:[{label:'old',state:{undo:[{label:'nested',state:{undo:[]}}]}}]});assert(compacted.undo.length===1&&Array.isArray(compacted.undo[0].state.undo)&&compacted.undo[0].state.undo.length===0,'migrate removes nested undo history');assert(compacted.meta.schemaVersion===39,'migrate old schema to v39');
store.replace(migrate({tasks:[],projects:[],ticketBook:{items:[],watchlist:[]},debtBook:{items:[]},personalAdmin:{items:[]},familyHome:{members:[]},emergencyFile:{contacts:[],assets:[]},personalInbox:{items:[]},assetBook:{items:[]}}),'preflight');
store.mutate('první změna',s=>{s.personalInbox.items.push({id:'x',title:'Test',status:'NEW'})});store.mutate('druhá změna',s=>{s.personalInbox.items[0].title='Test 2'});assert(store.get().undo.length===2,'undo keeps configured steps');assert(store.get().undo.every(x=>Array.isArray(x.state?.undo)&&x.state.undo.length===0),'undo snapshots never contain nested undo snapshots');
assert(store.get().meta.schemaVersion===39,'schema 39');const pf=runPreflight();assert(pf.ok===true,'preflight ready');assert(pf.checks.some(x=>x.name==='Personal Inbox'&&x.ok),'Personal Inbox preflight');assert(pf.checks.some(x=>x.name==='Asset Book'&&x.ok),'Asset Book preflight');
console.log('PERSONAL AUTOPILOT 28 RELEASE GATE PASS');