import fs from 'node:fs';
const fail=m=>{console.error(`OS333+ release guard: ${m}`);process.exitCode=1};
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
const release=read('./js/releaseMeta.js'),boot=read('./js/instantShell64.js'),mod=read('./js/unifiedCommand333.js'),resilience=read('./js/os333Resilience.js'),css=read('./os333.css'),pkg=JSON.parse(read('./package.json'));
const releaseVersion=release.match(/APP_VERSION='([^']+)'/)?.[1]||'';
const releaseMajor=Number(releaseVersion.split('.')[0]||0);
if(releaseMajor<333)fail(`releaseMeta ${releaseVersion||'unknown'} predates canonical OS333`);
if(pkg.version!==releaseVersion)fail(`package version ${pkg.version} does not match releaseMeta ${releaseVersion}`);
for(const path of ['./unifiedCommand333.js','./os333Resilience.js'])if(!boot.includes(path))fail(`OS333 boot missing ${path}`);
if(releaseMajor>=334&&!boot.includes("./focusRadar334.js"))fail('OS334+ boot missing ./focusRadar334.js');
if(releaseMajor>=342&&!boot.includes("./navigationOS342.js"))fail('OS342+ boot missing ./navigationOS342.js');
if(releaseMajor>=343){for(const symbol of ['BOOT343','__KAMIL_BOOT_BUDGET343__','kamil:boot-budget343'])if(!boot.includes(symbol))fail(`OS343 boot budget missing ${symbol}`);if(!fs.existsSync(new URL('./e2e_os343_boot_budget.spec.mjs',import.meta.url)))fail('missing OS343 browser regression')}
if(releaseMajor>=344){const shellPath='./js/personalShell640.js';if(!fs.existsSync(new URL(shellPath,import.meta.url)))fail(`missing OS344 file ${shellPath}`);else{const shell=read(shellPath);for(const symbol of ['SHELL344','__KAMIL_PERSONAL_SHELL344__','ticketMarketWatch656.js','personalAsk640.js'])if(!shell.includes(symbol))fail(`OS344 lazy shell missing ${symbol}`)}if(!fs.existsSync(new URL('./e2e_os344_lazy_shell.spec.mjs',import.meta.url)))fail('missing OS344 browser regression')}
if(releaseMajor>=345){for(const symbol of ['DEFER345','__KAMIL_DEFERRED345__','scheduleDeferred345','kamil:deferred345-complete'])if(!boot.includes(symbol))fail(`OS345 deferred boot missing ${symbol}`);for(const path of ['./performance330.js','./ticketQa332.js'])if(!boot.includes(path))fail(`OS345 deferred boot missing ${path}`);if(!fs.existsSync(new URL('./e2e_os345_deferred_boot.spec.mjs',import.meta.url)))fail('missing OS345 browser regression')}
if(releaseMajor>=346){const loaderPath='./js/ticketOnDemand346.js';if(!fs.existsSync(new URL(loaderPath,import.meta.url)))fail(`missing OS346 file ${loaderPath}`);else{const loader=read(loaderPath);for(const symbol of ['STATE346','__KAMIL_TICKET_ON_DEMAND346__','loadTicketDesk346','ticket-on-demand346'])if(!loader.includes(symbol))fail(`OS346 ticket loader missing ${symbol}`)}if(!boot.includes("./ticketOnDemand346.js"))fail('OS346 boot missing ticketOnDemand346');if(boot.includes("optionalImport('./ticketDesk331.js'"))fail('OS346 must not eager-load ticketDesk331');if(!fs.existsSync(new URL('./e2e_os346_ticket_on_demand.spec.mjs',import.meta.url)))fail('missing OS346 browser regression')}
if(releaseMajor>=347){for(const eager of ["optionalImport('./performance330.js'","optionalImport('./ticketQa332.js'","optionalImport('./ticketDesk331.js'"])if(boot.includes(eager))fail(`OS347 critical path contains forbidden eager import ${eager}`);if(!boot.includes("deferredImport('./performance330.js'"))fail('OS347 performance330 must remain deferred');if(!boot.includes("deferredImport('./ticketQa332.js'"))fail('OS347 ticketQa332 must remain deferred');if(!boot.includes("optionalImport('./ticketOnDemand346.js'"))fail('OS347 ticket on-demand loader must remain critical');if(!fs.existsSync(new URL('./e2e_os347_critical_path.spec.mjs',import.meta.url)))fail('missing OS347 critical-path regression')}
if(releaseMajor>=348){const wsPath='./js/workspaces305.js';if(!fs.existsSync(new URL(wsPath,import.meta.url)))fail(`missing OS348 file ${wsPath}`);else{const ws=read(wsPath);if(ws.includes('new MutationObserver'))fail('OS348 workspaces305 must not own a global MutationObserver');for(const symbol of ['observer:\'retired-os348\'','store.subscribe','kamil:view-change'])if(!ws.includes(symbol))fail(`OS348 workspaces305 missing ${symbol}`)}if(boot.includes("optionalImport('./workspaces305.js'"))fail('OS348 workspaces305 must not remain critical');if(!boot.includes("deferredImport('./workspaces305.js'"))fail('OS348 workspaces305 must be deferred');if(!fs.existsSync(new URL('./e2e_os348_workspace_retirement.spec.mjs',import.meta.url)))fail('missing OS348 browser regression')}
if(releaseMajor>=350){const currentPath='./ci_current_350_test.mjs';if(!fs.existsSync(new URL(currentPath,import.meta.url)))fail(`missing OS350 current architecture guard ${currentPath}`);for(const script of ['test:current','test:release'])if(!pkg.scripts?.[script])fail(`OS350 package script missing ${script}`);if(!String(pkg.scripts?.['test:release']||'').includes('ci_current_350_test.mjs'))fail('OS350 release gate must include current architecture guard')}
if(releaseMajor>=361){const longPath='./e2e_os361_ticket_longlist.spec.mjs',loaderPath='./js/ticketOnDemand346.js',visualPath='./ticketDesk357.css';if(!fs.existsSync(new URL(longPath,import.meta.url)))fail(`missing OS361 browser regression ${longPath}`);if(!String(pkg.scripts?.['test:e2e']||'').includes('e2e_os361_ticket_longlist.spec.mjs'))fail('OS361 test:e2e must include long-list Ticket Desk regression');if(!fs.existsSync(new URL(visualPath,import.meta.url)))fail(`missing OS361 Ticket Desk visual layer ${visualPath}`);const loader=read(loaderPath);for(const symbol of ['ensureVisualCss361','ticketDesk357.css'])if(!loader.includes(symbol))fail(`OS361 on-demand ticket visual contract missing ${symbol}`)}
for(const symbol of ['installUnifiedCommand333','Ticket Action Center','RUNTIME HEALTH','INVESTMENT ACTION CENTER'])if(!mod.includes(symbol))fail(`missing ${symbol}`);
for(const symbol of ['installOS333Resilience','data-os333-exec','data-os333-invest'])if(!resilience.includes(symbol))fail(`resilience missing ${symbol}`);
if(!css.includes('.os333-drawer'))fail('ticket detail drawer CSS missing');
for(const p of ['./js/ticketDesk331.js','./js/ticketQa332.js','./js/ticketCloud660.js','./js/financeCommand258.js'])if(!fs.existsSync(new URL(p,import.meta.url)))fail(`missing critical file ${p}`);
if(releaseMajor>=334)for(const p of ['./js/focusRadar334.js','./focusRadar334.css'])if(!fs.existsSync(new URL(p,import.meta.url)))fail(`missing OS334 file ${p}`);
if(releaseMajor>=342){const navPath='./js/navigationOS342.js';if(!fs.existsSync(new URL(navPath,import.meta.url)))fail(`missing OS342 file ${navPath}`);else{const nav=read(navPath);for(const symbol of ['installNavigation342','stopImmediatePropagation','kamil:navigate'])if(!nav.includes(symbol))fail(`OS342 navigation missing ${symbol}`)}}
if(!process.exitCode)console.log(`OS333+ release guard OK · ${releaseVersion}`);
