const mem=new Map();globalThis.localStorage={getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)};
const now=new Date(),fresh=now.toISOString(),assert=(x,m)=>{if(!x)throw new Error(m)};
localStorage.setItem('kamil-os-market-quotes-32',JSON.stringify({fetchedAt:fresh,quotes:[{symbol:'EURCZK=X',price:25,currency:'CZK',asOf:fresh,sourceUrl:'https://finance.yahoo.com/quote/EURCZK=X'}]}));
const {xtbPortfolioAudit}=await import('./js/xtbAudit24.js');
const {xtbContributionPlan32,xtbContribution32Contract}=await import('./js/xtbContribution32.js');
const {ticketEventPortfolio32,ticketPortfolio32Contract}=await import('./js/ticketPortfolio32.js');
const {liveBrain32Contract}=await import('./js/liveBrain32.js');
const {copilotWrite32Contract}=await import('./js/copilotWrite32.js');
const {cloudSchema32}=await import('./js/cloudPayload32.js');
const {cloudHistoryPlan32Info}=await import('./js/cloudHistoryPlan32.js');
const {remoteAutoCandidates32}=await import('./js/remoteMerge32.js');
const state={meta:{schemaVersion:80},financePlan:{plannedInvestment:25000},xtbHub:{asOf:fresh,accounts:{czk:{currency:'CZK',value:100000,positions:[{ticker:'EUNA.DE',name:'Core Global Aggregate Bond',category:'ETF',value:50000},{ticker:'EXUS.DE',name:'MSCI World ex USA',category:'ETF',value:50000}]},eur:{currency:'EUR',value:1000,positions:[{ticker:'VWCE.DE',name:'FTSE All-World',category:'ETF',value:1000}]}}},xtbReport:{asOf:fresh},xtbStrategy:{overrides:{}},ticketBook:{items:[{id:'c1',name:'Clash 17 - A2',date:'2026-10-24',workflow:'LISTED',qty:2,buy:2500,listPrice:0},{id:'c2',name:'Clash 17 - A3',date:'2026-10-24',workflow:'HOLD',qty:2,buy:2500}],watchlist:[],history:[]}};
const audit=xtbPortfolioAudit(state);assert(audit.valuationComplete&&Math.round(audit.total)===125000,'FX-safe valuation gate failed');
const contribution=xtbContributionPlan32(state);assert(contribution.ok&&!contribution.blocked&&contribution.plannedCzk===25000,'fresh 25k contribution gate failed');assert(!xtbContribution32Contract.autoTrade&&xtbContribution32Contract.requiresCompleteFx,'contribution firewall failed');
localStorage.setItem('kamil-os-market-quotes-32',JSON.stringify({fetchedAt:fresh,quotes:[]}));assert(!xtbPortfolioAudit(state).valuationComplete&&xtbContributionPlan32(state).blocked,'missing FX must block precise allocation');
const tickets=ticketEventPortfolio32(state);assert(tickets.totalEvents===1&&tickets.events[0].qty===4,'ticket event consolidation gate failed');assert(!ticketPortfolio32Contract.autoPrice&&!ticketPortfolio32Contract.autoSell&&!ticketPortfolio32Contract.staleMarketCanDrivePrice,'ticket automation firewall failed');
assert(!liveBrain32Contract.autoTrading&&!liveBrain32Contract.unsourcedOverride&&liveBrain32Contract.fallback==='RULE_ENGINE','Live Brain safety failed');
assert(copilotWrite32Contract.flow.join('>')==='UNDERSTAND>PROPOSE>PREVIEW>CONFIRM>EXECUTE'&&!copilotWrite32Contract.silentWrite,'Copilot safety failed');
assert(cloudSchema32({meta:{schemaVersion:81}},80).future,'future schema guard failed');assert(cloudHistoryPlan32Info.deleteEnabled===false,'cloud history delete safety failed');
const freshRemote={id:'x',domain:'tasks',entityId:'n',op:'UPSERT',kind:'REMOTE_NEW',payload:{id:'n'},seen:false},conflict={...freshRemote,id:'y',kind:'CONFLICT'},del={...freshRemote,id:'z',op:'DELETE',kind:'REMOTE_DELETE'};assert(remoteAutoCandidates32({actionable:[freshRemote,conflict,del]}).length===1,'remote merge safety failed');
console.log('KAMIL OS 32.5 RELEASE GATE PASS');
