import fs from 'node:fs';
const assert=(x,m)=>{if(!x)throw new Error(m)};
const {buildPersonalToday}=await import('./js/personalToday26.js');
const {decisionExplain30}=await import('./js/decisionExplain30.js');
const {decisionNext30}=await import('./js/decisionNext30.js');
const {decisionSnapshot30,decisionDelta30}=await import('./js/decisionDelta30.js');
const {systemHealth31}=await import('./js/systemHealth31.js');
const meta=fs.readFileSync('js/releaseMeta.js','utf8'),config=fs.readFileSync('js/config.js','utf8'),html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8'),cloud=fs.readFileSync('js/cloud.js','utf8'),command=fs.readFileSync('js/command.js','utf8'),vercel=fs.readFileSync('vercel.json','utf8');
assert(meta.includes("APP_VERSION='31.0.0'")&&meta.includes("APP_RELEASE='31.0'"),'31.0 release metadata mismatch');assert(config.includes('SCHEMA_VERSION = 42')&&config.includes("from './releaseMeta.js'"),'31.0 schema/version source mismatch');assert(html.includes('Kamil OS 31.0')&&html.includes('./js/systemHealthUi31.js'),'31.0 shell missing');assert(!html.includes('@supabase/supabase-js@2'),'31.0 local boot must not eagerly load Supabase');assert(sw.includes('kamil-os-31.0.0-shell-r1')&&sw.includes('systemHealth31.js'),'31.0 PWA runtime missing');assert(cloud.includes('loadSdk')&&cloud.includes('hasStoredCloudSession'),'31.0 lazy cloud missing');assert(command.includes('Tomuhle příkazu zatím nerozumím'),'31.0 safe command fallback missing');assert(vercel.includes('Content-Security-Policy'),'31.0 security headers missing');
const now=new Date('2026-08-20T10:00:00+02:00');const base={financePlan:{currency:'CZK',cashNow:200000,reserveFloor:50000,cashflow:[]},tasks:[],personalAdmin:{items:[]},familyHome:{members:[]},assetBook:{items:[]},emergencyFile:{contacts:[],assets:[]},calendar:{events:[]},debtBook:{items:[]},audit:[],xtbStrategy:{closedTickers:{},overrides:{}},ticketBook:{items:[],watchlist:[]}};
const beforeState=structuredClone(base);beforeState.xtbHub={asOf:'2026-08-20T08:00:00Z',accounts:{czk:{currency:'CZK',value:100000,positions:[{ticker:'WDAY',name:'Workday',category:'STOCK',value:10000,net_profit_pct:-10}]}}};beforeState.ticketBook.items=[{id:'ticket-1',name:'Test koncert',workflow:'LISTED',date:'2026-08-26',qty:1,buy:1000,listPrice:1800,floorPrice:1200}];
const currentState=structuredClone(base);currentState.xtbHub={asOf:'2026-08-20T09:00:00Z',accounts:{czk:{currency:'CZK',value:100000,positions:[{ticker:'WDAY',name:'Workday',category:'STOCK',value:10000,net_profit_pct:30}]}}};currentState.ticketBook.items=[{id:'ticket-1',name:'Test koncert',workflow:'LISTED',date:'2026-08-22',qty:1,buy:1000,listPrice:1800,floorPrice:1200}];
const before=buildPersonalToday(beforeState,now),current=buildPersonalToday(currentState,now);for(const d of current){const e=decisionExplain30(d);assert(e.score===d.priority,'31.0 explainability regression');if(d.action)assert(decisionNext30(d).hasStructuredTrigger,'31.0 Next Trigger regression')}
const baseline=decisionSnapshot30(before,now),delta=decisionDelta30(current,baseline,new Date('2026-08-20T12:00:00+02:00'));assert(delta.items.find(x=>x.key==='money|WDAY')?.type==='ACTION','31.0 XTB Decision Delta regression');assert(delta.items.find(x=>x.key==='tickets|ticket-1')?.type==='ACTION','31.0 ticket Decision Delta regression');
const health=systemHealth31({...base,meta:{schemaVersion:42,cloudMode:'local'},xtbHub:{asOf:'2026-08-20T09:00:00Z'}},{lastBackupAt:'2026-08-19T09:00:00Z'},{schemaVersion:42,stateBytes:250000,queueBytes:0,pendingSync:false,online:true,serviceWorkerSupported:true,serviceWorkerControlled:true,releaseConsistent:true},now);assert(health.score>=90&&health.checks.find(x=>x.id==='storage')?.level==='OK','31.0 System Health regression');
console.log('KAMIL OS 31.0 RELEASE GATE PASS');
