import fs from 'node:fs';
import {cloudPayload32,cloudSchema32,mergeCloudIntoDevice32} from './js/cloudPayload32.js';
import {authCooldownSeconds32,authErrorMessage32} from './js/authUx32.js';
import {remoteAutoCandidates32,applyRemoteItem32} from './js/remoteMerge32.js';
const assert=(x,m)=>{if(!x)throw new Error(m)},text=f=>fs.readFileSync(f,'utf8');
const meta=text('js/releaseMeta.js'),config=text('js/config.js'),html=text('index.html'),sw=text('sw.js'),cloud=text('js/cloud.js');assert(meta.includes("APP_VERSION='32.0.0'")&&meta.includes("APP_RELEASE='32.0'"),'release version mismatch');assert(config.includes('SCHEMA_VERSION = 80'),'schema 80 missing');assert(html.includes('<title>Kamil OS 32.0</title>')&&html.includes('32.0.0'),'shell mismatch');assert(sw.includes('kamil-os-32.0.0-shell-r1'),'PWA cache mismatch');assert(cloud.includes('futureSchema:true')&&!cloud.slice(cloud.indexOf('export async function flushQueue'),cloud.indexOf('export async function loadCloud')).includes('store.replace'),'cloud/queue safety regression');
const big={meta:{schemaVersion:79},tasks:[{id:'a',title:'A'}],undo:[{state:{blob:'x'.repeat(100000)}}]},safe=cloudPayload32(big,80);assert(safe.undo.length===0&&safe.meta.schemaVersion===80,'cloud payload compacting failed');assert(JSON.stringify(safe).length<5000,'cloud payload unexpectedly large');assert(cloudSchema32({meta:{schemaVersion:81}},80).future,'future schema not blocked');const merged=mergeCloudIntoDevice32({undo:[{label:'device'}],ui:{x:1}},{meta:{schemaVersion:79},undo:[],ui:{}},80);assert(merged.undo[0].label==='device'&&merged.ui.x===1,'device-local state not preserved');
const now=Date.parse('2026-08-20T22:00:00Z');assert(authCooldownSeconds32(new Date(now-10000).toISOString(),now)>0,'auth cooldown missing');assert(authErrorMessage32({status:429,message:'rate limit'}).includes('omezuje'),'auth 429 message missing');const state={tasks:[],personalAdmin:{items:[]},ticketBook:{items:[]},debtBook:{items:[]},personalGoals:{items:[]},netWorthBook:{items:[]},personalSpending:{transactions:[]},assetBook:{items:[]},personalInbox:{items:[]}},fresh={id:'x',domain:'tasks',entityId:'n',op:'UPSERT',kind:'REMOTE_NEW',payload:{id:'n',title:'N'},seen:false},conflict={...fresh,id:'y',kind:'CONFLICT',entityId:'c'};assert(remoteAutoCandidates32({actionable:[fresh,conflict]}).length===1,'unsafe auto candidate');assert(applyRemoteItem32(state,fresh).ok&&state.tasks[0].title==='N','remote apply failed');
console.log('KAMIL OS 32.0 RELEASE GATE PASS');
