import fs from 'node:fs';
const assert=(x,m)=>{if(!x)throw new Error(m)};const text=f=>fs.readFileSync(f,'utf8');
const engine=text('js/remoteInbox31.js'),ui=text('js/remoteInboxUi31.js'),sync=text('js/smartSync31.js'),idb=text('js/indexedDb31.js'),dataUi=text('js/dataEngineUi31.js');
assert(engine.includes('remoteInbox31')&&engine.includes("kind='CONFLICT'")&&engine.includes("kind='REMOTE_NEW'")&&engine.includes("kind='REMOTE_DELETE'")&&engine.includes('syncPayloadSafe31'),'Remote Inbox classifier/privacy guard missing');
for(const destructive of ['store.mutate','store.replace','store.persist','cloudClient','\.update(','\.delete(','\.upsert('])assert(!engine.includes(destructive.replaceAll('\\','')),'Remote Inbox engine must stay pure/read-only: '+destructive);
assert(sync.includes('fetchRemoteChanges31')&&sync.includes(".select('id,device_id,seq,domain,entity_id,op,payload,client_at,created_at')")&&sync.includes(".neq('device_id',deviceId)")&&sync.includes('remoteReadOnly:true'),'remote cloud read path missing');
const remoteFn=sync.slice(sync.indexOf('export async function fetchRemoteChanges31'),sync.indexOf('export async function runSmartSync31'));for(const destructive of ['.insert(','.update(','.delete(','.upsert(','store.mutate','store.replace'])assert(!remoteFn.includes(destructive),'remote fetch must be SELECT-only: '+destructive);
assert(idb.includes("get('remote-inbox')")&&idb.includes("key:'remote-inbox'")&&idb.includes('seenIds')&&idb.includes('lastCheckedAt'),'local read markers missing');
assert(ui.includes('READ ONLY')&&ui.includes('nikdy automaticky neaplikuje')&&ui.includes('kamil_os_state zůstává autoritativní')&&ui.includes('Supabase SDK se v čistě lokálním režimu nenačítá'),'Remote Inbox safety copy missing');
for(const destructive of ['store.mutate','store.replace','runSmartSync31','uploadPendingSmartSync31'])assert(!ui.includes(destructive),'Remote Inbox UI must not mutate/apply: '+destructive);
assert(dataUi.includes("import './remoteInboxUi31.js';"),'Remote Inbox UI not mounted');
console.log('KAMIL OS 31.5 REMOTE INBOX STATIC PASS');
