import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const read=p=>readFile(new URL(p,import.meta.url),'utf8');
const runtime=await read('./js/runtimeOwnership1100.js');
const coordinator=await read('./js/runtimeCoordinator1050.js');
for(const token of ['ownEvent1100','ownTimeout1100','scheduleMicrotask1100','cancelScheduled1100','ownObserver1100','disposeOwner1100','disposeDomain1100','activateDomain1100','runtimeSnapshot1100','installRuntimeOwnership1100'])assert.ok(runtime.includes(`function ${token}`)||runtime.includes(`function ${token}(`)||runtime.includes(` ${token}(`)||runtime.includes(`export function ${token}`),`OS1100 missing ${token}`);
assert.ok(runtime.includes("defineDomain1100('tickets')"),'OS1100 tickets domain missing');
assert.ok(runtime.includes("defineDomain1100('betting')"),'OS1100 betting domain missing');
assert.ok(runtime.includes("defineDomain1100('finance')"),'OS1100 finance domain missing');
assert.ok(runtime.includes("defineDomain1100('control')"),'OS1100 control domain missing');
assert.ok(runtime.includes('__KAMIL_RUNTIME1100__'),'OS1100 global diagnostics API missing');
assert.ok(coordinator.includes("['runtimeOwnership1100','./runtimeOwnership1100.js','installRuntimeOwnership1100'"),'OS1050 must install OS1100 before legacy runtime stages');
assert.equal((runtime.match(/setInterval\s*\(/g)||[]).length,0,'OS1100 must not introduce polling');
assert.ok((runtime.match(/setTimeout\s*\(/g)||[]).length<=1,'OS1100 scheduler must own at most one timeout primitive');
console.log('Runtime ownership guard PASS: registry, scheduler, domain lifecycle, cleanup and OS1050 wiring present');
