import fs from 'node:fs';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const read=p=>fs.readFileSync(p,'utf8');
execFileSync(process.execPath,['--check','js/oneOS977.js'],{stdio:'pipe'});
const legacy=read('js/oneOS977.js');
const strategy=read('js/strategy788.js');
for(const token of ["strategy:['./strategy788.js','openStrategy788']",'Pokročilé / legacy',"console.error('[OS969]'",'Legacy centrum se nepodařilo otevřít'])assert.ok(legacy.includes(token),`Strategy safe legacy gateway missing ${token}`);
assert.ok(strategy.includes("noAutoFinancialExecution:true"),'Financial guardrail missing');
assert.ok(strategy.includes("noInventedExternalRates:true"),'External-rate guardrail missing');
console.log('OS789 STRATEGY POLISH GUARD PASS · gateway OS977');
