import fs from 'node:fs';
const js=fs.readFileSync('js/todayDashboard213.js','utf8');
const css=fs.readFileSync('todayDashboard213.css','utf8');
const workspace=fs.readFileSync('js/appWorkspace211.js','utf8');
const boot=fs.readFileSync('js/instantShell64.js','utf8');
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
assert(js.includes('data-today-dashboard213'),'dashboard marker missing');
assert(js.includes('fallbackCommander213'),'empty-state fallback missing');
assert(js.includes('syncDashboard213'),'late-render sync missing');
assert(js.includes("setTimeout(run,1800)"),'late-render retry missing');
assert(js.includes("label:'Inbox'")&&js.includes("label:'Čekám'")&&js.includes("label:'Zítra'")&&js.includes("label:'7 dní'"),'quick actions missing');
assert(workspace.includes("view==='tickets'||view==='today'"),'Today must be excluded from OS211 pager');
assert(boot.includes("./todayDashboard213.js")&&boot.includes('installTodayDashboard213'),'dashboard not booted');
assert(css.includes('grid-template-columns:minmax(0,1fr) 260px')&&css.includes('grid-template-columns:repeat(6,minmax(0,1fr))'),'desktop/mobile layout missing');
assert(css.includes('var(--panel,#101720)'),'dark panel token missing');
assert(!css.includes('background:var(--surface,#fff)'),'white fallback surface must not be used in dark mode');
assert(css.includes('.today213-fallback'),'fallback card styling missing');
console.log('OS218 one-screen dashboard repair regression OK');
