import fs from 'node:fs';
const js=fs.readFileSync('js/todayDashboard213.js','utf8');
const action=fs.readFileSync('js/personalActionExecution641.js','utf8');
const css=fs.readFileSync('todayDashboard213.css','utf8');
const nav=fs.readFileSync('compactNavigation212.css','utf8');
const workspace=fs.readFileSync('js/appWorkspace211.js','utf8');
const boot=fs.readFileSync('js/instantShell64.js','utf8');
const release=fs.readFileSync('js/releaseMeta.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
assert(js.includes("import {openPersonalAction641} from './personalActionExecution641.js'"),'OS223 action engine wiring missing');
assert(js.includes('export function smartFocusAction223'),'OS223 exact action selector missing');
assert(js.includes("button.dataset.direct223=direct?.key===key?'1':'0'"),'OS223 direct action marker missing');
assert(js.includes('await openPersonalAction641(next.action)'),'OS223 must open existing personal action engine');
assert(action.includes("new CustomEvent('kamil:personal-action-updated'"),'OS224 central action update event missing');
assert(action.includes("updated224('done',action)")&&action.includes("updated224('tomorrow',action)")&&action.includes("updated224('postponed',action)")&&action.includes("updated224('waiting',action)"),'OS224 mutation outcomes must emit completion event');
assert(js.includes("window.addEventListener('kamil:personal-action-updated'"),'OS224 dashboard completion listener missing');
assert(js.includes('lastCompletion224=e.detail||null;run()'),'OS224 completion must trigger immediate focus refresh');
assert(js.includes("glance.dataset.completion224=lastCompletion224?.result||''"),'OS224 completion observability missing');
assert(js.includes('lastCompletion:lastCompletion224'),'OS224 debug completion state missing');
assert(js.includes('data-today-dashboard213'),'dashboard marker missing');
assert(js.includes('fallbackCommander213'),'empty-state fallback missing');
assert(js.includes('syncDashboard213'),'late-render sync missing');
assert(js.includes('function syncActions213'),'stable action sync missing');
assert(!js.includes('actions.innerHTML=nextActions'),'action bar must not be rebuilt for count changes');
assert(js.includes('function smartGlance222'),'OS222 smart focus model missing');
assert(workspace.includes("view==='tickets'||view==='today'"),'Today must be excluded from OS211 pager');
assert(boot.includes("./todayDashboard213.js")&&boot.includes('installTodayDashboard213'),'dashboard not booted');
assert(css.includes('display:flex!important;flex-direction:row!important')&&css.includes('height:70px!important'),'forced action flex row missing');
assert(css.includes('height:calc(100dvh - 108px)'),'Today vertical reclaim missing');
assert(css.includes('button[data-focus222="1"]:after')&&css.includes("content:'TEĎ'"),'focus marker missing');
assert(nav.includes('--os212-top:48px')&&nav.includes('.command-wrap{height:36px!important'),'compact top chrome missing');
assert(!css.includes('background:var(--surface,#fff)'),'white fallback surface must not be used in dark mode');
assert(release.includes("224.0.0"),'release metadata not OS224');
assert(sw.includes('kamil-os-224.0.0-core-r1'),'OS224 cache bump missing');
console.log('OS224 Smart Focus completion loop regression OK');
