import fs from 'node:fs';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const read=p=>fs.readFileSync(p,'utf8');
for(const f of ['js/todayPriority696.js','js/todayPage101.js'])execFileSync(process.execPath,['--check',f],{stdio:'pipe'});
const priority=read('js/todayPriority696.js'),page=read('js/todayPage101.js'),css=read('todayPriority696.css');
for(const label of ['TEĎ','DNES','ČEKÁ','PŘÍLEŽITOST'])assert.ok(priority.includes(label),`OS696 missing lane ${label}`);
assert.ok(priority.includes("legacy.hidden=true"),'OS696 must hide legacy Today Hub UI');
assert.ok(priority.includes("window.__KAMIL_TODAY_PRIORITY696__"),'OS696 health marker missing');
assert.ok(page.includes("from './todayPriority696.js'"),'Today page is not wired to OS696 cockpit');
for(const token of ['mountCanonical()','appendTodayPriority696()','refreshTodayPriority696()'])assert.ok(page.includes(token),`Today canonical priority mount missing ${token}`);
assert.ok(!page.includes('setTimeout('),'Today priority must not return to timeout refresh chains');
assert.ok(css.includes('@media(max-width:850px)'),'OS696 mobile layout guard missing');
console.log('OS696 PRIORITY COCKPIT GUARD PASS · canonical Today pipeline');