import fs from 'node:fs';
const js=fs.readFileSync('js/uxFoundation238.js','utf8');
const css=fs.readFileSync('uxFoundation238.css','utf8');
const boot=fs.readFileSync('js/instantShell64.js','utf8');
const release=fs.readFileSync('js/releaseMeta.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
const version=Number(release.match(/APP_VERSION='(\d+)\./)?.[1]||0);
assert(js.includes('Command Palette'),'OS230 palette missing');
assert(js.includes('openQuickAdd'),'OS231 universal quick add missing');
assert(js.includes('kamil-os-last-view-232'),'OS232 nav memory missing');
assert(js.includes("e.altKey")&&js.includes("Shift+D"),'OS233 shortcuts missing');
assert(css.includes('repeat(6,minmax(0,1fr))')&&css.includes('repeat(5,minmax(0,1fr))'),'OS234 mobile nav cleanup missing');
assert(css.includes('@media(min-width:851px) and (max-width:1180px)'),'OS235 responsive engine missing');
assert(js.includes('kamil-os-density-236')&&css.includes('data-density238'),'OS236 density modes missing');
assert(js.includes("kamil:detail-drawer")&&css.includes('.ux238-drawer'),'OS237 detail drawer missing');
assert(css.includes('.main-nav button:hover')&&css.includes('.main-nav button.on'),'OS229/238 visual polish missing');
assert(boot.includes("./uxFoundation238.js")&&boot.includes('installUxFoundation238'),'OS238 boot wiring missing');
assert(version>=238,'release must not regress below OS238');
assert(sw.includes('uxFoundation238.js')&&sw.includes('uxFoundation238.css'),'UX238 missing from current service-worker cache');
assert(js.includes("closest?.('#quickAddBtn')")&&js.includes('stopImmediatePropagation'),'UX238 quick-add capture guard missing');
console.log(`OS229-238 UX Foundation regression OK on OS${version}`);
