export const LOCKED_BETS=Object.freeze([
 {id:'locked-zbrojovka-brno-win-254-500',event:'Zbrojovka Brno vs Hradec Kralove',home:'Zbrojovka Brno',away:'Hradec Kralove',market:'MATCH_RESULT',period:'FULL_TIME',selection:'HOME',label:'Zbrojovka Brno - vyhra',odds:2.54,stakeCzk:500,status:'OPEN',bookmaker:'chance',source:'user-confirmed',locked:true,placedAt:null,recordedAt:null,settledAt:null,pnlCzk:null,notes:'User confirmed this bet was already placed.'},
 {id:'locked-machida-kawasaki-btts-yes-162-300',event:'Machida vs Kawasaki',home:'Machida',away:'Kawasaki',market:'BOTH_TEAMS_TO_SCORE',period:'FULL_TIME',selection:'YES',label:'Machida - Kawasaki: oba daji gol ANO',odds:1.62,stakeCzk:300,status:'OPEN',bookmaker:'chance',source:'user-confirmed',locked:true,placedAt:null,recordedAt:null,settledAt:null,pnlCzk:null,notes:'User confirmed this bet was already placed.'}
]);
function normalize(value){return String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function sameTeam(actual,expected){const a=normalize(actual);const e=normalize(expected);return !!a&&!!e&&(a===e||a.includes(e)||e.includes(a))}
function eventMatches(event,bet){return sameTeam(event?.home,bet.home)&&sameTeam(event?.away,bet.away)}
export function findLockedBet(event,market,selection){const marketType=String(market?.type||'').toUpperCase();const marketPeriod=String(market?.period||'').toUpperCase();const outcome=String(selection?.outcome||'').toUpperCase();return LOCKED_BETS.find(bet=>bet.status==='OPEN'&&bet.locked===true&&eventMatches(event,bet)&&marketType===bet.market&&marketPeriod===bet.period&&outcome===bet.selection)||null}
export function decorateLedgerSelection(event,market,selection){const bet=findLockedBet(event,market,selection);if(!bet)return {...selection,existingBet:false,ledgerDecision:'AVAILABLE'};return {...selection,existingBet:true,ledgerBetId:bet.id,lockedStakeCzk:bet.stakeCzk,lockedOdds:bet.odds,ledgerDecision:'LOCKED_NO_ADD'}}
export function ledgerSummary(){const openBets=LOCKED_BETS.filter(bet=>bet.status==='OPEN');return {persistence:'code_seed',writable:false,openCount:openBets.length,knownTicketExposureCzk:openBets.reduce((sum,bet)=>sum+Number(bet.stakeCzk||0),0),priorReportedExposureCzk:1000,priorReportedExposureUnresolved:true,rule:'Locked bets are never re-recommended or reversed. If later data weakens, the only allowed action is NO_ADD.',note:'The user had already reported 1000 CZK staked before these two confirmed tickets; those earlier tickets are not yet identified individually.'}}
export function publicLedger(){return LOCKED_BETS.map(bet=>({...bet}))}
