import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
const js=fs.readFileSync('js/controlOperations1047.js','utf8');
const runtime=fs.readFileSync('js/consolidationRuntime.js','utf8');
const storage=fs.readFileSync('js/featureStorage.js','utf8');
const need=(ok,msg)=>{if(!ok)throw new Error(`OS1047 guard: ${msg}`)};
for(const f of ['js/controlOperations1047.js','js/consolidationRuntime.js','js/featureStorage.js'])execFileSync(process.execPath,['--check',f],{stdio:'pipe'});
need(js.includes("CONTROL_OPERATIONS1047_VERSION='1047.1.0'"),'version missing');
const contracts={1038:'operationsOverview1038',1039:'snapshotDiff1039',1040:'confirmedRestore1040',1041:'createWatch1041',1042:'watchManager1042',1043:'createAutomation1043',1044:'runAutomations1044',1045:'resolveConflict1045',1046:'installHealthRibbon1046',1047:'openOperations1047'};
for(const [v,name] of Object.entries(contracts))need(js.includes(`function ${name}`)||js.includes(`async function ${name}`),`OS${v} ${name} missing`);
for(const name of ['testAutomation1043','conflictApplicationPreview1045'])need(js.includes(`function ${name}`),`${name} missing`);
need(js.includes('READ_ONLY_FIELD_DIFF')&&js.includes('entityDiff('),'field-level snapshot diff missing');
need(js.includes("String(confirmation).trim()!=='RESTORE'"),'typed restore confirmation missing');
need(js.includes("condition:'CHANGED'"),'watch change-only policy missing');
need(js.includes('WATCH_FIELDS'),'domain-scoped watch fields missing');
need(js.includes("enabled:false"),'new automations must start disabled');
need(js.includes('executed:false'),'automation/conflict preview must remain non-executing');
need(js.includes('noExternalWrites:true')&&js.includes('noFinancialExecution:true')&&js.includes('noBettingExecution:true')&&js.includes('noTicketExecution:true'),'operations safety policy missing');
for(const token of ['fetch(','XMLHttpRequest','sendMoney(','placeBet(','buyTicket(','sellTicket(','autoMerge('])need(!js.includes(token),`forbidden execution/network pattern ${token}`);
need(runtime.includes("install('./controlOperations1047.js','installControlOperations1047')"),'central runtime operations installer missing');
need(!fs.readFileSync('js/bettingBootstrap543.js','utf8').includes('controlOperations1047'),'betting bootstrap must not own operations');
need(storage.includes('indexedDB')&&storage.includes('featureStorageHealth'),'shared feature persistence/health missing');
console.log('OS1047 control operations guard OK');
