import fs from 'node:fs';
const need=['visual947.css','os111.css','design304.css','unified307.css','js/uxFoundation238.js'];
for(const f of need)if(!fs.existsSync(f))throw new Error(`missing ${f}`);
const visual=fs.readFileSync('visual947.css','utf8');
const os111=fs.readFileSync('os111.css','utf8');
const design=fs.readFileSync('design304.css','utf8');
const unified=fs.readFileSync('unified307.css','utf8');
const ux=fs.readFileSync('js/uxFoundation238.js','utf8');
for(const token of ['OS947 Visual Rebuild','--v947-accent:#7c8cff','--v947-sidebar-w:252px','.modal-box:has([data-modal-buttons]>.btn:nth-child(8))','grid-template-columns:repeat(6,minmax(0,1fr))','@media(max-width:850px)','prefers-reduced-motion'])if(!visual.includes(token))throw new Error(`visual contract missing ${token}`);
if(!os111.startsWith("@import url('./visual947.css');"))throw new Error('OS111 must load OS947 first');
if(!design.startsWith("@import url('./visual947.css');"))throw new Error('late Design304 must reload OS947');
if(!design.includes('.ux238-palette-card')||!design.includes('.ux238-drawer'))throw new Error('palette/drawer polish missing');
if(!unified.includes('--u307-accent:#7c8cff')||!unified.includes('color:#fff!important'))throw new Error('Unified307 not aligned to OS947');
for(const token of ["setNavDisplay238(el,!mobile)","[data-view=\"family\"]","[data-view=\"more\"]","mobile?'6':'desktop'"])if(!ux.includes(token))throw new Error(`mobile IA contract missing ${token}`);
if(/narrow\s*=\s*width<=430[\s\S]{0,900}setNavDisplay238\(el,narrow\)/.test(ux))throw new Error('legacy narrow mobile hiding returned');
const braces=s=>[...s].reduce((n,c)=>n+(c==='{')-(c==='}'),0);
for(const [name,css] of [['visual947.css',visual],['os111.css',os111],['design304.css',design],['unified307.css',unified]])if(braces(css)!==0)throw new Error(`unbalanced braces in ${name}`);
if(/sendMoney\s*\(|placeBet\s*\(|buyTicket\s*\(|sellTicket\s*\(|executeTrade\s*\(/.test(ux))throw new Error('visual/nav patch must not add execution behavior');
console.log('OS947 Visual Rebuild guard OK');
