import dns from 'node:dns/promises';
import net from 'node:net';
const TTL=20*60*1000;
const cache=globalThis.__KAMIL_OFFICIAL_MARKET_CACHE__||(globalThis.__KAMIL_OFFICIAL_MARKET_CACHE__=new Map());
const FX_URL='https://api.frankfurter.app/latest';
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const decode=s=>clean(String(s||'').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&euro;|&#8364;/gi,'€').replace(/&pound;|&#163;/gi,'£'));
const textFromHtml=html=>decode(String(html||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<svg[\s\S]*?<\/svg>/gi,' ').replace(/<[^>]+>/g,' '));
const num=s=>{let x=String(s||'').replace(/\s/g,'').replace(/[^0-9.,]/g,'');if(!x)return null;const comma=x.lastIndexOf(','),dot=x.lastIndexOf('.');if(comma>dot)x=x.replace(/\./g,'').replace(',','.');else x=x.replace(/,/g,'');const n=Number(x);return Number.isFinite(n)?n:null};
const privateIp=ip=>{if(net.isIPv4(ip)){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)}if(net.isIPv6(ip)){const x=ip.toLowerCase();return x==='::1'||x==='::'||x.startsWith('fc')||x.startsWith('fd')||x.startsWith('fe8')||x.startsWith('fe9')||x.startsWith('fea')||x.startsWith('feb')}return true};
export async function safeOfficialUrl(value){try{const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)return null;const host=u.hostname.toLowerCase();if(host==='localhost'||host.endsWith('.local'))return null;if(net.isIP(host)&&privateIp(host))return null;const rows=await dns.lookup(host,{all:true,verbatim:true});if(!rows.length||rows.some(x=>privateIp(x.address)))return null;return u.toString()}catch{return null}}
async function getFx(currency){if(currency==='CZK')return 1;const key=`ofx:${currency}`,hit=cache.get(key);if(hit&&Date.now()-hit.at<TTL)return hit.value;try{const r=await fetch(`${FX_URL}?from=${currency}&to=CZK`,{headers:{accept:'application/json'},signal:AbortSignal.timeout(5000)});if(!r.ok)throw new Error('fx');const j=await r.json(),v=Number(j?.rates?.CZK);if(!Number.isFinite(v))throw new Error('fx');cache.set(key,{at:Date.now(),value:v});return v}catch{return null}}
function priceMatches(text){const out=[],re=/(US\$|CA\$|AU\$|\$|€|£|CZK|Kč)\s*([0-9][0-9\s.,]*)/gi;let m;while((m=re.exec(text))){const value=num(m[2]);if(!value||value<5||value>200000)continue;const sym=m[1].toUpperCase(),currency=sym.includes('€')?'EUR':sym.includes('£')?'GBP':sym.includes('CZK')||sym.includes('KČ')?'CZK':'USD';out.push({currency,value})}return out}
async function lowestCzk(text){const vals=[];for(const p of priceMatches(text).slice(0,80)){const fx=await getFx(p.currency);if(fx)vals.push(Math.round(p.value*fx))}return vals.length?Math.min(...vals):null}
const LIMITED=[/limited availability/i,/limited tickets/i,/last tickets/i,/few tickets/i,/poslední vstupenky/i,/omezená dostupnost/i,/wenige tickets/i,/beperkt beschikbaar/i];
const SOLD=[/sold out/i,/currently unavailable/i,/no tickets available/i,/vyprod[aá]n(?:o|é)/i,/není k dispozici/i,/ausverkauft/i,/uitverkocht/i,/épuisé/i,/esaurito/i];
const AVAILABLE=[/buy tickets?/i,/purchase (?:your )?tickets?/i,/view tickets?/i,/buy now/i,/get tickets?/i,/select tickets?/i,/find tickets?/i,/koupit vstupenk(?:u|y)/i,/zakoupit vstupenk(?:u|y)/i,/vybrat vstupenky/i,/vstupenky (?:jsou )?v prodeji/i,/prodej vstupenek/i,/tickets available/i,/tickets on sale/i,/sale \/ reservation.*available/i,/in den warenkorb/i,/tickets kaufen/i,/bestel tickets/i];
export function classifyOfficialText(text){const t=clean(text);if(LIMITED.some(r=>r.test(t)))return{status:'LIMITED',label:'OMEZENĚ',confidence:'medium'};if(SOLD.some(r=>r.test(t)))return{status:'SOLD_OUT',label:'VYPRODÁNO',confidence:'medium'};if(AVAILABLE.some(r=>r.test(t)))return{status:'AVAILABLE',label:'DOSTUPNÉ',confidence:'medium'};return{status:'UNKNOWN',label:'NEJISTÉ',confidence:'low'}}
async function fetchOfficial(url){const hit=cache.get(url);if(hit&&Date.now()-hit.at<TTL)return hit.value;const r=await fetch(url,{redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36','accept':'text/html,application/xhtml+xml','accept-language':'cs-CZ,cs;q=0.9,en;q=0.8'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`Official HTTP ${r.status}`);const final=await safeOfficialUrl(r.url||url);if(!final)throw new Error('Official redirect blocked');const value={html:await r.text(),url:final};cache.set(url,{at:Date.now(),value});return value}
export async function scanOfficialMarket(url){const checkedAt=new Date().toISOString();if(!url)return{status:'NO_SOURCE',label:'NENÍ ZDROJ',lowestPriceCzk:null,sourceUrl:null,sourceName:null,confidence:'none',checkedAt};const safe=await safeOfficialUrl(url);if(!safe)return{status:'UNKNOWN',label:'NEJISTÉ',lowestPriceCzk:null,sourceUrl:null,sourceName:null,confidence:'low',checkedAt,message:'Oficiální URL není bezpečně dostupná.'};try{const page=await fetchOfficial(safe),text=textFromHtml(page.html),state=classifyOfficialText(text),price=await lowestCzk(text),host=new URL(page.url).hostname.replace(/^www\./,'');return{...state,lowestPriceCzk:price,sourceUrl:page.url,sourceName:host,checkedAt,message:state.status==='UNKNOWN'?'Stránku se podařilo načíst, ale dostupnost není jednoznačná.':null}}catch(e){return{status:'UNKNOWN',label:'NEJISTÉ',lowestPriceCzk:null,sourceUrl:safe,sourceName:new URL(safe).hostname.replace(/^www\./,''),confidence:'low',checkedAt,message:String(e?.message||e)}}}
