import {quoteSymbol32} from '../js/marketQuote32.js';
import {getBettingLedger543,mutateBettingLedger543} from '../lib/betting-ledger543-store.js';
import {decorateLedgerSelection,ledgerSummary} from '../lib/bet-ledger.js';
import {resolveAutoBettingModels} from '../lib/auto-betting-model.js';

const UA='Mozilla/5.0 (compatible; KamilOS/111; +https://kamil-os-smoke.vercel.app/)';
const ranges=new Set(['1mo','3mo','6mo','1y']);
const ODDS_BASE='https://api.odds-api.io/v3';
const ODDS_BOOKMAKER='Chance.cz';
const ODDS_CACHE_TTL=20*60*1000;
let oddsCache={at:0,key:'',payload:null};

function requestUrl(req){return new URL(String(req.url||'/api/market-history'),'https://kamil-os-smoke.vercel.app')}
function symbols(req){const u=requestUrl(req),out=[];for(const raw of String(u.searchParams.get('symbols')||'').split(',')){const s=quoteSymbol32(raw);if(s&&!out.includes(s))out.push(s);if(out.length>=16)break}return out}
async function one(symbol,range){const url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=${range}&interval=1d&includePrePost=false&events=div%2Csplits`;const r=await fetch(url,{headers:{'User-Agent':UA,'Accept':'application/json'}});if(!r.ok)throw new Error(`HISTORY ${r.status}`);const j=await r.json(),x=j?.chart?.result?.[0],ts=x?.timestamp||[],close=x?.indicators?.quote?.[0]?.close||[],points=[];for(let i=0;i<Math.min(ts.length,close.length);i++){const p=Number(close[i]);if(Number.isFinite(p)&&p>0)points.push({t:ts[i]*1000,p})}return{symbol,currency:x?.meta?.currency||'',points}}
async function readBody(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>100000)throw new Error('BODY_TOO_LARGE')}return raw?JSON.parse(raw):{}}
function isoDate(offset=0){const d=new Date(Date.now()+offset*86400000);return d.toISOString().slice(0,10)}
function norm(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\b(fc|cf|fk|sk|afc|sc|ac|club)\b/g,' ').replace(/[^a-z0-9]+/g,' ').trim()}
function scoreName(a,b){const x=norm(a),y=norm(b);if(!x||!y)return 0;if(x===y)return 1;if(x.includes(y)||y.includes(x))return .92;const xs=new Set(x.split(' ').filter(t=>t.length>2)),ys=new Set(y.split(' ').filter(t=>t.length>2));let hit=0;for(const t of xs)if(ys.has(t))hit++;return hit/Math.max(1,Math.max(xs.size,ys.size))}
async function fixturesForDate(date,key){const url=`https://v3.football.api-sports.io/fixtures?date=${encodeURIComponent(date)}&timezone=Europe%2FPrague`;const r=await fetch(url,{headers:{Accept:'application/json','x-apisports-key':key},cache:'no-store'});const j=await r.json().catch(()=>null);if(!r.ok)throw new Error(`API_FOOTBALL_${r.status}`);return Array.isArray(j?.response)?j.response:[]}
function compactFixture(x){return{fixtureId:x?.fixture?.id??null,date:x?.fixture?.date??null,status:x?.fixture?.status?.short??null,statusLong:x?.fixture?.status?.long??null,league:x?.league?.name??null,home:x?.teams?.home?.name??null,away:x?.teams?.away?.name??null,homeGoals:Number.isFinite(Number(x?.goals?.home))?Number(x.goals.home):null,awayGoals:Number.isFinite(Number(x?.goals?.away))?Number(x.goals.away):null}}
function matchBet(bet,fixtures){const home=bet?.home||String(bet?.event||'').split(/\s+(?:vs|v|–|-)\s+/i)[0]||'';const away=bet?.away||String(bet?.event||'').split(/\s+(?:vs|v|–|-)\s+/i)[1]||'';let best=null,bestScore=0;for(const fixture of fixtures){const direct=(scoreName(home,fixture.home)+scoreName(away,fixture.away))/2;const swapped=(scoreName(home,fixture.away)+scoreName(away,fixture.home))/2*.7;const s=Math.max(direct,swapped);if(s>bestScore){best=fixture;bestScore=s}}return bestScore>=.72?{fixture:best,confidence:Number(bestScore.toFixed(3))}:null}
async function bettingResults(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({ok:false,error:'METHOD_NOT_ALLOWED'});const key=String(process.env.API_FOOTBALL_KEY||process.env.API_SPORTS_KEY||'').trim();if(!key)return res.status(503).json({ok:false,error:'API_FOOTBALL_NOT_CONFIGURED'});let input={};try{input=await readBody(req)}catch{return res.status(400).json({ok:false,error:'BAD_BODY'})}const bets=(Array.isArray(input?.bets)?input.bets:[]).filter(b=>String(b?.status||'OPEN').toUpperCase()==='OPEN').slice(0,50);const dates=[0,-1,-2,-3].map(isoDate),all=[],errors=[];for(const date of dates){try{all.push(...(await fixturesForDate(date,key)).map(compactFixture))}catch(e){errors.push({date,error:String(e?.message||e)})}}const matches=bets.map(bet=>{const hit=matchBet(bet,all);return hit?{betId:bet.id,confidence:hit.confidence,fixture:hit.fixture}:null}).filter(Boolean);return res.status(200).json({ok:true,version:'544.0.0',provider:'API-Football',dates,fixturesChecked:all.length,matches,errors})}

function n(value){const x=Number(value);return Number.isFinite(x)?x:null}
function round(value,digits=4){if(!Number.isFinite(value))return null;const p=10**digits;return Math.round(value*p)/p}
function clampInt(value,fallback,min,max){const x=Number.parseInt(String(value??''),10);return Number.isFinite(x)?Math.min(max,Math.max(min,x)):fallback}
function oddsKey(){return String(process.env.ODDS_API_IO_KEY||process.env.ODDS_API_KEY||'').trim()}
function isHalfLine(value){const x=Number(value);return Number.isFinite(x)&&x>=0&&Math.abs(x*2-Math.round(x*2))<1e-8&&Math.abs(Math.round(x*2)%2)===1}
function isHalfHandicap(value){const x=Number(value);return Number.isFinite(x)&&Math.abs(x*2-Math.round(x*2))<1e-8&&Math.abs(Math.round(x*2)%2)===1}
function stableId(...parts){return `oa:${parts.map(x=>String(x??'').replace(/[^a-z0-9._-]+/gi,'_')).join(':')}`}
function periodOf(name){const s=String(name||'').toLowerCase();if(/1st half|first half|1\. half|1h|1\. polo/.test(s))return'FIRST_HALF';if(/2nd half|second half|2\. half|2h|2\. polo/.test(s))return'SECOND_HALF';return'FULL_TIME'}
function marketType(name){const s=String(name||'').toLowerCase();if(/moneyline|match result|1x2/.test(s))return'MATCH_RESULT';if(/both teams.*score|btts/.test(s))return'BOTH_TEAMS_TO_SCORE';if(/corner/.test(s)&&/total|over|under/.test(s))return'CORNER_OVER_UNDER';if(/yellow.*card|card.*total|cards/.test(s)&&/total|over|under/.test(s))return'YELLOW_CARD_OVER_UNDER';if(/home.*team.*total|home total/.test(s))return'HOME_OVER_UNDER';if(/away.*team.*total|away total/.test(s))return'AWAY_OVER_UNDER';if(/team total/.test(s))return'TEAM_TOTALS';if(/spread|handicap/.test(s))return'ASIAN_HANDICAP';if(/total|over.*under/.test(s))return'OVER_UNDER';return null}
function pushSelection(out,eventId,marketName,line,outcome,label,price){const odds=n(price);if(!(odds>1))return;out.push({selectionId:stableId(eventId,marketName,line,outcome,label),canonicalOutcome:outcome,rawName:label,line:n(line),odds})}
function normalizeMarket(eventId,raw,index){const name=String(raw?.name||raw?.market||'');const type=marketType(name);if(!type)return null;const period=periodOf(name),selections=[];for(const row of Array.isArray(raw?.odds)?raw.odds:[]){const line=row?.hdp??row?.line??row?.points??null;if(type==='MATCH_RESULT'){pushSelection(selections,eventId,name,line,'HOME','Domácí',row?.home);pushSelection(selections,eventId,name,line,'DRAW','Remíza',row?.draw);pushSelection(selections,eventId,name,line,'AWAY','Hosté',row?.away)}else if(type==='ASIAN_HANDICAP'){pushSelection(selections,eventId,name,line,'HOME',`Domácí ${line??''}`.trim(),row?.home);pushSelection(selections,eventId,name,line,'AWAY',`Hosté ${line??''}`.trim(),row?.away)}else if(type==='BOTH_TEAMS_TO_SCORE'){pushSelection(selections,eventId,name,line,'YES','Ano',row?.yes??row?.over);pushSelection(selections,eventId,name,line,'NO','Ne',row?.no??row?.under)}else{pushSelection(selections,eventId,name,line,'OVER',`Over ${line??''}`.trim(),row?.over);pushSelection(selections,eventId,name,line,'UNDER',`Under ${line??''}`.trim(),row?.under)}}if(!selections.length)return null;return{marketId:stableId(eventId,'m',index,name),canonicalMarket:type,rawName:name,period,line:selections[0]?.line??null,isActive:true,selections}}
function normalizeOddsEvent(raw){const id=raw?.id??raw?.eventId;const marketsRaw=raw?.bookmakers?.[ODDS_BOOKMAKER]||raw?.bookmakers?.Chance||raw?.bookmakers?.chance||[];const markets=(Array.isArray(marketsRaw)?marketsRaw:[]).map((m,i)=>normalizeMarket(id,m,i)).filter(Boolean);return{eventId:id,sport:raw?.sport?.slug||raw?.sport?.name||'football',league:raw?.league?.name||raw?.league||null,home:raw?.home||null,away:raw?.away||null,startTime:raw?.date||raw?.startTime||null,live:String(raw?.status||'').toLowerCase()==='live',markets}}
function modelable(market,selection){if(String(market?.period||'').toUpperCase()!=='FULL_TIME')return false;const type=String(market?.canonicalMarket||'').toUpperCase(),outcome=String(selection?.canonicalOutcome||'').toUpperCase(),line=selection?.line??market?.line;if(type==='MATCH_RESULT')return['HOME','DRAW','AWAY'].includes(outcome);if(type==='BOTH_TEAMS_TO_SCORE')return['YES','NO'].includes(outcome);if(['OVER_UNDER','HOME_OVER_UNDER','AWAY_OVER_UNDER','CORNER_OVER_UNDER','YELLOW_CARD_OVER_UNDER'].includes(type))return['OVER','UNDER'].includes(outcome)&&isHalfLine(line);if(type==='ASIAN_HANDICAP')return['HOME','AWAY'].includes(outcome)&&isHalfHandicap(line);return false}
function decorateValue(events,autoModel,minEv,minEdgePp){const probs=new Map(autoModel?.probabilities||[]),sources=new Map(autoModel?.sources||[]);return events.map(event=>({...event,markets:(event.markets||[]).map(market=>({...market,selections:(market.selections||[]).map(selection=>{const p=probs.get(String(selection.selectionId))??null,implied=1/selection.odds,fair=p?1/p:null,edge=p===null?null:(p-implied)*100,ev=p===null?null:p*selection.odds-1,decision=p!==null&&ev>=minEv&&edge>=minEdgePp?'BET':p===null?'WAITING_FOR_MODEL':'NO_BET';const withValue={...selection,id:selection.selectionId,name:selection.rawName,outcome:selection.canonicalOutcome,impliedProbability:round(implied,4),modelProbability:p===null?null:round(p,4),fairOdds:fair===null?null:round(fair,3),edgePctPoints:edge===null?null:round(edge,2),ev:ev===null?null:round(ev,4),evPct:ev===null?null:round(ev*100,2),decision,modelSource:p===null?null:(sources.get(String(selection.selectionId))||autoModel?.meta?.provider||'automatic')};return decorateLedgerSelection(event,{...market,id:market.marketId,type:market.canonicalMarket,name:market.rawName},withValue)})}))}))}
async function oddsGet(path,key){const sep=path.includes('?')?'&':'?';const r=await fetch(`${ODDS_BASE}${path}${sep}apiKey=${encodeURIComponent(key)}`,{headers:{Accept:'application/json','User-Agent':UA},cache:'no-store'});const text=await r.text();let payload=null;try{payload=JSON.parse(text)}catch{payload={raw:text.slice(0,1200)}}if(!r.ok){const error=new Error(`ODDS_API_${r.status}`);error.status=r.status;error.payload=payload;throw error}return payload}
async function loadChanceOdds(days){const key=oddsKey();if(!key){const error=new Error('ODDS_API_IO_NOT_CONFIGURED');error.status=503;throw error}const cacheKey=`${days}`;if(oddsCache.payload&&oddsCache.key===cacheKey&&Date.now()-oddsCache.at<ODDS_CACHE_TTL)return{...oddsCache.payload,cache:true};const now=Date.now(),until=now+days*86400000;const eventPayload=await oddsGet(`/events?sport=football&status=pending&limit=100&bookmaker=${encodeURIComponent(ODDS_BOOKMAKER)}`,key);const discovered=(Array.isArray(eventPayload)?eventPayload:Array.isArray(eventPayload?.data)?eventPayload.data:Array.isArray(eventPayload?.events)?eventPayload.events:[]).filter(x=>{const t=Date.parse(x?.date||x?.startTime||'');return Number.isFinite(t)&&t>now&&t<=until}).slice(0,60);const batches=[];for(let i=0;i<discovered.length;i+=10)batches.push(discovered.slice(i,i+10));const detailed=[];for(const batch of batches){const ids=batch.map(x=>x?.id).filter(Boolean).join(',');if(!ids)continue;const p=await oddsGet(`/odds/multi?eventIds=${encodeURIComponent(ids)}&bookmakers=${encodeURIComponent(ODDS_BOOKMAKER)}`,key);detailed.push(...(Array.isArray(p)?p:Array.isArray(p?.data)?p.data:[]))}const events=detailed.map(normalizeOddsEvent).filter(e=>e.eventId&&e.markets.length);const payload={events,rawCount:discovered.length,requests:1+batches.length,cache:false};oddsCache={at:Date.now(),key:cacheKey,payload};return payload}
async function chanceOddsHealth(req,res){if(req.method!=='GET')return res.status(405).json({ok:false,error:'METHOD_NOT_ALLOWED'});const configured=!!oddsKey();return res.status(200).json({ok:true,version:'693.0.0',provider:'odds-api.io',bookmaker:ODDS_BOOKMAKER,configured,ready:configured,cacheTtlMinutes:ODDS_CACHE_TTL/60000,freeTierDesign:'scanner batches up to 10 events per odds request'})}
async function chanceOddsPages(req,res,u){if(req.method!=='GET')return res.status(405).json({ok:false,error:'METHOD_NOT_ALLOWED'});const days=clampInt(u.searchParams.get('days'),5,1,14);try{const loaded=await loadChanceOdds(days);const leagues=[...new Set(loaded.events.map(e=>e.league).filter(Boolean))].sort();return res.status(200).json({ok:true,version:'693.0.0',provider:'odds-api.io',bookmaker:ODDS_BOOKMAKER,mode:'page-discovery',days,totalPages:1,scannedPages:1,relevantPages:loaded.events.length?1:0,pages:loaded.events.length?[{page:1,supportedEvents:loaded.events.length,leagues}]:[],requests:loaded.requests,cache:loaded.cache,fetchedAt:new Date().toISOString()})}catch(error){const status=error?.status||502;return res.status(status).json({ok:false,error:String(error?.message||'ODDS_API_IO_FAILED'),status,details:error?.payload||null})}}
async function chanceOddsScan(req,res,u){if(req.method!=='GET')return res.status(405).json({ok:false,error:'METHOD_NOT_ALLOWED'});const days=clampInt(u.searchParams.get('days'),5,1,14),minEv=Number(u.searchParams.get('minEv')||0.05),minEdgePp=Number(u.searchParams.get('minEdgePp')||4);try{const loaded=await loadChanceOdds(days);const candidates=loaded.events.filter(event=>event.markets.some(m=>m.selections.some(s=>modelable(m,s))));const autoModel=await resolveAutoBettingModels(candidates,{apiFootballKey:process.env.API_FOOTBALL_KEY||process.env.API_SPORTS_KEY||'',apiFootballLimit:clampInt(u.searchParams.get('autoModelLimit'),3,1,10),poissonLimit:clampInt(u.searchParams.get('poissonLimit'),15,1,30)});let events=decorateValue(loaded.events,autoModel,minEv,minEdgePp);if(u.searchParams.get('betsOnly')==='1')events=events.map(e=>({...e,markets:e.markets.map(m=>({...m,selections:m.selections.filter(s=>s.decision==='BET'&&!s.existingBet)})).filter(m=>m.selections.length)})).filter(e=>e.markets.length);return res.status(200).json({ok:true,version:'693.0.0',provider:'odds-api.io',bookmaker:ODDS_BOOKMAKER,sport:'soccer',mode:'prematch',fetchedAt:new Date().toISOString(),strictFutureFilter:true,page:1,limit:loaded.rawCount,total:loaded.rawCount,totalPages:1,hasNextPage:false,rawCount:loaded.rawCount,eventCount:events.length,requests:loaded.requests,cache:loaded.cache,ledger:ledgerSummary(),value:{minEv,minEvPct:round(minEv*100,2),minEdgePp,betsOnly:u.searchParams.get('betsOnly')==='1',automaticModelProbabilities:autoModel?.probabilities?.size||0,modelProvider:autoModel?.meta?.provider||'automatic',autoModel:autoModel?.meta||{}},events})}catch(error){const status=error?.status||502;return res.status(status).json({ok:false,error:String(error?.message||'ODDS_API_IO_FAILED'),status,details:error?.payload||null})}}

export default async function handler(req,res){
 const u=requestUrl(req),source=String(u.searchParams.get('source')||'').toLowerCase();
 res.setHeader('Content-Type','application/json; charset=utf-8');
 if(source==='ledger543'){
  res.setHeader('Cache-Control','no-store');
  if(req.method==='GET')return res.status(200).json(await getBettingLedger543());
  if(req.method==='POST'||req.method==='PUT'){try{const result=await mutateBettingLedger543(await readBody(req));return res.status(result.status).json(result.body)}catch(error){return res.status(500).json({ok:false,error:'LEDGER_543_FAILED',message:String(error?.message||error)})}}
  res.setHeader('Allow','GET, POST, PUT');return res.status(405).json({ok:false,error:'METHOD_NOT_ALLOWED'});
 }
 if(source==='bet_results')return bettingResults(req,res);
 if(source==='chance_odds_health693')return chanceOddsHealth(req,res);
 if(source==='chance_odds_pages693')return chanceOddsPages(req,res,u);
 if(source==='chance_odds693')return chanceOddsScan(req,res,u);
 res.setHeader('Cache-Control','public, s-maxage=600, stale-while-revalidate=1800');
 if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).json({ok:false,error:'METHOD_NOT_ALLOWED'})}
 const ss=symbols(req),range=ranges.has(u.searchParams.get('range'))?u.searchParams.get('range'):'1mo';
 if(!ss.length)return res.status(400).json({ok:false,error:'NO_SYMBOLS'});
 const series=[],errors=[];
 for(const s of ss){try{series.push(await one(s,range))}catch(e){errors.push({symbol:s,error:String(e?.message||e).slice(0,80)})}}
 return res.status(series.length?200:502).json({ok:series.length>0,provider:'Yahoo Finance chart',range,fetchedAt:new Date().toISOString(),series,errors});
}
