const TTL=20*60*1000;
const cache=globalThis.__KAMIL_STUBHUB_CACHE__||(globalThis.__KAMIL_STUBHUB_CACHE__=new Map());
const FX_URL='https://api.frankfurter.app/latest';
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const num=s=>{let x=String(s||'').replace(/\s/g,'').replace(/[^0-9.,]/g,'');if(!x)return null;const c=x.lastIndexOf(','),d=x.lastIndexOf('.');if(c>d)x=x.replace(/\./g,'').replace(',','.');else x=x.replace(/,/g,'');const n=Number(x);return Number.isFinite(n)?n:null};
const currency=s=>{const x=String(s||'').toUpperCase();if(x.includes('€')||x==='EUR')return'EUR';if(x.includes('£')||x==='GBP')return'GBP';if(x.includes('CZK')||x.includes('KČ'))return'CZK';if(x.includes('$')||x==='USD')return'USD';return null};
function prices(text){const out=[],s=String(text||''),patterns=[/(US\$|\$|€|£|CZK|Kč)\s*([0-9][0-9\s.,]*)/gi,/([0-9][0-9\s.,]*)\s*(CZK|Kč|EUR|€|GBP|£|USD)/gi];for(const re of patterns){let m;while((m=re.exec(s))){const v=num(m[2]||m[1]),c=currency(m[1]&&m[2]?m[1]:m[2]);if(v&&v>=5&&v<=200000&&c)out.push({value:v,currency:c})}}return out}
async function fx(c){if(c==='CZK')return 1;const k='fx:'+c,h=cache.get(k);if(h&&Date.now()-h.at<TTL)return h.v;try{const r=await fetch(`${FX_URL}?from=${c}&to=CZK`,{signal:AbortSignal.timeout(5000)}),j=await r.json(),v=Number(j?.rates?.CZK);if(v){cache.set(k,{at:Date.now(),v});return v}}catch{}return null}
async function toCzk(ps){const a=[];for(const p of ps){const r=await fx(p.currency);if(r)a.push(Math.round(p.value*r))}return a.sort((a,b)=>a-b)}
const norm=s=>clean(String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' '));
async function page(url){const h=cache.get(url);if(h&&Date.now()-h.at<TTL)return h.v;const r=await fetch(url,{redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36','accept':'text/html,application/xhtml+xml','accept-language':'en-US,en;q=0.9'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error('StubHub HTTP '+r.status);const v={html:await r.text(),url:r.url||url};cache.set(url,{at:Date.now(),v});return v}
function links(html){const out=[],seen=new Set();let m;const re=/href=["']([^"']+)["']/gi;while((m=re.exec(String(html||'')))){try{const u=new URL(m[1],'https://www.stubhub.com');if(!/(^|\.)stubhub\.com$/i.test(u.hostname)||!/event|tickets/i.test(u.pathname))continue;u.search='';u.hash='';const s=u.toString();if(!seen.has(s)){seen.add(s);out.push(s)}}catch{}}return out}
function score(text,item){const q=norm(item.event||item.label),t=norm(text),tokens=q.split(' ').filter(x=>x.length>2),matched=tokens.filter(x=>t.includes(x)).length;let s=matched*2;if(q&&t.includes(q))s+=5;const date=String(item.date||'').slice(0,10);if(date&&t.includes(date.slice(0,4)))s+=2;return{s,matched,total:tokens.length}}
async function scan(item){const q=clean(item.event||item.label);if(!q)return{status:'missing',message:'Chybí název akce.'};try{const search=await page(`https://www.stubhub.com/secure/search?q=${encodeURIComponent(q)}`),candidates=links(search.html).slice(0,12);let best=null;for(const url of candidates){try{const p=await page(url),sc=score(p.html,item);if(!best||sc.s>best.s)best={...sc,url:p.url,html:p.html}}catch{}}if(!best||best.matched<Math.min(2,Math.max(1,best.total)))return{status:'not_found',message:'StubHub akce nenalezena.'};const czk=await toCzk(prices(best.html));if(!czk.length)return{status:'no_price',url:best.url,message:'StubHub akce nalezena, ale cenu nelze spolehlivě přečíst.'};const section=norm(item.section),sectionPrices=section?await toCzk(prices(best.html.split(new RegExp(section,'i')).slice(0,4).join(' '))):[];const use=sectionPrices.length?sectionPrices:czk;return{status:'ok',url:best.url,marketPriceCzk:use[0],medianPriceCzk:use[Math.floor(use.length/2)],topPricesCzk:use.slice(0,5),confidence:sectionPrices.length?'stubhub-section':'stubhub-event-floor',sameSection:!!sectionPrices}}
catch(e){return{status:'error',message:e.message||'StubHub scan selhal.'}}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method==='GET'){const q=clean(req.query?.q||'');if(!q)return res.status(200).json({ok:true,source:'stubhub',diagnostic:true,usage:'?q=EVENT&date=YYYY-MM-DD&section=SECTION'});const result=await scan({id:'diagnostic',event:q,label:q,date:req.query?.date||null,section:req.query?.section||null});return res.status(200).json({ok:true,source:'stubhub',diagnostic:true,checkedAt:new Date().toISOString(),result})}if(req.method!=='POST')return res.status(405).json({ok:false,error:'Method not allowed'});const items=Array.isArray(req.body?.items)?req.body.items.slice(0,30):[];const results=[];for(const item of items)results.push({id:item.id,...await scan(item)});return res.status(200).json({ok:true,source:'stubhub',checkedAt:new Date().toISOString(),results})}
